### ISSUE TITLE
Proxy / VPN error reports

### ISSUE THREAD

**Issue by mchiang0610** [docker/kitematic#1031]

**Comment by FugDev** [comment]
On windows my solution is following:

create a windows batch script "C:\Program Files\Docker Toolbox\kitematic_proxy.cmd" and insert following script and replace "YOUR_PROXY" with the http://host:port of your proxy

set proxy=YOUR_PROXY
SET HTTP_PROXY=%proxy%
SET HTTPS_PROXY=%proxy%
for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
SET NO_PROXY=%DOCKER_HOST%
set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
cd Kitematic
Kitematic.exe

**Comment by stritti** [comment]
Thanks @FugDev ! Your cmd-file is workeing for me, too.

**Comment by dirkluijk** [comment]
Same issue here. As far as I know, we are not using a corporate proxy (so I don't know a proxy server address), but there is a root certificate "injected" somewhere. I want to mark the certificate as trusted.

![image](https://cloud.githubusercontent.com/assets/2102973/10518138/4c79a412-7360-11e5-85bb-96f663ad9fc2.png)

**Comment by Akhena** [comment]
I am also trying to find a way to make the certificate of our proxy trusted by Kitematic. Maybe in a future release?

**Comment by manojsh1984** [comment]
![image](https://cloud.githubusercontent.com/assets/15664731/11142106/f485fdf6-8a10-11e5-86cb-fd03ed647cea.png)
 getting error any solution

**Comment by zivc** [comment]
![image](https://cloud.githubusercontent.com/assets/4239224/12397161/57f375a0-be03-11e5-8e6a-15fb55f5c582.png)
 
```$ env
HTTPS_PROXY=http://10.244.161.20:3128
HTTP_PROXY=http://10.244.161.20:3128```

**Comment by FrenchBen** [comment]
@zivc Please see how to properly set this up by following the Wiki info:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by BecauseofLxcCheckpoint** [comment]
@Akhena ，hi，I have meet the same issue with you, how do you solve the problem finally?

**Comment by BecauseofLxcCheckpoint** [comment]
@Akhena @zivc ，hi，I have meet the same issue with you, how do you solve the problem finally?

**Comment by Akhena** [comment]
@BecauseofLxcCheckpoint Unfortunately (because of this issue) I don't use kitematic anymore in my professional environment

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.

**Comment by patdohere** [comment]
+1 that I'm having this issue on OS X

**Comment by mchiang0610** [comment]
@patdohere is this with Docker for Mac beta as well?

**Comment by patdohere** [comment]
Yes this is Docker for Mac.  Only with Kitematic when I'm behind a VPN.

**Comment by FrenchBen** [comment]
@patdohere We release Kitematic v0.10.2 today which includes a few fixes. Can you check if that fixed your problem?

**Comment by patdohere** [comment]
Seems to be fixed on my end 👍
