### ISSUE TITLE
how to set up hostname for a new container in Kitematic

### ISSUE THREAD

**Issue by wzymaster** [docker/kitematic#1088]
I want to set up hostname for a new container while pulling an image within Kitematic. 

Is there any approach to achieve that goal ? I can't find any place to do that. 
Please advise it .

**Comment by FrenchBen** [comment]
This is currently not implemented.

**Comment by leo-from-spb** [comment]
+1 for allowing to specify hostname

**Comment by FrenchBen** [comment]
@leo-from-spb The api supports hostname, If you'd like to add it to Kitematic, then we'd be happy to merge the PR once done.
