### ISSUE TITLE
setting proxy is not easy in kitematic

### ISSUE THREAD

**Issue by ndevireddy** [docker/kitematic#1103]
There is no easy way to set the proxy from kitematic, so when you are behind a proxy, login will never succeed.

**Comment by Juchar** [comment]
I have to admit that from my point of view this is a major downfall that subverts the whole intention of a easy on the go installation using the Docker-Toolsuite, as proxies are most commonly used at each and every company with a decent IT-infrastructure.

I would expect to be asked for the proxy settings during the first launch of kitematic - at the point it creates the first machine - (server + credentials) and not having to care about setting those afterwards inside the vm (windows) or as separate path variables for kitematic itself.

**Comment by FrenchBen** [comment]
@ndevireddy @Juchar Setting up a proxy in Kitematic has been detailed in the wiki:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#proxy-issues

Adding the proxy to Kitematic is a good idea, but unfortunately it also needs to be added within the VM - Perhaps this could be part of the Docker Toolbox setup rather than Kitematic.

**Comment by ndevireddy** [comment]
@FrenchBen  Thanks for sharing the workarounds. The main issue here is, Kitematic will not let you to login to your docker hub account after installation when you are behind a proxy.  By allowing the proxy settings ( or read it from network settings - if you do not want users to enter ) life will become much easier.

**Comment by FrenchBen** [comment]
@ndevireddy Kitematic should allow you to login behind a proxy as it makes a regular https request to the Hub. 
What we've seen in the past, is that the certificate is modified by the proxy, faking an insecure connection. If you go to https://hub.docker.com/ do you see any ssl error? Can you take a screenshot of the SSL connection details?

**Comment by ndevireddy** [comment]
@FrenchBen  Thanks and sorry for the delayed reply. https://hub.docker.com is not throwing any ssl error.  When I try launching kitematic, it goes till 99% and hangs there for a while, and then prompts for login, but when we enter the credentials, it just wont take and returns to login page. I tested the same without proxy and that just works fine.

**Comment by ndevireddy** [comment]
![docker error](https://cloud.githubusercontent.com/assets/15027925/10535234/a7767810-73fe-11e5-89fe-c7ed402ee537.jpg)
![docker error2](https://cloud.githubusercontent.com/assets/15027925/10535243/b26737aa-73fe-11e5-8e50-b7985b9b9017.jpg)

**Comment by FrenchBen** [comment]
Did you try the guide for to ensure that your VM had the proper proxy settings; since it seems that the issue happens when you are behind a proxy? 
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#proxy-issues

**Comment by fuzzball5000** [comment]
+1. It's the Kitematic.exe process which is attempting a direct TLS connection to hub.docker.com and ignoring the system proxy settings. The ability to define a proxy variable within the Kitematic GUI prior to attempting the Docker Hub connection would be much appreciated. The ability to then cascade the set variable down into the VM would be nice, but is not essential.

**Comment by FrenchBen** [comment]
@fuzzball5000 Unfortunately as you see in the Wiki, it's not just in the Gui that this needs to happen but within the OS running inside the VM. Making changes to the VM within Kitematic isn't supported; vbox doesn't even give you a chance to 'inject' env vars into the VM OS

**Comment by FrenchBen** [comment]
Docker for Mac/Windows do solve a lot of the proxy issues - The wiki is still your best friend if you need to run Virtualbox.
