### ISSUE TITLE
I would like to copy & paste text from interface

### ISSUE THREAD

**Issue by sirkkalap** [docker/kitematic#1186]
However for some reason this is not supported.

For example I would like to copy & paste the Access Url in the below image.
![screenshot 2015-11-05 20 06 45](https://cloud.githubusercontent.com/assets/703699/10977285/d0a4ed20-83f8-11e5-87d9-a663b889cf17.png)

**Comment by sirkkalap** [comment]
As a workaround I removed the webkit-user-select: none style from body.

![screenshot 2015-11-05 20 21 59](https://cloud.githubusercontent.com/assets/703699/10977662/08679990-83fb-11e5-9bdc-01476bc49fa9.png)

**Comment by FrenchBen** [comment]
Seems like a simple feature request - You can usually capture these within the Settings > Ports tab

**Comment by ClemMakesApps** [comment]
Is this still a feature request or is this issue resolved with PR #1201 ?

**Comment by FrenchBen** [comment]
@ClemMakesApps Thanks for digging this up - I'll close the issue, as it was fixed by #1201 as you mentioned. 
Thanks!
