### ISSUE TITLE
Add exposed ports using the GUI - Feature Request

### ISSUE THREAD

**Issue by alexandrev** [docker/kitematic#1206]
Today I notice I can not only change the port number of the local side but the protocol too. I can change from a XXXX TCP port to a XXXX UDP port, but I cannot add a new port. 

It doesn't seem more difficult to change the current port mapping than add the port protocol in the current ones. 

Could be posible to add these as a new feature form the app?

**Comment by FrenchBen** [comment]
Totally! The latest changes should allow you to pass a new object with all ports in them and thus push some new ports to a container that previously didn't have them open/available

**Comment by alexandrev** [comment]
I'm glad to hear that. But yesterday I tried the master version but I don't
find the option you commented. How can I test that feature?

-- Sent from my mobile phone. Please excuse any typo.

**Comment by FrenchBen** [comment]
I meant to say that you can implement it if you like. 

If you look at: https://github.com/kitematic/kitematic/blob/master/src/components/ContainerSettingsPorts.react.js#L79 You will see that any port in the  `this.state.ports` object  will be passed back to the container and thus will have it open.

**Comment by alexandrev** [comment]
Ok, i'll work on that!

-- Sent from my mobile phone. Please excuse any typo.
