### ISSUE TITLE
Feature Request: Using internal docker host

### ISSUE THREAD

**Issue by alexandrev** [docker/kitematic#1226]
With the new advances inside the docker development specifically on Windows platforms where we expect to have a native daemon running on Windows (at least on Windows Server 2016). I think we should start working about a posiblity to support a native docker host not only the one running inside the VirtualBox.

What do you think about this feature?

**Comment by FrenchBen** [comment]
@alexandrev The changes should be pretty straight-forward, since we can check for a native docker daemon and install virtualbox as needed. 
Do you have a link to the Windows Server specific docker daemon? I don't think I saw any details of the integration.

**Comment by alexandrev** [comment]
Hi @FrenchBen, I'd like your approach and I think it could be great not only for the Windows version but for the Linux port another mates are working on. About the details you are asking for, I have to admit there is not too much information about it. They said that the code will be the same the one we have in the docker GitHub repo (you can take a look that few of the latests code are about windows modifications), you can take a look at this link but I'm sure you already know about it. (https://blog.docker.com/2015/08/tp-docker-engine-windows-server-2016/) 

And the people from Microsoft these days have been showing the docker daemon implementation inside the Windows Server 2016 on the DockerConEU.

**Comment by FrenchBen** [comment]
Since the Linux port has been merged we can re-visit this when the windows server is more readily available. Closing for now.
