### ISSUE TITLE
Network configuration

### ISSUE THREAD

**Issue by asbjornu** [docker/kitematic#1233]
It would be awesome if Kitematic could help configure the network of all the involved moving parts so connecting to a given docker image from i.e. a VMware instance running Windows on the host (OS X in my case). I have absolutely no idea how to set up this without Kitematic, but I assume running the docker image with [`--net="host"`](https://docs.docker.com/v1.8/articles/networking/#how-docker-networks-a-container) is necessary, as well as configuring the VirtualBox VM to run in bridged mode. I have no idea, though, since I'm both network illiterate and a Docker noob.

Since Kitematic successfully abstracts most of the underlying complexities of both networking and Docker, having this sort of functionality would be incredibly powerful and useful. At least to me. Thanks! :smile:

**Comment by FrenchBen** [comment]
@asbjornu With the new Docker network now pushed in 1.9, this is something that's been discussed. 
We're still trying to come up with the proper way of adding the network, connecting to it and perhaps connecting networks.

We've considered adding the network as part of the overall preference panel, then on each container allow the selection of a network. (connecting 2 networks would need to be done manually)

What do you think of the above?

**Comment by asbjornu** [comment]
@FrenchBen That sounds great! As long as I don't have to figure out subnet masks, routing and what `docker` command line arguments to pass, I'm a very happy camper! :+1:

**Comment by FrenchBen** [comment]
Closing in favor of the Feature proposal. Please keep all discussion there.
https://github.com/docker/kitematic/issues/1249
