### ISSUE TITLE
Error while pulling image: Get https://index.docker.io/v1/repositories/library/redis/images: dial tcp: lookup index.docker.io: no such host

### ISSUE THREAD

**Issue by tubbo** [docker/kitematic#1238]
Getting an error whenever I attempt to pull from the Docker registry with either docker-compose or Kitematic...not sure where it's coming from.

**Comment by alexandrev** [comment]
Ok, in the information you are providing seems that you have problems to establish a connection with your docker host inside the Virtualbox. Are you behind some kind of firewall or proxy? If this is your case, you can take a look at https://github.com/kitematic/kitematic/wiki/Common-Proxy-Issues-&-Fixes . Please, come back to us if it that's not helping you to solve your issue.

**Comment by tubbo** [comment]
That's probably true, but this is a plain install of VirtualBox and a
fresh install of Docker Toolbox. As far as I know, I'm not behind any
kind of proxy. I'll give this a shot on another machine on another
connection and see how it goes.

On 11/23, Alexandre Vazquez wrote:
> Ok, in the information you are providing seems that you have problems to establish a connection with your docker host inside the Virtualbox. Are you behind some kind of firewall or proxy? If this is your case, you can take a look at https://github.com/kitematic/kitematic/wiki/Common-Proxy-Issues-&-Fixes . Please, come back to us if it that's not helping you to solve your issue.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kitematic/kitematic/issues/1238#issuecomment-158955637

-- 
- T

**Comment by tubbo** [comment]
Hey guys, it looks like I had multiple installations of Docker on the same machine. Got it all resolved. Thanks for the rubber ducking!
