### ISSUE TITLE
Container cannot be removed from Kitematic

### ISSUE THREAD

**Issue by janiemort** [docker/kitematic#1246]
I tried stopping and removing a container and got the following error:

no such container
404
no such id: big_tesla

How do I get rid of it?

Thanks,

Jane

**Comment by FrenchBen** [comment]
Can you provide the output of the following command:
`docker $(docker-machine config default) ps -a`

**Comment by janiemort** [comment]
Janes-Mac-mini:Documents janiemort$ docker $(docker-machine config default) ps -a
CONTAINER ID        IMAGE                    COMMAND                 CREATED             STATUS              PORTS                                                                                         NAMES
3c6623d83b65        oracle/weblogic:12.2.1   "createServer.sh"       4 hours ago         Up 4 hours          5556/tcp, 7001/tcp, 8001/tcp                                                                  desperate_cori
5e1311e02479        oracle/weblogic:12.2.1   "createMachine.sh"      4 hours ago         Up 4 hours          5556/tcp, 7001/tcp, 8001/tcp                                                                  backstabbing_wright
993e7822ab2f        oracle/weblogic:12.2.1   "startNodeManager.sh"   4 hours ago         Up 4 hours          5556/tcp, 7001/tcp, 8001/tcp                                                                  wlsnm0
275a2ccb862a        oracle/weblogic:12.2.1   "startWebLogic.sh"      4 hours ago         Up 4 hours          192.168.99.100:5556->5556/tcp, 192.168.99.100:7001->7001/tcp, 192.168.99.100:8001->8001/tcp   wlsadmin

**Comment by janiemort** [comment]
Sorry I did

**Comment by janiemort** [comment]
Sorry I didn't mean to close.

**Comment by FrenchBen** [comment]
@janiemort From the list of container you provided I don't see 'big_tesla' - Perhaps you just need to close Kitematic and re-open it?

**Comment by janiemort** [comment]
Hmmm, I did that yesterday, but today it is gone. Thanks. I am good now.

**Comment by FrenchBen** [comment]
Good to hear - Closing the issue
