### ISSUE TITLE
Feature proposal: Add Networking to containers

### ISSUE THREAD

**Issue by FrenchBen** [docker/kitematic#1249]
This proposal would keep networking to a minimal for now, but with a big impact.
The idea is as follow:
- [ ] Enable network support within Kitematic Preferences (this adds a new 'kitematic' networ)
- [ ] Add network to containers (with networking enabled, this would show the network that the container can attach to)

Keep in mind that the above is a rough draft and comments are welcome as to how users would like this to work. 
I would like to keep this as a small feature for now which can then grow later on.  Adding the default 'kitematic' network would allow for all things to talk to each other on a common network.

**Comment by klousiaj** [comment]
:+1:

**Comment by abacon** [comment]
I'd love to see this! :+1:

**Comment by ToniIltanen** [comment]
any progress in this?

**Comment by FrenchBen** [comment]
@ToniIltanen If you'd like to own the implementation, please do so :)
