### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by rjsicko** [docker/kitematic#1251]
"tunneling socket could not be established, cause=Parse Error"
I get this error when trying to connect to the dockerhub in kitematic... Possibly related to my network using "identity agent"?

**Comment by FrenchBen** [comment]
Are

**Comment by rjsicko** [comment]
Unfortunately they did away with the proxy when identity agent software was implemented... The new system is a check point software that I don't  fully  understand,  but their site says it allows users to "acquire and report identities to the Security Gateway" 

I use other virtual boxes and when this was implemented I had to remove all the proxy  info from them and I believe they  just connect through  my regular connection as long as I am logged into the identity agent.

**Comment by FrenchBen** [comment]
Do you have a link to the software?

**Comment by rjsicko** [comment]
http://www.checkpoint.com/products/identity-awareness-software-blade/index.html

**Comment by FrenchBen** [comment]
unfortunately you may need to get more information from your admin on getting the VM connected/allowed to the internet, as it's outside the scope of kitematic.
