### ISSUE TITLE
Starting Jenkins via Kitematic doesn't work

### ISSUE THREAD

**Issue by ilkka** [docker/kitematic#1254]
For some reason when starting through Kitematic, the official jenkins image produces a running container, with port mappings and all set up, but no Jenkins process. Starting through normal Docker CLI means works just fine.

**Comment by FrenchBen** [comment]
Can you share the command you're running via the CLI?

**Comment by ilkka** [comment]
Sure:

```
$ docker run -d -p 8080 -p 50000 jenkins
```

**Comment by FrenchBen** [comment]
That is weird - I don't think we do anything different, but it seems that the CMD is ran, yet the java process is never started. 

I'll see if I can pin-point it. Thanks for the issue.

**Comment by stoumpos** [comment]
Don't know if it is related, but when you start the container from the CLI, the entrypoint is  "/bin/tini -- /usr/local/bin/jenkins.sh"; from kitematic, the entry point is "/bin/tini -- /usr/local/bin/jenkins.sh bash".

**Comment by FrenchBen** [comment]
Yup I think you've nailed it. The extra bash prevents it from running the jenkins, as the script has the followin:
```
# As argument is not jenkins, assume user want to run his own process, for sample a `bash` shell to explore this image
exec "$@"
```
I'll checkout your PR, but on first glance it seems like the proper fix. Thanks :+1:

**Comment by ctran** [comment]
Any update on this?

**Comment by FrenchBen** [comment]
@ctran we actually pushed a similar fix within the latest cut of Kitematic. 
https://github.com/docker/kitematic/blob/master/src/utils/DockerUtil.js#L129

Checkout the latest Docker Toolbox to get the latest version.

**Comment by ctran** [comment]
Sweet!!!!
