### ISSUE TITLE
Cannot stop container

### ISSUE THREAD

**Issue by abdullahahad-tradedoubler** [docker/kitematic#1255]
Sometimes it cannot stop container when I want to close it from Kitematic. gives the ,message no such container
404
no such id: tender_pike

**Comment by FrenchBen** [comment]
I believe this happens when a container died after an update. If you get a container error, you will not be able to remove it, as it was not actually created. 

Can you provide the steps taken to reproduce this issue?

**Comment by FrenchBen** [comment]
No feedback in more than week - Closing
