### ISSUE TITLE
Unable to delete Containers

### ISSUE THREAD

**Issue by packet-rat** [docker/kitematic#1258]
MAC OSX 10.10.5
Kinematic 0.7.6

Unable to Delete (***any***) Containers from Kinematic  UI

server error
500
Cannot kill container mysql: notrunning: Container 9f7af77b73ced51b304ca3ab99945c66ccae5cc0c8d1071c166674e5497ab634 is not running

**Comment by FrenchBen** [comment]
Please update to the latest tools, although this is a known issue when a container dies.
