### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by GasCreature** [docker/kitematic#1261]
On Mac OS/X El Capitan, after installing the Docker Toolkit and launching the Docker CLI, it apparently created the VM successfully, but neither docker-machine nor docker can run successfully. For example, "docker info" just returns "Cannot connect to the Docker daemon." Running "docker-machine env default" returns "Error running connection boilerplate: Error getting driver URL: Something went wrong running an SSH command!"

**Comment by zakum1** [comment]
You should always run the docker commands from a shell created using Application/Docker Quickstart Terminal, because it sets up the required environment variables.
Or you can set these in your .bash_profile:
export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_MACHINE_NAME=default
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/Users/james/.docker/machine/machines/default

**Comment by GasCreature** [comment]
There's something wrong with the Docker Quickstart. That's the point of my
post. I can run it manually with the following from Terminal:

docker-machine create --driver virtualbox DockerBox
text=` docker-machine env DockerBox `
eval $text
docker-machine ssh DockerBox

**Comment by FrenchBen** [comment]
@GasCreature Can you provide some background information on perhaps previous docker installations?
Can you share the version of your tools?
`docker-machine --version`
`docker version`

**Comment by GasCreature** [comment]
I did not have Docker previously installed on this Mac, which is on a factory install of El Capitan. The Docker Toolbox is from a few days ago.

The boot2docker version is 1.9.1, Nov 20 2015.
Docker version 1.9.1 build a34a1d5.
Docker-machine version 0.5.1 (7e8e38e).
OS X El Capitan version 10.11.1.

At least one one attempt, Docker Quickstart Terminal seems to work now. But this is after the workaround I described before.

The issue could be because I set HOME to something other than /Users/gas in .profile. Maybe Quickstart Terminal is making some assumptions about the home directory apart from what bash actually does upon completing .profile. I noticed a .docker from a few days ago in /Users/gas. My "real" .docker directory is elsewhere.

**Comment by FrenchBen** [comment]
I don't think it's just the quick start, a lot of the docker/machine settings rely on the user's home directory and precisely the information we need to understand what's going on. 

Could you share *exactly* all of the changes you made and how they were applied (gist of .rc .profile would help)

Thanks

**Comment by GasCreature** [comment]
Try to repro like this:

1.Create user "gas".

2. These commands...
ln -s /u /Users
mkdir -p /u/gas/home/tmp
touch /u/gas/home/.profile
ln -s /u/gas/tmp /u/gas/home/tmp
ln -s /u/gas/home/.profile /u/gas/.profile
ln -s /u/gas/.ssh /u/gas/home/.ssh

3. Put into .profile
HOME=/u/gas/home
if [ -f /usr/local/share/chruby/chruby.sh ] ;then
    source /usr/local/share/chruby/chruby.sh
    source /usr/local/share/chruby/auto.sh
fi
PATH=.:$PATH
export HOME=/u/gas/home

4. Install VirtualBox by running an otto sample (https://ottoproject.io/downloads.html). Installing manually is probably fine, too.

5. If possible, do this:
cd /u/gas/Library
rm -rf VirtualBox
ln -s /u/gas/home/Library/VirtualBox

6. Install Docker Toolbox.

**Comment by FrenchBen** [comment]
@GasCreature It seems that you have a pretty custom setup - We currently only support vanilla setups which is why Toolbox may not be working well for you.
I would advise against installing virtualbox separately from Toolbox and letting it do all of the setup for you.

**Comment by GasCreature** [comment]
Thanks for looking at this. My two cents:

a) Most of the time, the developer will already have VirtualBox already installed, so "advise against installing virtualbox separately" is not going to be effective.

b) Yes, it makes sense to "only support vanilla setups" (for now, anyway) but it may be smart to remove assumptions about the home directory if possible.

**Comment by FrenchBen** [comment]
@GasCreature you're right that the assumption is difficult, but we package the different tools for the versions that are known to work well. 
For example using vbox 4.3 may be ok, but more than likely will cause more issues than the stable release of 5.0.10 included with Toolbox.

Regarding the home folder it's simply due to the default Vbox setup which maps your local folder to the VM.
