### ISSUE TITLE
can't remove stopped container

### ISSUE THREAD

**Issue by cpuguy83** [docker/kitematic#1265]
I have a container which is not running that I am trying to remove but I get an error from the daemon about the container not running and Kitematic won't remove it.

![image](https://cloud.githubusercontent.com/assets/799078/11514201/2ced0512-9845-11e5-9959-e8c25c849101.png)

**Comment by FrenchBen** [comment]
Can you provide details as to how you came about this error?
How did you create this container?
Did you modify it?
Did you exec into it and made changes?
etc.

Anything that would help me replicate the issue

**Comment by cpuguy83** [comment]
I created, via the gui, from the official MySQL image, which itself stopped immediately because it wants an envvar to be set which was not.
Then just clicked the "X" to remove it.

**Comment by FrenchBen** [comment]
Just tried it on the following version with no problem:
![version](https://cloud.githubusercontent.com/assets/3965324/11520083/b4cb9174-9854-11e5-970f-92a4d77c2261.png)

Anything else I'm missing?

**Comment by cpuguy83** [comment]
Evidently my kitematic install was quite outdated.
Thanks!
