### ISSUE TITLE
can't start the kitematic on window10

### ISSUE THREAD

**Issue by cnBruceHong** [docker/kitematic#1271]
hi,I hava a problem in starting the kitematic.It show me the information that :

C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Docker Machine Version: 0.5.2 ( 0456b9f ) Found binary path at .\docker-machine-driver-virtualbox.exe Launching plugin server for driver virtualbox Plugin server listening at address 127.0.0.1:61702 () Calling .GetVersion Using API Version 1 () Calling .SetConfigRaw () Calling .GetMachineName (flag-lookup) Calling .GetCreateFlags Making call to close connection to plugin binary Making call to close driver server (flag-lookup) Calling .Close Successfully made call to close driver server Found binary path at .\docker-machine-driver-virtualbox.exe Launching plugin server for driver virtualbox Plugin server listening at address 127.0.0.1:61706 () Calling .GetVersion Using API Version 1 () Calling .SetConfigRaw () Calling .GetMachineName (default) Calling .GetMachineName (default) Calling .DriverName Host already exists: "default"

reinstall the kitematic can't deal with this problem.

**Comment by haleksandre** [comment]
I had the same problem.

Notice the `Host already exists: "default"` at the end or the error. It seems like Docker Machine is unable to remove the default machine and recreate a new one even when you click on `delete vm and retry`. 

```bash
... Host already exists: "default"
```

The workaround is to remove the "default" machine manually via the Git for Windows:

```bash
docker-machine rm default
```

Once the default is remove and you run Kitematic it should be able to create a new default machine.

**Comment by FrenchBen** [comment]
Thanks @haleksandre for the steps to get this fixed. @cnBruceHong Feel free to re-open if this is still an issue after you follow the above steps

**Comment by eliassal** [comment]
So does this mean that each time we trigger the Kitematic GUI or the Docker Quick Terminal, we should manually do this?
Why I am saying this is because I have Kitematic 1.11, Launching Docker Quick terminal works like a charm, it creates the VM, I can run all needed commands. However, when I trigger Kitematic GUI, it starts working 5%, 10%....then I get the exact same error. So I understand from this thread that the machine created by one of those tools "GUI" and "Quick terminal" is not comaptible or should be deleted when we swithc between them?

**Comment by FrenchBen** [comment]
@eliassal I'm not following - There were several updates to Kitematic since this bug was opened. 
Update to the latest tools and then open a new issue if you still have an issue. 

Also as the Docker for Windows/Mac is now an Open Beta, I would recommend using that.
