### ISSUE TITLE
Container screen does not update when starting/stopping containers

### ISSUE THREAD

**Issue by markbao** [docker/kitematic#1275]
I have 1 container installed (a LimeSurvey install). Whenever I start/stop a container, the container screen does not update - the container logs do not update, and the web preview does not appear. I have to go to another screen (e.g. New Container) and then go back to the container to see the UI update.

Demo 1 (starting a container): https://gfycat.com/BronzeVacantAquaticleech

![](https://giant.gfycat.com/BronzeVacantAquaticleech.gif)

Demo 2 (stopping a container): https://gfycat.com/SpitefulConcernedGlowworm

![](https://giant.gfycat.com/SpitefulConcernedGlowworm.gif)

Potentially related to #535 and #622.

Kitematic 0.9.3
Installed with Docker Toolbox
Docker version 1.9.1, build a34a1d5
Mac OS X 10.11.1 (15B42)

**Comment by FrenchBen** [comment]
@markbao Thank you for the awesome screen shots/gif. We revamped the entire log system for the upcoming 0.9.4 release which will fix this issue.

Keep an eye out for the next update :)

**Comment by markbao** [comment]
Oh that's great news! Thank you very much :)
