### ISSUE TITLE
Missing volumes when environment variables are updated in an existing container

### ISSUE THREAD

**Issue by ChristianLopezGonzalez** [docker/kitematic#1285]
Missing volumes when environment variables are updated in an existing container.

I am using Windows 10 and kitematic.

**Comment by FrenchBen** [comment]
Can you provide me with a screenshot of your Kitematic version?

**Comment by ChristianLopezGonzalez** [comment]
The "version" file in the folder says v0.33.6

![captura](https://cloud.githubusercontent.com/assets/10656934/11699030/485c48a2-9ec2-11e5-859d-ba47286f1015.PNG)

**Comment by FrenchBen** [comment]
Closing due to more recent releases - If this is still an issue, feel free to re-open this issue.
