### ISSUE TITLE
Volume directory limited in /Users

### ISSUE THREAD

**Issue by HessianZ** [docker/kitematic#1286]
I have add shared folders manually. (Virtual box settings and mount it in boot2loader image)
I can run an image from command line and mount the shared folders.

BUT I CAN NOT DO THIS WITH KITEMATIC.

**Comment by FrenchBen** [comment]
Currently we limit the folders to within the Users's home directory as we do not have a proper solution in place to check if the volume is also mounted within Virtualbox. 

There's a PR being reviewed to possibly change this behavior. Be on the lookout for future releases
