### ISSUE TITLE
Private repos seen after login but not able to be pulled

### ISSUE THREAD

**Issue by trevrosen** [docker/kitematic#1288]
This is on a pristine install.
**Kitematic version:** v0.9.3 installed via Docker Toolbox
**OSX version:** 10.10.5

## How I got here
- Installed Kitematic
- Logged into Docker Hub via Kitematic
- After that, I can see all my organization's private repos -- :+1: 
- Click create on any of them
- Get error screen: "Error: image $username/$repo:$tag not found" (where '$' things are stand-ins for the real names of my stuff)
- I get this for any private repo, any tag I've tried
- All public repos I've tried pull images and start just fine.
- I can use `docker login` on the CLI to access the images/tags from Docker Hub just fine

In case this matters, I'm an owner on my organization's Docker Hub account and have "Admin" permissions set on the images I'm trying to use via Kitematic.

Apologies in advance for ticket noise here, but I've looked all over and can't find any reference to this kind of problem other than #724, which is closed.

**Comment by FrenchBen** [comment]
When you say  'access the images/tags from Docker Hub just fine' does that include doing a `docker run/pull` with the above image(s) of `$username/$repo:$tag` ?

**Comment by trevrosen** [comment]
@FrenchBen Yes, I can use `docker login` and authenticate to Docker Hub and then do a `docker run` no problem with an image that Kitematic can't pull/run.

**Comment by FrenchBen** [comment]
This may be asking for a lot, but anyway to add me to one of your org with a test repo?
I haven't been able to reproduce this with any of my images.

For example I created a copy of nginx, renamed it to `nginx-dev` and made it a private repo.
![nginx](https://cloud.githubusercontent.com/assets/3965324/11729911/a2a6fc24-9f46-11e5-80c4-8d755961e65a.png)

Pulled it via kitematic without any issues and have it running in Kitematic:
![nginx-kite](https://cloud.githubusercontent.com/assets/3965324/11729918/ad9dbbcc-9f46-11e5-8cf9-6e3b6b8283b4.png)

**Comment by trevrosen** [comment]
This data point might help then: I didn't make these images **myself**. I started a new job, was added to the Docker Hub org, then tried to use Kitematic to set some containers up, and **then** ran into this issue.

FWIW I checked with my colleague who set these up and he doesn't have the same problem -- he can pull the images just fine. 

We *did* make sure that I have the same Docker Hub permissions/membership as he does.

Yes, at this point adding you to our org would be controversial. I'm hoping this is some issue w/ how Kitematic sees/deals with permissions on private repos.

**Comment by FrenchBen** [comment]
To clarify, the above test was done with an org repo, which I was added to with simple read permissions. 
I haven't done anything special to get this working, it's odd that it's working for another user.

Did you try the obvious logout -> login. It could be that your original login keys didn't allow access to the repo, but a 'refreshed' login would?

**Comment by trevrosen** [comment]
Hi! Yes, I tried logging out and logging in before submitting the ticket. I also tried again just now and am still experiencing the same thing. Does Kitematic log anything anywhere? It's very strange to me that I can see these repos but not actually pull them, and maybe logs would shed more light than the UI can?

**Comment by FrenchBen** [comment]
@trevrosen Maybe we can chat over Gitter to try and get this resolved?

**Comment by trevrosen** [comment]
Sure — just created a room and added you.

-TR

**Comment by trevrosen** [comment]
@FrenchBen I'm on CDT timezone and will have to go pretty soon. Happy to talk tomorrow AM if you can't do sometime in the next few min.

**Comment by FrenchBen** [comment]
let's do it tomorrow AM - I'm on PST, so probably more like lunch for you :)

**Comment by trevrosen** [comment]
Sounds great - thanks for your time and attention. I'll keep an eye out starting around 12pm my time.

**Comment by trevrosen** [comment]
Hi @FrenchBen any further insights here? I'm thinking of trying a re-install, as I'm down to cargo cult magic attempts at solutions. :-\

**Comment by trevrosen** [comment]
Welp. That didn't work either. Also tried creating a new private image on my own (i.e. not in my organization) and have the same issue. I guess I just don't get to use Kitematic w/ anything but public images... :frowning: :frowning:

**Comment by trevrosen** [comment]
Just for posterity and completion's sake, I should mention here that in a Gitter session with @FrenchBen I was able to use commands in the Javascript console to pull down images that I can't retrieve with the GUI. WTF.

**Comment by FrenchBen** [comment]
Haven't been able to spend much time trying to trigger the same error on my end. When we left things, I was able to pull the private image @trevrosen created without issues.

**Comment by trevrosen** [comment]
Also just tried on an older version of Kitematic I have on a personal machine (0.8.7) and still experience the same issue. The fact that all of these images are downloadable via the CLI **and** by running a series of expressions/commands in Javascript in the Kitematic Chromium dev tools window, but not through a simple GUI click makes this one of the strangest bugs I've seen in my career. At this point, I'd happy if it just turned out to be PEBKAC, but there's just simply not much room for configuration errors or anything like that.

I'm going to pull clone the project and see if I can make any headway with a development copy.

**Comment by trevrosen** [comment]
Welp just repro'd error in a dev copy and decided I honestly don't have the spare time to try to grok the project and debug this on my own (I have basically zero exp w/ node, so it'd be a learning curve). 

W/e -- I'll just use the CLI to pull things down and launch them. I'm going to close this issue now and hope that it somehow gets solved in a later release. Thanks for your help to date.

**Comment by FrenchBen** [comment]
Sorry we weren't able to figure out what caused the issue - Hope future release 'magically' fix this for you
