### ISSUE TITLE
Tailoring descriptions and bitmaps

### ISSUE THREAD

**Issue by tiagoantao** [docker/kitematic#1289]
If I understand well, there are no ways to

1. add bitmaps to docker images

2. Have the description of the docker hub images appear on kitematic (or at least be able to create new ones) . See https://github.com/biopython/biopython_docker/issues/3

These would be two very cool functions

**Comment by FrenchBen** [comment]
1. bitmaps support should be handled upstream via Hub, which could then be shown to the user. 
2. As far as description, some of them can be quite long and why we've added a link to the hub docs on both the image card and on the container quick-actions.

Thanks for the feedback, having bitmap on docker images is something we really hope to see soon!
