### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by mimo38** [docker/kitematic#1292]
*(Under Mac OS X 10.10.3)*
I can't close this repository, probably owed to the setting in a stand-by mode of the computer :
**EHOSTDOWN
EHOSTDOWN
connect
192.168.99.100
2376**
or
**ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376**
I'm an incompetent novice :anguished:, but i want signal this "bug". The solution for the moment is to close all and restart Kitematic : very pratical!

**Comment by FrenchBen** [comment]
Can you provide the output of:
`docker-machine env default`
and
`docker-machine ssh default ifconfig`

**Comment by mimo38** [comment]
Le 10/12/2015 23:36, French Ben a écrit :
> Can you provide the output of:
> |docker-machine env default|
|Error running connection boilerplate: default is not running. Please 
start it in order to use the connection settings|

> and
> |docker-machine ssh default ifconfig|

Error: Cannot run SSH command: Host "default" is not running

-- 
Avec l'assurance de mes prières
Abbé Michel Morille

**Comment by FrenchBen** [comment]
I wrongly assume that you had it running.
`docker-machine start default`
`docker-machine env default`
`docker-machine ssh default ifconfig`

**Comment by mimo38** [comment]
ordinateur-de-michel:~ michel$ docker-machine start default
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
ordinateur-de-michel:~ michel$ docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/michel/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval "$(docker-machine env default)"
ordinateur-de-michel:~ michel$ docker-machine ssh default ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:D5:A0:AE:53  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:d5ff:fea0:ae53/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1860 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4070 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6648804 (6.3 MiB)  TX bytes:576091 (562.5 KiB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:EF:9C:0C  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:feef:9c0c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1390 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1412 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:126392 (123.4 KiB)  TX bytes:133463 (130.3 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:9F:18:B0  
          inet addr:192.168.99.100  Bcast:192.168.99.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe9f:18b0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7877 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9511 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:880306 (859.6 KiB)  TX bytes:10466837 (9.9 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1152 (1.1 KiB)  TX bytes:1152 (1.1 KiB)

vethdcee20c Link encap:Ethernet  HWaddr 06:DA:A0:2B:C5:56  
          inet6 addr: fe80::4da:a0ff:fe2b:c556/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1860 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4078 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6674844 (6.3 MiB)  TX bytes:576739 (563.2 KiB)

**Comment by mimo38** [comment]
Sorry to be so novice ! :confused:

**Comment by FrenchBen** [comment]
after the `eval "$(docker-machine env default)"`, can you run:
`docker run hello-world`

**Comment by mimo38** [comment]
docker run hello-world
docker0   Link encap:Ethernet  HWaddr 02:42:D5:A0:AE:53  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:d5ff:fea0:ae53/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1860 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4070 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6648804 (6.3 MiB)  TX bytes:576091 (562.5 KiB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:EF:9C:0C  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:feef:9c0c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1651 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1692 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:151939 (148.3 KiB)  TX bytes:164537 (160.6 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:9F:18:B0  
          inet addr:192.168.99.100  Bcast:192.168.99.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe9f:18b0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8107 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9627 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:917031 (895.5 KiB)  TX bytes:10505018 (10.0 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1152 (1.1 KiB)  TX bytes:1152 (1.1 KiB)

vethdcee20c Link encap:Ethernet  HWaddr 06:DA:A0:2B:C5:56  
          inet6 addr: fe80::4da:a0ff:fe2b:c556/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1860 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4078 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6674844 (6.3 MiB)  TX bytes:576739 (563.2 KiB)

**Comment by mimo38** [comment]
Just a precision. To stop the problem, I force the application to be closed, and re-run it. So, actually, there is no problem

**Comment by FrenchBen** [comment]
I'll close this issue for now as it sounds like you've got it running.
