### ISSUE TITLE
Error: Status 403 trying to pull repository library/elasticsearch: "Account is not Active"

### ISSUE THREAD

**Issue by rbalaban-IncentiveNetworks** [docker/kitematic#1293]
Tried to pull the official 'elasticsearch' image but got this error.

Error: Status 403 trying to pull repository library/elasticsearch: "Account is not Active"

**Comment by rbalaban-IncentiveNetworks** [comment]
When I tried it a second time, it seemed to work fine.

**Comment by FrenchBen** [comment]
It's usually an issue with your actual hub account which needs to be activated. Logging in to Hub will get this resolved.
