### ISSUE TITLE
Got Repository locked on new private repository: joegus/joegus-devx

### ISSUE THREAD

**Issue by InfiAps** [docker/kitematic#1297]
Hi!
I got: Error: Status 403 trying to pull repository joegus/joegus-devx: "\"The Repository is Locked, access denied\""

Could you unlock it for me?

Thanks!!

Kind regards
Jorgen

**Comment by thaJeztah** [comment]
@InfiAps you'll need to contact support@docker.com for that, the maintainers of kitematic I don't have access to that, that's handled by the Docker Hub team

**Comment by FrenchBen** [comment]
thanks @thaJeztah for the help - Closing as unrelated
