### ISSUE TITLE
install on ubuntu 14.04.3 failed

### ISSUE THREAD

**Issue by typekpb** [docker/kitematic#1298]
followed the steps on the: https://github.com/docker/kitematic/wiki/Early-Linux-Support, namely:

	sudo apt-get install nodejs
	sudo apt-get install npm
	git clone https://github.com/docker/kitematic
	cd kitematic/
	make

ended up with:

	npm http GET https://registry.npmjs.org/ansi-regex
	npm http GET https://registry.npmjs.org/traverse
	npm http 304 https://registry.npmjs.org/ansi-regex
	npm http 304 https://registry.npmjs.org/traverse
	npm ERR! 
	npm ERR! Additional logging details can be found in:
	npm ERR!	/home/pb/all/system/kitematic/npm-debug.log
	npm ERR! not ok code 0
	make: *** [run] Error 1

where: `less /home/pb/all/system/kitematic/npm-debug.log` shows:

	
	63272 silly gunzTarPerm extractEntry LICENSE-MIT
	63273 silly gunzTarPerm modified mode [ 'LICENSE-MIT', 438, 420 ]
	63274 silly addNameRange number 2 { name: 'generate-object-property',
	63274 silly addNameRange   range: '>=1.1.0-0 <2.0.0-0',
	63274 silly addNameRange   hasData: true }
	63275 silly addNameRange versions [ 'generate-object-property',
	63275 silly addNameRange   [ '1.0.0', '1.1.0', '1.1.1', '1.2.0' ] ]
	63276 verbose addNamed [ 'generate-object-property', '1.2.0' ]
	63277 verbose addNamed [ '1.2.0', '1.2.0' ]
	63278 silly lockFile 5893e0fd-generate-object-property-1-2-0 generate-object-property@1.2.0
	63279 verbose lock generate-object-property@1.2.0 /home/pb/.npm/5893e0fd-generate-object-property-1-2-0.lock
	63280 silly gunzTarPerm extractEntry lib/store/fslookup.js
	63281 silly gunzTarPerm extractEntry lib/store/index.js
	63282 silly gunzTarPerm extractEntry LICENSE
	63283 silly gunzTarPerm extractEntry .travis.yml
	63284 silly gunzTarPerm extractEntry LICENSE
	63285 silly gunzTarPerm modes [ '755', '644' ]
	63286 error addLocalDirectory Could not pack "/home/pb/tmp/npm-9220-8GVshoV4/1450050334473-0.9088068348355591/package" to "/home/pb/.npm/exec-sh/0.2.0/package.tgz"
	63287 silly lockFile 297a8ce7-js-org-exec-sh-exec-sh-0-2-0-tgz https://registry.npmjs.org/exec-sh/-/exec-sh-0.2.0.tgz
	63288 silly lockFile 297a8ce7-js-org-exec-sh-exec-sh-0-2-0-tgz https://registry.npmjs.org/exec-sh/-/exec-sh-0.2.0.tgz
	63289 verbose false,/home/pb/all/system/kitematic/node_modules,/home/pb/all/system/kitematic/node_modules/request/node_modules/har-validator/node_modules unbuild is-my-json-valid@2.12.3
	63290 info postuninstall is-my-json-valid@2.12.3
	63291 silly gunzTarPerm extractEntry reporters/json.js
	63292 silly gunzTarPerm extractEntry lib/MapUpdateTask.js
	63293 silly gunzTarPerm extractEntry lib/MessageList.js
	63294 silly gunzTarPerm extractEntry LICENSE
	63295 silly gunzTarPerm extractEntry index.js
	63296 silly gunzTarPerm extractEntry LICENSE
	63297 info preinstall lru-cache@2.7.3
	63298 silly lockFile 27a51b33-exec-sh-0-2-0 exec-sh@0.2.0
	63299 silly lockFile 27a51b33-exec-sh-0-2-0 exec-sh@0.2.0
	63300 error Error: ENOENT, chmod '/home/pb/tmp/npm-9220-8GVshoV4/1450050334750-0.37146347877569497/package/test'
	63301 error If you need help, you may report this log at:
	63301 error     <http://github.com/isaacs/npm/issues>
	63301 error or email it to:
	63301 error     <npm-@googlegroups.com>
	63302 error System Linux 3.19.0-33-generic
	63303 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
	63304 error cwd /home/pb/all/system/kitematic
	63305 error node -v v0.10.25
	63306 error npm -v 1.3.10
	63307 error path /home/pb/tmp/npm-9220-8GVshoV4/1450050334750-0.37146347877569497/package/test
	63308 error fstream_path /home/pb/tmp/npm-9220-8GVshoV4/1450050334750-0.37146347877569497/package/test/break.js
	63309 error fstream_type File
	63310 error fstream_class FileWriter
	63311 error fstream_finish_call setupMadeDir
	63312 error code ENOENT
	63313 error errno 34
	63314 error fstream_stack end (/usr/lib/nodejs/fstream/lib/writer.js:319:21)
	63314 error fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:336:20
	63314 error fstream_stack next (/usr/lib/nodejs/fstream/lib/writer.js:366:20)
	63314 error fstream_stack Object.oncomplete (fs.js:107:15)
	63315 verbose exit [ 34, true ]

moreover `git log | head` shows:

	commit 806efdd7673077886b1004621ab4416cef3f02f8
	Merge: ff19604 31928e6
	Author: Jeffrey Morgan <jeffdm@users.noreply.github.com>
	Date:   Mon Dec 7 14:58:43 2015 -0800

	    Merge pull request #1280 from docker/bump-version
	    
	    Bump version, fix exec related error in new version

**Comment by james-nesbitt** [comment]
so this looks more like an npm issue than a kitematic issue.  In particular, npm is failing because of file permissions in your tmp directory (which in ubuntu is /usr/{user}/tmp or in your npm folder (which is /home/{user}/.npm"

Can you try explictly setting your TMP path to something which is user-writeable, and chmod-able: https://github.com/npm/npm/issues/2936

**Comment by FrenchBen** [comment]
Npm versions are pretty sensitive - I would make sure you have the proper version running: `v4.2.2`

**Comment by andreicristianpetcu** [comment]
I think using ndenv simplifies node/npm version issues.

**Comment by FrenchBen** [comment]
The instructions had 'nodejs-legacy' as one of the dependencies, but this seemed unclear. I removed the npm package from the list and added instructions to use NVM which I prefer anyway.

Closing this for now

**Comment by Vanuan** [comment]
> Npm versions are pretty sensitive - I would make sure you have the proper version running: v4.2.2

This is node version, not npm version. Which npm version should be used?

**Comment by FrenchBen** [comment]
NPM version will depend on the Node version installed - If you install the proper Node, you'll get the associated NPM
