### ISSUE TITLE
Kitematic show me a container that does not exists anymore 

### ISSUE THREAD

**Issue by JimyRyan** [docker/kitematic#1302]
Hello,

On the Kitematic interface, I see a container that does not exists any more.

When I run the docker ps command, I got only 2 containers : 

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
7a9773a08867        mysite33_web        "python manage.py run"   36 seconds ago      Up 38 seconds       0.0.0.0:8000->80/tcp   mysite33_web_1
ec8ac457e7ad        postgres:9.4        "/docker-entrypoint.s"   2 minutes ago       Up 2 minutes        5432/tcp               mysite33_db_1

You can see a screenshot of the Kitematic interface in the image attached
![ko](https://cloud.githubusercontent.com/assets/1082289/11780456/52290444-a262-11e5-8c45-8768a9c6d12d.png)

**Comment by thaJeztah** [comment]
did you also try `docker ps -a`? the container may still exist, but "exited" / "stopped"

**Comment by JimyRyan** [comment]
With the docker ps -a command, I don't see a container named "**clever_albattani**"

Below is the result of the docker ps -a command : 

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                         PORTS                  NAMES
3711b67b2ba4        c12be19f93d5        "/bin/sh -c 'pip-comp"   3 minutes ago       Exited (1) 3 minutes ago                              modest_brown
d4ea6e81de47        da6e3f3c073d        "/bin/sh -c 'pip-comp"   6 minutes ago       Exited (127) 6 minutes ago                            evil_chandrasekhar
7078aa1a5b6a        dd990fd23b42        "/bin/sh -c 'pip inst"   6 minutes ago       Exited (2) 6 minutes ago                              nostalgic_hawking
f337cc196e08        8319e9013003        "/bin/sh -c 'pip inst"   7 minutes ago       Exited (1) 7 minutes ago                              elegant_leavitt
ee8316dd8d86        fabba5d8bb44        "/bin/sh -c 'pip inst"   10 minutes ago      Exited (1) 10 minutes ago                             grave_brahmagupta
a2cf81fd6d20        djangocms-app       "bash"                   11 minutes ago      Up 11 minutes                                         djangocms-app
2c6bdfc10fee        7d74fd2318da        "/bin/sh -c 'pip inst"   13 minutes ago      Exited (1) 13 minutes ago                             drunk_mayer
7cf1b620506c        c3771e3d0bf8        "/bin/sh -c 'pip-comp"   27 minutes ago      Exited (2) 27 minutes ago                             small_dubinsky
45755d7821d6        0f69c4fd6e54        "/bin/sh -c 'pip-comp"   38 minutes ago      Exited (2) 38 minutes ago                             drunk_joliot
bba99efb9306        d71052fc4c54        "/bin/sh -c 'pip-comp"   44 minutes ago      Exited (127) 44 minutes ago                           tiny_curie
bdf5e5c3dc1c        5d9865406620        "/bin/sh -c 'pip-comp"   45 minutes ago      Exited (2) 45 minutes ago                             high_newton
a5303291b0db        a8aa4d099331        "/bin/sh -c 'pip-comp"   47 minutes ago      Exited (2) 47 minutes ago                             condescending_babbage
fc38912cab3a        576001c43ad5        "/bin/sh -c 'pip-comp"   48 minutes ago      Exited (1) 48 minutes ago                             cranky_blackwell
034ec49b9a3c        mysite33_web        "gulp build"             58 minutes ago      Exited (0) 58 minutes ago                             mysite33_web_run_2
7a9773a08867        mysite33_web        "python manage.py run"   About an hour ago   Up About an hour               0.0.0.0:8000->80/tcp   mysite33_web_1
074efe328e3a        mysite33_web        "start migrate"          About an hour ago   Exited (0) About an hour ago                          mysite33_web_run_1
ec8ac457e7ad        postgres:9.4        "/docker-entrypoint.s"   About an hour ago   Up About an hour               5432/tcp               mysite33_db_1

**Comment by FrenchBen** [comment]
@JimyRyan This usually happens when you make a change to the container that breaks it and results in a 500 (container cannot be created) - There's a ghost container that needs to be removed. 
We have a fix in place that simply needs to be pushed.

Since this is a duplicate, I'll close it in favor of a previous issue
