### ISSUE TITLE
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/mongo/images. You may want to check your internet connection or if you are behind a proxy.

### ISSUE THREAD

**Issue by renxc** [docker/kitematic#1303]
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/mongo/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
Are you behind a proxy? If so, please check the Wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by renxc** [comment]
Thanks for your response.
