### ISSUE TITLE
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images

### ISSUE THREAD

**Issue by scwanglijun** [docker/kitematic#1304]
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
There are some guidelines in the wiki to help you get connected from behind a proxy. Please see:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
