### ISSUE TITLE
unknown command /usr/src/app/bin/codeclimate

### ISSUE THREAD

**Issue by raulsann** [docker/kitematic#1305]
We connected our repository and this is the message we are getting in the UI:

    unknown command /usr/src/app/bin/codeclimate

Where is the configuration file to tell Kitematic where to find codeclimate?

Thank you!

**Comment by FrenchBen** [comment]
This is more than likely an issue within the container. The `unknown command` is the container's error output. 
Just based on the bin request, you can see the call in the codeclimate Dockerfile:
https://github.com/codeclimate/codeclimate/blob/master/Dockerfile#L20
