### ISSUE TITLE
Better docker-machine and VM management features

### ISSUE THREAD

**Issue by Murazaki** [docker/kitematic#1306]
Please give a better feedback on whether the VM are running or not, and allow us to restart the docker-machine from the interface.

For now, what's happening is :
- I launch Kitematic, it launches docker-machine and display the available VMs and the ones running
- After a while (or after an hibernation), docker-machine shuts down, and the VMs are shown as running but are inoperant. To get out of the situation, I have to shut down Kitematic and launch it again.

I'm running Mac OS X El Capitan 10.11.2 on a MacBook Pro Retina A1502.

**Comment by FrenchBen** [comment]
This is a current topic in the machine management part of the wiki. 
https://github.com/docker/kitematic/wiki/Machine-Management

Thanks for the feedback.
