### ISSUE TITLE
cannot download mysql docker

### ISSUE THREAD

**Issue by dantonino** [docker/kitematic#1308]
I am getting the following error:

Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/mysql/images. You may want to check your internet connection or if you are behind a proxy.

However I can get onto https://index.docker.io/v1/repositories/library/mysql/images via browser

**Comment by alexandrev** [comment]
The connection you do with your browser is probably getting through your proxy but that's not happening with the Kitematic and the docker daemon themselves. Please, take a look at:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#proxy-issues

**Comment by dantonino** [comment]
Tis works. Thank a lot!
