### ISSUE TITLE
machine with core i7 and 32 go ram 

### ISSUE THREAD

**Issue by Malouke** [docker/kitematic#1311]
hello i want , insatall at  home cluster where i can use pyspark    whith this configuration  :

32 go RAM 
and core i7 

whith vm like sanbox hortonworks it's  realy slow.

**Comment by FrenchBen** [comment]
@Malouke Feel free to re-create the `default` VM to suit your needs. We only provide the VM with some ok resources, but you can go nuts and give all you've got if desired.
