### ISSUE TITLE
Problem pulling docker image

### ISSUE THREAD

**Issue by mcartia** [docker/kitematic#1315]
Network timed out while trying to connect to https://index.docker.io/v1/repositories/cloudera/quickstart/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by tristanbailey** [comment]
Have this also today, it was working yesterday fine.

**Comment by FrenchBen** [comment]
There have been a couple of network incidents, which you can check here:
http://status.docker.com/

Closing this for now, but feel free to re-open if the issue persist past the network incident
