### ISSUE TITLE
dis is not full, it has 100gb left

### ISSUE THREAD

**Issue by darpansharma** [docker/kitematic#1317]
Error pulling image (latest) from docker.io/bigdatauniversity/spark, Untar re-exec error: exit status 1: output: write /usr/local/hadoop-2.6.0/share/doc/hadoop/hadoop-archives/images/bg.jpg: no space left on device

**Comment by FrenchBen** [comment]
I believe the VM is capped at 20gb - You'll need to re-create it with a larger disk size if you're using that much space. 

Take a look at: https://github.com/docker/kitematic/issues/825
