### ISSUE TITLE
Kitematic v0.9.5 can't config vmware as docker-machine driver

### ISSUE THREAD

**Issue by soulteary** [docker/kitematic#1320]
```
system: OS X 10.10.5
install from: DockerToolbox-1.9.1f.pkg
```

![image](https://cloud.githubusercontent.com/assets/1500781/11973179/71a42d18-a991-11e5-8a0a-92679d7098a0.png)

I delete default virtualbox driver and reset driver to vmwarefusion, and then i start kitematic v0.9.5, the problem as you see:

```
➜  ~  docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER   ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.9.1 
```

how can i use vmwarefusion as driver?

====
is there any solution like https://github.com/docker/kitematic/pull/1108

**Comment by soulteary** [comment]
finally, i release the kitematic for myself, but i still hope kitematic can support switch docker-machine driver as feature...

that's is what i did for this problem:

### change the docker-machine cmd for vmwarefusion 

more detail : https://docs.docker.com/machine/drivers/vm-fusion/ 

```
  create: function (machineName = this.name()) {
    return util.execFile([this.command(), '-D', 'create', '-d', 'vmwarefusion', '--vmwarefusion-memory-size', '2048', machineName]);
  },
```

### fake VirtualBox is installed

```
  async nonNativeSetup () {
    let virtualBoxVersion = null;
    let machineVersion = null;
    while (true) {
      try {
        setupServerActions.started({started: false});

        // Make sure virtulBox and docker-machine are installed
        let virtualBoxInstalled = true || virtualBox.installed();
```

===

I think kitematic should add util for others drivers which docker-machine supported....

**Comment by FrenchBen** [comment]
@soulteary There was some early work done on VM selection and the ability to support the different VM. 
docker-machine no longer ships with all of the drivers, which means that a user would need to install them separately making this a lot more cumbersome. 

Thanks for the code snippet which help clarify some of the changes needed.

**Comment by soulteary** [comment]
But i use docker-machine version 0.5.4, build 6643d0e is until support VM which not Virtualbox.

And the v0.5.4 is the latest verion... https://github.com/docker/machine/releases

what does those words mead?

```
docker-machine no longer ships with all of the drivers
```

Thanks for your reply.

**Comment by FrenchBen** [comment]
Sorry - looks like they reverted back to 1 binary. up to 0.5.2 all drivers were separate and had to be downloaded with machine. 

If you want to create a proper PR it would need to support both fusion + vbox - fusion isn't free, which stops most users that are using this open source project.

**Comment by soulteary** [comment]
@FrenchBen 
Hi, i suggest that only support auto select vm environment when user install and first open kitematic.
It can help which people use other VMs, now kitematic often check vbox is installed and run `docker-machine create dev -d virtualbox`, whether user has been create any docker machine which called `default`, the origin VM will be overwrite anyway.

Not contain any software, it's free? 

Do I understand you correctly?

I'm sorry for my poor english, :(

**Comment by FrenchBen** [comment]
No worries about the english. It's a difficult subject.
The issue comes past the initial setup and something happens? How do you rebuild the VM?

**Comment by soulteary** [comment]
@FrenchBen aha... : )

i use kitematic long before v0.9.5, my laptop prevent version is v0.7 or v0.8... it gets along with vmwarefusion and parallels well.

and https://github.com/docker/kitematic/issues/1320#issue-123620441 7 days before, i decide to update the kitematic, but when i install new version of kitematic, i found my docker-machine had been overwrite... 

then i close kitematic process, rebuild vm by myself via `docker-machine create ....`

Unfortunately, when i restart kitematic, the vm has been replace by virtual-box vm again.

I try several times, both old version and v0.9.5, make sure isn't my system problem.

Finally i search all kitematic source and edit the file as above.

that's all i met.

**Comment by FrenchBen** [comment]
Understood - it's a good step in allowing different VM setup, but there is a lot more VM management behind it.
