### ISSUE TITLE
Docker Terminal doesn't launch the VM if set to use iTerm

### ISSUE THREAD

**Issue by raguay** [docker/kitematic#1330]
Hi,

I just reinstalled the latest Docker Toolkit that includes Kitematic. The quick launch terminal asked to use iTerm or Terminal. I selected iTerm and it launched iTerm, but the docker agents did not launch. I can not user the docker terminal at all now because it doesn't see the docker agents.

**Comment by FrenchBen** [comment]
Can you provide us with the output of:
`env | grep -i docker`
`docker version`
`which docker`

As an FYI this is more of a Kitematic related board - Toolbox related issues (such as the quick-launch terminal) are better within the Toolbox repo: https://github.com/docker/toolbox/issues

**Comment by raguay** [comment]
I did not know the tools had a repo. The output requested:

  

➜  ~ env | grep -i docker  
➜  ~ docker version  
Client:  
Version:      1.9.1  
API version:  1.21  
Go version:   go1.4.3  
Git commit:   a34a1d5  
Built:        Fri Nov 20 17:56:04 UTC 2015  
OS/Arch:      darwin/amd64  
Cannot connect to the Docker daemon. Is the docker daemon running on this
host?  
➜  ~  which docker  
/usr/local/bin/docker  
➜  ~  

  

Evidently, it isn't starting docker and setting the environment when you set
it to iTerm. How do you set it back to Terminal? Do you want me to repost this
on the other repo?

> On Dec 29 2015, at 11:57 pm, French Ben &lt;notifications@github.com&gt;
wrote:  

>

> Can you provide us with the output of:  
env | grep -i docker  
docker version  
which docker

>

> As an FYI this is more of a Kitematic related board - Toolbox related issues
(such as the quick-launch terminal) are better within the Toolbox repo:
<https://github.com/docker/toolbox/issues>

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/docker/
kitematic/issues/1330#issuecomment-167829707).![](https://github.com/notificat
ions/beacon/ACX0x4lL4vyJZp5CbRt1wMdi1FmAnkOeks5pUrL5gaJpZM4G8Nhj.gif)

**Comment by FrenchBen** [comment]
How did you 'set' your terminal to be iTerm?

**Comment by raguay** [comment]
When I wiped the old version of the toolbox and re-installed from scratch, the first time I ran the quick terminal it asked if I wanted to use iTerm or Terminal. Since I prefer iTerm, I selected iTerm. Now, I can't use the Quick Terminal at all. But, I can get a terminal from Kitematic to work.

**Comment by FrenchBen** [comment]
Forgot it does that - I just tried on mine (I use iTerm daily) and selected the 'iTerm' option (not always)
a new tab was opened in my existing window and I got the docker prompt.
Clicking on 'iTerm (always)' had the exact same effect.

Do you have any special scripts? What happens when you click on the Quickstart Terminal?

**Comment by raguay** [comment]
When I run Quickstart Terminal, it open/brings to front my iTerm with my
normal OhMyZsh prompt. I try a docker command and it says:

  

Cannot connect to the Docker daemon. Is the docker daemon running on this
host?  

  

But, when I open with Terminal from Kitematic, it works fine. Kitematic only
launches with Terminal.

  

Richard

> On Jan 6 2016, at 1:20 am, French Ben &lt;notifications@github.com&gt;
wrote:  

>

> Forgot it does that - I just tried on mine (I use iTerm daily) and selected
the 'iTerm' option (not always)  
a new tab was opened in my existing window and I got the docker prompt.  
Clicking on 'iTerm (always)' had the exact same effect.

>

> Do you have any special scripts? What happens when you click on the
Quickstart Terminal?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/docker/
kitematic/issues/1330#issuecomment-169087562).![](https://github.com/notificat
ions/beacon/ACX0xy7VtyxuVp0XEwhl8MZcZL_asYhqks5pXADxgaJpZM4G8Nhj.gif)

**Comment by FrenchBen** [comment]
From this:
"When I run Quickstart Terminal, it open/brings to front my iTerm with my normal OhMyZsh prompt"
Can you do that and then issue:
`env | grep -i docker`

Also can you check your OMZ shell preferences to confirm that you don't have any docker related mods in it?

**Comment by raguay** [comment]
That line returns nothing and there isn't anything in my .zshrc regarding
Docker. Like I said before, it doesn't launch the docker daemon nor setup any
environment when ran with iTerm.

> On Jan 7 2016, at 12:32 am, French Ben &lt;notifications@github.com&gt;
wrote:  

>

> From this:  
"When I run Quickstart Terminal, it open/brings to front my iTerm with my
normal OhMyZsh prompt"  
Can you do that and then issue:  
env | grep -i docker

>

> Also can you check your OMZ shell preferences to confirm that you don't have
any docker related mods in it?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/docker/
kitematic/issues/1330#issuecomment-169397803).![](https://github.com/notificat
ions/beacon/ACX0x-JQdiek7V-_TqW_mSv55Qw2rLSQks5pXUcggaJpZM4G8Nhj.gif)

**Comment by FrenchBen** [comment]
My point is that your OhMyZsh may be over-writing some of the env/shell variables that are created with the QuickStart Terminal.
The fact that you don't get anything when you run `env | grep -i docker` is an indicative that something is being over-written. 

Unfortunately I am not familiar with your particular shell mod and thus can't help much. My only advice is to disable OhMyZsh and see if the QuickStart Terminal works with iTerm + Zsh.

For comparison, I use iTerm + Zsh + Zprezto and never had any issues.

**Comment by raguay** [comment]
BTW: It still doesn't work. I removed my ohmyzsh and tried to start with the QuickStart Terminal and it still doesn't work. The quickstart terminal doesn't launch doesn't start the VM at all it set for iTerm. It just brings iTerm to the forground. I'm using iTerm Build 2.9.20160105-nightly which changes how an outside process can sent command to the terminal.

**Comment by FrenchBen** [comment]
Aha! You've put the finger on it. The information I was missing was the `nightly` - If you switch to the stable version everything will work as expected.

**Comment by snappyjig** [comment]
I was using iTerm2 3.0 (beta) and had the same issue. Switched back to latest stable release of iTerm2 (2.1.4). And it worked. (Had some unexpected error launching Quickstart Terminal first time. But launching it a second time did the trick).

**Comment by FrenchBen** [comment]
@snappyjig Recent PR #1717 was merged that should fix the above.
