### ISSUE TITLE
Containers not displayed by Kitematic UI

### ISSUE THREAD

**Issue by klousiaj** [docker/kitematic#1331]
This issue is a follow on to #251. Frequently, after shutting down and restarting Kitematic my docker containers are not displayed by the Kitematic UI. They are available using the CLI started through Kitematic but are not shown in the Containers list in the left hand pane.

Kitematic 0.9.4
MacOSX: 10.11.2

This problem does not seem to be limited to local images/containers. All of my current containers are images pulled from docker hub.

On occasion, this issue resolves itself with Kitematic restarts, but I have not been able to identify the pattern or steps cause or resolve the issue. (see Edit)

*Edit* - I was able to repopulate the container list by deleting a dangling image and the container that it was associated with.

**Comment by klousiaj** [comment]
This remains a problem for me. Is there some additional information that is needed in order to investigate this further? 

I have deleted and reinstalled docker-toolbox (and VirtualBox as well) but am still having this problem.

**Comment by dbartow** [comment]
I have the same problem.  If I click Docker CLI in the lower left of Kitematic, and list my images and containers, I have many.. but none are showing up in the left hand nav in Kitematic.  If I pull new ones at the commandline, they dont show up in Kitematic.

However, if I Create from within Kitematic, downloading the Mincecraft or nginx container for example.... it shows up immediately on the left.

Mac OS X 10.11.2
Kitematic:  0.9.3
VirtualBox: 5.0.10 r104061

**Comment by FrenchBen** [comment]
@dbartow Can you provide some example of the commands you're running within the Docker CLI, so that I can mimic the issue.

As a side note, current Docker Toolbox has:
Kitematic 0.9.5
VBox 5.0.12r104815

Maybe an update is needed?

**Comment by dbartow** [comment]
I went ahead an updated, our versions are now in sync on both fronts.  Unfortunately, no changes in behavior.

I tried your command, and the containers start at the command line but don't register in Kinematic.  Even something like `docker run kitematic/minecraft` starts at the command line but doesn't seem to do anything in Kitematic.  Clicking CREATE on any container in the list in Kinematic works right away tho.

I can see the Minecraft container I created via Kitematic in the same console at the nginx ones I did at the commandline.  Some screenshots attached just to make sure Im not doing anything wrong ;)

<img width="1389" alt="screen shot 2016-01-05 at 12 24 42 pm" src="https://cloud.githubusercontent.com/assets/3112388/12126888/c313b6d4-b3a8-11e5-9eea-a4244c5e18f2.png">

<img width="1389" alt="screen shot 2016-01-05 at 12 31 35 pm" src="https://cloud.githubusercontent.com/assets/3112388/12126893/c7ffc0ca-b3a8-11e5-8c1b-465c61cf0faa.png">

<img width="1384" alt="screen shot 2016-01-05 at 12 34 11 pm" src="https://cloud.githubusercontent.com/assets/3112388/12126897/cd381876-b3a8-11e5-834d-0bbdae2b7c51.png">

**Comment by klousiaj** [comment]
Adding to @dbartow information. Here are a few screen caps from my system as well. 

Kitematic: 0.9.5
MacOSX: 10.11.2
VirtualBox: 5.0.12

CLI started through the Kitematic UI in all cases.

Created three containers from Hub sourced images. This was done from within the UI and everything is displayed properly.

![screen shot 2016-01-05 at 4 48 11 pm](https://cloud.githubusercontent.com/assets/4754718/12128746/498d8234-b3cd-11e5-9978-1f6d68fec6e7.png)

Shutdown and restarted Kitematic. No errors presented at startup but this is what I see when the UI starts.
![screen shot 2016-01-05 at 4 52 07 pm](https://cloud.githubusercontent.com/assets/4754718/12128743/433d5198-b3cd-11e5-9ac1-2590df8a7e87.png)

Lastly, ran the script you suggested and got this result.
![screen shot 2016-01-05 at 4 55 36 pm]
(https://cloud.githubusercontent.com/assets/4754718/12128736/3a428e96-b3cd-11e5-966c-a59368b1b850.png)

Anecdotally, I have been able to get the containers to reappear. 

![screen shot 2016-01-05 at 5 41 20 pm](https://cloud.githubusercontent.com/assets/4754718/12129752/a0789e20-b3d3-11e5-8bf8-95974b8ef1e3.png)

In this particular case, I shutdown and restarted Kitematic quickly. I got an error during startup and "retried" the setup of the VM. The retry doesn't always work but in this particular case it did.
A normal restart after failed to populate the container list again.

**Comment by FrenchBen** [comment]
Thanks for all of the feedback and for both confirming the issue. TBH it's difficult to track as I'm not able to replicate the issue. 

![Kitematic Stream](https://fat.gfycat.com/SeveralGrandAustraliancattledog.gif)

https://gfycat.com/SeveralGrandAustraliancattledog

One other commands to run and confirm we're all on the same version:
`docker version`
My output:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

Another test is to have 2 terminal open. Have 1 terminal run: `docker events` and the other run the `docker run...` loop. 

Verify that docker events are being triggered for each docker run command

**Comment by dbartow** [comment]
Thanks again for the attention on this issue @FrenchBen - bummer that we can't reproduce it easily.

Here is my docker version output:  Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
bash-3.2$ 


`docker events` did indeed show events being registered for each container instantiation

<img width="1384" alt="screen shot 2016-01-07 at 2 55 41 pm" src="https://cloud.githubusercontent.com/assets/3112388/12185289/f2a392fa-b54e-11e5-8c15-6ab09c32c037.png">

**Comment by FrenchBen** [comment]
It's weird - Kitematic has a listener for all the docker events - If they are being triggered then you see them appear. 

Would you mind maybe opening the Dev console and see if perhaps some errors are being generated?
`View > Toggle Chromium Developer Tools`

**Comment by dbartow** [comment]
Good call - could this be something important?  IPC sounds like it could be a culprit :)

<img width="874" alt="screen shot 2016-01-07 at 3 22 32 pm" src="https://cloud.githubusercontent.com/assets/3112388/12185841/8b3dfa84-b552-11e5-8a2d-a2b937f1b8ae.png">

**Comment by FrenchBen** [comment]
It's just a warning for IPC calls - I have it too and don't have issues with it. 
IPC isn't involved in the listener for the containers.

**Comment by klousiaj** [comment]
Docker version:

    bash-3.2$ docker version
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   a34a1d5
     Built:        Fri Nov 20 17:56:04 UTC 2015
     OS/Arch:      darwin/amd64

    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   a34a1d5
     Built:        Fri Nov 20 17:56:04 UTC 2015
     OS/Arch:      linux/amd64

I also see events:

    bash-3.2$ docker events
    2016-01-08T09:36:59.854492217-05:00 kitematic/hello-world-nginx:latest: pull
    2016-01-08T09:36:59.902033086-05:00 dc1b6717290e5122e42f0f9a213c6e587da4ed39f01c3a462ae71aa192072021: (from kitematic/hello world-nginx) create

    2016-01-08T09:37:00.183205742-05:00 dc1b6717290e5122e42f0f9a213c6e587da4ed39f01c3a462ae71aa192072021: (from kitematic/hello-world-nginx) start

    2016-01-08T09:37:00.903450006-05:00 5c74b918bfb64f3d6e002f8855d63677ace550bb5dfd5f63fa65a6799b5d8477: (from kitematic/hello-world-nginx) create

    2016-01-08T09:37:01.237401803-05:00 5c74b918bfb64f3d6e002f8855d63677ace550bb5dfd5f63fa65a6799b5d8477: (from kitematic/hello-world-nginx) start

    2016-01-08T09:37:01.836762131-05:00 ee4d57debd467f105e6eaa865ec88c2d8b6732b5da319f6ed8b7c9e36e55fa33: (from kitematic/hello-world-nginx) create

    2016-01-08T09:37:02.166559250-05:00 ee4d57debd467f105e6eaa865ec88c2d8b6732b5da319f6ed8b7c9e36e55fa33: (from kitematic/hello-world-nginx) start

    2016-01-08T09:37:02.929371563-05:00 e16c341df02c5373c66a7882a2747e67c8f20196f8f14a100c28e42e7ab89a1b: (from kitematic/hello-world-nginx) create

    2016-01-08T09:37:03.290900441-05:00 e16c341df02c5373c66a7882a2747e67c8f20196f8f14a100c28e42e7ab89a1b: (from kitematic/hello-world-nginx) start

Oddly enough, today the containers are displayed. 
![screen shot 2016-01-08 at 9 45 16 am](https://cloud.githubusercontent.com/assets/4754718/12200385/9c70d6a6-b5ec-11e5-8c7d-61e36a8dec6d.png)

But restarting Kitematic reproduced the issue of containers not displaying.

![screen shot 2016-01-08 at 9 54 58 am](https://cloud.githubusercontent.com/assets/4754718/12200656/1c3530a2-b5ee-11e5-9b73-e83d799854aa.png)

**Comment by klousiaj** [comment]
Echo @dbartow, thanks for the attention @FrenchBen. When it works, this is a nice tool.

One thing of interest that may or may not be relevant.

Containers that are initiated through the Kitematic UI always seem to be displayed. I created a new container and noted that docker events recorded a pull event for the requested image... running the script through the CLI did not always record that event.

Here are the Docker events for the following situations:
These containers were shown in UI and they were started on the CLI with the provided loop:
*Note the pull event*

![screen shot 2016-01-08 at 9 45 16 am](https://cloud.githubusercontent.com/assets/4754718/12200978/ad6fd45e-b5ef-11e5-8534-619c4ac7c4f0.png)

This containers is shown in UI and was started using the new button in the Kitematic UI.
*Note the pull event*

    2016-01-08T09:51:14.615140797-05:00 kitematic/hello-world-nginx:latest: pull
    2016-01-08T09:51:14.731640613-05:00 79afb50c19a72b5adc49d0efa862f22e2515caa5fcd7175d99e936982d450c1f: (from kitematic/hello-world-nginx:latest) create
    2016-01-08T09:51:15.095245941-05:00 79afb50c19a72b5adc49d0efa862f22e2515caa5fcd7175d99e936982d450c1f: (from kitematic/hello-world-nginx:latest) start

These containers were <b>not</b> shown in UI. In this case, the CLI was used with the provided loop.
*Note: no pull event*
    
    bash-3.2$ docker events
    2016-01-08T09:50:38.995169008-05:00 70acf31f870b0d1faab1901a6b276d639e8fc7a074dfe07c1e02dfdf5c95a02c: (from kitematic/hello-world-nginx) create
    2016-01-08T09:50:39.272555212-05:00 70acf31f870b0d1faab1901a6b276d639e8fc7a074dfe07c1e02dfdf5c95a02c: (from kitematic/hello-world-nginx) start
    2016-01-08T09:50:39.838804156-05:00 13ac23078fd9fd7eca4e5fd5ebbe9702882aaf2c257a1603e8814d19b5fedc72: (from kitematic/hello-world-nginx) create
    2016-01-08T09:50:40.094546998-05:00 13ac23078fd9fd7eca4e5fd5ebbe9702882aaf2c257a1603e8814d19b5fedc72: (from kitematic/hello-world-nginx) start
    2016-01-08T09:50:40.587584956-05:00 9c2245dfafecbc1b8b095350496b371d3f3b442e3c18243c90aef440b7b82c28: (from kitematic/hello-world-nginx) create
    2016-01-08T09:50:40.831444439-05:00     9c2245dfafecbc1b8b095350496b371d3f3b442e3c18243c90aef440b7b82c28: (from kitematic/hello-world-nginx) start

Looks like @dbartow was also missing the pull event.

**Comment by klousiaj** [comment]
That all may be a red herring...

These containers didn't display in the UI either, but there was a pull event;
    
    2016-01-08T10:36:36.690774250-05:00 kitematic/hello-world-nginx:latest: pull
    2016-01-08T10:36:36.733273832-05:00 511222a0b0adc743f2b78a6c5641e01743710027ec04c23835e2490eb0003d72: (from kitematic/hello-world-nginx) create
    2016-01-08T10:36:37.012986469-05:00 511222a0b0adc743f2b78a6c5641e01743710027ec04c23835e2490eb0003d72: (from kitematic/hello-world-nginx) start
    2016-01-08T10:36:37.484209526-05:00 e915736a53f77d284b3268752070db4fa286777cbcc9bd0e848d5a7dbf34be1e: (from kitematic/hello-world-nginx) create
    2016-01-08T10:36:37.743722531-05:00 e915736a53f77d284b3268752070db4fa286777cbcc9bd0e848d5a7dbf34be1e: (from kitematic/hello-world-nginx) start
    2016-01-08T10:36:38.241399640-05:00 6eff0dfe1eda8b102a36a30a9d4cea5ebf4288accfc8652246dd22c87482d73e: (from kitematic/hello-world-nginx) create
    2016-01-08T10:36:38.521939196-05:00 6eff0dfe1eda8b102a36a30a9d4cea5ebf4288accfc8652246dd22c87482d73e: (from kitematic/hello-world-nginx) start

**Comment by FrenchBen** [comment]
The `pull` event is actually dependent upon the images that you have locally. The Pull event should be skipped if a local copy of the image exists. 
One thing that came to mind after all of this was of course networking. 
How long does the VM stay up? Do you see a chance in behavior if you shutdown the VM and kill any `VboxNetDHCP` process, then start kitematic?

Can you share your network setup within the VirtualBox app?  Vm (right click) -> Settings -> Network -> Adapter 1 && Adapter 2

**Comment by dbartow** [comment]
I usually leave my VM up for many days at a time.  Powering the VM down and then killing VboxNetDHCP, and firing everything back up didn't change the behavior :(

I don't think I've changed these from their defaults:

<img width="1157" alt="screen shot 2016-01-08 at 2 12 30 pm" src="https://cloud.githubusercontent.com/assets/3112388/12210856/f2412c8c-b611-11e5-8ee9-17247d4884fa.png">

<img width="1160" alt="screen shot 2016-01-08 at 2 12 35 pm" src="https://cloud.githubusercontent.com/assets/3112388/12210861/f5ea7384-b611-11e5-9958-cb360e31481e.png">

**Comment by FrenchBen** [comment]
It looks good - just making sure the adapters weren't slowing anything down. I'm honestly confused, even more so by the fact that you got it to work at one point. haha

**Comment by klousiaj** [comment]
I haven't changed anything in VBox directly, I've just been using Kitematic and never actually open the VBox manager or manipulate the VM.

I'm inclined think there is some sort of timing thing happening related to when the VM starts. I get varied behavior starting and stopping Kitematic. Sometimes the container list populates, sometimes it doesn't.

However, if I use the VBox Manager to start default, wait for it to come all the way up and then start Kitematic the list seems to populate every time.

**Comment by FrenchBen** [comment]
I think you're spot on - It seems to be a race condition when we try to communicate with the VM. The fact that you can manually start it, wait for it to come all the way up then start kitematic shows that it's a network issue.
I should've mentioned that I rarely turn off the VM and keep it running. This means that when Kitematic starts, it's already up and running and ready to show my containers. 

I'll look to see if we could integrate some sort of 're-sync' button, which would allow you to re-sync the container list and prevent this from happening after the initial load. Does this sound like a step in the right direction? (short of fixing Vbox of course)

**Comment by dbartow** [comment]
@klousiaj is spot on!  I just tried what he suggested (start default in VBox, then Kitematic) and I have all containers listed in Kitematic!  Woot!

@FrenchBen I can say for certain that if a re-sync button existed, I would click it :)  Would it be just as easy though, and cleaner if possible, to just somehow retry communicating with the vm and present a status icon 'waiting to sync with vm' until a successful return of the container list is completed?  Or is it not possible to know if communication becomes successful with the VM?

**Comment by dbartow** [comment]
Without some kind of status, a user might not know he needs to click the re-sync button anyways.  It's probably not easier, but it seems like constant checking of vm communication with retries is the 'right' solution for the best UX.  But in the short term, a button would help immensely :):)

**Comment by FrenchBen** [comment]
The issue is that the VM does behave as being up and running, but something else is preventing the network from being properly up. 

The 'retry' that you describe is actually what we do:
https://github.com/docker/kitematic/blob/master/src/utils/SetupUtil.js#L138

When we have an IP (which should mean that we have network) we then try to get the list of containers. Maybe we can look through the logs and see some common issues?
Can you copy them with:
`docker-machine scp default:/var/log/docker.log ~/Desktop/docker.log`

Then add them to a gist. (make sure no 'sensitive' data exist in it plz)

**Comment by klousiaj** [comment]
I've created a [gist](https://gist.github.com/klousiaj/5b0726d72e643a17d831) with two files:
no-containers.docker.log 
containers.docker.log

Haven't compared them in detail. I do see that the successful one has a bunch of events selecting containers at the end the unsuccessful one does not.

**Comment by dbartow** [comment]
Here we go:  https://gist.github.com/dbartow/2422bbaa385136f36aab

The first initialization in there was the successful one I did last night, starting the Default VM then Kitematic.  I can see a bunch of container ID/json messages at the end of it.  The second init, done 18 hours later (just now) was an unsuccessful start where I just fired up Kitematic and it started the Default VM but never synced properly.

**Comment by FrenchBen** [comment]
Thanks @dbartow for the logs - I'll look through it.

**Comment by FrenchBen** [comment]
@dbartow  @klousiaj Out of curiosity, do you mind downloading the latest release and see if you still see the same issue?

https://github.com/docker/kitematic/releases/tag/v0.9.5.1

**Comment by dbartow** [comment]
Just tried the new version and no change.  I did notice that the Electron IPC warnings are gone now tho :) :+1:

**Comment by FrenchBen** [comment]
Thanks for the QA - I've created a feature request and @alexandrev has been nice enough to take on the challenge!
