### ISSUE TITLE
Tag latest not found in repository docker.io/my_repo

### ISSUE THREAD

**Issue by tpraizler** [docker/kitematic#1333]
Not sure what is the problem..:-|
I downloaded the latest docker toolbox.

Trying to add my repo, but got error 

`Tag latest not found in repository docker.io/my_repo`

I also can't connect to docker from command line on my mac, I get: 
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

Can you please help?

**Comment by FrenchBen** [comment]
I would make sure that your repo has a tag of `latest` - Additionally use the docker quickstart terminal to be able to talk to docker from the CLI.

**Comment by tpraizler** [comment]
Thanks! worked for me!
