### ISSUE TITLE
Error pulling image (latest) from docker.io/bigdatauniversity/spark, mkdir /mnt/sda1/var/lib/docker/graph/_tmp/e4899875c7182d05ec0b5c2d316d686f2025bd22dfe8051b48470af808bf8b43: read-only file system

### ISSUE THREAD

**Issue by mrruland** [docker/kitematic#1335]
trying to download Spark training material from IBM BigDataUniversity results in message Error pulling image (latest) from docker.io/bigdatauniversity/spark, mkdir /mnt/sda1/var/lib/docker/graph/_tmp/e4899875c7182d05ec0b5c2d316d686f2025bd22dfe8051b48470af808bf8b43: read-only file system.  I was executing Kitematic on a Windows system so not sure what the mkfile was trying to do...

**Comment by FrenchBen** [comment]
@mrruland This seems related to Virtualbox and where the `mkdir` happens. I would advise to restart Virtualbox and try it again to see if the problem persists.
