### ISSUE TITLE
error downloading IBM BigDataUniversity Spark image

### ISSUE THREAD

**Issue by mrruland** [docker/kitematic#1336]
Error pulling image (latest) from docker.io/bigdatauniversity/spark, Untar re-exec error: exit status 1: output: unexpected EOF

Tried this numerous times on Windows and Mac without success.  Technology 1 - ease of use -3,  Guess I will try another venue...

**Comment by thaJeztah** [comment]
Do you have enough disk space available in the virtual machine? That image is quite large, it's possible the VM is running out of disk space during the pull or extracting the image

**Comment by FrenchBen** [comment]
You can re-create a new VM with more disk space, by following the details found in the wiki:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space

**Comment by sunyonggang** [comment]
i met the same problem, and i'm looking for a solution. my disk has about 100G, it assigned to the vm 20G, i think it's ok. the space is not the key point.
:flags:

**Comment by FrenchBen** [comment]
@sunyonggang can you confirm that the VM isn't full by providing us the output of:
`docker-machine ssh default df -h`

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
