### ISSUE TITLE
Cannot find repository on Docker Hub

### ISSUE THREAD

**Issue by bdaniel7** [docker/kitematic#1338]
I have a private repository for testing purposes and I'm trying to create a new container from this repository, by using Kitematic from Docker Toolbox 1.9.1f for Windows.
I start Kitematic, log in, I see my repository but when I'm trying to create the container from this repository, I'm getting an error:

Error: image bdaniel7/nodejs:latest not found

When using the CLI, I'm getting the same error:

PS C:\Program Files\Docker Toolbox> docker pull bdaniel7/nodejs
Using default tag: latest
Pulling repository docker.io/bdaniel7/nodejs
Error: image bdaniel7/nodejs:latest not found

When I log in using the web interface I see the repository at 
https://hub.docker.com/r/bdaniel7/nodejs/

So is this a bug or do I need to configure something in my Docker installation?

Thanks,
Daniel

**Comment by FrenchBen** [comment]
@bdaniel7 The fact that the command line cannot pull the image either, we can rule out Kitematic as being at the source of the issue. 

I cannot see your repository, but I would imagine that you simply do not have a 'tag' labelled 'latest'. For comparison, you can look at:
https://hub.docker.com/r/library/node/tags/

You'll see that a tag of 'latest' exists for all Hub images. You should be able to see the tags you have defined at the below URL:
https://hub.docker.com/r/bdaniel7/nodejs/tags/

**Comment by bdaniel7** [comment]
I deleted the repository in the meantime.
But I think that the error was caused by the fact that the repository was actually empty. I didn't push any image to it.

**Comment by FrenchBen** [comment]
That would do it - empty repo means you probably didn't have a tag either
