### ISSUE TITLE
Cannot sign in on Kitematic(Alpha) for windows 7

### ISSUE THREAD

**Issue by Baozi2** [docker/kitematic#1341]

**Comment by Baozi2** [comment]
my network is bad,maybe

**Comment by FrenchBen** [comment]
it's very possible. Can you login to hub.docker.com with the same credentials?

**Comment by Baozi2** [comment]
It is network.

**Comment by Baozi2** [comment]
I found network  has problem.If  network  has problem, I think that give some tips is good.
