### ISSUE TITLE
[Linux] Cannot find module 'git-docker-kitematic/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/lib/init.js

### ISSUE THREAD

**Issue by jean-christophe-manciot** [docker/kitematic#1344]
Ubuntu Server 15.10 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 GNU/Linux

docker version 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

I've built Kitematic following these guidelines: https://github.com/docker/kitematic/wiki/Early-Linux-Support (without the "Install Docker" part obviously).

sudo npm start

> Kitematic@0.9.5 start /home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic
> grunt

Running "newer:babel" (newer) task

Running "newer:babel:dist" (newer) task
No newer files to process.

Running "less:dist" (less) task
>> 1 stylesheet created.

Running "newer:copy:dev" (newer) task

Running "copy:dev" (copy) task
Copied 260 files

Running "newer-postrun:copy:dev:1:/home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "shell:electron" (shell) task

Running "watchChokidar" task
Waiting...
>> [10248:0105/115518:ERROR:CONSOLE(340)] "Uncaught Error: Cannot find module '/home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/lib/init.js'", source: module.js (340)

Any suggestion?

**Comment by FrenchBen** [comment]
What's the output of: `npm install`

**Comment by jean-christophe-manciot** [comment]
root@msi-ge60-ubuntu:/home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic# npm install
mixpanel@0.3.1 node_modules/mixpanel

**Comment by jean-christophe-manciot** [comment]
First pass, 2 packages need attention: lodash & prettyjson

[build-log.txt](https://github.com/docker/kitematic/files/79915/build-log.txt)
------------------------------------------------------------------------------------------------------------------------------------
So:
root@msi-ge60-ubuntu:/home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic# npm install prettyjson
prettyjson@1.1.3 node_modules/prettyjson
└── colors@1.1.2

root@msi-ge60-ubuntu:/home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic# npm install lodash@3.0.0
lodash@3.0.0 node_modules/lodash
-----------------------------------------------------------------------------------------------------------------------------------
Second pass: make
npm install
mixpanel@0.3.1 node_modules/mixpanel
npm run
Lifecycle scripts included in Kitematic:
  start
    grunt
  test
    jest -c jest-unit.json

available via `npm run-script`:
  start-dev
    NODE_ENV=development grunt
  integration
    jest -c jest-integration.json
  release
    grunt release
  release-mac
    grunt release-mac
  lint
    jsxhint src
-----------------------------------------------------------------------------------------------------------------------------------
Then:
npm start

> Kitematic@0.9.5 start /home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic
> grunt

Running "newer:babel" (newer) task

Running "newer:babel:dist" (newer) task

Running "babel:dist" (babel) task

Running "newer-postrun:babel:dist:1:/home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "less:dist" (less) task
>> 1 stylesheet created.

Running "newer:copy:dev" (newer) task

Running "copy:dev" (copy) task
Created 413 directories, copied 2193 files

Running "newer-postrun:copy:dev:2:/home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "shell:electron" (shell) task

Running "watchChokidar" task
Waiting...
>> [18525:0106/154509:ERROR:CONSOLE(340)] "Uncaught Error: Cannot find module '/home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/lib/init.js'", source: module.js (340)

**Comment by FrenchBen** [comment]
Can you detail how your env is setup?
Seeing something like: `home/actionmystique/Program-Files/Ubuntu/Docker/git-docker-kitematic/` makes me think it's a Windows mounted volume. Is this the case?
Can you try on a simple folder at such as `/home/actionmystique/Kitematic/` ?

**Comment by jean-christophe-manciot** [comment]
env | grep NVM
NVM_PATH=/root/.nvm/versions/node/v4.2.2/lib/node
NVM_DIR=/root/.nvm
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
NVM_BIN=/root/.nvm/versions/node/v4.2.2/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist

The working folder is not a Windows mounted volume.

**Comment by FrenchBen** [comment]
It seems your setup is a bit odd - NVM should've been setup for the user, not root - Otherwise the wrong version of node may be used. 
I expected this `env | grep NVM`
To be: (from your path descriptions)
```
NVM_PATH=/home/actionmystique/.nvm/versions/node/v4.2.2/lib/node
NVM_DIR=/home/actionmystique/.nvm
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
NVM_BIN=/home/actionmystique/.nvm/versions/node/v4.2.2/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
```
Can you confirm the node and npm version running for the user that is trying to setup kitematic?

**Comment by jean-christophe-manciot** [comment]
I'm quite surprised but you're right: running "npm start" as a user instead of root launches kitematic correctly.
Thanks for your help.

**Comment by FrenchBen** [comment]
Glad you're surprised that I'm right :D haha - Happy to see this working for you! :+1: 
Welcome to Kitematic Linux
