### ISSUE TITLE
ETIMEOUT 52.7.223.172:443 error when connecting docker hub account to Kitematic

### ISSUE THREAD

**Issue by liuxiaopiao** [docker/kitematic#1345]
I can use my docker hub account to login to docker hub successfully on my laptop.
But when I started the kitematic and tried to connect docker hub account to Kitematic, the error "connect ETIMEOUT 52.7.223.172:443" occurred. 

![error](https://cloud.githubusercontent.com/assets/8635574/12136508/6e1d4c22-b483-11e5-9c59-540f818768e0.png)

**Comment by FrenchBen** [comment]
Are you behind a firewall/proxy? If so, take a look at:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by liuxiaopiao** [comment]
Thank you very much for the help!. It is  resolved.

**Comment by BecauseofLxcCheckpoint** [comment]
@FrenchBen @liuxiaopiao 
I have met the same issue as described in this issue.
I add http_proxy and https_proxy to the /var/lib/boot2docker/profile file. I can successful execute the commands "docker run -it ubuntu bash" and "docker login" in the commandline, and I can also login the docker hub via broswer. But unfortunately, I can not login the kitematic.
In the kitematic, the protal also prompts that "There was an error contacting Docker Hub."

**Comment by FrenchBen** [comment]
@BecauseofLxcCheckpoint Make sure that you have set your ENV variables properly in the Terminal and then open Kitematic from there - I believe it will then work properly and use your proxy settings.

**Comment by BecauseofLxcCheckpoint** [comment]
**@FrenchBen 
I open a window git bash under /e/dockertoolbox/dockertoobox_install_dir/Docker Toolbox, the following are my procedures:
I create a cmd file named kitematic_proxy.cmd**
zhangqian@zhangqian-PC MINGW64 /e/dockertoolbox/dockertoobox_install_dir/Docker Toolbox
$ vi kitematic_proxy.cmd
**And insert following script and replace "YOUR_PROXY" with the http://host:port of your proxy**
set proxy=http://109.105.113.200:8080
SET HTTP_PROXY=%proxy%
SET HTTPS_PROXY=%proxy%
for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
SET NO_PROXY=%DOCKER_HOST%
set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
cd Kitematic
Kitematic.exe 




**I save and quit the kitematic_proxy.cmd file. Then I double click the kitematic_proxy.cmd file on windows.
Then the cmd.exe excutes, the log is as follow:**

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox>set proxy=http://109.105.113.200:8080

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox>SET HTTP_PROXY=http://1
09.105.113.200:8080

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox>SET HTTPS_PROXY=http://
109.105.113.200:8080

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox>for /F %i in ('docker-m
achine.exe ip default') do set DOCKER_HOST=%i

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox>set DOCKER_HOST=192.168
.99.100

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox>SET NO_PROXY=192.168.99
.100

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox>set DOCKER_HOST=tcp://1
92.168.99.100:2376

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox>cd Kitematic

E:\dockertoolbox\dockertoobox_install_dir\Docker Toolbox\kitematic>Kitematic.exe

**The kitematic also starts, but it still prompts "There was an error contacting Docker Hub"**
**Do you think my ENV variables are proper?**

**Comment by FrenchBen** [comment]
Can you do some light debugging for me?
When Kitematic opens, hit `CTRL+ALT+i` on your keyboard to get the debugging window. Then type:
```
var repositoryStore = require( './stores/RepositoryStore');
repositoryStore.getState().error
```
And paste the output in a gist.  Then in the same debugging window:
```
repositoryStore.all()
```
And paste that also in a gist.

Thanks!

**Comment by BecauseofLxcCheckpoint** [comment]
@FrenchBen  I try again and I am so happy that the kitematic works!
Maybe the network is so slow, sometimes it will be timeout!
Thanks~! I really want to record this experience.

**Comment by FrenchBen** [comment]
Great to here! thanks for your patience and feedback :D
