### ISSUE TITLE
Pulling error

### ISSUE THREAD

**Issue by DiWang1223** [docker/kitematic#1346]
Error while pulling image: Get https://index.docker.io/v1/repositories/tutum/hello-world/images: dial tcp: lookup index.docker.io on 75.75.76.76:53: server misbehaving

**Comment by FrenchBen** [comment]
What happens when you visit the above link? Do you get a bunch of JSon data?
It could be some simple network related issues - Can you try again?

**Comment by DiWang1223** [comment]
It works right now. Thanks!
