### ISSUE TITLE
bigdatauniversity spark image download issue

### ISSUE THREAD

**Issue by IpekKeskin** [docker/kitematic#1347]
Referencing to the site "https://hub.docker.com/r/bigdatauniversity/spark/", I searched the bigdatauniversity and tried to download spark but it gives me the following error:
ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

**Comment by FrenchBen** [comment]
You may need to restart Kitematic - Are you behind a proxy? Take a look at common solutions found within the Wiki:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
