### ISSUE TITLE
Unable to log in using my DockerHub password

### ISSUE THREAD

**Issue by tonyc** [docker/kitematic#1350]
I use a password manager (1Password to be exact) and I like long, secure passwords. 

I can log into the dockerhub website just fine with my password, but using the Kitematic OSX app, when I enter my username and password, and click "Log In", I get the spinner for a second, and nothing happens - no feedback, error messages, or anything.

My current password is 24 characters long, and contains letters, numbers, and the following punctuation in no particular order:

(.^%\

I was able to log in the very first time through the app, when it asks you to sign up, and it happily accepted my password and created the account, and I was logged in. After logging out, however, I can't get back in.

**Comment by tonyc** [comment]
It's... it's working now ;_;

I'm wondering if it was an intermittent problem with dockerhub itself, which is odd since I was able to sign in to the website just fine, but the app refused.

Sorry for the noise!

**Comment by jeffdm** [comment]
No worries! Thanks for creating an issue!

**Comment by arslankhanignite** [comment]
well it doesnt work for me after a fresh install i can login to kitematics but i cant do it the second time i have tried twice with same results

**Comment by FrenchBen** [comment]
@arslankhanignite you mean using a password manager? Why do you need to login twice?
