### ISSUE TITLE
Can't pull mongo image

### ISSUE THREAD

**Issue by jhu104** [docker/kitematic#1351]
Error pulling image (latest) from docker.io/library/mongo, Server error: Status 0 while fetching image layer (2c788329cf71b09863a2ba17dc0275d7f89c2890f04c0c6195313c5c37e09215)

**Comment by FrenchBen** [comment]
Looks like you got disconnected during the initial pull - Can you retry it and re-open if it fails again?

**Comment by jhu104** [comment]
It worked again yesterday thanks
