### ISSUE TITLE
Unable to start up kinematic. No space left on device (28)

### ISSUE THREAD

**Issue by jkristoffer** [docker/kitematic#1356]
While running some commands in my container, Kinematic crashed. After trying to start up Kinematic again I get the following error:

```
(electron) ipc module is deprecated. Use require("electron").ipcMain instead.
(electron) loadUrl is deprecated. Use loadURL instead.
2016-01-13 07:47:10.075 Electron[729:25094] Persistent UI failed to open file file:///Users/jkris/Library/Saved%20Application%20State/com.electron.kitematic_(beta).savedState/window_2.data: No space left on device (28)
```

I'm on a MacBook Pro OSX v10.11.2

**Comment by FrenchBen** [comment]
is your disk full?

**Comment by jkristoffer** [comment]
I still have plenty of space on my disk

**Comment by FrenchBen** [comment]
on your actual HD - but the VirtualBox hdd may be full. 
Can you run the following and paste the output here:
`df -h`
and
`docker-machine ssh default df -h`

**Comment by jkristoffer** [comment]
df -h
```
Filesystem      Size   Used  Avail Capacity  iused   ifree %iused  Mounted on
/dev/disk1     112Gi   86Gi   25Gi    78% 22668104 6655158   77%   /
devfs          180Ki  180Ki    0Bi   100%      624       0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0       0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0       0  100%   /home
```

docker-machine ssh default df -h
```
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     1.8G    123.8M      1.6G   7% /
tmpfs                  1001.3M         0   1001.3M   0% /dev/shm
/dev/sda1                18.2G     13.9G      3.3G  81% /mnt/sda1
cgroup                 1001.3M         0   1001.3M   0% /sys/fs/cgroup
none                    111.9G     86.5G     25.4G  77% /Users
/dev/sda1                18.2G     13.9G      3.3G  81% /mnt/sda1/var/lib/docker/aufs
```

**Comment by FrenchBen** [comment]
Would you mind trying to install the latest Docker Toolbox as we recently made some changes.
Your disk isn't full, but looks to only have 3.3GB left - If you tried to download a large image, it's possible that the above error would've been triggered.

**Comment by sadortun** [comment]
I was able to reproduce this issue. When you have many downloaded images, the docker VM hdd gets full. You should probably display a notice in the UI, or increase silently the docker VM HDD.

**Comment by FrenchBen** [comment]
@sadortun Increasing the VM isn't such an easy thing to do - We did however add some info in the wiki:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space

**Comment by sadortun** [comment]
Would it be possible to display a warning message in the UI ? 

The only side effect i had was a error while performing an `ALTER TABLE` in mysql.

```
ERROR 1878 (HY000): Temporary file write failure in mysql
```

Having a notice in the UI would probably saved my hours of investigation ....

**Comment by FrenchBen** [comment]
@sadortun We would need to catch the error when any container operations are made. It's doable but not high on the priority list - If you'd like open a new Issue with a title that starts with `Feature proposal: ` and I'll add the proper labels to it, so that we get around to implementing it in the future
