### ISSUE TITLE
Support using proxy

### ISSUE THREAD

**Issue by davidshen84** [docker/kitematic#1359]
Accessing to `docker.io` is slow or blocked in some places. It would be nice if **Kitematic** can support **socks5** proxy.

**Comment by FrenchBen** [comment]
Kitematic isn't really the issue, but rather the VM communicating with docker.io - You can read more about proxy settings in our wiki:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by davidshen84** [comment]
No I really mean the web browser in Kitematic. I cannot use it the search for the images because `docker.com` is blocked.

**Comment by FrenchBen** [comment]
If docker.com being blocked completely, there isn't much we can do short of asking your admin to whitelist the site?
Getting Kitematic to support 'socks5' is more an entire arch re-structure as the overall Docker chain doesn't support it (yet).
See: https://github.com/docker/docker/issues/5989

**Comment by davidshen84** [comment]
I think Kitematic is implemented in Node.js and *electron* framework. But the referred issue is talking about docker itself and *GoLang*...

Anyway, if the change is too much, I will just go VPN.

**Comment by davidshen84** [comment]
I think Kitematic is implemented in Node.js and *electron* framework. But the referred issue is talking about docker itself and *GoLang*...

Anyway, if the change is too much, I will just go VPN.

**Comment by davidshen84** [comment]
I think Kitematic is implemented in Node.js and *electron* framework. But the referred issue is talking about docker itself and *GoLang*...

Anyway, if the change is too much, I will just go VPN.

**Comment by davidshen84** [comment]
I think Kitematic is implemented in Node.js and *electron* framework. But the referred issue is talking about docker itself and *GoLang*...

Anyway, if the change is too much, I will just go VPN.

**Comment by FrenchBen** [comment]
Kitematic relies on Docker itself for all API requests. As long as there is support in place, Kitematic can then adapt.
