### ISSUE TITLE
using other mount protocol than vboxsf

### ISSUE THREAD

**Issue by xinity** [docker/kitematic#1360]
hi,

i'm been wondering how we can use kitematic in toolbox to mount a shared folder using protocol like nfs for mac or cifs for windows, rather than vboxfs which in term a performance is the worst :(

i haven't found any options in kitematic, maybe i've missed something ?

**Comment by FrenchBen** [comment]
Kitematic will use the VirtualBox VM of `default` - As long as you setup the vm as such, the mounted folder can use a different protocol and still work in Kitematic.
