### ISSUE TITLE
zombie container

### ISSUE THREAD

**Issue by StevePrice** [docker/kitematic#1366]

**Comment by StevePrice** [comment]
server error
500
Cannot stop container hfbk: [2] Container does not exist: container destroyed

docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                                                                                           NAMES
7de9a636df60        pwdevops/evergreen:stable   "/evergreen/entrypoin"   17 minutes ago      Exited (137) 9 minutes ago                                                                                                                   sfsh
9be9b7fa4725        parentsware/evergreen       "/docker-entrypoint.s"   7 days ago          Up 7 days                    7000-7001/tcp, 7199/tcp, 9042/tcp, 9160/tcp, 0.0.0.0:81->80/tcp, 0.0.0.0:444->443/tcp, 0.0.0.0:8081->8080/tcp   hfbk
steveprice@Planet-Steve:~$ docker stop hfbk
Error response from daemon: Cannot stop container hfbk: [2] Container does not exist: container destroyed
Error: failed to stop containers: [hfbk]
steveprice@Planet-Steve:~$ docker stop sfsh
sfsh
steveprice@Planet-Steve:~$ docker rmi 7de9a636df60
Error response from daemon: could not find image: no such id: 7de9a636df60
Error: failed to remove images: [7de9a636df60]

**Comment by FrenchBen** [comment]
That's a know issue, where the container list doesn't refresh properly in Kitematic when an error happens. Closing in favor of previous issue.

Thanks

**Comment by StevePrice** [comment]
Ben,thanks for letting me know.
Steve
