### ISSUE TITLE
Error while downloading container

### ISSUE THREAD

**Issue by dp80** [docker/kitematic#1367]
I got this error while connected to network and trying to download container.

Error while pulling image: Get https://index.docker.io/v1/repositories/library/ubuntu/images: x509: certificate is valid for FG3K6C3A15800002, not index.docker.io

**Comment by FrenchBen** [comment]
From the response given, it seems you are behind a proxy - I would follow the Wiki on setting up your VM to work with the Proxy:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
