### ISSUE TITLE
当使用docker-machine环境变量MACHINE_STORAGE_PATH指定存放目录后kitematic无法正常进入

### ISSUE THREAD

**Issue by skywit** [docker/kitematic#1368]
system : windows 10
docker-toolbox: 1.9.1h

当使用docker-machine的MACHINE_STORAGE_PATH指定到D:\docker\时，docker quick start 能正常运行，但kitematic提示“Certificate directory does not exist” 并且在重启kitematic时会删除已存在vm，再rebuild，导致数据被误删；

I found some keyword in this project:
src/utils/DockerUtil.js

let certDir = path.join(util.home(), '.docker/machine/machines/', name);
32	      if (!fs.existsSync(certDir)) {
33	        throw new Error('Certificate directory does not exist');
34	      }

**Comment by FrenchBen** [comment]
It sounds like the VM didn't get created properly - Can you open VirtualBox, delete the VM and try to re-open Kitematic?

**Comment by skywit** [comment]
when kitematic throw that error and reopen,  the vm will  be  auto deleted! so i think is issue too. the last i means i had deleted the vm many times and reopen Kitematic! thank you!

**Comment by FrenchBen** [comment]
Closing as this seems to be resolved?

**Comment by weituotian** [comment]
@FrenchBen it still be not solved!

**Comment by oulaly** [comment]
Try to add env var like this `DOCKER_CERT_PATH='D:\docker\certs'`, make sure there are `.pem` files in `certs` directory.
