### ISSUE TITLE
Driver aufs failed to remove root filesystem

### ISSUE THREAD

**Issue by scraplesh** [docker/kitematic#1372]
Cannot start or delete container after reboot. Error message:
```
Driver aufs failed to remove root filesystem ...: rename /mnt/sda1/var/lib/docker/aufs/mnt/... /mnt/sda1/var/lib/docker/aufs/mnt/...-removing: read-only file system
```
OSX 10.11.2

**Comment by panneerboss** [comment]
@scraplesh - Was this issue fixed? . I am facing this issue , my container status is dead and trying to delete the container and getting the above error message . I used mount option -v while staring the container
