### ISSUE TITLE
Kitematic won't list images/containers created manually

### ISSUE THREAD

**Issue by davidshen84** [docker/kitematic#1373]
- On Windows
- Do not start Kitematic
- Start the VM by `docker-machine start default`
- Pull a container by `docker pull`
- Start Kitematic

The image will not be listed in Kitematic. If I create a container from that image, it won't be listed in Kitematic either.

It would be nice to be able to see those manually created containers in Kitematic.

**Comment by FrenchBen** [comment]
There's a PR in progress for this - Be on the lookout for future release changelog
