### ISSUE TITLE
Does Kitematic require admin rights to pull the container ?

### ISSUE THREAD

**Issue by etournay** [docker/kitematic#1374]
Error pulling image (latest) from docker.io/brandl/tissue_miner, mkdir /mnt/sda1/var/lib/docker/graph/_tmp/866adaba2a181c39a5651e7bf4db4c2ac3d41e8efb787d08831b2cc40f2a4772: read-only file system

Best regards

**Comment by FrenchBen** [comment]
It looks like your VM may need to be restarted. 
Can you close down Kitematic and issue the following: `docker-machine restart default`

**Comment by igasi** [comment]
In my case, it was because, does not support the processes that were running when free up memory ran smoothly

**Comment by etournay** [comment]
Thanks a lot to both of you for your comments. I did it again with admin rights and it worked. But that might not be the good reason... because I restarted the computer (hence the VM) in the meantime. Of note, I'm using an up-to-date MacOSX Yosemite. I haven't tried on Linux yet.
