### ISSUE TITLE
portType needs to be expanded from udp,tcp to ALSO include none

### ISSUE THREAD

**Issue by ph-hs** [docker/kitematic#1375]
'none' means not exported. In the UI, it would be an override to that specified in the Dockerfile:

<img width="450" alt="screen shot 2016-01-16 at 1 13 02 pm" src="https://cloud.githubusercontent.com/assets/10211993/12373769/2113523c-bc53-11e5-9437-316f1b21b4bf.png">

**Comment by FrenchBen** [comment]
By default all ports are exported. if they aren't exported then they wouldn't have a `MAC IP PORT` assigned. 
Adding 'none' as a port type would be adding a possible entry for bugs/issues if a user failed to select either. 

This behavior mimics how most router admin behave as well:
![](http://www.xlightftpd.com/tutorial/images/setup_behind_firewall_4.png)
