### ISSUE TITLE
'container name' in the user interface should always show the person/org associated.

### ISSUE THREAD

**Issue by ph-hs** [docker/kitematic#1376]
eg. There are 10+ "clouchdb" repositories. In the New dialog you can see which is which:

<img width="450" alt="screen shot 2016-01-16 at 1 08 45 pm" src="https://cloud.githubusercontent.com/assets/10211993/12373755/707e8b1c-bc52-11e5-97c7-b5ef62371da8.png">

But in the main UI, the "who" is lost:

<img width="450" alt="screen shot 2016-01-16 at 1 11 13 pm" src="https://cloud.githubusercontent.com/assets/10211993/12373760/c351c66a-bc52-11e5-90b6-5ac84e3836ec.png">

**Comment by FrenchBen** [comment]
Although not obvious perhaps, but the information isn't lost. If you mouse-over the image name, a pop-up will be displayed with the proper namespace.

![namespace](https://cloud.githubusercontent.com/assets/3965324/12405060/9c49b240-bdf5-11e5-915c-853f3c2f6cef.png)
