### ISSUE TITLE
The mssql container doesn't work 

### ISSUE THREAD

**Issue by Ygilany** [docker/kitematic#1377]
That's what I get 
Network timed out while trying to connect to https://index.docker.io/v1/repositories/rsmoorthy/mssql/images. You may want to check your internet connection or if you are behind a proxy.

Which is not the case for me !

**Comment by FrenchBen** [comment]
Are you behind a proxy?
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
