### ISSUE TITLE
Hello-wrold container failed

### ISSUE THREAD

**Issue by artgeekit** [docker/kitematic#1379]
When pressed create in  Kitematic tool it tries to connect, and then throws this 
Error:
ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

-----
After first installation it worked ok

**Comment by FrenchBen** [comment]
It's possible that VirtualBox's network has failed - A simple restart of Kitematic and the VM should do it:
`docker-machine restart default`
