### ISSUE TITLE
Feature Proposal: Customize machine location

### ISSUE THREAD

**Issue by alexandrev** [docker/kitematic#1380]
Now, the machine is always created at ~/.docker/machine/default/, and this path cannot be changed (or at least, it is not configurable using the GUI). 

The idea is to support any path on your hard disk because it is usual that you don't have the same disk space in your main partition than your "data" partition.

What do you think about it?

**Comment by nathanleclaire** [comment]
`docker-machine` does have a `--storage-path` option (which defaults to `~/.docker/machine`), so if KM wanted to support this feature, it would not be impossible.

**Comment by alexandrev** [comment]
I know it is feasible, but I need to know if the kitematic maintenance/users thinks that it is useful, because if they don't think so there is no reason to do a PR

**Comment by nathanleclaire** [comment]
cc @FrenchBen @jeffdm

**Comment by FrenchBen** [comment]
I think this as a very particular use case - The machine has a default as explained above, which means that the flag would need to be passed with every `docker-machine` command. 

If anything you could symlink the `.docker` dir to be within your data partition and make this all work the same?

**Comment by alexandrev** [comment]
But normally you have all your VM on the same folder or on your own
structure and that is not possible with this approach.

But as I said, if there is no support for the core time, it has no sense to
start any pr.

I'll close the issue.

-- Sent from my mobile phone. Please excuse any typo.

**Comment by FrenchBen** [comment]
It's actually the first time I've heard of someone needing/wanting to move where the VM are stored. 
Thanks for your understanding.

**Comment by alexandrev** [comment]
No problem. Only suggesting.

-- Sent from my mobile phone. Please excuse any typo.

**Comment by FrenchBen** [comment]
Closing for now. We can revisit it if there is a demand for it. :8ball:
