### ISSUE TITLE
Error while pulling image: Get https://index.docker.io/v1/repositories/library/jenkins/images: dial tcp: lookup index.docker.io: no such host

### ISSUE THREAD

**Issue by vitaliedicusara** [docker/kitematic#1382]
No docker images are available because of following issue.

Error while pulling image: Get https://index.docker.io/v1/repositories/library/jenkins/images: dial tcp: lookup index.docker.io: no such host.

Error while pulling image: Get https://index.docker.io/v1/repositories/library/elasticsearch/images: dial tcp: lookup index.docker.io: no such host

...

**Comment by FrenchBen** [comment]
Are you behind a proxy? We have a few common fixes in our wiki:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by souravpatnaik** [comment]
Solution :
[root@xx ~]# docker pull hello-world
Using default tag: latest
Pulling repository docker.io/library/hello-world
**Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: authenticationrequired**


earlier i have set docker proxy in file   /etc/systemd/system/docker.service.d/https-proxy.conf
#[Service]
#Environment="HTTPS_PROXY=http://xxx:8080/"

then i commented this, and sys-reloaded
#sudo systemctl daemon-reload
#sudo systemctl restart docker

then i tried to pull hello-world and i got it.

sometime docker works with proxy also without proxy :(
