### ISSUE TITLE
Unable to docker thru commandline - login failed

### ISSUE THREAD

**Issue by premtechgeez** [docker/kitematic#1386]
I tried to connect to docker hub thru command line and got the below error message. Appreciate your help!

Error response from daemon: invalid registry endpoint https://dockershow/v0/: un
able to ping registry endpoint https://dockershow/v0/
v2 ping attempt failed with error: Get https://dockershow/v2/: dial tcp: lookup
dockershow: no such host
 v1 ping attempt failed with error: Get https://dockershow/v1/_ping: dial tcp: l
ookup dockershow: no such host. If this private registry supports only HTTP or H
TTPS with an unknown CA certificate, please add `--insecure-registry dockershow`
 to the daemon's arguments. In the case of HTTPS, if you have access to the regi
stry's CA certificate, no need for the flag; simply place the CA certificate at
/etc/docker/certs.d/dockershow/ca.crt

**Comment by FrenchBen** [comment]
Looks like you're not using the proper hub - `dockershow` is not a confirmed docker endpoint.
