### ISSUE TITLE
MySQL Downloading Problem

### ISSUE THREAD

**Issue by EMart002** [docker/kitematic#1389]
EHOSTDOWN
EHOSTDOWN
connect
192.168.99.100
2376

I have this problem. In Kitemagic i searched for mysql and wanted to create a Docker instance with the original mysql. When clicking, it gives me this error.

**Comment by FrenchBen** [comment]
It seems that your virtualbox may not be connected properly - Can you close kitematic and issue the following in your terminal?
`docker-machine restart default`

**Comment by EMart002** [comment]
Hi, i restarted my Mac and everything worked fine. Thanks for your help!
