### ISSUE TITLE
Network issues while doing in kitemaic as well as terminal

### ISSUE THREAD

**Issue by albasir4u** [docker/kitematic#1390]
Hi,

am facing issue while installing spark from bigdata university through kitmatic as well as terminal.
Network timed out while trying to connect to https://index.docker.io/v1/repositories/bigdatauniversity/spark/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
Clicking the above link I get the proper json data. Are you behind a proxy? You may need to configure your VM for proper connectivity with the Proxy.
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
