### ISSUE TITLE
ETIMEDOUT ETIMEDOUT 

### ISSUE THREAD

**Issue by avinbond** [docker/kitematic#1391]
connect 192.168.99.100 2376

**Comment by FrenchBen** [comment]
It sounds like your VM has lost it's connectivity

**Comment by faisontw** [comment]
This issue still cannot be fixed by restart docker machine. I don't know what happened.

**Comment by FrenchBen** [comment]
@faisontw you may need to regenerate your certificates
`docker-machine regenerate-certs default`
