### ISSUE TITLE
How can I clean out temporary filles?

### ISSUE THREAD

**Issue by j-ough** [docker/kitematic#1392]
I'm using Kitematic to run Ubuntu for a machine learning project (with Jupyter and ITorch). The container has quickly reached maximum space (20GB), and is now too full to do anything.

Typing df -h at the command line tells me that the partition "none" is using 19GB of space. I assume this is leftover temporary files from previous runs which haven't been cleared for some reason.

How can I clean out this temporary data? I've spent a bit of time installing new packages on the container so I don't want to completely reset it.

I've tried telling the container to reboot from the command line, but it tells me it "Failed to talk to init daemon".

**Comment by FrenchBen** [comment]
Checkout the wiki to re-create the machine with more space:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
