### ISSUE TITLE
The search doesnt find anything with search query "linux"

### ISSUE THREAD

**Issue by ShashankaNataraj** [docker/kitematic#1395]
The search doesnt find anything with search query "linux" whereas web version of docker hub finds it.

**Comment by FrenchBen** [comment]
I don't understand, this is what I get every time I search:
![linux](https://cloud.githubusercontent.com/assets/3965324/12491922/7d6e4a54-c032-11e5-96c7-f8dac8f0af92.png)

Are you properly connected?
