### ISSUE TITLE
Unable to refresh network settings when switching wireless connections

### ISSUE THREAD

**Issue by klousiaj** [docker/kitematic#1396]
A fairly common use case of mine is working on different wireless networks over the course of a day, work, hotspot, home, etc. Unfortunately, I need to restart Kitematic (and therefore default) in order for the new network to be recognized/used.

Is there a way to force docker to refresh the network settings? It would be awesome to have a way to do that through Kitematic via a button press or something like it.

**Comment by FrenchBen** [comment]
The network settings are actually a VBox issue, not a kitematic one - You could 'maybe' get away with doing a vbox reboot:
`docker-machine restart default`

Until we have some machine management within Kitematic, there isn't much we can do. See:
https://github.com/docker/kitematic/wiki/Machine-Management

Closing in favor of machine management discussions
