### ISSUE TITLE
Cant stop/remove containers on Mac (not sure about other OSs)

### ISSUE THREAD

**Issue by kevinduffey** [docker/kitematic#1398]
For some reason, the list on the left shows the running docker containers.. but when I click on the X, it shows stopping.. but never actually stops or removes the container. Not sure if this is a bug or as intended but I assume it should actually stop and remove the container when I click the X?

**Comment by FrenchBen** [comment]
Do you get any errors? The 'X' should remove the container

**Comment by kevinduffey** [comment]
Nope.. just a pop up asking me if I really want to stop/remove it.. which I click yes to. It then either shows me its stopping.. but no log output or anything.. or often times it stays in a running state.

**Comment by FrenchBen** [comment]
For a container to be removed it will need to be stopped first, then removed - Some containers can take some time to shutdown and thus appear for a few seconds after the initial click.

What version of Kitematic are you running? Could you create a small video showing what's going on?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
