### ISSUE TITLE
Feature request - support container linking

### ISSUE THREAD

**Issue by hagmonk** [docker/kitematic#14]
I know there are moves afoot in the docker community to do more sophisticated service discovery, but while that is getting sorted out, basic container linking support would be great.

Additionally, intelligent container restarting based on linked relationships could also be interesting. With my current setup, if I restart my database container I need to restart my whole stack to have it re-recognize the new database container.

**Comment by dtornow** [comment]
+1 for linked containers

**Comment by tslater** [comment]
+1

**Comment by hhcordero** [comment]
+1

**Comment by brunowego** [comment]
+1

**Comment by mfkilgore** [comment]
+1

**Comment by jik1992** [comment]
+1

**Comment by greenkiwi** [comment]
+1

I am guessing I can always drop into bash, but having a mechanism to do this through the UI would be great.

**Comment by arcxyz** [comment]
+1

**Comment by azizur** [comment]
+1

**Comment by chermed** [comment]
+1

**Comment by greenkiwi** [comment]
This feature could be as simple as being able to just provide additional command line args.

**Comment by andredasilvapinto** [comment]
+1

**Comment by vicary** [comment]
+1 service discovery is still not yet settled, we need something.

**Comment by nVitius** [comment]
There's a PR for this in #608, but it hasn't been updated in over a month.

**Comment by FrenchBen** [comment]
Just updated the PR to get it up to date. :)

**Comment by xlight** [comment]
where can I get this version?

**Comment by FrenchBen** [comment]
@xlight Need to get the PR updated and squashed. Hopefully the team can then take a look and see it merged

**Comment by bls20Automic** [comment]
+1

**Comment by klousiaj** [comment]
:+1: 
Any status on this PR?

**Comment by FrenchBen** [comment]
@klousiaj Networking is the new Linking - It'd be a lot better and more functional to get it implemented. 
A proposal was drafted: https://github.com/docker/kitematic/issues/1249
But no one chimed in :[

**Comment by sidharta** [comment]
+1

**Comment by jhgorse** [comment]
In lieu of complex solutions, perhaps a generic addition to the docker command line arguments for any unimplemented functionality in kitematic?

For instance, under Settings->Environment Variables there could be Settings->Other Arguments section for raw docker options typically passed on the command line. Such as --link, in this case.

Also, FWIW, I opened #1990 which is related to this need to link docker containers. Namely, I cannot seem to access the linux vm or native directory for the macOS Sierra docker-beta's dockerfile after setting it up with kitematic, so other ways of accessing the raw dockerfile seem appropriate.

Cheers,
Joe

**Comment by FrenchBen** [comment]
@jhgorse Linking of containers is a bit of an old way to do things - The proper way to do it these days seems to be via networking, where 2 network exist under the same network and thus can communicate. 
There's a feature request to get networking implemented into kitematic, but time has been the enemy so far.

**Comment by jhgorse** [comment]
Networking on os x is broken.
https://docs.docker.com/docker-for-mac/networking/#/known-limitations-use-cases-and-workarounds
https://github.com/docker/docker/issues/22753#issuecomment-243406719

I think the optimal solution is to have a generic docker `run` argument extension as a catchall for unimplemented docker features in kitematic and general first step for testing a new ui wrapped around the existing functionality.

**Comment by FrenchBen** [comment]
@jhgorse it is not broken, it has limitations, which is that it cannot use the `docker0` space, which is essentially `host`. This was used by most in the past to connect the different services, when a first class network would actually do the trick. 
Connection of containers and host-exposed ports is a known issue. If you keep everything in containers, it works.

**Comment by jhgorse** [comment]
@FrenchBen that is an interesting definition of "not broken."

In any case, perhaps this ought to be renamed "docker for linux networking" then or rewritten to avoid the `docker0` interface? https://docs.docker.com/engine/userguide/networking/

**Comment by FrenchBen** [comment]
@jhgorse IMHO broken means it doesn't work at all - The fact that it works with limitations doesn't fit the definition of broken (it works under constraints).

@jhgorse I believe you missed the beginning of the sentence, which says that you communicate between containers via their IP (on the default bridge network) but if you need to communicate using the actual container names (once again using the default bridge network), then linking is used due to a lack of service discovery. 

It then goes on to explain that you can create your own networks:
https://docs.docker.com/engine/userguide/networking/#/user-defined-networks
It then goes on to say that `Each container in the network can immediately communicate with other containers in the network.`

**Comment by alexgalkin** [comment]
+1

**Comment by panga** [comment]
+1

**Comment by daaru00** [comment]
+1

**Comment by bwangfdu** [comment]
+1

**Comment by josedacosta** [comment]
+1
It's clearly missing!
A management of the "links", and a management of "composes"

Here is an example of the Synology Docker:
![image](https://user-images.githubusercontent.com/3801119/27090298-174b92d8-505d-11e7-9057-f566fbb59e21.png)

**Comment by Regner** [comment]
The PR @daaru00 linked was merged and covers this issue. This issue can probably be closed.

**Comment by FrenchBen** [comment]
Thanks @Regner closing
