### ISSUE TITLE
Docker cli tries to execute old shell

### ISSUE THREAD

**Issue by vabue** [docker/kitematic#1401]
Docker Kitematic 0.9.5, Mac OS X El Capitan

After executing Docker cli in iTerm 2.1.4 got:
```bash: /usr/local/bin/fish: No such file or directory```

In history:
```bash -c "clear && DOCKER_HOST=tcp://192.168.99.101:2376 DOCKER_CERT_PATH=/Users/valbudkin/.docker/machine/machines/default DOCKER_TLS_VERIFY=1 /usr/local/bin/fish"```

Fish shell was installed previously but now default shell is zsh:
```echo $SHELL
/bin/zsh```

I also reseted all Terminal.app settings, but it didn't help. Where can I look to set shell for Kitematic to my current shell?

**Comment by FrenchBen** [comment]
Sounds like there are some leftover issues in your bashrc/zshrc/terminal pref. 
I would clear those first.

**Comment by rtorr** [comment]
@vabue I am running into the same issue. Did you have any luck?
