### ISSUE TITLE
PATH is wrong on Windows

### ISSUE THREAD

**Issue by kelemen** [docker/kitematic#1403]
When I spawn a PowerShell instance by clicking on the "DOCKER CLI" button, the *PATH* variable will contain "/usr/local/bin:". It is not just an invalid path but the colon makes the first entry on *PATH* ignored. The problem seems to be in [browser.js](https://github.com/docker/kitematic/blob/53436e81b2d289bf91f3e4321a1ce168d0687ea1/src/browser.js#L13).

ps.: I wanted to send a pull request but given the contribution guide, I cannot build the project. That is, when I run *npm start*, it just shows a blank window, so I cannot verify my change.

**Comment by FrenchBen** [comment]
Did you follow the Kitematic development guide?
https://docs.docker.com/opensource/kitematic/set_up_dev/

**Comment by kelemen** [comment]
I have followed [CONTRIBUTING.md](https://github.com/docker/kitematic/blob/master/CONTRIBUTING.md) which seems to contain what you have linked.

**Comment by FrenchBen** [comment]
It's close, but the docs do specify the NPM version, as it's what we've been using. 
If you're getting a 'white' screen after `npm start` it's more than likely an issue with your code/env

**Comment by kelemen** [comment]
The problem for starting Kitematic was that I had the 64 bit version of npm installed. I fixed that and sent a pull request to fix this issue.
