### ISSUE TITLE
Network timed out while trying to connect to *any package*

### ISSUE THREAD

**Issue by wide-awake** [docker/kitematic#1404]
While trying install ANY package next error appeaser: 
```
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/celery/images. You may want to check your internet connection or if you are behind a proxy.
```

My network is fine and it worked okay before weekend. 
Kitematic running directly on OS X 

UP. Looks like hub is okay https://status.docker.com/ 

UPUP:
If I restart kitematic old package (which frilled with "Network timed" before) will download perfectly okay. But new containers will fail with same error.

**Comment by FrenchBen** [comment]
Seems like an issue with your VM - I would simply issue a restart of it via:
`docker-machine restart default`
