### ISSUE TITLE
Feature Request: Third-party register integration

### ISSUE THREAD

**Issue by gramster** [docker/kitematic#1410]
Note: this is not a dup of #1225 which is about private registries (and hence a dup of #210), which I interpret as being about self-hosted registries. This is really about third-party non-self-hosted registries, such as gcr. It seems smarter to have one app that can integrate with 3rd party registries (and can have Docker first enabled by default) than to have Kitematic being forked or a plethora of similar apps.

**Comment by gramster** [comment]
Ah, I may be misunderstanding how gcr works - that it isn't "a registry" but a host for "registries". So hopefully covered by #210.

**Comment by FrenchBen** [comment]
That's correct - A lot of the details are in my comments:
https://github.com/docker/kitematic/issues/210#issuecomment-156210361

There's a lot under the hood that's not apparent at first sight
