### ISSUE TITLE
Error pulling image from docker.io

### ISSUE THREAD

**Issue by mujo228** [docker/kitematic#1411]
docker run or docker pull requests all return the following error:

Error pulling image (latest) from docker.io/kitematic/hello-world-nginx, Server error: Status 0 while fetching image layer (4a130ef69fe4c11804103d017eecb3af8845c7f3fcf089a2b168a5bf41c12163)

Above attempt was from kitematic GUI.    Following request is from cmd line.

$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b901d36b6f2f: Pulling fs layer
0a6ba66e537a: Pulling fs layer
Pulling repository docker.io/library/hello-world
975b84d108f1: Error pulling image (latest) from docker.io/library/hello-world, Server error: Status 0 while fetching image layer (3f
12c794407e68e515ba7f473a744e748ac8a827a2ea8b33855dec564238b2e5) 473a744e748ac8a827a2ea8b33855dec564238b2e5)
Error pulling image (latest) from docker.io/library/hello-world, Server error: Status 0 while fetching image layer (3f12c794407e68e5
15ba7f473a744e748ac8a827a2ea8b33855dec564238b2e5)

**Comment by FrenchBen** [comment]
It looks like you may have some connectivity issue - can you power cycle the VM and try again?
`docker-machine restart default`

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
