### ISSUE TITLE
Container remains in list if it fails to start and is removed

### ISSUE THREAD

**Issue by timcroydon** [docker/kitematic#1412]
I accidentally mapped a volume that masked an important folder in a docker image and caused the container to fail starting up with a 500 error. I then clicked 'remove container' in Kitematic but it did not get removed from the list.

To reproduce, try something like:

    docker create --name wontwork -v /usr/local/tomcat tomcat

Then start the container. It will fail after a bit because the `/usr/local/tomcat` folder is empty. Click the 'remove' cross in Kitematic and OK. The container remains in the list, although `docker ps` shows it does not exist.

On restarting KM, it still shows in the list, with the error:
<pre><code>no such container
404
no such id: wontwork
</code></pre>

This is in v0.9.5 on Mac.

**Comment by FrenchBen** [comment]
Removing the container should have a proper refresh - A known issue is if the container creation fails, then it can't be removed and shows the 404 you're referring to.

**Comment by leowmjw** [comment]
Same here; getting 404. Kitematic 0.9.5:
```
no such container
404
no such id: c10e2ad749_popitng_common_1
```

**Comment by FrenchBen** [comment]
@leowmjw there's a good chance the container wasn't created properly, but the container list wasn't refreshed. This is a known issue.
