### ISSUE TITLE
Error when downloading image - Linux

### ISSUE THREAD

**Issue by edgr** [docker/kitematic#1413]
I am getting this error whenever I try to download an image. I'm running kitematic on Arch.

EACCES
EACCES
connect
/var/run/docker.sock

Thanks

**Comment by mibamur** [comment]
+1

**Comment by FrenchBen** [comment]
Did you follow the install instructions about having the user account setup correctly?
https://github.com/docker/kitematic/wiki/Early-Linux-Support

**Comment by mibamur** [comment]
`https://github.com/docker/kitematic/wiki/Early-Linux-Support` - Done. Thanks

now is
```
Error: VirtualBox is complaining that the installation is incomplete. Please
run `VBoxManage --version` to see the error message which should contain
instructions on how to fix this error.
```

is terminal answer it or a "node_app"?
