### ISSUE TITLE
Aborted due to warnings.

### ISSUE THREAD

**Issue by twitctor** [docker/kitematic#1414]
I was installing kitematic on ubuntu like the manual say, but i have this error:

Running "newer:babel" (newer) task

Running "newer:babel:dist" (newer) task

Running "babel:dist" (babel) task
Warning: [BABEL] src/actions/AccountActions.js: Unknown option: base.blacklist Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 3.19.0-43-generic
npm ERR! argv "/home/vsrecio/.nvm/versions/node/v4.2.2/bin/node" "/home/vsrecio/.nvm/versions/node/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! Kitematic@0.9.6 start: `grunt`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the Kitematic@0.9.6 start script 'grunt'.
npm ERR! This is most likely a problem with the Kitematic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls Kitematic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vsrecio/kitematic/npm-debug.log

**Comment by twitctor** [comment]
i deleted the folder, and started from scratch and it worked :)

**Comment by FrenchBen** [comment]
:+1: thanks for the update
