### ISSUE TITLE
First download the jenkins failed via Kitematic

### ISSUE THREAD

**Issue by zjx-immersion** [docker/kitematic#1416]
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/jenkins/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
Unfortunately this happens quite a bit when connected from China - It seems that the network is not reliable enough and the disconnect happens from time to time.
If you look at the Docker RC, you'll see that a lot of improvements were made to get the retries/resume to work correctly. 
This will hopefully take care of some of your issues!
