### ISSUE TITLE
cant't connect to docker hub in kitematic in window7

### ISSUE THREAD

**Issue by BecauseofLxcCheckpoint** [docker/kitematic#1417]
I can't log in the docker hub in the kitematic

**Comment by FrenchBen** [comment]
are you using the proper credentials? Are you behind a proxy?

**Comment by BecauseofLxcCheckpoint** [comment]
@FrenchBen yes,I am behind a proxy. I add proxy in the /var/lib/boot2docker/profile. And I can login the dockerhub in commandline. But still can't login the kitematic~!

**Comment by FrenchBen** [comment]
Since you're on 2 different threads, I'm closing this one in favor of the previous mention.
