### ISSUE TITLE
Docker kinematic error: EPROTO EPROTO write

### ISSUE THREAD

**Issue by fazero** [docker/kitematic#1421]
After installation of docker kinematic tool on Win10 with preinstalled VirtualBox 5.0.14 I have an "EPROTO\nEPROTO\nwrite" error while trying to use docker imaged from docker-hub.

![eproto](https://cloud.githubusercontent.com/assets/2446672/12670401/2eb0d01a-c679-11e5-82d9-e206476014e5.png)

![vbox](https://cloud.githubusercontent.com/assets/2446672/12670399/2eae4fd4-c679-11e5-86a2-3fdc44fb32bf.png)

![system](https://cloud.githubusercontent.com/assets/2446672/12670400/2eaffa8c-c679-11e5-8023-410ae24fa567.png)

**Comment by fazero** [comment]
The VM used by docker "default" using DNS provided by local network, but it has some issues, so the solution is "**sudo echo "nameserver 8.8.8.8" /etc/resolv.conf**". Although, the google DNS could be replaced by any else, if it is working properly and accessible.

**Comment by FrenchBen** [comment]
This was also in the wiki: https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#cannot-download-imageconnect
Thanks for confirming that it works

**Comment by rcholic** [comment]
> The VM used by docker "default" using DNS provided by local network, but it has some issues, so the solution is "**sudo echo "nameserver 8.8.8.8" /etc/resolv.conf**". Although, the google DNS could be replaced by any else, if it is working properly and accessible.

I got the same error today, but previously Kitematic worked fine for past few days. I tried to add the nameserver 8.8.8.8 to my default docker machine, but I got permission denied:
```
sudo echo "nameserver 8.8.8.8" /etc/resolv.conf"
```

I know this is an old thread, but what is the working solution as of now 2020? Thanks!
