### ISSUE TITLE
Volume mount path should be independent of User dir

### ISSUE THREAD

**Issue by raeesiqbal** [docker/kitematic#1423]
Why should the local mount path for Docker volumes should be only under User directory?
I have all of my projects in a different partition, so, I cant mount any of them as volume in a container. I even tried making a symlink under User dir pointing to original dir but that didnt work also.

Volume mount path should be independent of User directory.

**Comment by raeesiqbal** [comment]
I'm using Windows 10 x64, Docker version `1.9.1`

**Comment by FrenchBen** [comment]
The issue is that the VM itself doesn't mount the volume/drive - Therefore you end up with a 1/2 mounted volume and no way to really get the data. 
If you would like, subscribe to the PR, which has some of this info:
https://github.com/docker/kitematic/pull/1202
