### ISSUE TITLE
Not able to download the docker image

### ISSUE THREAD

**Issue by bhayarahul** [docker/kitematic#1424]
getting timeout error even though internet connectivity is there

**Comment by nathanleclaire** [comment]
If you try `docker-machine restart default`, does it start working?

**Comment by FrenchBen** [comment]
Thanks @nathanleclaire for chiming in :+1:

**Comment by nathanleclaire** [comment]
NP-- @bhayarahul please re-open if that does not fix

**Comment by nathanleclaire** [comment]
Oops, I don't have issue close permissions on this repo @FrenchBen

**Comment by jofan** [comment]
This worked for me at least
