### ISSUE TITLE
ENHANCEMENT: "Remember me" option for login

### ISSUE THREAD

**Issue by leadbaxter** [docker/kitematic#1425]
It would be nice if the login screen had an option to "Remember me" so I don't have to type my username and password each time.

An EXTRA NICE feature would be for it to get the password from my keychain (OS/X).

As it is, I have a keychain-generated password and I have to go look it up each time. Quite painful. I could make a simpler password, but isn't that kind of defeating the purpose by diminishing security?

**Comment by FrenchBen** [comment]
The login should be saved for your sessions and every other session after that - Are you doing something odd when you quit the app?
What's your homedir structure like?

**Comment by leadbaxter** [comment]
OIC... I logged in, then logged out without quitting the app. Just to see if it was going to remember my password for me (wondering if I'd have to look it up again!)

You're right. If I exit the app while still logged in, I'm still logged in when I relaunch. It was just slightly different than my expectation, but this works.

Thanks for the response!
