### ISSUE TITLE
All containers disappeared from Kinematic GUI [MacOS]

### ISSUE THREAD

**Issue by painhardcore** [docker/kitematic#1426]
At some point, i realized that I can't manage  containers from Kinematic.
Docker cli button not working too, but if launched from MacOS docker cli is working properly and everything work.
MacOS  10.11.3 (15D21)
DockerToolbox-1.9.1i

**Comment by FrenchBen** [comment]
How many containers do you have? Any steps to reproduce this issue?

**Comment by psychemedia** [comment]
I'm seeing this as well - containers have just disappeared (maybe half a dozen or so).
Mac 10.9.5, Kitematic 0.9.5
CLI had stopped launching a terminal window too in an on-running Kitematic (Mac had been hibernated); worked okay on a Kitematc restart, but still no containers?

**Comment by FrenchBen** [comment]
There are some issues with Virtualbox's networking that hopefully are saved in the latest release. 
Can either of you try the latest Toolbox?

**Comment by andrew-w-ross** [comment]
I have the same sort of problem but I just need to start Kinematic shut it down and then turn it on again.

**Comment by FrenchBen** [comment]
The fact that a restart works seems to show that the networking is getting in the way -

**Comment by bryanjcampbell** [comment]
I have this issue too, why is this closed without a fix. I have upgraded to the latest version both of vbox and docker toolbox, still containers are lost.

**Comment by andrew-w-ross** [comment]
@bryanjcampbell I have to agree. Why is this ticket closed?

**Comment by FrenchBen** [comment]
@bryanjcampbell @andrew-w-ross unfortunately the issue is related to Virtualbox not Kitematic - Hence the ticket being closed. 
We usually keep up with the vbox changes and try to update Kitematic as often as possible to get the vbox updates pushed to the users.

**Comment by lokeshcherukuri** [comment]
I faced this issue today. All containers disappeared after Mac restart

**Comment by tmleeek** [comment]
all containers that i created with kitematic is gone its only available through docker cli
