### ISSUE TITLE
"Exec" button seems to include -it flags but doesn't actually connect to terminal.

### ISSUE THREAD

**Issue by andrewgies17** [docker/kitematic#1427]
Pressing the "exec" button in the Kitematic UI (the one near the stop and restart buttons along the top) opens the default terminal (I'm on Mac) as expected. However, when I try to run certain commands, like screen, I get messages telling me I'm not connected to a terminal. Specifically, the end title bar of the terminal window says the following:
`docker exec -it prism sh`

However, when I run certain commands I get the following outputs:
```
# tty
not a tty
# screen
Must be connected to a terminal.
```

The command I'm really trying to run is `screen`. Specifically, I want to attach to a screen session running somewhere else like the following: `screen -x server`. The issue is present anytime I run screen, though.

If I'm not mistaken it should be connected to a terminal as a result of the `-it` flags and these commands should be working.

**Comment by FrenchBen** [comment]
Please see: https://github.com/docker/docker/issues/728
