### ISSUE TITLE
Kitematic doesn't refresh available container list

### ISSUE THREAD

**Issue by EugeneKrapivin** [docker/kitematic#1428]
After pulling and running a container through Kitematic, remove the container using CLI.
The container still exists in the kitematic menu.
Try to remove the entry - you'll get 404 and the entry will not be removed from the list.

**Comment by FrenchBen** [comment]
I'm not seeing this behavior at all and can't replicate - What version of kitematic/virtualbox (toolbox) are you using?

**Comment by EugeneKrapivin** [comment]
I was using an old version of kitematic. Couldn't replicate at home with a fresh installation.

**Comment by FrenchBen** [comment]
@EugeneKrapivin :+1:

**Comment by clenoma** [comment]
I'm having this behavior with docker for mac and latest kitematic.
When I launch docker-compose, I have to shut close Kitematic, and launch it again from Docker for mac menu.
