### ISSUE TITLE
Trouble running vi in 'docker exec bash' via Docker Quickstart Terminal

### ISSUE THREAD

**Issue by alankent** [docker/kitematic#1429]
Reporting a problem I hit in case useful. Fundamentally from Windows I am trying to be able to run 'vi' inside Docker container and have it work correctly without screen being scrambled when you scroll around the document.

How I repeat: 

I run "Docker Quickstart Terminal" from Start menu, use 'vi' on local files, all is good. Terminal/vi works perfectly. echo $TERM reports "cygwin".

I then run "docker exec -i -t my-container bash". TERM variable is xterm. I use vi, screen gets jumbled up. I try "export TERM=cygwin" and try again, screen still jumbled up, then when I exit I get a panic message. (See below.)

So I tried a simpler test. "docker run -i -t ubuntu", similar thing (but no panic). TERM is by default set to xterm and vi does not work very well. I set to cygwin, still does not work (but exiting vi this time did not cause a panic). Note there is a "cygwin" entry in /lib/terminfo/c/cygwin.

Reporting in case the panic is interesting to you, but more fundamentally trying to work out how on Windows I can run 'vi' in a Linux container and have scrolling up/down of the document working.

    oot@52f2ec8258e0:/# panic: runtime error: slice bounds out of range

    goroutine 12 [running]:
    bufio.(*Reader).fill(0xc08204c6c0)
            /usr/local/go/src/bufio/bufio.go:86 +0x2e2
    bufio.(*Reader).WriteTo(0xc08204c6c0, 0x3725b0, 0xc08200ebe0, 0x1c4e, 0x0, 0x0)
            /usr/local/go/src/bufio/bufio.go:449 +0x285
    io.Copy(0x3725b0, 0xc08200ebe0, 0x3748a0, 0xc08204c6c0, 0x0, 0x0, 0x0)
            /usr/local/go/src/io/io.go:354 +0xb9
    github.com/docker/docker/api/client.func-+022(0x0, 0x0)
            /go/src/github.com/docker/docker/api/client/hijack.go:210 +0x1e0
    github.com/docker/docker/pkg/promise.func-+001()
            /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
    created by github.com/docker/docker/pkg/promise.Go
            /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

    goroutine 1 [chan receive]:
    github.com/docker/docker/api/client.(*DockerCli).CmdExec(0xc0820983c0, 0xc08204c
    140, 0x4, 0x4, 0x0, 0x0)
            /go/src/github.com/docker/docker/api/client/commands.go:2713 +0xabc
    reflect.callMethod(0xc0820f1320, 0xc08204fbe8)
            /usr/local/go/src/reflect/value.go:605 +0x180
    reflect.methodValueCall(0xc08204c140, 0x4, 0x4, 0x1, 0xc0820f1320, 0xc082098401,
     0xc0821085a0, 0x5, 0xc08200eb01, 0x365da8, ...)
            /usr/local/go/src/reflect/asm_amd64.s:29 +0x3d
    github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc0820983c0, 0xc08204c130,
     0x5, 0x5, 0x0, 0x0)
            /go/src/github.com/docker/docker/api/client/cli.go:81 +0x385
    main.main()
            /go/src/github.com/docker/docker/docker/docker.go:138 +0xb90

    goroutine 5 [syscall]:
    os/signal.loop()
            /usr/local/go/src/os/signal/signal_unix.go:21 +0x26
    created by os/signal.init-+1
            /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c

    goroutine 11 [chan receive]:
    github.com/docker/docker/api/client.(*DockerCli).hijack(0xc0820983c0, 0x898b90,
    0x4, 0xc08206eb90, 0x4c, 0x1, 0x372580, 0xc08200eb90, 0x3725b0, 0xc08200ebe0, ..
    .)
            /go/src/github.com/docker/docker/api/client/hijack.go:237 +0xd38
    github.com/docker/docker/api/client.func-+015(0x0, 0x0)
            /go/src/github.com/docker/docker/api/client/commands.go:2689 +0x192
    github.com/docker/docker/pkg/promise.func-+001()
            /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
    created by github.com/docker/docker/pkg/promise.Go
            /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

    goroutine 9 [IO wait]:
    net.(*pollDesc).Wait(0xc08210a170, 0x72, 0x0, 0x0)
            /usr/local/go/src/net/fd_poll_runtime.go:84 +0x4e
    net.(*ioSrv).ExecIO(0xc08204a0f0, 0xc08210a060, 0x89b3f0, 0x7, 0x97d8c0, 0xaf, 0
    x0, 0x0)
            /usr/local/go/src/net/fd_windows.go:188 +0x305
    net.(*netFD).Read(0xc08210a000, 0xc08205dc00, 0x400, 0x400, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/fd_windows.go:470 +0x180
    net.(*conn).Read(0xc08204a020, 0xc08205dc00, 0x400, 0x400, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/net.go:121 +0xe3
    crypto/tls.(*block).readFromUntil(0xc0820f08d0, 0x3740f8, 0xc08204a020, 0x5, 0x0
    , 0x0)
            /usr/local/go/src/crypto/tls/conn.go:454 +0xed
    crypto/tls.(*Conn).readRecord(0xc0820642c0, 0x17, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:539 +0x2e1
    crypto/tls.(*Conn).Read(0xc0820642c0, 0xc08201b000, 0x1000, 0x1000, 0x0, 0x0, 0x
    0)
            /usr/local/go/src/crypto/tls/conn.go:904 +0x16d
    net/http.noteEOFReader.Read(0x374660, 0xc0820642c0, 0xc08209e5d8, 0xc08201b000,
    0x1000, 0x1000, 0xc08200aa00, 0x0, 0x0)
            /usr/local/go/src/net/http/transport.go:1270 +0x75
    net/http.(*noteEOFReader).Read(0xc0820c62a0, 0xc08201b000, 0x1000, 0x1000, 0xc08
    201c000, 0x0, 0x0)
            <autogenerated>:125 +0xdb
    bufio.(*Reader).fill(0xc0820ec360)
            /usr/local/go/src/bufio/bufio.go:97 +0x1d5
    bufio.(*Reader).Peek(0xc0820ec360, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/bufio/bufio.go:132 +0xf7
    net/http.(*persistConn).readLoop(0xc08209e580)
            /usr/local/go/src/net/http/transport.go:842 +0xab
    created by net/http.(*Transport).dialConn
            /usr/local/go/src/net/http/transport.go:660 +0xca6

    goroutine 10 [select]:
    net/http.(*persistConn).writeLoop(0xc08209e580)
            /usr/local/go/src/net/http/transport.go:945 +0x424
    created by net/http.(*Transport).dialConn
            /usr/local/go/src/net/http/transport.go:661 +0xcc3

    goroutine 13 [runnable, locked to thread]:
    syscall.WSASend(0x138, 0xc08210a430, 0x1, 0xc08210a418, 0x0, 0xc08210a3e8, 0x0,
    0x0, 0x0)
            /usr/local/go/src/syscall/zsyscall_windows.go:1528 +0xcb
    net.func-+026(0xc08210a3e8, 0x0, 0x0)
            /usr/local/go/src/net/fd_windows.go:515 +0x95
    net.(*ioSrv).ExecIO(0xc08204a0f8, 0xc08210a3e8, 0x89b410, 0x7, 0x97d8d0, 0x1, 0x
    0, 0x0)
            /usr/local/go/src/net/fd_windows.go:166 +0x25d
    net.(*netFD).Write(0xc08210a300, 0xc0820b6000, 0x1e, 0x400, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/fd_windows.go:516 +0x183
    net.(*conn).Write(0xc08204a110, 0xc0820b6000, 0x1e, 0x400, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/net.go:129 +0xe3
    crypto/tls.(*Conn).writeRecord(0xc082064580, 0x17, 0xc082124000, 0x1, 0x8000, 0x
    0, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:748 +0x4fa
    crypto/tls.(*Conn).Write(0xc082064580, 0xc082124000, 0x1, 0x8000, 0x0, 0x0, 0x0)

            /usr/local/go/src/crypto/tls/conn.go:880 +0x418
    io.Copy(0x374c20, 0xc0820f2440, 0x374d78, 0xc08200eb90, 0x40, 0x0, 0x0)
            /usr/local/go/src/io/io.go:364 +0x27f
    github.com/docker/docker/api/client.func-+023(0x0, 0x0)
            /go/src/github.com/docker/docker/api/client/hijack.go:221 +0xe3
    github.com/docker/docker/pkg/promise.func-+001()
            /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
    created by github.com/docker/docker/pkg/promise.Go
            /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

    goroutine 14 [sleep]:
    github.com/docker/docker/api/client.func-+025()
            /go/src/github.com/docker/docker/api/client/utils.go:286 +0x69
    created by github.com/docker/docker/api/client.(*DockerCli).monitorTtySize
            /go/src/github.com/docker/docker/api/client/utils.go:295 +0x163

    akent@L-SJN-20000267 MINGW64 ~/Google Drive/GSD Book/gsd-dev/gsd-sftp
    $

**Comment by FrenchBen** [comment]
I'm running Windows 10 and did the following without any issues:
1. Open Docker Quickstart Terminal
2. Ran `cd My\ Documents` then `vi desktop.ini` to confirm I could view/edit the file
3. Ran `echo $TERM` and confirmed `cygwin`
4. Started a new busybox container with sh: `docker run -itd busbybox sh`
5. Exec'd into the container: `docker exec -it container-id sh`
6. Used `vi etc/groups` saw all groups no problem
7. Ran `echo $TERM` and got `xterm`


Whatever you're doing in your 'container' seems to be causing an issue. If the above scenario works properly, then it's pointing to issues with how you connect or whatever is in your `my-container`.

**Comment by alankent** [comment]
Using 'less' in busybox gives a fatal error and it drops back to Windows terminal emulator window.

    $ docker run -it busybox
    / # less /etc/passwd
    FATA[0062] The parameter is incorrect.
    $

There is no /lib at all in busybox, so no /lib/terminfo etc describing what "xterm" means. Changing TERM to 'xxxx' does the same thing as "xterm". Basically I think busybox is a super cut down version of binaries with the terminal escape sequences hard coded into the binaries (no way to change it). So it is not useful for testing TERM settings. No matter what TERM is set to, it does the same thing.

Try using ubuntu

    $ docker run -it ubuntu
    root@9055e364b93d:/# vi /etc/passwd

I did some copy/paste to make file longer, then tried ^Y and ^E (display one more line at top or bottom of screen) - messes up the screen.

    root@9055e364b93d:/# less /etc/passwd

Did not abort window immediately, but output was only a single page.

    root@9055e364b93d:/# cat /etc/passwd /etc/passwd /etc/passwd /etc/passwd | less

Type 'u' and 'd' to scroll up/down half a page - screen gets messed up quickly.

Looking in /lib/terminfo there are terminal definitions. But 'xterm' (and 'cygwin') does not work well.

Also using vi plays up, but it is worth noting in Ubuntu "vi" is "vim", unlike busybox where "vi" is a special cut down binary with a single terminal type built in.

The fact that 'vi' does work in busybox seems to indicate there is a set of escape sequences that the terminal emulator works with well (ignoring 'less' crashing out for some reason!). I just don't know what terminal type to use for a Linux container that supports TERM settings.

Thanks!

**Comment by FrenchBen** [comment]
`Less` works perfectly fine for me in busybox - I really think you have something going on in your terminal that's causing the issues/crashing. 
Doing:
```
$ docker run -it busybox
/ # less /etc/passwd
```
Actually shows the content of the file for me and I can escape out `q` without any issues at all.

Same thing with the ubuntu image. which actually uses regular `vi` not `vim`.
```
$ docker run -it ubuntu bash
root@1dc5928237d5:/# less /etc/passwd
root@1dc5928237d5:/# vi /etc/passwd
```
I could then navigate with `j` (down) `k` (up) `l` (right) `h` (left)

Seems to be a problem with your system - Try on a fresh machine and report back if it still happens

**Comment by alankent** [comment]
Well I am baffled. I tried on another machine and works perfectly. I will try and reinstall my own laptop. Sorry for the distraction.

**Comment by FrenchBen** [comment]
@alankent no worries, it's sometimes difficult to tell if the software is at fault or something on the machine is causing it. Thanks for the feedback.
