### ISSUE TITLE
tell me how to solve this 

### ISSUE THREAD

**Issue by faizi1407** [docker/kitematic#1431]
Error while pulling image: Get https://index.docker.io/v1/repositories/faizi1407/centos6/images: x509: certificate signed by unknown authority

email back at faizan.panwala@slkgroup.com

**Comment by FrenchBen** [comment]
Looks like you're behind a Proxy?
Try to setup the Proxy env by following the guide:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
