### ISSUE TITLE
We are sorry there seems to be an error

### ISSUE THREAD

**Issue by itsbalamurali** [docker/kitematic#1438]
Error while pulling image: Get https://index.docker.io/v1/repositories/library/mysql/images: dial tcp: lookup index.docker.io on 0.0.0.0:53: read udp 127.0.0.1:53: connection refused.

**Comment by nathanleclaire** [comment]
Please try `docker-machine restart default`

**Comment by itsbalamurali** [comment]
@nathanleclaire  it works! thank you :+1:

**Comment by nathanleclaire** [comment]
:+1:
