### ISSUE TITLE
Kitematic log in for "Connect to Docker Hub" only accepts lower case letters or numbers

### ISSUE THREAD

**Issue by rolfedh** [docker/kitematic#1443]
Ugh! It's rejecting my email, not my password. This isn't a software bug, it's a pair of design issues. 

1) In most login screens, can use your email address and username interchangeably, or they are one and the same thing. Here, you're only accepting the user name. 

2) The position of the red text is ambiguous. It's unclear whether it's flagging the username or password. It's equidistant from the two, and its separated from the username by a line. This gives the impression it's flagging the password. 

These two issues combined had me fooled for 30 minutes. Perhaps you could highlight the offending entry or update the string to say "**Username** must be 4-30 lower case letters or numbers."

Previous description was:
BUG: Kitematic rejects the login attempt, displays an error message: "Must be 4-30 lower case letters or numbers."
![image](https://cloud.githubusercontent.com/assets/350907/12836783/f13ca9e6-cb89-11e5-904b-ea63e8bc6cba.png)

**Comment by nathanleclaire** [comment]
:scream: 

cc @FrenchBen @jeffdm

**Comment by rolfedh** [comment]
Actually, it produces the same error message even though the password contains only lower case letters and numbers.

**Comment by rolfedh** [comment]
Ugh! It's rejecting my email, not my password. This isn't a software bug, its a design issue. In most login screens, can use your email address and username interchangeably, or they are one and the same thing. Here, you're only accepting the user name. The position of the red text is ambiguous. It's unclear whether it's flagging the username or password.

**Comment by jeffdm** [comment]
@rolfedh. Very sorry about this. The errors should be more clear, and login should accept either your hub username _or_ email. Thanks for letting us know!

**Comment by rolfedh** [comment]
No problem. Glad to help.

**Comment by FrenchBen** [comment]
Although we should be able to handle emails, the input does say 'username' :P, similar to the hub login page: 
https://hub.docker.com/login/

As Jeff mention will update the error message to be even more clear.

**Comment by rolfedh** [comment]
@FrenchBen You seem defensive. Does constructive feedback bother you? :P.
The issue was that the username field didn't work like it does on https://hub.docker.com/login/ and many other sites. And both the content and location of the error message were ambiguous. We're all on the same team, trying to make Docker better!

**Comment by arowla** [comment]
I've just been bit by this, as well. Kitematic is not allowing me to log in with my email address. Please keep us updated on the release of this fix! Thanks!

**Comment by hafeez-syed** [comment]
same issue, I have change my password several times so that kitematic could accept my password but it gives me "incorrect authentication credentials" on each attempt. Please help and thanks heaps in advance.

**Comment by rolfedh** [comment]
@arowla @hafeez-syed  The dialog and error message are confusing. Enter your user name, not your email address, in the username field. Your password should work just fine. I hope this helps.

**Comment by hafeez-syed** [comment]
Hi @rolfedh I have been entering username (not my email address) but no success :(

**Comment by rolfedh** [comment]
@hafeez-syed Sorry to ask the obvious, but have you verified that the same username and password combo work when you go to the hub.docker.com **website**?

**Comment by hafeez-syed** [comment]
@rolfedh yes I can log on to docker hub website with same credentials.

**Comment by arowla** [comment]
Username worked for me this time. Thanks, @rolfedh!

**Comment by rolfedh** [comment]
Excellent. I'm glad it worked out!

**Comment by thaddaeus** [comment]
A year later and still no update to either logic or text.

**Comment by FrenchBen** [comment]
@thaddaeus perhaps you should've looked at the latest release notes. 
https://github.com/docker/kitematic/pull/2390
