### ISSUE TITLE
Error from Kitematic

### ISSUE THREAD

**Issue by yalcocer1** [docker/kitematic#1449]
Error while pulling image: Get https://index.docker.io/v1/repositories/yalcocer/yuyu/images: dial tcp: lookup index.docker.io: no DNS servers

**Comment by FrenchBen** [comment]
Sounds like you're having some networking issues. Please see our wiki for common solutions:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#cannot-download-imageconnect
