### ISSUE TITLE
Home directory is not always located under /Users

### ISSUE THREAD

**Issue by extra-0** [docker/kitematic#1450]
As illustrated on the screenshot, on Mac home folder can be located outside system drive (in my case home is on HDD, system is on SSD)
When I tried mounting folders from my home, it didn't work.
When I tried choosing volume folders inside /Users, i got a message that volume should be located inside my Home folder.
Please consider fixing automount or implementing a #809 / #1202 (custom mount folder location)
Thanks.
![screen shot 2016-02-06 at 17 28 36](https://cloud.githubusercontent.com/assets/5904093/12867498/08a3e918-ccf8-11e5-8e30-d781b9f59a23.png)

**Comment by viztastic** [comment]
+1 I am in the same boat.

**Comment by FrenchBen** [comment]
As seen/explained in the PR https://github.com/docker/kitematic/pull/1202#issuecomment-180992712 There's a bit of a manual process to get this working and the main blocker is how Vbox handles the mounts.
Closing in favor of discussion within the PR
