### ISSUE TITLE
failed to register layer: Untar re-exec error: gzip: invalid checksum: output:

### ISSUE THREAD

**Issue by zeyab** [docker/kitematic#1452]
While installing meanjs image, error:

failed to register layer: Untar re-exec error: gzip: invalid checksum: output:

**Comment by FrenchBen** [comment]
There are multiple meanjs images, providing the actual link to the image could help - The above seems like an image error, not an issue with Kitematic

**Comment by zeyab** [comment]
https://hub.docker.com/r/luebken/mean/

**Comment by FrenchBen** [comment]
Last commit is from last year (8/2015) - I'd ping the maintainer to see if there are updates pending
