### ISSUE TITLE
failed to register layer: Untar re-exec error: gzip: invalid checksum: output:

### ISSUE THREAD

**Issue by zeyab** [docker/kitematic#1456]
Error message: 
failed to register layer: Untar re-exec error: gzip: invalid checksum: output:

While using:
https://hub.docker.com/r/asfaltboy/meanjs/

**Comment by FrenchBen** [comment]
Please do not open multiple issues for the same problem - Per our discussion on the other thread, this looks like a problem with the actual image. 
If all official images work out of the box, then please open an issue in the repo for the image above.
