### ISSUE TITLE
Unable to access my private repo on Docker Hub

### ISSUE THREAD

**Issue by Msimoneau** [docker/kitematic#1464]
I'm logged into my Docker Hub account and I can't access my private repo.

Error: Status 403 trying to pull repository msimoneau/portail-base-master: "\"The Repository is Locked, access denied\""

Thank you!

Martin

**Comment by FrenchBen** [comment]
Please login to http://hub.docker.com and look at the status of your account - Make sure that it's been activated and that you can see your repo while doing a `docker search msimoneau/portail-base-master`

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
