### ISSUE TITLE
Random containers showing in Kitematic?

### ISSUE THREAD

**Issue by etweb37** [docker/kitematic#1465]
If I leave Kinematic running for a while I end up with many containers that I didn't knowingly pull in. Is this part of the caching mechanism while I'm building? Is this a hack?

**Comment by FrenchBen** [comment]
`caching mechanism while I'm building` what do you mean by that? Are you running some CLI/Compose commands?

**Comment by etweb37** [comment]
I was not understanding fundamentals... not the first time, not the last.
