### ISSUE TITLE
Connection Aborted by wsarecv

### ISSUE THREAD

**Issue by ManuDeveloper90** [docker/kitematic#1466]
Hi, 

i've got some issues on docker 1.10. and 1.10.1 while executing any of the basic commands on windows 7 enterprise.

$ docker ps
An error occurred trying to connect: Get https://192.168.99.100:2376/v1.22/containers/json: read tcp 192.168.99.1:53868->192.168.99.100:2376: wsarecv: An established connection was aborted by the software in your host machine.

The system is under restriction policy and joined to an enterprise domain.
I don't know if that's the point. I also cannot understand which program is generating the issue.
I'm also analyzing this problem with tech support of my company.

Kitematic sais

EPROTO
EPROTO
write

Is there something i can do to solve this? 
Thanks in advice
Emanuele

**Comment by FrenchBen** [comment]
Do you have any antivirus/firewall running? It looks like it's cutting the connection, which means that you may need to add the VM to the "trusted" list

**Comment by ManuDeveloper90** [comment]
Hi,
I found an article about this same issue.It's fixed simply uninstalling docker deleting .docker folder and installing it again.
So a full reinstallation fixes this.
Thanks
Date: Fri, 12 Feb 2016 12:46:05 -0800
