### ISSUE TITLE
Can kitematic not use port 22 for its internal ssh usage?

### ISSUE THREAD

**Issue by alankent** [docker/kitematic#1469]
Kitematic uses port 22 (ssh) for its own usage. As far as I can tell, that means if I want to connect to any of the docker containers I have to use a port different to 22 in order for ssh to work (e.g. -p 2222:22). That can get quite tricky at times. For example, do an rsync into a container needs something like:

    rsync -avz -e "ssh -p 2222" foo user@192.168.99.100:foo

It can get rather confusing as if you forget the -p command line option, it successfully connects but fails to authenticate. You then have to remember that its because you are talking to a different ssh server.

Rather than making it complex for anyone else using ssh with a Docker container, could kitematic leave port 22 free for developers?

I know "you should use docker exec, not ssh to get into a container". But in some applications ssh is useful/important. It would be nicer if kitematic took on the burden of making sure a different port number was used, rather than impacting developers.

**Comment by alexandrev** [comment]
Hi @alankent, I'm not sure if what you are saying it is right. I think the 22 port it is not used by kitematic but boot2docker, the host OS which the docker daemon is running. So, I don't think kitematic could change that setting for you.

**Comment by alankent** [comment]
I don't know who reserved the port, just that it is reserved. http://blog.bananacoding.com/blog/how-to-connect-to-the-docker-remote-api-using-kitematic-and-boot2docker-for-mac indicated Kitematic was using port 22 to talk to Docker, but I could not find that code in the repo. And it would have been docker that picked the port number it is listening on. So you may be correct.

**Comment by FrenchBen** [comment]
@alankent The VM is what's keeping the port busy (the vm runs boot2docker). Short of changing the port-mapping as you've done, there isn't much more to do. 
If you use the rsync enough, you could also alias the command or create a small shell script to do just that.
