### ISSUE TITLE
Error while pulling image

### ISSUE THREAD

**Issue by guerind** [docker/kitematic#1470]
Error while pulling image: Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:49199->[::1]:53: read: connection refused

**Comment by FrenchBen** [comment]
Are you behind a proxy? Do you have any antivirus running?
I would follow the steps found in the wiki and see if that helps:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes
