### ISSUE TITLE
Kitematic goes crazy when I just suspend and resume windows

### ISSUE THREAD

**Issue by rsantosdev** [docker/kitematic#1472]
Hey Guys,

Wanna check if anybody has the same issue as me, on just suspending windows and resuming it. Not sure if kitematic or virtual box problem.

**Comment by rsantosdev** [comment]
![image](https://cloud.githubusercontent.com/assets/863056/13046785/14205396-d3c2-11e5-8f33-49a752c175bb.png)

**Comment by FrenchBen** [comment]
It's unfortunately a Vbox issue, where the networking bit isn't always brought back up properly. Shutting down kitematic+VM and restarting them does the job.
