### ISSUE TITLE
Issue when creating a new containter and mounting a volume in Kitematic. 

### ISSUE THREAD

**Issue by tomasmelin** [docker/kitematic#1475]
I ran the command:
>docker run --name sonarqube -p 9000:9000 -p 9092:9092 -v docker-sonarqube:/opt/sonarqube sonarqube:5.1

and received this error:
>server error
>500
>Container command not found or does not exist.

**Comment by alexandrev** [comment]
Sorry @tomasmelin when you said that you run the command. Which was the procedure that involves Kitematic? Do you launch the CLI from Kitematic? 

Which output do you receive when you run docker -version ? 

Thx!

**Comment by FrenchBen** [comment]
@tomasmelin sounds like an issue with the image - When I followed the details found on the hub page, and ran the command specified `docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube:5.1` everything worked for me.

**Comment by tomasmelin** [comment]
@FrenchBen when I ran the command you pasted it worked for me aswell. However, once I added the option **-v docker-sonarqube:/opt/sonarqube sonarqube:5.1** it did not work and the error I pasted appeared.

@alexandrew I ran the command in the quickstart terminal and the went into the GUI to edit the mounted folders to be able to edit the files on the host, that's when the crash appeared. 
When I run docker -version I get the following: 

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: NKSE:6GZL:N7AE:47Q5:HBAF:CERC:MHWZ:HWEC:QSVI:FTK5:P2E2:HRM3
Debug mode (server): true
 File Descriptors: 29
 Goroutines: 38
 System Time: 2016-02-16T07:40:15.401096197Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by FrenchBen** [comment]
@tomasmelin you need to mount/map the entire path:
`-v $PWD:/opt/sonarqube`

**Comment by tomasmelin** [comment]
@FrenchBen Thank you for your response. Is 
>§PWD

a general term which I should replace or does it mean something in this special context?

**Comment by FrenchBen** [comment]
should just be your local path, you can check it by doing:
`echo $PWD`
