### ISSUE TITLE
Downloading first image.

### ISSUE THREAD

**Issue by ibNez** [docker/kitematic#1476]
server error
500
error creating aufs mount to /mnt/sda1/var/lib/docker/aufs/mnt/f143bd76977faa37a695287389b4a1c073333bb08d7933fa84c4b52ed00ca953-init: invalid argument

**Comment by alexandrev** [comment]
What task were you trying to accomplish?

**Comment by FrenchBen** [comment]
I would restart the vm and try again: `docker-machine restart default`
