### ISSUE TITLE
Postgres Docker image issue

### ISSUE THREAD

**Issue by msdme** [docker/kitematic#1478]
Hi, i got an error like this when trying to get docker image for postgres:

Error pulling image (latest) from docker.io/library/postgres, Server error: Status 0 while fetching image layer (fa42b668d5b9b8f33530b22653686a58bd39b2efd7518061aa7546e2d23f8f84)

I using Windows 10 OS.
I'm new to docker.
Thanks

**Comment by FrenchBen** [comment]
it's possible that you were disconnected - I would restart the VM to make sure the connection is solid and try again:
`docker-machine restart default`
