### ISSUE TITLE
Dark Theme support

### ISSUE THREAD

**Issue by superherointj** [docker/kitematic#1482]
Please add Dark Theme support to windows app. The application is too bright.

**Comment by FrenchBen** [comment]
Hi @superherointj feel free to submit one - Theme support is currently not in our immediate roadmap.

**Comment by wonea** [comment]
Dark theme support would be brilliant. The application is far too bright for work at night.

**Comment by FrenchBen** [comment]
@wonea if you have an easy way to get this added, I'm all for it!

**Comment by R0dri** [comment]
@FrenchBen I believe I found an easy way, I don't know how to compile all the code to test if modding this variable is on the right path.
it is currently set like:
`@body-bg:               #fff;` (white)
could be changed to:
`@body-bg:               #000;` (black)

https://github.com/docker/kitematic/blob/3d40e1334aae598eff99dbf3910906ed5ad9727b/styles/bootstrap/variables.less#L28

currently running macOS if help to test is needed.

**Comment by EricCanull** [comment]
Created a dark theme style, see my [fork](https://github.com/EricCanull/kitematic).

**Comment by JohSchillerEmnify** [comment]
any chance that this will get implemented with the main application since the fork hasn't recieved updates since 2019?
