### ISSUE TITLE
cannot pull from dockerhub

### ISSUE THREAD

**Issue by phairow** [docker/kitematic#1484]

**Comment by phairow** [comment]
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/node/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by nathanleclaire** [comment]
Try `docker-machine restart && eval $(docker-machine env)` in a terminal to see if that fixes it

**Comment by phairow** [comment]
That worked. Thank you!
On Feb 17, 2016 3:13 PM, Nathan LeClaire <notifications@github.com> wrote:Try docker-machine restart && eval $(docker-machine env) in a terminal to see if that fixes it

**Comment by mrspeaker** [comment]
I came here with the same issue - and doing a search turned up a bunch of us with the same "problem" - perhaps you could add the "have you tried restarting?" or something to the network error message.

**Comment by FrenchBen** [comment]
@mrspeaker It may be needed. Thanks for the suggestion.
