### ISSUE TITLE
Cannot access exposed port of running container in Windows 10 Pro x64

### ISSUE THREAD

**Issue by CyborTronik** [docker/kitematic#1488]
Hi I've installed toolbox 1.10.1.
```
docker run -d --name es elasticsearch
docker run -d -P --name cas1 spotify/Cassandra
docker run -d --link es:elasticsearch --link cas1:cassandra -p 8182:8182 -p 8183:8183 -p 8184:8184 --name titan yubozhao/titan-gremlin
```

Kitematic shows to me that I can access it by ip 192.168.99.100
so I'm trying to check by: ``` curl "http://192.168.99.100:8182?gremlin=100-1" ```
And received connection refused.
When I go into container via docker exec, everything works fine.
Do you know a work around for that?
Maybe a possibility to reconfigure toolbox to have bridge connection(I guess that will allow to access directly the ports of VM)?

**Comment by FrenchBen** [comment]
If you look at the wiki, this is a known issue with Windows 10:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#windows-10

By default it seems that any 'local' IP will not be reachable, unless you add it to the local network whitelist.
