### ISSUE TITLE
Strange error importing orient db container

### ISSUE THREAD

**Issue by Vladm87** [docker/kitematic#1492]
Error pulling image (latest) from docker.io/orientdb/orientdb, Untar re-exec error: exit status 1: output: write /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/classes.jsa: no space left on device

**Comment by FrenchBen** [comment]
Looks like you've maxed out your VM disk space - Please see a possible solution from the wiki:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
