### ISSUE TITLE
Use kitematic to control any docker environment

### ISSUE THREAD

**Issue by Shuliyey** [docker/kitematic#1493]
So far kitematic is designed to manage the docker environments in the Virtual Machine (with the name default) created by the docker tools (for mac and windows).

Is it possible to extend kitematic to be used as a pure GUI to manage any docker environment?

So below would be a possible scenario

I have an docker environment installed on a remote linux host . I want to be able to use kitematic as the GUI to manage this docker environment. :smile:

**Comment by FrenchBen** [comment]
@Shuliyey We've had some discussion on machine management and how to use remote hosts. 
Unfortunately it's quite stale at the moment:
https://github.com/docker/kitematic/wiki/Machine-Management

Feel free to submit a feature request (even better a PR) describing how it should all work.
