### ISSUE TITLE
Error installing tensorflow - Mac OSX 10.11.3

### ISSUE THREAD

**Issue by arvind114** [docker/kitematic#1494]
Error while pulling image: Get https://index.docker.io/v1/repositories/drunkar/anaconda-tensorflow-gpu/images: dial tcp: lookup index.docker.io on 127.0.0.54:53: read udp 127.0.0.1:40707->127.0.0.54:53: read: connection refused

Downloading has been active for > 1hr.  No network issue but download completion status not visible.

**Comment by nathanleclaire** [comment]
When you get error like this, does `docker-machine restart` fix it?

**Comment by nathanleclaire** [comment]
Where is your DNS resolver pointing? e.g. is it going through proxy

**Comment by FrenchBen** [comment]
The restart should fix this, feel free to add more comments here if this doesn't solve it.
