### ISSUE TITLE
Button for shutting down the Linux VM

### ISSUE THREAD

**Issue by Enzo90910** [docker/kitematic#1497]
There should be a button to explicitely shutdown the linux VM. I think the default of not shutting it down when quitting Kitematic is fine, but I should be able to shut it down after I'm done trying stuff out without changing the default behaviour on app quit which is the right one.

**Comment by FrenchBen** [comment]
The button wouldn't work in your use-case, since you've already shutdown Kitematic to do something else and would need to start it back up to shutdown the VM.
Instead you can do: `docker-machine stop default`
