### ISSUE TITLE
Powershell errors on up, down, left, right, backspace, {, } etc

### ISSUE THREAD

**Issue by matteo-bombelli** [docker/kitematic#1498]
**Specs:**

OS: Windows 8.1
LANG: italian
Keyboard: Italian

**Description:**
Sometimes (not every time) i get strange output while pressing keys on my keyboard when i launch exec in some docker images

^H for backspace
^[[A for up
^[[B for down
^[[C for right
^[[D for left

**special chars:**
[nothing] for è é ì ù à ò 

Thank You

**Comment by FrenchBen** [comment]
It could be that the docker images you speak off do not emulate tty as expected - Could you list the images?
This has happened before to other user and it turned out to be a windows config issue (specific settings in PowerShell getting in the way)

**Comment by oldmud0** [comment]
Same here. I've never touched PowerShell settings.

**Comment by FrenchBen** [comment]
the default shell selected is `/bin/sh` - if you switch to something like `/bin/bash` in the container, the arrows should work
