### ISSUE TITLE
http: TLS handshake timeout

### ISSUE THREAD

**Issue by no10pc** [docker/kitematic#1499]
http: TLS handshake timeout

**Comment by syardumi** [comment]
+1. I'm getting a similar problem. In trying to download any repo I'm getting an error like this:

> Network timed out while trying to connect to https://index.docker.io/v1/repositories/jwilder/nginx-proxy/images. You may want to check your internet connection or if you are behind a proxy.

OR

> Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/mysql/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
Are you behind a proxy? If so, please follow some of the steps found in the Wiki:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
