### ISSUE TITLE
After installing Docker Toolbox when I run Kitematic it says "VirtualBox is configured with multiple host-only adapters with the same IP \"192.168.50.1\". Please remove one"

### ISSUE THREAD

**Issue by shahriar1** [docker/kitematic#1500]
I'm new in docker. Your help will be appreciated.
Here is the full error -
`Command failed: /usr/local/bin/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.6.0, build e27fb87,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:50160,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:50164,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: /usr/local/bin/VBoxManage --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.0.14r105127,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | local Boot2Docker ISO version: v1.10.2,(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | Name: vboxnet0,(default) DBG | GUID: 786f6276-656e-4074-8000-0a0027000000,(default) DBG | DHCP: Disabled,(default) DBG | IPAddress: 192.168.50.1,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | IPV6Address: ,(default) DBG | IPV6NetworkMaskPrefixLength: 0,(default) DBG | HardwareAddress: 0a:00:27:00:00:00,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Down,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet0,(default) DBG | ,(default) DBG | Name: vboxnet1,(default) DBG | GUID: 786f6276-656e-4174-8000-0a0027000001,(default) DBG | DHCP: Disabled,(default) DBG | IPAddress: 192.168.50.1,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | IPV6Address: ,(default) DBG | IPV6NetworkMaskPrefixLength: 0,(default) DBG | HardwareAddress: 0a:00:27:00:00:01,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Down,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet1,(default) DBG | ,(default) DBG | Name: vboxnet2,(default) DBG | GUID: 786f6276-656e-4274-8000-0a0027000002,(default) DBG | DHCP: Disabled,(default) DBG | IPAddress: 192.168.50.1,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | IPV6Address: ,(default) DBG | IPV6NetworkMaskPrefixLength: 0,(default) DBG | HardwareAddress: 0a:00:27:00:00:02,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Down,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet2,(default) DBG | ,(default) DBG | Name: vboxnet3,(default) DBG | GUID: 786f6276-656e-4374-8000-0a0027000003,(default) DBG | DHCP: Disabled,(default) DBG | IPAddress: 192.168.56.1,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | IPV6Address: ,(default) DBG | IPV6NetworkMaskPrefixLength: 0,(default) DBG | HardwareAddress: 0a:00:27:00:00:03,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Down,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet3,(default) DBG | ,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },Error with pre-create check: "VirtualBox is configured with multiple host-only adapters with the same IP \"192.168.50.1\". Please remove one.",Opting out of crash reporting.,`

**Comment by FrenchBen** [comment]
If you look at the last line, it says what the error is:
`VirtualBox is configured with multiple host-only adapters with the same IP`

If you only have 1 VM, then you can delete all of the host-only adapters and `docker-machine` will re-create them for you. 
Otherwise follow the instructions here:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99-or-cannot-pull-images

**Comment by shahriar1** [comment]
Thanks a lot. Solved the issue by following the instruction.
