### ISSUE TITLE
Kinematic fails to create a container with 500 server error

### ISSUE THREAD

**Issue by svalleru** [docker/kitematic#1504]
![image](https://cloud.githubusercontent.com/assets/1657324/13411415/bc75c640-def1-11e5-836c-c8ef4f4fd16a.png)

**Comment by FrenchBen** [comment]
Please provide:
* Kitematic version
* Docker version: `docker version`
* Image selected
* Changes to the normal container creation

**Comment by svalleru** [comment]
Kitematic version: 0.10.0
Docker version: docker version
![image](https://cloud.githubusercontent.com/assets/1657324/13420573/44abb674-df3c-11e5-9e45-214d15b528aa.png)
Image selected: svalleru/findsimi
Changes to the normal container creation: None, just clicked on create button from kinematic

interestingly, it's working now! must have been the corporate firewall @ work

**Comment by FrenchBen** [comment]
Good to hear it's working :+1:
