### ISSUE TITLE
ETIMEDOUT and many many errors, very unstable

### ISSUE THREAD

**Issue by pulse14** [docker/kitematic#1507]
I have a lot of error every time I click on something, each time the error is different. 404, 500 from docker hub and so on. VM error etc.. (50 error/day avg.) 

Yesterday, it worked for the first time. But today I have one more error and when I retry, the error stay the same. And now all my containers get deleted, why ?

`ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376`

And it's not my network, nothing changed. 6 hours ago it worked.
I tried to reboot the VM, nothing change.

PS: I'm on a new Win10 install (because can't get Docker working on my last install)

**Comment by pulse14** [comment]
SOLVED

** you must delete all network card ** in virtualbox, delete the vm. Restart kitematic or recreate vm with docker.

**Comment by FrenchBen** [comment]
Thanks for the follow up - This has been documented in the wiki, as it's unfortunately one of the common issue with VBox
