### ISSUE TITLE
New Install On Kitematic El Capitan Can't Download or Run Docker

### ISSUE THREAD

**Issue by imaginethepoet** [docker/kitematic#1509]
I've set it up about 5 times now and nothing has seemed to work yet.   In the main panel I see the following error.

ETIMEDOUT
ETIMEDOUT
connect
192.X.X.100
2376

**Comment by FrenchBen** [comment]
It looks like your vbox network died - Please close Kitematic and restart your VM: `docker-machine restart default`

**Comment by imaginethepoet** [comment]
I appreciate you tried to close this, but that is not the case. This seems to be something with kitematic. I was expecting this to just work. I think that's the whole point of moving this from the command line. A fresh install of this and this is the error I'm getting.

The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings:

So how do I turn of TLSverify on a mac? Is this a setting in kitematic? I'm new to docker so I'm the audience for Kitematic.

**Comment by FrenchBen** [comment]
Are you doing this within a work environment? (aka behind VPN)
See:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

The reason it was closed so quickly is that this is a _VERY_ common issue when moving from a house network to say a coffee shop network and VBox can't adapt. Restarting the VM fixes the issue in 99.999% of the cases.

**Comment by imaginethepoet** [comment]
Nope,  I'm on my own network. I was able to set it up on another machine that is older a Mac.  On my primary Mac  though no luck.  I rebooted to try again and still seeing those errors.

I feel like it may have to be with certs?

**Comment by FrenchBen** [comment]
Can you run these commands:
```
$ docker-machine ls
$ docker-machine env default
```
If at any point you get the cert issue, then simply regenerate them:
`docker-machine regenerate-certs default`

**Comment by imaginethepoet** [comment]
I just did another re-install going on day 3 of this trying to get it to work.

default   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.10.2   

Followed by env command that worked fine.

Then I tried to run docker hello. And got the TLS error. So I ran the regenerate and still get this.

docker: The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Post https://192.168.99.100:2376/v1.22/containers/create: remote error: bad certificate.

**Comment by FrenchBen** [comment]
Can you run the following?
`docker-machine ssh default docker ps` 

This should execute the `ps` from within the VM.
Can you share also:
`env | grep -i "docker"`

**Comment by imaginethepoet** [comment]
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/myname/.docker/machine/machines/default

**Comment by FrenchBen** [comment]
Did the `ps` command work?

**Comment by imaginethepoet** [comment]
This is what shows up when I run the PS

docker-machine ssh default docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by imaginethepoet** [comment]
This is the exact error I'm seeing in my Kitematic - 

https://github.com/docker/kitematic/issues/1221

**Comment by FrenchBen** [comment]
Ok - it's encouraging to see that the daemon is up and running properly and it's only a network issue. 
Did you try to clean up your network adapters as a possible solution seen in this comment?
https://github.com/docker/kitematic/issues/1221#issuecomment-164476650

**Comment by imaginethepoet** [comment]
I did see the item about cleaning network adapters, but wasn't sure what that meant. There were no steps to do that.

**Comment by FrenchBen** [comment]
When Vbox sets up the VM it creates a bunch of host-specific networks. You can see them by opening the `Virtualbox.app` and going to `Preferences` then `Network`
Ideally there should only be 1 Host-only network adapter created, but Vbox can sometimes get confused and create a LOT of them - It's safe to delete them all and re-create the VM so that it creates the only 1 it needs:
![host-only](https://cloud.githubusercontent.com/assets/3965324/13580324/a7a12b46-e46f-11e5-9630-0c2c71c63b9a.png)

**Comment by imaginethepoet** [comment]
I wanted to get an update here. I found the setting you were talking about and I only see one vbox image network adapters. I went back to kitematic and still it just hangs. When I click on create "hello" world it just says "connecting to docker hub" but does not do anything (eventually timed out)

So then I was thinking let me see if everything is running ok in the VM.

So I opened the vm and issued the command line tool and was able to pull the remote docker hello world and get it working. (command line inside the VM).

It has to be something that is preventing the virtual from talking to kitematic. I also used the CLI to see if that would do anything and same time out issue.    

This is a tricky one!

**Comment by FrenchBen** [comment]
@imaginethepoet I can't remember if you went through it, but I would check the host-only settings:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99-or-cannot-pull-images

Issues as you describe are usually network related where VBox isn't really doing its job (hence the issue with Kitematic connecting)

**Comment by imaginethepoet** [comment]
I tried several of the items on that page and still no luck. I'm going to try a few more things.

**Comment by FrenchBen** [comment]
Let me know - seems that your system has something peculiar about it that's preventing it from working properly.

Another possible test would be to Uninstall everything and create a new OSX user. Login as that user and try the Docker Toolbox again.
If everything is working as expected than you've narrowed it down to your user config

**Comment by canfixit** [comment]
I have the same problem. Has this been solved?

**Comment by clearsitedesigns** [comment]
Nope - never got it solved.

**Comment by FrenchBen** [comment]
@canfixit @clearsitedesigns @imaginethepoet  Since vbox seems to cause some issues, feel free to signup for the Docker Beta: beta.docker.com
