### ISSUE TITLE
Unable to create the weblogic12.2.1

### ISSUE THREAD

**Issue by jlbuenosvinos** [docker/kitematic#1512]
Error while pulling image: Get https://index.docker.io/v1/repositories/iwanttobefreak/docker-weblogic1221/images: dial tcp: lookup index.docker.io on 141.143.196.21:53: server misbehaving

**Comment by FrenchBen** [comment]
I was able to pull the image without any issue:
<img width="499" alt="weblogic" src="https://cloud.githubusercontent.com/assets/3965324/13481514/2a7371c4-e09b-11e5-9dac-01195a9d762a.png">


I would close Kitematic and restart the VM before trying again: `docker-machine restart default`
