### ISSUE TITLE
Network timed out

### ISSUE THREAD

**Issue by self-creative** [docker/kitematic#1513]
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/jenkins/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
If you're behind a proxy, please see:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

Otherwise I would recommend restarting the VM: `docker-machine restart default`
