### ISSUE TITLE
Kitematic Containers Missing

### ISSUE THREAD

**Issue by ashton02** [docker/kitematic#1514]
Improper shutdown of Kitematic results in lost containers

**Comment by adrian7** [comment]
@ashton02 I have encountered the same issue. However restarting Kitematic brought all containers back. 
os: Mac OS X 10.11.3

**Comment by ashton02** [comment]
Os: Windows 10.    My experience happened upon inappropriate shutdown of the computer. Maybe some internal corruption occurred.

**Comment by FrenchBen** [comment]
What do you consider 'improper shutdown'  Can you provide steps to replicate?

**Comment by ashton02** [comment]
Improper shutdown during installation of an image ,  I believe this happen bc my host machine lost power supply.

**Comment by FrenchBen** [comment]
I believe for most cases a simple restart of Kitematic + VM does the trick. 
Being able to recover from corruption would be on the VM side of things, IMHO
