### ISSUE TITLE
Trying to pull logstash image, but it has been failing with errors since yesterday

### ISSUE THREAD

**Issue by sheaman** [docker/kitematic#1515]
image logstash:latest

message from Kitematic
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/logstash/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
There were some connection latency on the repos around that time - I would recommend closing down kitematic and then restarting the vm: `docker-machine restart default`
