### ISSUE TITLE
Support for iterm2 version 3

### ISSUE THREAD

**Issue by hildjj** [docker/kitematic#1516]
Version 3 of iterm2 has been announced: https://www.iterm2.com/version3.html, which includes breaking changes to its AppleScript API.

The applescript in `Contents/Resources/resources/terminal` will need to be updated.  Here is the new script that you need:

```applescript
tell application "iTerm"
  activate
  tell current window
    create tab with default profile command "bash -c \"$CMD\""
  end tell
end tell
```

**Comment by FrenchBen** [comment]
@hildjj thank you for the changes, there was a recent PR that was merged to prevent breaking changes found in the 2.9+ release. 
https://github.com/docker/kitematic/pull/855

Can you see if the 2.9 change fixes it for you in iTerm3?

**Comment by monowai** [comment]
Kitematic (master) is working against the latest beta build of iTerm - 2.9.20160313

Yay - one less command to remember.
