### ISSUE TITLE
Error pulling image (latest) from neo4j

### ISSUE THREAD

**Issue by hvandenb** [docker/kitematic#1519]
Getting the following error when pulling down the neo4j image:

Error pulling image (latest) from neo4j, Driver aufs failed to create image rootfs 3c3e582d88fad41cd2fc62d98ab54d4199030bff57b76a55c66b6946173909fa: open /mnt/sda1/var/lib/docker/aufs/layers/a582cd499e0ff0b0a2af94dbaef5f56fce1935b7c01429074c2d5abd1ea23d5a: no such file or directory

**Comment by FrenchBen** [comment]
I would restart the VM and see if the error persists: `docker-machine restart default`

Closing this for now, but feel free to re-open it if you still experience errors
