### ISSUE TITLE
No chance to run a "npm run release" on Windows

### ISSUE THREAD

**Issue by alexandrev** [docker/kitematic#1521]
When I try to execute npm run release to create a packaged version of Kitematic for all the supported platforms on a Windows host I get the following erorr:

```
Running "shell:sign" (shell) task
>> 'codesign' is not recognized as an internal or external command,
>> operable program or batch file.

Running "shell:zip" (shell) task
>> 'ditto' is not recognized as an internal or external command,
>> operable program or batch file.
Warning: Done, with errors: command "ditto -c -k --sequesterRsrc --keepParent ./dist/Kitematic\ \(Beta\)-darwin-x64/Kite
matic\ \(Beta\).app release/Kitematic-Mac.zip" (target "zip") exited with code 1. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 10.0.14279
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "release"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! Kitematic@0.9.5 release: `grunt release`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the Kitematic@0.9.5 release script 'grunt release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Kitematic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Kitematic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Kitematic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\GitHub\kitematic\npm-debug.log
```

That seems to be related that some of the tools using to do the release version are not "universal or internal tools" so they only are on Linux/Mac environment and not on Windows.

**Comment by FrenchBen** [comment]
I think that's the expected behavior as most of the release tools used were implemented with a Mac in mind. 
Feel free to update it so that Windows can build its own release. We usually do both Mac+Windows in 1 run, so it made sense to build the Windows release using Mac tools, as it's usually easier than the opposite.

**Comment by alexandrev** [comment]
IMHO I think we should allow Windows users to be able to release its own version. I think it should the idea of using multi-platform dev environment. I'll keep you posted about the PR.

**Comment by FrenchBen** [comment]
:+1:

**Comment by alexandrev** [comment]
I've created PR https://github.com/docker/kitematic/pull/1529

**Comment by henriquebremenkanp** [comment]
I may be wrong, but I think this is not a windows only problem. 
I just ran `npm run release` on mac and it failed the windows build too.

https://github.com/docker/kitematic/blob/master/Gruntfile.js#L37
So I removed this block to ignore it and get my mac binaries. Linux was ok too.

**Comment by FrenchBen** [comment]
@henriquebremenkanp  The release process has some dependencies that need to be satisfied - All releases happen on a Mac, so your edit shouldn't get in the way, although it does build both (mac+win)

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
