### ISSUE TITLE
Problems working on docker in VPN

### ISSUE THREAD

**Issue by ggovindan** [docker/kitematic#1527]
I am trying to pull some images hosted on my companies website. It does not work when I am on VPN. Is there a specific setting that needs to be configured for docker to work behind VPN?

**Comment by FrenchBen** [comment]
@ggovindan Please see our possible solutions in the wiki:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by mchiang0610** [comment]
@ggovindan are you using this on a Mac? If so, please ping me at mchiang@docker.com, and we might be able to give you another tool to try to resolve this issue.

**Comment by ggovindan** [comment]
Hi Michael,
Thanks for your response. I am using mac and I have this problem. Please
let me know how to resolve this.
Regards,
Guru

**Comment by mchiang0610** [comment]
@ggovindan Get in touch with me through email. I will be able to connect you with a private beta.
