### ISSUE TITLE
Can not access remote repository

### ISSUE THREAD

**Issue by slavash** [docker/kitematic#1528]
Network timed out while trying to connect to https://index.docker.io/v1/repositories/slavash/ecweb55w/images. You may want to check your internet connection or if you are behind a proxy.

The URL responses with error: "The Repository is Locked, access denied"

**Comment by FrenchBen** [comment]
This looks like a private repository which I unfortunately can't check. I would recommend a quick reboot of your VM first and see if that solves the issue:
`docker-machine restart default`
