### ISSUE TITLE
Unable to download bigdatauniversity/spark image for docker

### ISSUE THREAD

**Issue by bhavyakv** [docker/kitematic#1530]
1. "Network timed out while trying to connect to https://index.docker.io/v1/repositories/bigdatauniversity/spark/images. You may want to check your internet connection or if you are behind a proxy."
2. "no such image
404
No such image: bigdatauniversity/spark:latest"

I'm getting these 2 errors when I'm trying to download spark image form docker.

**Comment by FrenchBen** [comment]
The `latest` tag does exist for that image, it's surprising that you got a 404 - More than likely your network connection isn't solid and the source of the download issue. 
https://hub.docker.com/r/bigdatauniversity/spark/tags/

The image is 2GB, please make sure that you have a good connection prior to downloading it.

**Comment by bhavyakv** [comment]
Thanks for the timely reply. I was on a pretty good network. Now that
you've confirmed the image's there, I'll try a couple of more times.

Thanks,
Bhavya
