### ISSUE TITLE
Kitematic TOS contains a broken link tests

### ISSUE THREAD

**Issue by pmario** [docker/kitematic#1535]
Kitematic TOS https://kitematic.com/terms-of-service/ contains a broken link text at:

 - section 3.1 see: http://www.docker.com/privacy.html
 - section 9.4 last line in the pragraph, contains a link, that shows a blank page on FF latest win 10

**Comment by FrenchBen** [comment]
Thanks for the heads-up, the website is more or less retired and thus is a non-issue.
