### ISSUE TITLE
Kitematic lose VM when pc shutdown

### ISSUE THREAD

**Issue by heidiks** [docker/kitematic#1536]
I lose my VM when kitematic is running and my pc is unexpectedly shut down

$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

**Comment by FrenchBen** [comment]
That's somewhat expected as the VM state isn't cleanly shutdown - I would issue a VM restart to get things back in order: `docker-machine restart default`
