### ISSUE TITLE
Featurerequest: Make the size of the VMDisk flexible, please!

### ISSUE THREAD

**Issue by thorstensiefert** [docker/kitematic#1538]
I'am using Docker excessively -  which means I use many (and large) images for development. Today I tried to load an exported Docker image (Magento with large DB) in my Macs Docker and surprisingly ran out of VMs diskspace.
I fixed it by creating a new default machine (see Issue #825).

It would be really great if you could add an option on the desired VMs disksize into kitematics setup routine.

**Comment by FrenchBen** [comment]
Unfortunately this is all tied to the VMDisk supported by VirtualBox. Until vbox supports a good flexible schema, it wont be possible. 
Additionally this could be dangerous as a VM could completely take over a hdd - Most VM managers force you to set the disk size
