### ISSUE TITLE
Unable to run tests on Windows.

### ISSUE THREAD

**Issue by Bigguy34** [docker/kitematic#1545]
I have been unable to successfully run tests on windows. I am probably missing something really simple. But when I try to run `npm test` I get this
` FAIL  __tests__\Util-test.js
Runtime Error
Error: Failed to get mock metadata: kitematic\node_modules\core-js\modules\$.global.js`

Any ideas. Sorry if this isn't the right spot to log this issue, as this is not an issue with Kitematic.

**Comment by Bigguy34** [comment]
I was able to fix it, by putting `  "<rootDir>/node_modules/core-js"` in the `  "unmockedModulePathPatterns"`, it is included with part of my other PR[https://github.com/docker/kitematic/pull/1544] if interested

**Comment by FrenchBen** [comment]
Thanks for the PR and overall contribution to the project :+1:  - it's all been merged
