### ISSUE TITLE
Mac OS X 10.11 Support

### ISSUE THREAD

**Issue by kennetham** [docker/kitematic#1547]
Does Docker Toolbox have issues on OSX?

I tried the command line to 'docker pull repo' and Kitematic, I have been getting an error "Error while pulling image: Get https://index.docker.io/v1/repositories/gogs/gogs/images: dial tcp: lookup index.docker.io on 127.0.0.54:53: read udp 127.0.0.1:49279->127.0.0.54:53: read: connection refused" Any reason what this could might have been?

Thanks

**Comment by FrenchBen** [comment]
Looking at the IP it seems you're behind a vpn or have customized something beyond the original toolbox - I would look at the wiki pages:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
