### ISSUE TITLE
No such image: bigdatauniversity/spark:latest (tag: latest)

### ISSUE THREAD

**Issue by Prabu87** [docker/kitematic#1548]
I'm trying to download "bigdatauniversity/spark" from Docker- Kitematic-Alpha.
I'm getting below error message:
no such container
404
No such image: bigdatauniversity/spark:latest (tag: latest)

**Comment by Prabu87** [comment]
![spark error message](https://cloud.githubusercontent.com/assets/17840036/13778716/6a130e0e-ea85-11e5-8b0d-b46ae8440168.jpg)

**Comment by FrenchBen** [comment]
The image you're requesting is quite large ~2GB - I make sure that you're on a solid network before downloading it:
https://hub.docker.com/r/bigdatauniversity/spark/tags/

Does getting it via the command line work? `docker pull bigdatauniversity/spark:latest` ?

**Comment by Prabu87** [comment]
I'm trying to download from Docker Kitematic(Alpha). once its downloaded , then I could use
docker pull bigdatauniversity/spark:latest

**Comment by Prabu87** [comment]
Kitematic (GUI)
Start Kitematic in Docker folder

type bigdatauniversity in the search box to filter the Docker Hub catalog to Big Data University provided images

Click on Create button on the spark image to create Docker container using this image.

**Comment by FrenchBen** [comment]
I understand this - I was wondering if you had the same result when you did it from the command line?

**Comment by benpickles** [comment]
I'm getting a similar error.

![screen shot 2016-03-16 at 14 30 02](https://cloud.githubusercontent.com/assets/3637/13815735/a3f9110a-eb83-11e5-9fc1-e9c7053b1a1a.png)

Also when I try to search from the command line:

```sh
$ docker search elasticsearch
Error response from daemon: Get https://index.docker.io/v1/search?q=elasticsearch: dial tcp: lookup index.docker.io on 172.16.0.1:53: read udp 172.16.0.1:53: i/o timeout
```

But it seems to work with curl:

```sh
$ curl https://index.docker.io/v1/search?q=elasticsearch
{"num_pages": 68, "num_results": 1677, "results": ...
```

**Comment by mixxmac** [comment]
I noticed when I got this error, sometimes you need to click on the elipsis and change which tag to pull (i.e. if latest doesn't exist). Not sure if it will help here though (since the latest tag does exist).

<img width="278" alt="kitematic-spark1" src="https://cloud.githubusercontent.com/assets/351702/13819521/208ea4b4-eb70-11e5-9e50-eb28df97c295.png">
<img width="279" alt="kitematic-spark2" src="https://cloud.githubusercontent.com/assets/351702/13819523/208f922a-eb70-11e5-9c71-1e06ee6e24e2.png">
<img width="278" alt="kitematic-spark3" src="https://cloud.githubusercontent.com/assets/351702/13819522/208f48ba-eb70-11e5-880f-a287973bd97e.png">

**Comment by FrenchBen** [comment]
make sure that before you run it in the terminal you issue:
`eval $(docker-machine env default)`

thanks @mixxmac for the input, it's true that for certain images getting the proper Tag helps.

**Comment by benpickles** [comment]
My problem seems to have fixed itself and running `$ docker search elasticsearch` now also works...

**Comment by Prabu87** [comment]
FrenchBen,
Worked in command line by " docker pull bigdatauniversity/spark:latest". When trying to start Daemon

" docker run -d --hostname bigdatauniversitySpark --name bdu_spark -P -p 8080:8080 -p 8081:8081 bigdatauniversity/spark:latest /etc/bootstrap.sh -d"

Getting below error:
7ff967bf8aee81b2f55fbd0db8e525649dfb70c5cdfd801d680c2d5eb15d33e7
Error response from daemon: Cannot start container 7ff967bf8aee81b2f55fbd0db8e525649dfb70c5cdfd801d680c2d5eb15d33e7: [8] System error: exec: "C:/Program Files/Git/etc/bootstrap.sh": stat C:/Program Files/Git/etc/bootstrap.sh: no such file or directory

**Comment by FrenchBen** [comment]
Didn't have any issues running it here (osx):
`docker run -d --hostname bigdatauniversitySpark --name bdu_spark -P -p 8080:8080 -p 8081:8081 bigdatauniversity/spark:latest /etc/bootstrap.sh -d
d413fc81f2073203b2de5c96d4a4ac1fda382a405303ba1e1dec1173a6095138`

Do you have some specific shell setup? I don't have a windows machine to try this on unfortunately

**Comment by Prabu87** [comment]
docker run -d --hostname bigdatauniversitySpark --name bdu_spark -P -p 8080:8080 -p 8081:8081 bigdatauniversity/spark:latest /etc/bootstrap.sh -d
Error response from daemon: Conflict. The name "bdu_spark" is already in use by container 7ff967bf8aee. You have to delete (or rename) that container to be able to reuse that name.

I dont have specific shell setup. Now I'm getting error response?

**Comment by FrenchBen** [comment]
error because the previous setup stopped working but isn't removed. You need to stop/remove it first:
`docker stop bdu_spark && docker rm bdu_spark`
