### ISSUE TITLE
rserver: ERROR system error 98 (Address already in use)

### ISSUE THREAD

**Issue by jrowen** [docker/kitematic#1549]
When I run the rocker/rstudio dockerfile from Kitematic, I am seeing the address error message below repeat indefinitely.  I believe this message indicates a [port error](http://stackoverflow.com/questions/31081426/initctl-unknown-instance-error-after-rstudio-conf-change).
```
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] conf: executing... 
[cont-init.d] conf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
rserver[134]: ERROR system error 98 (Address already in use); OCCURRED AT: rstudio::core::Error rstudio::core::http::initTcpIpAcceptor(rstudio::core::http::SocketAcceptorService<boost::asio::ip::tcp>&, const string&, const string&) /home/ubuntu/rstudio/src/cpp/core/include/core/http/TcpIpSocketUtils.hpp:103; LOGGED FROM: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/server/ServerMain.cpp:438
```
If instead I run the docker file from the CLI, 
```
docker run -d -P rocker/rstudio
```
everything works fine and I see it listed in Kitematic using the docker generated name.  I can stop and start the container without issue, and I don't see any error messages.

I'm using Docker Toolbox 1.10.3 on Windows 10.

**Comment by FrenchBen** [comment]
Sounds like the port is already in use somewhere - what's the output of  `docker ps -a` ?

**Comment by jrowen** [comment]
Here's what I'm seeing when I run via Kitematic.  I deleted and reloaded the containers, issue persists.
```
PS C:\Program Files\Docker Toolbox> docker ps -a
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS                      PORTS                     NAMES
156af4cfff3a        rocker/rstudio          "/init"             2 minutes ago       Exited (0) 41 seconds ago                             awesome_hypatia
7cf8441bb2f6        rocker/rstudio:latest   "/init"             3 minutes ago       Up 36 seconds               0.0.0.0:32794->8787/tcp   rstudio
```

**Comment by FrenchBen** [comment]
The output looks correct - If look at the error output, it's actually a `rocker/rstudio` error output and not a docker related error. 
The error that the port was already in use from docker would look like:
`docker: Error response from daemon: failed to create endpoint nauseous_mayer on network bridge: Bind for 0.0.0.0: 8787 failed: port is already allocated.`

**Comment by jrowen** [comment]
I agree that the error is coming from the container, but I don't understand why.  In Kitematic I just search for the container and choose create and then see the error when it starts.  In the CLI I just enter the command noted above.  In neither case do I change the dockerfile or the VM.  Is there something in my Kitematic or VM settings that could be causing the port issues?  Thanks.
