### ISSUE TITLE
Arangodb container on Mac crashes

### ISSUE THREAD

**Issue by MCarroll** [docker/kitematic#1554]
Running the default official Arangodb container. Click on the gear in the Volumes Section in the Kinematic window and get a dialog window: 

"Enable all values to edit files? This may not work with all database containers." 

When you select the "Enable Volumes" button the container shutdowns with the following error: 

"touch: cannot touch '/var/lib/arangodb-apps/_rwcheck_f65878134f5f': Permission denied"
We seem to not have proper rw access to /var/lib/arangodb-apps/. Please make sure that every mounted volume has full rw access for user arangodb (uid=999(arangodb) gid=999(arangodb) groups=999(arangodb))

Then the container will not start and you have to completely reset it by running:

 docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 -d --name arangodb-instance -d arangodb

 docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 --name my-app --link arangodb-instance:db-link arangodb

Thanks

**Comment by FrenchBen** [comment]
This is an issue with Virtualbox and mapping of user volumes - There are currently no known solution to this issue, unless you'd like to add a user `arangodb` with the above UID of `999` and give it access to the folder you're trying to map.
