### ISSUE TITLE
Lost VM after restart

### ISSUE THREAD

**Issue by bienenf** [docker/kitematic#1555]
Hello,

I restarted Kitematic, and I don't have the previous VM/Container i used to have,

Any idea how to retrieve them ?

Thank you
Yves

**Comment by FrenchBen** [comment]
Restarting kitematic would not delete the VM or any containers associated with it. Unless you clicked on the button that said 'Delete VM and Retry'
You can check the list of VM you currently have setup by run the following command in a terminal : `docker-machine ls`

**Comment by WaitNkill** [comment]
I know this is old and closed, but I experience the same issue when i have installed everything from scratch with machine_storage_path set to a different drive.
