### ISSUE TITLE
Network Timed Out 

### ISSUE THREAD

**Issue by byteshiva** [docker/kitematic#1563]
I'm unable to connect to docker, I'm getting the below error.
```
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/ubuntu/images. You may want to check your internet connection or if you are behind a proxy.
```

**Comment by FrenchBen** [comment]
If you are behind a proxy please check the wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
