### ISSUE TITLE
EPROTO EPROTO write: https://hub.docker.com/r/suriyaakudo/suriyaa/

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [docker/kitematic#1564]
I got a Kitematic program error:

```error
EPROTO
EPROTO
write
```

> I want to download my image from Docker Hub: https://hub.docker.com/r/suriyaakudo/suriyaa/.

![screenshot 2016-03-22 16 57 29](https://cloud.githubusercontent.com/assets/5073946/13958123/31b65ece-f04f-11e5-814f-28ac8c636bda.png)

----

I check my docker version in CMD and got this following output (in English & German):

```cmd
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Suriyaa>docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.

C:\Users\Suriyaa>
```

----

I also tired to create a windows batch script under "`C:\Program Files\Docker Toolbox\kitematic_proxy.cmd`" with the below script, replacing "YOUR_PROXY" with the http://host:port of my own proxy ([after this](https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes)):

```notepad++
set proxy=http://localhost:2376
SET HTTP_PROXY=%proxy%
SET HTTPS_PROXY=%proxy%
for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
SET NO_PROXY=%DOCKER_HOST%
set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
cd Kitematic
Kitematic.exe
```

**Comment by FrenchBen** [comment]
The `EPROTO` error is usually linked to a Vbox network connectivity issue - I would issue a VM reboot to fix the problem: `docker-machine restart default`
Regarding the CLI call of `docker version` it will not work until you issue the proper `docker-machine env default` command

**Comment by SuriyaaKudoIsc** [comment]
#### Commands
`docker-machine ls` works fine in CMD.

I get this error output after running `telnet localhost 2375`:
```bash
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Suriyaa>telnet localhost 2375
Verbindungsaufbau zu localhost...Es konnte keine Verbindung mit dem Host hergestellt werden, auf Port 2375: Verbindungsfehler

C:\Users\Suriyaa>
```

And for the `docker-machine ssh default` command I get this error output:
```bash
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
```

**Comment by SuriyaaKudoIsc** [comment]
Issue continues #1568!
