### ISSUE TITLE
docker error in windows 10

### ISSUE THREAD

**Issue by devansdev** [docker/kitematic#1566]
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/mysql/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
If you're behind a proxy you will have some issues with connectivity. 
Please see our workaround in the Wiki:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
