### ISSUE TITLE
Error Contacting docker hub

### ISSUE THREAD

**Issue by byteshiva** [docker/kitematic#1567]
Any idea why its not connecting to docker hub.

![image](https://cloud.githubusercontent.com/assets/10637299/13985038/2e34af9a-f120-11e5-9938-719ffae19d68.png)

**Comment by byteshiva** [comment]
![image](https://cloud.githubusercontent.com/assets/10637299/13985125/d61985fa-f120-11e5-84b0-f9441eda7dd9.png)

**Comment by FrenchBen** [comment]
Are you behind a proxy? Any certificate issue is usually a sign of a proxy manipulating it.
See:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by byteshiva** [comment]
I'm still having the same issue. I'm unable to login to hub docker via kitematic BETA mac application

```
$docker-machine ssh default
$sudo vi /var/lib/boot2docker/profile

EXTRA_ARGS='
--label provider=virtualbox --insecure-registry :443

'
PROXY='http://proxy-server.com:8080'
export http_proxy=$PROXY
export HTTP_PROXY=$PROXY
export HTTPS_PROXY=$PROXY
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem

$docker-machine stop default
$docker-machine start default
Starting "default"...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Machine "default" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
$docker-machine env


```

![image](https://cloud.githubusercontent.com/assets/10637299/14008315/777dd43a-f1a5-11e5-8238-78eb1497bb4e.png)
