### ISSUE TITLE
Using Kitematic 0.5.10 beta

### ISSUE THREAD

**Issue by susanwu88** [docker/kitematic#1569]
I tried to pull the minecraft and nginx and both services couldn't connect to the Docker Engine.

Susan

**Comment by FrenchBen** [comment]
@susanwu88 Could you provide details of the error? Was this from within Kitematic?

**Comment by susanwu88** [comment]
yes, it was Kitematic. I'll try to take a screenshot.

One more thing, does Kitematic automatic install the Docker Engine 1.5 by any chance.
I went and got the Docker Engine 1.10 from github...

Thanks!

**Comment by pmario** [comment]
You can have a look at the docker toolbox: https://www.docker.com/products/docker-toolbox

**Comment by FrenchBen** [comment]
thanks @pmario for the help - Closing this for lack of update since the latest changes. 
@susanwu88 Feel free to re-open as needed.
