### ISSUE TITLE
Throws same Error Connecting Hub Docker

### ISSUE THREAD

**Issue by byteshiva** [docker/kitematic#1571]
Added my comment @ https://github.com/docker/kitematic/issues/685

Related to https://github.com/docker/kitematic/issues/1567

I'm still having the same issue. I'm unable to login to hub docker via kitematic BETA mac application

```
$docker-machine ssh default
$sudo vi /var/lib/boot2docker/profile

EXTRA_ARGS='
--label provider=virtualbox --insecure-registry :443

'
PROXY='http://proxy-server.com:8080'
export http_proxy=$PROXY
export HTTP_PROXY=$PROXY
export HTTPS_PROXY=$PROXY
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem

$docker-machine stop default
$docker-machine start default
Starting "default"...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Machine "default" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
$docker-machine env


```

![image](https://cloud.githubusercontent.com/assets/10637299/14008315/777dd43a-f1a5-11e5-8238-78eb1497bb4e.png)

**Comment by FrenchBen** [comment]
No need to keep creating issues, you can simply re-open the original one with all of the details in it - 
Can you show the output of:
```
$ env | grep -i "proxy"
```

Also did you follow that mentioned starting kitematic from the CLI so that the env vars are applied? ( I didn't see it in your console output above)

**Comment by byteshiva** [comment]
Am i missing something here? How do i run Kinematic from CLI?
```
docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
``

**Comment by FrenchBen** [comment]
@byteshiva that's correct you're missing this part of the instruction:
```
cd Kitematic
Kitematic.exe
```
Via your terminal/powershell, you navigate to where Kitematic `"C:\Program Files\Docker Toolbox\kitematic\"` is installed then start Kitematic `Kitematic.exe`.

**Comment by byteshiva** [comment]
Please note I'm using MaC OS not windows, where do i find the kitematic file in mac os.
