### ISSUE TITLE
docker pull ansible/ansible: Tag latest not found in repository docker.io/ansible/ansible

### ISSUE THREAD

**Issue by avbeuzekom** [docker/kitematic#1573]
$ docker pull ansible/ansible
Using default tag: latest
Pulling repository docker.io/ansible/ansible
Tag latest not found in repository docker.io/ansible/ansible

**Comment by FrenchBen** [comment]
That's the expected behavior - the image you are requesting does not have a 'latest' tag. 
Please open an issue with the image owner:
https://hub.docker.com/r/ansible/ansible/tags/
