### ISSUE TITLE
server error 500

### ISSUE THREAD

**Issue by eqielb** [docker/kitematic#1576]
![500 server error](http://ww2.sinaimg.cn/large/674ad70fgw1f2bprwwelyj20u00iw0un.jpg)

**Comment by eqielb** [comment]
finally i use Docker Hub speeder to download images

**Comment by FrenchBen** [comment]
Can you elaborate on what Docker Hub speeder is?

**Comment by eqielb** [comment]
[daocloud docker speeder](https://dashboard.daocloud.io/mirror) @FrenchBen

**Comment by FrenchBen** [comment]
Thanks!
