### ISSUE TITLE
kitematic not getting removed completely from os x 10.11.1

### ISSUE THREAD

**Issue by kandekar** [docker/kitematic#1583]
removed kitematic from app folder, os x. kitematic did not get removed completely. it still opens. but unsuccesfully creating virtual linux on my mac.
then i read this thread told to run docker-machine rm dev, which i did, the output said, INFO[0000] machine does not exist, assuming it has been removed already

but when i run docker -v, i still see Docker version 1.5.0, build a8a31ef

which means docker is still not removed from my machine, how to successfully delete it.

**Comment by FrenchBen** [comment]
If you removed kitematic and placed it in the trash, it removes kitematic, unless you have another copy somewhere.
I would check your OSX file system to see where it's installed. 

Official uninstall docs can be found here:
https://docs.docker.com/engine/installation/mac/#uninstall-docker-toolbox
