### ISSUE TITLE
Kinematic fails with Erro:403 while pulling a public repository (screenshot attached)

### ISSUE THREAD

**Issue by svalleru** [docker/kitematic#1584]
![image](https://cloud.githubusercontent.com/assets/1657324/14131019/4a5ea6a0-f5ec-11e5-8cc3-9eac62e7ec52.png)

**Comment by gabhi** [comment]
Looks like that repo doesnt exists now.

**Comment by gabhi** [comment]
found similar issue on https://forums.docker.com/t/pull-error-the-repository-is-locked-access-denied/2178/7

Solution: 
all new users referring to this problem, this problem are mainly caused if a user has his Global Settings41 set to Private and they push new repository using Docker CLI. Then it instantly creates a repository, set the visibility to Private and then gets locked, if you do not have free private repo.
We will fix this issue of not getting unlocked on its own when converted back to public on our end but until then if you encounter such problem, please change your default repository visibility to Public and push or create private repo from WebUI and then push to that private repo.

**Comment by svalleru** [comment]
So, private(default)-->public fails, ha. Thx for looking into this, I'll try with default public option.

**Comment by FrenchBen** [comment]
@svalleru the default is for your repo to be public - Manually setting it to private is what seems to create the issue seen above. If you want to keep the default of private repo, then all you need to do is purchase a plan that has private repos: https://www.docker.com/pricing#/repo-5

Thanks @gabhi for the help. 

side note: Github behaves in a similar way, where a private repository is locked until billing is updated.
