### ISSUE TITLE
Unable to start tyk gate way container

### ISSUE THREAD

**Issue by Shoaib627** [docker/kitematic#1595]
Container Logs
<INFO[0000] Hostname set:                                
INFO[0000] Connection dropped, connecting..             
INFO[0000] Setting up Server                            
INFO[0000] --> Standard listener (http)                 
INFO[0000] Loading API Specification from /opt/tyk-gateway/apps/app_sample.json 
INFO[0000] Detected 1 APIs                              
INFO[0000] --> Loading API: Tyk Test API                
INFO[0000] ----> Tracking: (no host)                    
INFO[0000] ----> Checking security policy: Token        
INFO[0000] Loading uptime tests...                      
INFO[0000] Gateway started (v1.9.1.1)                   
INFO[0000] --> Listening on port: 8080                  
ERRO[0001] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0001] Connection to Redis failed: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0002] Could not EXPIRE key: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
INFO[0002] [HOST CHECK MANAGER] Starting Poller         
WARN[0011] Reconnecting                                 
ERRO[0012] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0013] Could not EXPIRE key: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0014] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0014] Connection to Redis failed: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
WARN[0024] Reconnecting                                 
ERRO[0025] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0025] Could not EXPIRE key: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0027] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0027] Connection to Redis failed: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0037] Could not EXPIRE key: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
WARN[0037] Reconnecting                                 
ERRO[0039] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0040] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0040] Connection to Redis failed: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0048] Could not EXPIRE key: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
WARN[0050] Reconnecting                                 
ERRO[0052] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0054] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0054] Connection to Redis failed: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0061] Could not EXPIRE key: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
WARN[0064] Reconnecting                                 
ERRO[0065] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0066] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0066] Connection to Redis failed: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0073] Could not EXPIRE key: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
WARN[0076] Reconnecting                                 
ERRO[0078] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0079] Redis disconnected or error received, attempting to reconnect: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
ERRO[0079] Connection to Redis failed: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving 
WARN[0089] Reconnecting                                 
ERRO[0092] Could not EXPIRE key: dial tcp: lookup redis on 10.5.7.20:53: server misbehaving >

**Comment by FrenchBen** [comment]
This looks like an issue with the container setup, not Kitematic - Please submit an issue to the owner's repo:
https://hub.docker.com/r/tykio/tyk-gateway/
