### ISSUE TITLE
Cannot connect to Docker Hub

### ISSUE THREAD

**Issue by roboncode** [docker/kitematic#1596]
I can view the list of repos but each time i try to download one it times out with...

ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

**Comment by FrenchBen** [comment]
You need to make sure you are on a solid connection to download images. I would also recommend restarting the VM if you've changed network: `docker-machine restart default`

**Comment by roboncode** [comment]
It was down. I went back up later that day. It was not a connection issue. Thanks
