### ISSUE TITLE
Setting DNS `nameserver`'s for container

### ISSUE THREAD

**Issue by ls12styler** [docker/kitematic#1597]
Hi,

I can't find a way to pass the `--dns` flag to a container so that I can configure `resolv.conf` entries. I have to ssh to the container and set the contents myself.

This became apparent as I've tried to create some Consul servers/clients and wanted to use `127.0.0.1` as a nameserver. According to the docker docs, I cannot set them in the docker-machine either because, and I quote, "the daemon filters out all localhost IP address `nameserver` entries from the host’s original file". 

Any help would be appreciated.

Thanks.

**Comment by FrenchBen** [comment]
There was a previous Feature request/PR for this, but there was almost no users who chimed in or 👍 the feature and thus it was never published. 
Feel free to re-implement it properly and create a feature request explaining how you're going about it.

see our contributing guidelines here: https://github.com/docker/docker/blob/master/CONTRIBUTING.md#conventions


Old pr: https://github.com/docker/kitematic/pull/834
