### ISSUE TITLE
Not able to download

### ISSUE THREAD

**Issue by xs2github** [docker/kitematic#1599]
Hi,

I have tried multiple times to download the  fluxcapacitor/pipeline, but have failed all the times. Always when it is between 70-80% finished. Kindly let me know if there is another way to download.

-Ritesh

**Comment by FrenchBen** [comment]
@xs2github what happens when you do from a terminal:
`docker pull fluxcapacitor/pipeline`

**Comment by xs2github** [comment]
Well, I was able to pull through kitematic. You can close the issue. Btw,
when I ran that it also ended up getting stuck.
