### ISSUE TITLE
Issue with docker command line on OSX

### ISSUE THREAD

**Issue by leetercola** [docker/kitematic#1600]
From Kitematic launching docker CLI or launching it manually I cannot connect or issue any commands to the docker host. When trying to build I get the error below.
ERROR 
An error occurred trying to connect: Post https://192.168.99.100:2376/v1.22/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&shmsize=0&ulimits=null: Tunnel Connection Failed

I've read a few issues about making sure that CLI environment is correct for the terminal session with and `eval $(docker-machine env)` but that hasn't helped. I've also issues a `docker-machine restart` followed by the eval just to make sure everything was kosher. 

I'm running OSX El Capitan version 10.11.3, Kitematic version 0.10.0 and oh-my-zshell. I've tried connecting with a standard bash executable as well using the steps above but it doesn't seem to make a difference even after completely scrubbing my machine of anything docker related and reinstalling.

**Comment by FrenchBen** [comment]
The correct commands is:
`eval $(docker-machine env default)`

**Comment by leetercola** [comment]
bash-3.2$ cd Documents/Development/dockerImage/
bash-3.2$ eval $(docker-machine env default)
bash-3.2$ docker build - < Dockerfile 
An error occurred trying to connect: Post https://192.168.99.100:2376/v1.22/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&shmsize=0&ulimits=null: Tunnel Connection Failed
<img width="1337" alt="screen shot 2016-04-06 at 10 22 53 am" src="https://cloud.githubusercontent.com/assets/581174/14322209/9a513c36-fbe1-11e5-9c60-e31d03f8959b.png">

The docker machine is running, I ran the command as you stated and when I build I still get the same error

**Comment by FrenchBen** [comment]
Couple of things:

* Can you share that Dockerfile
* Can you issue a `docker ps` to confirm the connection worked
* Do you have any env set? `env | grep -i "docker"`

If kitematic can connect properly to the VM and you can create containers from Kitematic, then this is the wrong place for the issue to live.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
