### ISSUE TITLE
vmwarefusion VM overwritten with vbox VM on launch

### ISSUE THREAD

**Issue by hotgazpacho** [docker/kitematic#1607]
I've been working with docker-machine and docker-compose to set up a development environment for my team. For various reasons *(corporate VPN)*, we've opted to use VMmare Fusion as the provider when creating the docker-machine image. So, I used docker-machine to create this VM, named "default" and using the vmwarefusion provider, and started playing around with containers. Then I downloaded Kitematic (via homebrew cask) today, fired it up, and when I went to run a command in one of my docker containers, it failed, stating the VM was not up. I ran `docker-machine ls`, and it listed the "default" virtual machine as using the vbox provider. Kitematic apparently clobbered my vmwarefusion VM and stood up a vbox VM in its place, taking all my containers (and their data) with it.

I would not expect merely launching Kitematic to clobber my docker setup.

**Comment by FrenchBen** [comment]
Kitematic only removes the VM if you click on 'Reset VM and start setup' button. I believe the error message received then points to the fact that no default VM could be used. 
The name collision hasn't happened in the past, as most people setup their vm via Kitematic.

**Comment by hotgazpacho** [comment]
The thing is, all I did was launch Kitematic. That's it.

I don't doubt that you think it *shouldn't* overwrite the VM, but what I experienced is that Kitematic removed my vmware VM and replaced it with a vbox VM.

**Comment by FrenchBen** [comment]
Looking through the code I see what happened. 
If you look at the following line:
https://github.com/docker/kitematic/blob/master/src/utils/SetupUtil.js#L140
Kitematic did not detect any 'existing' VM and this deleted anything that could've existed. This is in place if Kitematic attempted to create a VM and failed - It's not a true VM per vbox standard and simply exists in the void.
Unfortunately your edge case of naming the VMWare VM 'default' falls in that category. 

There has been some (although stale) discussion around introducing machine management within Kitematic, but no work has been done towards it in a while. 

Closing this for now but will flag it for archival purposes.
