### ISSUE TITLE
No idea why I can't download images from docker hub

### ISSUE THREAD

**Issue by JakobEng** [docker/kitematic#1609]
So I get this error, when I run `docker run` and `docker build`.
`docker: dial tcp: lookup registry-1.docker.io on 192.168.2.1:53: no such host.`
I have version 1.10.3 of docker.
When I search on this error many says it is something to do with a proxy. I have search for it and all proxy detection websites says I don't have any so I don't think that is the problem. I uninstall and install docker tool box to and updated osx to 10.11.4. It is strange, for a few days ago everything worked and now i does not.

I really hope someone can help me with this annoying problem,
cheers.

**UPDATE**
Now there happen something even more strang I run
`$ docker run hello-world`
and I worked. 2 minutes later and I removed all containers run on the hello-world image and then removed hello-world. I run the command above again and I got the error again. I did not do anything else then what I described.

**Another UPDATE**
So now if I try many times (about 5) it works. First 4 fails with the error above and then 1 work. Anyone have an idea why?

**Comment by FrenchBen** [comment]
If you are behind a proxy that is causing some issues, look at our wiki for common fixes:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by JakobEng** [comment]
But I'm not. I don't know why but it will work sometimes and other times it keep failing me.

**Comment by FrenchBen** [comment]
VBox's network is a bit sensitive - If you are on 1 network and 'move' to a different network, there's a chance the VM will lose connectivity. 
If you restart the VM after connecting, it should work as expected.

**Comment by JakobEng** [comment]
So I have a desktop and haven't changes network. Here is the different errors I get with `docker run hello-world`:
`docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https://auth.docker.io/token?account=jakobeng&scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.65.1:53: no such host.`

`docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c5/c54a2cc56cbb2f04003c1cd4507e118af7c0d340fe7e2720f70976c4b75237dc/data?Expires=1468116651&Signature=DcMG9BizyfFAXvFKBpFfoq2IV3EmRtrg5QuiZXicJzGdTSmECT-U4Hj8MqrZ5vs6VDLDJ2gtJxS6djWBEs3bsAok2L8YFcPO8y7cDgfwdcj3vLXMkxSDyBH3~YuZRcbAyHQjfUzxpoztLusYX99p4WYy2KZsT0pO7yI1Zv~Rl8U_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: no such host.`

`error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c5/c54a2cc56cbb2f04003c1cd4507e118af7c0d340fe7e2720f70976c4b75237dc/data?Expires=1467738345&Signature=Eb~8-GGFBUxS6wE~GNZEOxCrCK5wBaBTkIH18TODSpgUHlpvoVx~W4UrRFAReoQ-LSVIzOZPJiXn4RTKMzKCqhLgAPGgAhU7xOuaBgnrwyccAD9pKMjm0pi879hIbHBWY~-kVNdd7XEaQiQ5ClX4ukKkY~RoXthaQs~-~kTy54k_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: DNS message ID mismatch`

`docker: Tag latest not found in repository docker.io/library/hello-world.`

Less than half the time it works though.

When I do to preference > network > Then I login > advanced > proxy  and look through every proxy at the left and there is no information about any proxy. I have also talk with a friend and he sad it could be something with the DNS server but not what precisely. In preference > network the DNS ip is 192.168.2.1 but grayed out.
I use 1.12.0-rc3 but had the same problem with docker 1.11 which I used when I started this issue here. And I use macOS (as it is called now), 

 I glad to give more information about the problem if there is something I have forgot.

Thanks in advance

**Comment by FrenchBen** [comment]
Do you have any env variables that perhaps get in the way?
`env | grep -i "docker"`

**Comment by JakobEng** [comment]
When I type that I get nothing back

**Comment by FrenchBen** [comment]
have you tried this again? There were a few changes to the hub that may have caused this.

**Comment by JakobEng** [comment]
IT WORKS! If you work at docker please say thank you to them who fixed this please. Now I can get to work with Docker! Hours of work ahead...
