### ISSUE TITLE
Kitematic on windows - Ubuntu:latest "untar re-exec error"

### ISSUE THREAD

**Issue by dannystaple** [docker/kitematic#1611]
Error message:

`failed to register layer: Untar re-exec error: exit status 1: output: no such file or directory`.

No further logs appear to be available.
Attempting "docker run -it ubuntu" from the Cli (Docker cli powershell button) results in it working as expected.

**Comment by FrenchBen** [comment]
Could be that a bad layer was downloaded and pulling it from the cli cleared it. 
Unless this is something 💯 reproducible it's difficult for us to fix
