### ISSUE TITLE
open /mnt/sda1/var/lib/docker/tmp/GetImageBlob254158797: read-only file system

### ISSUE THREAD

**Issue by StillSlippery** [docker/kitematic#1612]
With a docker container running (ohmage/base) and trying to install a new docker container (ohmage/server) get the following error:

![kitematic-error](https://cloud.githubusercontent.com/assets/127503/14360520/a1f88f0a-fcab-11e5-90fc-fdfac7c6b5da.png)

This also happens is the other containers are stopped.  

After that error I get this one:

![kitematic-error2](https://cloud.githubusercontent.com/assets/127503/14360670/588b714c-fcac-11e5-8f11-4e5fcc1608e0.png)

Retrying set-up does not help.

Is this a bad Docker container?

**Comment by StillSlippery** [comment]
Took a "delete VM and retry setup" and a system (Mac OS) restart and "delete VM & retry setup" again for this problem to clear.

**Comment by FrenchBen** [comment]
Thanks for the issue - Read-only file system issues have been seen in the past. I believe some of it is usually due to a bad initial setup, or vbox not doing it's job. 
I'll close this for now since you got it working but will add the proper label for archival puposes
