### ISSUE TITLE
cann't download img

### ISSUE THREAD

**Issue by maphey** [docker/kitematic#1614]
Error while pulling image: Get https://index.docker.io/v1/repositories/library/ubuntu/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:45688->[::1]:53: read: connection refused

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by maphey** [comment]
Think you, It is work.
