### ISSUE TITLE
ETIMEDOUT error

### ISSUE THREAD

**Issue by collinsauve** [docker/kitematic#1615]
Getting this error attempting to start several new containers:

> ETIMEDOUT
> ETIMEDOUT
> connect
> 192.168.99.100
> 2376

![image](https://cloud.githubusercontent.com/assets/157603/14390541/a81333ba-fd85-11e5-80ad-bdbee6545cd4.png)

**Comment by FrenchBen** [comment]
You need to make sure you are on a solid connection to download images. I would also recommend restarting the VM if you've changed network: `docker-machine restart default`

**Comment by collinsauve** [comment]
Can the messaging be improved here?  The current message is cryptic and not very helpful.

**Comment by FrenchBen** [comment]
@collinsauve Yes, there is some work in progress for detecting the ETIMEDOUT and supply the above command.
