### ISSUE TITLE
Error: Status 403 trying to pull repository caskdata/cdap-standalone: "Account is not Active"

### ISSUE THREAD

**Issue by dapplewang** [docker/kitematic#1616]
Error: Status 403 trying to pull repository caskdata/cdap-standalone: "Account is not Active"

**Comment by FrenchBen** [comment]
Two things can happen when this is displayed:
1. You did not activate your account, but used the Hub Login in Kitematic
2. You created a private repo without any billing information and are now trying to pull from it. 

Fix the above and you'll be all set
