### ISSUE TITLE
Error downloading new container

### ISSUE THREAD

**Issue by arkanjoms** [docker/kitematic#1620]
Getting this error attempting to download new container:

> EPROTO
> EPROTO
> write

this error occur with any container in kitematic

![docker_error](https://cloud.githubusercontent.com/assets/1004876/14407812/1fe9c2ea-fea4-11e5-8ea0-78d1424a962d.png)

**Comment by FrenchBen** [comment]
You need to make sure you are on a solid connection to download images. I would also recommend restarting the VM if you've changed network: `docker-machine restart default`
