### ISSUE TITLE
Error attempting to download Cloudera QuickStart container

### ISSUE THREAD

**Issue by nashguy** [docker/kitematic#1624]
### Expected behavior
Container would fully download

### Actual behavior
received an error and download failed.
failed to register layer: Untar re-exec error: exit status 1: output: write /home/cloudera/workspace/.metadata/.plugins/org.eclipse.jdt.core/1839635701.index: no space left on device

### Steps to reproduce the behavior

  1. Using Kinematic, attempt to instantiate the container.
  2. ...

**Comment by FrenchBen** [comment]
Looks like the VM that you're using for development is now full (see: `no space left on device`) - I would clean-up the different images that may be linguering or re-create the VM with more space on it. 

See:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
Please note the above will create a VM that will completely erase your existing one.
