### ISSUE TITLE
Tag latest not found in repository docker.io/pcomte/darkvision

### ISSUE THREAD

**Issue by PhilippeComte** [docker/kitematic#1630]
### Expected behavior
download darkvision
### Actual behavior
error missing tag latest
### Information about the Issue
Is there something missing ? 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Latest tag doesn't exist - this is the expected behavior:
https://hub.docker.com/r/pcomte/darkvision/tags/
