### ISSUE TITLE
Kitematic has hardcoded "latest" tag

### ISSUE THREAD

**Issue by MatthiasGa** [docker/kitematic#1632]
example "phpmentors/symfony-app", tag "latest" not exist 
"solution" >> 
1. seen error message 
2. back and select tag
>> why is a not existing tag selected by default?

**Comment by FrenchBen** [comment]
This is the default behavior of Docker - Kitematic allows you to select the appropriate tag within the UI. 
Best practice points to having your latest image tagged as such. Unfortunately not all project follow that principle (the image listed above included).

Feel free to open an issue within the owner's repo https://github.com/phpmentors-jp/docker-images, or look up the existing tags when not using an official image.
