### ISSUE TITLE
Unable to properly run kitematic behind a corporate proxy: unable to verify the first certificate

### ISSUE THREAD

**Issue by jmborer** [docker/kitematic#1633]
### Expected behavior
Access the Docker image hub when sitting behind a corporate web proxy.

### Actual behavior
Error message "unable to verify the first certificate"

### Information about the Issue
We are sitting behind a corporate proxy server that uses NTLM authentication and uses its own "self sign" certificate that it includes for every HTTPS call into the certification chain as a CA authority.

Usually it is possible to fix the issue by adding our proxy certificate into a trusted CA database. To start kitematic we launch it with the following bat:

set proxy=http://user:password@webproxy.example.corp:8080
SET HTTP_PROXY=%proxy%
SET HTTPS_PROXY=%proxy%
for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
SET NO_PROXY=%DOCKER_HOST%
set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
cd Kitematic
Kitematic.exe

**Comment by jmborer** [comment]
Here is the image
![error](https://cloud.githubusercontent.com/assets/6607350/14562858/a35bbfb6-030e-11e6-9638-fa84c49427de.png)

**Comment by FrenchBen** [comment]
Did you also follow these instructions?
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes#add-proxy-settings-to-vm

**Comment by jmborer** [comment]
Thanks for your reply, but my question is related to Kitematic. As I explained above I found out how to use our proxy, but the problem is still the inserted certificate which is self signed. Everything works within my docker runtime. The problem remains in Kitematic as well as in docker-machine. Corporate proxies are always creating problems with tools heavily relying on the use of internet...

**Comment by FrenchBen** [comment]
`Everything works within my docker runtime` = You're able to do `docker pull hello-world` from the command line, but it doesn't work via kitematic?

**Comment by jmborer** [comment]
Excatly. In kitematic i cannot view the catalog for example.

Envoyé de mon iPad

Le 19 avr. 2016 à 01:47, French Ben <notifications@github.com> a écrit :

Everything works within my docker runtime = You're able to do docker pull
hello-world from the command line, but it doesn't work via kitematic?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/docker/kitematic/issues/1633#issuecomment-211635917>

**Comment by jmborer** [comment]
Maybe my question should be: where are the CA certs used by kitematic stored?

**Comment by FrenchBen** [comment]
Kitematic doesn't store any of it - it uses the VM that it provisions via `docker-machine`

To confirm, from a terminal, you can do a `docker pull hello-world` but when you open kitematic using the *same* terminal, you're getting errors?

**Comment by jmborer** [comment]
Yes, I am getting even more errors:
1) I can pull projects from the repos
2) kitematic it doesn't seem to use the proxy settings from the docker instance at all as you can see below.
![image](https://cloud.githubusercontent.com/assets/6607350/14670334/2ee24dea-06dc-11e6-888d-fce9778906e0.png)
The closest I could get to connect the internet with kitematic is it by using the afermentioned "bat solution" where I set the proxy settings in ENV variables. However the intemediate CA certificate is missing.

**Comment by jmborer** [comment]
If you follow instructions:
![image](https://cloud.githubusercontent.com/assets/6607350/14671375/f7ddc892-06e0-11e6-8b5c-db4ffcc61969.png)
It is actually the same as creating a start.bat for kitematic that reads:
`set proxy=http://user:password@webproxy.example.corp:8080
SET HTTP_PROXY=%proxy%
SET HTTPS_PROXY=%proxy%
for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
SET NO_PROXY=%DOCKER_HOST%
set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
cd Kitematic
Kitematic.exe`

Again, same issue "unable to verify the first certificate" in the catalog view (search for Docker Images). As I said: kitematic doesn't use the proxy and certificate settings of the docker machine. It uses the ones you provide it with env variables. Problem: the intermediate CA certificate is missing because the code begind kitematic knows how to handle proxies, but not CA certificates or at least I don't know where this certs DB is stored...

**Comment by jmborer** [comment]
Looking at the code, I discovered Kitematic is Node.js and Electron based app. 

The proxy settings are used in the library https://www.npmjs.com/package/request that is used by Kitematic. It won't use any proxy settings set in a docker machine. 

I will continue to search where certificates are used. Libraries or the electron (chromium) engine? I already tried some eletron switches without success. https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

I am totally new to  Node.js and Electron, so it may take a while, but I expected the those chromium switches could be used with the Kitematic.exe. Is it just a rebranded chromium by the way?

**Comment by jmborer** [comment]
So according to the documentation of request (https://www.npmjs.com/package/request#proxies), it is possible to specify a trusted CA certs file by using for example:

request.get({
    url: 'https://api.some-server.com/',
    agentOptions: {
        ca: fs.readFileSync('ca.cert.pem')
    }
});

Are such calles made in Kitematic? 

I seached though the code for agentOptions and couldn't find it. So I suppose an external CA cert PEM encoded file it is not supported (yet?) by Kitematic. This should be fixed in the future.

**Comment by jmborer** [comment]
After some testing, I think I can confirm that 
1) Kitematic.exe is rebranded Electron runtime
2) some electron command line switches work like --enable-logging
3) all proxy or certificate switches are ignored by the "request" library (which is pity)

**Comment by llwt** [comment]
Not the most "safe" option but you can set the env var `NODE_TLS_REJECT_UNAUTHORIZED=0` to have request/node ignore certificate errors which will get you past that error behind a corporate proxy.

**Comment by FrenchBen** [comment]
1) Correct we're even on the homepage: http://electron.atom.io/
2) Most electron runtime should work
3) The request  library should make use of your ENV vars, or it's been proven to work in the past. 

Making updates to Kitematic to have all of the certs in place has been discussed before - Have you tried to use [Docker for Windows](https://www.docker.com/products/docker#/windows)?
If not, would you mind giving it a try to see if the experience is a bit better when working with proxies?

**Comment by jmborer** [comment]
I cannot try "Docker on Windows" as we are still constrained to use Win 7. 
Concerning the request library, I looked at the code and I saw that not all switches/options from the ENV vars are taken into account...

I haven't checked Steven's answer yet:

> Not the most "safe" option but you can set the env var NODE_TLS_REJECT_UNAUTHORIZED=0 to have request/node ignore certificate errors which will get you past that error behind a corporate proxy.

**Comment by pitervergara** [comment]
I have this same issue (DockerToolbox 1.10.2 on Windows 7 SP1 64b).

After configuring my default boot2docker machine to use proxy, I was able to run 'docker pull hello-world' and 'docker run hello-world' via 'Docker Quickstart Terminal'.

Despite of that, Kitematic didn't showed images nor allowed me to login. The images screen only showed _There was an error contacting Docker Hub_ and   the login screen showed _unable to verify the first certificate_, after submiting my credentials.

I tryed several other stuff, (exporting proxy upper and lowercase, set the CA path in my .npmrc, set strict-ssl to false via npm config, set  DOCKER_TLS_VERIFY to 0) but nothing worked. The only thing that made a difference was to set **NODE_TLS_REJECT_UNAUTHORIZED=0** before launching kitematic.

This is my start.bat (placed on the same directory as kitematic.exe) :
```
set NODE_TLS_REJECT_UNAUTHORIZED=0
set proxy=http://proxy.my.domain:8080/
set HTTP_PROXY=%proxy%
set HTTPS_PROXY=%proxy%
for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
set NO_PROXY=%DOCKER_HOST%
set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
Kitematic.exe
```

**Comment by FrenchBen** [comment]
Can you guys try to use [Docker for Windows](https://www.docker.com/products/docker#/windows) instead and see if that helps resolve these issues?

**Comment by jmborer** [comment]
Well, I don't really understand why you ask us to use Docker for Windows. We are talking about Kitematic which is not able to browse the image repository. We all said that a docker instance properly configured is able to retrieve images on the internet.

How will Docker for Windows help to solve the Kitematic issue???

**Comment by PeterMcLaren** [comment]
@jmborer I can help here and add my support - I have the same issue and I am running Win 10 with Docker for Windows. 

I am behind a corp proxy and therefore I duly configured this during the setup of DfW:

To be clear - all the command line (docker search, docker pull etc) work perfectly first time (so through the proxy) with no further action on my part.

Kitematic installed fine, and can manipulate images I have download via the command line. However, Kitematic will not connect to docker hub on startup (and errors elsewhere in the UI in a similar way). 

I tried the environment variables but appears to ignore this and attempts to lookup hub.docker.com and connect. We don't resolve public records in our DNS environment (only the proxy can) so this fails. If I then add a hostfile entry for hub.docker.com, it attempts a direct 443 connection to that address - in other words it makes no attempt to use a proxy.

**Comment by FrenchBen** [comment]
@jmborer as @PeterMcLaren mentioned there's a good chance that the issue is due to proxy issues which is difficult to configure within Virtualbox. Installing Docker for Windows helps solve this issue partially, by removing the Virtualbox configuration/complexity.

@PeterMcLaren when you set the env var, did you make sure to start Kitematic from the command line as well?

**Comment by PeterMcLaren** [comment]
@FrenchBen I didn't - I set it in the windows master environment - but I did check at a command prompt that I could see it. I'll try that and let you know. thanks.

**Comment by PeterMcLaren** [comment]
@FrenchBen  Thanks - the command line method worked. I went back and reviewed my user environment variable settings in the system settings and rebooted. that now works too - so I must have made a typo somewhere. The nice thing about setting at the windows level is the <right-click> ; "Open Kitematic..." on the tray icon works properly. thanks again.

**Comment by FrenchBen** [comment]
@PeterMcLaren thanks for the feedback - Do you mind taking a screenshot of how you have it setup in the main Env Variable window? I'll add that screenshot to the wiki.

**Comment by PeterMcLaren** [comment]
@FrenchBen sure. Make the following entries. Reboot to be sure they stick, but should be ok.
![image](https://cloud.githubusercontent.com/assets/13315640/16794565/7ae83c78-48d0-11e6-8e7f-f89174855972.png)

**Comment by FrenchBen** [comment]
Thanks @PeterMcLaren - Added it to the wiki:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes#make-the-proxy-settings-sticky

If you feel like adding more detailed steps, don't hesitate :)
