### ISSUE TITLE
HTTP code is 500 which indicates error: server error - Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by yclbysf** [docker/kitematic#1634]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
You need to make sure you are on a solid connection to download images. I would also recommend restarting the VM if you've changed network: `docker-machine restart default`
