### ISSUE TITLE
Error while pulling image: Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:54528->[::1]:53: read: connection refused

### ISSUE THREAD

**Issue by NikhilCTS** [docker/kitematic#1635]
### Expected behavior
User should be able to download Cassandra 

### Actual behavior
Error while pulling image: Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:54528->[::1]:53: read: connection refused

### Steps to reproduce the behavior

  1. Select cassandra in kitematic,.
  2. Observe error.

Note: I am not able install any file. Please help.

**Comment by FrenchBen** [comment]
You need to make sure you are on a solid connection to download images. I would also recommend restarting the VM if you've changed network: `docker-machine restart default`

**Comment by pradeepkumards** [comment]
even i am facing same issue.
**error msg**: Error while pulling image: Get http://localhost:5001/v1/repositories/hello_world_application/images: dial tcp [::1]:5001: getsockopt: connection refused

>docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
img_app                   latest              259dc6d7b6fe        18 hours ago        689.3 MB
localhost:5001/img_app    latest              259dc6d7b6fe        18 hours ago        689.3 MB
docker.io/python          2.7                 ca388cdb5ac1        8 days ago          676.1 MB

>netstat -anp | grep 5001
tcp6       0      0 :::5001                 :::*                    LISTEN      31971/registry    

>cat my-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
    name: my-pod-label
spec:
  containers:
    - name: my-application
      image: localhost:5001/img_app:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
          name: my-pod-label
