### ISSUE TITLE
Unresponsive Window (Kitematic)

### ISSUE THREAD

**Issue by tarun-yadav** [docker/kitematic#1636]
### Expected behaviour
I wanted to pull new images from docker hub by clicking the new button on the container section to download the desired ones. Also on clicking the Create buttons it is expected that the docker hub would be connected and download will start

### Actual behaviour
Nothing of the above two happen and the window shows the buttons to be active but turns unresponsive.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
What version of Docker Toolbox are you using?

**Comment by tarun-yadav** [comment]
It is Docker Kitematic 0.10.2 and Virtual Box 0.35.4 on OS X 10.11.3

**Comment by FrenchBen** [comment]
What happens when you manually pull them from a terminal? Open 'Docker QuickStart Terminal' and run:
`docker pull hello-world`

**Comment by tarun-yadav** [comment]
It works absolutely fine with the terminal.

**Comment by FrenchBen** [comment]
I don't see why it would work from the cli, but not in Kitematic - I need more details, such as screenshot of the error you're seeing.
