### ISSUE TITLE
Can't launch Kitematic app after downloading (on Mac)

### ISSUE THREAD

**Issue by mixxmac** [docker/kitematic#1637]
Hi...

I've been having this problem trying to download the last two releases (v0.10.1 and v0.10.2).

Has anyone had the same problem? Or would anyone know what the problem might be?

I've tried had the same problem on two different computers.

### Expected behavior
Double-click Kitematic (Beta).app launches Kitematic application

### Actual behavior
Error message: “Kitematic (Beta).app” is damaged and can’t be opened. You should move it to the Trash.

### Information about the Issue
![kitematic-app-is-damaged](https://cloud.githubusercontent.com/assets/351702/14583715/692e1b14-03f8-11e6-8567-0d181632187a.png)

### Steps to reproduce the behavior

  1. Download: 
https://github.com/docker/kitematic/releases/download/v0.10.2/Kitematic-0.10.2-Mac.zip
  
  2. Unzip
  
  3. Double-click Kitematic (Beta).app

**Comment by thaJeztah** [comment]
If you put `Kitematic (Beta)` in your applications folder, can you try opening a terminal, and running;

    xattr -rc /Applications/Kitematic\ \(Beta\).app

That solved it for me

ping @FrenchBen ^^ same issue I ran into on one computer

**Comment by mixxmac** [comment]
That did the trick! Thanks a lot!

**Comment by FrenchBen** [comment]
For clarity:
```
-r: act recursively
-c: deletes (clears) all xattrs
```
Seems like some invalid xattrs were added along the way.

**Comment by RobertJansson** [comment]
That should be perfectly fine in this case but you might want to limit the command to target nothing but the quarantine setting running xattr:
xattr -rc com.apple.quarantine /Applications/Kitematic\ \(Beta\).app

**Comment by andrewcollette** [comment]
Any idea why this is happening?  I'm not sure the issue should be closed as it is still doing this out of the box on my (fully up to date) Mac.  I've never seen this with any other app, including ones downloaded from the Internet.

Typically Mac apps are distributed on .dmg files rather than in .zip files; I wonder if this is why there are problems.

**Comment by RobertJansson** [comment]
The application triggers the security system in OS X that is there to protect your computer from trojans. It happens because the application is not wrapped with a certificate that can testify the institution of the author.

**Comment by andrewcollette** [comment]
I think there may be something more subtle going on... I have installed unsigned apps before on OS X, and the security warning is quite different; here's an example:

![exemption_dialog](https://cloud.githubusercontent.com/assets/3101370/15561735/88dcc5d4-22be-11e6-818c-e6c9cb9226e4.png)

This article on the Apple website suggests that the Kitematic app is signed, but is somehow later being modified, which invalidates the signature and causes the "app is damaged" dialog.  That's why I suspected it had something to do with the zip file distribution:

https://support.apple.com/en-us/HT202491

**Comment by FrenchBen** [comment]
unzipping with Keka I've never had this issue - Can you download the latest release and see if the issue is still happening?
https://github.com/docker/kitematic/releases/tag/v0.10.4

**Comment by andrewcollette** [comment]
The release you linked seems to be OK.  Thanks!

**Comment by RobertJansson** [comment]
You can not compare how an installer handle such event compared to what happens if you download an executable binary and try to execute it.
The quarantine flag is only set by quarantine-aware programs so I would not recommend anyone to use programs like that. It's better to get the trap and lift it with the command, because then you've got the heads-up.

**Comment by ryber** [comment]
I'm still getting an error. It's reported as:

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/Downloads/Kitematic (Beta).app/Contents/MacOS/Electron
  Reason: image not found

**Comment by jasonayre** [comment]
The linked release, along with 10.0.5 both throw that same "Damaged and cant be opened error for me". I don't think this was resolved. The workaround posted above 
`xattr -rc /Applications/Kitematic\ \(Beta\).app`
Did however

**Comment by seanjensengrey** [comment]
The Docker for Mac Beta still exhibits the quarantine problem. If you don't have Kitematic installed, it propts with a link to download 

```
45562719 Kitematic-Mac.zip
# shasum -a 256
161d702e25cfda4337c5f9b1315ad1487b287cd581e8951caee7ff529595370c  Kitematic-Mac.zip
```

**Comment by DJphilomath** [comment]
I agree, this issue should not be closed as I ran on the same problem today.

**Comment by maxtheman** [comment]
I also had this issue, and @thaJeztah 's xattr deletion solved it for me.

**Comment by VMTrooper** [comment]
+1 still having this issue with the version of Kitematic that the latest Docker for Mac downloads. The xattr workaround was needed to move forward.

**Comment by jeffski** [comment]
Having this issue too

**Comment by FrenchBen** [comment]
For those having the issue, can you provide a few details:

* OSX version
* Disk encryption
* AntiVirus installed
* Proxy/VPN

**Comment by maxtheman** [comment]
OSX 10.10.5
No
No
No

**Comment by VMTrooper** [comment]
- OSX version - 10.11.3
- Disk encryption - Yes, FileVault
- AntiVirus installed - McAfee Endpoint Protection 2.3.0 (1791)
- Proxy/VPN - GlobalProtect 2.3.3-5 (it was not enabled at the time)

NOTE: I had to run the xattr command twice:
1. When initially trying to launch Kitematic from the Applications folder
2. When trying to use the "Open Kitematic" menu item from Docker for Mac.

**Comment by greenkiwi** [comment]
We are still having this issue.  The workaround above and the one presented here:
https://forums.docker.com/t/kitematic-mac-download-corrupt/9256/4
Allow it to work

**Comment by DJphilomath** [comment]
OSX version 10:11:3
No
No
No

**Comment by b01** [comment]
I just had this happen to me, the attribute fix above solved the problem. But the issue seems to still be occurring.

**Comment by FrenchBen** [comment]
To put things in perspective, this isn't just a Kitematic issue, as it's been seen in other apps:
http://apple.stackexchange.com/a/215372

The built-in Archiver utility is usually the culprit - I've never had this pop-up when using something like [Keka](http://www.kekaosx.com/en/)

**Comment by thaJeztah** [comment]
@FrenchBen I would not really recommend using that setting. Would it be possible to ship Kitematic as a `.dmg`? It's more "native", and would work around the issue with archiver

**Comment by FrenchBen** [comment]
@thaJeztah The reason it's not a DMG is due to the current Packaging with Docker Toolbox. 
With the release of Docker for Mac/Windows there may be a need to create an actual installer though for all versions.

**Comment by seanjensengrey** [comment]
The app is signed

```
$ codesign -dv /Applications/Kitematic\ \(Beta\).app
Executable=/Applications/Kitematic (Beta).app/Contents/MacOS/Electron
Identifier=com.electron.kitematic_(beta)
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=233 flags=0x0(none) hashes=3+4 location=embedded
Signature size=8907
Timestamp=Jun 13, 2016, 23:40:33
Info.plist entries=20
TeamIdentifier=9BNSXJN65R
Sealed Resources version=2 rules=12 files=11
Internal requirements count=1 size=192
```
I would recommend putting in a `.dmg` and delivering it over https and see if the problem goes away. I am wagering it will.

**Comment by vitortd** [comment]
OSX version: 10.11.3
Disk encryption: Yes
AntiVirus installed: No
Proxy/VPN: No

**Comment by crapthings** [comment]
it works!
