### ISSUE TITLE
Kitematic's place in the Docker world

### ISSUE THREAD

**Issue by rkazak** [docker/kitematic#1638]
This is not a bug as such, just a request for clarification on some points.

Is Kitematic going to be evolved to manage the Docker ecosystem? Or is that something else. I ask so that I know what's reasonable to request as a features or report as bugs?

### Expected behavior
Kitematic - one utility to rule them all.  We should be able to execute all the CLI operations via the GUI.

### Actual behavior
Kitematic - limited to single machine/vm (?).

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
We've had a few discussions around this and nothing has been set in stone as of yet. Feel free to chime in on any Feature request or create one of your own.

**Comment by rkazak** [comment]
I have a ton of ideas! I would like to see Kitematic as it starts up be a
map of the Docker ecosystem (do we support both VBox based and the newer
hosted-supported vms, I vote yes ) and from here should be able to
visualize swarms, clusters and machines.  There should be some layer
depicting the eco-systems networking. We should be able to affect network
config from this layer. To affect other assets we should be able to
'double-click' and drill into swarms/clusters/machines...

just my 2cents...


On Tue, Apr 19, 2016 at 1:33 PM, French Ben <notifications@github.com>
wrote:

> We've had a few discussions around this and nothing has been set in stone
> as of yet. Feel free to chime in on any Feature request or create one of
> your own.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/kitematic/issues/1638#issuecomment-212115663>
>



-- 
Rohinton Kazak

**Comment by FrenchBen** [comment]
@rkazak I like the idea, feel free to map them out accordingly into a proper Feature proposal.

**Comment by rkazak** [comment]
Hi, just thinking on this some more and I think that we could take inspiration from
"Curvature – an interactive visual orchestration tool for applications on OpenStack."
