### ISSUE TITLE
Kitematic cannot download image

### ISSUE THREAD

**Issue by sreux** [docker/kitematic#1639]
Hi,

I have an issue with Kitematic, i start it behind a proxy with the following command line.
http_proxy=http://Myproxy https_proxy=http://Myproxy open /Applications/Docker/Kitematic\ \(Beta\).app/
Kitematic launch perfectly and can connect on the Docker Hub without issue.
![image](https://cloud.githubusercontent.com/assets/18576479/14678359/9f7ca4ea-0715-11e6-8afa-9b4a2cf57eb0.png)

When i choose an image i cannot download it without issue message ... 
I have this screen endlessly
![image](https://cloud.githubusercontent.com/assets/18576479/14678402/c9acdd34-0715-11e6-8fbc-c8147d78a342.png)

It's strange because yesterday it works well....
Any idea why i have this issue...
I have this issue on MACOS and Windows 2008R2

Regards

**Comment by sjardim** [comment]
Same here, I can't download either (no error message). And I'm not behind a proxy.

**Comment by wfowlks** [comment]
I am also getting this error. However I do get a message:
<img width="691" alt="screen shot 2016-04-20 at 11 12 19 am" src="https://cloud.githubusercontent.com/assets/7023176/14679654/d3a55866-06e8-11e6-9a5f-86e4ab2dbd66.png">

**Comment by FrenchBen** [comment]
@wfowlks your error has nothing to do with the other 2 - You need to select the proper tag prior to creating the container.
You can do so by clicking on the ellipsis next to  'create' and selecting a valid tag.

**Comment by sreux** [comment]
Hi all,

No one have any solution for this issue... i have try to deeply unistall Kitematic & Virtualbox and reinstall... and i keep the same issue :(

Regards

**Comment by FrenchBen** [comment]
@sreux If you look at the wiki information, you'll notice that the VM also needs to be setup with the proper proxy settings:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
