### ISSUE TITLE
I've never experienced this error before... Is there a simple way to update to latest?

### ISSUE THREAD

**Issue by mattinclude** [docker/kitematic#1641]
### Expected behavior
normal run from index
### Actual behavior
Error: Tag latest not found in repository docker.io/mattinclude/webuntu
### Information about the Issue
Tag latest not found in repository docker.io/mattinclude/webuntu

### Steps to reproduce the behavior

  1. ...try to pull: mattinclude/webuntu
  2. ...

**Comment by FrenchBen** [comment]
You can click the ellipsis next to the create button and select a different tag. 
Looks like that image doesn't have the 'latest' tag defined.
