### ISSUE TITLE
Docker doesn't release ports on OSX. Guess that's old news.

### ISSUE THREAD

**Issue by erich-comsIO** [docker/kitematic#1642]
### Expected behavior
Docker should release ports
### Actual behavior
Docker doesn't release ports
### Information about the Issue
It really sucks

### Steps to reproduce the behavior

  1. ...start a container
  2. ...stop a container
  3 try to restart and learn that the port wasn't released. Still.

bash-3.2$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

**Comment by FrenchBen** [comment]
Stopping a container isn't enough to release a port - You need to remove that container for it to release the port.

**Comment by erich-comsIO** [comment]
my mistake and apologies. Thx.

**Comment by erich-comsIO** [comment]
Got it - There was some behavior in kinematic where it seemed to get confused about if the container was running or not, and think I conflated issues here. I appreciate the education!
