### ISSUE TITLE
Question about environment transplantation

### ISSUE THREAD

**Issue by rhuab** [docker/kitematic#1644]
I have a program running in the docker image but it needs compilation environment in the host. How to use the environment in the host while the program runs in the image? -v option does not work because  the path for compilation environment may contains multiple possibilities even the user does not know where it is.

**Comment by FrenchBen** [comment]
By design the container shouldn't need anything from the host - What image are you using? What are you trying to do?

**Comment by rhuab** [comment]
I am using Ubuntu:14.04 but I think the image version is not the problem I am talking about. I design a program that need  compilation environment of the host when it runs. I want to deploy it on any platform so I choose Docker to solve this problem but Docker cannot solve that problem when the program runs as I mentioned before. My question is whether docker can transplant compilation environment of the host so that the program that runs in the image can make use of the environment of the host. If not, is there any substitute solution?

**Comment by FrenchBen** [comment]
This is more of an issue for `docker/docker` - Can you open an issue there?
