### ISSUE TITLE
Pitch to zoom is avialible in Mac Os X

### ISSUE THREAD

**Issue by Matvey-Kuk** [docker/kitematic#1646]
### Expected behavior
No reaction to pitch to zoom.

### Actual behavior
Zoom is avialible. Video: https://yadi.sk/i/kfWEWQ2hrGNkk

### Steps to reproduce the behavior

  1. Open Kitematic.
  2. Zoom.

**Comment by FrenchBen** [comment]
What would be the expected behavior behind the pinch to zoom?
We have a PR against adding some 'zoom' feature to the logs:
https://github.com/docker/kitematic/pull/1479

**Comment by Matvey-Kuk** [comment]
Zoom is moving window buttons (close, minimize, maximize) outside of the window. It's unexpected behavior. I don't know not any application with such mechanics.

**Comment by FrenchBen** [comment]
I see what you mean now - It's because of the way our window is built. There's a pending PR to correct this in Windows, but will be replicated for Mac. 
https://github.com/docker/kitematic/pull/1559
