### ISSUE TITLE
Kinematic should periodically refresh its list of running containers

### ISSUE THREAD

**Issue by wchrisjohnson** [docker/kitematic#1649]
### Expected behavior

The Kinematic app should periodically refresh itself wrt the containers that show up as running.
### Actual behavior

If the Kinematic app is running when a `docker compose` is done, the new running containers don't show up in the UI.
### Information about the Issue

Kitematic v0.10.0
### Steps to reproduce the behavior
1. ...
2. ...

**Comment by FrenchBen** [comment]
Hi @wchrisjohnson,
I would recommend upgrading to v0.10.2 where some of the triggered events are now handled better. 
Additionally we introduced a 'refresh' feature to get the latest containers displayed.

**Comment by mireczatko** [comment]
where can I find this "refresh" feature? I hope there is a button to manually activate it...

**Comment by FrenchBen** [comment]
@mireczatko you can click on the menubar View -> Refresh Container List
The shortcut of CMD+R has also been set to do the same thing

**Comment by dbjpanda** [comment]
There are already dozen of issue regarding this feature. But a proper auto refresh will be very helpful.  I am using latest version and sometimes it refreshes i.e it shows properly and sometimes does not work. I have to manually press command +R or need to quit and start again.
