### ISSUE TITLE
Not downloading the image

### ISSUE THREAD

**Issue by rohitbhardwaj** [docker/kitematic#1652]
### Expected behavior
Cassandra image should download
### Actual behavior
Cassandra image is not getting downloaded

### Steps to reproduce the behavior

  1. Try downloading Cassandra image using Kitematic or commandline

Should I use latest version of Kitematic?

**Comment by FrenchBen** [comment]
Can you provide more details about the actual image, your networking setup, etc.
No issues on my end pulling directly or via Kitematic:
```
$ docker run --name some-cassandra -d cassandra:latest
Unable to find image 'cassandra:latest' locally
latest: Pulling from library/cassandra

efd26ecc9548: Already exists
a3ed95caeb02: Pull complete
c50f81084f58: Pull complete
db7e7b58735f: Pull complete
eb568ae1aaa9: Pull complete
61a4e1ace676: Pull complete
2bcaaa00f040: Pull complete
1cbedd7d14e9: Pull complete
afbc05a579e4: Pull complete
8c5a5e0b17a1: Pull complete
e0c7393de2fb: Pull complete
Digest: sha256:90b62ef5ee5aecd30cae65b1bee6d0f2fb6fb06efb232c0c08db9e4b99f7a68e
Status: Downloaded newer image for cassandra:latest
5b09b30d04facf06788bae3053af2f31bffe5fccf452836b91bb5db1d0c8b969
```

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
