### ISSUE TITLE
Kitematic no such file or directory if changed docker machine storage location

### ISSUE THREAD

**Issue by Verayth** [docker/kitematic#1653]
Kitematic is unable to access the default machine if the storage location is changed.  To reproduce (in Windows 7), set environment variable "MACHINE_STORAGE_PATH=Q:\.docker" and run Kitematic for the first time.  The setup gets to 100 percent, and then throws this error trying to access files from wrong location:

ENOENT: no such file or directory, open 'C:\Users\\.docker\machine\machines\default\ca.pem'

'docket-machine ls' from the quickstart terminal shows the default machine is running just fine:
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox   Running   tcp://192.168.99.106:2376           v1.11.1

**Comment by FrenchBen** [comment]
@Verayth Closing this as it's a dup of #1640
