### ISSUE TITLE
Missing tooltips in OSX 

### ISSUE THREAD

**Issue by salamanders** [docker/kitematic#1656]
### Expected behavior
Hovering over any icon should show a tooltip of what it will do.  (eg. I didn't expect the "chat" icon to take me here, it would be nice if the tooltip was "Submit a new issue on github")

### Actual behavior
Nothing happens on mouse hover

### Information about the Issue
OSX, app v 0.10.2

### Steps to reproduce the behavior

  1. Hover over any icon in the UI
  2. nothing happens, no tooltip.  Which makes the user less confident in clicking, because who knows what it will do!

**Comment by FrenchBen** [comment]
The general idea was that the icons were explicit enough to provide the user with the action behind them.
Feel free to create a PR that will implement all of the tooltip you speak of :)
