### ISSUE TITLE
URLs use docker.local instead of localhost on Mac OS with latest Docker Beta

### ISSUE THREAD

**Issue by amir20** [docker/kitematic#1661]
### Expected behavior
Clicking web preview should send the user to actual ip address or localhost if using Beta on Mac. 

### Actual behavior
With the latest version of Docker Beta, clicking on a exposed ports, OR app web preview, opens `http://docker.local:[port]` where page is not found. 

### Information about the Issue
Mac OS X 10.11.4
Docker -v `Docker version 1.11.1, build 5604cbe`
Kitematic `0.10.2`. 

### Steps to reproduce the behavior
1. Install Docker Beta (https://beta.docker.com/) 
2. Open or install latest Kitematic 
3. Create a new `hello-world-nginx` 
4. Click on web preview
5. Note that browser to `http://docker.local:32772/` is opened 
6. But changing `docker.local` -> `localhost` works.

**Comment by thaJeztah** [comment]
ping @FrenchBen, perhaps this should be configurable?

**Comment by dsperling** [comment]
I just opened (and then closed 1663) as it was a duplicate.  Once Kitematic is integrated into Docker for Mac, this might be a non-issue.  However making this a configuration may provide the best forwards compatibility.
