### ISSUE TITLE
Mapping Volumes on graylog2/server image fails

### ISSUE THREAD

**Issue by Vittel** [docker/kitematic#1662]
### Expected behavior
Mapping of volumes on graylog2/server image works
### Actual behavior
Mappin fails with the message "data" is not an absolute path

### Steps to reproduce the behavior

  1. Just try to run start graylog2/server and then enable mapping.

**Comment by FrenchBen** [comment]
Reading the documentation (https://hub.docker.com/r/graylog2/server/), under the "Persist log data" section, it seems that graylog2 depends on some default configurations. Did you make sure to set these up prior to enabling volume mapping?

Either way the error described is that of graylog2 not Kitematic
