### ISSUE TITLE
Release note 0.10.3 states: Docker for Mac/Windows native support - doesn't work

### ISSUE THREAD

**Issue by pmario** [docker/kitematic#1665]
### Expected behavior

https://github.com/docker/kitematic/releases

>This release includes a few bug fixes and enhancements, including the following:
>
>   Docker for Mac/Windows native support

### Actual behavior

Kitematic expects VirtualBox to be installed, which is not possible with "Docker for Windows" support. So it seems the detection is broken.

### Information about the Issue

Kitematic expects VirtualBox to be installed, which is not possible with "Docker for Windows" support

### Steps to reproduce the behavior

Download the zip and extract it
Start the program ... it's broken

**Comment by FrenchBen** [comment]
@pmario it's a pre-release, a couple of things went wrong during the build that I'm fixing :(
Thanks for the issue

**Comment by FrenchBen** [comment]
@pmario new build available - can you confirm it works as expected?
https://github.com/docker/kitematic/releases/tag/v0.10.3

Thanks!

**Comment by pmario** [comment]
Sorry. It's not possible to test it atm. I do have the same problem described here: https://forums.docker.com/t/docker-not-initializing-after-update/11069/13?u=pmario

**Comment by pmario** [comment]
@FrenchBen .. I can confirm, that the "windows" version connects to docker now. Did a fast test and nginx container started. ... accessing the volumes will be tested next.

**Comment by pmario** [comment]
@FrenchBen, Volumes seem to work too. There are some strange error messages, is I do share drive D: ... but I'll open a new issue for this one. 

So from my point of view this issue can be closed. ... but since you assigned the "mac" label and I can't test this, you should close it :)

**Comment by FrenchBen** [comment]
Mac is working on my end - thanks for confirming!
Happy to hear the hot-fix also fixed the issue for you.
