### ISSUE TITLE
Have no ability to Configure volumes

### ISSUE THREAD

**Issue by ivan-exness** [docker/kitematic#1668]
### Expected behavior
Want to mount volumes from local machine
### Actual behavior
No option in default ubuntu image
I have OSX 10.11.4 (15E65)
Kinematic 0.10.2

### Information about the Issue
![screenshot 2016-05-11 12 06 16](https://cloud.githubusercontent.com/assets/17728801/15175804/ca86689a-1770-11e6-9114-6830d40797a9.png)

### Steps to reproduce the behavior
Create ubuntu:latest conteaner.
Open Settings-Volumes

**Comment by FrenchBen** [comment]
@ivan-exness Unfortunately only the volumes exposed by the image will be shown here -  
If you look at an image like: https://hub.docker.com/_/nginx/ you'll see that the Dockerfile actually exposes a volume that shows up in kitematic.
