### ISSUE TITLE
Kitematic Installer freezes at 99% with OSX 10.11.4 

### ISSUE THREAD

**Issue by beebase** [docker/kitematic#1669]
Kitematic Installer 1.11.1 freezes at 99% with OSX 10.11.4

**Comment by FrenchBen** [comment]
@beebase Can you see if the VM is up and running?
`docker-machine ls`

**Comment by beebase** [comment]
Thanks for replying.
I started up virtual box and re installed kitematic. Everything ok now.
Amazing program! Like it.





On Thursday, 12 May 2016, French Ben <notifications@github.com> wrote:

> @beebase <https://github.com/beebase> Can you see if the VM is up and
> running?
> docker-machine ls
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/kitematic/issues/1669#issuecomment-218624872>
>


-- 

- - - - - - - - - - - - - - - - - - - - - - - - - -

BeeBase
Maarten Berkenbosch
Mobile + 31 (0)6   24 69 42 40


Address Albert Neuhuijssraat 9
Zip/City 3817 EC Amersfoort
Country Netherlands

- - - - - - - - - - - - - - - - - - - - - - - - - -
