### ISSUE TITLE
I can not use swift command to launch REPL process.

### ISSUE THREAD

**Issue by aaqqxx** [docker/kitematic#1670]
### Expected behavior
go to swift REPL
### Actual behavior
get ERROR.can not launch REPL process
### Steps to reproduce the behavior

root@36f19dec674b:/tmp# swift
error: failed to launch REPL process: process launch failed: 'A' packet returned an error: 8
root@36f19dec674b:/tmp# swift --version
Swift version 3.0-dev (LLVM dffa09ffd8, Clang 1e6cba3ce3, Swift d2aee43220)
Target: x86_64-unknown-linux-gnu

**Comment by FrenchBen** [comment]
See:
https://github.com/swiftdocker/docker-swift/issues/9
