### ISSUE TITLE
Kitematic Beta doesn't allow login

### ISSUE THREAD

**Issue by xgt001** [docker/kitematic#1671]
### Expected behavior
Kitematic beta lets you login
### Actual behavior
Kitematic beta doesn't let you login

### Steps to reproduce the behavior
1. Enter username
2. Enter password
3. Try logging in
4. gets stuck at password should be lower case letters and numbers

Also, why do we have a peculiar requirement for password only in Kitematic Beta? dockerhub doesn't have this restriction!

Kitematic beta version : 0.10.2 (Mac)
 
![docker-bug](https://cloud.githubusercontent.com/assets/1500199/15201970/c12237c2-1813-11e6-9dbc-8cc6b1df7c30.png)

**Comment by pmario** [comment]
did you try it with v0.10.3 too? https://github.com/docker/kitematic/releases

**Comment by xgt001** [comment]
Yep. Just did. Same behaviour

**Comment by FrenchBen** [comment]
make sure that you're using your hub username in lowercase

**Comment by xgt001** [comment]
FrenchBen, this worked thanks.

However, dockerhub lets users login with either email id or username.

![image](https://cloud.githubusercontent.com/assets/1500199/15244243/cf01995e-191d-11e6-9cfb-d989cb92ad11.png)

Was expecting kitematic to behave the same here. (Kitematic should allow login via email id as well)

Please feel free to close this issue as the original issue in the title is non-existent

**Comment by FrenchBen** [comment]
@xgt001 It's a feature request we've logged, unfortunately we are more focused on fixing a few bugs atm. 
Feel free to create a PR to fix this :D
