### ISSUE TITLE
Update comment about adding `+1` comments.

### ISSUE THREAD

**Issue by Zoltu** [docker/kitematic#1672]
The last comment by @FrenchBen in https://github.com/docker/kitematic/issues/210 tells people to use the GitHub reactions feature to `+1` instead of comments and then locks the conversation.  Unfortunately, GitHub doesn't allow using reactions on locked issues so no one can actually follow the recommendation right now.

Recommend either updating the comment to remove the suggestion of using the reaction feature or unlocking the issue.

Side-note: Repo admins can delete user comments, I think telling people to use the reaction feature and then deleting their comments will help reenforce the desired behavior since their `+1` comments will get deleted and their "vote" lost if they don't use the reaction feature.

Feel free to close this message as soon as it is seen by an admin, I couldn't figure out any better obvious/immediate way to give this feedback.

**Comment by FrenchBen** [comment]
Thanks @Zoltu for the update - Didn't realize that locking the conversation prevented it from doing +1.
To keep things clear and remove any drama, I don't want to delete comments :P

I'll re-open the issue.
