### ISSUE TITLE
Ports set gets reset on restart of the container

### ISSUE THREAD

**Issue by AbhayParab** [docker/kitematic#1673]
### Expected behavior
When port mapping is saved, i am expecting same port would be used when container is restarted

### Actual behavior
Ports get changed to random number on restart of the container

### Information about the Issue
When port mapping is saved, i am expecting same port would be used when container is restarted. Ports get changed to random number on restart of the container. Due to this dependent container fails.

### Steps to reproduce the behavior

  1. ...Got to Ports on any installed container. Set the value of one of the port to 9999
  2. ...Server gets restarted with 9999 port. This is correct
  3. ...Restart container. Observe that port would get changed

**Comment by FrenchBen** [comment]
How do you 'restart' the container? I've done this plenty of times with my containers and don't see any issues.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Comment by vpol** [comment]
It's quite strange that this have being closed.

<img width="297" alt="screenshot 2017-01-26 14 57 30" src="https://cloud.githubusercontent.com/assets/203558/22335816/08a3ea38-e3d8-11e6-92fc-0b37ad0d935b.png">

Container -> Stop

Container -> Start

<img width="360" alt="screenshot 2017-01-26 14 59 50" src="https://cloud.githubusercontent.com/assets/203558/22335840/1979ef60-e3d8-11e6-8ab6-918fa3ff1f72.png">

Ports change randomly.

Is there any way to lock the ports?

Docker Kitematic 0.13

**Comment by FrenchBen** [comment]
you can lock them when you assign actual ports
