### ISSUE TITLE
Docker CLI not starting or starts random

### ISSUE THREAD

**Issue by eduardoinnorway** [docker/kitematic#1675]
### Expected behavior
"DOCKER CLI" button in left corner  in Kitematic should start Docker cli.

### Actual behavior
It starts randomly

### Information about the Issue
I am on Mac OS X El Capitan

### Steps to reproduce the behavior

  1Buy a Mac with El Captian ;) 
  2.  and so on. ... start Kitematic

**Comment by FrenchBen** [comment]
When you say it starts randomly, do you mean that no window appears, or that executing a `docker ps` doesn't work?

**Comment by eduardoinnorway** [comment]
The actual window. I noticed this is a very random thing, sometimes I just wait and then it will appear with as many windows as I have pressed the "DOCKER CLI" button. It is very hard to tell what is exactly happening, I will just have to restart to make it work again if it will not come after some time. I will reformat my mac and see if it helps, have to do it anyways.

**Comment by FrenchBen** [comment]
let me know if that helps - It always comes up for me without any issue.

**Comment by galerienv** [comment]
To be clear, on Windows 10, Docker Cli open Powershell but do load modules.

I obtain the same problem without create container and just to click on docker cli. It open Powershell but without docker extension loaded.  See image attached.

![docker cli](https://cloud.githubusercontent.com/assets/10227016/17350095/cb7855de-5923-11e6-84f6-d2e6bc1f9033.png)

If i use Windows powershell provided by Windows 10, i have no problem to execute docker command. Really strange.

**Comment by FrenchBen** [comment]
I'm not sure if I understand this:
```
The problem is only when i use the button docker cli after call kinematic by docker services (Not toolbox). If i call directly kinematic, i don't have the problem.
```
Qu'est-ce que tu veux dire? Tu cliques sur quoi?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Comment by geminiyellow** [comment]
what is the solution? i cannot open docker cli from kitematic. 

use the latest docker ce for mac and the latest kitematic.
