### ISSUE TITLE
OSX Docker CLI iTerm script broken for newer iTerms

### ISSUE THREAD

**Issue by sr105** [docker/kitematic#1680]
Scripts Location: `/Applications/Docker/Docker\ Quickstart\ Terminal.app/Contents/Resources/Scripts/`

Open the iterm.scpt file in Script Editor and run it. Newer iTerms do not support the ITRMLNCH event.

Workaround: running the start.sh script directly from a terminal works fine.

**Comment by FrenchBen** [comment]
@sr105 Although the projects are related (Kitematic is in Toolbox), the proper location to file this issue is here:
https://github.com/docker/toolbox

Thanks

**Comment by sr105** [comment]
Ah, sorry and thanks.
