### ISSUE TITLE
Not able to use with VPN

### ISSUE THREAD

**Issue by devsmart** [docker/kitematic#1683]
### Expected behavior
Docker should be able to use when I connected to VPN

### Actual behavior
shows error attached image "capture"

### Information about the Issue
I was connected to office VPN and when I using docker it gives error.

### Steps to reproduce the behavior
![capture](https://cloud.githubusercontent.com/assets/2795891/15379798/42aab204-1d8e-11e6-9263-11e5c543d50e.PNG)
![capture1](https://cloud.githubusercontent.com/assets/2795891/15379799/42ab793c-1d8e-11e6-8dc2-7cec24aa1714.PNG)

  1. Login to VPN using local machine (Cisco any-connect) 
  2. open Docker Kitematic (Alpha) screen and try to download a VM

**Comment by FrenchBen** [comment]
Please see a possible fix in our wiki:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
