### ISSUE TITLE
unable to create cdap in docker using windows 10

### ISSUE THREAD

**Issue by kishore2509** [docker/kitematic#1685]
### Steps to reproduce the behavior
![image](https://cloud.githubusercontent.com/assets/19464018/15385175/5f2d2f40-1dbd-11e6-8930-564983e4e9ff.png)
![capturecdap](https://cloud.githubusercontent.com/assets/19464018/15385184/6ceb8ac8-1dbd-11e6-905a-2ae46d275e33.PNG)

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Seems like this could've been a simple network issue - Could you re-try?
