### ISSUE TITLE
docker beta and haxm cannot run together

### ISSUE THREAD

**Issue by ruurd** [docker/kitematic#1692]
### Expected behavior
docker beta (xhyve based IIAIC) and HAXM play nice together

### Actual behavior
incompatibility between HAXM hypervisor and VirtualBox 4.3.30 error message when attempting to start up Android emulator

### Information about the Issue
https://www.virtualbox.org/ticket/14294 last remark
https://code.google.com/p/android/issues/detail?id=197915

### Steps to reproduce the behavior
1. start docker beta for OSX
2. start Android Studio latest version
3. try starting a qemu emulator from Android Studio

### Log
/Users/ruurd/Library/Android/sdk/tools/emulator -netdelay none -netspeed full -avd Nexus_S_API_23
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
emulator: WARNING: Increasing RAM size to 1024MB
emulator: WARNING: VM heap size set below hardware specified minimum of 48MB
emulator: WARNING: Setting VM heap size to 256MB
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocksHax is enabled
Hax ram_size 0x40000000
HAX is working and emulator runs in fast virt mode.
console on port 5554, ADB on port 5555
Failed to sync vcpu reg
emulator: ERROR: Unfortunately, there's an incompatibility between HAXM hypervisor and VirtualBox 4.3.30+ which doesn't allow multiple hypervisors to co-exist.  It is being actively worked on; you can find out more about the issue at http://b.android.com/197915 (Android) and https://www.virtualbox.org/ticket/14294 (VirtualBox)
Failed to sync vcpu reg
Failed to sync vcpu reg
Internal error: initial hax sync failed

**Comment by FrenchBen** [comment]
Thanks for the report - IMHO It seems that this is more of an Android Studio issue, which doesn't play nice with other Hypervisors. 
Docker for Mac has the same warning for Virtualbox 4.3.3, but this was fixed by Virtualbox in later version aka you can run Virtualbox v5x and Docker for Mac at the same time. 

Additionally this was previously reported here:
https://forums.docker.com/t/cant-using-docker-for-mac-with-android-emulator-haxm/8939
