### ISSUE TITLE
WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by maklipsa** [docker/kitematic#1693]
### Expected behavior
Once every 10~20 minutes I get this:
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 12 [running]:
sync.(*WaitGroup).Wait(0xc082317778)
        /usr/local/go/src/sync/waitgroup.go:128 +0x11b
github.com/Microsoft/go-winio.(*win32File).closeHandle(0xc082317770)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:94 +0x62
github.com/Microsoft/go-winio.(*win32File).Close(0xc082317770, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:103 +0x34
net/http.(*persistConn).closeLocked(0xc0822a9760)
        /usr/local/go/src/net/http/transport.go:1248 +0x55
net/http.(*persistConn).close(0xc0822a9760)
        /usr/local/go/src/net/http/transport.go:1242 +0x81
net/http.(*persistConn).readLoop(0xc0822a9760)
        /usr/local/go/src/net/http/transport.go:1004 +0x95b
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc7f

goroutine 1 [runnable]:
io/ioutil.readAll.func1(0xc08216ad90)
        /usr/local/go/src/io/ioutil/ioutil.go:22
io/ioutil.readAll(0x52900e0, 0xc0823a60e0, 0x200, 0xc0823ae000, 0xdc, 0x200, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:34 +0x1d7
io/ioutil.ReadAll(0x52900e0, 0xc0823a60e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:42 +0x58
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc082306a20, 0x2828f68, 0xc08200ae00, 0x13b7ea0, 0x4, 0x13b4ee8, 0x6, 0xc082305320, 0x282eac0, 0xc08233e420, .
.)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/request.go:116 +0xb6d
github.com/docker/engine-api/client.(*Client).postRaw(0xc082306a20, 0x2828f68, 0xc08200ae00, 0x13b4ee8, 0x6, 0xc082305320, 0x282eac0, 0xc08233e420, 0xc08216b168, 0x0, ...)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/request.go:40 +0xbb
github.com/docker/engine-api/client.(*Client).ImageBuild(0xc082306a20, 0x2828f68, 0xc08200ae00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100, ...)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/image_build.go:37 +0x3bb
github.com/docker/docker/api/client.(*DockerCli).CmdBuild(0xc0821c1680, 0xc082003f10, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/build.go:239 +0x2cda
reflect.callMethod(0xc082304a50, 0xc08216bc88)
        /usr/local/go/src/reflect/value.go:628 +0x203
reflect.methodValueCall(0xc082003f10, 0x1, 0x1, 0x1, 0xc082304a50, 0x0, 0x0, 0xc082304a50, 0x0, 0x4716cb, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/cli.(*Cli).Run(0xc082304090, 0xc082003f00, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/cli.go:89 +0x38a
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:63 +0x35a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 8 [runnable]:
sync.runtime_Syncsemacquire(0xc082083038)
        /usr/local/go/src/runtime/sema.go:237 +0x20f
sync.(*Cond).Wait(0xc082083028)
        /usr/local/go/src/sync/cond.go:62 +0xa2
io.(*pipe).write(0xc082082fc0, 0xc082340000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:94 +0x241
io.(*PipeWriter).Write(0xc0820266d8, 0xc082340000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:161 +0x57
bufio.(*Writer).flush(0xc0822ef6c0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:562 +0xe7
bufio.(*Writer).Write(0xc0822ef6c0, 0xc082350000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:598 +0x26c
github.com/docker/docker/pkg/ioutils.(*writeCloserWrapper).Write(0xc082303460, 0xc082350000, 0x8000, 0x8000, 0xc0ffffffff, 0x0, 0x0)
        <autogenerated>:6 +0x89
archive/tar.(*Writer).Write(0xc082032480, 0xc082350000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/archive/tar/writer.go:366 +0xdb
bufio.(*Writer).flush(0xc082358000, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:562 +0xe7
bufio.(*Writer).ReadFrom(0xc082358000, 0x2860050, 0xc08236a028, 0x78000, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:686 +0x13b
io.copyBuffer(0x282ea10, 0xc082358000, 0x2860050, 0xc08236a028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:375 +0x187
io.Copy(0x282ea10, 0xc082358000, 0x2860050, 0xc08236a028, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:351 +0x6b
github.com/docker/docker/pkg/archive.(*tarAppender).addTarFile(0xc08202bdd0, 0xc0823701b0, 0x82, 0xc08235f020, 0x54, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/archive/archive.go:338 +0x9cb
github.com/docker/docker/pkg/archive.TarWithOptions.func1.2(0xc0823701b0, 0x82, 0x282a630, 0xc08235ef00, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/archive/archive.go:635 +0x964
path/filepath.walk(0xc0823701b0, 0x82, 0x282a630, 0xc08235ef00, 0xc08202be18, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:349 +0x87
path/filepath.walk(0xc08235c410, 0x4e, 0x282a630, 0xc08235eba0, 0xc08202be18, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc08235a090, 0x2d, 0x282a630, 0xc08235e0c0, 0xc08202be18, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.Walk(0xc08235a090, 0x2d, 0xc08202be18, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:396 +0xe8
github.com/docker/docker/pkg/archive.TarWithOptions.func1(0x282ea38, 0xc082303460, 0xc0820678c0, 0xc0820266d8, 0xc082326350, 0x1bc6cb8, 0x0, 0x0, 0x1bc6cb8, 0x0, ...)
        /go/src/github.com/docker/docker/pkg/archive/archive.go:643 +0x7f7
created by github.com/docker/docker/pkg/archive.TarWithOptions
        /go/src/github.com/docker/docker/pkg/archive/archive.go:645 +0x655

goroutine 11 [syscall, locked to thread]:
syscall.Syscall6(0x7ff9c045d5c0, 0x5, 0x200, 0xc08234df54, 0xc08234df58, 0xc08234df60, 0xffffffff, 0x0, 0xc08234df78, 0x1, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x5c
github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x200, 0xc08234df54, 0xc08234df58, 0xc08234df60, 0xffffffff, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/zsyscall.go:72 +0x99
github.com/Microsoft/go-winio.ioCompletionProcessor(0x200)
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:127 +0x7c
created by github.com/Microsoft/go-winio.initIo
        /go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:55 +0xb3

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc0822a9760)
        /usr/local/go/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xca4

This is with docker running on hyper-v

**Comment by FrenchBen** [comment]
tbh this has nothing to do with Kitematic (kitematic has no golang code) - For the purpose of moving things along, what image did you pull for this to happen?

**Comment by maklipsa** [comment]
Building a custom image based on elastic.
And, as with previous issue, I managed to narrow it to intererance with Cisco VPN. 
Some time after connecting to the VPN (few minutes) it started to happen.
