### ISSUE TITLE
HTTP cdoe 500

### ISSUE THREAD

**Issue by Frozen-Shadow** [docker/kitematic#1697]
### Expected behavior
I was createing the  nginx container ...
### Actual behavior
There was something wrong 
### Information about the Issue
```
HTTP code is 500 which indicates error: server error - Get https://registry-1.docker.io/v2/library/nginx/manifests/latest: net/http: TLS handshake timeout
```

### Steps to reproduce the behavior

  1. Only click the create button.

###  More

Hello!
I'm in China,I must use VPN to contact Docker Hub.I think we need some configuration to use my VPN. When I got the error,I can't found any way to try again...

**Comment by FrenchBen** [comment]
If you're using a VPN, please checkout:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
