### ISSUE TITLE
Broken ability to click on link on port mapping page

### ISSUE THREAD

**Issue by sibprogrammer** [docker/kitematic#1700]
### Expected behavior
Clicking by IP address on port mapping page should open a page in the browser with corresponding URL.

### Actual behavior
Nothing happens if you try to click the IP.

### Information about the Issue
It seems that the root cause is missed URL scheme. Sometime ago it was present, but affected by commit 73f29a2b490c4613f1c4548b8cf65e0c0394148d

### Steps to reproduce the behavior

  1. Create a container.
  2. Go to port mapping page (Settings -> Ports). If there are exposed ports, IP address is clickable.
  3. Try to  click by IP

**Comment by FrenchBen** [comment]
Good catch, not sure how it got removed as I can't find the source of the change. 
Do you want to create a PR against your branch and I'll merge it?
