### ISSUE TITLE
Exec on Windows 10 does not support special keys

### ISSUE THREAD

**Issue by ondj** [docker/kitematic#1705]
### Expected behavior

EXEC button runs PowerShell console, which correctly handles special keys

### Actual behavior

Special keys (like backspace, arrow keys etc.) are converted to escape sequences like `^[[C`

### Information about the Issue

Docker CLI button works as expected, also like running `docker exec -it containter bash` from this console

### Steps to reproduce the behavior

  1. Create some new container
  2. Push EXEC button on running container
  3. Use arrow keys

**Comment by FrenchBen** [comment]
What image are you referring to? What happens when you do this via the terminal instead of through kitematic?

**Comment by ondj** [comment]
> What image are you referring to?

Every tested image, for example `python:3.5.1` or `registry:latest`

> What happens when you do this via the terminal instead of through kitematic?

If I run 

```
$ docker exec -it python bash
```
from Docker Quickstart Terminal, everything works fine.

**Comment by FrenchBen** [comment]
We try to be creative when doing a `docker exec` the problem is that most containers don't have `bash` which means that we default to `sh` to make sure we can get into all containers. 
I believe if you do `$ docker exec -it python sh` you'll see the same thing. 

Changing to bash once you're in is pretty straight-forward.

**Comment by ondj** [comment]
@FrenchBen Yes, that's the problem, `sh` in terminal behaves same as EXEC button. But is possible to change Kitematic EXEC function to first try run `bash` and if not exists, then run `sh` command? Or set command name in global or container setting?

**Comment by FrenchBen** [comment]
Unfortunately this would break the container, since the runnable command would fail.

**Comment by rickgrana** [comment]
I am having the same problem

**Comment by twocs** [comment]
I hate this problem. Basically, Kitematic has a button that says Exec but it shouldn't be used, because it will create a shell that is extremely annoying to interact with. The workaround suggested above is to stop using Kitematic, and that's the reason to close the issue?

**Comment by rickgrana** [comment]
Hello, the solution was pretty simple to me: just type _bash_ and be happy :)

**Comment by twocs** [comment]
> Hello, the solution was pretty simple to me: just type bash and be happy :)

Thanks so much. That's very nice to learn!

**Comment by FrenchBen** [comment]
@twocs FYI not images have `bash` which is why it couldn't be used as the default shell.
