### ISSUE TITLE
Issues with VPN, OpenVPN-GUI or custom GUI, TUN.

### ISSUE THREAD

**Issue by Vellicle** [docker/kitematic#1706]
### Expected behavior
Log in
### Actual behavior
"Unable to verify the first certificate", first on IVPN, OpenVPN as well, but even on no VPN now I'm not able to log in.
### Information about the Issue
I have two custom OpenVPN-based TUN/TAP applications and 1 generic build with about 16 or 17 servers. I'm usually always logged into one of them, TUN. This time no matter what I did afterwards it stil won't log in.

### Steps to reproduce the behavior

  1. ... Open VPN, keep it on for about a day, install beta
  2. ... Enter correct credentials, have beta not log in.

**Comment by FrenchBen** [comment]
Is this for Docker for Mac?

**Comment by Vellicle** [comment]
Win 10,  so now I think it might be related to Windows? System normal
otherwise, my device machine us on Debian so I'm a little short on options
in the short run.

**Comment by FrenchBen** [comment]
Since this isn't Kitematic related, please use the [Docker forums](https://forums.docker.com/c/docker-for-windows)
