### ISSUE TITLE
Docker for Windows/Mac should allow sharing of non-User volume (e.g. C:/tmp)

### ISSUE THREAD

**Issue by dmenne** [docker/kitematic#1707]
### Expected behavior
With docker for Windows, you can share drives like C: in settings. So it should be possible to use something like 

docker run -d -v c:/tmp/Gastrobase:/home/shiny/Gastrobase ....

In fact, some user recommend NOT to use the users folder any more because of user registration problems (not confirmed)

### Actual behavior
In Kitematic, you get an error message when trying to change the local folder to c:/tmp or similar

**Comment by FrenchBen** [comment]
@dmenne With Docker for Mac/Windows allowing more flexibility on folder share, this is something we're working on changing. 
I'll keep this issue open to keep track of it and will close it once it's in master.

**Comment by destenson** [comment]
I also would like more flexibility in this matter. My home folder on windows is located on a drive that constantly runs out of space, so I prefer to locate data elsewhere.

**Comment by FrenchBen** [comment]
With Docker for Mac/Windows being more broadly use, we should be able to add more folder support - the previous issue was related to the complexity of mounting the user folders within the VM.

**Comment by destenson** [comment]
Please do. Should I create an issue, or would you? Thanks.

**Comment by FrenchBen** [comment]
@destenson I think we can keep this issue as the main one, but I'll change the title to reflect the above discussion/exchanges
