### ISSUE TITLE
I can't see my containers in kinematic

### ISSUE THREAD

**Issue by zerubeus** [docker/kitematic#1708]
### Expected behavior

find my containers in Kinematic, like always when I open my Windows machine the first thing I do is going to Kinematic and I run my containers

### Actual behavior

I can't find any of my containers in Kinematic.

### Information about the Issue

I'm using the current Docker&kinematic version of Windows, normally when I open my computer I can see my containers in Kinematic, today I've found nothing, even when I "docker ps" or "docker images" I see nothing, like every thing is gone, I lost all my configs , all the data in my MongoDB, all the indexes in my Elasticsearch container, all the jobs in Jenkins, everything is gone. And i'm very sad now ..

**Comment by FrenchBen** [comment]
if `docker ps` is showing no container, then Kitematic wont be showing anything either. 

If this is with Docker for Windows, please open a thread in the Docker forums, as seen in the docs link you received, with your logs and steps to reproduce.
