### ISSUE TITLE
Fix react flattenChildren warnings

### ISSUE THREAD

**Issue by ClemMakesApps** [docker/kitematic#1713]
### Expected behavior
No warnings in console

### Actual behavior
![screen shot 2016-05-27 at 10 42 10 am](https://cloud.githubusercontent.com/assets/3363898/15613163/b40a31da-23f7-11e6-9405-65e4c57549f5.png)

### Steps to reproduce the behavior
Run Kitematic and open developer tools console

**Comment by FrenchBen** [comment]
I've seen it creeped it from times, but can't always pin-point where the children with the same key come from. 
Open to suggestions to track it down.
