### ISSUE TITLE
Use specific docker-machine (i.e., not default)

### ISSUE THREAD

**Issue by richburdon** [docker/kitematic#1714]
### Expected behavior
Should be able to configure docker-machine to use

### Actual behavior
Can't do this.

### Steps to reproduce the behavior
Open kitematic (Mac)

**Comment by FrenchBen** [comment]
Some PRs have been submitted for this but nothing concrete came out, as it would meant that all machines have been properly provisioned. 
Feel free to create a PR for this :D

**Comment by stephendrew** [comment]
I'm not sure I understand your comment @FrenchBen.  As Kitematic is able to open an existing `default` docker machine, what's to stop it opening  a non-default one? We have a default and non-default machine and now disappointed to find we can't use the awesome Kitematic on the second :(

**Comment by FrenchBen** [comment]
@stephendrew My points were as follow:
* What happens if your machine doesn't use the common port?
* What happens if it uses a different version?
* What happens if it uses a custom driver?
* What if the VM has certain mount points that differ from the 'common' ones?

If you look at the amount of available drivers for `docker-machine` here:
https://github.com/docker/machine/tree/master/drivers

You'll see that ALL of them would need to be implemented/supported by Kitematic.

**Comment by stephendrew** [comment]
OK. But as it stands I have created `default` machine in terminal and it could also meet one or more of those criteria yet kitematic connects to it. What's the difference if it has a different name?

**Comment by FrenchBen** [comment]
naming isn't the issue, it's the drivers used with that name. It just happens that we selected default as the name. 
What do you gain from having multiple VM with the exact same setup?

**Comment by stephendrew** [comment]
We don't have the same setup on each docker machine. Simply want to use kitematic to look at the machine...it can do so fine for `default` but not e.g. `build`. The machines are identical but with different containers running.

**Comment by FrenchBen** [comment]
I see - if you'd like to look at it, I'd be happy to review it. 
At this point we're more focused on Docker for Mac and Windows, and the separation of container environment could be made with compose files.
There's an on-going thread about integrating compose. 

I'm open to suggestions also on allowing kitematic to show different stack of containers based on a certain filter.

**Comment by FrenchBen** [comment]
Closing in favor of #231
