### ISSUE TITLE
Release 0.10.5 deb package not detected as debian format

### ISSUE THREAD

**Issue by adomenech73** [docker/kitematic#1718]
### Expected behavior
Get package metadata.
```
dpkg -I /home/albert/Descargas/Kitematic.deb 
 paquete debian nuevo, versión 2.0.
 tamaño 32105540 bytes: archivo de control= 500 bytes.
     554 bytes,    13 líneas     control              
 Package: Kitematic
 Version: 0.10.2-1
 Section: devel
 Priority: optional
 Architecture: amd64
 Depends: git, gconf2, gconf-service, gvfs-bin, libc6, libcap2, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libnotify4, libnss3, libxtst6, python, xdg-utils
 Recommends: lsb-release
 Suggests: gir1.2-gnomekeyring-1.0, libgnome-keyring0
 Installed-Size: 116688
 Maintainer: Kitematic
 Homepage: https://kitematic.com/
 Description: Simple Docker Container management for Mac OS X.
  Run containers through a simple, yet powerful graphical user interface.
```
### Actual behavior
Get unknown format error
```
dpkg -I /home/albert/Descargas/Kitematic-0.10.5-Ubuntu.deb 
dpkg-deb: error: `/home/albert/Descargas/Kitematic-0.10.5-Ubuntu.deb' no es un archivo en formato debian
```
### Information about the Issue

I don't known exactly what could happen but the first one is the package was generated from sorce the second downloaded from the release page

### Steps to reproduce the behavior

1. download release deb package

2.use ``` dpkg -I ``` over it.

**Comment by adomenech73** [comment]
I think the problem is that the package could be zipped in some point of the release process

```
file dist/Kitematic_0.10.4_amd64.deb 
dist/Kitematic_0.10.4_amd64.deb: Debian binary package (format 2.0)

file ~/Descargas/Kitematic-0.10.5-Ubuntu.deb 
/home/albert/Descargas/Kitematic-0.10.5-Ubuntu.deb: Zip archive data, at least v2.0 to extract

```

**Comment by PierreBesson** [comment]
I confirm the issue on Ubuntu 14.04 and 16.04. Although when I extracted Kitematic-0.10.5-Ubuntu.deb it produced a `dist/Kitematic_0.10.4_amd64.deb` file that could be installed correctly.

**Comment by adomenech73** [comment]
Seems to be as easy as to change .deb ex to .zip, actual file ext can cause confusion

**Comment by FrenchBen** [comment]
Seems about right. I can modify the extension to be consistent with all of the other release files.
