### ISSUE TITLE
Unable to download sonarqube official image

### ISSUE THREAD

**Issue by juanbacardit** [docker/kitematic#1727]
### Expected behavior
Download and start a container with sonarqube image

### Actual behavior
Unable to download sonarqube official image, 401 error.

### Steps to reproduce the behavior

  1. run Kitematic
  2. search "sonar"
  3. Download sonarqube official image
  4. Error 401.

**Comment by FrenchBen** [comment]
what do you get when you run:
`docker pull sonarqube` from a terminal?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
