### ISSUE TITLE
Using ESLint

### ISSUE THREAD

**Issue by ClemMakesApps** [docker/kitematic#1729]
Are we using ESLint? We seem to have a `.eslintrc` but our `npm run lint` script uses jsxhint (https://github.com/docker/kitematic/blob/master/package.json#L20)

>    "scripts": {
    "start": "grunt",
    "start-dev": "NODE_ENV=development grunt",
    "test": "jest -c jest-unit.json",
    "integration": "jest -c jest-integration.json",
    "release": "grunt release",
    "release-verbose": "grunt --verbose release",
    "lint": "jsxhint src"
  },

**Comment by FrenchBen** [comment]
I have it running via my editor - it would be cleaner to have it as part of the npm script.

**Comment by ClemMakesApps** [comment]
Are you running `eslint src`?

**Comment by FrenchBen** [comment]
yup - I think we can safely replace it.
