### ISSUE TITLE
Avoiding private registry hostname in FROM directive of Dockerfile

### ISSUE THREAD

**Issue by salmanbaset** [docker/kitematic#1733]
Say I have an image FOOBASE in a private registry (hostname:port PRIVREGHOSTNAME:5000)

I want to use this image in a Dockerfile for a new image FOONEW. Currently, it was to be done as follows:

# Dockerfile
FROM PRIVREGHOSTNAME:5000/FOOBASE
...

That is, the hostname of the private registry is in the Dockerfile.

Now say, I want to change the registries. I have to change the Dockerfile of FOOBASE, rebuild it, and rebuild the image FOONEW that depends on FOOBASE. Obviously, changing the Dockerfile is not desirable. The registry hostname should not be in the Dockerfile

Instead, a better solution is to define a new parameter --registry-url for docker build. E.g.,

docker build -t . --registry-url PRIVREGHOSTNAME:5000

So by default, the image referenced in Dockerfile is searched first in the registry-url and then in Dockerhub.

#210

**Comment by FrenchBen** [comment]
This isn't a Kitematic specific - Please create an issue in https://github.com/docker/docker
