### ISSUE TITLE
Mac - Ability to choose default terminal application (iTerm2)

### ISSUE THREAD

**Issue by spsoni** [docker/kitematic#1736]
### Expected behaviour

In preferences, we should be able to choose preferred terminal application for "Docker CLI" terminal popup.
### Actual behaviour

By default, its opening Mac default terminal.
### Information about the Issue

Its possibly issue in Docker beta for Mac.
### Steps to reproduce the behavior
1. Open Kitematic
2. Click on "DOCKER CLI" from bottom left of the screen once Kitematic is loaded and running.
3. There is no option to choose default/preferred terminal application in Kitematic preferences page/screen.

**Comment by jeeftor** [comment]
When i hit CLI it opens in iterm2 for me - but it doesn't actually seem to work correctly with the CLI

**Comment by FrenchBen** [comment]
@spsoni What version are you running? The latest version fixed this:
https://github.com/docker/kitematic/releases/tag/v0.12.0

@jeeftor The command you posted has nothing to do with any of the above.

**Comment by PaoloFalomo** [comment]
Please, i'd like this feature

**Comment by PaoloFalomo** [comment]
Is this a duplicate of https://github.com/docker/kitematic/issues/1502 ?

**Comment by spsoni** [comment]
yes, its duplicate and fixed. thanks
