### ISSUE TITLE
HTTP code is 500 which indicates error: server error

### ISSUE THREAD

**Issue by SalvorinFex** [docker/kitematic#1740]
### Expected behavior

**Downloading and running the hello-world-nginx docker**

### Actual behavior

**HTTP code is 500 which indicates error: server error**

### Information about the Issue

`HTTP code is 500 which indicates error: server error - Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: Get https://auth.docker.io/token?account=salvorin&scope=repository%3Akitematic%2Fhello-world-nginx%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 10.0.2.3:53: server misbehaving`

### Steps to reproduce the behavior

  1. ... Installed Docker for Windows
  2. ...Run Kitematic
  3. ...Click "Create" for 'hello-world-nginx'

**Comment by SalvorinFex** [comment]
![screenshot 2016-06-04 16 00 27](https://cloud.githubusercontent.com/assets/2433369/15802625/86e59650-2a6d-11e6-8e04-1645c6b1c30f.png)

**Comment by SalvorinFex** [comment]
Huh, I would have expected at least a comment by someone at Docker, after a week.
Most discouraging!

**Comment by FrenchBen** [comment]
@SalvorinFex I missed your earlier issue, but please also understand that our conference, DockerCon is coming up which keeps us pretty busy. 

I tried to replicate your issue without any success. Can you try to logout of your Hub account and see if the image downloads?

**Comment by SalvorinFex** [comment]
@FrenchBen Well, this is even weirder. 
I reboot several times one day last week and this, somehow, caused Docker to start working :/

Any idea what the `10.0.2.3:53` address is from?

**Comment by FrenchBen** [comment]
the `10.0.2.3` is the internal Docker Daemon IP - If after a few reboots it started working, there's a good chance the networking didn't work as expected, but finally did. Perhaps an update was pushed in the middle somewhere?

**Comment by SalvorinFex** [comment]
OKay, I think the Toolbox version did go up to 1.11.2, when I had installed 1.11.1.
Don't know if that matters.

You may close the issue.

Thank you.
