### ISSUE TITLE
newbie question: filled up all the space and don't know how to delete containers on a Mac

### ISSUE THREAD

**Issue by TheBigBear** [docker/kitematic#1744]
### Expected behaviour
choosing a container such as 'hello-world-nginx' I expect it to start up the container. 

### Actual behaviour
it does not start it up anymore but now it says instead in red:

```
We're sorry, but there seems to be an error: 
```

```
write /var/lib/docker/image/aufs/imagedb/content/sha256/03b4557ad7b98859ac39aee048ce400a664de81cfa625fd7dfa94e61ac7c1947.tmp: no space left on device
```
and if i try to delete one such as the hello-world-nginx one, it says:

```docker rmi 03b4557ad7b9```
```
Error response from daemon: write /var/lib/docker/image/aufs/repositories.json.tmp: no space left on device
```

### Information about the Issue
how do I recover form this and get rid of images when it doesn't start up anymore?

### Steps to reproduce the behaviour
I downloaded quite a few images and now I am "stuck", presumably because I filed up the docker main container with too many images, but I don't know how to get to those images and remove some of them so it starts up again.

**Comment by FrenchBen** [comment]
If you open Kitematic - you can click the `x` next to all of the containers. 
You can then go to the `My Image` tab and similarly, click the `ooo` to see the 'Delete' button for each image. 
If you feel like nothing is worth saving, you can do:
`docker rm -f $(docker ps -aq)`
to remove all containers
then:
`docker rmi $(docker images -q)` 
to remove all images

please beware that the above deletes **EVERYTHING**
