### ISSUE TITLE
Layout problem in Linux version of Kitematic

### ISSUE THREAD

**Issue by sbacic** [docker/kitematic#1745]
### Expected behavior
Same layout as in non-Linux versions. 

### Actual behavior
This is what I get when I load a container.
![kite](https://cloud.githubusercontent.com/assets/1626419/15873260/1d672070-2cfe-11e6-8ab3-faebabe45229.png)

### Information about the Issue
I've noticed that this only happens in the Linux version (I'm running Ubuntu 14.04). The Mac and Windows versions do not have this issue.

### Steps to reproduce the behavior
I've followed this guide:
https://github.com/docker/kitematic/wiki/Early-Linux-Support

After the installation, Kitematic threw errors, so I manually install some packages (electron). I've also pulled the latest changes.

I'm willing to work on a fix for this issue.

**Comment by FrenchBen** [comment]
@sbacic Can you check if the Ubuntu release `.deb` has the same issue?
https://github.com/docker/kitematic/releases

If you can send a fix it would be greatly appreciated!

**Comment by sbacic** [comment]
@FrenchBen 

I get the following error when I try to install from deb:

_dpkg-deb: error: `Kitematic-0.10.5-Ubuntu.deb' is not a debian format archive
dpkg: error processing archive Kitematic-0.10.5-Ubuntu.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 Kitematic-0.10.5-Ubuntu.deb_

I'll get started on that layout fix ASAP, but maybe somebody should look over this as well.

**Comment by FrenchBen** [comment]
@sbacic Haven't released the latest patch - the `.deb` is actually a `.zip`.
```
mv Kitematic-0.10.5-Ubuntu.deb Kitematic-0.10.5-Ubuntu.zip
unzip Kitematic-0.10.5-Ubuntu.zip
```
You can then try to install the proper `.deb` in the `dist/` directory

**Comment by sbacic** [comment]
@FrenchBen 

OK, finally managed to install the deb and everything appears to be displaying properly now. Does that mean that this bug is already fixed? Or can I work on it (since I assume the bug is ?

I should also mention that I got this warning when I tried to install and had to force the installation:

_The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. 
Please contact the person or organisation who provided this package file and include the details beneath._

Not a biggie since everything seems to work but I'd get it looked over all the same.

**Comment by FrenchBen** [comment]
It's possible that it's in the newer version - If you don't mind looking at it, it would be helpful. 
Regarding the package, it's possible that signing is needed somewhere. Probably something we should add.

Thanks!

**Comment by sbacic** [comment]
OK, I'll get on it then. Also, here are some of the errors I got when installing the deb:

_Lintian check results for /home/sbacic/Downloads/dist/Kitematic_0.10.4_amd64.deb:
E: Kitematic: bad-package-name
E: Kitematic: package-not-lowercase
E: Kitematic: maintainer-address-missing Kitematic_

The rest is a bunch of "wrong-file-owner-uid-or-gid" errors for the files in the package. I suspect the package just doesn't follow their quality standards (but that doesn't rule of package signing as a potential issue, though).

**Comment by FrenchBen** [comment]
Thanks for the feedback - All of these seem manageable to update/change.

**Comment by sbacic** [comment]
The bug appears to have been caused by an outdated dependency rather than a defect in the Kitematic codebase. Once I updated the dependencies to the newest version the bug was gone.

I think it's safe to close this issue.

**Comment by adomenech73** [comment]
@FrenchBen The message @sbacic talks about, happens when installing on graphical envronment, seems that it does extra checks in this way, and finds that the package don't fullcomplish [Debian policy](http://www.debian.org/doc/debian-policy/ch-controlfields.html),  but I think it's easy to fix using lowercase for the package name and changing the maintainer address, because I recall usig github Kitematic project url and probably is looking for email format

**Comment by FrenchBen** [comment]
@adomenech73 Ahh thanks for chiming in on this. Do you think this is something you could take care of?

**Comment by sbacic** [comment]
@FrenchBen 

Hi, has the issue with the deb package been solved? If not, I'm volunteering to fix it.

**Comment by FrenchBen** [comment]
@sbacic Thanks for the help - I believe we now have a better deb package, which is still wrapped in a Zip file. 
If you'd like to fix the following it would be of great help:
```
Lintian check results for /home/sbacic/Downloads/dist/Kitematic_0.10.4_amd64.deb:
E: Kitematic: bad-package-name
E: Kitematic: package-not-lowercase
E: Kitematic: maintainer-address-missing Kitematic
```

**Comment by sbacic** [comment]
OK, I'm on it.

**Comment by sbacic** [comment]
@FrenchBen 

Hey Ben, I've made a commit with the fixes:
https://github.com/docker/kitematic/pull/1847

If you need anything else, I think it's best that we continue there.

**Comment by FrenchBen** [comment]
It's been merged and is in the latest release:
https://github.com/docker/kitematic/releases/tag/v0.12.1

@sbacic can you confirm that it looks good?

**Comment by sbacic** [comment]
@FrenchBen 

All good. I pull the latest changes, generated a release and installed from the deb without a hitch. The layout bug is gone as well.
