### ISSUE TITLE
Thank you for creating this! 

### ISSUE THREAD

**Issue by alicetoreno** [docker/kitematic#1747]
To the developers who made this, THANK YOU THANK YOU THANK YOU. 

I was asked to look into Docker 3 months ago, and it wasn't until today that I found this gem to help me use Docker. Are you guys working on this full time or is this a hobby project? If you guys are interested, I'd definitely love to forward you to our HR - for front end developers our range is $125k - $165k.

**Comment by elesant** [comment]
You are welcome @alicetoreno :)
