### ISSUE TITLE
Unable to Create Container

### ISSUE THREAD

**Issue by werebear73** [docker/kitematic#1748]
### Expected behavior
Create Container

### Actual behavior
Got Error
![image](https://cloud.githubusercontent.com/assets/3290150/15895267/fc334c9c-2d4f-11e6-8f95-acf616e4b806.png)

### Steps to reproduce the behavior

  1. Searched "bettervoice/freeswitch-container"
  2. Clicked CREATE to create the container

**Comment by FrenchBen** [comment]
@werebear73 As you can see the error complains about the `Tag latest not found`.
If you look at the hub repository:
https://hub.docker.com/r/bettervoice/freeswitch-container/tags/

You will see that indeed it does not exist - Select a different tag before clicking 'Create' and you'll be all set.

**Comment by siracdmr** [comment]
@FrenchBen  thanks buddy
