### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by rlameijer** [docker/kitematic#1749]
### Expected behavior
I am using Kitematic (Alpha). When it starts up, it is checking the Docker connection and then shows me this error:
Error: getaddrinfo ENOTFOUND docker.local docker.local:2375

I then press the "Use virtualbox" button and things seem to be fine. 
Click on "My repos"
Choose "ibmdashdb" and press the "Create" button 
At first things seem to be fine but it shows me this error after ±70% of the download:
write /mnt/sda1/var/lib/docker/tmp/GetImageBlob250329780: no space left on device

I have tried it a couple of times now, but I am ont getting any further. 

### Actual behavior
See above

### Steps to reproduce the behavior
See above
  1. 
  2. ...

**Comment by FrenchBen** [comment]
2 things:
* Get the latest Kitematic, the ENOTFOUND should be better.
* See the wiki to change your VM's disk size: https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
