### ISSUE TITLE
Odd versioning with linux and mac package

### ISSUE THREAD

**Issue by DuckThom** [docker/kitematic#1751]
### Expected behavior
0.10.5 Release installs version 0.10.5

### Actual behavior
When installed on a mac, the app reports version 0.10.4 and Ubuntu 0.10.5 "deb" (actually a zip) contains a 0.10.4 installer deb.

**Comment by FrenchBen** [comment]
@DuckThom there was some missed version updates. A new release will be made early next week, which should amend those mistakes.

Thanks for the issue.
