### ISSUE TITLE
getaddrinfo ENOTFOUND docker.local docker.local:2375

### ISSUE THREAD

**Issue by khanshakeeb** [docker/kitematic#1754]
### Steps to reproduce the behavior

  1. Open Kitematic
  2. Create MySQL  container

**Comment by FrenchBen** [comment]
Hi @khanshakeeb The latest version of kitematic found here shouldn't be causing this issue. 
Can you provide details of your OS?

**Comment by vincenzocaruso** [comment]
Hi, @khanshakeeb, i've the same problem with a clean installation of docker and its tools. 
I work with Windows 10 64x.

**Comment by aledelgo** [comment]
same for me. Win 10x64 + last version of VirtualBox already (tough it was not detected by the Docker installer, on the contrary GIT was detected)

**Comment by FrenchBen** [comment]
@vincenzocaruso @aledelgo Kitematic has a preference for Docker for Windows. If you're still on Virtualbox you then have the ability to click on that button and use it. 
We're working on a better way to check this, for the Kitematic start-up to be cleaner.

**Comment by deividfortuna** [comment]
I have the same issue but at the end I select VM and works fine.

**Comment by FrenchBen** [comment]
@deividfortuna As explained it's as-expected, as we have a slight preference for a Docker for Mac/Win setup

**Comment by svandragt** [comment]
When Kitematic is installed on a pre-Windows 10 system, Docker for Windows is not avaialble so it should fallback to the virtualbox solution and never show this error?

**Comment by vincenzocaruso** [comment]
@FrenchBen I use dokcer for windows and I don't have installed Virtual Box because i would use Hyper-V.
I've updated Docker with the last release 1.12.0 beta 21 and Kitemac still not working.

**Comment by FrenchBen** [comment]
@vincenzocaruso Can you verify that this release works as expected:
https://github.com/docker/kitematic/releases/tag/v0.12.0

**Comment by vincenzocaruso** [comment]
@FrenchBen last version works, thank you for your support.
