### ISSUE TITLE
Search is poor

### ISSUE THREAD

**Issue by warrickhill** [docker/kitematic#1756]
### Expected behavior

when searching for jenkinsci/jenkins it should put https://hub.docker.com/r/jenkinsci/jenkins/ first
 
### Actual behavior

https://hub.docker.com/r/jenkinsci/jenkins/ is not top

### Information about the Issue

search functionality is poor, would be good if you could explore users repos like you can on the web

### Steps to reproduce the behavior

  1. search for jenkinsci/jenkins
  2. don't find https://hub.docker.com/r/jenkinsci/jenkins/ at the top of the list

**Comment by FrenchBen** [comment]
I agree that when passed as such, the `jenkinsci/jenkins` repo should be the first one to show. 
Kitematic's search behavior is consistent with what Hub shows:
HUB:
![hub](https://cloud.githubusercontent.com/assets/3965324/16023701/d287a970-3172-11e6-97d2-a027534771e2.png)
`jenkinsci/jenkins` is the 3rd repo.

Kitematic:
![kitematic](https://cloud.githubusercontent.com/assets/3965324/16023706/e2a5a398-3172-11e6-9ea9-287cee01d7c9.png)
`jenkinsci/jenkins` is the 3rd repo.
