### ISSUE TITLE
Docker CLI not triggering/opening from Kitemetic DockerCli option in windows

### ISSUE THREAD

**Issue by sabbir360** [docker/kitematic#1758]
### Expected behavior:
Open CLI while clicking on DOCKER CLI on Kitemectic

### Actual behavior
Not opening

### Issue Details:
I'm using windows 10 and docker beta, while I'm clicking *Docker CLI* from bottom left of kitemetic, its not opening/triggering any CLI interface for me. 

### Steps to reproduce the behavior

  1. Open Kitemetic on windows 10
  2. Click on "DOCKER CLI" option on bottom left of kitemetic

**Comment by FrenchBen** [comment]
Hello @sabbir360 Can you try the pre-release created today and let me know if the issue persists?

**Comment by sabbir360** [comment]
Its working, thanks.
