### ISSUE TITLE
Issue with MySQL Installation

### ISSUE THREAD

**Issue by abhishekbiswas** [docker/kitematic#1761]
### Expected behavior
should install

### Actual behavior
not getting installed

### Information about the Issue
Error Message:
failed to register layer: rename /mnt/sda1/var/lib/docker/image/aufs/layerdb/tmp/layer-171301421 /mnt/sda1/var/lib/docker/image/aufs/layerdb/sha256/36e515ec7546ccd7a3f6dc1e6cebf7306db5a6078227e423ea197437c3b300de: directory not empty

### Steps to reproduce the behavior

  1. ... downloan MySQL from Kitematic
  2. ...

**Comment by FrenchBen** [comment]
is this on a fresh install? Did you have any other mysql containers previously installed. 
I can't replicate the issue on my end

**Comment by abhishekbiswas** [comment]
I started a fresh installation and quit it half-way. From that point onwards, whenever I was trying to install it I was receiving the error. 


I believe the issue is all about file cleanup. I deleted couple of files mentioned in the error message and it started working for me.

Thanks | Abhishek

**Comment by FrenchBen** [comment]
Please re-open if the issue happens again. 
Thanks
