### ISSUE TITLE
missing latest tag

### ISSUE THREAD

**Issue by kenneyhe** [docker/kitematic#1764]
### Expected behavior
latest tag available
### Actual behavior
missing latest tag
### Information about the Issue
Tag latest not found in repository docker.io/scrapinghub/cloudera-manager
with kinematic

### Steps to reproduce the behavior

  1. ... checkout latest from information
  2. ...

**Comment by thaJeztah** [comment]
I don't think there's much that can be done here; the repository you're referring to doesn't have a `:latest` tag; https://hub.docker.com/r/scrapinghub/cloudera-manager/tags/

I suggest to open an issue in the issue tracker for that image; https://github.com/scrapinghub/docker-cloudera-manager
