### ISSUE TITLE
Enhancement request: progress bar on download

### ISSUE THREAD

**Issue by DavidBates** [docker/kitematic#1765]
### Expected behavior
To be able to view progress of downloading a container
### Actual behavior
Just a downloading notification without progress
### Information about the Issue
Containers can be large downloads on slower networks often taking hours. It would be nice to have a %complete, time left, or a progress bar during the download phase to indicate how much longer it would be before the download is complete. 

### Steps to reproduce the behavior

  1. Download a large container
  2. Brew coffee

**Comment by FrenchBen** [comment]
I don't understand - There is a download status already:
<img width="484" alt="progress" src="https://cloud.githubusercontent.com/assets/3965324/16172940/0ffaf266-3548-11e6-91c4-873dc33ccc81.png">

**Comment by DavidBates** [comment]
I just checked on another system and you are right. Mine has a spinning wheel saying connecting to docker hub. I am guessing I fall into issue #1639
