### ISSUE TITLE
Drawing Windows in Kitematic causes high CPU usage

### ISSUE THREAD

**Issue by klousiaj** [docker/kitematic#1766]
### Expected behavior
Running Kitematic should not cause my WindowServer process to consistently use high % of my CPU(s)
### Actual behavior
Running Kitematic reliably spins the WindowServer process, frequently over 20% CPU usage. Additionally, it has three of its own processes that each use ~8% of my CPU.
### Information about the Issue
![screen shot 2016-06-17 at 10 25 27 pm](https://cloud.githubusercontent.com/assets/4754718/16168597/e32bae0a-34da-11e6-98f7-9fb5a029aa45.png)

El Capitan v10.11.5
MBP Mid 2009
Kitematic 0.10.4

_Workaround_ - minimizing Kitematic reduces CPU usage for WindowsServer

### Steps to reproduce the behavior

  1. Start and run Kitematic.

**Comment by FrenchBen** [comment]
@klousiaj Can you try the latest release? 
https://github.com/docker/kitematic/releases/tag/v0.12.0

We removed some 'animation' bits that were causing high cpu usage

**Comment by klousiaj** [comment]
Significantly improved. Good work. Will mark as closed in v0.12.0.
