### ISSUE TITLE
support window 7

### ISSUE THREAD

**Issue by DomTeng** [docker/kitematic#1768]
### Expected behavior

I thought it support window 7 64bit

### Actual behavior
it can be installed, but can't be run

### Information about the Issue
my os is win7 64bit,

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by DomTeng** [comment]
another question, i can't find the log file, if it can be ,i think it's better.

**Comment by FrenchBen** [comment]
What did you try?
What happened?
What did you expect?

**Comment by DomTeng** [comment]
@FrenchBen ,sorry for i don't describe what i want clearly.
I had installed dockertoolbox, and Docker Quickstart Terminal can be used successed. but when click the Kitematic.exe, it didn't run.

![screenshot](https://cloud.githubusercontent.com/assets/20020743/16175618/758b6226-3626-11e6-8a0c-056ba9ed5fc1.jpg)
