### ISSUE TITLE
Unable to Fetch Restcomm Repo

### ISSUE THREAD

**Issue by bilal966** [docker/kitematic#1772]
### Steps to reproduce the behavior

  1. Select Repo on Docker (restcomm)
  2. Select Tag "Stable"
  3. Click on Create button

Output:
Network timed out while trying to connect to https://index.docker.io/v1/repositories/restcomm/restcomm/images. You may want to check your internet connection or if you are behind a proxy

**Comment by ErrolSayre** [comment]
I'm getting this same error trying to install mattermost.

**Comment by FrenchBen** [comment]
@bilal966 Not sure what you searched for or clicked on - I followed the exact steps that you provided and get a proper download:
<img width="1343" alt="restcomm" src="https://cloud.githubusercontent.com/assets/3965324/16322334/45cea5dc-3957-11e6-88e5-8ad3e06763d7.png">

**Comment by FrenchBen** [comment]
@ErrolSayre Can you provide a link to the Docker Hub image you're trying to download?

**Comment by ErrolSayre** [comment]
I'm away from that box, but I was trying to install mattermost-preview and got a similar error message.

**Comment by banesto** [comment]
I have the same issue with Docker 2 beta. Strangely enough, when I connect to my company's VPN then it's ok and I can pull images. It's some sort of networking problem, but I'm not able to tell if the root of issue is within IPS, my router AirPort, Mac or Docker. Maybe https://index.docker.io/v1/repositories/ is running on some non-standart port or something?

**Comment by FrenchBen** [comment]
@banesto if changing network allows you to pull, then it's more than likely related to your own network.

**Comment by banesto** [comment]
@FrenchBen Yes, but the issue still persists on a computer without any VPN installed and there's no clear hint on how to resolve this or what is the blocker.

**Comment by FrenchBen** [comment]
@banesto Unfortunately this is outside of the scope of Kitematic, as it's related to your particular network setup more than the tool itself. 
I would start by confirming that you cannot pull outside of the VM, then inside of the VM and try normal network-related stuff to gain some knowledge as to why your network is blocking this.
