### ISSUE TITLE
Cannot mount local windows folder using docker for windows

### ISSUE THREAD

**Issue by vicanfon** [docker/kitematic#1774]
### Expected behavior
I have mounted a windows local folder using this sentence:

docker run -v /c/Users/vanay/Downloads/java-example:/eslap/java-example --entrypoint=bash -it name

when listing content of java-example, the folder is void. The volume relationship is listed in Kitematic, and no error is shown in the log.

### Actual behavior

Nothing is mounted.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
@vicanfon Make sure you followed the docs on sharing the folder:
https://docs.docker.com/docker-for-windows/#shared-drives
