### ISSUE TITLE
docker-upgrade ends with permission denied

### ISSUE THREAD

**Issue by ReneVallecillo** [docker/kitematic#1775]
### Expected behavior

`docker-machine upgrade default
`server api gets updated to latest version

### Actual behavior
`docker-machine upgrade default`

I get this:

ownloading /Users/reneval/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.0-rc2/boot2docker.iso...

open /Users/reneval/.docker/machine/cache/boot2docker.iso.tmp619339182: permission denied

### Information about the Issue
I tried changing the permissions and ~/.docker owner to user:staff. Same issue

### Steps to reproduce the behavior

  1. Use docker for mac
  2. docker create default --driver xhyve
  3. docker-machine env default
  4. eval $(docker-machine env default)
  5. docker ps
  6. You will get:  Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
  7. docker-machine upgrade default
  8. Ends with open /Users/reneval/.docker/machine/cache/boot2docker.iso.tmp193116981: permission denied

**Comment by FrenchBen** [comment]
Looks like you're using an external plugin to handle `xhyve` - Please open an issue with the plugin owner.

**Comment by ReneVallecillo** [comment]
Can I avoid to use an external plugging? @FrenchBen. I used it because it didn't seem to come out of the box on the new docker.

**Comment by FrenchBen** [comment]
@ReneVallecillo Why not use Docker for Mac? https://www.docker.com/products/docker#/mac

**Comment by ReneVallecillo** [comment]
@FrenchBen I did, but I thought I didn't come with the driver/plugging. I guess my bad, I have to setup docker in 3 env(win, osx, ubuntu) and I may be confused on the basics. I'll try again and see what happens.
