### ISSUE TITLE
spark 2 image not downloading

### ISSUE THREAD

**Issue by aniqurrehman** [docker/kitematic#1777]
### Actual behavior
 i am trying to down load spark2 immage but it is not downloading.
### Information about the Issue

 i am trying to down load spark2 immage but it is not downloading.
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
The image is 2GB - make sure you are on a stable internet connection. 
Try to do a `docker pull bigdatauniversity/spark2:latest`

**Comment by aniqurrehman** [comment]
no such container404no such id: spark2i receive this error on kinematics.

 

    On Friday, June 24, 2016 3:51 AM, French Ben <notifications@github.com> wrote:
 

 The image is 2GB - make sure you are on a stable internet connection. 
Try to do a docker pull bigdatauniversity/spark2:latest—

**Comment by FrenchBen** [comment]
@aniqurrehman it sounds like the container failed to be created - I would advise you to read the docs on the image as to what needs to be passed to it for the container to be created properly.
