### ISSUE TITLE
Malformed URL on link in "Ports" tab (missing http scheme colon)

### ISSUE THREAD

**Issue by andresvia** [docker/kitematic#1779]
### Expected behavior

Click "localhost" link on "Ports" tab, "http://localhost:5000", opens.

### Actual behavior

Click "localhost" link on "Ports" tab, "http//localhost:5000" opens. (no colon : after http)

### Information about the Issue

Bug.

### Steps to reproduce the behavior

  1. Get latest registry image.
  1. Go to "Ports" tab
  1. Change mapped port: container port 5000 to mac port 5000

**Comment by Fahrradflucht** [comment]
Pinging @FrenchBen to close this issue as it is resolved with #1783.
