### ISSUE TITLE
kitematic doesn't autorefesh to show latest dockerhub images after latest push

### ISSUE THREAD

**Issue by babatundebusari** [docker/kitematic#1782]
### Expected behavior
kitematic should auto-refresh and show latest dockerhub images under "my repos"

### Actual behavior
Every time i push latest docker images to dockerhub, i have to sign out and sign back in to have latest image show up under "my repos" tab

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
There isn't any listener for push, but you can always click the tab again to force a refresh.
Feel free to implement it and submit a PR :)
