### ISSUE TITLE
(Ubuntu) Kitematic displayed error on startup because it was not sudoed

### ISSUE THREAD

**Issue by Koroeskohr** [docker/kitematic#1784]
When starting Kitematic through my Cinnamon menu, the first loading screen would display 
`Error: connect EACCES /var/run/docker.sock` when reaching 50%. I thought this was a docker daemon issue but I tried `sudo Kitematic` in console, then it finally started.

I guess it doesn't ask the right permissions, I'm no Unix pro, sorry about that.

Kitematic 0.12.0
Ubuntu 14.10
Docker 1.11.2

**Comment by FrenchBen** [comment]
Please see the documentation on allowing docker commands from a regular user:
https://docs.docker.com/engine/installation/linux/ubuntulinux/#create-a-docker-group
