### ISSUE TITLE
Error starting hello-world-nginx sample

### ISSUE THREAD

**Issue by VeryKross** [docker/kitematic#1792]
### Expected behavior
Expected it to download hello-world-nginx sample, install and start the Docker machine

### Actual behavior
Timeout error - Try and restart your VM by running:
"docker-machine restart default" in a terminal

### Information about the Issue
This is the first thing I've tried since installing Docker for Windows. Docker appears to be running correctly (according to the icon). This was also the first thing I tried with Kitematic once I downloaded it and unzipped into C:\Program Files\Docker\Kitematic

### Steps to reproduce the behavior

  1. Run Kitematic and click "Create" on the "hello-world-nginx" sample.
  2. Watch Kitematic attempt to connect to Docker Hub
  3. Note the timeout error

----------------------------
Never mind - I discovered that what was happening is that the Docker Hub authentication was failing (behind the scenes) because I was using a new DH account that hadn't been verified via email yet. It appears that this is required before the downloads will be permitted but, unfortunately, its reported to the end-user as a timeout error.

**Comment by FrenchBen** [comment]
A couple of things are confusing - you're mentioning Docker machine, but seem to be running the Docker for Windows beta?
In that case, `docker-machine restart default` wouldn't work. 

The timeout only happens if you clicked on 'Use VirtualBox' - I would check that `docker ps` first works in a simple `PowerShell` window

**Comment by VeryKross** [comment]
Thanks for the reply. Yes, this is the Windows beta - the use of "docker-machine restart default" is what was suggested by Kitematic running on Windows so if that's an invalid command then that's a separate issue. The container is running now, although it doesn't show up when I execute "docker-machine ls" at a command prompt (the command works, just comes back with an empty list).

**Comment by FrenchBen** [comment]
@VeryKross That command should only shows up if you selected Virtualbox within the UI, option which would've showed up if the native setup didn't work.

`docker-machine` is not involved with Docker for Windows

**Comment by pmario** [comment]
>`docker-machine` is not involved with Docker for Windows 

But for consistency reasons it should be. I think this should be an issue somewhere.

**Comment by FrenchBen** [comment]
@pmario There's already an open issue for it :)
https://github.com/docker/machine/issues/3543

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
