### ISSUE TITLE
Can't reach dockerhub from docker for mac

### ISSUE THREAD

**Issue by randalllj** [docker/kitematic#1793]
### Expected behavior
run# docker pull influxdb

should download image

### Actual behavior
Error response from daemon: Get https://registry-1.docker.io/v2/library/influxdb/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Finfluxdb%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.65.1:53: dial tcp 192.168.65.1:53: getsockopt: connection refused
### Information about the Issue

Version 1.12.0-rc2-beta17 (build: 9779)
ff18c0c63c5ff3c4a4a925d191d5592d655779d7

### Steps to reproduce the behavior

  1. docker pull influxdb
  2. ...

**Comment by FrenchBen** [comment]
@randalllj It's not just that image, it's all images - Seems to be an issue with Docker Hub.
A ticket has been dispatched internally
