### ISSUE TITLE
bug: error pulling image configuration

### ISSUE THREAD

**Issue by buluma** [docker/kitematic#1799]
### Expected behavior
Download Image
### Actual behavior
error pulling image configuration
### Information about the Issue
error pulling image configuration: Get https://registry-1.docker.io/v2/library/jenkins/blobs/sha256:d5c0410b1b443d3ed805078d498526590ae76fc42a1369bc814eb197f5ee102b: net/http: TLS handshake timeout

### Steps to reproduce the behavior
  1. Click create on image
  2. Cannot connect

**Comment by FrenchBen** [comment]
Sounds like you're behind a proxy/firewall?

Perhaps give [Docker for Mac/Windows](https://www.docker.com/products/docker) a try?

**Comment by buluma** [comment]
That wasn't the case but i got it working.

**Comment by FrenchBen** [comment]
for record keeping purposes, would you mind sharing what you did to get it working, so that other users may get this information as well?

**Comment by sauravskumar99** [comment]
@buluma  can you please share how you got the problem resolved. I am facing the same issues. Thank You

**Comment by buluma** [comment]
@sauravskumar kitematic seems to have connectivity issues sometimes. i had to try later for it to work.
