### ISSUE TITLE
SqlServer Express container fails in Kitematic

### ISSUE THREAD

**Issue by floradu88** [docker/kitematic#1802]
### Expected behavior

Should start this image ```docker pull brogersyh/sqlexpress```

### Actual behavior

```HTTP code is 500 which indicates error: server error - [object Object]```

### Information about the Issue

The container fails to run

### Steps to reproduce the behavior

  1. In Kitematic I select this container
  2. Run new container

**Comment by FrenchBen** [comment]
It looks like the error isn't very descriptive, but the error is actually in the image itself. 
If you try to run it manually via `docker run brogersyh/sqlexpress` you'll see that the error it gives is:
`oci runtime error: Cwd must be an absolute path.`
