### ISSUE TITLE
HTTP code is 404 which indicates error: no such image - [object Object]

### ISSUE THREAD

**Issue by jimarasim** [docker/kitematic#1803]
### Expected behavior
docker image downloads and starts through kitematic after restart
### Actual behavior
HTTP code is 404 which indicates error: no such image - [object Object]
### Information about the Issue
docker beta kitematic

### Steps to reproduce the behavior
restart computer
click whale
start kitematic 
download the latest jenkins container
occurs while downloading
<img width="1262" alt="screen shot 2016-07-03 at 5 35 55 pm" src="https://cloud.githubusercontent.com/assets/2319417/16548486/a152d712-4144-11e6-82d8-dad7cebcc288.png">

  1. ...
  2. ...

**Comment by skyw00lker** [comment]
same error...

**Comment by FrenchBen** [comment]
Sorry there was a light issue that caused this. It's all working as expected now
