### ISSUE TITLE
Getting error while trying to install docker--cloudera-quickstart

### ISSUE THREAD

**Issue by SanjayKumar14** [docker/kitematic#1805]
failed to register layer: Untar re-exec error: exit status 1: output: write /etc/solr/conf.dist/collection1/conf/velocity/jquery.autocomplete.js: no space left on device

**Comment by FrenchBen** [comment]
If this is using VirtualBox please see:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space

Otherwise delete some of the images stored on the VM to clear-up some space.
