### ISSUE TITLE
Kinematic failing to run local image from third party

### ISSUE THREAD

**Issue by stevek** [docker/kitematic#1806]
### Expected behavior
Image downloaded from 3rd Party is selectable in Kinematic and will run.

### Actual behavior
Image fails to run.

### Information about the Issue

![kitematic_error](https://cloud.githubusercontent.com/assets/884627/16591583/6f291d84-4291-11e6-9e8d-a9392dafb86e.png)

### Steps to reproduce the behavior

1. Download image locally from 3rd Party repo (JFrog Artifactory Docker Image - Official/Latest) using Docker CLI
2. Click "New Container" in Kinematic UI
3. Select "My Images" in selection screen.
4. Select "Create" on 3rd Party Image entry - observe error.

**Comment by FrenchBen** [comment]
This is a known issue. https://github.com/docker/kitematic/issues/1643
