### ISSUE TITLE
Error: Problem about download

### ISSUE THREAD

**Issue by zkh90644** [docker/kitematic#1808]
I want to download a container in the app.
Than when I cancel the container and download it again, the app shows that there are 2 progress bar in the same container,just like there are 2 thread to download the container.

**Comment by FrenchBen** [comment]
Screenshot and steps to reproduce?
If you click on download and then download again, 2 containers will be created.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
