### ISSUE TITLE
Docker image not woking

### ISSUE THREAD

**Issue by Ishu12** [docker/kitematic#1811]
### Expected behavior
Docker inage is not getting up,its not working
### Actual behavior
giving error
### Information about the Issue
HTTP code is 404 which indicates error: no such image - No such image: jfrog-docker-reg2.bintray.io/jfrog:latest

### Steps to reproduce the behavior

  1. ...$ docker pull jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro:latest
  2. ...docker pull jfrog-docker-reg2.bintray.io/jfrog/artifactory-registry:latest

**Comment by FrenchBen** [comment]
Looks like this is on a private registry, which makes it difficult for us to debug. 
Previous similar issue indicate that neither `artifactory-pro` nor `artifactory-registry` have a tag of `latest`
