### ISSUE TITLE
"HTTP Code is 500 which indicates error: [object Object]"

### ISSUE THREAD

**Issue by komocode** [docker/kitematic#1814]
### Expected behavior
Container should be started

### Actual behavior
Pressing Start button on a container causes an error message that appears for a few milliseconds before disappearing.

"HTTP Code is 500 which indicates error: server error - [object Object]"

Container does not start at all.

### Information about the Issue
Updated Docker for Mac private beta 
Version 1.12.0-rc3-beta18 (build: 9996)
ec40b14c72adc0bff3b01fa8886dae7f2eee1541

Can no longer start my containers.

### Steps to reproduce the behavior

  1. Launch Docker for Mac 1.12.0-rc3-beta18 (build:9996)
  2. Launch Kitematic 0.10.5
  3. Press Start on an existing MariaDB container
  4. Observe error for a few milliseconds before disappearing

 
![screen shot 2016-07-08 at 12 37 45 pm](https://cloud.githubusercontent.com/assets/226526/16699415/d23baf76-4508-11e6-957c-42b605c478e0.png)

**Comment by FrenchBen** [comment]
@komocode Thank you for the report. This is similar to https://github.com/docker/kitematic/issues/1802 as the error provided isn't detailed. 

Your solution however was at the top of the changelog when moving from RC2 to RC3:
https://docs.docker.com/docker-for-mac/troubleshoot/#/recreate-or-update-your-containers-after-beta-18-upgrade

Thanks for the info.
