### ISSUE TITLE
Start imedeatly stops.

### ISSUE THREAD

**Issue by NVentimiglia** [docker/kitematic#1815]
### Expected behavior

I pressed the start button and The container would tun,

### Actual behavior

Start then stopped.

### Information about the Issue

IDK, using latest. total docker noob.

### Steps to reproduce the behavior

  1. ... Download microsoft/dotnet:latest
  2. ... Run the container

**Comment by NVentimiglia** [comment]
Resolved. Issue is I was not logged in. Please provide some messaging.

**Comment by FrenchBen** [comment]
I'm not sure if I understand why logging in made a difference.
Each container can have it's on set of requirements which makes it impossible for us to provide the appropriate messaging.

The proper approach is to read the documentation provided for that image and confirm that you're doing everything it's asking you to do.
