### ISSUE TITLE
error pulling image configuration:

### ISSUE THREAD

**Issue by gengzhengtao** [docker/kitematic#1817]
### Steps to reproduce the behavior
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/18/1859b344ee112e57a039525b26d6354688568f0f3d6fd0f7f8c9e3e9db2f212d/data?Expires=1468050787&Signature=VFmzB1iWxXWZqh3CuY4dXhuxLQVmTxKqFmF9-wyqFYQrX2qxFFVkeB-4opoBNmnnCOOmtraHsP2ZDiItibR2ETpz8rn7tO5h9rGjPHWJPdqaQFHULOioogcgcGnJIR08CU5xQd~Fa8XU-jGbPXRrmDK~tb-kvbgGnh-a01Y0ULE_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: server misbehaving

**Comment by FrenchBen** [comment]
Looks like it's related to https://github.com/docker/docker/issues/24344 - Closing in Favor of the docker/docker issue.
