### ISSUE TITLE
Toolbox install error - Does not import existing Virtualbox settings

### ISSUE THREAD

**Issue by putztzu** [docker/kitematic#1818]
### Expected behavior
Toolbox installs, then attempts to create the first Linux Virtualbox machine running Docker, but fails because my custom location for Virtualbox machines is not the default.
### Actual behavior
Creating first VM running docker fails and displays log error
### Information about the Issue
http://pastebin.com/aXGtwut7

### Steps to reproduce the behavior
1. Download and execute latest DockerToolbox 1.11.2.exe to a machine that **already** has **VBox 5.24 and Windows Git installed.** and various VBox custom configurations like a different VMs location.
2. Click to execute shortcut "Kitematic (Alpha)
3. Let the setup run until you see the error log posted in the above pastebin

Among various things (I haven't looked further), I can see that the install script expects to find the VM files in an incorrect location.

I would think that this type of thing should be addressed easily but has never been addressed since beginning of this project.... Have not looked for, but I would think that VBox API documentation <should> have a compiled list of API settings that correspond to the various custom settings in VBox Manager, and should then be easily inserted into the existing install command(s).

**Comment by FrenchBen** [comment]
Thank you for the issue report - We now favor using Docker for Mac/Windows when possible. 
Looking through the logs it doesn't seem to be an issue with your custom virtualbox setup, but rather an issue when creating the hostnet interface - Did you not click 'Accept' when prompted to do so in Windows?

`VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter'`
Check Virtualbox directly, it looks like the VM was created but the interfaces weren't.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
