### ISSUE TITLE
Error pulling from docker hub

### ISSUE THREAD

**Issue by JakobEng** [docker/kitematic#1822]
### Overview
I have read many of the people with a problem similar to mine but I could not find anyone who had/have the same.
Usually when people get the **_errors_** I get when runing `docker run hello-world`, they say it is the **_proxy_** or you have **_changed network_**. I don't think I have a proxy, and I have a desktop so I don't like change network often even after restart my mac I still have the problem.

### Errors
I think it is strange that I get different errors but I do, here they are: 

`docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https://auth.docker.io/token?account=jakobeng&scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.65.1:53: no such host.`

`docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c5/c54a2cc56cbb2f04003c1cd4507e118af7c0d340fe7e2720f70976c4b75237dc/data?Expires=1468116651&Signature=DcMG9BizyfFAXvFKBpFfoq2IV3EmRtrg5QuiZXicJzGdTSmECT-U4Hj8MqrZ5vs6VDLDJ2gtJxS6djWBEs3bsAok2L8YFcPO8y7cDgfwdcj3vLXMkxSDyBH3~YuZRcbAyHQjfUzxpoztLusYX99p4WYy2KZsT0pO7yI1Zv~Rl8U_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: no such host.`

`docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c5/c54a2cc56cbb2f04003c1cd4507e118af7c0d340fe7e2720f70976c4b75237dc/data?Expires=1467738345&Signature=Eb~8-GGFBUxS6wE~GNZEOxCrCK5wBaBTkIH18TODSpgUHlpvoVx~W4UrRFAReoQ-LSVIzOZPJiXn4RTKMzKCqhLgAPGgAhU7xOuaBgnrwyccAD9pKMjm0pi879hIbHBWY~-kVNdd7XEaQiQ5ClX4ukKkY~RoXthaQs~-~kTy54k_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: DNS message ID mismatch`

`docker: Tag latest not found in repository docker.io/library/hello-world.`

Sometimes it works though, but more than half the time it don't. 

### Proxy and Dns
When I do to preference > network > Then I login > advanced > proxy and look through every proxy at the left, there is no information about any proxy. I have also talk with a friend and he sad the problem could be something with the DNS server but not what precisely. In preference > network the DNS ip is 192.168.2.1 but grayed out.

### Versions
I use docker 1.12.0-rc3 but had the same problem with version 1.11. I use macOS (as it is called now), version 10.11.5

I glad to give more information about the problem if there is something I have forgot.

Thanks in advance

**Comment by FrenchBen** [comment]
@JakobEng Since this happens also outside of Kitematic, it's more than likely something with docker itself - It seems related to:
https://github.com/docker/docker/issues/18842

**Comment by JakobEng** [comment]
It seems that docker/docker#18842 has something to do with ping, push, and more. I does not really look to be the same I think. My problem is with pulling images from docker hub.

**Comment by FrenchBen** [comment]
The reason I mentioned it, was due to the similarity of DNS issue/errors. 
Do you know if this is still happening?

**Comment by JakobEng** [comment]
What, it works now! Do you know what why changes? I so happy I finally can get to work with Docker. Thanks

**Comment by FrenchBen** [comment]
we've made a lot of changes to the beta (now also available as stable) to handle Proxy more easily. happy to hear it also fixed your issue.
