### ISSUE TITLE
write /var/lib/docker/tmp/GetImageBlob424790207: no space left on device

### ISSUE THREAD

**Issue by yangboz** [docker/kitematic#1825]
### Actual behavior

Any option for resize disk storage?

### Information about the Issue

docker pull cloudier/quickstart it takes 4.44G mega bytes.
### Steps to reproduce the behavior

  1. docker pull cloudier/quickstart
  2.  /var/lib/docker/tmp/GetImageBlob424790207: no space left on device

**Comment by FrenchBen** [comment]
Unfortunately there isn't a 'resize' function. You can always create a bigger VM from the get-go:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
