### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### ISSUE THREAD

**Issue by kedarl-cybage** [docker/kitematic#1826]
### Expected behavior
Docker Calabash-android-cloud9 should get downloaded

### Actual behavior
I get error 
"ETIMEDOUT
connect
192.168.99.100
2376"
And when tried on CLI -
Error: An error occurred trying to connect: Post https://192.168.99.100:2376/v1.21/images/create?fromImage=neofreko%2Fcalabash-android-cloud9%3Alatest: dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Information about the Issue
Docker Calabash-android-cloud9 is not getting downloaded. 

### Steps to reproduce the behavior

  1. Launch Kitematic (Alpha)  
  2. Serach Calabash-android-cloud9
  3. Try to download.

**Comment by FrenchBen** [comment]
@kedarl-cybage Looks like it's related to https://github.com/docker/docker/issues/24344 not kitematic.
