### ISSUE TITLE
can not download cloudera/quickstart

### ISSUE THREAD

**Issue by estheryou** [docker/kitematic#1828]
### Information about the Issue
do not know how to deal with this after pulling completed 50%

500 server error - No command specified
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This works as intended, as the cloudera quickstart indicates in their docs, no command is specified by them:
https://hub.docker.com/r/cloudera/quickstart/

Please open an issue with the image owner.
