### ISSUE TITLE
[win10_hyper-v]Error: connect ETIMEDOUT 120.209.138.64:2375

### ISSUE THREAD

**Issue by lilonghe** [docker/kitematic#1829]
i'm using docker 1.12.0-rc4 and kitematic 0.12, hyper-v, win10

![2016-07-16_220723](https://cloud.githubusercontent.com/assets/12867278/16895220/b0f99ba8-4ba1-11e6-9b2a-08fcdfe95ff2.png)
![2016-07-16_220748](https://cloud.githubusercontent.com/assets/12867278/16895222/c1b352b8-4ba1-11e6-86be-8ed65c8adbe9.png)

**Comment by nokola** [comment]
Similar to mine issue #1029 Docker machine install issues. Does it work for you if you put the machine in airplane mode?

**Comment by lilonghe** [comment]
@nokola thanks, but whay?
whatever start it , i must need in airplane mode  ?

**Comment by nokola** [comment]
I'm not sure - someone suggested to try it out, and it partially worked for me. I'm wondering if you have the same issue

**Comment by FrenchBen** [comment]
there's a bug in the RC4 that is currently being worked on - Closing in favor of:
https://github.com/docker/kitematic/issues/1836
