### ISSUE TITLE
Do not work behind proxy

### ISSUE THREAD

**Issue by deanwong** [docker/kitematic#1834]
### Expected behavior
Can login to docker hub with Kitematic

### Actual behavior
Get error  

> connect ENETUNREACH 104.xx.xx.xx:443

### Information about the Issue
I used the **Docker for Mac Version 1.12.0-rc4-beta19 (build: 10258)**  (not the toolbox or docker-machine), and I configured the Proxy in Docker GUI. I can pull image in command-line with `docker pull xxxx`, but I cannot pull anything with Kitematic.

### Steps to reproduce the behavior

  1. Make sure the mac only can visit website behind proxy
  2. Open Kitematic and try to login or search any images.

**Comment by FrenchBen** [comment]
@deanwong getting kitematic to read the proxy settings is a bit tricky. 
What you can do however is make sure to make your proxy settings globale, by following:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes#make-the-proxy-settings-sticky
Then start Kitematic from the command line.
