### ISSUE TITLE
Kitematic won't start properly

### ISSUE THREAD

**Issue by artuross** [docker/kitematic#1836]
I have just installed Kitematic on my corporate computer and when i start application, it loads for a while and then 
![err1](https://cloud.githubusercontent.com/assets/8393226/16955339/8209dbb6-4dd4-11e6-9610-39fe3e77b8fc.png)

Retrying does not help anyhow, so I clicked Use VirtualBox and this issue occured: 
![err2](https://cloud.githubusercontent.com/assets/8393226/16955484/14cab0a6-4dd5-11e6-9e69-3e4b03e9c432.png)

I figured that maybe proxy is messing here, so I switched to personal hotspot on my phone, reinstalled Kitematic (did it, because while I was using proxy, installer was hanging), but still, issue remains.

Structure of `C:\Users\myacc\.docker\` is as follows (printed by `tree /F /A`):
```
C:.
\---machine
    |   no-error-report
    |
    +---cache
    |       boot2docker.iso
    |
    +---certs
    |       ca-key.pem
    |       ca.pem
    |       cert.pem
    |       key.pem
    |
    \---machines
        \---default
            |   boot2docker.iso
            |   disk.vmdk
            |
            \---default
                \---Logs
                        VBox.log
                        VBoxHardening.log

```

Is this known error? It looks like the installer is not providing all files for some reason.

**Edit:** Provisioning VM with docker-machine produces same error as in 2nd screenshot.

**Comment by FrenchBen** [comment]
@artuross thank you for the report - There is a change in Docker for Windows that breaks the current logic - A fix is being implemented and will reference this issue when merged.

Thanks.

**Comment by FrenchBen** [comment]
@artuross Do you mind giving this freshly baked version a try:
https://drive.google.com/file/d/0Bw5EwLyGjFkQQWFVc1hsRVpac1k/view?usp=sharing

If it works for you I'll go ahead and make it a release. Thanks!

**Comment by lilonghe** [comment]
@FrenchBen  it started ! but can't load anything -_-
![2016-07-21_193820](https://cloud.githubusercontent.com/assets/12867278/17021462/bc4ba4ce-4f7a-11e6-86bc-ce88d369142f.png)

**Comment by artuross** [comment]
Hey, it works for me, at least when I click Use Virtualbox.

![untitled](https://cloud.githubusercontent.com/assets/8393226/17028442/e9032af4-4f67-11e6-99ae-a65a3c8655e9.png)

![untitled](https://cloud.githubusercontent.com/assets/8393226/17028459/f69c2350-4f67-11e6-8190-61c60ff74546.png)

![untitled](https://cloud.githubusercontent.com/assets/8393226/17028496/189c623a-4f68-11e6-93b0-c655330c1e76.png)

Thank you :)

**Comment by FrenchBen** [comment]
@artuross unless you have Docker for Windows, then you'll see the error - I need to figure out a better error message. 

@lilonghe works without issues here and I see all of the data - Are you on Docker for Windows or Virtualbox?

**Comment by GeoffreyEmery** [comment]
Hey @FrenchBen  I did a fresh install of both and i am still getting that same error local.2375. I have opened a ticket for it https://github.com/docker/kitematic/issues/1843

**Comment by FrenchBen** [comment]
@GeoffreyEmery The new release was just created today with the proper fix. 
Thanks for the detailed issue - Let me know if you encounter any other problem
