### ISSUE TITLE
Docker can't pull image

### ISSUE THREAD

**Issue by ZhaoFeiK** [docker/kitematic#1838]
I'm a new docker,  when I execute download `hello-world-nginx`, there is a error say `Error while pulling image: Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp 0.0.8.90:443: connect: invalid argument`

**Comment by FrenchBen** [comment]
Are you using Docker Toolbox? It looks like you're behind a proxy, is that correct?

**Comment by ZhaoFeiK** [comment]
Yes, it's behind a proxy
