### ISSUE TITLE
not download images

### ISSUE THREAD

**Issue by sebasrock** [docker/kitematic#1842]
### Expected behavior

HTTP code is 404 which indicates error: no such image - [object Object]

Tag latest not found in repository docker.io/library/sonarqube

Download images : jhipster:laste and  sonarqube

### Steps to reproduce the behavior

  1. open docker for mac
  2. . docker pull sonarqube

**Comment by FrenchBen** [comment]
If you download the latest Kitematic release from this repository, you will get the proper error. 
Thanks

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
