### ISSUE TITLE
Kitematic Alpha fails to launch after install  - Windows 10

### ISSUE THREAD

**Issue by GeoffreyEmery** [docker/kitematic#1843]
Kitematic fails launch after windows rc install. I had kitematic installed and used it quite often prior to RC install. When I copy the files from the download into the C:\Program Files\Docker\Kitematic as requested from dialog and then relaunch it i get this message. 
![image](https://cloud.githubusercontent.com/assets/3301804/17041079/4eede8e6-4f58-11e6-807f-a46724a5650f.png)

### My system:

![image](https://cloud.githubusercontent.com/assets/3301804/17041244/9a4a26e6-4f59-11e6-9355-2bc707a2486b.png)

![image](https://cloud.githubusercontent.com/assets/3301804/17041243/980b4b4e-4f59-11e6-98e1-f4a20b36ed61.png)

# FEATURE REQUEST: Minor Enhancements.
Clicking on Open Kitematic as seen below from the windows tray icon..
![image](https://cloud.githubusercontent.com/assets/3301804/17040536/2235c718-4f55-11e6-8e27-330032767db3.png)

You get this modul
![image](https://cloud.githubusercontent.com/assets/3301804/17040560/44417d98-4f55-11e6-8bfe-806e628a9e3c.png)

I have kitematic on this machine from pre 1.12 docker. So to the ex is a bit confusing.

## Feature 1:    Update modul for kitematic launch from windows tray.  
Message: Current message is confusing for users . As a user of docker I had kitematic installed so when i saw that and was a bit confusing. If we need to re-install kitematic  no matter what just say that.  
Button: should say close not cancel IMO. 

## Feature 2: Download should link to a page that states its downloading. ###
It took three time before i figured out you were downloading it directly because the new window would open in chrome and then close but if you have a bunch of tabs open your like what happened.

**Comment by rezonant** [comment]
This bug is due to a recent change in Docker, you can work around the issue by adding an entry to your hosts file (%windir%\drivers\etc\hosts) pointing docker.local to your loop back (127.0.0.1):

`127.0.0.1 localhost`

This should work regardless of your hypervisor.

**Comment by GeoffreyEmery** [comment]
yup that did the trick.. your file location is incorrect.. for anyone else running into this ...
easiest way to do this is to right click on notepad and run as administrator... 
![image](https://cloud.githubusercontent.com/assets/3301804/17080226/17d1fb6a-50dc-11e6-8f07-b8fc2f4976a1.png)
then file > Open > enter
c:\windows\system32\drivers\etc\hosts
Press enter you can now edit the host file
add to the file this line. 
127.0.0.1 docker.local
Save> re-open kitematic.

**Comment by CsCdanNyx** [comment]
I had a similar issue, but thanks to @GeoffreyEmery, the problem was fixed.

The issue was:
I used Docker for windows 10 and followed the same instruction to download Kitematic-Windows. 
Then I opened the Kitematic, an Error showed up:
![13833535_1138765466197723_772712461_o](https://cloud.githubusercontent.com/assets/10433505/17082108/90615256-51a4-11e6-922c-2fda08a0bef0.png)

**Comment by friism** [comment]
I suspect https://github.com/docker/kitematic/pull/1839 has the fix

**Comment by FrenchBen** [comment]
Correct this has been fixed - Please check the latest release here:
https://github.com/docker/kitematic/releases/tag/v0.12.1
