### ISSUE TITLE
Download images without starting a container

### ISSUE THREAD

**Issue by Sh4kE** [docker/kitematic#1849]
Currently when downloading an image it automatically starts a new container, which is I think already wrong. Sometimes you want to change some environment variables or volumes to local directories before starting a new container.

In my case my default CMD command runs a dbinit and dbmigrate, which creates a new database file. With the default volume it does it in a newly created volume. But I need to be able to change it to a local directory before running the dbinit command.

If it is possible to download images without starting it, then one could simply add an update button or something to update the images to the latest tag, as well :)

**Comment by FrenchBen** [comment]
There's already a proposal in progress for that, see:
https://github.com/docker/kitematic/issues/1260
