### ISSUE TITLE
Docker Image (openproject

### ISSUE THREAD

**Issue by Rahali** [docker/kitematic#1851]
### Actual behavior
I can't get openproject image : 
open /mnt/sda1/var/lib/docker/tmp/GetImageBlob173979945: read-only file system
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please provide more information on how to reproduce this error.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
