### ISSUE TITLE
Was not found the rabbitmq image

### ISSUE THREAD

**Issue by pablobastidasv** [docker/kitematic#1852]
### Expected behavior
The pull download correctly the image that I saw in hub.docker.com

### Actual behavior
The system show me the message "Tag latest not found in repository docker.io/library/rabbitmq"

### Steps to reproduce the behavior

  1. Start docker beta on my mac
  2. Open Kitematic
  3. Search rabbitmq
  4. Click on create

**Comment by FrenchBen** [comment]
Looks like RabbitMQ forgot to create a `latest` tag. 
See:
https://hub.docker.com/r/library/rabbitmq/tags/

I'd open an issue with them.
