### ISSUE TITLE
Caused by: com.spotify.docker.client.DockerException: Get https://registry-1.docker.io/v1/repositories/library/java/tags/8: dial tcp 52.3.178.145:443: i/o timeout  at com.spotify.docker.client.AnsiProgressHandler.progress(AnsiProgressHa

### ISSUE THREAD

**Issue by sagarsdeulkar** [docker/kitematic#1854]
### Expected behavior
Java Image should get downloaded
Jenkin Image get downloaded.
### Actual behavior
Error 
TTP code is 500 which indicates error: server error - Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: Get https://auth.docker.io/token?account=synbaas&scope=repository%3Alibrary%2Fjenkins%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Information about the Issue
No image is getting downloading from docker hub, neither from docker hub through kitematic nor from through DockerFile.

### Steps to reproduce the behavior

  1. Login to kitematic
  2. try to download any image
  3. It will result to above error.

**Comment by FrenchBen** [comment]
Timeout usually means that your connection to the server was lost. I would re-try on a solid network connection.

**Comment by sagarsdeulkar** [comment]
I guess some maintenance activity was going on aws side as it was failing with below error & 52.3.178.145 IP belonging to 52.3.178 - amazonaws.com.

Failed to execute goal com.spotify:docker-maven-plugin:0.2.3:build (defa
ult-cli) on project eureka: Exception caught: Get https://registry-1.docker.io/v1/repositories/library/java/tags/8: dial tcp 52.3.178.145:443: i/o timeout ->

For more details please refer link,
https://forums.docker.com/t/pulling-docker-images-i-o-timeout/740/13
