### ISSUE TITLE
Error docker pull sciensa/weblogic-osb

### ISSUE THREAD

**Issue by CibercorpSystemsLtda** [docker/kitematic#1855]
### Expected behavior
Install OSB
### Actual behavior
Don't Install
### Information about the Issue
write /mnt/sda1/var/lib/docker/tmp/GetImageBlob365327721: no space left on device

### Steps to reproduce the behavior

  1. only docker pull sciensa/weblogic-osb
  2. help

**Comment by FrenchBen** [comment]
Is your VM out of space?
See: https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
