### ISSUE TITLE
Can't build a jenkins container

### ISSUE THREAD

**Issue by eldermoraes** [docker/kitematic#1856]
### Expected behavior
Simply build a jenkins container.

### Actual behavior
failed to register layer: rename /mnt/sda1/var/lib/docker/image/aufs/layerdb/tmp/layer-619456010 /mnt/sda1/var/lib/docker/image/aufs/layerdb/sha256/49108e62eaacf69f2c803cfee2aad793ff52272316bf22114a8bd7f35fdc318c: directory not empty

### Information about the Issue
The log above.

### Steps to reproduce the behavior

  1. Select the jenkins image
  2. Click create
  3. Boom...

**Comment by FrenchBen** [comment]
Somehow this was missed - Could you provide exact steps to reproduce this. On a fresh install of Kitematic+Docker for Mac I'm unable to replicate

**Comment by eldermoraes** [comment]
Can't do it anymore. I have erased the machine and started a new one. Everything is fine now.

Looked like something happened in the previous download and corrupted some file. But I could not figure out which one...

Thanks!

**Comment by FrenchBen** [comment]
thanks for the response - Closing for now but feel free to comment as needed.
