### ISSUE TITLE
error while downloading container in kitematic

### ISSUE THREAD

**Issue by adliazaddin** [docker/kitematic#1857]
### Expected behavior
docker image will be download
### Actual behavior
received error network timed out
### Information about the Issue
im not behind proxy, 

### Steps to reproduce the behavior

  1. launch kitematic
  2. click create on any docker image available
  3. and the message appear

**Comment by FrenchBen** [comment]
Is this on Docker Toolbox? Some large images require a stable connection.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
