### ISSUE TITLE
open /mnt/sda1/var/lib/docker/tmp/GetImageBlob389795205: no such file or directory

### ISSUE THREAD

**Issue by yangboz** [docker/kitematic#1858]
### Information about the Issue

open /mnt/sda1/var/lib/docker/tmp/GetImageBlob389795205: no such file or directory

### Steps to reproduce the behavior

  1. Search ELK:lastest
  2. Downloading...

**Comment by FrenchBen** [comment]
Can you open a terminal and provide us with the output of:
```
docker version
```

**Comment by yangboz** [comment]
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by FrenchBen** [comment]
Could've been a temporary issue - It looks like you're using the Docker Toolbox. 
I would recommend using the native [Docker for Mac](https://www.docker.com/products/docker#/mac), as it may solve a lot of the vbox issues you are facing.
