### ISSUE TITLE
Add 'Retry' button to connection errors

### ISSUE THREAD

**Issue by amingilani** [docker/kitematic#1861]
<img width="669" alt="screen shot 2016-07-29 at 9 14 59 am" src="https://cloud.githubusercontent.com/assets/1188552/17237605/2f2f16fe-556d-11e6-9b6c-15f7b2cd07d4.png">

### Expected behavior

A Retry link with "File an Issue"

### Actual behavior

Just File an issue.

### Information about the Issue

I closed my laptop in the middle of a connection, then I didn't know what to do.

**Comment by FrenchBen** [comment]
There is no resume - when you close your laptop the connection is cut and this will need to be re-tried with a proper connection.

**Comment by amingilani** [comment]
That's what I meant, I had to quit and restart docker because there was nothing similar to "try again" on the screen.

**Comment by amingilani** [comment]
*Retry*, as the title says, not "resume"

**Comment by FrenchBen** [comment]
You don't have to quit and restart docker - You can simply click on the image again to create it.
