### ISSUE TITLE
Downloadable zip of 0.10.5 is incorrect

### ISSUE THREAD

**Issue by unixben** [docker/kitematic#1862]
### Expected behaviour
File downloaded should contain that version for which it is named. 

### Actual behaviour
Version of file downloaded is 0.10.4, not 0.10.5.

### Information about the Issue
For example, downloading https://github.com/docker/kitematic/releases/download/v0.10.5/Kitematic-0.10.5-Mac.zip does not contain version 0.10.5 (it contains 0.10.4).

### Steps to reproduce the behaviour

  1. Download https://github.com/docker/kitematic/releases/download/v0.10.5/Kitematic-0.10.5-Mac.zip
  2. Unzip.
  3. Get info on "Kitematic (Beta).app" and check version. It is 0.10.4, not 0.10.5.

**Comment by FrenchBen** [comment]
@unixben with `0.12.0` being the latest release, this is not a valid issue.
