### ISSUE TITLE
error pull image sonarqube

### ISSUE THREAD

**Issue by sebasrock** [docker/kitematic#1864]
### Expected behavior
Download images
### Information about the Issue

HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/library/sonarqube/manifests/latest: Get https://auth.docker.io/token?account=ssanchezbassan\u0026scope=repository%3Alibrary%2Fsonarqube%3Apull\u0026service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
### Steps to reproduce the behavior

  1. intro to kitematic
  2. download image sonarqube

**Comment by FrenchBen** [comment]
I'm not having the same issue and able to download the image without any issue. 
Can you try again?
