### ISSUE TITLE
Docker CLI button in Kitematic

### ISSUE THREAD

**Issue by drubarth** [docker/kitematic#1869]
### Expected behavior
Open terminal normally.

### Actual behavior
Displays the following error message.
Unable to find any JVMs matching version "1.6*".

### Information about the Issue
I had been running an earlier version of Docker on my Mac and then uninstalled that version and installed Docker for Mac and Kitematic.
I'm running Kitematic 0.12.0 and Docker for Mac 1.12.0 beta 1
I'm also running Java version 8, update 101, which appears to be the recommended current version for OS X.

### Steps to reproduce the behavior

  1. Click on Docker CLI button in Kitematic

**Comment by FrenchBen** [comment]
It sounds like some env variables or startup scripts are causing this. JVM isn't a dependency of Kitematic and thus unrelated. 
I would look at the shell startup scripts and see which one is causing this.

**Comment by drubarth** [comment]
Thanks so much. Found the issue and fixed it. 

Darryl 

www.LabAnalytix.com 

775-996-5775 

----- Original Message -----

**Comment by FrenchBen** [comment]
@drubarth Do you mind sharing your findings so that others with the same issue can fix it as well?

**Comment by drubarth** [comment]
The following line was in my .bashrc file. 

export JAVA_HOME=`/usr/libexec/java_home -v '1.6*'` 

As I recall I had set this up several years ago when I was on a prior version of OS X and needed to run some application with Java 1.6. 

thanks, 

Darryl 

----- Original Message -----
