### ISSUE TITLE
Cannot connect to docker hub using kitematic in windows 10

### ISSUE THREAD

**Issue by anggun-indra** [docker/kitematic#1870]
when trying to install image from dockerhub always return i/o timeout.
i already check my network and find nothing problem
so please help :D

sorry for my bad english

**Comment by FrenchBen** [comment]
Can you make sure that you have a stable internet before downloading the image.

**Comment by anggun-indra** [comment]
i think that is because my office firewall policy , docker using cloadflare , i will check using other internet connection
Almost frustating stuck on this issue :D

**Comment by FrenchBen** [comment]
@anggun-indra sorry to hear that your office makes this less than ideal to work with.
If it's possible you should download [Docker for Windows](https://www.docker.com/products/docker#/windows)
