### ISSUE TITLE
Tag latest not found in repository docker.io/casadocker/alpine-wildfly-postgresql

### ISSUE THREAD

**Issue by dkhedekar** [docker/kitematic#1873]
### Expected behavior
Tag found
### Actual behavior
Tag latest not found in repository docker.io/casadocker/alpine-wildfly-postgresql
### Information about the Issue
Tag latest not found in repository docker.io/casadocker/alpine-wildfly-postgresql

### Steps to reproduce the behavior

  1. User Kinematic
  2. search for alpine postgres wildfly

**Comment by FrenchBen** [comment]
Works as expected - There are no tags 'latest' defined for that image. See the Hub link:
https://hub.docker.com/r/casadocker/alpine-wildfly-postgresql/tags/
