### ISSUE TITLE
Image size for own images

### ISSUE THREAD

**Issue by lferro9000** [docker/kitematic#1881]
### Expected behavior
When navigating on the UI, i was expecting to see the size of my images.

### Actual behavior
The size is not shown on my own images, only on the repository / official ones.

### Information about the Issue
Just UI thing.

### Steps to reproduce the behavior

  1. Create an image by using docker from command line
  2. Open Kitematic and go to All
  3. Images show a down-arrow with image size
  4. go to My images
  5. Images don't show the size in a similar way.

**Comment by FrenchBen** [comment]
@lferro9000 The `down-arrow with image size` is actually inaccurate. 
The `down-arrow` actually represents the amount of downloads for an image. 
if you look at Redis on the `All` tab of kitematic, you'll see that those numbers match what's on hub's explore page:
https://hub.docker.com/explore/
