### ISSUE TITLE
When Docker is installed but not running, Kitematic takes too long to start

### ISSUE THREAD

**Issue by dluc** [docker/kitematic#1885]
### Expected behavior
Given that Docker is installed
And Virtualbox is installed
And Docker is turned off
When Kitematic is launched
Then Kitematic prompts whether to use Virtualbox or Docker
Or Kitematic uses Virtualbox automatically
And the whole process is fast!

### Actual behavior
[...]
Then Kitematic tries to connect to Docker
And times out with an error
And asks the user whether to use Virtualbox
And the whole thing takes too long!

### Information about the Issue
Platform: OSX (10.11). Docker is installed but not running. Virtualbox is installed.

### Steps to reproduce the behavior

  1. Install Docker, and turn it off
  2. Install Virtualbox
  3. Install Kitematic
  4. Launch Kitematic

**Comment by FrenchBen** [comment]
Unfortunately we need a small time-out to make sure that the request to the native docker is actually not working and not just slow to respond.
In the following PR: https://github.com/docker/kitematic/pull/1878 we added support for a preference panel to save the preferred docker engine (native or virtualbox).
I'll see if we can reduce the time-out to speed this up. 

Thanks for the great issue detail

**Comment by dluc** [comment]
The preference panel is nice, perhaps instead of selecting which one to use, you could allow the user to define the order, e.g. "probe VirtualBox first, then Docker" or viceversa.
