### ISSUE TITLE
Tag latest not found in repository docker.io/divio/django-cms-demo

### ISSUE THREAD

**Issue by jegesh** [docker/kitematic#1890]
Got this error trying to run the image with kitematic

**Comment by FrenchBen** [comment]
The latest tag is there and I'm able to pull it manually - What do you get when you run:
```
docker pull divio/django-cms-demo
```

**Comment by jegesh** [comment]
Yeah, it ended up being some kind of connectivity issue - I was getting error messages for any image I tried to pull with kitematic.
