### ISSUE TITLE
"MAC IP:PORT" is confusing

### ISSUE THREAD

**Issue by garethflowers** [docker/kitematic#1894]
Within the "Ports" section of settings the published IP and Port are listed under the "MAC IP:PORT" heading - is there a reason for this? It can be confusing for Windows and Linux users.

Would it not make more sense to have the heading shown as "PUBLISHED IP:PORT", or something similar?

**Comment by FrenchBen** [comment]
MAC stands for Media Access Control - not the OSX Mac :)
https://en.wikipedia.org/wiki/Media_access_control

However, I'm not opposed to the wording change.
