### ISSUE TITLE
Containers started in virtualbox through command line is not displayed in Kitematic

### ISSUE THREAD

**Issue by ainderkkumar** [docker/kitematic#1898]
Expected behaviour: Containers started in virtualbox through command line must be displayed in Kitematic

Actual behaviour: Containers started in virtualbox through command line is not displayed in Kitematic

### Steps to reproduce the behavior:

  1. Start some containers through command line. Use 'docker ps -a' to verify the containers created
  2. Open Kitematic and see if the containers are listed in the left hand side of the Kitematic UI

**Comment by FrenchBen** [comment]
This behavior works for me just about every time. It could be that you're on a different virtualbox than the one used by kitematic?
Either way I can not reproduce this reliably - We did add a 'Refresh Container List' option to the view; if this happens again, you can refresh the list, which usually fixes this.

**Comment by ainderkkumar** [comment]
I observed that only containers running on default machine in Virtual box is listed in Kitematic Container List. Is there any settings which should be done to list all the containers running in all the VMs in the same Virtual box.
**Note:** I'm using **only one Virtual Box** with multiple VMs running inside the same.

**Comment by FrenchBen** [comment]
Kitematic only supports 1 VM labelled default.
