### ISSUE TITLE
MacOSX (El Capitan) : Black screen when Kitematic in full screen is closed

### ISSUE THREAD

**Issue by antyriad** [docker/kitematic#1899]
With Kitematic (Beta) 0.12.0 (Electron 0.35.4)

### Expected behavior
No full black screen when closed

### Actual behavior
Full black screen when closed

### Steps to reproduce the behavior

  1. Launch Kitematic
  2. Set it in full screen by clicking on green button on top-left
  3. Close it by clicking on red button on top-left

Screen is all black !!!

**Comment by FrenchBen** [comment]
We're currently revamping the functionality behind full-screen and those buttons. Closing for now as the PR https://github.com/docker/kitematic/pull/1559 should fix this. 
thanks
