### ISSUE TITLE
Pictures/logos broken on new container window

### ISSUE THREAD

**Issue by bbodenmiller** [docker/kitematic#1902]
### Expected behavior

I expect pictures/logos for images to show on new container window

### Actual behavior

Broken image pictures occur rather than pictures/logos
![image](https://cloud.githubusercontent.com/assets/1192780/17681644/cf3663fa-62fb-11e6-8b43-0652549df25d.png)

### Information about the Issue

I'm on a corporate network with a proxy and I suspect that may have something to do with this. I'm able to download Docker images without any problems.

**Comment by FrenchBen** [comment]
Could you try to setup Kitematic to work behind a proxy and see if this helps?
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by bbodenmiller** [comment]
Interestingly now it is working even though I didn't change anything yet.
