### ISSUE TITLE
Kitematic won't start

### ISSUE THREAD

**Issue by bbodenmiller** [docker/kitematic#1903]
### Expected behavior

I expect Kitematic to easily start

### Actual behavior

I receive the error:

`Error: connect ENOENT //./pipe/docker_engine`

![image](https://cloud.githubusercontent.com/assets/1192780/17684476/df4d02a2-6310-11e6-8f3a-983c998398a0.png)

### Information about the Issue

I'm on a corporate network which requires a proxy to get outside the network. I suspect this is likely causing troubles with Kitematic. I also cannot get Docker Toolkit to run `docker run hello-world` or `docker ps` however it returns no other error messages and is able to ping and SSH the Docker machine (`192.168.99.100`).

If I select the "USE VIRTUALBOX" button and then select "DOCKER CLI" I can run `docker run hello-world` in the PowerShell window that opens.

**Comment by bbodenmiller** [comment]
I was able to fix Docker Toolbox by running `docker-machine env --no-proxy`... how can I get Kitematic to do that? I also had to unset the `ALL_PROXY` environment variable as go returns an error if it is not a socks address (see https://github.com/golang/go/issues/16715 & https://github.com/docker/docker/issues/25740).

**Comment by FrenchBen** [comment]
Please see our wiki for proxy setup:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by bbodenmiller** [comment]
`for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i` returns `%%i was was unexpected at this time`

/cc @FogDev

**Comment by ZetaoYang** [comment]
The problem has solved. Please see [#1992](https://github.com/docker/kitematic/issues/1992).

**Comment by megamindbrian** [comment]
@ZetaoYang this is not solved.
