### ISSUE TITLE
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images. You may want to check your internet connection or if you are behind a proxy.

### ISSUE THREAD

**Issue by mumataotao** [docker/kitematic#1904]
### Actual behavior
webbrowser can load the https url，bug kitematic couldn't
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by adius** [comment]
I have the same issue with https://index.docker.io/v1/repositories/library/php/images

**Comment by FrenchBen** [comment]
I'm able to download all images without any issue - Can you try to download the image from the CLI and see what you get?

**Comment by emory** [comment]
Possibly related — I have the same error and I'm dual-stacked on my office and home workstations v4/v6. Disabling my ipv6 interface appears to fix it. Because…

```
❯ host index.docker.io
index.docker.io is an alias for elb-io.us-east-1.aws.dckr.io.
elb-io.us-east-1.aws.dckr.io is an alias for us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com.
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com has address 52.73.159.23
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com has address 54.85.12.131
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com has address 52.207.178.113

~
❯ host -t aaaa index.docker.io
index.docker.io is an alias for elb-io.us-east-1.aws.dckr.io.
elb-io.us-east-1.aws.dckr.io is an alias for us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com.

~
❯ host -t aaaa us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com.
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com has no AAAA record
```

**Comment by FrenchBen** [comment]
@emory Thank you for the help - IPv6 isn't currently supported and why you're seeing this error. 
I've opened a ticket internally to see if this is something we could add support for in the future.
