### ISSUE TITLE
Application cannot be opened

### ISSUE THREAD

**Issue by aarongundel** [docker/kitematic#1905]
### Expected behavior

Expecting that Kitematic will open when I click on it in "Applications". 

### Actual behavior

It doesn't open and gives me the error "The application Kitematic (Beta) can't be opened."

### Information about the Issue

If I try to open from the applications menu, I get the error above.  If I try to open from Docker, I see Kitematic needs to be updated from 0.10.0 to 0.10.4.  I've followed the instructions -- downloaded and placed 0.10.4 in the Applications folder.  It doesn't work, and I still get the "needs to be updated" message.  This makes me think that there's some kind of pathing issue within the docker client; but I don't know where its actually looking for Kitematic.

### Client Info

Kitematic 0.10.4
Docker for Mac 1.12.0-a
OSX El Capitan (10.11.6)

**Comment by pmario** [comment]
you should probably use the latest one. https://github.com/docker/kitematic/releases

**Comment by aarongundel** [comment]
Welp, that was it.  Thanks!
