### ISSUE TITLE
Error installing mongo image

### ISSUE THREAD

**Issue by Baccanno** [docker/kitematic#1907]
### Expected behavior
Install Mongo image

### Actual behavior
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/library/mongo/manifests/latest: x509: certificate is valid for www.parkingcrew.com, not registry-1.docker.io"}

### Steps to reproduce the behavior

![image](https://cloud.githubusercontent.com/assets/3664080/17731147/540e1ad4-646c-11e6-835a-65329c229b7f.png)

**Comment by Fahrradflucht** [comment]
Is this still happening?

Is this happening if you it this URI in your browser?

**Comment by FrenchBen** [comment]
@Baccanno it sounds like you're behind a proxy that changes the certificate. 
Please see our wiki to setup your environment for this:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
