### ISSUE TITLE
Need connection to different container registries

### ISSUE THREAD

**Issue by Jaff** [docker/kitematic#1909]
### Expected behavior
Kitematic allows configuration and pulling from a variety of Docker container repositories 

### Actual behavior
Kitematic allows configuration and pulling ONLY from DockerHub repository 

### Information about the Issue
We push our containers to quay.io

**Comment by FrenchBen** [comment]
@Jaff We would need to build-in the authentication functionality of quay.io (or other registry)
We aim to support Docker Hub as best as we can and rely on the community to help build other registries. Feel free to write a plugin-like add-on for Kitematic to support quay.io
