### ISSUE TITLE
Running very slowly

### ISSUE THREAD

**Issue by TelWoolsey** [docker/kitematic#1910]
### Expected behavior
To run faster
### Actual behavior
Running very slowly
### Information about the Issue
Kitematic is running super slowly for me.  It loads fine but when I try to open the CLI it takes about a minute to finally open and when I'm working in the environment every time I click anything it takes a good 20-30 seconds to load a new page.

### Steps to reproduce the behavior
Didn't do anything. Though I have tried uninstalling and reinstalling and still have the problem.
  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Can you provide specs of your machine?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
