### ISSUE TITLE
Everything I did is gone....

### ISSUE THREAD

**Issue by TelWoolsey** [docker/kitematic#1911]
### Expected behavior
To still have all my changes when I restarted Kitematic
### Actual behavior
All of my changes are gone!
### Information about the Issue
I'm running Drupal and every time I create new content, close down the machine and start it back up, everything I did is gone!  The pages I created are gone, the theme I set up is gone, all of it.

### Steps to reproduce the behavior
Turn off Kitematic and start it up again.
  1. ...
  2. ...

**Comment by FrenchBen** [comment]
I think you're under the false impression that a container is a VM. You should not be making your changes to a container, unless you remember to commit those changes to an image once you're done.
https://docs.docker.com/engine/reference/commandline/commit/
