### ISSUE TITLE
not able to pull images with the windows docker stable

### ISSUE THREAD

**Issue by sujithemmanuel** [docker/kitematic#1913]
### Expected behavior
Clicking create should create the image. Used to work perfectly with docker toolkit
### Actual behavior
Gives a network timeout saying something about proxy
### Information about the Issue
Network timed out while trying to connect to https://index.docker.io/v1/repositories/owasp/zap2docker-stable/images. You may want to check your internet connection or if you are behind a proxy.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
If you're behind a proxy you would need to follow our wiki to https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
