### ISSUE TITLE
Can't pull the microsoft/iis image - "unknown blob"

### ISSUE THREAD

**Issue by rpipkin** [docker/kitematic#1917]
### Expected behavior
Can download the full microsoft/iis image.
### Actual behavior
Can't pull the microsoft/iis image - "unknown blob"

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pmario** [comment]
have a look at: https://hub.docker.com/r/microsoft/iis/ it states: 

>Internet Information Services (IIS) installed in a Windows Server Core based container

So it is a windows container, that needs a windows backend. https://msdn.microsoft.com/en-us/virtualization/windowscontainers/containers_welcome

I'm not sure, if kitematic can handle this combination atm.

**Comment by FrenchBen** [comment]
@pmario is correct. This isn't related to kitematic.
