### ISSUE TITLE
Can't create a container due to no space left on device error

### ISSUE THREAD

**Issue by kskoeld** [docker/kitematic#1920]
### Expected behavior
Creation of new container

### Actual behavior
getting the following error message
write /mnt/sda1/var/lib/docker/tmp/GetImageBlob870420129: no space left on device
### Information about the Issue
Checked disk space (97GB available) available memory (8GB available)
When trying to create the a container based on
https://hub.docker.com/r/soasta/dswb-kitematic/

### Steps to reproduce the behavior

  1. Open kitematic
  2. Click create button
  3. look for dswb-kitematic container
 4. watch the percentage downloading go up
 5. error occurs

**Comment by pmario** [comment]
did you check your free hd space on the host, or inside the VM?
do you use kitematic with  "docker for windows/mac" or DockerToolbox with VirtualBox?

**Comment by FrenchBen** [comment]
Please see the wiki on how to solve this:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
