### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by Denys-Bushulyak** [docker/kitematic#1921]
### Expected behavior
Download Mongo image
### Actual behavior
error pulling image configuration: Get https://registry-1.docker.io/v2/library/mongo/blobs/sha256:af52553e1c34b3ec48a2e50cf73a1eed1fc6d2fd2b0d3d73d7397c8d6341551f: net/http: TLS handshake timeout
### Information about the Issue
error pulling image configuration: Get https://registry-1.docker.io/v2/library/mongo/blobs/sha256:af52553e1c34b3ec48a2e50cf73a1eed1fc6d2fd2b0d3d73d7397c8d6341551f: net/http: TLS handshake timeout

### Steps to reproduce the behavior

  1. Open Kinematic
  2. Select official mongodb image to download
<img width="845" alt="2016-08-20 12 36 40" src="https://cloud.githubusercontent.com/assets/6935209/17830400/cc6d8862-66d2-11e6-82d1-fb558d0b2e54.png">

**Comment by FrenchBen** [comment]
Are you perhaps behind a proxy?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
