### ISSUE TITLE
UI: Selected container at list looks like halted.

### ISSUE THREAD

**Issue by Denys-Bushulyak** [docker/kitematic#1922]
### Expected behavior
See container state even when focus on container
### Actual behavior
Green icon looks muted, than is why I have to change focus between containers to see current state: green or gray.

**Comment by FrenchBen** [comment]
Not sure what you're referring to - Only the current/active container will have the green icon

**Comment by Denys-Bushulyak** [comment]
Yes, now I see. I talking about left-side list containers' list. It would be great to see it more clear. When you select container which already live it's icon will be inverse-white on gray background. And only indicator on up of app showing true status.

**Comment by FrenchBen** [comment]
I'm open to suggestion - Feel free to mock up what it would look like
