### ISSUE TITLE
network error window

### ISSUE THREAD

**Issue by feichangshun** [docker/kitematic#1927]
### Steps to reproduce the behavior

  1. ...Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/mysql/images. You may want to check your internet connection or if you are behind a proxy.
  2. ...

**Comment by Fahrradflucht** [comment]
Duplicate of #1904

**Comment by FrenchBen** [comment]
thanks @Fahrradflucht for the help!
@feichangshun since you're in Beijing I'm guessing you are behind a proxy and thus need to do the following:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
