### ISSUE TITLE
Move wiki to docs

### ISSUE THREAD

**Issue by bbodenmiller** [docker/kitematic#1928]
### Expected behavior

I expect all docs I need to run Kitematic to be at http://kitematic.com/docs (https://github.com/docker/kitematic/tree/master/docs)

### Actual behavior

Some important documentation such as how to use with a proxy is located at https://github.com/docker/kitematic/wiki

**Comment by FrenchBen** [comment]
The wiki serves more as a guide for quick help on common issues with Virtualbox - As people are moving to a native setup (Docker for Mac/Windows), the solutions provided in the wiki are less likely to be used.

With the above said, we accept all PR against our docs :)
