### ISSUE TITLE
Cleanup the Issue Tracker

### ISSUE THREAD

**Issue by Fahrradflucht** [docker/kitematic#1929]
I noticed that Kitematic has a lot of open issues. (At the time of this writing 195) While going through some of them I noticed that a lot of them aren't actionable, because the reporter didn't provide enough detail and never got back on requests for additional information. To make this issue tracker more useful I would suggest closing most of them and let the reporter re-open them if there is still a problem.

Here is a list with issues worth looking at:

#285
#809
#1336
#1390
#1398
#1436
#1409
#1464
#1593
#1600
#1639
#1652
#1655
#1673
#1675 - I don't speak French though ;)
#1678
#1727
#1747 - Nice, but not an issue I guess
#1790
#1792
#1807
#1808
#1818
#1842
#1851
#1856 - Boom!
#1857
#1861
#1889
#1892
#1904
#1910
#1921
#1927

In addition to that, there are feature request that either seem solved or are thrown together in one issue:

#207
#252
#450
#1521
#1719 - @FrenchBen Is this fixed?

Then there are issues that seem to be legit but VirtualBox related and pre-Docker for Mac/Docker for Windows and are maybe worth looking at, too:

#258
#267
#292
#314
#549
#638
#673
#1103
#1029
#979
#1886 - This isn't pre but still...

#1463
#1539

Sidenote: Are this all duplicates of one another?
#210, #308, #769

#231, #777, #1714

I also noticed that there are a bunch of issues regarding network issues that sound like either normal network hiccups or proxy issues. It might be worth consolidating the issue template to encourage the reporters to first try the command line and check their proxy settings.

As you might guess this was a task where you easily get confused. Sorry if I classified an issue wrong or missed one.

**Comment by Fahrradflucht** [comment]
Okay know that a read [this issue](https://github.com/docker/toolbox/issues/535) on docker toolbox I have another perspective on the timeline for ditching VirtualBox. Maybe one should exclude my list of issues related to this for know.

**Comment by FrenchBen** [comment]
@Fahrradflucht thank you for going through all of this - There's definitely a good amount of issues that should be closed, especially since the users don't provide enough details for us to help. 
I'll go through the list tomorrow and will close them out.

thanks again for the help!

**Comment by Fahrradflucht** [comment]
While this is obviously an ongoing issue, I will close this since it looks like you went through all of them. 🙂

Down to 145 in 4 days is not bad 😉 !

**Comment by FrenchBen** [comment]
All thanks to you for tracking down the ones that could easily be closed :D
