### ISSUE TITLE
SETUP ERROR: Could not determine IP from docker-machine.

### ISSUE THREAD

**Issue by karneaud** [docker/kitematic#1940]
### Expected behaviour
Should setup and connect docker default container
### Actual behaviour
throws subject error
### Information about the Issue
I tried setup docker at a directory outside of my ~/.docker using the MACHINE_STORAGE_PATH env and while the files/ folders were able to install I got this [log error ](http://pastebin.com/xfERFtdh) so I went in and adjusted the permissions and tried to **"RETRY SETUP"** this time though I got the subject error.

### Steps to reproduce the behavior

  1. set env MACHINE_STOREAGE_PATH and DOCKER_CERT_PATH to a network drive on another machine
  2. run kitematic
  3. adjust the id_rsa permissions
  4. RETRY SETUP

**Comment by FrenchBen** [comment]
Make sure that you tried this with the latest release:
https://github.com/docker/kitematic/releases/tag/v0.12.0

Previous versions didn't respect the machine path provided.

**Comment by karneaud** [comment]
I am using the latest version 0.12.0

**Comment by FrenchBen** [comment]
I've tested 3 different machine storage path and haven't had any issues. You need to provide more details of your setup, what you're doing and permissions set. 
A lot of things are being touched and modified, which makes it difficult to troubleshoot.

**Comment by karneaud** [comment]
I'm running  OSX Yosemite 
I'm trying to install to a shared folder over a Network

**Comment by karneaud** [comment]
`docker-machine inspect`

> {
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "",
        "MachineName": "default",
        "SSHUser": "docker",
        "SSHPort": 0,
        "SSHKeyPath": "",
        "StorePath": "/Volumes/NASMAC/VMs/.docker",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "VBoxManager": {},
        "HostInterfaces": {},
        "CPU": 1,
        "Memory": 2048,
        "DiskSize": 20000,
        "NatNicType": "82540EM",
        "Boot2DockerURL": "",
        "Boot2DockerImportVM": "",
        "HostDNSResolver": false,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HostOnlyNicType": "82540EM",
        "HostOnlyPromiscMode": "deny",
        "UIType": "headless",
        "NoShare": false,
        "DNSProxy": true,
        "NoVTXCheck": false
    },
    "DriverName": "virtualbox",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [],
            "Ipv6": false,
            "InsecureRegistry": [],
            "Labels": [],
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": true,
            "RegistryMirror": [],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Agent": false,
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Image": "swarm:latest",
            "Strategy": "spread",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": [],
            "ArbitraryJoinFlags": [],
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "/Volumes/NASMAC/VMs/.docker/certs",
            "CaCertPath": "/Volumes/NASMAC/VMs/.docker/certs/ca.pem",
            "CaPrivateKeyPath": "/Volumes/NASMAC/VMs/.docker/certs/ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/Volumes/NASMAC/VMs/.docker/machines/default/server.pem",
            "ServerKeyPath": "/Volumes/NASMAC/VMs/.docker/machines/default/server-key.pem",
            "ClientKeyPath": "/Volumes/NASMAC/VMs/.docker/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "/Volumes/NASMAC/VMs/.docker/certs/cert.pem",
            "ServerCertSANs": [],
            "StorePath": "/Volumes/NASMAC/VMs/.docker/machines/default"
        }
    },
    "Name": "default"
}

**Comment by karneaud** [comment]
`docker -D ip default`

> Docker Machine Version:  0.8.0, build b85aac1
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:57677
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
command=ip machine=default
(default) Calling .GetIP
(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | name="default"
(default) DBG | groups="/"
(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(default) DBG | UUID="bd23bada-e4d3-465e-a81f-f540b361da8a"
(default) DBG | CfgFile="/Volumes/NASMAC/VMs/.docker/machines/default/default/default.vbox"
(default) DBG | SnapFldr="/Volumes/NASMAC/VMs/.docker/machines/default/default/Snapshots"
(default) DBG | LogFldr="/Volumes/NASMAC/VMs/.docker/machines/default/default/Logs"
(default) DBG | hardwareuuid="bd23bada-e4d3-465e-a81f-f540b361da8a"
(default) DBG | memory=2048
(default) DBG | pagefusion="off"
(default) DBG | vram=8
(default) DBG | cpuexecutioncap=100
(default) DBG | hpet="on"
(default) DBG | chipset="piix3"
(default) DBG | firmware="BIOS"
(default) DBG | cpus=1
(default) DBG | pae="on"
(default) DBG | longmode="on"
(default) DBG | cpuid-portability-level=0
(default) DBG | bootmenu="disabled"
(default) DBG | boot1="dvd"
(default) DBG | boot2="dvd"
(default) DBG | boot3="disk"
(default) DBG | boot4="none"
(default) DBG | acpi="on"
(default) DBG | ioapic="on"
(default) DBG | biossystemtimeoffset=0
(default) DBG | rtcuseutc="on"
(default) DBG | hwvirtex="on"
(default) DBG | nestedpaging="on"
(default) DBG | largepages="on"
(default) DBG | vtxvpid="on"
(default) DBG | vtxux="on"
(default) DBG | paravirtprovider="default"
(default) DBG | VMState="running"
(default) DBG | VMStateChangeTime="2016-08-26T00:14:11.624000000"
(default) DBG | monitorcount=1
(default) DBG | accelerate3d="off"
(default) DBG | accelerate2dvideo="off"
(default) DBG | teleporterenabled="off"
(default) DBG | teleporterport=0
(default) DBG | teleporteraddress=""
(default) DBG | teleporterpassword=""
(default) DBG | tracing-enabled="off"
(default) DBG | tracing-allow-vm-access="off"
(default) DBG | tracing-config=""
(default) DBG | autostart-enabled="off"
(default) DBG | autostart-delay=0
(default) DBG | defaultfrontend=""
(default) DBG | storagecontrollername0="SATA"
(default) DBG | storagecontrollertype0="IntelAhci"
(default) DBG | storagecontrollerinstance0="0"
(default) DBG | storagecontrollermaxportcount0="30"
(default) DBG | storagecontrollerportcount0="30"
(default) DBG | storagecontrollerbootable0="on"
(default) DBG | "SATA-0-0"="/Volumes/NASMAC/VMs/.docker/machines/default/boot2docker.iso"
(default) DBG | "SATA-ImageUUID-0-0"="795b47c2-4aa8-4cad-94e0-f7bbdd86a6d2"
(default) DBG | "SATA-tempeject"="off"
(default) DBG | "SATA-IsEjected"="off"
(default) DBG | "SATA-1-0"="/Volumes/NASMAC/VMs/.docker/machines/default/disk.vmdk"
(default) DBG | "SATA-ImageUUID-1-0"="60ac344f-b661-458e-88ad-5bedc40d343a"
(default) DBG | "SATA-2-0"="none"
(default) DBG | "SATA-3-0"="none"
(default) DBG | "SATA-4-0"="none"
(default) DBG | "SATA-5-0"="none"
(default) DBG | "SATA-6-0"="none"
(default) DBG | "SATA-7-0"="none"
(default) DBG | "SATA-8-0"="none"
(default) DBG | "SATA-9-0"="none"
(default) DBG | "SATA-10-0"="none"
(default) DBG | "SATA-11-0"="none"
(default) DBG | "SATA-12-0"="none"
(default) DBG | "SATA-13-0"="none"
(default) DBG | "SATA-14-0"="none"
(default) DBG | "SATA-15-0"="none"
(default) DBG | "SATA-16-0"="none"
(default) DBG | "SATA-17-0"="none"
(default) DBG | "SATA-18-0"="none"
(default) DBG | "SATA-19-0"="none"
(default) DBG | "SATA-20-0"="none"
(default) DBG | "SATA-21-0"="none"
(default) DBG | "SATA-22-0"="none"
(default) DBG | "SATA-23-0"="none"
(default) DBG | "SATA-24-0"="none"
(default) DBG | "SATA-25-0"="none"
(default) DBG | "SATA-26-0"="none"
(default) DBG | "SATA-27-0"="none"
(default) DBG | "SATA-28-0"="none"
(default) DBG | "SATA-29-0"="none"
(default) DBG | natnet1="nat"
(default) DBG | macaddress1="080027B1BA88"
(default) DBG | cableconnected1="on"
(default) DBG | nic1="nat"
(default) DBG | nictype1="82540EM"
(default) DBG | nicspeed1="0"
(default) DBG | mtu="0"
(default) DBG | sockSnd="64"
(default) DBG | sockRcv="64"
(default) DBG | tcpWndSnd="64"
(default) DBG | tcpWndRcv="64"
(default) DBG | Forwarding(0)="ssh,tcp,127.0.0.1,56727,,22"
(default) DBG | hostonlyadapter2="vboxnet1"
(default) DBG | macaddress2="080027E6C715"
(default) DBG | cableconnected2="on"
(default) DBG | nic2="hostonly"
(default) DBG | nictype2="82540EM"
(default) DBG | nicspeed2="0"
(default) DBG | nic3="none"
(default) DBG | nic4="none"
(default) DBG | nic5="none"
(default) DBG | nic6="none"
(default) DBG | nic7="none"
(default) DBG | nic8="none"
(default) DBG | hidpointing="ps2mouse"
(default) DBG | hidkeyboard="ps2kbd"
(default) DBG | uart1="off"
(default) DBG | uart2="off"
(default) DBG | uart3="off"
(default) DBG | uart4="off"
(default) DBG | lpt1="off"
(default) DBG | lpt2="off"
(default) DBG | audio="none"
(default) DBG | clipboard="disabled"
(default) DBG | draganddrop="disabled"
(default) DBG | SessionName="headless"
(default) DBG | VideoMode="720,400,0"@0,0 1
(default) DBG | vrde="off"
(default) DBG | usb="off"
(default) DBG | ehci="off"
(default) DBG | xhci="off"
(default) DBG | SharedFolderNameMachineMapping1="Users"
(default) DBG | SharedFolderPathMachineMapping1="/Users"
(default) DBG | VRDEActiveConnection="off"
(default) DBG | VRDEClients=0
(default) DBG | vcpenabled="off"
(default) DBG | vcpscreens=0
(default) DBG | vcpfile="/Volumes/NASMAC/VMs/.docker/machines/default/default/default.webm"
(default) DBG | vcpwidth=1024
(default) DBG | vcpheight=768
(default) DBG | vcprate=512
(default) DBG | vcpfps=25
(default) DBG | GuestMemoryBalloon=0
(default) DBG | GuestOSType="Linux26_64"
(default) DBG | GuestAdditionsRunLevel=2
(default) DBG | GuestAdditionsVersion="5.1.2 r108956"
(default) DBG | GuestAdditionsFacility_VirtualBox Base Driver=50,1472170470695
(default) DBG | GuestAdditionsFacility_VirtualBox System Service=50,1472170489693
(default) DBG | GuestAdditionsFacility_Seamless Mode=0,1472170470695
(default) DBG | GuestAdditionsFacility_Graphics Mode=0,1472170470695
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | name="default"
(default) DBG | groups="/"
(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(default) DBG | UUID="bd23bada-e4d3-465e-a81f-f540b361da8a"
(default) DBG | CfgFile="/Volumes/NASMAC/VMs/.docker/machines/default/default/default.vbox"
(default) DBG | SnapFldr="/Volumes/NASMAC/VMs/.docker/machines/default/default/Snapshots"
(default) DBG | LogFldr="/Volumes/NASMAC/VMs/.docker/machines/default/default/Logs"
(default) DBG | hardwareuuid="bd23bada-e4d3-465e-a81f-f540b361da8a"
(default) DBG | memory=2048
(default) DBG | pagefusion="off"
(default) DBG | vram=8
(default) DBG | cpuexecutioncap=100
(default) DBG | hpet="on"
(default) DBG | chipset="piix3"
(default) DBG | firmware="BIOS"
(default) DBG | cpus=1
(default) DBG | pae="on"
(default) DBG | longmode="on"
(default) DBG | cpuid-portability-level=0
(default) DBG | bootmenu="disabled"
(default) DBG | boot1="dvd"
(default) DBG | boot2="dvd"
(default) DBG | boot3="disk"
(default) DBG | boot4="none"
(default) DBG | acpi="on"
(default) DBG | ioapic="on"
(default) DBG | biossystemtimeoffset=0
(default) DBG | rtcuseutc="on"
(default) DBG | hwvirtex="on"
(default) DBG | nestedpaging="on"
(default) DBG | largepages="on"
(default) DBG | vtxvpid="on"
(default) DBG | vtxux="on"
(default) DBG | paravirtprovider="default"
(default) DBG | VMState="running"
(default) DBG | VMStateChangeTime="2016-08-26T00:14:11.624000000"
(default) DBG | monitorcount=1
(default) DBG | accelerate3d="off"
(default) DBG | accelerate2dvideo="off"
(default) DBG | teleporterenabled="off"
(default) DBG | teleporterport=0
(default) DBG | teleporteraddress=""
(default) DBG | teleporterpassword=""
(default) DBG | tracing-enabled="off"
(default) DBG | tracing-allow-vm-access="off"
(default) DBG | tracing-config=""
(default) DBG | autostart-enabled="off"
(default) DBG | autostart-delay=0
(default) DBG | defaultfrontend=""
(default) DBG | storagecontrollername0="SATA"
(default) DBG | storagecontrollertype0="IntelAhci"
(default) DBG | storagecontrollerinstance0="0"
(default) DBG | storagecontrollermaxportcount0="30"
(default) DBG | storagecontrollerportcount0="30"
(default) DBG | storagecontrollerbootable0="on"
(default) DBG | "SATA-0-0"="/Volumes/NASMAC/VMs/.docker/machines/default/boot2docker.iso"
(default) DBG | "SATA-ImageUUID-0-0"="795b47c2-4aa8-4cad-94e0-f7bbdd86a6d2"
(default) DBG | "SATA-tempeject"="off"
(default) DBG | "SATA-IsEjected"="off"
(default) DBG | "SATA-1-0"="/Volumes/NASMAC/VMs/.docker/machines/default/disk.vmdk"
(default) DBG | "SATA-ImageUUID-1-0"="60ac344f-b661-458e-88ad-5bedc40d343a"
(default) DBG | "SATA-2-0"="none"
(default) DBG | "SATA-3-0"="none"
(default) DBG | "SATA-4-0"="none"
(default) DBG | "SATA-5-0"="none"
(default) DBG | "SATA-6-0"="none"
(default) DBG | "SATA-7-0"="none"
(default) DBG | "SATA-8-0"="none"
(default) DBG | "SATA-9-0"="none"
(default) DBG | "SATA-10-0"="none"
(default) DBG | "SATA-11-0"="none"
(default) DBG | "SATA-12-0"="none"
(default) DBG | "SATA-13-0"="none"
(default) DBG | "SATA-14-0"="none"
(default) DBG | "SATA-15-0"="none"
(default) DBG | "SATA-16-0"="none"
(default) DBG | "SATA-17-0"="none"
(default) DBG | "SATA-18-0"="none"
(default) DBG | "SATA-19-0"="none"
(default) DBG | "SATA-20-0"="none"
(default) DBG | "SATA-21-0"="none"
(default) DBG | "SATA-22-0"="none"
(default) DBG | "SATA-23-0"="none"
(default) DBG | "SATA-24-0"="none"
(default) DBG | "SATA-25-0"="none"
(default) DBG | "SATA-26-0"="none"
(default) DBG | "SATA-27-0"="none"
(default) DBG | "SATA-28-0"="none"
(default) DBG | "SATA-29-0"="none"
(default) DBG | natnet1="nat"
(default) DBG | macaddress1="080027B1BA88"
(default) DBG | cableconnected1="on"
(default) DBG | nic1="nat"
(default) DBG | nictype1="82540EM"
(default) DBG | nicspeed1="0"
(default) DBG | mtu="0"
(default) DBG | sockSnd="64"
(default) DBG | sockRcv="64"
(default) DBG | tcpWndSnd="64"
(default) DBG | tcpWndRcv="64"
(default) DBG | Forwarding(0)="ssh,tcp,127.0.0.1,56727,,22"
(default) DBG | hostonlyadapter2="vboxnet1"
(default) DBG | macaddress2="080027E6C715"
(default) DBG | cableconnected2="on"
(default) DBG | nic2="hostonly"
(default) DBG | nictype2="82540EM"
(default) DBG | nicspeed2="0"
(default) DBG | nic3="none"
(default) DBG | nic4="none"
(default) DBG | nic5="none"
(default) DBG | nic6="none"
(default) DBG | nic7="none"
(default) DBG | nic8="none"
(default) DBG | hidpointing="ps2mouse"
(default) DBG | hidkeyboard="ps2kbd"
(default) DBG | uart1="off"
(default) DBG | uart2="off"
(default) DBG | uart3="off"
(default) DBG | uart4="off"
(default) DBG | lpt1="off"
(default) DBG | lpt2="off"
(default) DBG | audio="none"
(default) DBG | clipboard="disabled"
(default) DBG | draganddrop="disabled"
(default) DBG | SessionName="headless"
(default) DBG | VideoMode="720,400,0"@0,0 1
(default) DBG | vrde="off"
(default) DBG | usb="off"
(default) DBG | ehci="off"
(default) DBG | xhci="off"
(default) DBG | SharedFolderNameMachineMapping1="Users"
(default) DBG | SharedFolderPathMachineMapping1="/Users"
(default) DBG | VRDEActiveConnection="off"
(default) DBG | VRDEClients=0
(default) DBG | vcpenabled="off"
(default) DBG | vcpscreens=0
(default) DBG | vcpfile="/Volumes/NASMAC/VMs/.docker/machines/default/default/default.webm"
(default) DBG | vcpwidth=1024
(default) DBG | vcpheight=768
(default) DBG | vcprate=512
(default) DBG | vcpfps=25
(default) DBG | GuestMemoryBalloon=0
(default) DBG | GuestOSType="Linux26_64"
(default) DBG | GuestAdditionsRunLevel=2
(default) DBG | GuestAdditionsVersion="5.1.2 r108956"
(default) DBG | GuestAdditionsFacility_VirtualBox Base Driver=50,1472170470695
(default) DBG | GuestAdditionsFacility_VirtualBox System Service=50,1472170489693
(default) DBG | GuestAdditionsFacility_Seamless Mode=0,1472170470695
(default) DBG | GuestAdditionsFacility_Graphics Mode=0,1472170470695
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | Host-only MAC: 080027e6c715
(default) DBG | 
(default) DBG | Using SSH client type: external
(default) DBG | Using SSH private key: /Volumes/NASMAC/VMs/.docker/machines/default/id_rsa (-rw-------)
(default) DBG | &{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Volumes/NASMAC/VMs/.docker/machines/default/id_rsa -p 22] /usr/bin/ssh <nil>}
(default) DBG | About to run SSH command:
(default) DBG | ip addr show
(default) DBG | SSH cmd err, output: exit status 255: 
Error getting IP address: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  :

**Comment by FrenchBen** [comment]
Let's focus on the SSH permissions too open first - Hopefully that will solve this issue as well.

**Comment by karneaud** [comment]
@FrenchBen  i believe we should close this issue and continue on https://github.com/docker/kitematic/issues/1939

**Comment by FrenchBen** [comment]
Closing in favor of #1939 :)

**Comment by jozcar** [comment]
Hi All, I was having the issue describe on this thread, using Windows 7,  I solve the problem by updating Virtual box.

**Comment by mike2tango** [comment]
Hi I have the latest version of Virutal Box but in this Winodows 7 I used it does not seem to work..

**Comment by jozcar** [comment]
I have version 5.1.28 r117968(Qt5.6.2), another thing that I forgot to mention was that I also reset the docker image that is used in Virtual Box,   to reset it , all you have to do is start the image, and then right click the image, and there "reset" option is enable, 

![virtualbox](https://user-images.githubusercontent.com/134879/30707743-766ca6d8-9eca-11e7-9ee2-5fe314b71780.PNG)
