### ISSUE TITLE
Launching Docker CLI from Kitematic not honouring DOCKER_CERT_PATH

### ISSUE THREAD

**Issue by karneaud** [docker/kitematic#1941]
### Expected behaviour
To start the docker terminal with correct DOCKER_CERT_PATH
### Actual behaviour
not detecting current running default machine resulting in 

> Could not read CA certificate "/Users/useraccount/.docker/machine/machines/default/ca.pem": open /Users/useraccount/.docker/machine/machines/default/ca.pem: no such file or directory

### Information about the Issue
When trying to start the terminal from within Kitematic using a CUSTOM MACHINE_STORAGE_PATH and DOCKER_CERT_PATH

docker commands fail as it does not recognise currently running default machine. I get errors such as

> Could not read CA certificate "/Users/useraccount/docker/machine/machines/default/ca.pem": open 

The command used seems to have the PATH to the /Users/useraccount hardcoded rather than using from the env as set for Kitematic

### Steps to reproduce the behavior

  1. see issue https://github.com/docker/kitematic/issues/1939
  2. open Kitematic 
  3. open terminal from Kinematic menu

**Comment by FrenchBen** [comment]
The `Quick Start Terminal` is a toolbox product - if it's related to that, then an issue should be opened there: https://github.com/docker/toolbox

The information you provided is misleading, the error indicates that the machine you created is at:
```
/Volumes/VMs/docker/
```
yet it seems that you're trying to load certs from this location:
```
/Volumes/NASMAC/VMs/.docker/
```
Which one is it? Are you creating these machines with different env vars?

**Comment by karneaud** [comment]
@FrenchBen  Oops my bad would open the ticket in the appropriate repo

**Comment by karneaud** [comment]
Im reopening this issue because i think it maybe related to the Kitematic software as launching the "Docker CLI" from within Kitematic produces this error. 

What is more interesting is that when I have a look at the command used in the process the DOCKER_CERT_PATH has the path hardcoded to use /User/useraccount/..... instead of the env path specified and as used by Kitematic.

**Comment by FrenchBen** [comment]
Where is it hard-coded?

**Comment by karneaud** [comment]
great should I re-install the latest version now?

**Comment by FrenchBen** [comment]
Haven't made a new release - There are a couple of pending PRs I'd like to merge prior to making a new release.
