### ISSUE TITLE
Specify required node version

### ISSUE THREAD

**Issue by Fahrradflucht** [docker/kitematic#1944]
[CONTRIBUTING.md](https://github.com/docker/kitematic/blob/master/CONTRIBUTING.md) only says that Node is needed but it does not say which version should be used. Correct me if I'm wrong but this suggests to me that the current version should be good. Especially because there is neither an .nvmrc file in the project nor an `engines` key set in package.json.

Turns out the tests won't even run on node 6.

Looking in [.travis.yml](https://github.com/docker/kitematic/blob/master/.travis.yml) I see that the CI tests run on 4.2.2 what suggests that this is the version everyone should develop against.

Options of fixing that are:
- Adding the version to CONTRIBUTING.md (Which has a high risk of going stale I think)
- Adding a [.nvmrc](https://github.com/creationix/nvm#nvmrc)
- Add an `engines` key to package.json

**Comment by FrenchBen** [comment]
Interestingly enough I thought I had made a PR for this - It would be nice to have it in the CONTRIBUTING.md, but as mentioned could go stale pretty easily. 

The cleanest is probably to add the proper `engines` entry to `package.json`. Do you think you could make a PR for this?

**Comment by Fahrradflucht** [comment]
Sure I will do it tomorrow (CEST)
