### ISSUE TITLE
[bug] Can't configure ports on Kitematic (Windows)

### ISSUE THREAD

**Issue by stephaaan** [docker/kitematic#1947]
### Expected behavior
The (+) button under Settings > Ports (from a Container) should allow you to create new IP:port combinations

### Actual behavior
Nothing happens when you click on the (+) button. 

### Information about the Issue
This has been tested with Docker 1.12.0 (b5968) with kitematic 0.12.0.0 (alpha)

### Steps to reproduce the behavior
  1. Download any docker container
  2. Go to it's Settings > Ports page
  3. Try to add a IP:port combination via the (+) button.

**Comment by FrenchBen** [comment]
The + button is only to add a rule for existing exposed ports - there's a PR to allow ports to be added by the user, even if they're not exposed by the image. 

The image should be built properly and expose the ports/volumes it uses which the user can map. Open an issue with the image owned :)
