### ISSUE TITLE
Feature Suggestion: Login into Host 

### ISSUE THREAD

**Issue by donert** [docker/kitematic#1948]
### Expected behavior
On the UI, there should be an easy way to login into the docker host. On docker for Mac, the equivalent of:
`screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`

### Actual behavior
Feature doesn't exist.

### Information about the Issue
The presence of a UI widget to take a use to the docker host would be helpful for those just learning docker. It may be a handy short cut for those more experienced as well.

**Comment by FrenchBen** [comment]
There is no use case to login to the docker host - Any changes made on the docker host will not persist and thus is useless.
