### ISSUE TITLE
Network time out for the following docker image.

### ISSUE THREAD

**Issue by vcao** [docker/kitematic#1951]
### Expected behavior
Download and install data-volume docker image.

### Actual behavior
Network timed out while trying to connect to https://index.docker.io/v1/repositories/boomtownroi/data-volume/images. You may want to check your internet connection or if you are behind a proxy.

### Steps to reproduce the behavior

  1. ... Search data-volume docker image
  2. ... Attempt to install data-volume docker-image

**Comment by FrenchBen** [comment]
Unable to replicate. I would confirm that you've got proper connectivity and retry to install/setup a container based on that image

![data-volume](https://cloud.githubusercontent.com/assets/3965324/18130029/5680ed18-6f85-11e6-8f32-175d29d523a8.png)
