### ISSUE TITLE
Kitematic Freezing on startup OSX

### ISSUE THREAD

**Issue by Scoutski** [docker/kitematic#1952]
### Expected behavior

Expect the checking docker screen to run from 0-100% and then proceed to the login screen.

### Actual behavior

Checking docker screen moves from 0-5% and then goes straight to the login screen with the cursor caret frozen immediately. Happens consistently.

### Information about the Issue

Kitematic only installed for the first time today, issues have occurred since first run.

Kitematic was installed form the latest version of docker toolbox (1.12.0)
Docker Version 1.12.1-beta24
Virtual Box 5.0.26
OS X El Capitan 10.11.6

Have not been able to determine any additional information from trying to reproduce the issue. Have tried running:
```docker-machine rm -f dev && docker-machine create -d virtualbox dev```
as per [this page](https://docs.docker.com/kitematic/known-issues/) to no avail.

No reported error messages are presented.

### Steps to reproduce the behavior

  1. Start up Kitematic from applications folder or terminal.

Please let me know if I can provide any more information to help👌

**Comment by FrenchBen** [comment]
Since you're running on a Mac 10.11.6 - I would recommend using Docker for Mac:
https://www.docker.com/products/docker/#mac

**Comment by Scoutski** [comment]
Thanks for your response, @FrenchBen - Unfortunately this didn't resolve the problem for me, but I'll continue to look into it and report back to the ticket if I find a solution.

**Comment by FrenchBen** [comment]
@Scoutski looking at this info:
```
Docker Version 1.12.1-beta24
Virtual Box 5.0.26
OS X El Capitan 10.11.6
```
It's a bit a mix and match. 
If you're using Docker for Mac, there is no need for any virtualbox whatsoever. You can simply run containers without it, as Docker for Mac handles all of the heavy lifting.

**Comment by Scoutski** [comment]
Hi @FrenchBen - Thanks for your response.

I think initially I wasn't actually using Virtual Box when it was present. I was trying to use Docker for Mac. I've been able to get around the issue using Virtual Box for now, but was never able to get it running with Docker for Mac 😢. I understand that it isn't an ideal solution, but my use case is personal and pretty limited so it's not a big problem for me. Again, I appreciate you getting back to me on this.

**Comment by FrenchBen** [comment]
@Scoutski for development purposes it would be nice to know what's causing the blockage and what prevents you from using Docker for Mac and Kitematic together
