### ISSUE TITLE
Getting 404 error while fetching repo solr:latest

### ISSUE THREAD

**Issue by parimal-patel** [docker/kitematic#1953]
### Expected behavior
It should create a repo
### Actual behavior
Giving 404 error
### Information about the Issue
HTTP code is 404 which indicates error: no such image - [object Object]

### Steps to reproduce the behavior

  1. Install Kitematic 0.12.0
  2. Click on create button for solr image from list of available images
<img width="1075" alt="screen shot 2016-08-30 at 12 09 25 pm" src="https://cloud.githubusercontent.com/assets/3582637/18078707/a599ce50-6eaa-11e6-8efc-9d97cc12227b.png">

**Comment by FrenchBen** [comment]
Unable to replicate as solr downloads properly for me.
What happens if you do this via the terminal:
`docker pull solr:latest`

**Comment by parimal-patel** [comment]
This issue is fixed after resetting Wifi service from Mac.
