### ISSUE TITLE
UTC time error

### ISSUE THREAD

**Issue by dongm2ez** [docker/kitematic#1954]
### Expected behavior
in containers i hope one correct time
### Actual behavior
I get error time, One hour faster than normal time
### Information about the Issue

Last login: Tue Aug 30 15:51:15 on ttys003
bash -c "clear && docker exec -it memcached sh"
➜  ~ bash -c "clear && docker exec -it memcached sh"
$ date
Sat Aug 27 17:01:04 CST 2016

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Container time should always be in UTC, but depending on the image/settings, you may get something slightly different.
For example, when I run the `memcached` image you mentioned above, I get:
```
$ date
Wed Aug 31 13:07:39 UTC 2016
```
