### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by JimXie83** [docker/kitematic#1958]
### Expected behavior
create docker container
### Actual behavior
can not create container, 
### Information about the Issue

Network timed out while trying to connect to https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images. You may want to check your internet connection or if you are behind a proxy.

my Internet connection is fine.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Your internet connection may be fine, but if you are behind a proxy, you will need to configure it properly:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
