### ISSUE TITLE
Killing containers does not remove them from Kitematic

### ISSUE THREAD

**Issue by dave-tucker** [docker/kitematic#1962]
From: https://github.com/docker/for-mac/issues/481 

### Expected behavior
docker kill $(docker ps -aq)
and
docker rm $(docker ps -aq)
should cause the containers to be removed from kitematic dynamically (it used to do this in toolbox kitematic)
### Actual behavior
Conteiners show they are greenand running but are not when "docker ps" is executed

### Information

Diagnostic ID: F99F8B18-EA59-489A-B1BA-E63AA3FAB90A
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by FrenchBen** [comment]
@dave-tucker this works as expected - Killing a container doesn't actually remove it, only kills the running process:
https://docs.docker.com/engine/reference/commandline/kill/#kill

Killing a non-running container would return: 
`Error response from daemon: Cannot kill container xxx: Container xxx  is not running`
