### ISSUE TITLE
Error 400 when creating container from local ruby-alpine image

### ISSUE THREAD

**Issue by hubletkoresh** [docker/kitematic#1965]
### Expected behavior
Container is created and running, can attach PowerShell to container.
### Actual behavior
![Wat?!](http://fs5.directupload.net/images/160904/q4abcjtc.png)
### Information about the Issue
Dockerfile:
```
FROM ruby:alpine

# Reset stupid settings (base image forces you into irb console)
CMD []
ENTRYPOINT []

# Need this for project
RUN apk add --update --no-cache nginx nano

#Allow to mount source code directory from host
VOLUME ["/www/projectname"]
WORKDIR /www/projectname

#Add gemfile so we can have the deps installed right away
ADD ./railsapp/Gemfile /www/projectname/railsapp/
ONBUILD RUN bundle install
```

### Steps to reproduce the behavior

  1. Make this Dockerfile
  2. Put it in folder called `projectname` that also contains `railsapp` with `Gemfile`
  3. Build image
  4. Use Kitematic to create container from that imge

**Comment by hubletkoresh** [comment]
The problem is with `CMD []` and `ENTRYPOINT []`. It goes away if I remove those. But I need these, and being able to reset parent image settings this way is expected functionality.

**Comment by FrenchBen** [comment]
You cannot have an empty command and entrypoint - It looks like you're trying to re-create their onbuild image, why not just use that?
https://github.com/docker-library/ruby/blob/1b08f346713a1293c2a9238e470e086126e2e28f/2.3/onbuild/Dockerfile

**Comment by hubletkoresh** [comment]
I am not. I am using ruby:alpine, which is much larger and uglier than original image. It is not productive to try copy the entire thing just to change the entrypoint or command.

Either way, I have specified the `ENTRYPOINT` to be `bin/sh` and it works. It would be helpful if Kitematic provided a more specific error message.

**Comment by FrenchBen** [comment]
The newer version of Kitematic (hasn't been released but based on the master source code) does have more details when such error occurs.
