### ISSUE TITLE
Need readable icon when the container item is selected

### ISSUE THREAD

**Issue by mmcer** [docker/kitematic#1966]
### Expected behavior
The container icon should be readable if the item is selected to get its status(running or not)

### Actual behavior
When the item is selected, the background color is blue, and the icon color is white, I don't know its current status expect I select the other item, when I see green icon, I know the container is running.

It is very easy to know the status if the item not selected, one is green and the other one is gray, but the difference is very small when selected.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
The icon itself is different for every status:

Stopped: <img width="27" alt="stopped" src="https://cloud.githubusercontent.com/assets/3965324/18266209/ef960194-7419-11e6-8010-e357eb2d8fda.png">
Running: <img width="32" alt="running" src="https://cloud.githubusercontent.com/assets/3965324/18266213/f35e9a8e-7419-11e6-8383-756b297d7d07.png">

Running Selected: <img width="31" alt="selected-running" src="https://cloud.githubusercontent.com/assets/3965324/18266222/fdbc003e-7419-11e6-8414-573adc1977fe.png">
Stopped Selected: <img width="28" alt="selected-stopped" src="https://cloud.githubusercontent.com/assets/3965324/18266221/fdb9c9cc-7419-11e6-8b8d-0222c247a76d.png">
Closing for now, unless you can provide assets to replace the current status icons

**Comment by mmcer** [comment]
hi, for the running selected icon, is it possible to use green color? that we know there is just background color changed for running and running selected?
and, how can I provider the assets?

**Comment by FrenchBen** [comment]
@mmcer  IMHO this would look quite ugly on the blue that we have.
