### ISSUE TITLE
Kitematic install Error 

### ISSUE THREAD

**Issue by mrslawshe** [docker/kitematic#1968]
First time using Docker, trying to install it on a Windows 7 using the docker toolbox. The VM seems to be running fine, but when I try to open Kitematic, it loads 50% and gives me the below error. Not sure what to do.

**Below are all of the screens I have running, ie. VM toolbox, command, etc.**

![image](https://cloud.githubusercontent.com/assets/21180422/18274399/3f3897a2-7410-11e6-9faf-9a6a17aea6a9.png)

![image](https://cloud.githubusercontent.com/assets/21180422/18274415/542a8030-7410-11e6-857e-9c2d1c834a7a.png)

![image](https://cloud.githubusercontent.com/assets/21180422/18274455/6e2e7a86-7410-11e6-9b0c-f819457ef57f.png)

![image](https://cloud.githubusercontent.com/assets/21180422/18274473/86a9c818-7410-11e6-9dbc-0162fe81c33b.png)

**Steps I take to get this error**

  1. Open docker quickstart - works fine
  2. Start the VM VirtualBox - works fine
  3. Try to open Kitematic to finish the Docker setup - loads 50% and gives error

**Comment by GesuitaVolante** [comment]
Same error Here

**Comment by FrenchBen** [comment]
@mrslawshe it is the expected behavior for now, as we assume that the user will be using Docker for Windows instead of Virtualbox. 
The latest build of Kitematic (to be release next week) will have a better error message displayed. 

Thanks
