### ISSUE TITLE
Can't select hidden folder as Volume (Mac)

### ISSUE THREAD

**Issue by elysrivero99** [docker/kitematic#1978]
I have an image based on Maven and I need to configure ~/.m2 Volume.

![captura de pantalla 2016-09-09 a las 10 32 49 am](https://cloud.githubusercontent.com/assets/3760276/18392817/dbb002c2-7678-11e6-898a-fa4944e25379.png)

But, when I click on "change" I can't see my hidden folders (/Users/<myuser>/.m2). If I open /Users/<myuser>/ with finder, I can see all my hidden folders.

**Comment by FrenchBen** [comment]
The open/select folder window is part of the OS, not something Kitematic controls.
Please see this stackoverflow answer:
http://apple.stackexchange.com/a/186378
