### ISSUE TITLE
Error to download the image

### ISSUE THREAD

**Issue by jmaciel33** [docker/kitematic#1981]
### Steps to reproduce the behavior

  1. ...Download the image
  2. ...

**Comment by Fahrradflucht** [comment]
> Download the image

Which image?

What is the exact error you encounter?

Are you behind a proxy? If yes check this out: https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by FrenchBen** [comment]
No information provided - Closing
