### ISSUE TITLE
Proper Windows installer

### ISSUE THREAD

**Issue by atrauzzi** [docker/kitematic#1982]
I'm using Docker for Windows, and so toolbox really doesn't make sense for me.  It would be nice if kitematic listed a proper `.msi` installer on the web site to install *just* kitematic.  Not the entirety of toolbox.

**Comment by FrenchBen** [comment]
Thanks @atrauzzi for the issue - We are tracking this issue internally and will probably bundle it within the Docker for Windows installer.

**Comment by atrauzzi** [comment]
Why not have a standalone installer that can always be used separately regardless of what else is installed?

**Comment by FrenchBen** [comment]
@atrauzzi ideally it could be, but would require some re-work on the Toolbox side.

**Comment by atrauzzi** [comment]
Well, you don't really need toolbox at that point then, do you?  I mean, just take the `.zip` that's being distributed here and wrap it in an MSI installer...?

**Comment by FrenchBen** [comment]
@atrauzzi Toolbox is still supported, which means that I would need to create 2 different process: 1 for toolbox and 1 for Docker for Windows. 
There's an internal discussion on how we should do this and we'll go with the path of least resistance. 

Thank you for your patience and feedback.

**Comment by atrauzzi** [comment]
@FrenchBen You might be misunderstanding.  I'm not saying I needed toolbox support or docker for windows support.

I'm saying just make a windows installer. Nothing to do with toolbox or docker for windows.

**Comment by FrenchBen** [comment]
@atrauzzi I understand it perfectly - Toolbox is currently using the Zip release as the source for the toolbox install of Kitematic. 
Creating the release as a Windows installer means that Toolbox would then start a separate installer during its own install (follow me?)

Although you're not needing them, the 2 products are closely linked; which means that a change of setup in Kitematic would trigger a change of setup in toolbox.

**Comment by atrauzzi** [comment]
@FrenchBen Many installers support unattended modes (think xamarin, chocolatey as well as many others).

Although application dependency management sucks in Windows, this might be one way to have the standalone installer and then just have any depending applications deal with making the install silent on their ends.

**Comment by FrenchBen** [comment]
@atrauzzi I'm not too familiar with the different stacks of windows installers. If you'd like to take a stab at it, I would def appreciate the help :)
