### ISSUE TITLE
"weareathlon/chimpjs-xfvb" downloading failed

### ISSUE THREAD

**Issue by olegdovger** [docker/kitematic#1986]
### Steps to reproduce the behavior

  1. Open kinematic app
  2. Find 'chimpjs'
  3. Start to download "weareathlon/chimpjs-xfvb". Can not be downloaded

"Tag latest not found in repository docker.io/weareathlon/chimpjs-xfvb"

**Comment by FrenchBen** [comment]
Works as expected, the repo doesn't have the latest tag:
https://hub.docker.com/r/weareathlon/chimpjs-xfvb/tags/

Open an issue with the image owner
