### ISSUE TITLE
Advanced Option not applied as expected

### ISSUE THREAD

**Issue by sgentile** [docker/kitematic#1987]
### Expected behavior
running container advanced options should be applied automatically

### Actual behavior
after running docker, ie...
docker run --rm -t -i --name kb -v $(pwd)/kb:/kb -p 8080:8080 sgentile/kb:latest /bin/bash

When I refresh Kitematic it shows my docker container running, when I goto 'advanced' it show 'Allocate a TTY for this container' and 'Keep STDIN open even if not attached' as checked, but I have to press 'Save' in order for it to apply 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
You are passing them in the command line:  `-t -i` no need to click 'save' again. If the option is checked, it means it's enable for the container.

**Comment by sgentile** [comment]
If I don't click 'save' it doesn't work - that is the issue I'm having.
That even though it's checked, it doesn't get until I hit save.

**Comment by FrenchBen** [comment]
I'm not sure I understand - You're passing the `-it` flags to the container creation directly. How can it not work? What do you observe doesn't work when you don't click save?

**Comment by sgentile** [comment]
It shows green like it's running but the console area and mapped drives
don't show up.  If I hit the url it exposes it doesn't work.  Once I hit
save it looks like it actually starts running - I can send screenshots if
that helps

**Comment by FrenchBen** [comment]
please do - unfortunately the image you're using is private, which makes it difficult to replicate. 
Can you show the same with something like `alpine:latest` ?

**Comment by sgentile** [comment]
Screenshots show that although it says it's running, it doesn't actually
run until I click 'save' on options.

**Comment by FrenchBen** [comment]
Can you share the screenshots?

**Comment by sgentile** [comment]
my apologies, I uploaded and share them here:

https://drive.google.com/drive/folders/0BxsqBrmXThvaWEREenJsb3NieW8?usp=sharing

**Comment by FrenchBen** [comment]
What you're seeing is actually a different bug. 
When you hit 'save' we actually re-create your container with all of the new settings. In this case we didn't copy the existing run `CMD` that you provided `/bin/bash` and instead run the default `CMD` which seems to be tomcat for your image. 

The container is running, but the only thing that it's running is a `bash` shell. If you type stuff in after your `docker run ...` command, you'll see that show up in the log window of Kitematic.

**Comment by sgentile** [comment]
ok, I took that off and it worked as expected - thanks for following up and working with me on this
