### ISSUE TITLE
where is the dockerfile for the container that kitematic manages?

### ISSUE THREAD

**Issue by jhgorse** [docker/kitematic#1990]
### Expected behavior
Export or view the effective "dockerfile" for a container configuration listed in kitematic
### Actual behavior
Cannot find any "dockerfile" representing current configuration
### Information about the Issue
I am on macOS Sierra using the native beta docker app.
### Steps to reproduce the behavior
Pull an image into container. Change settings. Look for dockerfile.

**Comment by FrenchBen** [comment]
Dockerfile is what is used to build the image. The image is what you distribute. Some image creator share the dockerfile, some don't. 
You can always use their image as the base of your Dockerfile and create your own modifications to it.

**Comment by jhgorse** [comment]
Yeah... I see it now. It seems strange to me that the Dockerfile does not get embedded or cannot be inferred from the `image` or `container` via the _inspect_ command or similar.

Also awkward is the wiring up of the networks known as `linking` which can only be done prior to instantiating a `container` from an `image`.

In any case, for reference the current workflow for modifying a kitematic container is as follows:
* docker commit `containername` yourgithubaccount/yourcontainername
* docker run `yournewoptions (e.g. --link)` `thenewimage`

**Comment by FrenchBen** [comment]
Linking is the old way to wire up containers - You can now create a network specific to a set of containers and dynamically add them to that network.
