### ISSUE TITLE
Error: connect ENOENT //./pipe/docker_engine

### ISSUE THREAD

**Issue by an0nh4x0r** [docker/kitematic#1992]
![docker1](https://cloud.githubusercontent.com/assets/9419452/18547782/fd61d6d6-7af9-11e6-89dd-54744b8ab18b.png)

I don't understand why i am getting this error

docker version 1.12.0, build 8eab29e
virtual box version 5.0.26 r108824

**Comment by FrenchBen** [comment]
Kitematic prefers a native setup - You can click the 'Use Virtualbox' button to get things working with Virtualbox.

The new release will have a better message to handle this.

**Comment by an0nh4x0r** [comment]
@FrenchBen if i click "USE VIRTUALBOX"  then also it is not working giving error. I don't know what to do now :(

**Comment by FrenchBen** [comment]
@an0nh4x0r Is this using the latest release?
https://github.com/docker/kitematic/releases/tag/v0.12.0

**Comment by an0nh4x0r** [comment]
Command failed: C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.8.0, build b85aac1,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:49861,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:49865,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: E:\Programs\Oracle\Virtualbox\VBoxManage.exe --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.0.26r108824,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Hyper-V is not installed.,(default) DBG | %!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)COMMAND: wmic cpu get VirtualizationFirmwareEnabled,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | VirtualizationFirmwareEnabled ,(default) DBG | TRUE ,(default) DBG | ,(default) DBG | },(default) DBG | local Boot2Docker ISO version: v1.12.0,Error with pre-create check: "read tcp 192.168.1.3:49873->54.231.32.107:443: wsarecv: An existing connection was forcibly closed by the remote host.",open C:\Users\an0nh4x0r\.docker\machine\machines\default\default\Logs\VBox.log: The system cannot find the path specified.,notifying bugsnag: [Error with pre-create check: "read tcp 192.168.1.3:49873->54.231.32.107:443: wsarecv: An existing connection was forcibly closed by the remote host."],bugsnag.Notify: [bugsnag/payload.deliver: Post https://notify.bugsnag.com/: net/http: TLS handshake timeout],

**Comment by an0nh4x0r** [comment]
yes i am using the latest version.

**Comment by FrenchBen** [comment]
@an0nh4x0r Can you open an issue in `docker/machine` with the above output? They'll be able to help.

**Comment by an0nh4x0r** [comment]
Ok

**Comment by pcp1976** [comment]
Same problem, latest version running on Windows 7. Run Kitematic with administrative permissions, use VBox.

**Comment by an0nh4x0r** [comment]
@pcp1976 will try asap :+1:

**Comment by sanjayjare** [comment]
How do i connect the github repository with docker kitmatic

**Comment by ZetaoYang** [comment]
I have solved this problem.
First,I will show the error info here:
```
Command failed: G:\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.8.2, build e18a919,Found binary path at G:\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:13087,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at G:\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:13091,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: G:\VirtualBox\VBoxManage.exe --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.1.8r111374,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Hyper-V is not installed.,(default) DBG | %!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)COMMAND: wmic cpu get VirtualizationFirmwareEnabled,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | VirtualizationFirmwareEnabled ,(default) DBG | TRUE ,(default) DBG | ,(default) DBG | },(default) DBG | local Boot2Docker ISO version: v1.12.2,Error with pre-create check: "read tcp 172.30.203.73:13151->54.231.81.88:443: wsarecv: An existing connection was forcibly closed by the remote host.",open C:\Users\Yang\.docker\machine\machines\default\default\Logs\VBox.log: The system cannot find the path specified.,notifying bugsnag: [Error with pre-create check: "read tcp 172.30.203.73:13151->54.231.81.88:443: wsarecv: An existing connection was forcibly closed by the remote host."],
```  
because it has the space between 'Docker' and ' Toolbox' of "G:\Docker Toolbox\docker-machine.exe" , you can solve this problem use `"e" -D create -d virtualbox --virtualbox-memory 2048 default` in terminal, just like this:    
![image](https://cloud.githubusercontent.com/assets/10769951/20302687/46799612-ab63-11e6-8e59-a72b33b198f0.png)  
notice that we must enclose `G:\Docker Toolbox\docker-machine.exe` in quotation marks. If you add`docker-machine.exe` in the PATH, you alse can use`docker-machine -D create -d virtualbox --virtualbox-memory 2048 default` directly.  
then enjoy Kitematic.  
(P.S. I tested it in Kitematic-0.13.0-RC1, maybe you can be Kitematic-0.12.0 or other version.)

**Comment by singhakash** [comment]
Has anybody found the solution to this, the above solution dint work for me.

I have DockerToolbox1.12.5 on running normally it shows
`Error: connect ENOENT //./pipe/docker_engine`

On choosing `USE VIRTUALBOX` option it gave me

`Command failed: C:\DockerToolbox\docker-machine.exe -D start default,Docker Machine Version: 0.8.2, build e18a919,Found binary path at C:\DockerToolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:51351,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,command=start machine=default,(default) Calling .GetState,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo default --machinereadable,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | name="default",(default) DBG | groups="/",(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)",(default) DBG | UUID="d2371a97-14a7-4158-a9f0-2e51add35f8b",(default) DBG | CfgFile="C:\\Users\\Akash Singh\\.docker\\machine\\machines\\default\\default\\default.vbox",(default) DBG | SnapFldr="C:\\Users\\Akash Singh\\.docker\\machine\\machines\\default\\default\\Snapshots",(default) DBG | LogFldr="C:\\Users\\Akash Singh\\.docker\\machine\\machines\\default\\default\\Logs",(default) DBG | hardwareuuid="d2371a97-14a7-4158-a9f0-2e51add35f8b",(default) DBG | memory=2048,(default) DBG | pagefusion="off",(default) DBG | vram=8,(default) DBG | cpuexecutioncap=100,(default) DBG | hpet="on",(default) DBG | chipset="piix3",(default) DBG | firmware="BIOS",(default) DBG | cpus=1,(default) DBG | pae="on",(default) DBG | longmode="on",(default) DBG | triplefaultreset="off",(default) DBG | apic="on",(default) DBG | x2apic="off",(default) DBG | cpuid-portability-level=0,(default) DBG | bootmenu="disabled",(default) DBG | boot1="dvd",(default) DBG | boot2="dvd",(default) DBG | boot3="disk",(default) DBG | boot4="none",(default) DBG | acpi="on",(default) DBG | ioapic="on",(default) DBG | biosapic="apic",(default) DBG | biossystemtimeoffset=0,(default) Calling .Start,(default) DBG | rtcuseutc="on",(default) DBG | hwvirtex="on",(default) DBG | nestedpaging="on",(default) DBG | largepages="on",(default) DBG | vtxvpid="on",(default) DBG | vtxux="on",(default) DBG | paravirtprovider="default",(default) DBG | effparavirtprovider="kvm",(default) DBG | VMState="poweroff",(default) DBG | VMStateChangeTime="2017-03-09T19:46:17.000000000",(default) DBG | monitorcount=1,(default) DBG | accelerate3d="off",(default) DBG | accelerate2dvideo="off",(default) DBG | teleporterenabled="off",(default) DBG | teleporterport=0,(default) DBG | teleporteraddress="",(default) DBG | teleporterpassword="",(default) DBG | tracing-enabled="off",(default) DBG | tracing-allow-vm-access="off",(default) DBG | tracing-config="",(default) DBG | autostart-enabled="off",(default) DBG | autostart-delay=0,(default) DBG | defaultfrontend="",(default) DBG | storagecontrollername0="SATA",(default) DBG | storagecontrollertype0="IntelAhci",(default) DBG | storagecontrollerinstance0="0",(default) DBG | storagecontrollermaxportcount0="30",(default) DBG | storagecontrollerportcount0="30",(default) DBG | storagecontrollerbootable0="on",(default) DBG | "SATA-0-0"="C:\Users\Akash Singh\.docker\machine\machines\default\boot2docker.iso",(default) DBG | "SATA-ImageUUID-0-0"="bcf5f3f2-c8a0-4629-a8c5-72782ac5602d",(default) DBG | "SATA-tempeject"="off",(default) DBG | "SATA-IsEjected"="off",(default) DBG | "SATA-1-0"="C:\Users\Akash Singh\.docker\machine\machines\default\disk.vmdk",(default) DBG | "SATA-ImageUUID-1-0"="1cc0e4d4-2222-4c64-a558-cea0897ac805",(default) DBG | "SATA-2-0"="none",(default) DBG | "SATA-3-0"="none",(default) DBG | "SATA-4-0"="none",(default) DBG | "SATA-5-0"="none",(default) DBG | "SATA-6-0"="none",(default) DBG | "SATA-7-0"="none",(default) DBG | "SATA-8-0"="none",(default) DBG | "SATA-9-0"="none",(default) DBG | "SATA-10-0"="none",(default) DBG | "SATA-11-0"="none",(default) DBG | "SATA-12-0"="none",(default) DBG | "SATA-13-0"="none",(default) DBG | "SATA-14-0"="none",(default) DBG | "SATA-15-0"="none",(default) DBG | "SATA-16-0"="none",(default) DBG | "SATA-17-0"="none",(default) DBG | "SATA-18-0"="none",(default) DBG | "SATA-19-0"="none",(default) DBG | "SATA-20-0"="none",(default) DBG | "SATA-21-0"="none",(default) DBG | "SATA-22-0"="none",(default) DBG | "SATA-23-0"="none",(default) DBG | "SATA-24-0"="none",(default) DBG | "SATA-25-0"="none",(default) DBG | "SATA-26-0"="none",(default) DBG | "SATA-27-0"="none",(default) DBG | "SATA-28-0"="none",(default) DBG | "SATA-29-0"="none",(default) DBG | natnet1="nat",(default) DBG | macaddress1="080027DDC541",(default) DBG | cableconnected1="on",(default) DBG | nic1="nat",(default) DBG | nictype1="82540EM",(default) DBG | nicspeed1="0",(default) DBG | mtu="0",(default) DBG | sockSnd="64",(default) DBG | sockRcv="64",(default) DBG | tcpWndSnd="64",(default) DBG | tcpWndRcv="64",(default) DBG | Forwarding(0)="ssh,tcp,127.0.0.1,51220,,22",(default) DBG | hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #3",(default) DBG | macaddress2="0800270FDB14",(default) DBG | cableconnected2="on",(default) DBG | nic2="hostonly",(default) DBG | nictype2="82540EM",(default) DBG | nicspeed2="0",(default) DBG | nic3="none",(default) DBG | nic4="none",(default) DBG | nic5="none",(default) DBG | nic6="none",(default) DBG | nic7="none",(default) DBG | nic8="none",(default) DBG | hidpointing="ps2mouse",(default) DBG | hidkeyboard="ps2kbd",(default) DBG | uart1="off",(default) DBG | uart2="off",(default) DBG | uart3="off",(default) DBG | uart4="off",(default) DBG | lpt1="off",(default) DBG | lpt2="off",(default) DBG | audio="dsound",(default) DBG | clipboard="disabled",(default) DBG | draganddrop="disabled",(default) DBG | vrde="off",(default) DBG | usb="off",(default) DBG | ehci="off",(default) DBG | xhci="off",(default) DBG | SharedFolderNameMachineMapping1="c/Users",(default) DBG | SharedFolderPathMachineMapping1="\\?\c:\Users",(default) DBG | vcpenabled="off",(default) DBG | vcpscreens=0,(default) DBG | vcpfile="C:\Users\Akash Singh\.docker\machine\machines\default\default\default.webm",(default) DBG | vcpwidth=1024,(default) DBG | vcpheight=768,(default) DBG | vcprate=512,(default) DBG | vcpfps=25,(default) DBG | GuestMemoryBalloon=0,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo default --machinereadable,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | name="default",(default) DBG | groups="/",(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)",(default) DBG | UUID="d2371a97-14a7-4158-a9f0-2e51add35f8b",(default) DBG | CfgFile="C:\\Users\\Akash Singh\\.docker\\machine\\machines\\default\\default\\default.vbox",(default) DBG | SnapFldr="C:\\Users\\Akash Singh\\.docker\\machine\\machines\\default\\default\\Snapshots",(default) DBG | LogFldr="C:\\Users\\Akash Singh\\.docker\\machine\\machines\\default\\default\\Logs",(default) DBG | hardwareuuid="d2371a97-14a7-4158-a9f0-2e51add35f8b",(default) DBG | memory=2048,(default) DBG | pagefusion="off",(default) DBG | vram=8,(default) DBG | cpuexecutioncap=100,(default) DBG | hpet="on",(default) DBG | chipset="piix3",(default) DBG | firmware="BIOS",(default) DBG | cpus=1,(default) DBG | pae="on",(default) DBG | longmode="on",(default) DBG | triplefaultreset="off",(default) DBG | apic="on",(default) DBG | x2apic="off",(default) DBG | cpuid-portability-level=0,(default) DBG | bootmenu="disabled",(default) DBG | boot1="dvd",(default) DBG | boot2="dvd",(default) DBG | boot3="disk",(default) DBG | boot4="none",(default) DBG | acpi="on",(default) DBG | ioapic="on",(default) DBG | biosapic="apic",(default) DBG | biossystemtimeoffset=0,(default) DBG | rtcuseutc="on",(default) DBG | hwvirtex="on",(default) DBG | nestedpaging="on",(default) DBG | largepages="on",(default) DBG | vtxvpid="on",(default) DBG | vtxux="on",(default) DBG | paravirtprovider="default",(default) DBG | effparavirtprovider="kvm",(default) DBG | VMState="poweroff",(default) DBG | VMStateChangeTime="2017-03-09T19:46:17.000000000",(default) DBG | monitorcount=1,(default) DBG | accelerate3d="off",(default) DBG | accelerate2dvideo="off",(default) DBG | teleporterenabled="off",(default) DBG | teleporterport=0,(default) DBG | teleporteraddress="",(default) DBG | teleporterpassword="",(default) DBG | tracing-enabled="off",(default) DBG | tracing-allow-vm-access="off",(default) DBG | tracing-config="",(default) DBG | autostart-enabled="off",(default) DBG | autostart-delay=0,(default) DBG | defaultfrontend="",(default) DBG | storagecontrollername0="SATA",(default) DBG | storagecontrollertype0="IntelAhci",(default) DBG | storagecontrollerinstance0="0",(default) DBG | storagecontrollermaxportcount0="30",(default) DBG | storagecontrollerportcount0="30",(default) DBG | storagecontrollerbootable0="on",(default) DBG | "SATA-0-0"="C:\Users\Akash Singh\.docker\machine\machines\default\boot2docker.iso",(default) DBG | "SATA-ImageUUID-0-0"="bcf5f3f2-c8a0-4629-a8c5-72782ac5602d",(default) DBG | "SATA-tempeject"="off",(default) DBG | "SATA-IsEjected"="off",(default) DBG | "SATA-1-0"="C:\Users\Akash Singh\.docker\machine\machines\default\disk.vmdk",(default) DBG | "SATA-ImageUUID-1-0"="1cc0e4d4-2222-4c64-a558-cea0897ac805",(default) DBG | "SATA-2-0"="none",(default) DBG | "SATA-3-0"="none",(default) DBG | "SATA-4-0"="none",(default) DBG | "SATA-5-0"="none",(default) DBG | "SATA-6-0"="none",(default) DBG | "SATA-7-0"="none",(default) DBG | "SATA-8-0"="none",(default) DBG | "SATA-9-0"="none",(default) DBG | "SATA-10-0"="none",(default) DBG | "SATA-11-0"="none",(default) DBG | "SATA-12-0"="none",(default) DBG | "SATA-13-0"="none",(default) DBG | "SATA-14-0"="none",(default) DBG | "SATA-15-0"="none",(default) DBG | "SATA-16-0"="none",(default) DBG | "SATA-17-0"="none",(default) DBG | "SATA-18-0"="none",(default) DBG | "SATA-19-0"="none",(default) DBG | "SATA-20-0"="none",(default) DBG | "SATA-21-0"="none",(default) DBG | "SATA-22-0"="none",(default) DBG | "SATA-23-0"="none",(default) DBG | "SATA-24-0"="none",(default) DBG | "SATA-25-0"="none",(default) DBG | "SATA-26-0"="none",(default) DBG | "SATA-27-0"="none",(default) DBG | "SATA-28-0"="none",(default) DBG | "SATA-29-0"="none",(default) DBG | natnet1="nat",(default) DBG | macaddress1="080027DDC541",(default) DBG | cableconnected1="on",(default) DBG | nic1="nat",(default) DBG | nictype1="82540EM",(default) DBG | nicspeed1="0",(default) DBG | mtu="0",(default) DBG | sockSnd="64",(default) DBG | sockRcv="64",(default) DBG | tcpWndSnd="64",(default) DBG | tcpWndRcv="64",(default) DBG | Forwarding(0)="ssh,tcp,127.0.0.1,51220,,22",(default) DBG | hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #3",(default) DBG | macaddress2="0800270FDB14",(default) DBG | cableconnected2="on",(default) DBG | nic2="hostonly",(default) DBG | nictype2="82540EM",(default) DBG | nicspeed2="0",(default) DBG | nic3="none",(default) DBG | nic4="none",(default) DBG | nic5="none",(default) DBG | nic6="none",(default) DBG | nic7="none",(default) DBG | nic8="none",(default) DBG | hidpointing="ps2mouse",(default) DBG | hidkeyboard="ps2kbd",(default) DBG | uart1="off",(default) DBG | uart2="off",(default) DBG | uart3="off",(default) DBG | uart4="off",(default) DBG | lpt1="off",(default) DBG | lpt2="off",(default) DBG | audio="dsound",(default) DBG | clipboard="disabled",(default) DBG | draganddrop="disabled",(default) DBG | vrde="off",(default) DBG | usb="off",(default) DBG | ehci="off",(default) DBG | xhci="off",(default) DBG | SharedFolderNameMachineMapping1="c/Users",(default) DBG | SharedFolderPathMachineMapping1="\\?\c:\Users",(default) DBG | vcpenabled="off",(default) DBG | vcpscreens=0,(default) DBG | vcpfile="C:\Users\Akash Singh\.docker\machine\machines\default\default\default.webm",(default) DBG | vcpwidth=1024,(default) DBG | vcpheight=768,(default) DBG | vcprate=512,(default) DBG | vcpfps=25,(default) DBG | GuestMemoryBalloon=0,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter #3,(default) DBG | GUID: 50d8eeb6-d382-44ee-9a0c-a0263a8146ec,(default) DBG | DHCP: Disabled,(default) DBG | IPAddress: 192.168.99.1,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | IPV6Address: fe80:0000:0000:0000:70c1:7c18:5c2f:be22,(default) DBG | IPV6NetworkMaskPrefixLength: 64,(default) DBG | HardwareAddress: 0a:00:27:00:00:07,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Up,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3,(default) DBG | ,(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter,(default) DBG | GUID: e2f9ae73-3115-4566-9df9-023e6f4a0639,(default) DBG | DHCP: Enabled,(default) DBG | IPAddress: 169.254.15.137,(default) DBG | NetworkMask: 255.255.0.0,(default) DBG | IPV6Address: fe80:0000:0000:0000:e5ec:b9c6:f33d:0f89,(default) DBG | IPV6NetworkMaskPrefixLength: 64,(default) DBG | HardwareAddress: 0a:00:27:00:00:15,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Up,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter,(default) DBG | ,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00,(default) DBG | Found: VirtualBox Host-Only Ethernet Adapter #3,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list dhcpservers,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | NetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter,(default) DBG | IP: 192.168.56.100,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | lowerIPAddress: 192.168.56.101,(default) DBG | upperIPAddress: 192.168.56.254,(default) DBG | Enabled: Yes,(default) DBG | ,(default) DBG | NetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3,(default) DBG | IP: 192.168.99.6,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | lowerIPAddress: 192.168.99.100,(default) DBG | upperIPAddress: 192.168.99.254,(default) DBG | Enabled: Yes,(default) DBG | ,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Removing orphan DHCP servers...,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter #3,(default) DBG | GUID: 50d8eeb6-d382-44ee-9a0c-a0263a8146ec,(default) DBG | DHCP: Disabled,(default) DBG | IPAddress: 192.168.99.1,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | IPV6Address: fe80:0000:0000:0000:70c1:7c18:5c2f:be22,(default) DBG | IPV6NetworkMaskPrefixLength: 64,(default) DBG | HardwareAddress: 0a:00:27:00:00:07,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Up,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3,(default) DBG | ,(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter,(default) DBG | GUID: e2f9ae73-3115-4566-9df9-023e6f4a0639,(default) DBG | DHCP: Enabled,(default) DBG | IPAddress: 169.254.15.137,(default) DBG | NetworkMask: 255.255.0.0,(default) DBG | IPV6Address: fe80:0000:0000:0000:e5ec:b9c6:f33d:0f89,(default) DBG | IPV6NetworkMaskPrefixLength: 64,(default) DBG | HardwareAddress: 0a:00:27:00:00:15,(default) DBG | MediumType: Ethernet,(default) DBG | Status: Up,(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter,(default) DBG | ,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Adding/Modifying DHCP server "192.168.99.6"...,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list dhcpservers,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | NetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter,(default) DBG | IP: 192.168.56.100,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | lowerIPAddress: 192.168.56.101,(default) DBG | upperIPAddress: 192.168.56.254,(default) DBG | Enabled: Yes,(default) DBG | ,(default) DBG | NetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3,(default) DBG | IP: 192.168.99.6,(default) DBG | NetworkMask: 255.255.255.0,(default) DBG | lowerIPAddress: 192.168.99.100,(default) DBG | upperIPAddress: 192.168.99.254,(default) DBG | Enabled: Yes,(default) DBG | ,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --nic2 hostonly --nictype2 82540EM --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter #3 --cableconnected2 on,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --natpf1 delete ssh,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --natpf1 ssh,tcp,127.0.0.1,51353,,22,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm default --type headless,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | Waiting for VM "default" to power on...,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3' (VERR_INTNET_FLT_IF_NOT_FOUND).,(default) DBG | VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND),(default) DBG | VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole,(default) DBG | },(default) DBG | Checking vm logs: C:\Users\Akash Singh\.docker\machine\machines\default\default\Logs\VBox.log,Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm default --type headless failed:,VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3' (VERR_INTNET_FLT_IF_NOT_FOUND). ,VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND) ,VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole ,,Details: 00:00:02.533621 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005)),`

**Comment by ZetaoYang** [comment]
@sanjayjare the docker default machine folder at `C:\Users\<Your User Name>\.docker\machine\machines`
![image](https://cloud.githubusercontent.com/assets/10769951/23776203/c224850c-0567-11e7-8864-3e8788d86e97.png)

Please remove `default` folder manually and then reinstall in terminal `C:\DockerToolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default`.

If you network so bad, you could download `boot2docker.iso` manually and then put it into `C:\Users\<Your User Name>\.docker\machine\cache` folder (P.S. the installation process should be so fast) , [the download link](https://github.com/boot2docker/boot2docker/releases/download/v17.03.0-ce/boot2docker.iso)

`C:\DockerToolbox\docker-machine.exe -D start default` start docker in terminal or start it with Kitematic, then please lookup it in your vitualbox.
![image](https://cloud.githubusercontent.com/assets/10769951/23776487/a474392e-0569-11e7-9a1f-831fbc15f192.png)

**Comment by singhakash** [comment]
@ZetaoYang thanks for the help, I tried the command but it gave me

(default) DBG | VBoxManage.exe: error: Failed to open/create the internal networ
k 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3' (VERR_INTNE
T_FLT_IF_NOT_FOUND).
(default) DBG | VBoxManage.exe: error: Failed to attach the network LUN (VERR_IN
TNET_FLT_IF_NOT_FOUND)
(default) DBG | VBoxManage.exe: error: Details: code E_FAIL (0x80004005), compon
ent ConsoleWrap, interface IConsole
(default) DBG | }
(default) DBG | Checking vm logs: C:\Users\Akash Singh\.docker\machine\machines\
default\default\Logs\VBox.log
Error creating machine: Error in driver during machine creation: Unable to start
 the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm default --typ
e headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterface
Networking-VirtualBox Host-Only Ethernet Adapter #3' (VERR_INTNET_FLT_IF_NOT_FOU
ND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_
FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

Details: 00:00:02.253722 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E
_FAIL (0X80004005))
Opting out of crash reporting.

**Comment by ZetaoYang** [comment]
@singhakash you could remove `VirtualBox Host-Only Ethernet Adapter #3` in virtualbox and then reinstall docker `default`.
![image](https://cloud.githubusercontent.com/assets/10769951/23788196/6d208490-05b0-11e7-86e8-d179a62112d5.png)

If your Virtualbox version is too old, please update it to latest.

**Comment by megamindbrian** [comment]
This is not fixed.  Not using virtual box, using a fresh install of Docker.

**Comment by ZetaoYang** [comment]
@megamindbrian  I use Windows system, which can not use both hyper-v and virtualbox, but I need virtualbox to use the Android simulator,genymotion. This is very embarrassing, so I can only use virtualbox to install docker.This solution solved my problem.

**Comment by megamindbrian** [comment]
I just don't want someone to come along and close all of these threads.  I am using Windows 10, Hyper-V installed with Docker CE Stable and MobyLinuxVM listed properly!  It works on my dev computer, but docker-machine ls shows nothing.  It doesn't work on a fresh install.  I can't remember what solution I spent days tracking down when I first installed it.  All of this looks so familiar, but I am lost...

**Comment by GuilhermeHideki** [comment]
@ZetaoYang The Visual Studio Emulator for Android uses hyper-v, so it's possible to use docker and an android emulator

**Comment by megamindbrian** [comment]
I'll try it now that the firewall rule is added. On the computer where
docker works, rocket-like shows nothing like the tool is installed without
anything else.

**Comment by jrajav** [comment]
For anyone running across this issue from googling, this solved it for me:

https://stackoverflow.com/questions/34778147/cannot-boot-windows-guest-in-virtualbox-without-kernel-module-error

**Comment by megamindbrian** [comment]
Using Hyperv not virtual box.

**Comment by jlsjonas** [comment]
@FrenchBen looks like the error message hasn't been updated ;) (@ https://github.com/docker/kitematic/issues/1992#issuecomment-247484800)

![image](https://user-images.githubusercontent.com/932193/43256824-4abe2808-90ce-11e8-99ae-abbe574201ac.png)
