### ISSUE TITLE
unable to retrieve centos6.8 image

### ISSUE THREAD

**Issue by jw34** [docker/kitematic#1993]
### Expected behavior
Download Image
### Actual behavior
Tag latest not found in repository docker.io/644597521/centos6.8
### Steps to reproduce the behavior

  1. ... Install docker, try 
  2. ...install centos6.8 (offiical via kimetic)

**Comment by FrenchBen** [comment]
Make sure that you select the proper tag:
<img width="261" alt="tags" src="https://cloud.githubusercontent.com/assets/3965324/18570502/780b2d8c-7b5f-11e6-8fe1-694347f1e84d.png">


And things work:
<img width="217" alt="centos" src="https://cloud.githubusercontent.com/assets/3965324/18570505/7e6d8aee-7b5f-11e6-96b9-87f95302b0ee.png">
