### ISSUE TITLE
Error while pulling image

### ISSUE THREAD

**Issue by wardcomm** [docker/kitematic#1994]
### Expected behavior
crash
### Actual behavior
error

Error while pulling image: Get https://index.docker.io/v1/repositories/juhofriman/borg/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: no such host
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
