### ISSUE TITLE
Server error: Http code 500

### ISSUE THREAD

**Issue by dongdongqin** [docker/kitematic#2000]
### Expected behavior
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/library/redis/manifests/latest: Get https://auth.docker.io/token?account=dongdongqin\u0026scope=repository%3Alibrary%2Fredis%3Apull\u0026service=registry.docker.io: net/http: TLS handshake timeout"}
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Could be that the connection with the hub was interrupted - Could you retry?
