### ISSUE TITLE
Kitematic can not connect with docker-machine default

### ISSUE THREAD

**Issue by mgoldsman** [docker/kitematic#2001]
### Expected behavior
I want to see my images / containers in the left bar on the kitematic app.

### Actual behavior
kitematic app show empty list en the left bar

### Steps to reproduce the behavior

  1. Start kitematic

**Comment by FrenchBen** [comment]
@mgoldsman Do you have any containers actually created/running? Are you using Docker for Mac/Windows and thus not virtualbox?
A lot more information is needed on your setup in order for us to debug any of this. 

Closing until proper details are given.
