### ISSUE TITLE
bug : server error

### ISSUE THREAD

**Issue by mimo38** [docker/kitematic#2002]
### Expected behavior
download of a container
[https://hub.docker.com/r/musite/musite/](https://hub.docker.com/r/musite/musite/
)
### Actual behavior
error message at 99,3% :

> HTTP code is 500 which indicates error: server error - dial unix /Users/[user]l/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused

**Comment by FrenchBen** [comment]
If this is the only image that it happens with, it could be that the image is broken. Can you confirm that it works with any of the recommended images?

**Comment by mimo38** [comment]
I reinstalled everything, and the bug disappeared. Thanks.
