### ISSUE TITLE
Can't get microsoft/nanoserver image

### ISSUE THREAD

**Issue by mraswinc** [docker/kitematic#2003]
### Actual behavior
Kept retrying when doing docker pull microsoft/nanoserver

### Information about the Issue
unknown blob shown

### Steps to reproduce the behavior

  1. Command "docker pull microsoft/nanoserver"
  2. After sometime, it would timeout and show as unknown blob

**Comment by FrenchBen** [comment]
Although it is not obvious at first, the image does have the following short:
```
Nano Server base OS image for Windows containers
```
This means that unless you're on Windows Pro and have set your preference to be 'use Windows Containers' this image will not work for you.
