### ISSUE TITLE
Multiple ':' (colon characters) in the image name cause the image cannot be deleted

### ISSUE THREAD

**Issue by jverger** [docker/kitematic#2006]
### Expected behavior
When using Kitematic UI, in 'My Images', i want to be able to delete any of my image
### Actual behavior
When using Kitematic UI, in 'My Images', i can't delete an image if there is multiple 'colon' characters
### Information about the Issue
I'm using docker toolbox which provides 'Kitematic'.
I've setup a private registry (https secured) that can be accessed by using 'docker pull' command

### Steps to reproduce the behavior
e.g from my docker toolbox:
# docker pull myregistryhost:443/myimage:latest

So, i've a local image called 'myregistryhost:443/myimage:latest' in my local docker engine.
When i go to the Kitematic UI, i can't delete the image because Kitematic doesn't handle images that have multiple 'colon'

I've to manually tag the image with a name that not contains 'colon' character, so Kitematic can then see the image and is able to delete it.

**Comment by FrenchBen** [comment]
Thanks for reporting the issue - This has previously been reported; closing in favor of: https://github.com/docker/kitematic/issues/1840
