### ISSUE TITLE
Unable to run hello-world from Docker

### ISSUE THREAD

**Issue by hanskumar00** [docker/kitematic#2008]
### Expected behavior
Should be able to run the hello-world app

### Actual behavior
Getting following error:
Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp: lookup index.docker.io on 192.168.65.1:53: no such host

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
