### ISSUE TITLE
Kitematic becomes unresponsive/stuck on launch

### ISSUE THREAD

**Issue by jasdeepsingh** [docker/kitematic#2009]
### Expected behavior

- On launching Kitematic it should work - being responsive and usable.

### Actual behavior

- On launching it goes into a state of unsresponsiveness. ie: Hangs.

### Information about the Issue

- Docker version: Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856

- Kitematic version: Cannot find, as "About Kitematic" menu item is unresponsive too. If there's any other way I can get the version number, please let me know and i'll find it out?

### Steps to reproduce the behavior

  1. Launch Kitematic

Small screen recording of the issue, notice that the cursor in the search bar is hung. I try to click around on various docker images - nothing happens.

![img](http://g.recordit.co/R4A4k1KpNj.gif)

**Comment by jasdeepsingh** [comment]
Update: Noticed that if I wait long enough - 5-10 minutes Kitematic does gain it's responsiveness and usability back.

**Comment by FrenchBen** [comment]
What OS is this on?

**Comment by jasdeepsingh** [comment]
macOS ElCapitan

**Comment by jasdeepsingh** [comment]
Any update?

**Comment by FrenchBen** [comment]
@jasdeepsingh I'm unable to reproduce this at this point - More information is needed from you to understand why this is happening.
