### ISSUE TITLE
Cant able to download elastic search 

### ISSUE THREAD

**Issue by krishnabitmca** [docker/kitematic#2011]
### Expected behavior
I was trying to download elastic search through kitematic.
### Actual behavior
As ealier I was able to download images this time also it should work
### Information about the Issue

Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/elasticsearch/images. You may want to check your internet connection or if you are behind a proxy.
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
