### ISSUE TITLE
nanoserver pulling error

### ISSUE THREAD

**Issue by writetoavi** [docker/kitematic#2019]
### Steps to reproduce the behavior

  1. ...Pull started for Microsoft/nanoserver

  2. ...error in the last failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\fbc146483ed9f9d2b0a54585ad1fc85e8e18c431756b26e1ae9628644afa33e9\UtilityVM: The process cannot access the file because it is being used by another process.

**Comment by FrenchBen** [comment]
Please open an issue here: https://github.com/docker/for-win
