### ISSUE TITLE
an err。I am  window 10 pro 

### ISSUE THREAD

**Issue by Kibos** [docker/kitematic#2021]
### Information about the Issue

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/12/12231e6a3e14470af591124c2f29016640e48ea9b88a52e0ede373b41a5217b6/data?Expires=1475080432&Signature=Bm3Hw2dhOs6ExDOullcf2nF7hvzty8QCqwB1IDnkLHR2zVo9tCNJXG-7sp5tleFGt5ue8mgjT~HeMfIjf3hCZgLMXMMFBpPHJG6IbyUTGFD3-SYDnJappujWh6TrTphZnkHrKzfoUT6GiOYbWHok3V4bzf-dvCPy68EPVG7gUfU_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
it's possible that your connection dropped - Could you retry and I'll re-open this issue if the problem persists.
