### ISSUE TITLE
unable to download "iis" docker image.

### ISSUE THREAD

**Issue by rchhatwal** [docker/kitematic#2026]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Serkan-devel** [comment]
Are you trying to download the iis webserver not on Windows 10 Pro/Enterprise/Server docker host?
If yes then that's why. You can only run linux docker images on docker for mac or linux. Windows containers on the other hand only on windows with docker.

**Comment by FrenchBen** [comment]
@rchhatwal If you look at the hub docs, you'll see that this is a Windows Container image, not linux based:
https://hub.docker.com/r/microsoft/iis/
