### ISSUE TITLE
Tag latest not found in repository docker.io/jpizarrom/spark-yarn

### ISSUE THREAD

**Issue by firemonk9** [docker/kitematic#2027]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
Looks like that image does not have a `:latest` tag on Docker Hub, so either use a specific tag, or ask the author of that image to add a `latest` tag; https://hub.docker.com/r/jpizarrom/spark-yarn/tags/
