### ISSUE TITLE
Can't share C drive

### ISSUE THREAD

**Issue by tommed** [docker/kitematic#2028]
### Expected behavior

Looking to persist data from Redis (via Linux Containers) to a share on my user's Documents folder. Go into Settings and enable C drive for sharing, then press apply, C drive should then be shared and folder in my Documents folder should be used as /data volume in Redis instance.

### Actual behavior

Takes aaaaages to share C drive from settings menu, but then unticks C drive sharing without any error. Try and mount /data from Redis image to my documents and fails (error below).

### Information about the Issue

No error when trying to share C drive, but when I subsequently try and mount /data, I get: "HTTP code is 500 which indicates error: server error - C: drive is not shared. Please share it in Docker for Windows Settings"

### Steps to reproduce the behavior

  1. Go into Settings
  2. Share C drive
  3. Create Redis instance
  4. Attempt to set /data volume to a folder in your user's Documents folder

**Comment by FrenchBen** [comment]
Could you open an issue in github.com/docker/for-win instead?
