### ISSUE TITLE
Docker Installation Issue on MAc

### ISSUE THREAD

**Issue by chintac** [docker/kitematic#2033]
Just installed Docker and verifying the installation with
docker run hello-world

### Expected behavior
hello world image should be imported and docker should say heelo

### Actual behavior
Getting following error
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.65.9:53: dial tcp 192.168.65.9:53: getsockopt: connection refused.
See 'docker run --help'.

### Information about the Issue
I'm getting this issue after installing Docker on Mac
Docker version 1.12.1, build 6f9534c

### Steps to reproduce the behavior

  1. Install Docker on Mac
  2. Run command -> docker run hello-world

I tried to import image from kitematic as well but getting same error for any image

**Comment by FrenchBen** [comment]
Could you open an issue in github.com/docker/for-mac instead?

Thanks
