### ISSUE TITLE
The list of containers is not up-to-date

### ISSUE THREAD

**Issue by michaa76** [docker/kitematic#2038]
### Expected behavior
The list of containers on the left side in GUI is up-to-date, even running container(s) with / in Docker CLI

### Actual behavior
The list of container(s) is not changing, if new docker container(s) are created and running.

### Information about the Issue
Windows 10 x64
Windows-Kitematic

### Steps to reproduce the behavior
  1. Start Kitematic GUI
  2. Create and start container(s) in Docker CLI

### Screenshot
![windows-kitematic](https://cloud.githubusercontent.com/assets/3788410/19146611/82954f16-8bb4-11e6-94b1-0605933ad311.PNG)

**Comment by FrenchBen** [comment]
It's possible that they get out of sync although I haven't been able to track down how - There's a refresh option via CMD+R or CTRL+R on top of the View > Refresh Container list in the menu on the mac. 

If you had time to debug it, it would be of great help as I'm unable to replicate this issue.

**Comment by Joshfindit** [comment]
Also experiencing this issue.
Granted, it feels like I'm stress-testing on the way to learning how docker works

example

```
docker run -p 3000:3000 -it 89b01cdad080 /bin/bash
docker rm 89b01cdad080
docker rm bfb73631c53b
docker rmi 89b01cdad080
docker-compose build
docker-compose up -d
docker run -it 7757a02ada6a /bin/bash
```
And so-on.

Kitematic regularly gets out of sync when new containers are created.
I'm open to troubleshooting.
