### ISSUE TITLE
pull ghost error

### ISSUE THREAD

**Issue by formobi** [docker/kitematic#2044]
### Steps to reproduce the behavior

  1. ...Install KI on mac
  2. ..pull ghost
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/ec/ec55ea2421da4af3b752dadbba8b1c6389565d542f6e8538e513e81f7f07eccf/data?Expires=1476249805&Signature=ZLViUTQm4gWM5l1HBJ2JHeIVZERURc05QaHd-OAIzJh0gH4GqHebOckbJvOvfi0XqitUW7tk5QyL9IA44XhNG3wvEuR-tVnSdck7QaJF-PBi4zDEKffG0TFd6qxQAkc3s1~402HuoDsTb74fvPd2ZSQKsXWKJ9t9WwyQGUgmluw_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: i/o timeout

**Comment by FrenchBen** [comment]
Could you please retry from a solid connection? I can't reproduce the issue here even while tethered to my phone.
