### ISSUE TITLE
get centos image error.

### ISSUE THREAD

**Issue by Vincent2015** [docker/kitematic#2048]
### Expected behavior
get centos image
### Actual behavior
error pulling image configuration:
### Information about the Issue
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/98/980e0e4c79ec933406e467a296ce3b86685e6b42eed2f873745e6a91d718e37a/data?Expires=1476434345&Signature=hZJxnF6OpHYPc9T3SreVwCUiohKFCcEfKTA1~vKvgLQw9tRR-iZKRcIHFSM~ck~LGYjEO91dwB4QDqRtJQSmHyrwdnZt634AaUm4qD0xAyL0iJggvAY6O75CiVn2yjyOXdEp-9q03BDFZimoqP-ZfU1J8hH-fzf5cHHGIbyBEws_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

### Steps to reproduce the behavior
![Uploading 537532BD-67FC-46BA-8092-00B96CA71E44.png…]()

  1. install kitematic
  2.search "centos" ;create the first result

**Comment by FrenchBen** [comment]
Unable to replicate the issue here - Can you check if the image can be pulled via `docker pull ...` and show us the result?
