### ISSUE TITLE
unable to  run the image on ec2

### ISSUE THREAD

**Issue by jpca999** [docker/kitematic#2052]
ive done the security groups setting 
and ports 22 and 80 are open. 

So i downloaded the /kitematic image on ec2  via the command line that i ssh into. 
when i visit  http://52.4.15.69/ 

I dont see anything there. 

ubuntu@ip-172-31-63-36:~$ curl localhost:80

<div style="color: #35393B; margin-top: 100px; text-align: center; font-family: HelveticaNeue-Light, sans-serif;">
  <img src="https://cloud.githubusercontent.com/assets/251292/5254757/a08a277c-7981-11e4-9ec0-d49934859400.png">
  <h2>Voil&agrave;! Your nginx container is running!</h2>
  <div style="color: #838789;">
    <p>To edit files, double click the <strong>website_files</strong> folder in Kitematic and edit the <strong>index.html</strong> file.</p>
  </div>
</div>

**Comment by jpca999** [comment]
stupid keys / security group issue...

**Comment by FrenchBen** [comment]
Feel free to give [Docker for AWS](https://www.docker.com/products/docker#/AWS) a try, so that you don't have to remember these details :)

**Comment by jpca999** [comment]
@FrenchBen  whats the benefit of using Docker for Aws  compared to i can ssh into the aws and give one docker-compose up   ?

**Comment by FrenchBen** [comment]
@jpca999 Docker for AWS and Azure both start a fleet of Docker 1.12 Engines with swarm mode enabled out of the box. Swarm mode means that the individual Docker engines form into a self-organizing, self-healing swarm, distributed across availability zones for durability. 
Docker 1.12 also introduces powerful new concepts for running complex multi-container apps including: Service deployment API with health checks and rolling updates, built-in container-aware load balancing, and node communication secured with TLS out of the box
