### ISSUE TITLE
Does not download container without tags

### ISSUE THREAD

**Issue by rafaelstz** [docker/kitematic#2056]
### When I click in getting container, it show me this image bellow

![screen shot 2016-10-20 at 01 06 13](https://cloud.githubusercontent.com/assets/610598/19544973/711eb9cc-9661-11e6-9409-addf46ada73e.png)

The image is this: https://github.com/clean-docker/PHP-IonCube
Does not have tags.

**Comment by FrenchBen** [comment]
does not have tags = nothing was ever uploaded to that hub repo.
