### ISSUE TITLE
can't download microsoft blobs

### ISSUE THREAD

**Issue by brian-douglas** [docker/kitematic#2058]
### Expected behavior
sql 2014 downloads successfully
### Actual behavior
"unknown blob"  error
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Unless you're using Windows containers, you will not be able to use this image, per their documentation.

**Comment by brian-douglas** [comment]
I was trying to use Windows containers in Docker for Windows.  Windows 10 anniv, not 2016 Server though.

**Comment by FrenchBen** [comment]
Docker for Windows runs linux containers by default - You need to manually enable Windows Containers as the feature. 
Can you provide the output of:
` docker version`

**Comment by brian-douglas** [comment]
I figured it out.   I think I had an old version that probably didn't support Windows containers.   I upgraded to 1.13.0 and now it works.  Thanks!

**Comment by jamesmanning** [comment]
@FrenchBen any chance the error message in this scenario could be improved?  Looking at the closed issues, this seems to crop up for lots of people, and 'unknown blob' during the image download isn't very actionable.  An error message stating that you need to enable Windows Containers would be great! 😄

**Comment by FrenchBen** [comment]
Unfortunately the error comes from Docker and not kitematic - We could do a find/replace, but I'm unsure if this would work as expected. 

Ideally we should switch from hub.docker.com to https://store.docker.com since it allows to filter images by arch
