### ISSUE TITLE
Docker image says "unknown blob": mssql-server-2014-express-windows

### ISSUE THREAD

**Issue by sharpe5** [docker/kitematic#2063]
### Expected behavior

I should be able to install "mssql-server-2014-express-windows" on my Windows 10 Box. All of the other container images work just fine.

### Actual behavior

When I install using Kitematic, it gets to 75%, then says "unknown blob".

### Information about the Issue

-

### Steps to reproduce the behavior

  1. Install Docker for Windows on Windows 10 Professional.
  2. Use Kitematic to install a few images to prove that everything works. I installed Redis, etc.
  3. Try to install "mssql-server-2014-express-windows", it will fail with an error "unknown blob".

I am using:
- docker-machine v0.8.1, 
- Windows 10 N Enterprise N 2016 LTSB (10.0.14393 build 14393)
- Dell Precision T7500 Workstation, x64 with 32GB RAM, and 12 cores.

**Comment by FrenchBen** [comment]
You will need to be using actual Windows Containers to make use of this image, per their documentation.
