### ISSUE TITLE
Unknown Blob

### ISSUE THREAD

**Issue by dwfruman** [docker/kitematic#2065]
### Expected behavior
Using Docker Kitematic to try and pull Microsoft/nanoserver
Using docker powershell command "docker pull Microsoft/nanoserver"

### Actual behavior
Requests to pull time out, and in Kitematic, the request simply times out with "Unknown blob"

### Information about the Issue
Started just after updating to windows 10 build 14393

### Steps to reproduce the behavior

  1. try and command from expected behavior
  2. ...

**Comment by FrenchBen** [comment]
This is a windows container image only - Please see the documentation for this image and the requirements.
