### ISSUE TITLE
Can not found any local image

### ISSUE THREAD

**Issue by szyhf** [docker/kitematic#2068]
### Expected behavior

Display my images
### Actual behavior

Can not found any local image.
### Information about the Issue

If I run "docker images" in [DOCKER CLI], I can see all of my images, but Kitematic can't found, no matter whether the image pull by CLI "docker pull XXX" or by Kitematic.

But all of my container can display properly.

Kitematic used worked well while I first installed, but I don't know what happened and one day it suddenly can't  found any local image, even re-install Kitematic can't help. 
### Steps to reproduce the behavior

I think it can't help.
1. Run "docker create mysql".
1. Open Kitematic and click "my images".
1. Showing "Can not found any local image."
1. Run "docker images" and my images are well displayed in terminal.
1. Use Kitematic to "+ New Image"
2. Still "Can not found any local image."
3. Run "docker images" and my images are well displayed in terminal, too.

Thanks for building this great tools.
## Evn

macOS Sierra 10.12
## Docker Info

Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 38
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 152
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.854 GiB
Name: moby
ID: 7WLT:52PU:T57U:GYSW:I7JH:KA26:HOIN:4CNC:UBRY:3HNW:UZZ2:D4EC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 35
 System Time: 2016-10-25T15:49:05.648618396Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Comment by hj1980** [comment]
I had the same problem, multiple times. Using the very latest docker and kitematic-beta. I've narrowed it down to occurring when I have local images which are not tagged. Once I remove all the untagged images, I see the complete list. Please give that a go and let me know if it works for you.

**Comment by szyhf** [comment]
@hj1980 Thanks a lot, unfortunately, I've got an accident and I have to keep away from my office for few days, I'll try your advice as soon as I come back.
Tanks again !

**Comment by szyhf** [comment]
@hj1980 Thanks a lot!!!! It works, even I don't know how the untagged image occur.

**Comment by vishaltelangre** [comment]
Solution provided by @hj1980 worked for me too.

```
$ docker images
REPOSITORY    TAG        IMAGE ID         CREATED          SIZE
my_image      latest     5180d4d3b45e     22 hours ago     1.14GB
my_image      <none>     6bd77000a8d0     23 hours ago     1.14GB
```

I needed to remove image having `<none>` tag.

```
$ docker rmi 6bd77000a8d0
```

After this, local images started showing in Kitematic app.

**Comment by adamo901** [comment]
I have the same issue even if all my images are tagged

```
$ docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
ps-docker            latest              1eb6ba093d7f        39 hours ago        904MB
ps-docker            test                769a139feac1        39 hours ago        929MB
python-docker        latest              769a139feac1        39 hours ago        929MB
python-docker        test                769a139feac1        39 hours ago        929MB
node                 latest              9ff38e3a6d9d        2 days ago          904MB
tomcat               latest              dd6ff929584a        4 days ago          463MB
python               latest              32260605cf7a        5 days ago          929MB
airhacks/developer   latest              0b0670b99b7e        13 days ago         582MB
airhacks/coffee      latest              b01439d5d281        2 weeks ago         611MB
payara/server-full   latest              c09b64de4009        2 weeks ago         807MB
airhacks/wildfly     latest              3781f7ea3a79        5 weeks ago         611MB
hello-world          latest              fce289e99eb9        2 months ago        1.84kB
airhacks/payara      latest              5b4ab90b1227        2 months ago        582MB
```

**Comment by systemsincode** [comment]
I had the same issue but with all images tagged. I had put my machine (mbp) to 'sleep' but on boot Docker had restarted and worked on CLI. Closing Kinematic and then Restarting Docker. The 'start Kinematic' fly-out on the Docker Control drop down didn't re-start kinematic, I had to start it in the application folder directly. Then it found my existing images:)

**Comment by nackdai** [comment]
I had the same issue. I followed same things which were posted here, but I can't fix.

Ubuntu : 16.04
Docker : 18.09.6
Kitematic : 0.17.7

**Comment by nicolabeghin** [comment]
Any hint on this? experiencing the same issue on latest Ubuntu and Kitematic
