### ISSUE TITLE
features stop containers, manage ports and deployments ?

### ISSUE THREAD

**Issue by sallespro** [docker/kitematic#207]
hei huys, great job, lots of bugs and minor improvements.

the Important stuff from my perspective are 

1.  to save resources and run a couple of containers while some others are just stopped.

2. choose the ports mapped in mac.

3. to publish your docker in a self hosted docker server, or third parties who offer docker image hosting.

**Comment by trezm** [comment]
:+1:

**Comment by mainiak** [comment]
:+1:

**Comment by yakovkhalinsky** [comment]
Duplicate of #164

**Comment by tslater** [comment]
+1

**Comment by yborunov** [comment]
Voting for stopping container opportunity

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
