### ISSUE TITLE
i can not pull a image from  https://registry-1.docker.io/

### ISSUE THREAD

**Issue by OXDAF** [docker/kitematic#2072]
### Actual behavior
i can not pull a image from  https://registry-1.docker.io/
### Information about the Issue
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/library/mysql/manifests/latest: Get https://auth.docker.io/token?account=*******\u0026scope=repository%3Alibrary%2Fmysql%3Apull\u0026service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

###

**Comment by FrenchBen** [comment]
Looks like your timeout was too big when pulling - Please try this again from a solid connection.
