### ISSUE TITLE
Lost commit changes when edit port mapping in container setting.

### ISSUE THREAD

**Issue by bdh92123** [docker/kitematic#2074]
### Expected behavior
preserve commit changes after editting port mapping.
### Actual behavior
lost commit changes after editting port mapping.
### Information about the Issue
To edit port mapping in existing container, I try following command without Kitematic.

$ docker stop container01
$ docker commit container01 image01
$ docker rm container01
$ docker run -d -p 80:80 --name container01 image01

I know this needs temporary image and isn't graceful but it worked as I expected. Commit changes lost only when using Kitematic.

### Steps to reproduce the behavior

1. Download ubuntu image for test and start container as 'ubuntu'.

  `$ docker run -it --name ubuntu ubuntu /bin/bash`

2. touch testfile in /root directory.

  `$ touch /root/testfile`

3. Commit image.

  `$ docker commit ubuntu`

4. In Kitematic, change port setting (in my case, I added 80:80 mapping)
5. Container will be restarted by Kitematic.
6. testfile in /root directory doesn't exists.

**Comment by MonkeyTonk** [comment]
What happened to this one as I seem to be facing this issue?
