### ISSUE TITLE
wnews-sling fails to download / install

### ISSUE THREAD

**Issue by dfparker2002** [docker/kitematic#2075]
### Expected behavior
docker pull wnews/wnews-sling
install wnews-sling @ https://hub.docker.com/r/wnews/wnews-sling

### Actual behavior
WEB: 
Error while pulling image: Get https://index.docker.io/v1/repositories/wnews/wnews-sling/images: dial tcp: lookup index.docker.io on [2001:4860:4860::8888]:53: dial udp [2001:4860:4860::8888]:53: connect: network is unreachable

or 

CLI:
$ docker pull wnews/wnews-sling
Using default tag: latest
Pulling repository docker.io/wnews/wnews-sling
Error while pulling image: Get https://index.docker.io/v1/repositories/wnews/wnews-sling/images: dial tcp: lookup index.docker.io on [2001:4860:4860::8888]:53: dial udp [2001:4860:4860::8888]:53: connect: network is unreachable

### Steps to reproduce the behavior

  1. Kitematic find wnews-sling
  2. click "create"

**Comment by FrenchBen** [comment]
Are you on IPV6? We currently only support IPV4
