### ISSUE TITLE
kitematic not open in windows 10

### ISSUE THREAD

**Issue by IsmaTeddy** [docker/kitematic#2076]
I install "DockerToolbox-1.12.2.exe" [windows 10] and execute "kitematic (Alpha)", I hope kitematic run. but nothing, not up or fails. no message.

I had never happened to me. I have it installed on other PCs with Windows 10
I reinstall and nothing.
I can see log?

¿?
THANKS!

**Comment by FrenchBen** [comment]
Do you have a screenshot? Can you try to open it in powerShell so that we can perhaps see some debug output?

**Comment by IsmaTeddy** [comment]
![kitematic power shell](https://cloud.githubusercontent.com/assets/19637084/19800301/74520cd4-9cfb-11e6-937e-da9e47bc96fd.jpg)

I expect ten minutes and nothing....

**Comment by FrenchBen** [comment]
Are you familiar with Node/NPM? It would be good to see it compiled on your machine to see what the issue is.

**Comment by IsmaTeddy** [comment]
Thanks FrenchBen.
Yes, I have installed npm. that command requires or suggests

**Comment by FrenchBen** [comment]
Can you clone the project then do:
```
npm install
npm start
```

**Comment by IsmaTeddy** [comment]
![node](https://cloud.githubusercontent.com/assets/19637084/19828114/d6b8de3a-9dbd-11e6-80e0-6667779c8e9a.jpg)

You suggest reinstall node/npm?

**Comment by IsmaTeddy** [comment]
![kitematic-electron](https://cloud.githubusercontent.com/assets/19637084/19924940/4b72bf7e-a0ee-11e6-8970-8f4741585fb3.jpg)

I install electron and reinstall & start....
this error (picture).

**Comment by FrenchBen** [comment]
@IsmaTeddy I don't see any obvious errors from the screenshot you provided. Does kitematic not come up after the last line?

**Comment by IsmaTeddy** [comment]
@FrenchBen Kitematic not run,  i wait but nothing... Can be by the "docker CLI" ,  
I dont know the reason and I dont know where to look. any ideas?

**Comment by FrenchBen** [comment]
What build of Windows 10 are you on?

**Comment by IsmaTeddy** [comment]
Windows 10 Home

**Comment by FrenchBen** [comment]
@IsmaTeddy I'm not sure if I understand - What env variables have you used?

**Comment by IsmaTeddy** [comment]
I'm sorry for my language. If you understand correctly. I don't have any but I don't know if kitematic need any ...

**Comment by FrenchBen** [comment]
Kitematic doesn't need any, unless you have VPN settings

**Comment by IsmaTeddy** [comment]
I havent vpn settings.

**Comment by FrenchBen** [comment]
@IsmaTeddy A pre-release was set in our code. Do you mind checking if this one is working for you?
\

**Comment by IsmaTeddy** [comment]
You say this version: kitematic-0.13.0-RC1  ???¿¿
I 

![image](https://cloud.githubusercontent.com/assets/19637084/20317392/20128ba2-ab66-11e6-9647-c3dd6a5de934.png)

**Comment by FrenchBen** [comment]
You shouldn't have to do an npm start - If you download the latest release from here: https://github.com/docker/kitematic/releases/tag/v0.13.0-RC1
there should be a `Kitematic.exe`

**Comment by IsmaTeddy** [comment]
@FrenchBen 
Nothing, this version does the same as the previous one, it does not make it work or gives error ....
I had open a request in electron for the error with which kitematic ends, but I was told that this error is here and not in electron since I can do electron and if I put that version inside the kitematic modules I get the window but In gray colo not with kitematic blue and its containers ....

(Thanks)

https://github.com/electron/electron/issues/7965

**Comment by FrenchBen** [comment]
@IsmaTeddy Could you provide your exact Windows version and any customization - I'm unable to replicate this issue across 3 different VM

**Comment by IsmaTeddy** [comment]
![image](https://cloud.githubusercontent.com/assets/19637084/20619216/9826d1e0-b2f3-11e6-927e-956b8937f2f7.png)

My npm version is 2.14.7
Docker toolbox version 1.12.2
Oracle vm virtual box 5.1.16

**Comment by wildloop** [comment]
We solved this problem by uninstalling this software:

- LavasoftTcpService `C:\Program Files (x86)\Lavasoft\Web Companion\TcpService\2.3.4.7\LavasoftTcpService.exe`
- WebCompanion `C:\Program Files (x86)\Lavasoft\Web Companion\Application\WebCompanion.exe`
- cryptoCertum Scanner `C:\Program Files (x86)\Unizeto\proCertum CardManager\cryptoCertumScanner.exe`

We don't know which one exactly helped... but in your case it could be something else.
So, you have to do some investigation on your own:

- download and unzip [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) 
- stop any program that you don't need at this moment (to avoid hype)
- run Process Monitor and start capturing all events
- run Kitematic and wait for about 15 seconds
- stop capturing (magnifier icon)
- analyse logs... (use excluding/including filters, ctrl+f,...)

We found something like this:

> Kitematic.exe, Operation: ReadFile, Path: C:\Windows\System32\LavasoftTcpService64.dll
> Kitematic.exe, Operation: ReadFile, Path: C:\Program Files (x86)\Lavasoft\Web Companion\TcpService\2.3.4.7\LavasoftTcpService.exe
> ...

---------

There is something else that may be helpful for someone. 
I our case Kitematic.exe showed the main window when was started as a windows service generated by [Process Hacker](http://processhacker.sourceforge.net/) (even while it doesn't work as a normal windows process). But, Kitematic executed as a windows service didn't work properly with Docker/VirtualBox :(

![kitematic-as-a-service](https://cloud.githubusercontent.com/assets/2461648/22501277/6aa5edaa-e868-11e6-8968-269ab1a8db09.png)

HTH
Best regards from Lublin@Poland :)

**Comment by FrenchBen** [comment]
@wildloop Thanks for sharing your findings! 👍

**Comment by IsmaTeddy** [comment]
@wildloop @FrenchBen  THANKS!!

I solved the problem by idea @wildloop , i unistall Ad-Aware (lavasoft), I dont remember install it....
@FrenchBen close the issue if you like.

Greetings and thanks again!

**Comment by FrenchBen** [comment]
Happy to hear this was resolved for you @IsmaTeddy 🎉
