### ISSUE TITLE
Cannot start kitematic on Manjaro Linux: Error: connect ENOENT /var/run/docker.sock

### ISSUE THREAD

**Issue by sysadmin1337** [docker/kitematic#2080]
### Expected behavior

Start or give me a useful error message so I can troubleshoot the issue. 
### Actual behavior

Loading Kitematic gives me a setup error:

```
We're Sorry!
There seems to have been an unexpected error with Kitematic:
Error: connect ENOENT /var/run/docker.sock
```
### Information about the Issue

Running on Manjaro linux installed through the [AUR](https://aur.archlinux.org/packages/kitematic/). Changed `.bashrc` and `.bash_profile` to point to docker machine. Both contain:

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/home/user/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
```
### Steps to reproduce the behavior
1. Install Kitematic with pamac or yaourt
2. Start Kitematic
3. See error

**Comment by FrenchBen** [comment]
Shouldn't you have docker installed natively for Manjaro Linux? 
Kitematic assumes that Docker is running locally on Linux and not under a virtualbox setup.

**Comment by sysadmin1337** [comment]
Your correct, natively it works without boot2docker. Problem solved.
