### ISSUE TITLE
Enabling Volumes prevents container from properly starting

### ISSUE THREAD

**Issue by juxtaposed** [docker/kitematic#2081]
### Expected behavior

When I start a Jenkins image with volumes enabled, it should map the directory specified in the volumes configuration to my host machine's location
### Actual behavior

Whenever I start up the container with volumes enabled, this is the error I get; 

```
touch: cannot touch ‘/var/jenkins_home/copy_reference_file.log’: Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
```
### Steps to reproduce the behavior
1. Start up Kitematic 
2. Pull the Jenkins image from the Recommended images list
3. start up the container.
4. Click on "/var/jenkins_home" in the lower right hand corner in the Volumes panel
5. Click on "Enable" in the dialog that pops up.
6. Watch the container restart with the error.

**Comment by FrenchBen** [comment]
This can be solved by using Docker for Mac/Windows. The issue is linked to volumes with Virtualbox.

**Comment by juxtaposed** [comment]
I found the opposite to be true. Docker on Windows 10 using Hyper-V exhibit this problem. As soon as I switched to the Virtual Box version of docker that comes packaged with Kitematic, volumes work fine.

**Comment by FrenchBen** [comment]
@juxtaposed Can you open an issue with [Docker for Windows](https://github.com/docker/for-win/issues)?

**Comment by juxtaposed** [comment]
@FrenchBen Sure, np.

**Comment by zinklandi** [comment]
What's the solution? I run into the same problem.
I'm running a cassandra database and enabled the volume. Now the database won't start. Im also using the VirutalBox on my Windows system.

Thanks for your help! :)
