### ISSUE TITLE
windowsservercore doesn't download and install correctly

### ISSUE THREAD

**Issue by tomgron** [docker/kitematic#2082]
### Expected behavior

New ->windowsservercore -> install -> function
### Actual behavior

New ->windowsservercore -> install starts -> "unknown blob"
### Information about the Issue

Only info from kitematic was "unknown blob"
### Steps to reproduce the behavior
1. ...
2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
