### ISSUE TITLE
addition of " docker-opensips "" image onto Kitematic onMacOS Sierra 10.12.1 failed

### ISSUE THREAD

**Issue by alisajjad** [docker/kitematic#2083]
### Steps to reproduce the behavior
1. ...launch the Kitematic on mac os x 
2. ... try to add the image "" docker-opensips  ""

**Comment by FrenchBen** [comment]
Are you on Docker for Mac?
It looks like you ran out of space and need to clean some of the images you've already downloaded. 
This can be done easily via:
`docker rmi $(docker -q images)`
This will remove all images that aren't associated with a container. 

Images will be re-downloaded as needed for future containers.
