### ISSUE TITLE
cannot navigate the app

### ISSUE THREAD

**Issue by dearfrankg** [docker/kitematic#2085]
### Expected behavior
I expect to navigate between image catalog and container info
I expect 'show tab bar' to show something

### Actual behavior
I have no way to navigate between image-catalog and container-view

the view tab bar option shows only a small line

### Steps to reproduce the behavior

1. from the whale toolbar menu choose "open kitematic"
2. see containers on the left and app-search on the right
3. click a container on the left 
4. no way to navigate back to app-search

1. choose view -> show tab bar
2. notice the only change is a thin line.

**Comment by FrenchBen** [comment]
@dearfrankg you can navigate back to the `app-search` by clicking on `New`
It's assumed you're trying to create a "New" container and thus becomes the default action.

**Comment by dearfrankg** [comment]
Thanks
