### ISSUE TITLE
Kitematic - internet connectivity issue

### ISSUE THREAD

**Issue by rchhatwal** [docker/kitematic#2086]
### Information about the Issue: Possible internet connectivity issue. How do I configure Kitematic, Docker to use proxy?
![kitematic_error](https://cloud.githubusercontent.com/assets/15172771/19871436/4755a956-9f8b-11e6-83fd-aa2429327176.jpg)

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
