### ISSUE TITLE
Can't downlaod container in China

### ISSUE THREAD

**Issue by hanyou** [docker/kitematic#2087]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
What image are you trying to download? We've recently announced a partnership with Alibaba, which should help with the download issues:
https://blog.docker.com/2016/10/docker-announces-expansion-china-commercial-partnership-alibaba-cloud/

**Comment by Murriouz** [comment]
Same here while trying to download ubuntu image.

**Comment by FrenchBen** [comment]
@Murriouz see the above.

A temporary solution is here:
https://github.com/denverdino/aliyungo/wiki/Speed-Up-Docker-Access-In-China
