### ISSUE TITLE
index

### ISSUE THREAD

**Issue by heigc** [docker/kitematic#2089]

**Comment by heigc** [comment]
<html>
	<head><title>Mission</title>
		<style type="text/css">
		body {
			background-color: #d2b48c;
			margin-right: 20%;
			margin-left: 20%;
			border: 2px dotted black;
			padding:10px 10px 10px 10px;
			font-family: sans-serif;
		}
		</style>
		</head>
	<body>
		<H1>Starbuzz Coffee's Mission</H1>
		<p>To provide all the caffeine that you need to power your life</p>
		<p>just drink it</p>
	</body>
</html>

**Comment by FrenchBen** [comment]
No information provided - Closing
