### ISSUE TITLE
[BUG] macOS : Windows manager (split view)

### ISSUE THREAD

**Issue by Parnoud** [docker/kitematic#2102]
### Expected behavior
Launch the windows manager from macOS Sierra (tested on version 10.12.1) by hold click the green 
button in the left corner (with the two arrow):
<img width="237" alt="capture d ecran 2016-11-07 a 20 56 48" src="https://cloud.githubusercontent.com/assets/18117703/20073508/d08cb7a4-a52c-11e6-8a46-b37d1dde2966.png">

### Actual behavior
Nothing happend, you can just run the full screen by clicking one time.

### Information about the Issue
If you try to add the Kinematic's window in the split view (Windows Manager), Hold the green button (like before) from a another windows, like Google Chrome and click, after moving the windows on the left or right side, on the Kinematic window.
It's working ! The split view is working !

### Steps to reproduce the behavior

  1. Launch Kinematic app from the launchpad
  2. Open a second app who support the split view (like Google Chrome)
  3. Click and hold the green button from the Kinematic window

Nothing happend, the windows manager start.

**Comment by FrenchBen** [comment]
There's a PR related to the title bar action:
https://github.com/docker/kitematic/pull/1559

Care to share your findings there, so that we keep all comments related to it there?
