### ISSUE TITLE
Create microsoft nanoserver returns "unknown blob" error

### ISSUE THREAD

**Issue by timhibberd** [docker/kitematic#2103]
### Expected behavior

Create Microsoft nanoserver container which is listed in the Kitematic repository

### Actual behavior

returns "unknown blob" error

### Information about the Issue

Operational Kitematic on windows 10 pro computer with Docker for Windows installed and Linux containers successfully launched from the Kitematic repository, successfully running and successfully manageable via this Kitematic installation

### Steps to reproduce the behavior

  1. Try to install Microsoft nanoserver

NOTE: Same error if you try to create container from windowsservercore image

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
