### ISSUE TITLE
error pulling image configuration with latest build

### ISSUE THREAD

**Issue by tsal** [docker/kitematic#2113]
### Expected behavior
Pull python:3 container image and spin up.
### Actual behavior
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/a3/a399f3670068b420aa832694f0c1472a3f34a44d497661440ab810afb8842302/data?Expires=1478913560&Signature=dr-yNjrO0WDNj~zqG0kmeDolxdw6ica3pCXjlfG8GFNKMcW0toOUBJxQFkMqp39mIJ-tkNnYxJCIuGLONLar4uuIxSjiD~ZH~Qp3ErdwVYTYBNf-jcmrrJV9h54ftzl9jaki-zxHhvCNs3xKaDFpCEn9doG0qDyF4CDzt5VQ0DM_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: no such host
### Information about the Issue
Latest update installed today.

### Steps to reproduce the behavior

  1. Select tag "3" under official python image
  2. Profit?

**Comment by FrenchBen** [comment]
Can you provide the version of Docker for Mac in use and also the diagnostic output?

**Comment by sugun999** [comment]
Hi,

I also getting same error when trying to pull MySQL image

Using default tag: latest
latest: Pulling from mysql/mysql-server
2c48edfee2a0: Pulling fs layer
5b0458647b73: Pulling fs layer
4de0b63848ea: Pulling fs layer
ca5c82ea0c88: Waiting
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/7d/7de18fc4344c458a8a062714dcaae11aed00e58c68c9981ac0a6d66df26389eb/data?Expires=1485331713&Signature=P7gBrZhONO7O3RX1ZYer-H0waJaPD5zU2W347bAPLRLnDwFM8rx2LW4whC-YSk~MC6Mx1ZZoQ6LSY6s9IVhsY14jUn6BKeoo-z9Etse49QHEJY0dCCGUiJ57tvCf6B3LDVRwlY9743Mqn81GLTl2MmsKsr7F~WWyxTClc9F082w_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: no such host

Windows native docker version:

Docker version 1.13.0, build 49bf474

Windows version:

Windows 10 enterprise build 14393

**Comment by FrenchBen** [comment]
There were a few DNS issues that were found and fixed in the latest Beta version of Docker for Windows.
You can update to the latest Beta and get the fix or wait for it to be added to stable
