### ISSUE TITLE
Redis Container - Unable to download thru Kitematic.

### ISSUE THREAD

**Issue by avidunixuser** [docker/kitematic#2116]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please provide version information and env details - I'm able to do it all using Docker for Mac and the latest kitematic setup

**Comment by avidunixuser** [comment]
0.12.0 seem to work fine now. I'm able to get Redis.Rethink and Solr images. Thx.
