### ISSUE TITLE
Need to warn lost changes uncommitted when container setting is changed.

### ISSUE THREAD

**Issue by bdh92123** [docker/kitematic#2117]
### Expected behavior
Warn user before changing container's setting makes lost uncommitted changes.
### Actual behavior
All changes in container lost when container setting is changed.
### Information about the Issue
I know that kitematic removes container and recreate when container's setting was changed. It makes lost uncommitted data in container, but kitematic doesn't show any warning about this.

### Steps to reproduce the behavior

  1. Make any change in the container.
  2. Change port mapping in the container setting and save.
  3. Changes in the container is removed.

**Comment by FrenchBen** [comment]
Why are you making changes to the container directly? 
In reality I don't think there's a way for us efficiently monitor user changes within the container. 
I'm open to suggestions as to how you see this working

**Comment by VivekRagunathan** [comment]
Not sure if there was resolved or if there is a workaround. I use kitematic to make changes to the container (ports etc.)

Normally you run an image to create a container C, and make file changes (apt-get install etc) in C. You exit C but changes are still available in C unless you create a new container out of C or the original image. But if you make changes via Kitematic (or any changes like ports etc. to C), all changes in C are lost, which is weird. Not a unreasonable expectation, eh?

Is there a workaround?

**Comment by FrenchBen** [comment]
@VivekRagunathan When you make changes to C, you're making changes within the container. When you use Kitematic to make changes, you're essentially changing the container configuration which will spawn a new container.
There is no dynamic option for container config update.
