### ISSUE TITLE
NO space on the file error

### ISSUE THREAD

**Issue by unndevops** [docker/kitematic#2121]
$ docker run -it ubuntu bash
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: mkdir /mnt/sda1/var/lib/docker/aufs/mnt/967ca9baf5e43ce2148fd49c8933c65723f81bb5f1003f845970cf5f1accd825-init: no space left on device.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by FrenchBen** [comment]
Either remove unused images/volumes or create a new VM with more disk space:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
