### ISSUE TITLE
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\docker\windowsfilter\b079907e1457581f355f9a6f251781d3553bd438b774099d768d40c697ca02a7: The system cannot find the path specified.

### ISSUE THREAD

**Issue by huacixu** [docker/kitematic#2124]
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\docker\windowsfilter\b079907e1457581f355f9a6f251781d3553bd438b774099d768d40c697ca02a7: The system cannot find the path specified.

**Comment by FrenchBen** [comment]
No information provided - Closing
