### ISSUE TITLE
Unable to download any image

### ISSUE THREAD

**Issue by danlebbe** [docker/kitematic#2131]
### Expected behavior
After launching the toolbox docker (kitematic), I would download an image.
### Actual behavior
There seems to be an error.

### Information about the Issue
Error while pulling image: Get https://index.docker.io/v1/repositories/alexeiled/docker-oracle-xe-11g/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: no such host

### Steps to reproduce the behavior

  1. Launch kitematic
  2. Try to download image "docker-oracle-xe-11g:latest

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by danlebbe** [comment]
Hello FrenchBen,
As I'm behind a corporate firewall, I'll follow your wiki to fixe my issue.
Thank for your help.
