### ISSUE TITLE
Error executing action `run` on resource 'ruby_block[directory resource: /var/opt/gitlab/git-data]'

### ISSUE THREAD

**Issue by gifer** [docker/kitematic#2133]
/opt/gitlab/embedded/bin/runsvdir-start: line 24: ulimit: pending signals: cannot modify limit: Operation not permitted
/opt/gitlab/embedded/bin/runsvdir-start: line 34: ulimit: max user processes: cannot modify limit: Operation not permitted
/opt/gitlab/embedded/bin/runsvdir-start: line 37: /proc/sys/fs/file-max: Read-only file system
Configuring GitLab...
================================================================================
Error executing action `run` on resource 'ruby_block[directory resource: /var/opt/gitlab/git-data]'
================================================================================
2016-11-19T03:46:04.376858907Z 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Failed asserting that ownership of "/var/opt/gitlab/git-data" was git
---- Begin output of set -x && [ "$(stat --printf='%U' $(readlink -f /var/opt/gitlab/git-data))" = 'git' ] ----
STDOUT: 
STDERR: + readlink -f /var/opt/gitlab/git-data

**Comment by FrenchBen** [comment]
No information provided or steps to replicate - Closing

**Comment by MadLittleMods** [comment]
See https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2280
