### ISSUE TITLE
Error while pulling image: Get https://index.docker.io/v1/repositories/library/redis/images: dial tcp: lookup index.docker.io on 192.168.65.1:53: server misbehaving

### ISSUE THREAD

**Issue by vimalprakashts** [docker/kitematic#2138]
Error while pulling image: Get https://index.docker.io/v1/repositories/library/redis/images: dial tcp: lookup index.docker.io on 192.168.65.1:53: server misbehaving

**Comment by FrenchBen** [comment]
No information provided or steps to replicate - Closing
