### ISSUE TITLE
Unable to `docker pull bde2020/hive`

### ISSUE THREAD

**Issue by blahster** [docker/kitematic#2142]
### Expected behavior
Able to pull bd2020/hive
### Actual behavior
Not able to pull bde2020/hive
### Information about the Issue
On the terminal, I see
```
f5eedb46fcd1: Downloading
dial tcp: i/o timeout
```

### Steps to reproduce the behavior

  1. On terminal `docker pull bde2020/hive`
  2. On Kitematic "create" bde2020/hive

**Comment by FrenchBen** [comment]
if the terminal is unable to pull the image, Kitematic will have a similar issue. 

Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by blahster** [comment]
Uninstalling and installing Docker for mac beta worked.
Thank you.
