### ISSUE TITLE
Error when pulling microsoft/aspnet

### ISSUE THREAD

**Issue by azzlack** [docker/kitematic#2144]
### Expected behavior
Able to pull `microsoft/aspnet`

### Actual behavior
Received error `unknown blob`

### Information about the Issue
N/A

### Steps to reproduce the behavior

  1. Run `docker pull microsoft/aspnet`
  2. Observe it fail

**Comment by Serkan-devel** [comment]
Are you trying to install it on Linux?

**Comment by Serkan-devel** [comment]
probably a duplicate of https://github.com/docker/kitematic/issues/2026 due to asp.net based on iis https://github.com/Microsoft/aspnet-docker/blob/master/4.6.2/Dockerfile

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
