### ISSUE TITLE
Error installing the official image

### ISSUE THREAD

**Issue by liuyi61123** [docker/kitematic#2145]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by liuyi61123** [comment]
# Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/ubuntu/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
