### ISSUE TITLE
pull image for ngix using kinematic does not work

### ISSUE THREAD

**Issue by amygeojo** [docker/kitematic#2146]
### Information about the Issue

Error while pulling image: Get https://index.docker.io/v1/repositories/library/postgres/images: http: error connecting to proxy http:////:localhost/: dial tcp :80: getsockopt: connection refused

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
No information provided to replicate the issue - Closing
