### ISSUE TITLE
Error while connecting to Docker Hub

### ISSUE THREAD

**Issue by rambabusaravanan** [docker/kitematic#2151]
### Information about the Issue
Attempt 1:
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/rambabusaravanan/docker-whalesay/manifests/latest: read tcp 10.0.2.15:58184-\u003e52.45.33.149:443: read: connection reset by peer"}

Attempt 2:
error pulling image configuration: read tcp 10.0.2.15:35986->54.230.175.216:443: read: connection reset by peer

**Comment by FrenchBen** [comment]
I would try from a solid connection - It seems that you're getting some disconnects while pulling files.
