### ISSUE TITLE
trying to get an image (Kitematic Beta)

### ISSUE THREAD

**Issue by asloan7** [docker/kitematic#2155]
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/ba/baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3/data?Expires=1480445658&Signature=aKcTn7KsDu4dVLyDoRmcTnANlPcsFVI5DK7hwD7P-LQT2nG5mBgfbN7awWmu6oTw6V0W41TNBdmm2XCXF00zaiPXKEifepjMJMlyezaaCHSkxth9l7fU0O~vTrpC0AAT-W5iHWwcRdTtlQ8B43mnNxxVDmzG231xLFsDJk7kSBA_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: x509: certificate signed by unknown authority

### Steps to reproduce the behavior
  1. hit Create button!

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
