### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by gaborkorodi-hms** [docker/kitematic#2159]
### Expected behavior
laravel-starter.latest image installation
### Actual behavior
Received an error "Tag latest not found in repository docker.io/realpage/laravel-starter"
### Information about the Issue
Mac OS X

### Steps to reproduce the behavior
Select laravel-started on Kitematic(Beta) is unable to install the image.
<img width="1477" alt="screen shot 2016-12-01 at 10 46 28 am" src="https://cloud.githubusercontent.com/assets/17987657/20800479/a1671282-b7b3-11e6-9b36-e32226556a24.png">

**Comment by FrenchBen** [comment]
Works as expected - there is no existing latest tag: https://hub.docker.com/r/realpage/laravel-starter/tags/
