### ISSUE TITLE
Cann't create jenkins container in China

### ISSUE THREAD

**Issue by Wanghuayin** [docker/kitematic#2174]
### Expected behavior
Set up the jenkins container
### Actual behavior
error message:
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fjenkins%3Apull\u0026service=registry.docker.io: dial tcp: lookup auth.docker.io on 10.0.2.3:53: read udp 10.0.2.15:40926-\u003e10.0.2.3:53: i/o timeout"}

### Information about the Issue
Kitematic 0.12.0

### Steps to reproduce the behavior

  1. Click [NEW] button
  2. Click jenkins->[CREATE]

**Comment by FrenchBen** [comment]
What happens if you go to a terminal and type:
```
docker pull jenkins
```
