### ISSUE TITLE
Couldn't install ubuntu

### ISSUE THREAD

**Issue by rahulreddyv** [docker/kitematic#2176]
### Expected behavior
I am planning to replicate an amazon ec2 server on the local machine as a staging server to deploy the code locally, before deploying it on the server.
### Actual behavior
One of the mirrors that's pulling the ubuntu image is not dowloading
### Steps to reproduce the behavior

  1. `docker pull ubuntu`
Sending build context to Docker daemon 663.6 kB
Step 1 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
af49a5ceb2a5: Pulling fs layer 
8f9757b472e7: Pulling fs layer 
e931b117db38: Pulling fs layer 
47b5e16c0811: Waiting 
9332eaf1a55b: Waiting 
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/4c/4ca3a192ff2a5b7e225e81dc006b6379c10776ed3619757a65608cb72de0a7f6/data?Expires=1481021541&Signature=DHijjhgbfs3Pk2aPhBkHEY5XKOJlo9LicfsrWtzwtFmZ2giLWkbWWuMgVbUBwRk2~-eWPiowU3cbNvT8bBDGVsYUzBEK6qBWHe~obbuJtVUNJtpVB57cUNRys7uzonyWWcKfUBzeH2FCsbmL-9MbhgtNi9qXu5XHZpUSU4LBy5s_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.230.191.74:443: i/o timeout

  2. When I ran it again, it downloaded from 4 mirrors(deamons) and then stops at the 5th mirror
Sending build context to Docker daemon 663.6 kB
Step 1 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
af49a5ceb2a5: Pull complete 
8f9757b472e7: Pull complete 
e931b117db38: Pull complete 
47b5e16c0811: Pull complete 
9332eaf1a55b: Downloading 
dial tcp: i/o timeout

Please help me out

**Comment by FrenchBen** [comment]
Please make sure that you have a solid connection and proper DNS - I would use Google's DNS as they are always reliable.
