### ISSUE TITLE
Unable to pull microsoft/nanoserver

### ISSUE THREAD

**Issue by djcarter** [docker/kitematic#2178]
### Expected behavior
pull image from docker hub

### Actual behavior
pull request times out

### Information about the Issue
unable to pull this image all day.  have successfully pulled other images.

### Steps to reproduce the behavior

C:\Users\me>docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver

5496abde368a: Retrying in 1 second
482ab31872a2: Downloading
unknown blob

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
