### ISSUE TITLE
Installing workflowgen

### ISSUE THREAD

**Issue by Sanpkn** [docker/kitematic#2179]
### Expected behavior
Install workflowgen
### Actual behavior
Unknown Blob
### Steps to reproduce the behavior

  1. ...just pull workflowgen docker image
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
