### ISSUE TITLE
Cannot connect to docker repository

### ISSUE THREAD

**Issue by tulous** [docker/kitematic#2184]
### Expected behavior
From kitematic, search redis, choose official, click install. Expected latest redis docker images downloaded.
### Actual behavior
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images. You may want to check your internet connection or if you are behind a proxy.
### Information about the Issue
Have try with different network. When accessing via browser just [] returned. 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ananthulasrikar** [comment]
Even I have the same problem. I tried multiple times :(

**Comment by tulous** [comment]
Have solved this, change setting of the DNS of docker service to google dns. Seems the default dns setting did have problem

**Comment by ananthulasrikar** [comment]
should i change the DNS of container or system DNS ?

**Comment by FrenchBen** [comment]
@ananthulasrikar sounds like your system DNS is at cause here - I would change the DNS lookup to be that of Google and check if it fixes the problem for you.

**Comment by ananthulasrikar** [comment]
I configured the Google DNS. It works now. Thanks so much !
