### ISSUE TITLE
Cakephp docker failed

### ISSUE THREAD

**Issue by masteramuk** [docker/kitematic#2186]
### Expected behavior
Able to create docker for cakephp
### Actual behavior
Failed with following error:
Tag latest not found in repository docker.io/occitech/cakephp
### Information about the Issue
Not available

### Steps to reproduce the behavior

  1. Search for cakephp
  2. Click on create for occitech cakephp docker image

**Comment by thaJeztah** [comment]
Looks like that repository does not have a `:latest` tag, so you will have to specify a specific tag to use https://hub.docker.com/r/occitech/cakephp/tags/

<img width="263" alt="screen shot 2016-12-10 at 18 06 43" src="https://cloud.githubusercontent.com/assets/1804568/21074843/78797c96-bf03-11e6-9dcc-e0256f52d642.png">

<img width="273" alt="screen shot 2016-12-10 at 18 06 28" src="https://cloud.githubusercontent.com/assets/1804568/21074844/7ef93138-bf03-11e6-8965-783514a78f89.png">

However, be aware that this is not an "official" CakePHP image, and looking at the readme here; https://github.com/occitech/docker/tree/master/cakephp/2.x#how-to-use, and the content of the 3.x Dockerfile in that same repository, CakePHP itself is _not_ installed in that image, it's just a basic Apache / PHP image, and you have to add the CakePHP source or your project source code yourself
