### ISSUE TITLE
##unauthorized: authentication required

### ISSUE THREAD

**Issue by abhaykumarin** [docker/kitematic#2189]
### Steps to reproduce the behavior

  1. ...Create wordpress instance from official wordpress image
  2. ...and I got an error - unauthorized: authentication required after 50% of download.

Thank you,
Abhay Kumar.

**Comment by FrenchBen** [comment]
Can you re-try to download and create new container?

**Comment by abhaykumarin** [comment]
Hi FrenchBen,

I tried again and it worked.

Thank you,
Abhay Kumar.
