### ISSUE TITLE
container ID changed after save setting info

### ISSUE THREAD

**Issue by wyzwhp** [docker/kitematic#2190]
### Steps to reproduce the behavior

  1. chang setting container name
  2. container ID change

**Comment by FrenchBen** [comment]
This behaves properly - When you change settings, kitematic re-creates a new container with the provided settings.
Containers cannot be modified once created. Why are you relying on the Container ID?

**Comment by wyzwhp** [comment]
thanks

**Comment by sowork** [comment]
If the container ID is modified, the `docker-compose up` will not be able to start the previous container

**Comment by sowork** [comment]
>Docker website description:
> https://docs.docker.com/compose/overview/#multiple-isolated-environments-on-a-single-host
Preserve volume data when containers are created
Compose preserves all volumes used by your services. When docker-compose up runs, if it finds any containers from previous runs, it copies the volumes from the old container to the new container. This process ensures that any data you’ve created in volumes isn’t lost.
