### ISSUE TITLE
`galaxy-rnacommender` container not downloading

### ISSUE THREAD

**Issue by nuno-agostinho** [docker/kitematic#2192]
### Expected behavior
Download `galaxy-rnacommender` container.

### Actual behavior
When trying to download this container, it shows: `HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/gianlucacorrado/galaxy-rnacommender/manifests/latest: read tcp 10.0.2.15:56990-\u003e52.0.191.83:443: read: connection reset by peer"}`

### Steps to reproduce the behavior

  1. Open Kinematic
  2. Search for **galaxy-rnacommender**
  3. Click **Create** and this error will appear

**Comment by FrenchBen** [comment]
Make sure that you're on a solid connection with a good DNS (something like google's DNS works well)
