### ISSUE TITLE
not workin in windows 10 and docker for windows

### ISSUE THREAD

**Issue by njss** [docker/kitematic#2193]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
@njss could you give this RC3 a try?
https://github.com/docker/kitematic/releases/tag/v0.13.0-RC3

**Comment by 2bon** [comment]
me too 
![image](https://cloud.githubusercontent.com/assets/13090885/21299369/c5290208-c54f-11e6-9a70-56535dcffca0.png)
Command failed: C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.8.2, build e18a919,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:59932,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:59936,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.1.10r112026,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Hyper-V is not installed.,(default) DBG | %!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)COMMAND: wmic cpu get VirtualizationFirmwareEnabled,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | VirtualizationFirmwareEnabled ,(default) DBG | FALSE ,(default) DBG | ,(default) DBG | },Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory",open C:\Users\RickX\.docker\machine\machines\default\default\Logs\VBox.log: The system cannot find the path specified.,notifying bugsnag: [Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"],

**Comment by 2bon** [comment]
thx

**Comment by FrenchBen** [comment]
@2bon the error is shown in the logs:
```
"This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"
```

**Comment by LightCC** [comment]
This issue is still present.  I'm running on Windows 10 with Docker for Windows, and that runs on Hyper-V.  When I try to run Kinematic (it unzips to "Kinematic for Windows") I get an error message that VirtualBox is not installed - please install it with the Docker Toolbox. The Docker toolbox is specifically for the legacy support of Windows prior to the Docker for Windows that runs on Hyper-V. One cannot run both VirtualBox and Hyper-V at the same time.

I haven't been able to find it in the documentation anywhere - but does Kinematic support the new Docker for WIndows Hyper-V virtualization method?  I can't tell if this is a defect or currently unsupported feature (enhancement request).  It would seem this is the planned way to support Docker on Windows going forward, but that may not be realistic considering that it requires Windows Pro, so the millions of users with Windows Home editions would still need to use Virtualbox.

**Comment by FrenchBen** [comment]
@LightCC can you verify that `docker run hello-world` works from the command line?
Additionally if you had Kitematic previously setup with Toolbox, you will need to click the `reset` button first.

**Comment by LightCC** [comment]
Thanks FrenchBen,

Okay - I thought everything was working, both Linux mode and Windows mode (I was following a Pluralsight course), but now looking at this hello-world only appears to run in Linux mode.  When I switch to Windows containers, I get the following error trying to run hello-world:

> Unable to find image 'hello-world:latest' locally
> latest: Pulling from library/hello-world
> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: image operating system "linux" cannot be used on this platform.
> See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

I have not installed Docker Toolbox or Kinematic before.  Fresh Docker installs on Windows 10 Pro with Hyper-V.  In the Hyper-V Manager, I have `MobyLinuxVM` with a state of `Running`.  Not sure if I should be able to connect to the VM, but that fails when I try.

So... it does look like something else is wrong, at least with Windows containers.

**Comment by FrenchBen** [comment]
`hello-world` is a linux container, I assumed that's what you were running. 
If you're running Windows containers then try:
`docker run microsoft/dotnet-samples:dotnetapp-nanoserver`

**Comment by LightCC** [comment]
Okay, got that now (I didn't realize the OS type worked that way) - thanks.  The dotnetapp-nanoserver is working fine.

If I switch to linux containers, I can run hello-world fine.  In both cases, Kinematic gives me the same error as above (i.e. "Virtualbox is not installed", etc.)

**Comment by FrenchBen** [comment]
You may need to reset Kitematic in order for it to pickup the changes.
