### ISSUE TITLE
Error downloading sitewhere docker file

### ISSUE THREAD

**Issue by uxout** [docker/kitematic#2195]
### Expected behavior
Download Sitewhere docker image file.
### Actual behavior
Impossible to download.
### Information about the Issue
Sitewhere/sitewhere:1.8.0

### Steps to reproduce the behavior
docker pull sitewhere/sitewhere:1.8.0

**Comment by FrenchBen** [comment]
Please have a solid internet connection and good DNS - We use Google's DNS and never had any issue.
