### ISSUE TITLE
Error downloading mssqlserver-server-windows-express:latest

### ISSUE THREAD

**Issue by dansand71** [docker/kitematic#2196]
### Expected behavior
Able to download and launch SQL Server 2016 express container

### Actual behavior
Error at approximately 70% complete - "Unknown Blob"

### Steps to reproduce the behavior

  1. download mssqlserver-server-windows-express:latest

![docker error for mssqlserver express](https://cloud.githubusercontent.com/assets/19396639/21183247/18736fa8-c1d5-11e6-8611-70a91942055b.png)

  2. error @ 70% complete

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
