### ISSUE TITLE
download microsoft/aspnet fail

### ISSUE THREAD

**Issue by GeniusQ** [docker/kitematic#2202]
### Expected behavior
download microsoft/aspnet
### Actual behavior
unknown blob
### Information about the Issue
no other infos

### Steps to reproduce the behavior

  1. click new button
  2. search microsoft/aspnet
  3. click create button

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
