### ISSUE TITLE
Is there a way to start kitematic using other host?

### ISSUE THREAD

**Issue by raphaklaus** [docker/kitematic#2205]
### Information about the Issue

When I start Docker, in Hyper-V I notice a VM called "mobylinux" which I dont know how to ssh into it. So I create a new VM via `docker-machine create`, but Kitematic seems to not understand and gives 500 server error.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Kitematic has been built to look for Docker native environment such as the one created by Docker for Windows or Docker for Mac. 
There is currently no way to target a different environment
