### ISSUE TITLE
applicationsights image creation fails

### ISSUE THREAD

**Issue by volkanp** [docker/kitematic#2207]
### Expected behavior

The container to download and run within Kitematic for Windows.

### Actual behavior

failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\d48783036e7c6053200598fd980bdf9a8a717d6f09571b9203e825d4409c87ca\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label syntax is incorrect. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\d48783036e7c6053200598fd980bdf9a8a717d6f09571b9203e825d4409c87ca\usr\share\man\man3\Locale::gettext.3pm.gz
### Information about the Issue

failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\d48783036e7c6053200598fd980bdf9a8a717d6f09571b9203e825d4409c87ca\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label syntax is incorrect. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\d48783036e7c6053200598fd980bdf9a8a717d6f09571b9203e825d4409c87ca\usr\share\man\man3\Locale::gettext.3pm.gz

### Steps to reproduce the behavior

1. On a Windows 10 - Docker 1.13.0-rc3-beta33 (9442) running Windows containers (mode) search for images in public Docker Hub repo.
2. Find and hit Create on applicationinsights:latest tag.
3. Download will run up to 99.5% and fail with the verbose error information.
4. Docker images command returns no images and as the message implies the path to store the image cannot be found/created/referenced incorrectly.

**Comment by FrenchBen** [comment]
Looks like an issue with the image - Please open the issue with repo owner of the image you're trying to run.
