### ISSUE TITLE
Chrome development tools enabled

### ISSUE THREAD

**Issue by Javirln** [docker/kitematic#2210]
### Expected behavior
Although the current released is still in beta, under my point of view the developer tools window shouldn't be enabled.
### Actual behavior
Chromium developer tools is enabled.
### Steps to reproduce the behavior

  1.  Load the application
  2. Go to **View** -->**Toggle Chromium Developer Tools**

**Comment by FrenchBen** [comment]
@Javirln I'm not sure if that really hurts anything and is quite convenient to help people debug the application when something goes wrong. 
If you feel strongly about it, feel free to open a PR :)
