### ISSUE TITLE
Unable to pull

### ISSUE THREAD

**Issue by praveenprabharavindran** [docker/kitematic#2211]
docker pull microsoft/aspnet:1.0.0-rc1-update1-core
### Expected behavior
The image "microsoft/aspnet:1.0.0-rc1-update1-core" gets installed correctly

### Actual behavior
I am getting the following error:
Network timed out while trying to connect to https://index.docker.io/v1/repositories/raduporumb/aspnetcore-rc1-update1/images. You may want to check your internet connection or if you are behind a proxy.

### Information about the Issue

docker pull microsoft/aspnet:1.0.0-rc1-update1-core
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
