### ISSUE TITLE
Nano Server Image - Microsoft

### ISSUE THREAD

**Issue by WILLEM-LENS** [docker/kitematic#2215]
### Steps to reproduce the behavior

  1. Microsoft Nano Server Image Download - Error: unknown blob
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
