### ISSUE TITLE
try to run meteor in docker container

### ISSUE THREAD

**Issue by docono** [docker/kitematic#2216]
### Expected behavior
just build a container and let it run fine.

### Actual behavior
can not run container in docker.

```
You are attempting to run Meteor as the 'root' superuser. If you are
developing, this is almost certainly *not* what you want to do and will likely
result in incorrect file permissions. However, if you are running this command
in a build process (CI, etc.), or you are absolutely sure you know what you are
doing, set the METEOR_ALLOW_SUPERUSER environment variable or pass
--allow-superuser to proceed.
Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:
  sudo chown -Rh <username> .meteor/local
```

### Information about the Issue
I installed meteor (NOT AS ROOT OR WITH SUDO). Docker installed too. Both run's on a Mac with OSX Sierra.

**Meteor:**
Version: 1.4.2.3
Path: /usr/local/bin/meteor

**Docker:**
Version: 1.12.5, build 7392c3b
Path: /usr/local/bin/docker

I have tried different images including **kadirahq/meteord**, **danieldent/meteor**, **meteorhacks/meteord**

I have also removed .meteor several times and installed it in different Versions always the same result.

Any idea or suggestions for me what i have to do? I like to run the docker container later in a jelastic enviroment.

Thanks in advance

**Comment by FrenchBen** [comment]
@docono changing meteor locally will not fix this issue - By default all containers run with root - You can specify a different user at run-time, but that user needs to exist with the image you specify. 
None of the images you listed above seem to have added a user other than root. 
You can do easily do this with: 
https://docs.docker.com/engine/reference/builder/#user

If you don't care to build a new image, you can set the env var `METEOR_ALLOW_SUPERUSER` as specified above in Kitematic under Settings > General tab, then adding it to the list of Environment.

On a side note I created a simple meteor project using the `danieldent/meteor` image without any issue:
Create project without installing meteor locally
```
docker run -it -v $PWD:/app danieldent/meteor meteor create myapp
```
Check that everything worked (local folder):
```
$ cd myapp
$ ls
myapp.css  myapp.html myapp.js
```
Create a new container in Kitematic using the above image. Then go to the Volume (under setttings) and use the above created `myapp` folder.
Output from the kitematic console log:
![console](https://cloud.githubusercontent.com/assets/3965324/21620940/adcf85d8-d1ab-11e6-901c-71b55400858c.png)

I never added the `METEOR_ALLOW_SUPERUSER` env variable. I am also using [Docker for Mac](https://www.docker.com/products/docker#/mac)
