### ISSUE TITLE
Port number settings resets to empty value after save

### ISSUE THREAD

**Issue by kodivasanth** [docker/kitematic#2217]
### Expected behavior
Under the ports tab, the port number assigned should be saved.
### Actual behavior
After adding the port numbers.  If you navigate to another tab and come back to ports tab, all values are lost
### Steps to reproduce the behavior

  1. Set the port values for docker and localhost
  2. Save.  The VM will restart.
 3.  Click on Advanced Tab and return to the Ports tab.

**Comment by FrenchBen** [comment]
If you don't click 'Save' the ports will not be retained
