### ISSUE TITLE
No about screeen or version

### ISSUE THREAD

**Issue by quole** [docker/kitematic#2218]
Desktop apps usually have an _about_ screen, where users can check the version number of the application. Version numbers are useful to check for updates or when reporting bugs like this one.

I'm running the latest version, installed from `DockerToolbox-1.12.5.exe`. (`Kitematic.exe` lists its "Product version" as `0.12.0` within the file's properties.)

**Comment by FrenchBen** [comment]
There's a PR in-progress to add similar menus to Windows - Feel free to comment there. 
Thanks for the feedback!
