### ISSUE TITLE
unknown blob?

### ISSUE THREAD

**Issue by hengsoheak** [docker/kitematic#2220]
### Steps to reproduce the behavior
<img width="478" alt="screen shot 2559-12-26 at 10 17 45 pm" src="https://cloud.githubusercontent.com/assets/812528/21483731/ffc8e5f2-cbb9-11e6-832c-b7acb3b10b23.png">

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
