### ISSUE TITLE
why can't add Volumes by using kitematic?

### ISSUE THREAD

**Issue by luxin88** [docker/kitematic#2221]
I'm trying to add a Volume, but the tool do not have any button I can add, I have to add volumes by using command line like this
```
docker run --name nginx2 -v ~/Documents/docker/conf/nginx/:/etc/nginx/:ro -v ~/Documents/code/:/home/nginx/:ro -d nginx:stable
```

but it makes too much trouble.

if Kitematic can add a volume easy as add a port?

**Comment by FrenchBen** [comment]
You can add a volume, as long as the image exposes the volume - Some PR had added the ability to add any volume, but there are currently stale.

**Comment by dvdnhm** [comment]
if the command line can do it, the app should be able to do it.. what is the point of having an apache or nginx container without volume?
