### ISSUE TITLE
Doesn't work properly on high resolution screens on windows

### ISSUE THREAD

**Issue by myuseringithub** [docker/kitematic#2222]
Text in Kitmatic app doesn't scale even if windows scaling is increased. i.e. the app structure increases in size but text size is fixed ! Should be relative to the system text size settings.  Using a high resolution screen makes too small to read from a distance. 
E.g. Text on "container logs" doesn't scale at all.

Thanks

**Comment by FrenchBen** [comment]
We currently do not have this on our roadmap; feel free to open a PR that fixes this, it would be much appreciated :)
