### ISSUE TITLE
Search for ubuntu recommends deprecated image

### ISSUE THREAD

**Issue by dansailer** [docker/kitematic#2223]
### Expected behavior
When searching for ubuntu, Kitematic should recommend the officially supported and maintained Ubuntu container image.

### Actual behavior
While the official ubuntu image is the first one to appear in the "other repositories" list of all ubuntu images, the recommended image is ubuntu-upstart which is according to their readme "this image is officially deprecated (especially now that Upstart is no longer the default init system for Ubuntu) and will receive no further updates. Please adjust your usage accordingly."

### Information about the Issue
Kitematic should not recommend deprecated images even though they are official.

### Steps to reproduce the behavior

  1. Search for "ubuntu"

**Comment by FrenchBen** [comment]
We rely on the hub repo owners to provide that information and make no assumptions as to what latest or version x.x.x should be.
