### ISSUE TITLE
Connection refused issue :(

### ISSUE THREAD

**Issue by TrilokDevda** [docker/kitematic#2226]
### Expected behavior
download image .
### Actual behavior
Error while pulling image: Get https://index.docker.io/v1/repositories/trilokdev/suppcolliimepics/images: dial tcp 52.207.178.113:443: getsockopt: connection refused
### Information about the Issue
Connection refused on a proxy network.

### Steps to reproduce the behavior

  1. Open tool.
  2. Go to your docker image.
  3. Try to pull your image.

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
