### ISSUE TITLE
Message "unauthorized: authentication required" when try to command: docker pull ypandit/hdp-spark

### ISSUE THREAD

**Issue by pepihno** [docker/kitematic#2227]
I try the command:
docker pull ypandit/hdp-spark

The download start but after 60% download a receive the massage "unauthorized: authentication required"

My Docker version is:
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64

Installed on a windows 10 machine.

**Comment by FrenchBen** [comment]
I'm unable to replicate this on my end - Could you re-try and comment here if it fails?
