### ISSUE TITLE
Kitematic for use with Docker for Mac, not with Virtual Box

### ISSUE THREAD

**Issue by rick02840** [docker/kitematic#2228]
### Expected behavior
Is there a version of Kitematic to download that runs directly with Docker for Mac, rather than requiring Virtual Box and/or Docker Toolbox?

### Actual behavior
All instructions say to download Docker Toolbox to get Kitematic, but you don't want to download that if you are using Docker for Mac right?

### Information about the Issue
I swear I have had this working - Kitematic with Docker for Mac only, where I can see containers started with docker-compose up in Kitematic - but cannot recall where/how I downloaded Kitematic from to do that.  (setting up a new Mac)

### Steps to reproduce the behavior
  1. Search for ways to get Kitematic without Docker Toolbox
  2. Cannot find

**Comment by rick02840** [comment]
BTW Kitematic version is 0.12.0 and I got it by clicking the link in the Docker for Mac icon (the spouting whale icon at top of Mac window).  As I recall, a link to get Kitematic appears in a popup if you click the 'Open Kitematic" link in that Docker icon and you do not have Kitematic installed yet.  

So anyhow...   shortly after I posted above I seem to have it running OK.  

At first it was asking for Virtual Box to be installed.  I did that, as I needed it anyhow.  Then Kitematic would start, but showed none of the containers I had created with docker-compose up.  Guessing because it is looking for containers in the VM not in Docker for Mac.

Anyhow, I shut down Virtual Box and started Kitematic again.  It briefly shows the screen when it is starting up the VM, but then loads the main interface and I can see the containers I had created.  So, guess it's working for now. 

I see Kitematic as sort of like a Git GUI - not necessary, since everything can be done on command line - but nice to have a visual of what's going on.

**Comment by FrenchBen** [comment]
@rick02840 From the `Whale` menu in your mac status bar, you should see 'Open Kitematic' - If kitematic isn't installed, it will provide you with the proper download location.
Another way to do this is to download the DMG directly from this repo, under the https://github.com/docker/kitematic/releases

**Comment by lebedeanastasija** [comment]
This installation requires docker toolbox for Docker Desktop.
