### ISSUE TITLE
docker-cloud installation fail?

### ISSUE THREAD

**Issue by Downes** [docker/kitematic#2229]
### Expected behavior

C:\Users\downess>docker-cloud -v
docker-cloud 1.0.0

### Actual behavior
C:\Users\downess>docker-cloud -v
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\dockercloud\api\auth.py", line 56, in load_from_file
    out = p.communicate(input=HUB_INDEX)[0]
  File "c:\program files\anaconda3\lib\subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "c:\program files\anaconda3\lib\subprocess.py", line 1306, in _communicate
    self._stdin_write(input)
  File "c:\program files\anaconda3\lib\subprocess.py", line 1012, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\Scripts\docker-cloud.exe\__main__.py", line 5, in <module>
  File "c:\program files\anaconda3\lib\site-packages\dockercloudcli\cli.py", line 7, in <module>
    import dockercloud
  File "c:\program files\anaconda3\lib\site-packages\dockercloud\__init__.py", line 31, in <module>
    basic_auth = auth.load_from_file("~/.docker/config.json")
  File "c:\program files\anaconda3\lib\site-packages\dockercloud\api\auth.py", line 58, in load_from_file
    raise dockercloud.AuthError('error getting credentials - err: exec: "%s": executable file not found in $PATH, out: ``' % cmd)
dockercloud.api.exceptions.AuthError: error getting credentials - err: exec: "docker-credential-wincred": executable file not found in $PATH, out: ``

### Information about the Issue

Same error occurs using native Windows command prompt and the Kitematic PowerShell. If there is any other place this command should be run, it is not discoverable by me.

### Steps to reproduce the behavior

On a Windows 10 install on Dell XPS (Core i7 quad)
  1. Install Docker for Windows
  2. Install Anaconda Python
  3. In command prompt, pip install docker-cloud  or
  4. In power shell docker run dockercloud/cli -h

Note that this sequence works fine and I can successfully log in:
C:\Users\downess> docker login
Username: user
Password:
Email: user@example.org
Login succeeded!

FYI:

C:\Users\downess>pip install -U docker-cloud
Requirement already up-to-date: docker-cloud in c:\program files\anaconda3\lib\site-packages
Requirement already up-to-date: requests<3,>=2.5.2 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)
Requirement already up-to-date: python-dockercloud<2,>=1.0.8 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)
Requirement already up-to-date: six<2,>=1.3.0 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)
Requirement already up-to-date: tabulate<1,>=0.7 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)
Requirement already up-to-date: future<1,>=0.15.0 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)
Requirement already up-to-date: ago<0.1,>=0.0.6 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)
Requirement already up-to-date: python-dateutil<3,>=2 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)
Requirement already up-to-date: PyYAML<4,>=3 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)
Requirement already up-to-date: websocket-client<1,>=0.32.0 in c:\program files\anaconda3\lib\site-packages (from docker-cloud)

Also, I have a properly configured Docker account running. See http://hello-world-1cdc2a5d-1.2d9ac8f4.cont.dockerapp.io:32768/

**Comment by FrenchBen** [comment]
This doesn't relate to Kitematic at all - Can you open an issue with the proper repo: 
https://github.com/docker/for-win/issues
