### ISSUE TITLE
Windows Server Core Returning Unknown Blob

### ISSUE THREAD

**Issue by shivamvermainfobeans** [docker/kitematic#2231]
### Actual behavior
unknown blob
### Information about the Issue
When pulling the image of windowsservercore it is returning the message unknown blob

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
