### ISSUE TITLE
Error while pulling image: Get https://index.docker.io/v1/repositories/jboss/drools-workbench-showcase/images: dial tcp 0.0.1.65:443: connect: invalid argument

### ISSUE THREAD

**Issue by selvakumarEsra** [docker/kitematic#2233]
### Expected behavior
Want to pull docker image
### Actual behavior
Unable to login to docker hub

### Information about the Issue
Error while pulling image: Get https://index.docker.io/v1/repositories/jboss/drools-workbench-showcase/images: dial tcp 0.0.1.65:443: connect: invalid argument #2233

i am getting above error when trying to pull an docker image

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
