### ISSUE TITLE
Tab autocomplete and arrows not working in exec shell

### ISSUE THREAD

**Issue by mtrtm** [docker/kitematic#2239]
### Expected behavior
Would expect to be able to use arrow keys, tabs etc. to interact with bash

### Actual behavior
When trying tab completion, it either actually tabs the cursor.  When trying for last command, ^[[A is put in

### Information about the Issue
Just want to be able to interact with the shell like I normally would if I was native in linux

### Steps to reproduce the behavior
  1. On Windows 10 box with Docker and Kitematic, download/start an Ubuntu container
  2. Click EXEC, launches a shell in powershell.exe
  3. type ls
  4. hit the up arrow, see it put in weird characters. Delete all gibberish.
  5. type "cd /lib6" and then hit the tab.  See the cursor tab instead of autocomplete to lib64

**Comment by FrenchBen** [comment]
I'm unable to replicate this - It must be something with your Powershell setup. (win10 pro with Docker for Windows)
![alpine](https://cloud.githubusercontent.com/assets/3965324/21625726/e13cf5f2-d1c1-11e6-8332-37cb25500586.png)


Please do share your findings once you find the settings that were changed.

**Comment by twocs** [comment]
As @FrenchBen has described in other issue reports, the bash shell is not opened by default, but the sh shell. Powershell does not interact properly with the sh shell so you should switch to bash. I am adding this text to the FAQ:

> Kitematic uses sh for the Exec function. This can cause unwanted behavior, such as up arrows being displayed as '^[[A' in Powershell terminal. This is unavoidable, because not all docker containers have a bash shell (or csh, zsh, etc.). One way to use the bash shell, which does not have these limitations, is simply to type "bash" into the terminal each time that a new session is started.
> 
> If you want your bash shell to be the default shell for when you 'exec' into the container, then in Settings > Advanced, simply add an entry for SHELL with a value of /bin/bash. [[1]]( https://github.com/docker/kitematic/issues/1022)
