### ISSUE TITLE
bethgelab/jupyter-deeplearning: "Account is not Active"

### ISSUE THREAD

**Issue by ryandisaskara** [docker/kitematic#2243]
Error: Status 403 trying to pull repository bethgelab/jupyter-deeplearning: "Account is not Active"
Error When Downloading the bethgelab/jupyter-deeplearning Image

**Comment by FrenchBen** [comment]
There's a good chance you signed in using your hub account, but failed to actually activate your Docker account. 
Please login to Docker Cloud: https://cloud.docker.com and activate the account.
