### ISSUE TITLE
I have a mysql docker to build my website, After I change the data volumes, The data all lose! 

### ISSUE THREAD

**Issue by zoorz** [docker/kitematic#2244]
### Expected behavior
Move the mysql data volume from the docker container to local volume
### Actual behavior
I losed all my build webiste data.
### Information about the Issue
The database was losted. I can't restore my database.

### Steps to reproduce the behavior

  1. build a wordpress container and mysql container. I didn't configure the database volume  map to local volume.
  2. After I build my website，And wan't to backup my database. I configure the volume, and map it to the local volume. And the container restart.
  3. The mysql database return to default. and I lost my data.

Is't possible to restore the database.

**Comment by Diluka** [comment]
@zoorz I had just imagined a few days ago what to do if this happened
use `docker volume ls` to find out with volume is the old one, then mount it to a new mysql container using `-v <YOUR VOLUME ID>:/var/lib/mysql`
better make a backup before you try this

**Comment by zoorz** [comment]
@Diluka Thanks a lot! That really help me. I have restore the database from the default volume.

**Comment by FrenchBen** [comment]
@zoorz Please read the docs on managing data with Docker:
https://docs.docker.com/engine/tutorials/dockervolumes/
