### ISSUE TITLE
Not able to download docker image for kibana

### ISSUE THREAD

**Issue by tarunendra** [docker/kitematic#2247]
### Expected behavior
Kitematic should be able to add Kibana docker image.
### Actual behavior
getting below error message - 
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/kibana/images. You may want to check your internet connection or if you are behind a proxy.
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by FrenchBen** [comment]
Additionally please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
