### ISSUE TITLE
starter-kit docker not found in repository

### ISSUE THREAD

**Issue by jeremyder** [docker/kitematic#2251]
Tag latest not found in repository docker.io/oprudkyi/laravel-bootstrap-adminlte-starter-kit

**Comment by FrenchBen** [comment]
Open an issue with the image owner - https://hub.docker.com/r/oprudkyi/laravel-bootstrap-adminlte-starter-kit/tags/ `latest` doesn't exist. 
In the meantime, you can select one of the other tags to get the container created.
