### ISSUE TITLE
docker pull chipgarner/opencv3-webcam not working

### ISSUE THREAD

**Issue by huiyingShen** [docker/kitematic#2252]
### Steps to reproduce the behavior

 C:\> docker pull chipgarner/opencv3-webcam
Using default tag: latest
Pulling repository docker.io/chipgarner/opencv3-webcam
Tag latest not found in repository docker.io/chipgarner/opencv3-webcam

**Comment by FrenchBen** [comment]
That's the expected behavior, as no tag of `latest` exists within the repo:
https://hub.docker.com/r/chipgarner/opencv3-webcam/tags/

Please open an issue with the image owner.
