### ISSUE TITLE
Error while pulling image: Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:40882->[::1]:53: read: connection refused

### ISSUE THREAD

**Issue by sumitkute** [docker/kitematic#2255]
### Information about the Issue
Error while pulling image: Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:40882->[::1]:53: read: connection refused

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by sumitkute** [comment]
There was a problem in my docker installation, it got fixed. I restarted the system and it started working. I am working behind firewall, thanks for the help
