### ISSUE TITLE
Mainfest not found

### ISSUE THREAD

**Issue by cynoxure** [docker/kitematic#2256]
### Information about the Issue

HTTP code is 404 which indicates error: undefined - {"message":"manifest for fgrehm/eclipse:latest not found"}

### Steps to reproduce the behavior

  1. select fgrehm/eclipse from Kitematic
  2. ...

**Comment by FrenchBen** [comment]
https://hub.docker.com/r/fgrehm/eclipse/tags/ - there are no `latest` tags
