### ISSUE TITLE
Authentication error while downlo

### ISSUE THREAD

**Issue by abhaykumarin** [docker/kitematic#2264]
### Expected behavior
I should be able download and create minecraft image from docker hub.
### Actual behavior
I am getting error - unauthorised : authentication required
### Information about the Issue
Error screenshot is attached

### Steps to reproduce the behavior

  1. Click create button in Kitematics for minecraft official image and I get authentication error after 70% download.
![docker minecraft error](https://cloud.githubusercontent.com/assets/24223770/21963971/0c9bfb98-db69-11e6-8e36-a062b70ff1af.png)

  2. ...

**Comment by FrenchBen** [comment]
Did you login to Docker Hub on the first Kitematic screen? There's a good chance your account needs to be verified:
Login here to do so: https://cloud.docker.com

**Comment by abhaykumarin** [comment]
Hi French Ben,

The issue has been resolved now. Docker icon used to come in my system tray once I log into my machine (mac) and I find myself logged into Kitematic when I open the Kitematic from the system tray docker icon drop down. 

I logged out for Kitematic, closed the docker and restarted the machine. I didn’t find the issue in my new login.

Thank you,
Abhay Kumar.
