### ISSUE TITLE
readthedocs missing latest tag

### ISSUE THREAD

**Issue by tartarini** [docker/kitematic#2265]
### Expected behavior
regular pulling of docker container.

### Actual behavior
Error message:
"Tag latest not found in repository docker.io/readthedocs/build"

### Information about the Issue
the "latest" tag is missing, available only tags with ubuntu release number.
either a latest tag is add or the container page provide a correct instructions as:

docker pull readthedocs/build:16.04

### Steps to reproduce the behavior

  1. docker pull readthedocs/build

**Comment by FrenchBen** [comment]
That's correct: 
https://hub.docker.com/r/readthedocs/build/tags/

You should open an issue with the image owner, so that they add a `latest` tag - In the meantime, you can select a different tag within Kitematic to start a container from this image.
