### ISSUE TITLE
Is there a Linux version or not?

### ISSUE THREAD

**Issue by samdidos** [docker/kitematic#2270]
From what I have seen in the issues, there has been a Linux version of Kitematic and it's still indicated in the readme file that you are supporting Linux, but I don't see any guides to install it. Is there a way?

**Comment by FrenchBen** [comment]
Absolutely - If you look in the release there's a package that you can download:
https://github.com/docker/kitematic/releases/tag/v0.13.0

Then install it - it's an ubuntu based package which will also work in debian.

If you have any terminal issues, please see the wiki:
https://github.com/docker/kitematic/wiki/Early-Linux-Support

**Comment by samdidos** [comment]
Ok thx a lot! It could be great to have some indications on the ReadMe file though

**Comment by FrenchBen** [comment]
@samdidos Feel free to update the Wiki with a nice how-to while you install it :)

**Comment by impredicative** [comment]
The latest Ubuntu package is at https://github.com/docker/kitematic/releases/latest
