### ISSUE TITLE
Unable to create container from My Repos with tag

### ISSUE THREAD

**Issue by rvf148** [docker/kitematic#2273]
### Expected behavior
Download container from docker hub https://hub.docker.com/r/rafvanhoof/homegenie/ in my repos with tag dev-linux

### Actual behavior
Throws error:
Network timed out while trying to connect to https://index.docker.io/v1/repositories/rafvanhoof/homegenie/images. You may want to check your internet connection or if you are behind a proxy.

### Information about the Issue
Internet connection is fine, no proxy.
When i put https://index.docker.io/v1/repositories/rafvanhoof/homegenie/images in the browser it just returns "[]" , this looks like an empty array.

### Steps to reproduce the behavior

  1. Goto My Repos
  2. Select ... on homegenie
  3. Select dev-linux
  4. Click x button
  5. Click Create

**Comment by FrenchBen** [comment]
I'm guessing you're not selecting your own tag? I can't replicate the issue

![search](https://cloud.githubusercontent.com/assets/3965324/22123613/23d931ba-de41-11e6-97f0-c4df7f36c108.png)
![tag](https://cloud.githubusercontent.com/assets/3965324/22123629/314c84e6-de41-11e6-8121-4dbfc5e8e226.png)
![tag-selected](https://cloud.githubusercontent.com/assets/3965324/22123631/32defcee-de41-11e6-867f-8db7340c227c.png)
![downloading](https://cloud.githubusercontent.com/assets/3965324/22123634/359e0678-de41-11e6-9d1b-a0933000a4df.png)
![running](https://cloud.githubusercontent.com/assets/3965324/22123644/421690dc-de41-11e6-8cd6-80ba50809e36.png)


Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
