### ISSUE TITLE
mssql express container is failed after installation

### ISSUE THREAD

**Issue by beylkhanovdamir** [docker/kitematic#2278]
### Steps to reproduce the behavior

  1. "docker pull microsoft/mssql-server-windows-express"
  2. installing process...
  3. 
![image](https://cloud.githubusercontent.com/assets/7656847/22149931/6a25b544-df27-11e6-8095-b03921216b6f.png)

P.S. 
Docker has last version and kitematic accordingly

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
