### ISSUE TITLE
OpenNMT issue

### ISSUE THREAD

**Issue by wassemgtk** [docker/kitematic#2280]
HTTP code is 404 which indicates error: undefined - {"message":"manifest for harvardnlp/opennmt:latest not found"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/harvardnlp/opennmt/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
