### ISSUE TITLE
Error when pull NanoServer

### ISSUE THREAD

**Issue by zcorp** [docker/kitematic#2282]
![nanoserver pull error](https://cloud.githubusercontent.com/assets/4031485/22174627/4d005ef8-dfca-11e6-862d-04d66ec51ccf.png)
### Expected behavior
download/pull image Microsoft NanoServer
### Actual behavior
error: unknown blob
### Information about the Issue
i just cant pull nanoserver

### Steps to reproduce the behavior

  1. ...find for nanoserver
  2. ...try pull

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:36637 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWmi0-0032MC-BG
	for greg@biomassiv.es; Thu, 26 Jan 2017 10:15:36 -0600
Date: Tue, 24 Jan 2017 17:35:01 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485308101;
	bh=Vqiqsixfy6GXglG1uh/igBmEO/5lrzhImbATdaR4Syo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=EmxFtDzKeY0mS4wABh/qv/0W7VmFyUHxKftPjaaBpTQo6Q/aw42+Qxlf/SAvmizRr
	 dTVz2VswnOaI/J92JIRju3nWOnug9M98Kk+mg0TzsD1OPx2w7iLNomILO/qFl1oD8A
	 cf20KvJgTQPyXznKHZhKp+8oQGid/Um9RbxS16k8=

**Comment by authurwoo** [comment]
French Ben ！ do you know that is nothing what you said ? do think about why the some question appear so many times? that means your answer is not work.
