### ISSUE TITLE
windowsservercore docker issue

### ISSUE THREAD

**Issue by agni896** [docker/kitematic#2283]
### Expected behavior
Trying to install the docker images
### Actual behavior
unknown blob
### Information about the Issue

unknown blob
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
