### ISSUE TITLE
docker pull securityrat/all_in_one fails due to missing manifest

### ISSUE THREAD

**Issue by JDL27** [docker/kitematic#2284]
### Expected behavior
download docker file
### Actual behavior
Error during docker pull command 
### Information about the Issue
HTTP code is 404 which indicates error: undefined - {"message":"manifest for securityrat/all_in_one:latest not found"}

### Steps to reproduce the behavior
try to run: docker pull securityrat/all_in_one fails

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/securityrat/all_in_one/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
