### ISSUE TITLE
Kitematic: Error in creating/downloading existing hello-world image

### ISSUE THREAD

**Issue by shwetaaher** [docker/kitematic#2288]
### Information about the Issue
I am downloading 'hello-world-nginx' image in Kitematic on Windows 7 64 bit machine. While downloading I got the following error 'read tcp 10.0.2.15:34856->52.222.190.31:443: read: connection reset by peer'.

### Steps to reproduce the behavior

1. Click on Kitematic. Select 'Use VirtualBox'.
2. Login and then click on 'Create' for hello-world-nginx image.

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
