### ISSUE TITLE
Imply docker image is not working on Windows 10

### ISSUE THREAD

**Issue by znevrly** [docker/kitematic#2289]
### Expected behavior
Creating docker image should be working

### Actual behavior
Tag latest not found in repository docker.io/imply/imply

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/imply/imply/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
