### ISSUE TITLE
Container list doesn't automatically update

### ISSUE THREAD

**Issue by JoshuaColeman** [docker/kitematic#2291]
### Expected behavior
The container list automatically updates... even if it's a poll every 5-10 seconds...

### Actual behavior
It never updates..

### Information about the Issue
Please implement this feature

### Steps to reproduce the behavior

  1. Expect your container list to update
  2. Be frustrated

**Comment by FrenchBen** [comment]
3. When frustrated go to View -> Refresh Container List - Or use CMD+R as a shortcut
