### ISSUE TITLE
HTTP code is 404 which indicates error: undefined - {"message":"manifest for openhab/openhab:latest not found"}

### ISSUE THREAD

**Issue by leiweke** [docker/kitematic#2296]
### Information about the Issue
HTTP code is 404 which indicates error: undefined - {"message":"manifest for openhab/openhab:latest not found"}

### Steps to reproduce the behavior

  1. click new and look for openhab/openhab
  2. click create

issue appears

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/openhab/openhab/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
