### ISSUE TITLE
Volumes not working on Mac Kitmatic

### ISSUE THREAD

**Issue by mfpost** [docker/kitematic#2297]
### Expected behavior
I would expect the Finder window that comes up to interactively work with the Docker container.

### Actual behavior
The container will not even boot.  In the container log it flashes '0 logs for this container', but I never get any more info and the container never starts.

### Information about the Issue
macOS Sierra 10.12.2
iMac 5K 

### Steps to reproduce the behavior
  1. Download the "hello-world-nginx' image
  2. Click on the folder under the "VOLUMES" section of the right sidebar
  3. Try to start the container

**Comment by FrenchBen** [comment]
I'm unable to reproduce this - I can mount any of my Desktop folders as volumes and get the proper behavior. 
Where is volume located?

**Comment by mfpost** [comment]
Sorry I should have updated the bug.  I figured it out later.  The problem was that I didn't have "File Sharing" in my "Mac Docker" app setup correctly.    So it seems you have to have the root of the files shared out via "Mac Docker" before you can use them via Kitematic.  Once I shared them out from "Mac Docker" they all started working fine.
