### ISSUE TITLE
Tag latest not found in repository docker.io/luketillman/datastax-enterprise

### ISSUE THREAD

**Issue by yoursatya** [docker/kitematic#2298]
### Expected behavior
It should download the image
### Actual behavior
Getting "Tag latest not found in repository docker.io/luketillman/datastax-enterprise" error

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/luketillman/datastax-enterprise/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
