### ISSUE TITLE
Impossible to create a new docker image

### ISSUE THREAD

**Issue by teger** [docker/kitematic#2299]
### Expected behavior
install a new docker image

### Actual behavior
Erreor, impmossible to install a new docker image

### Information about the Issue
Impossible to install a new image

### Steps to reproduce the behavior

  1. open kitematic
  2. add new and create a rabbitmq official docker image
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving"}

Even problem with cli : 
Unable to find image 'rabbitmq:3' locally
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving

Thanks

best regards

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
