### ISSUE TITLE
Start Kitematic with Virtualbox automatically

### ISSUE THREAD

**Issue by thenets** [docker/kitematic#2300]
### Expected behavior
Start Kitematic with Virtualbox automatically.

### Actual behavior
![kitematic_error](https://cloud.githubusercontent.com/assets/2138276/22347246/6b0f807c-e3ee-11e6-92dc-79a0ab2bfc84.JPG)

- Everytime I start the Kitematic and I got the error above.
- If I click on "Use Virtualbox", everything works as expected.

### Steps to reproduce the behavior

  1. Start "Docker Quickstart Terminal"
  2. Start "Kitematic"
  3. Got error as image above
  4. Click on "Use Virtualbox"
  5. Everything works

### Other information
I'm using VirtualBox because I need the VMware for other personal project and I can't keep Hyper-V and VMware installed the same time.

**Comment by FrenchBen** [comment]
Please upgrade to the latest release where this option can be set in the preference panel.

**Comment by thenets** [comment]
I got the Kitematic version from latest Docker Toolbox.
Now I update the Kitematic manually and everything works.

Thanks a lot!
