### ISSUE TITLE
Can not run Hello-world or any other image, connection refused

### ISSUE THREAD

**Issue by delley123** [docker/kitematic#2303]
### Expected behavior
Download and run of hello-world:latest

### Actual behavior
Getting error message:
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp 52.55.240.129:443: getsockopt: connection refused"}

### Information about the Issue
docker-toobox version 1.12.5 for Windows.
OS version: Windows 7 Pro
No custom settings Applied yet. Clean install!
HTTPS is going through corporate proxy

### Steps to reproduce the behavior

1. Install docker-toolbox
2. Run Kitematic
3. Try to create hello-world:latest

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
