### ISSUE TITLE
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp 127.0.0.1:443: getsockopt: connection refused"}

### ISSUE THREAD

**Issue by lauff** [docker/kitematic#2308]
### Expected behavior

cannot create container (e.g. hello-world-nginx)

### Actual behavior

HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp 127.0.0.1:443: getsockopt: connection refused"}

### Information about the Issue

There is no proxy needed, nor is a proxy environment variable set

### Steps to reproduce the behavior

create new hello-world-nginx container with Kitematic

**Comment by FrenchBen** [comment]
The fact that you are doing a lookup on the registry at address `127.0.0.1:443` instead of the proper DNS ip of the domain, seems to indicate otherwise. 
Can you share details about your setup?

**Comment by lauff** [comment]
very strange, but I solved the issue.

The problem was caused by the Synology DNS server that I entered as a backup to the normal FritzBox NS.
