### ISSUE TITLE
Unable to create a new container from the docker hub

### ISSUE THREAD

**Issue by bigblind** [docker/kitematic#2309]
### Expected behavior
The docker image is downloaded, and run.

### Actual behavior
I get an error screen:
<img width="852" alt="" src="https://cloud.githubusercontent.com/assets/737493/22429484/11982b0a-e70b-11e6-8d50-87dd45e13860.png">

>  We're sorry, there seems to be an error:
>
>  Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/postgres/images. You may want to check your internet connection or if you are behind a proxy.

### Information about the Issue
I'm connected to the internet, not behind any proxy.

### Steps to reproduce the behavior

  1. Click "new"
  2. Search for "postgres"
  3. In the recommended section, there's the official postgres image. Click "Create".

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
