### ISSUE TITLE
Docker mongo image failed 

### ISSUE THREAD

**Issue by pcsgithubid** [docker/kitematic#2314]
### Expected behavior

i should be able install docker mongo image

### Actual behavior

got the below error

### Information about the Issue

(HTTP code 404) unexpected - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: no such host"}

**Comment by FrenchBen** [comment]
This has been fixed in the latest beta release of Docker for Mac. See:
https://github.com/docker/for-mac/issues/1025
