### ISSUE TITLE
Allow defining the shell to use when launching CLI

### ISSUE THREAD

**Issue by navneetkarnani** [docker/kitematic#2317]
### Expected behavior
Opening the shell should take me to bash prompt
### Actual behavior
Opening shell takes me to sh prompt
### Information about the Issue
There is no way to tell Kitematic that /bin/bash should be used as the default shell when it launches the console/shell for the container

### Steps to reproduce the behavior

  1. start a container
  2. click on the "Exec" icon in the toolbar

**Comment by FrenchBen** [comment]
Not all images have the `bash` shell and thus can't be used as the default to exec into. 
You can actually 'tell' kitematic to use a different shell by setting the `SHELL` env variable to `/bin/bash`

**Comment by navneetkarnani** [comment]
Thanks for that. I missed that env variable.
