### ISSUE TITLE
Issue NGINX

### ISSUE THREAD

**Issue by albericsevilla** [docker/kitematic#2319]
### Steps to reproduce the behavior

  1. Create a nginx docker in Kitematic
  2. HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:56271->10.0.2.3:53: i/o timeout"}

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
