### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by jacoblyw** [docker/kitematic#2322]
I'm trying to install images using Kitematic and I am unable to install some images I'm getting the following message:

> unauthorized: authentication required

I am able to install *some* images (for example  **mongo:latest**)

In Kitematic I am logged in with my docker account and the packages are selected from the docker hub.

I have also tried via the command line with _docker run_ and _docker pull_ after logging in via _docker login_ and I get the same message.

Here's a recent example from terminal: 

> bash-3.2$  docker run joshuatyree/locomotive-3
> Unable to find image 'joshuatyree/locomotive-3:latest' locally
> latest: Pulling from joshuatyree/locomotive-3
> 
> a3ed95caeb02: Pull complete
> 453d13af6c96: Pull complete
> 65bb55baec9b: Download complete
> dcb8d2043cc2: Download complete
> 52f3d8b24a47: Downloading [==========>                                        ] 32.98 MB/160.2 MB
> 23a7d0052e00: Downloading [=====================>                             ] 12.69 MB/29.15 MB
> 75a6756e6a02: Downloading
> 56162a215fa6: Waiting
> 18c226e7a884: Waiting
> 0c660712f3c4: Waiting
> 745877459500: Waiting
> 09099f160b92: Waiting
> 323fee2fa24d: Waiting
> 2fedd2c023f4: Waiting
> 3710a96a8e1e: Waiting
> d860e3e49aa8: Waiting
> 8d87e1e05360: Waiting
> f6650479583f: Waiting
> 464f4b25d864: Waiting
> 6df773135241: Waiting
> a3472e2f28a3: Waiting
> docker: unauthorized: authentication required.
> See 'docker run --help'.

So, you can see that some pulls are completing but something is happening (or not happening) which causes a failure.

Mac OS 10.11.6
Docker version 1.12.6, build 23cf638
VirtualBox 5.1.14

Thanks for any help.

Jacob

**Comment by FrenchBen** [comment]
Please login to https://cloud.docker.com and confirm your account

**Comment by jacoblyw** [comment]
Actually, I'd already read your suggestion to "confirm your account" on another thread so, previous to posting I did visit https://cloud.docker.com . Once there, I could see no indication that anything was wrong: e-mail is verified there and at hub.docker.com as well.

Maybe there is something that I am missing, if you could be more specific as to "how" to confirm...

Thank you,

Jacob
