### ISSUE TITLE
Kitematic Changes port on restart (Container)

### ISSUE THREAD

**Issue by fc0712** [docker/kitematic#2323]
I' have set a static port on 32777 first time i did the setup of a container and then I restarted the container and it changed the port to 32781. Which is quite annoying as I have a setup with 4 apps talking to each other. 

Update:  I'm running Docker Version 1.13.0 (9795) and the latest Kitematic as far as I know installed it fresh 7 days ago.

Should it matter if the ports is one chosen when installing the container by kitematic or one you have defined yourself?

**Comment by FrenchBen** [comment]
Randomly assigned ports are still going to be randomly assigned on restart. 
Assign an actual port to it and it shouldn't change.

Aka it's the difference between doing:
`docker run -it -d -P nginx`
and
`docker run -it -d -p 32777:80 nginx`
