### ISSUE TITLE
Can't pull Docker images from Kitematic

### ISSUE THREAD

**Issue by michelbisson** [docker/kitematic#2324]
### Expected behavior
Pull the images from Docker epo

### Actual behavior
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/04/041d509e23e29ff3d8f1971e60215872bfb1fe63e8dbe401c00116c9caaab6a2/data?Expires=1486080346&Signature=DjpUFgA7GC7uYcXRHPPFO9hMeZ1EPrNCdrb0dHYiPCggB5E2YTHQZB4AG3HyUb8weL9vJkmsy9iD-SLfL3fSJuyxobnzJV~NO9X0z1k6UwevMhZJ-PsDC1AaPa~pYuBDJeoD-JTWZ~NSfiEC3zhB0Wn3ntrruweehvbC3SpNZGU_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: read udp 192.168.65.2:58220->192.168.65.1:53: i/o timeout

### Information about the Issue
I installed Docker for Mac, and also from there I could not pull images.

### Steps to reproduce the behavior
1 - Install the latest version of native 'Docker for Mac'
2 - Install the latest version of Kitematic
3 - Try to pull images....unsuccessful

Comment:
I have a suspicion that the resolving the Docker Repos server address is not working at the level on 'Docker for Mac'

**Comment by FrenchBen** [comment]
This is a bug in Docker for Mac which has been addressed:
https://github.com/docker/for-mac/issues/1025
