### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by jacoblyw** [docker/kitematic#2327]
Re-opening issue https://github.com/docker/kitematic/issues/2322

@FrenchBen said:
> Please login to https://cloud.docker.com and confirm your account

Actually, I'd already read your suggestion to "confirm your account" on another thread so, previous to posting I did visit https://cloud.docker.com. Once there, I could see no indication that anything was wrong: e-mail is verified there and at hub.docker.com as well.

Maybe there is something that I am missing, if you could be more specific as to "how" to confirm...

Thank you,

Jacob

**Comment by FrenchBen** [comment]
@jacoblyw With a lot of common issues being open for similar things, I didn't link the two - Feel free to comment on closed issues (or link them as you did here) so that we can have a common thread.

Within Docker Cloud, click on your username in the top right, from the dropdown click on `Account Settings`- You'll see that there is no checkmark next to your email and can click on the `resend verification email` icon. 
<img width="76" alt="resend-email" src="https://cloud.githubusercontent.com/assets/3965324/22613262/d3bf16ee-ea2b-11e6-83b2-d9fdae1d298d.png">

**Comment by jacoblyw** [comment]
Thanks for the more detailed instructions. I've been there to check on this and I've found
the following:
![screenshot 2017-02-04 20 07 57](https://cloud.githubusercontent.com/assets/8970192/22620887/b06a0196-eb15-11e6-9486-d122ba548a44.png)
and
 ![screenshot 2017-02-04 15 39 47](https://cloud.githubusercontent.com/assets/8970192/22620883/78a3ba0e-eb15-11e6-9964-4dc13a7ae36c.png)

As you can see, I have the checkmarks in both places  and for what it's worth in Kitematic:

![screenshot 2017-02-04 20 10 06](https://cloud.githubusercontent.com/assets/8970192/22620892/fe4e3062-eb15-11e6-9e21-a23c278299d4.png)

Here's what happens via the command line when I try to run an image.

![screenshot 2017-02-04 20 05 15](https://cloud.githubusercontent.com/assets/8970192/22620884/8191da60-eb15-11e6-8a2a-4df7809aefc4.png)

As you can see I logged in first to confirm that I was correctly logged in. I can mention that I am able to install the _mongo_ package but not _gordonburgett/mongo-locomotive_ por ejemplo

Thanks for your patience,

Jacob

**Comment by jacoblyw** [comment]
Today I installed Docker on another machine (slightly newer) which is not my development machine. I was able to install with no problem whatsoever. This speaks to the verification of e-mail, etc..

I'm going to go ahead and try to delete everything docker on my development machine and reinstall Docker to see if it clears up the problem.

Jacob

**Comment by FrenchBen** [comment]
It does sound like something else is getting in the way if you're able to install some images but not others. 
Thanks for the feedback regarding a new machine working no problem

**Comment by jacoblyw** [comment]
I deleted everything and installed the newer version of docker toolbox that I had downloaded to the other machine.

As I deleted everything I had to re-create the virtual machine and everything and had to login to use kitematic.

I have now been able to install several images that I hadn't been able to, to pick and choose and try new ones (you know; like a normal person).

For now the problem seems to have cleared up. Since I'd already deleted all the configuration files and started fresh as part of my attempts at troubleshooting several times, the main difference seems to be the new(er) version of Docker toolbox.

I had
> Docker version 1.12.6, build 23cf638

and now I have

> Docker version 1.13.0, build 49bf474

I think that whatever has changed between versions has been for the better (Thanks!)

Thank you for your assistance and for listening,

Jacob

**Comment by 4np** [comment]
![docker auth error](https://user-images.githubusercontent.com/1049693/34667208-515f0540-f468-11e7-98ff-b42314295bd3.png)

I experience similar issues... I completely re-installed docker (for mac) and kitematic as described by @jacoblyw above, but I keep getting the HTTP 500 unauthorised error in Kitematic when I want to install a docker image. I can properly login in both docker as well as Kitematic, on docker hub and cloud.docker.com... Not sure why this happens though?
