### ISSUE TITLE
unknown blob

### ISSUE THREAD

**Issue by kevinmarchand** [docker/kitematic#2328]
### Expected behavior

Installation work

### Actual behavior

Installation error with unknown blob

### Information about the Issue

using kitematic to install during the download we are getting this unknown blob

### Steps to reproduce the behavior

  1. last version of docker
  2. last version of toolbox
  3. download aspnet container from microsoft

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
