### ISSUE TITLE
I am getting this masege : Tag latest not found in repository docker.io/deeposm/deeposm.org

### ISSUE THREAD

**Issue by mosmos** [docker/kitematic#2329]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/deeposm/deeposm.org/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
