### ISSUE TITLE
Add possibility to search for image with specific tag

### ISSUE THREAD

**Issue by w0mbat** [docker/kitematic#233]
I would like to be able to enter "rabbitmq:3-management" into the search bar and Kitematic should automatically detect, that I want to start the "rabbitmq" image with the tag "3-management".

**Comment by jeffdm** [comment]
Great! Thanks for the issue!

**Comment by hshira** [comment]
Is this issue being worked on? I would love this feature as well.

**Comment by HadesArchitect** [comment]
That's an important feature.

**Comment by Nolanus** [comment]
+1
At the moment it is not possible to pull the php:7-apache, you can only download the "latest" cli version.
