### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by HiJack1** [docker/kitematic#2331]
### Expected behavior
download the node.js officiale with kitematics from docker hub. 
### Actual behavior
get error:
HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.2:58486->192.168.65.1:53: i/o timeout"}
### Steps to reproduce the behavior

  1. open kitematics
  2. Search node anche start downloading node official

**Comment by FrenchBen** [comment]
This is a bug in Docker for Mac which has been addressed:
https://github.com/docker/for-mac/issues/1025
