### ISSUE TITLE
download run into problem 

### ISSUE THREAD

**Issue by samuelan** [docker/kitematic#2332]
### Expected behavior
Docker image download complete and started

### Actual behavior
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\59f83b291a302afd20b8a3ede96d3ecce9e51afcb593b35d08002f6e486245a0\UtilityVM: The parameter is incorrect.

### Information about the Issue
This was run on Docker for Windows (Beta) 
Version 1.13.1-rc1-beta40 (9961)
Channel: beta
0d026e1

### Steps to reproduce the behavior

  1. open Kitematic from the Docker for Windows task icon
  2. search for Microsoft Sql Server Windows
 3. click "create" button to start download
 4. will get stuck at 99.xx% and finally report the above error message.

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
