### ISSUE TITLE
Prevent  Kinematic on restart vm if already started

### ISSUE THREAD

**Issue by neridonk** [docker/kitematic#2334]
Im using Docker Toolbox and there is this known issue "Windows host-only adapter creation fails due to slow background processing".
When I try running KInematic it tries to restart the VM (default) with a new adapter setting.

and If it does that all breaks down, how can i prevent the restart if it is already running

**Comment by FrenchBen** [comment]
Kitematic always attempts to find the currently running VM and only tries to start it if it finds it dead.
it's the first time I've heard of issues related to this. 
Do you have a link to the host-only adapter creation issue you mentioned?

**Comment by neridonk** [comment]
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes was a section.
Im not sure but i think it might be a problem with my right on my PC or antivir so I close this because it fiexed it
