### ISSUE TITLE
500 error when create mysql

### ISSUE THREAD

**Issue by Max-lu** [docker/kitematic#2335]
### Information about the Issue

HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/library/mysql/manifests/latest: Get https://auth.docker.io/token?account=maxlu\u0026scope=repository%3Alibrary%2Fmysql%3Apull\u0026service=registry.docker.io: net/http: TLS handshake timeout"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
