### ISSUE TITLE
No way back from setting VirtualBox in VM Settings 

### ISSUE THREAD

**Issue by VojtechVitek** [docker/kitematic#2338]
### Expected behavior
I can change back to Native.

### Actual behavior
I clicked on VirtualBox in the VM Settings by accident. The app restarted. And now I'm stuck with VirtualBox and I can't toggle the VM Settings back to "Native".

### Steps to reproduce the behavior
1. Click on "Use VirtualBox instead of Native on next restart" in the VM settings
2. App restarts
3. Try to toggle the option back to "Native"
4. I guess all you can do is remove the app cache

**Comment by FrenchBen** [comment]
@VojtechVitek I have it on my todo list to allow for a 'reset' of that pref when you see the error. 
As a quick hack, you can also open the dev console (like on chrome) and issue the delete of the preference to get you back on track.

**Comment by rissvann** [comment]
Unluckily, I also clicked on VirtualBox option in the settings area and now, there is a setup error "Docker Machine is not installed. Please install it via the Docker Toolbox." I have tried to get rid of this error but no luck. Would you please explain that where exactly we need to open the dev console and where to delete the preferences? I am brand new to Docker & Kinematic so looking a little bit of more help to get familiar with the concepts.

**Comment by luckydonald** [comment]
Clicking "Use VirtualBox instead of Native on next restart" also shouldn't instantly trigger a reboot of the app.
It should wait for the _user_ rebooting the app.

**Comment by bzm97** [comment]
A quick hack to get over this issue is to reset ```settings.useVM``` flag in LocalStorage.
Here's a Mac solution, I guess Windows\Linux should be somewhat the same (one just need to find out where ```Toggle Chromium Developer Tools``` menu item is located).
* Click top menu ```View > Toggle Chromium Developer Tools```
* In the Developer Tools select ```Resources``` pane:
![screen shot 2017-05-17 at 22 02 31](https://cloud.githubusercontent.com/assets/3764746/26171203/c733f508-3b4c-11e7-91ed-283674c02bb9.png)
* Expand ```Local Storage``` section and select ```file://``` node
* Edit ```settings.useVM``` value in the table to be ```false```
* Restart the app

**Comment by FrenchBen** [comment]
This is also now part of the latest release where a reset button has been added.

**Comment by luckydonald** [comment]
@FrenchBen Will it now ask for confirmation before restartig after you click the checkbox?

**Comment by FrenchBen** [comment]
There will be an extra `reset` option when you get the error

**Comment by luckydonald** [comment]
But clicking the checkbox will still instantly stop the app and restart?
This is not how checkboxes work.
Maybe use a button <kbd>Use Virtualbox and restart</kbd>.
Having a checkbox and talking about `on next reboot` but not waiting for `next reboot` but instead instantly reboot simply is wrong.

**Comment by FrenchBen** [comment]
I think you're confusing 2 different settings. 
the `reset` button will exist on the launch screen, if something goes wrong and will allow the user to reset any/all Kitematic.
The checkbox preference was setup to match all other checkbox on that page, which is no 'save' - You're right that I should remove the `on next reboot` wording as it is confusing.

**Comment by luckydonald** [comment]
@FrenchBen saving it on click is fine.

Still it shouldn't trigger a reboot.
Maybe open a simple alert box 
>**Restart now?**
><kbd>Yes</kbd> <kbd>No</kbd>
