### ISSUE TITLE
Clicking on "Create" from a "My Images" downloaded from a private repo gets a "404 no such image"

### ISSUE THREAD

**Issue by rfagen** [docker/kitematic#2340]
### Expected behavior
Create a container and be able to start it

### Actual behavior
Error message: (HTTP code 404) no such image - No such image: xxx.xxx.xxx.xxx/imagename:latest

### Information about the Issue
I downloaded "imagename:latest" from an internal repo, and I can see it from "docker images" on in the CLI.

### Steps to reproduce the behavior

  1. download an image from a private repo
  2. attempt to create a container from that image

**Comment by FrenchBen** [comment]
There's an on-going issue regarding namespace in local images. Closing this in favor of that older issue
