### ISSUE TITLE
Microsoft Images Not Downloading - Unknown Blob

### ISSUE THREAD

**Issue by pedrohugorm** [docker/kitematic#2341]
### Expected behavior
Download the Docker Image = windowsservercore

### Actual behavior
Error on Screen - Unknown Blob

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
