### ISSUE TITLE
can't download ltp-on-ubuntu

### ISSUE THREAD

**Issue by jhfnetboy** [docker/kitematic#2347]
### Expected behavior
download ltp image
### Information about the Issue
HTTP code 404) unexpected - {"message":"manifest for scorpio147wbh/ltp:latest not found"}

### Steps to reproduce the behavior

  1. open kitematic
  2. search ltp
  3.find the first one in the result:ltp(Langu)age Technology Platform
  4.click create,then show info:HTTP code 404) unexpected - {"message":"manifest for scorpio147wbh/ltp:latest not found"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/scorpio147wbh/ltp/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
