### ISSUE TITLE
Jenkins enterprise error

### ISSUE THREAD

**Issue by ganeshnewt** [docker/kitematic#2348]
### Expected behavior
HTTP code is 500 which indicates error: server error - {"message":"read tcp 10.0.2.15:34306-\u003e52.201.90.157:443: read: connection reset by peer"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
