### ISSUE TITLE
Can't install Discourse container

### ISSUE THREAD

**Issue by dimitriskr** [docker/kitematic#2351]
### Expected behavior
Discourse container is installed
### Actual behavior
Kitematic shows error `(HTTP code 404) unexpected - {"message":"manifest for discourse/discourse:latest not found"}`
### Information about the Issue
System Information: 
* Windows 10 64-bit Education

### Steps to reproduce the behavior

  1. Start Docker on Windows
  2. Open Kitematic
  3. Add *Official* Discourse container

![image](https://cloud.githubusercontent.com/assets/21278702/22950114/342ff054-f30d-11e6-9d7b-7dd0b57a6d94.png)

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/discourse/discourse/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by dimitriskr** [comment]
Yes, it worked! I used Powershell to install it
Thank you very much! I will send the devs a note about this.
