### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:48595->10.0.2.3:53: i/o timeout"}

### ISSUE THREAD

**Issue by chowhl** [docker/kitematic#2353]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by chowhl** [comment]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:48595->10.0.2.3:53: i/o timeout"}

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
