### ISSUE TITLE
It can't reset the setting after set wrong options

### ISSUE THREAD

**Issue by wyicwx** [docker/kitematic#2354]
### Expected behavior
Offer an entrance or button to reset setting.

### Actual behavior
I can't found any button to reset my wrong setting..In Settings-Ports tabs, there are nothing what i set option before, and also can't add new port map....

### Information about the Issue
Home tabs show:
We're sorry. There seems to be an error:
(HTTP code 500) server error - invalid port specification: "80800"

### Steps to reproduce the behavior

  1. In setting Ports tabs, add new port config
  2. set docker port 8080 and published ip:port 80800
  3. save

**Comment by LotusAxt** [comment]
Had the same issue today. Copy & pasted a space at the end of the Port number and now only getting. "HTTP code 500) server error - invalid port specification: '1433 '".
A plausibility check before saving, or in my case a `String.Trim();`, would be nice here. :) 👍

**Comment by FrenchBen** [comment]
There isn't a need to really 'reset' anything, when you can simply delete the container and create a new one. 
@LotusAxt Adding the `trim` is a good idea and will add it to the list of things to do. 

Thanks
