### ISSUE TITLE
Managed to run on Fedora 25

### ISSUE THREAD

**Issue by ozc** [docker/kitematic#2357]
As Fedora uses Wayland, electron-prebuilt is not working. So electron has to be built.

I did not have any spare machine to install Fedora on, so used VirtualBox. And I did not take notes during this installation attempt, so there may be some errors.

installed these packages:
libcanberra-gtk3 libcanberra libcanberra-devel 

"sudo dnf install libXScrnSaver" to install libXss.so.1

Had to change electron-prebuilt, electron-version values in package.json file to "electron
 1.6.0" and in Gruntfile.js file to require ("electron").

In src directory several files needs to be edited to change these lines, for new electron version:
import shell from 'shell';
to
import {shell} from 'electron';

after these are done, make and grunt commands work and kitematic seems to run

I don't know if it's because it's running under VirtualBox or not, but there are some GUI glitches. Like, <div class="details-panel home" ...> needs to have padding-top:50px; , otherwise log area is blocking the start/restart menu.

For grunt release command to work and yield a rpm, rpm-build needs to be installed:
sudo dnf install rpm-build

and the final rpm package have the lsb package dependency. 

sudo dnf install lsb

Will try to test how it works and take notes as I use it.

**Comment by FrenchBen** [comment]
Thanks for the help in getting this to work on Fedora - Would be glad to see a proper list of what needs to be modified, in order to support more linux distributions.

**Comment by ozc** [comment]
I've tried to retrace my steps and make it as easy as possible. But it needs to be checked. At least, the regex codes and the typo errors. Kitematic and electron version numbers need to be changed if necessary, too.


sudo dnf -y update

--Download kitematic tar.gz file
tar zxvf kitematic-0.13.1.tar.gz
cd kitematic-0.13.1

sed -ie 's/.*\("electron-version"\)\(.*\)\(".*"\).*$/\1: "1.6.0",/g' package.json
sed -ie 's/.*\("electron-prebuilt"\)\(.*\)\(".*"\).*$/"electron": "\^1.6.0",/g' package.json

sed -ie 's/.*\(var electron\)\(.*\);$/\1 = require(\x27electron\x27);/g' Gruntfile.js 


grep -Ril "import shell from 'shell'" ./src | xargs sed -ie 's/.*\(import shell from \x27shell\x27\)/import {shell} from \x27electron\x27;/g'

sudo dnf -y  install libXScrnSaver
sudo dnf -y install libcanberra-gtk3 libcanberra libcanberra-devel
make
grunt

--At this point Kitematic is compiled and running

--If you want to create a rpm
sudo dnf -y install rpm-build
grunt release

cd dist
sudo rpm -Uvh Kitematic_0.13.1_x86_64.rpm

-- If shows dependency errors:
sudo dnf -y install lsb

**Comment by riggerthegeek** [comment]
Does anyone know of a reason why this couldn't be incorporated into the main project so we get an .rpm release as well as a .deb?

**Comment by riggerthegeek** [comment]
A solution to this is actually much simpler than first I thought. Download the zip/tar.gz of the release you want, extract it and run the following commands.

```sh
cd /path/to/kitematic
npm install
grunt release
```

This will create an RPM that you can install as you would normally.

You will need Grunt installed for this. I've done this using Grunt 0.4.5 and Grunt CLI 1.2.0.

**Comment by FrenchBen** [comment]
@riggerthegeek that's correct - All of the builds are done on an OSX machine, which doesn't seem to have the proper electron-rpm packages needed for the RPM build.
