### ISSUE TITLE
No such image error: truncated name

### ISSUE THREAD

**Issue by crockpotveggies** [docker/kitematic#2360]
### Expected behavior

Built the following image and wanted to run it via Kitematic:
```
docker build -t skymindio-docker-dl4j-examples.bintray.io/deeplearning4j/keras-dl4j .
```

### Actual behavior

It appears the naming scheme has been truncated, and Kitematic thinks the image is named

```
skymindio-docker-dl4j-examples.bintray.io/deeplearning4j:latest
```

![screen shot 2017-02-18 at 2 59 47 pm](https://cloud.githubusercontent.com/assets/1445295/23097543/339143ce-f5eb-11e6-9784-ecc4c6b4bf54.png)

### Information about the Issue

Latest Docker versions on everything.

### Steps to reproduce the behavior

  1. Build image on command line with bintray naming scheme.
  2. Attempt to launch via Kitematic console

**Comment by FrenchBen** [comment]
There's an existing issue with namespace with local images. Closing in favor of the original issue.
Thanks
