### ISSUE TITLE
Cannot find image name like 'mycompany.com/foo/bar:v0.1'

### ISSUE THREAD

**Issue by asdfsx** [docker/kitematic#2365]
### Expected behavior
create the container use the image I build for a self-host docker repository.

### Actual behavior
error on the gui:
(http code 404)no such image  - No such image: mycompay.com/foo:v3.1.0

It seems the real image name missed

### Steps to reproduce the behavior

  1. pulled an image from an self-host repostry
  2. start it with kitematic, by click the create button

**Comment by FrenchBen** [comment]
This is a non-issue with local images and namespace. Closing in favor of earlier issues.
