### ISSUE TITLE
Ubuntu Official Given HTTP 500 eror.

### ISSUE THREAD

**Issue by nsrtky** [docker/kitematic#2372]
### Expected behavior
get ubuntu.
### Actual behavior
![image](https://cloud.githubusercontent.com/assets/12385044/23209911/fa6dbf16-f903-11e6-8650-f6e40c7940e9.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kitora** [comment]
I have similar problem when I pull centos:latest image.
Even it occurs from DOCKER CLI.
```
PS C:\Program Files\Docker\Kitematic> docker pull centos
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I upgraded docker to docker 17.03.0-ce-rc1-win1 but not resolved.

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
