### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by joshuagithub** [docker/kitematic#2374]
### Information about the Issue
I have installed docker for windows 10 then install Kitematic  it ask me the username and password. i have provided then  to pull "getHue" image into kitematic. It start with initial downloading the image. but it stop with the above message. 

kindly advice. 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by joshuagithub** [comment]
need suggestions

**Comment by FrenchBen** [comment]
Login to https://cloud.docker.com -> Account Settings and verify that your email has been verified

**Comment by joshuagithub** [comment]
Thank you. firstly i like docker and Hue combination. Once i install everything successful then i am able to explore more. 

However, i have another minor configuration issues. Let me explain the steps . please help me to run Hue with my laptop.

1. I have downloaded docker VM (currently running in my Windows-10 Laptop)
    I have followed the url : https://docs.docker.com/docker-for-windows/install/
2. I have downloaded Kitematic separately. but i use step 3. 
3. I have installed Docker Toolbox which has Kitematic Alpha.
4. I have installed powershell and install Ubuntu 
url: https://docs.docker.com/docker-for-windows/
5.  I have followed the url: http://gethue.com/getting-started-with-hue-in-2-minutes-with-docker/

![image](https://cloud.githubusercontent.com/assets/9146963/23332416/43e69d86-fbb4-11e6-9b18-ffaa029a4a24.png)

BUT...

I am not able to login  OR how to reset the password.  Kindly advice.
