### ISSUE TITLE
Not allowing login using dockerhub emails with special characters

### ISSUE THREAD

**Issue by sachin-gupta** [docker/kitematic#2378]
### Expected behavior
Should allow entry of any email like "sachin.aut@gmail.com"

### Actual behavior
Not allowing to log using dockerhub credentials

### Information about the Issue
Won't allow entry of dockerhub login value "sachin.aut@gmail.com". Regular expression check for username needs to be fixed to allow special characters in email like ".-_"

### Steps to reproduce the behavior

  1. Type email "sachin.aut@gmail.com" in the Username box

![image](https://cloud.githubusercontent.com/assets/3601983/23328605/605af610-fb4b-11e6-9e75-f98ccc000222.png)

**Comment by FrenchBen** [comment]
There is a previous issue opened for this specifically; the entry placeholder does mention that a username is required, not the email address.
Feel free to open a PR to fix this :)

**Comment by sachin-gupta** [comment]
How to open PR :)



*Sachin Gupta *

*LinkedIn: http://in.linkedin.com/in/sachingpta
<http://in.linkedin.com/in/sachingpta>*

*Blog / Web:  https://sachingpta.gitlab.io/home/
<https://sachingpta.gitlab.io/home/> <https://sachin-gupta.github.io/>*

*GitLab: https://gitlab.com/users/sachingpta/projects
<https://gitlab.com/users/sachingpta/projects>*

*GitHub: https://github.com/sachin-gupta <https://github.com/sachin-gupta>*

*StackOverFlow:
http://stackoverflow.com/users/5288679/sachin-gupta?tab=profile
<http://stackoverflow.com/users/5288679/sachin-gupta?tab=profile>*

* <sachin.q3@gmail.com>*

*Intellectual Stuff: https://goo.gl/u4SlBO <https://goo.gl/u4SlBO>*




*Mobile: (+91)8755-787848,            (+91)8077-659072*

*Skype: sachin.aut*
*Email: sachin.aut@gmail.com <sachin.aut@gmail.com>*

**Comment by thaddaeus** [comment]
The place holder doesn't say "Username" but "Username or Email" still.
