### ISSUE TITLE
How to add volumes interface is not

### ISSUE THREAD

**Issue by wl496928838** [docker/kitematic#2386]
How to add volumes interface is not

**Comment by FrenchBen** [comment]
Volumes depend on the image declaring volumes - There's a PR to add volumes when none exist, but it's in need of updates.
You can always run the container by hand to map any volume you'd like using `-v`
https://docs.docker.com/engine/reference/commandline/run/#/mount-volume--v---read-only

**Comment by wl496928838** [comment]
Can't operate in UI again

**Comment by wl496928838** [comment]
I want to edit UI in volumes
