### ISSUE TITLE
Microsoft/nanoserver image failure: "unknown blob"

### ISSUE THREAD

**Issue by kilyin** [docker/kitematic#2387]
### Expected behavior
Microsoft nanoserver image is downloaded
### Actual behavior
download fails with error: "unknown blob"
### Information about the Issue
OS: Windows 10
Docker version: 1.13.1
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
