### ISSUE TITLE
centos:latest not downloading

### ISSUE THREAD

**Issue by Neelerak** [docker/kitematic#2392]
### Expected behavior
Starting New Container centos:latest
Download and start

### Actual behavior
Fails to download

### Information about the Issue
(HTTP code 404) unexpected - {"message":"manifest for centos:latest not found"}

### Steps to reproduce the behavior

  1. Search for centos container
  2. Click Create on official container

**Comment by Neelerak** [comment]
Thought it was our network, doesn't seem to be, can not download any docker image ATM.

**Comment by FrenchBen** [comment]
Docker Hub is hosted on AWS s3, which is currently down:
https://status.aws.amazon.com/

Sorry for the inconvenience.
