### ISSUE TITLE
Docker Pull tomcat:latest results in "Could not reach any registry endpoint"

### ISSUE THREAD

**Issue by larajones** [docker/kitematic#2393]
### Expected behavior

Tomcat:latest (or appropriate tag)

 is pulled

### Actual behavior

whether I use Docker CLI or Kitematic,  I cannot pull a Tomcat docker container.

### Steps to reproduce the behavior

  1. ... Run: docker pull tomcat:<tag> 
 OR
  1. ... Open Kitematic>search for Tomcat>Select Create
--wait for timeout

**Comment by FrenchBen** [comment]
Docker Hub is hosted on AWS s3, which is currently down:
https://status.aws.amazon.com/

Sorry for the inconvenience.
