### ISSUE TITLE
Downloading / Installing Docker Image fails

### ISSUE THREAD

**Issue by BartokW** [docker/kitematic#2395]
### Expected behavior
For the container to be downloaded, and setup
### Actual behavior
Error message Recieved "(HTTP code 404) unexpected - {"message":"manifest for binhex/arch-delugevpn:latest not found"}"

### Information about the Issue
Running Kitematic on MacOS 10.12.3

### Steps to reproduce the behavior

  1.  Installed DockerTools
  2. Searched for Binhex
  3. Selected Create on the binhex/arch-delugevpn item.
  4. Received the above error

**Comment by FrenchBen** [comment]
Docker Hub is hosted on AWS s3, which is currently down:
https://status.aws.amazon.com/

Sorry for the inconvenience.
