### ISSUE TITLE
Issue: Could not reach any registry endpoint. 

### ISSUE THREAD

**Issue by s4sharma** [docker/kitematic#2400]
### Expected behavior
Be able to install dashDB image.

### Actual behavior
Could not reach registry endpoint.

### Information about the Issue
First occurrence

### Steps to reproduce the behavior

  1. Launch Kitematics > My Repos > dashDB Local Create.
  2. Communication to docker hub fails with "could not reach registry endpoint" error.

**Comment by FrenchBen** [comment]
Docker Hub is hosted on AWS s3, which is currently down:
https://status.aws.amazon.com/

Sorry for the inconvenience.
