### ISSUE TITLE
eclipse che:latest can't be downloaded

### ISSUE THREAD

**Issue by bugsend** [docker/kitematic#2403]
### Expected behavior
image successfully downloaded
### Information about the Issue
(HTTP code 404) unexpected - {"message":"manifest for eclipse/che:latest not found"}

### Steps to reproduce the behavior

  1. open Kinematic
  2. search for "eclipse che" image
  3. find one with tens of Ks downloads (69)
  4. click "download"

**Comment by FrenchBen** [comment]
Docker Hub is hosted on AWS s3, which is currently down:
https://status.aws.amazon.com/

Sorry for the inconvenience.
