### ISSUE TITLE
Modify IP docker machine - windows

### ISSUE THREAD

**Issue by andryi777** [docker/kitematic#2404]
### Information about the Issue
I've got the IP http://192.168.99.100:32770/ but I want to changed it to 172.30.55.123  but in kitematic I don't have an option to modify.
I am on windows10

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Once the VM has been created you cannot change it - The only thing you can do is manually create the VM with a different IP and Kitematic should pick it up. 

Checkout the `--virtualbox-hostonly-cidr` of docker-machine: https://docs.docker.com/machine/reference/create/
