### ISSUE TITLE
Unenble to create the paddle image in Docker(Version 1.13.1 (10072) Channel: Stable 94675c5) on windows10

### ISSUE THREAD

**Issue by yecfly** [docker/kitematic#2411]
### Expected behavior
download and create the paddle image
### Actual behavior
Unable to download the docker image. ERROR: (HTTP code 404) unexpected - {"message":"manifest for paddledev/paddle:latest not found"}
### Information about the Issue
ERROR: (HTTP code 404) unexpected - {"message":"manifest for paddledev/paddle:latest not found"}

### Steps to reproduce the behavior

  1. search for 'paddle-dev/paddle'
  2. click CREATE button

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/paddledev/paddle/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by yecfly** [comment]
Thanks @FrenchBen!
Problem solved when I replaced the tag as follow:
docker run -it paddledev/paddle:gpu-release-v0.9.0
