### ISSUE TITLE
opendaylight latest image not found

### ISSUE THREAD

**Issue by bilucent** [docker/kitematic#2419]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to the OpenDaylight repo.
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
