### ISSUE TITLE
How can pull an imagen from proxy

### ISSUE THREAD

**Issue by andryi777** [docker/kitematic#2420]
### Information about the Issue
I installed Docker Toolbox with Kitematic, and I couldn't view the images but with add 2 registries in enviroment variables (http_proxy, https_proxy), now I can.

And, the new problem it's how can I connect to docker hub by proxy because when I selected 

### Steps to reproduce the behavior

  1. ...
  2. ...
![1](https://cloud.githubusercontent.com/assets/21963698/23527131/adb3c552-ff62-11e6-9892-d56af4c25426.png)
![2](https://cloud.githubusercontent.com/assets/21963698/23527130/adb3a82e-ff62-11e6-9708-6b648525e196.png)

**Comment by FrenchBen** [comment]
Make sure that the env vars are set in your terminal and within the VM.

See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
