### ISSUE TITLE
Image not available

### ISSUE THREAD

**Issue by umesh-chauhan-searce** [docker/kitematic#2421]
### Steps to reproduce the behavior

  1. Started kitematic on system
  2. Search creating new container for iis with this path.
  3. Getting error for this repositery
![kitematic iis image downloading issue](https://cloud.githubusercontent.com/assets/5081032/23544563/80e4e040-001d-11e7-80f9-ab61f6c31c10.PNG)

**Comment by vesper8** [comment]
getting this error too.. and the cloud icon just seems to be downloading perpetually. There should be a button to "re-attempt" download as well as a place to see current downloads' progress

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/samslaider/mssql-iis-windows/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
