### ISSUE TITLE
Doesn't pull images

### ISSUE THREAD

**Issue by BCPRA-AKA** [docker/kitematic#2422]
### Expected behavior
pull image, e.g. docker pull uifd/ui-for-docker

### Actual behavior
timeout

### Information about the Issue
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Steps to reproduce the behavior
  1. docker pull uifd/ui-for-docker

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
