### ISSUE TITLE
too slow when downloading tensorflow

### ISSUE THREAD

**Issue by gunuo** [docker/kitematic#2430]
I use Thunder to accelerate when downloading software. I just want to know, if I download tensorflow from Kitematic,  how can I use this accelerator? 3x

**Comment by FrenchBen** [comment]
Unfortunately the image for Tensorflow is quite large 1-2GB and there isn't much we can do on our side.
You should open an issue with their repo to have them slim it down, as many improvements could be made. 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile
