### ISSUE TITLE
SSL interception unable to load repository or login

### ISSUE THREAD

**Issue by leeroya** [docker/kitematic#2433]
### Expected behavior

Login to Docker Hub

### Actual behavior

- self signed certificate chain error
- Cannot login to dockerhub when in a network that replaces certificates with the companies certificates.

### Steps to reproduce the behavior

Load applicaiton behind proxy and ssl interception

**Comment by FrenchBen** [comment]
I'm guessing you're still using Toolbox? if you're able to run Docker for Mac/Windows, I would suggest using that instead. 
If not, please see the instructions below for a possible solution:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
