### ISSUE TITLE
HTTP code is 500: Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by juanmiguelRuaDev** [docker/kitematic#2442]
### Expected behavior
 
Download any container

### Actual behavior

When I try to create any  container from an image, I get the following error: 

`HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: Get https://auth.docker.io/token?account=juanmiguelruadev&scope=repository%3Alibrary%2Fjenkins%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}`

### Information about the Issue

I'm trying to run "Kitematic" on windows 7  under "proxy  server"

### Steps to reproduce the behavior

  1. ... Open Ketimetic
  2. ... Trying to download any container
  3. ... Get error 500

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
