### ISSUE TITLE
Official elasticsearch image unable to start

### ISSUE THREAD

**Issue by likewei92** [docker/kitematic#2445]
### Expected behavior

After pulling an image, starting it from "My Images" should work.

### Actual behavior

Does not

### Information about the Issue

I'm following steps from elasticsearch (https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) and trying to make it work with kitematic

### Steps to reproduce the behavior

  1. docker pull docker.elastic.co/elasticsearch/elasticsearch:5.2.2
  2. In kitematic, go to new container, then "My Images". Click create on the elasticsearch container.
  3. Get error "(HTTP code 404) no such image - No such image: docker.elastic.co/elasticsearch:5.2.2"

**Comment by FrenchBen** [comment]
It looks like Elasticsearch is forcing you to download from their remote registry, which seems broken. Doing `docker pull elasticsearch:5.2.2` works perfectly for me. 

Open a ticket with them.
