### ISSUE TITLE
Unable to authenticate MySQL via kitematic

### ISSUE THREAD

**Issue by bythckr** [docker/kitematic#2452]
### Expected behavior
There should be a box where I can input parameters to run MySQL
### Actual behavior
Container log:
_**error: database is uninitialized and password option is not specified 
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD**_
### Steps to reproduce the behavior

  1. Installed mysql via kitematic.

I am not sure if this issue is already being worked on based on what I read in the the closed issues.

**Comment by FrenchBen** [comment]
Please read the MySQL requirement documentation:
https://hub.docker.com/_/mysql/

**Comment by dhulke** [comment]
I havent found anything on that documentation that addresses the issue with kitematic. What should I do?

**Comment by collin5** [comment]
@dhulke @bythckr Did you set any of  **MYSQL_ROOT_PASSWORD**, **MYSQL_ALLOW_EMPTY_PASSWORD** or **MYSQL_RANDOM_ROOT_PASSWORD** environment variables for the container and still getting this error ?

**Comment by dhulke** [comment]
I eventually found out that I had to set that on kitematic and it worked

**Comment by ZeFifi** [comment]
@dhulke Could you share the solution with us please :) ?
