### ISSUE TITLE
Docker windows 10 error

### ISSUE THREAD

**Issue by mrrisky123** [docker/kitematic#2453]
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\86517ae3a94d1f726ff08be725361487febb1f6de32dad024f046cb9733e6849: The system cannot find the path **specified**

docker windows 10 error lol

**Comment by bodote** [comment]
+1 for me

**Comment by FrenchBen** [comment]
@mrrisky123 Can you provide additional details, such as docker version, kitematic version and image used?

**Comment by gy0857478** [comment]
`failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\9c194064ad1b0e49eec749cff19b806ab12a1a2c8c0d75b03c3aabd54c32d957: The system cannot find the path specified.`

I got same error with download hello-world-nginx
my environment was windows 10 pro, but my laptop is macbook pro 
my windows is installed on parallels desktop.

**Comment by FrenchBen** [comment]
@gy0857478 Are you using toolbox or Docker for Windows?

**Comment by SachinCS1992** [comment]
+1. Downloaded latest Kitematic off the site, made sure Docker is running, and tried to import hello-world-nginx from the repo, got the following error:

failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\a9eb511834452cf9854fd0d547038e1415b4f755a9f6bcfda83044242d89fe8c: The system cannot find the path specified.

**Comment by FrenchBen** [comment]
@SachinCS1992 Can you do a `docker run` of the same container via PowerShell and provide the output here?

**Comment by Sharkrit** [comment]
That errors might be related to an issue with BitLocker enforced in our domain GPO. 
Hope this helps: https://github.agodadev.io/ServerInfra/Windows10init#install-docker-community-edition-on-windows-10-for-support-windows-container

**Comment by FrenchBen** [comment]
thanks @Sharkrit for sharing, the link although it doesn't seem valid from the outside. Can you provide details as to what was changed?
Closing for now, but please comment here.

**Comment by Sharkrit** [comment]
@FrenchBen I have updated link location. Please feel free to try out.

**Comment by FrenchBen** [comment]
Thanks @Sharkrit added the info to our wiki as well:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#windows-processbaselayer-error

**Comment by SimonSDA** [comment]
The fix:
Set-ItemProperty -Path 'HKLM:SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\Containers' -Name VSmbDisableOplocks -Type DWord -Value 1 -Force

Did not work for me :( I'm on Windows 10 Enterprise x64 and getting the error:

failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\fda242042d30b3e8503b20cf2f701e089440342832a69c6dcf700d695a1b0559: The system cannot find the path specified.

When trying to download the hello-world-nginx image. The official 'hello-world' image works fine (though I had to change the network from 'bridge' to 'Virtual Switch(automatic)'). Have tried restarting Docker etc.

**Comment by mdkitzman** [comment]
I too am seeing this error with the `hello-world-nginx` image.  My error output is the same as @SimonSDA and setting the registry value call did not work for me either.

**Comment by marcelfalliere** [comment]
Having the same error, on a windows k8s cluster. Any ideas ?

**Comment by rajeshanayaka** [comment]
I am having same error with Docker for Windows 18.09 on Windows 10 - 1803 

docker build -t emptyimage .
Sending build context to Docker daemon  3.072kB

Step 1/2 : From scratch
 ---> 
Step 2/2 : add ./ /
docker : re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\66f8de26edbe62fd8464cf3b438f145b0fb0eb681fa2e5d3abc90a4fd984f375: The system cannot find the path specified.
