### ISSUE TITLE
Unable to get docker image of openresty/openresty

### ISSUE THREAD

**Issue by snowwolf007cn** [docker/kitematic#2458]
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/openresty/openresty/manifests/trusty: Get https://auth.docker.io/token?account=snowwolf&scope=repository%3Aopenresty%2Fopenresty%3Apull&service=registry.docker.io: EOF"}

**Comment by FrenchBen** [comment]
No information provided or steps to replicate - Closing
