### ISSUE TITLE
win7 - while shutting down get stuck indefinitely on Virtual box interface has active connection

### ISSUE THREAD

**Issue by ankur07garg** [docker/kitematic#2470]
### Expected behavior
Win7 shutdown - should shutdown without ay issues
### Actual behavior
win7 - while shutting down get stuck indefinitely on Virtual box interface has active connection. If force shutdown, corrupts docker...
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Unfortunately we've seen a lot of issues with Virtualbox and why we've moved towards our Desktop solutions of Docker for Mac and Docker for Windows

**Comment by stereokai** [comment]
@FrenchBen @ankur07garg this still happens to me with the latest Kitematic on Windows 10. Was there ever a solution for this since then?

**Comment by ldeluigi** [comment]
I need a solution, don't close the issue if unsolved
