### ISSUE TITLE
HTTP Code 500 Server Error on Kitematic (When I'm creating "hello-world-nginx")

### ISSUE THREAD

**Issue by SomboChea** [docker/kitematic#2472]
### Steps to reproduce the behavior

> **I'm got error like that!**

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:56662->10.0.2.3:53: i/o timeout"}

**Comment by shaoxiong789** [comment]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Akitematic%2Fhello-world-nginx%3Apull&service=registry.docker.io: read tcp 10.0.2.15:54122->50.17.62.194:443: read: connection reset by peer"}

> I met the wrong is this

**Comment by shaoxiong789** [comment]
You need to change the mirror image of the domestic in the docker toolbox

**Comment by FrenchBen** [comment]
This has been documented many times in the WIKI:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
