### ISSUE TITLE
Change Volume does not show hidden files/directories on macOS

### ISSUE THREAD

**Issue by Franky47** [docker/kitematic#2475]
### Expected behavior
When selecting the local folder for a volume, one would expect to see the same contents in the dialog as what can be seen in the Finder, like hidden files/folders (revealed with `defaults write com.apple.finder AppleShowAllFiles YES`):
![finder](https://cloud.githubusercontent.com/assets/1174092/24078674/4f698ed6-0c74-11e7-8dfd-db6aa5e7970f.png)

### Actual behavior
The Kitematic local folder browser does not show hidden files / directories:
![kitematic](https://cloud.githubusercontent.com/assets/1174092/24078675/546605ea-0c74-11e7-8086-8a104cc2126c.png)

### Information about the Issue
* macOS 10.12.3
* Kitematic 0.13.0
* Docker 17.03.0-ce-mac2 (15654)

### Steps to reproduce the behavior
On an existing container (that exposes volumes):
  1. Navigate to Settings > Volumes
  2. In the Configure Volumes section, click `Change`.

**Comment by FrenchBen** [comment]
We use the normal electron 'Show Finder' and don't have a ton of leverage to show more/less on the window. I would check your default preferences for new Finder windows opened as I get the exact same window in my setup.

**Comment by Franky47** [comment]
Thanks, here's the solution that helped me for the record:
http://apple.stackexchange.com/questions/100384/how-to-get-open-file-selector-to-show-hidden-files

The trick is that file dialogs are not considered the same as Finder windows, therefore respond to different sets of properties.

**Comment by FrenchBen** [comment]
Thanks for sharing your fix @Franky47
