### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: EOF"}

### ISSUE THREAD

**Issue by seven1986** [docker/kitematic#2477]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mloder1337** [comment]
Had the same issue via corporate proxy. Fixed it via this method on Win7
1 Setup environment variables "HTTP_PROXY" and "HTTPS_PROXY"
2 Delete the 'C:\Users\<username>\.docker\machine\machines\default'
3 Run command "docker-machine create -d virtualbox --engine-env HTTP_PROXY=YOURPROXY create -d virtualbox default"
4 Startup Kitematic like normal

I also had to kill VBox processes along the way
Hope this helps

**Comment by FrenchBen** [comment]
This has been documented many times in the WIKI:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by mloder1337** [comment]
I read that wiki, it didnt fix the issue.

**Comment by HyperBrain** [comment]
I have the same issue. It seems that it is an IPv6 issue for me - The 500 error refers to [::1] instead of the IPv4 address. Is is possible to lock it to IPv4?
