### ISSUE TITLE
(HTTP code 500) server error  connection reset by peer

### ISSUE THREAD

**Issue by shaoxiong789** [docker/kitematic#2479]
I'm got error like that!
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Akitematic%2Fhello-world-nginx%3Apull&service=registry.docker.io: read tcp 10.0.2.15:54122->50.17.62.194:443: read: connection reset by peer"}

**Comment by FrenchBen** [comment]
This has been documented many times in the WIKI:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
