### ISSUE TITLE
下载不下来

### ISSUE THREAD

**Issue by datafu** [docker/kitematic#2481]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by emilkje** [comment]
These issues are getting ridiculous and completely destroys meaningful notifications on this repository. You have my sympathies @FrenchBen for having to put up with all the garbage. No offence to you OP.

The title translates to "Download is down" according to google translate btw.

**Comment by FrenchBen** [comment]
@emilkje thanks for the kind words - I've been thinking about implementing an auto-close feature, because of this.

@datafu Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
