### ISSUE TITLE
Download dashdb-local

### ISSUE THREAD

**Issue by vannlam** [docker/kitematic#2489]
### Actual behavior
unauthorized: authentication required
### Steps to reproduce the behavior

  1. ...MacBook Pro
  2. ...Kitematic
  3. New Container, search for ibmdashdb/local:latest or ibmdashdb/local:v1.6.0-kitematic
  4. Click on CREATE

**Comment by FrenchBen** [comment]
Please make sure that you've validated your 
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified

**Comment by vannlam** [comment]
Hi,

In my account settings, my primary email is already verified.

But still ...


_________________________________________________________
Vann Lam
IBM Certified IT Specialist
IBM France | IBM Analytics Technical Sales
+33158752608 (phone) | +33673193286 (cell) | +33158752608 (fax) | 38802608 
(tie-line)

**Comment by FrenchBen** [comment]
Are you using a local registry? what happens if you do: `docker pull ` your image in a terminal?

**Comment by vannlam** [comment]
Hi,

Sorry for the delay I was very busy the last past days.

the command : docker pull ibmdashdb/local:latest ended up successfully

What is the right docker command to 'run' to deploy the container from 
that image ?

Thanks
_________________________________________________________
Vann Lam
IBM Certified IT Specialist
IBM France | IBM Analytics Technical Sales
+33158752608 (phone) | +33673193286 (cell) | +33158752608 (fax) | 38802608 
(tie-line)
