### ISSUE TITLE
Ability to list already pulled images.

### ISSUE THREAD

**Issue by kputland** [docker/kitematic#249]
Can't find https://github.com/dockerfile/elasticsearch in containers search, but I was able to pull and start a container from the docker shell.

Karls-MacBook-Pro:~ karl$ docker pull dockerfile/elasticsearch
Pulling repository dockerfile/elasticsearch
b64ee46fa1b3: Download complete 
511136ea3c5a: Download complete 
f0dde87450ec: Download complete 
76b658ecb564: Download complete 
4faa69f72743: Download complete 
2103b00b3fdf: Download complete 
4303edc5e986: Download complete 
14dfde0f38c5: Download complete 
d489fc3e869f: Download complete 
a8253f7d9cc1: Download complete 
38cf7a363b14: Download complete 
d9343f29a1c4: Download complete 
9cb3dca21a1f: Download complete 
313a8af0a9bf: Download complete 
a639da5da7ec: Download complete 
75d984c37217: Download complete 
ac48cf46299c: Download complete 
ff0f3e05eb59: Download complete 
54e20d5331e7: Download complete 
a434cf75a201: Download complete 
316e635d58e2: Download complete 
71e2875c2614: Download complete 
a134289d3679: Download complete 
4c9cc126c9f2: Download complete 
Status: Downloaded newer image for dockerfile/elasticsearch:latest
Karls-MacBook-Pro:~ karl$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ansible/centos7-ansible       latest              9bddea9a5c52        17 hours ago        453.1 MB
dockerfile/elasticsearch      latest              b64ee46fa1b3        39 hours ago        799.9 MB
elasticsearch                 latest              9aa7a23eccbe        4 days ago          509.9 MB
kitematic/hello-world-nginx   latest              a7b9e0669702        13 days ago         7.899 MB
Karls-MacBook-Pro:~ karl$ docker 
Display all 194 possibilities? (y or n)
Karls-MacBook-Pro:~ karl$ docker docker run -d -p 9200:9200 -p 9300:9300 dockerfile/elasticsearch
Karls-MacBook-Pro:~ karl$ docker run -d -p 9200:9200 -p 9300:9300 dockerfile/elasticsearch
093c04e70ade90b76ef2af6e2e5428c21375f2dcfe213ff73415d33dd109dc90
Karls-MacBook-Pro:~ karl$ docker ps
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS              PORTS                                            NAMES
093c04e70ade        dockerfile/elasticsearch:latest   "/elasticsearch/bin/   25 seconds ago      Up 24 seconds       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   nostalgic_galileo   
Karls-MacBook-Pro:~ karl$

**Comment by fredmeews** [comment]
Similarly, [imported] (https://docs.docker.com/reference/commandline/cli/#import) images do not show up in the UI list.

**Comment by jeffdm** [comment]
Thanks for the issue.

@fredmeews I think this may be separate - the UI list only shows _containers_. Unfortunately there's no current way to create a container from a local image that you've built or imported.

**Comment by cfljam** [comment]
There is an obvious need to be able to select local images, not just ones form Dockerhub. THis seems like the right issue thread

**Comment by pazustep** [comment]
A nice way to do this would be a "Local" filter in the new container panel. A related issue would be local image management: check which are dangling, and allow image deletion (dangling or not, with the approppriate warnings).

**Comment by dmarley** [comment]
Agree -- with pazustep -- this would make the app really impressive -- allow for local management prior to pushing up to a repo (private or public)

**Comment by joao-guerra** [comment]
+ 1 for this, without it the app loses most of its interest.
I have a lot of images that I imported from a VM that a used.
When I installed the app I was looking for something like pazustep described and was shocked to find out that it didn't exist.

**Comment by jeffdm** [comment]
Thanks for the feedback and great points, all.

**Comment by TeckniX** [comment]
This is probably not perfect, but I was able to implement some of the above features, via the following:
https://github.com/tecknix/kitematic/tree/list-images

![local-images](https://cloud.githubusercontent.com/assets/33699/8758836/49e5df9e-2cb7-11e5-9a8e-717d29538191.png)

I'll need to add support for tags and such.
Any downloaded image will show up on this tab, additionally you can now build your images from cli and see them listed within kitematic. 

Feedback is appreciated.

**Comment by FrenchBen** [comment]
This is probably not perfect, but I was able to implement some of the above features, via the following:
https://github.com/tecknix/kitematic/tree/list-images

![local-images](https://cloud.githubusercontent.com/assets/33699/8758836/49e5df9e-2cb7-11e5-9a8e-717d29538191.png)

I'll need to add support for tags and such.
Any downloaded image will show up on this tab, additionally you can now build your images from cli and see them listed within kitematic. 

The example here is from the Static Python example:
https://github.com/elyase/docker/tree/master/staticpython
```bash
$ cd staticpython
$ docker build -t fb/staticpy .
```

Feedback is appreciated.

**Comment by jeffdm** [comment]
@FrenchBen awesome!

**Comment by djsly** [comment]
:+1: 
Thanks @FrenchBen 
@jeffdm really looking for this PR! 

Kitematic is great! even when your a CLI addict.

**Comment by klousiaj** [comment]
:+1: Would love to see this.

**Comment by FrenchBen** [comment]
@klousiaj It's still pending in the PR - Just needs to be updated and looked at again

**Comment by rixx** [comment]
+1 for showing and administrating local images. Anything that could be done to speed this up?

**Comment by psychemedia** [comment]
Any chance of this getting added sometime soon? I use Kitematic as a local app launcher, and one of the images I've started using requires a fresh start each time from the base image, which is a faff having to try to remember the name of the image each time I want to launch it.

**Comment by dalegaspi** [comment]
+1

**Comment by FrenchBen** [comment]
This has been released a few versions ago - Closing this issue.

**Comment by MicahZoltu** [comment]
This doesn't appear to actually work in the latest version of Kitematic.  When I click on `My Images` tab it says `Cannot find any local images` but if I click on the `DOCKER CLI` button and then type `docker images` it lists a bunch of images, both built locally and pulled from docker hub.

`docker version`:
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

Kitematic version: `0.12.0`

**Comment by FrenchBen** [comment]
@MicahZoltu Can you show the list of images you obtained with `docker images` ?

**Comment by MicahZoltu** [comment]
@FrenchBen 
![image](https://cloud.githubusercontent.com/assets/886059/20074032/77721054-a4e3-11e6-8d21-8e08177adf89.png)

**Comment by MicahZoltu** [comment]
`hello-world:latest` and `node:4` and `microsoft/dotnet` are all official Docker Hub images, the ones starting with `zoltu/` are personal Docker Hub images.  The rest are locally built images.

**Comment by FrenchBen** [comment]
@MicahZoltu Thanks for the info - I'll try to replicate on my end and will report back.

**Comment by allyn-psyonix** [comment]
2 years later and this still appears to be an issue
