### ISSUE TITLE
not found container

### ISSUE THREAD

**Issue by ribbear** [docker/kitematic#2490]
### Expected behavior
expect container
### Actual behavior
not found container
### Information about the Issue
HTTP code is 404 which indicates error: undefined - {"message":"manifest for jamesandariese/go-solaris-amd64:latest not found"}

### Steps to reproduce the behavior

  1. search solaris
  2. or/and create jamesandariese/go-solaris-amd64:latest

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/jamesandariese/go-solaris-amd64/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
