### ISSUE TITLE
container image name with multiple / included in the name doesn't display correctly in the UI and creation of the image is not usable

### ISSUE THREAD

**Issue by bogdanmaxim** [docker/kitematic#2491]
### Expected behavior
image name, owner name should be displayed correctly
when clicking the create button the image should be created successfully
### Actual behavior
the image name is not displayed correctly
"owner/org" field shows first part of the path
"image name" field shows second part of the path
when clicking create kitmatic returns an image 
### Information about the Issue
might be a duplicate of #1840 
### Steps to reproduce the behavior
1. create a local container image similar to "docker-registry.company.test/product/component"
2. open kitematic
3. go to my images
4. try to create the image
5. it returns a 404 not found error

**Comment by FrenchBen** [comment]
This has been previously documented in previous issue. Closing in favor of earlier issue. thanks!
