### ISSUE TITLE
HTTP code is 404 which indicates error: undefined - {"message":"manifest for dockershelf/python:latest not found"}

### ISSUE THREAD

**Issue by cclauss** [docker/kitematic#2494]
Kitematic, create official Python just after the new CPython 3.6.1 dropped.

### Actual behavior

HTTP code is 404 which indicates error: undefined - {"message":"manifest for dockershelf/python:latest not found"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/dockershelf/python/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by cclauss** [comment]
I am not quite sure that I understand.  These three URLs are **out of sync**.
* https://github.com/docker-library/official-images/blob/master/library/python
* https://hub.docker.com/_/python
* https://store.docker.com/images/1ae86987-df14-4741-9433-d9602a4da995

The first two are Python 3.6.**1** and the last one is 3.6.**0**

**Comment by FrenchBen** [comment]
Look at the link I posted - there's more than 1 python image maintained by different people
