### ISSUE TITLE
download jenkins error.

### ISSUE THREAD

**Issue by aaqqxx** [docker/kitematic#2496]
### Expected behavior
下载jenkins
### Information about the Issue
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: read tcp 10.0.2.15:51440->50.17.62.194:443: read: connection reset by peer"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
