### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by yangfu132** [docker/kitematic#2497]
### Steps to reproduce the behavior

  1. ...
  2. ...

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/2f/2fb3cac83ed8d9dc13763ffa4e2655c2b98f81e1db82ccf18ec47c7ba98ad225/data?Expires=1490257947&Signature=G7Ty3UUGbtEyy5wOduHtOwBU1Hw23C6xRahk2uEBnPOWX3OFT6VBxjeZcMuOAySueW-kvCK1DbKpJyQpk-K4vD9ZylBbWP9~zprBsF3-HyNIBgmO54rGngmiWxwrvGTep50r~Q8SEuyCFw3yL0F4pEH85HiKDc9IR8STPidzeDA_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
