### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:43308->10.0.2.3:53: i/o timeout"}

### ISSUE THREAD

**Issue by Noslenesilv** [docker/kitematic#2498]
### Expected behavior
Image download (docker pull)
### Actual behavior
code 500 -  server timeout
### Information about the Issue
when i try to do docker pull image it gives me server timeout and it also happens in kitematic. after i installed docker and stuff i did docker run ubuntu and it actually downloaded the ubuntu image since it wasnt found in my local machine.

### Steps to reproduce the behavior

  1. Have windows 10 HOME
  2. Install Docker Toolbox
  3. run: docker pull image
ps- i'm using MINGW64 the console when u run docker quickstart, but it also happens in powershell

**Comment by Noslenesilv** [comment]
somehow it seems to loose network configuration, i restart pc then when running docker quickstart terminal it gave me a new network ip setup and everything went fine

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
