### ISSUE TITLE
manifest for jgajek/cuckoo-docker:latest not found

### ISSUE THREAD

**Issue by icepaule** [docker/kitematic#2503]
### Actual behavior
Error message: (HTTP code 404) unexpected - {"message":"manifest for jgajek/cuckoo-docker:latest not found"} during install/clone from docker
### Information about the Issue
Used Kitematic (lastes version) on WIndows.

### Steps to reproduce the behavior
Just try to install yourself

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/jgajek/cuckoo-docker/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
