### ISSUE TITLE
OpenHab docker container download error

### ISSUE THREAD

**Issue by ionultd** [docker/kitematic#2508]
### Expected behavior
Download of Docker container for Openhab from Openhab latest using Kitematic for windows
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for openhab/openhab:latest not found"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/openhab/openhab/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
