### ISSUE TITLE
Containers created on CLI are not being displayed in Kitematic

### ISSUE THREAD

**Issue by kbowerma** [docker/kitematic#251]
I think this should be possible but I can't figure out how to do.    I want images/containers that I have built to show up the gui.

I tried opening the terminal and building a images and did not see it.   Then I started the container but still did not see it.  Is this not supported?

Thanks great work so far this is awesome so far

**Comment by jeffdm** [comment]
Hi there! Thanks for creating an issue.

Kitematic syncs with what you do on the CLI as long as commands are run while pointed at the right Docker VM & ENgine. To make sure your shell is correctly either use:

- `$(docker-machine env dev)` in a terminal or click the Docker Terminal button in Kitematic:

Or click on the button shown below:
![screen shot 2015-03-12 at 8 43 59 pm](https://cloud.githubusercontent.com/assets/251292/6631202/99a634c0-c8f8-11e4-834b-f79d509f3f77.png)

Does this work at all?

In terms of being able to build an image in Kitematic - that's not yet possible - sorry.

**Comment by kykim** [comment]
Having the same issue.

I opened the Docker Terminal by clicking the button as describe, created an image, then created a container. It's running. But it doesn't appear in the Kitematic window.

**Comment by mchiang0610** [comment]
@kykim Do you have the procedure to help us reproduce on our side? 

Thanks!

**Comment by hrwebasst** [comment]
docker run -d -t -p 8282:80 -p 443:443 -v /Users/me/work/drupal_docker/logs:/var/log/apache2  -v /Users/me/work/drupal_docker/status:/var/www/html/status status

starts a container
4868fd8d79b7        status:latest      "/bin/sh -c 'bash -C   2 minutes ago       Up 2 minutes        0.0.0.0:443->443/tcp, 3306/tcp, 0.0.0.0:8282->80/tcp   prickly_bardeen

and then kitematic doesn't show the created container. I built the container from the command line after clicking "Open terminal to use docker command line"

**Comment by d3v1an7** [comment]
:+1:

Was working in `0.7.7`, but containers no longer show in `0.8.5`.
<img width="1920" alt="screen shot 2015-10-01 at 3 01 29 pm" src="https://cloud.githubusercontent.com/assets/4087799/10215965/f40ee1b8-684f-11e5-8067-4825e729c556.png">

All containers were created and started via command line.  
I have this in `.bash_profile` and `.bashrc`:
```sh
if [ $(type -P docker-machine) ]; then eval $(docker-machine env dev); fi
```

**Comment by FrenchBen** [comment]
@d3v1an7 the VM that kitematic uses is called 'default' - Change your `.bashrc` to:
`if [ $(type -P docker-machine) ]; then eval $(docker-machine env default); fi`

**Comment by klousiaj** [comment]
:+1: I'm having the same problem. 

Kitematic 0.9.4
El Capitan 10.11.2

Locally built image on the command line started through the Kitematic GUI. Start the container via the CLI with a docker run and the container is not shown in the Kitematic container list.

`c99873e9eaf6        klousiaj/wso2-das:1.0   "/bin/sh -c 'sh ./wso"   3 hours ago         Up 3 hours          7711/tcp, 8243/tcp, 8280/tcp, 9443/tcp, 9763/tcp, 10397/tcp   condescending_easley`

![screen shot 2015-12-24 at 6 17 11 pm](https://cloud.githubusercontent.com/assets/4754718/11998381/9d96f58e-aa6a-11e5-9444-d1e3c33e4113.png)

**Comment by FrenchBen** [comment]
@klousiaj anyway to share the Dockerfile (and assets) for this image? I'd like to try and replicate this.

**Comment by klousiaj** [comment]
I haven't identified a pattern with a particular Dockerfile/image. I have a couple of published images that you can find source for on my [github](https://github.com/klousiaj). But it doesn't seem that my problem is limited to only images built locally through the CLI.

It was working for a while. I restarted and am seeing the following now:
<table>
<tr>
<td>CONTAINER ID</td>
<td>IMAGE</td>
<td>COMMAND</td>
<td>CREATED</td>
<td> STATUS </td>
<td> PORTS </td>
<td> NAMES </td>
</tr>
<tr>
<td> 27024cb47b35 </td>
<td>klousiaj/wso2-das:latest</td>
<td>"/bin/sh -c 'sh ./wso"</td>
<td> 3 minutes ago </td>
<td> Up 23 seconds </td>
<td> 0.0.0.0:32774->7611/tcp, 0.0.0.0:32773->7711/tcp, 0.0.0.0:32772->9160/tcp, 0.0.0.0:32771->9443/tcp, 0.0.0.0:32770->9763/tcp, 0.0.0.0:32769->21000/tcp </td>
<td> wso2-das </td>
</tr>
<tr>
<td> 2cfc4f6ce786 </td>
<td>mysql:latest </td>
<td>"/entrypoint.sh mysql"</td>
<td> 6 minutes ago</td>
<td> Up 2 minutes </td>
<td> 0.0.0.0:3306->3306/tcp</td>
<td>mysql</td>
</tr>
<tr>
<td> 901d8abae64c </td>
<td>klousiaj/h2-db:latest</td>
<td>"/bin/sh -c 'java -cp"</td>
<td>2 days ago</td>
<td>Exited (143) 44 hours ago </td>
<td>&nbsp;</td>
<td> h2-db</td>
</tr>
<tr>
<td> 8e2d37681ce8 </td>
<td>klousiaj/wso2-am:latest </td>
<td>"/bin/sh -c 'sh ./wso"</td>
<td>3 days ago</td>
<td>Exited (137) 2 hours ago</td>
<td>&nbsp;</td>
<td>wso2-am</td>
</tr>
<tr>
<td> 7b865d931290 </td>
<td>centos:7</td>
<td>"bash"</td>
<td>4 days ago</td>
<td>Exited (0) 4 days ago</td>
<td>&nbsp;</td>
<td>cranky_wright</td>
</tr>
</table>

![screen shot 2015-12-29 at 3 49 56 pm](https://cloud.githubusercontent.com/assets/4754718/12041919/d8528fa8-ae43-11e5-8621-0eb32dabea2e.png)

I'm not sure where my other containers went...

**Comment by FrenchBen** [comment]
OK great - last question for my qa, can you provide the commands you run with each?
`docker build -t klousiaj/wso2-das:latest .` ?
`docker run -itd --name wso2 klousiaj/wso2-das:latest` ?

**Comment by klousiaj** [comment]
You got it...

I was able to just bring the UI back up inline. I'm thinking that this might be an issue with processes not all dying in sync. I went into Activity Monitor and force killed a couple of docker-machine processes and the next start of Kitematic brought it all back up in line. (I will say, this no longer seems related to the OP's issue)

**Comment by klousiaj** [comment]
You got it...

I was able to just bring the UI back up inline. I'm thinking that this might be an issue with processes not all dying in sync. I went into Activity Monitor and force killed a couple of docker-machine processes and the next start of Kitematic brought it all back up in line. (I will say, this no longer seems related to the OP's issue)

**Comment by FrenchBen** [comment]
seems something else is happening in the background. Thanks for the update. I'll close this issue as it's becoming unrelated. 

Would you mind creating a new issue for this (keeping the OP from getting a bunch of emails)

**Comment by fenglianxu** [comment]
I have seen the same issue but if you click **refresh container list** from the **view** menu, you will see all of the running container in Kitematic UI.

**Comment by pranavgarg** [comment]
If you are on mac and have the native docker and somehow it was showing earlier and all of a sudden one day you don't see the containers in kitematic. Then check the kitematic settings ->VM settings-> Use VirtualBox instead of Native on next restart is checked. Uncheck it and it will show all the containers.

**Comment by hotdang-ca** [comment]
I had to turn ON that feature (it was off), and on kitematic restart, turn it back off. 

Once that was done, we were good.

**Comment by btwq** [comment]
Thanks @hotdang-ca's suggestion worked for me too

**Comment by leosco** [comment]
Why is this issue closed? This is basic behavior that needs to be supported. If you pull a docker image from a non-Docker Hub source, you lose all the functionality of Kitematic!

**Comment by leosco** [comment]
@pranavgarg If I do that, it breaks my Kitematic, telling me to install Docker Toolbox. I follow the link, and it tells me that Docker Toolbox is deprecated and that I shouldn't use it.

**Comment by 456wyc** [comment]
我遇到了同样的问题，看了大家的问题，我尝试把 kitematic 退出后再启动，然后就可以看到列表了。可能是重启电脑后，自动打开原来的窗口引起的。
