### ISSUE TITLE
hello-word-nginx.   raise error

### ISSUE THREAD

**Issue by haurx** [docker/kitematic#2514]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: Get https://auth.docker.io/token?account=haur&scope=repository%3Akitematic%2Fhello-world-nginx%3Apull&service=registry.docker.io: read tcp 10.0.2.15:54426->50.17.62.194:443: read: connection reset by peer"}

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
