### ISSUE TITLE
stuck on virtual box installation screen

### ISSUE THREAD

**Issue by greggjaskiewicz** [docker/kitematic#2517]
### Expected behavior
I should be able to go back from the virtual box installation screen back to previous screens

### Actual behavior
stuck on the "we're sorry" "virtual box is not installed..." screen, All I have in terms of options is "retry setup", "get toolbox", none of which are the options I want to pick from 

### Steps to reproduce the behavior

  1. open the app, login, etc
  2. go to "instal virtual box" option (can't remember the actual detail of it). 

Now I'm stuck...

**Comment by FrenchBen** [comment]
I'm guessing at some point you picked a different choice than native, which then gets 'saved' within the app. 
Please see this similar issue and fix for the time being:
https://github.com/docker/kitematic/issues/2499#issuecomment-289133965
