### ISSUE TITLE
Need some more basic functions in the application

### ISSUE THREAD

**Issue by joebeady** [docker/kitematic#252]
Hello, and congratulations are in order, but recently downloaded kinematic 0.5.10 and noticed the following:
1)  Stop /Start a container functions don't exist, but would help out plenty (Restart works on stopped container but would be better to have both stop & start.
2)  No way to augment the Docker run command for a container with options if needed.  Would be nice if this was done as well.  
3)  Also a way to view the images and delete them may be handy as well.

Regards,

**Comment by jeffdm** [comment]
This is fantastic - thanks for creating an issue!

**Comment by poisa** [comment]
:+1:

**Comment by chryton** [comment]
:+1: 

FYI if you need to stop it run:

```
docker stop container-name
```

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
