### ISSUE TITLE
unable to download container

### ISSUE THREAD

**Issue by sanju99sen** [docker/kitematic#2521]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:41326->10.0.2.3:53: i/o timeout"}

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
