### ISSUE TITLE
gwh_docker_kitematic

### ISSUE THREAD

**Issue by gaowenhui** [docker/kitematic#2522]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gaowenhui** [comment]
gwh_docker_kitematic

**Comment by FrenchBen** [comment]
No information provided or steps to replicate - Closing

**Comment by gaowenhui** [comment]
欢迎来到王者农药

**Comment by FrenchBen** [comment]
如果您不提供详细信息，您希望如何获得帮助？
