### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by shahmaulikn** [docker/kitematic#2527]
### Expected behavior
I should not get 404
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for shahmaulikn/appdynamics:latest not found"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/shahmaulikn/appdynamics/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
