### ISSUE TITLE
we can't find a native setup

### ISSUE THREAD

**Issue by suparek** [docker/kitematic#2528]
I have a question："we can't find a native setup.....",  I have setup docker in my computer，my environment is Ubuntu kylin 16.10，why comes this？？？

**Comment by FrenchBen** [comment]
@suparek we try to look for the docker socket and talk to it - Can you provide me with the output of:
`docker info`
`docker version`
`ls -l /var/run/docker.sock`

**Comment by mil1i** [comment]
I am also experiencing this on Solus.

```
✗ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib64/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-03-31 14:09:21 MST; 6min ago
     Docs: https://docs.docker.com
 Main PID: 6190 (dockerd)
   CGroup: /system.slice/docker.service
           ├─6190 /usr/bin/dockerd --storage-driver=overlay -H fd://
           └─6210 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-contain...

 ✗ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

 ✗ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   78d18021ecba00c00730dec9d56de6896f9e708d78d18021ecba00c00730dec9d56de6896f9e708d
 Built:        Fri Jan 27 21:44:08 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

 ✗ ls -l /var/run/docker.sock
srw-rw---- 1 root docker 0 Mar 31 14:09 /var/run/docker.sock=
```

**Comment by suparek** [comment]
my output ：
$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
   Active: active (running) since 六 2017-04-01 09:09:05 CST; 56min ago
     Docs: https://docs.docker.com
 Main PID: 1975 (dockerd)
    Tasks: 22 (limit: 4915)
   Memory: 90.8M
      CPU: 6.412s
   CGroup: /system.slice/docker.service
           ├─1975 /usr/bin/dockerd -H fd://
           └─2196 docker-containerd -l unix:///var/run/docker/libcontainerd/dock

$ systemctl status docker.socket
● docker.socket - Docker Socket for the API
   Loaded: loaded (/lib/systemd/system/docker.socket; enabled; vendor preset: en
   Active: active (running) since 六 2017-04-01 09:08:49 CST; 57min ago
   Listen: /var/run/docker.sock (Stream)

$ sudo docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-22-generic
Operating System: Ubuntu Kylin 16.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55 GiB
Name: yangtz-All-Series
ID: WTUB:CMIZ:NB2W:3GTI:3YGG:JSPQ:VYFE:XVTU:37ST:M5XZ:KO53:K2G2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

$ sudo docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:50:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:50:18 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ ls -l /var/run/docker.sock
srw-rw---- 1 root docker 0 4月   1 09:08 /var/run/docker.sock

**Comment by FrenchBen** [comment]
@suparek Thank you for providing this great output. 

As you've shown in your different commands, your current user cannot use `docker version` without using `sudo` - Kitematic will have the exact same rights as your current user. 

Please see the post-installation steps here:
https://docs.docker.com/engine/installation/linux/linux-postinstall/

**Comment by fedz03** [comment]
I've experienced the same issue but what i notice is that i did not run kitematic in SU

**Comment by MurhafSousli** [comment]
I have the same problem, my current user is a member of sudo group and still not working

**Comment by ThiagoBfim** [comment]
This can happen because it's without sudo user.

execute: `id -nG ` This will list all user that can use docker.

If your user has not in the list use this command:

```
sudo usermod -aG docker ${USER}
su - ${USER}
```

Then restart the session and try to open kitematic.

Hope this helps.

**Comment by ImtiazeA** [comment]
I solved my issue following **ThiagoBfim** instructions.

**Comment by oshai** [comment]
For me, it didn't work. However, killing the process solved the issue.
```
ps -efww | grep -i kitematic
```
to find it.

**Comment by jcreforme** [comment]
how about running the command
`sudo kitematic`

**Comment by cardboardcode** [comment]
Following jcreforme's instruction worked for me.

**Comment by hottime** [comment]
> I have a question："we can't find a native setup.....", I have setup docker in my computer，my environment is Ubuntu kylin 16.10，why comes this？？？

I had been installed several times, and I found a solution finally.

But, I don't know it's perfect solution for you.

It's very simple and i think it's a bug.

You try to run your Docker Desktop with Administrator privilege.

Have a good time.
