### ISSUE TITLE
Microsoft/IIS Image Container error while downloading through Kitematic

### ISSUE THREAD

**Issue by scarymrgrey** [docker/kitematic#2529]
### Expected behavior
successfully downloaded
### Actual behavior
Error:"unknown blob"
### Steps to reproduce the behavior

  1. run Docker on MacOS X Sierra
  2. try to download Microsoft/IIS image with Kitematic

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
