### ISSUE TITLE
docker CLI get an image

### ISSUE THREAD

**Issue by ayc868** [docker/kitematic#2535]
### Information about the Issue
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/04/04b44316b6af194b7c3caf632ffc5aa4ccc0a4c39c120ea2279ee85493a5d889/data?
6Q: x509: certificate signed by unknown authority

   company has firewall - proxy server

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Mac: Use Docker for Mac
Windows: Use Docker for Windows
Toolbox: See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
