### ISSUE TITLE
docker install jenkins error

### ISSUE THREAD

**Issue by changqing91** [docker/kitematic#2537]
HTTP code is 500 which indicates error: server error - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fjenkins%3Apull\u0026service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
