### ISSUE TITLE
Changing Volume setting not honored

### ISSUE THREAD

**Issue by Toontje** [docker/kitematic#2539]
Kitematic 0.13.0 on Sierra 10.12.4
Container that maps out the /logs directory to ~/Documents/Kitematic/containername/logs.
I am changing the mapping to /private/var/log/containername.

### Expected behavior
Logs are stored in /private/var/log/containername

### Actual behavior
Logs are still stored in ~/Documents/Kitematic/containername/logs.

### Information about the Issue
I tried to solve this by restarting the container, restarting Docker and Kitematic. Behaviour still the same. 
In Docker the /private directory is shared.

### Steps to reproduce the behavior

  1. Create a container with a mapping for a logs directory.
  2. Start the container and check if logs are created.
  3. Stop the container.
  4. Change the mapping.
  5. Start the container and check where the logfiles are created.

**Comment by FrenchBen** [comment]
@Toontje how are you doing `Change the mapping`?
When a container has settings that change, a new container is created in its place with the new settings. Could it be that you're looking at a different container all together?

**Comment by Toontje** [comment]
1. Stop container
2. In Kitematic, container, Settings, Volumes, Change the one i want to change.
3. Start container

What am i missing?

**Comment by FrenchBen** [comment]
Do you get the same error if you don't stop the container?

**Comment by Toontje** [comment]
Yes.

**Comment by WizX20** [comment]
Same issue here on Windows 10 Pro x64, behaviour:
- Permission denied exceptions
- When the container is running, and you click the volume on the HOME tab, it will switch back to the default location: c:/users/etc...
- When the last folder starts with a 'C' the path gets corrupted, for example: d:\MyContainer\Config; Will be translated to: \d\MyContainerC:onfig

**Comment by FrenchBen** [comment]
@WizX20 Please see how to share drives in windows:
https://docs.docker.com/docker-for-windows/#shared-drives

**Comment by WizX20** [comment]
On Windows 10:

- When the container is running, and you click the volume on the HOME tab, it will switch back to the default location: c:/users/etc...
- When the last folder starts with a 'C' the path gets corrupted, for example: d:\MyContainer\Config; Will be translated to: \d\MyContainerC:onfig

**Comment by FrenchBen** [comment]
@WizX20 can you open a new issue and provided steps to replicate?
