### ISSUE TITLE
gitlab-ce   ------ why can't download it ?

### ISSUE THREAD

**Issue by peterlevel1** [docker/kitematic#2543]
### Expected behavior
just download the gitlab

### Actual behavior
it can not do that

### Information about the Issue
error when download it

### Steps to reproduce the behavior

  1. search gitlab
  2. then download the gitlab-ce 
  3. error ........

**Comment by FrenchBen** [comment]
I'm unable to reproduce the issue as `gitlab-ce` downloads properly for me. 
![gitlab-ce](https://cloud.githubusercontent.com/assets/3965324/24624519/03df7356-1861-11e7-9078-42c28f3da7b9.png)

If you would like some help, please provide proper steps to reproduce along with `docker version` and Kitematic version used.
