### ISSUE TITLE
Chrome Dev Tools opens on startup

### ISSUE THREAD

**Issue by dylanparry** [docker/kitematic#2546]
### Expected behavior

Kitematic should open without showing Chrome Dev Tools

### Actual behavior

Chrome Dev Tools opens on startup

### Information about the Issue

Running Docker using the 17.03.1-ce package on Windows 10. Installed Kitematic (v0.35.4) by copying/pasting into `C:\Program Files\Docker\Kitematic` as instructed.

### Steps to reproduce the behavior

  1. Open Kitematic via right-clicking on Docker system tray icon
  2. Dev Tools opens before showing the proper Kitematic window

![kitematic](https://cloud.githubusercontent.com/assets/3692873/24697539/851e1e7e-19e5-11e7-9b2b-765767933152.png)

**Comment by FrenchBen** [comment]
@dylanparry I have the devtools setup to open during dev, but shouldn't be opening in the final package - I'll look through the recent changes to get this fixed. 
Thanks for the issue.

**Comment by dylanparry** [comment]
Thanks. It looks like something has added a `NODE_ENV` environment variable to my Windows profile, and it's set to `development`. I’ve deleted it from my profile, so that _should_ fix it at my end. What might be a good idea though is to set the Dev Tools to enabled but not displayed in in development mode, as it's only a few key presses away to show it but at least it won't be visible by default for anyone who for some reason finds themselves in the same situation as me :)

**Comment by FrenchBen** [comment]
@dylanperry thanks for the update on this. I commented out part of the functionality in the latest release. 
The idea was to make it easy for people to do light debugging with a simple env var, but your point of a few shortcut away is correct. 
I will close this issue for now.
