### ISSUE TITLE
Set/mounts volume using `~/path`

### ISSUE THREAD

**Issue by unsalted** [docker/kitematic#2547]
### Expected behavior
Set/Mount volume with absolute path

### Actual behavior

Set/mounts volume using `~/path`

### Information about the Issue

```
(HTTP code 500) server error - invalid bind mount spec "/Users/meehan/Code/smart-memory:[/home/mdp/src]": invalid volume specification: '/Users/meehan/Code/smart-memory:[/home/mdp/src]': invalid mount config for type "bind": invalid mount path: '[/home/mdp/src]' mount path must be absolute
```

### Steps to reproduce the behavior

  1. launch
  2. got to volumes
  3. change
  4. select directory

**Comment by FrenchBen** [comment]
Please see: 
https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume

**Comment by unsalted** [comment]
Sorry I'll move this a step further, and yes it's still a bug but it's a different one.  If I have set two volumes through my dockerfile, and I go to set the host directory through kitematic, it errors on the second volume that I would ideally do next, because it doesn't have a directory set on the host... but of course it doesn't because I've only managed to set one.
