### ISSUE TITLE
Why is 0.13.1 installed with Docker Toolbox and not 0.17.1?

### ISSUE THREAD

**Issue by JCzz** [docker/kitematic#2549]
### Expected behavior
Why is 0.13.1 installed with Docker Toolbox?

And not 0.17
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
The version of kitematic doesn't necessarily reflect the version of docker. 
The current update is available within our edge channel and will be part of the next stable release. 
Meanwhile feel free to grab the latest version from GitHub and provide us with feedback :)
