### ISSUE TITLE
Timeout error - Try and restart your VM by running:

### ISSUE THREAD

**Issue by dax-westerman** [docker/kitematic#2552]
### Expected behavior

Loading image 

### Actual behavior

Timeout error - Try and restart your VM by running:

"docker-machine restart default" in a terminal

### Steps to reproduce the behavior

  1. ...
  2. ...

Attempted restart with "docker-machine restart default".  restart hun, went to task manager, killed two docker-machine.exe processes, tried again with command, hung.

**Comment by FrenchBen** [comment]
It sounds like this issue is related to docker-machine. 
Please open an issue in `docker/machine` for further help.
