### ISSUE TITLE
unknown blob

### ISSUE THREAD

**Issue by dax-westerman** [docker/kitematic#2553]
### Expected behavior

retrieve IIS image

### Actual behavior

unknown blob

### Information about the Issue

![image](https://cloud.githubusercontent.com/assets/11837526/24802204/b0c3b524-1b6c-11e7-9002-5d1cdf7d184d.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by SharePointOscar** [comment]
@dax-westerman are you trying to use the IIS Image on a non-windows machine? Just curious, I've seen this message when that is the case.

**Comment by dax-westerman** [comment]
No, was trying to run this on a windows machine.  However, on reading more it looks like I have a “linux container” running.  So, I expect that I need to figure out how to switch this?  Or should it be automatic?

**Comment by SharePointOscar** [comment]
Can you let me know what image name you are using?  There are several, and Microsoft provides IIS images for Linux and IIS for Windows respectively (microsoft/iis).  What is your Docker setup on your Windows machine?

You can have  a Linux host within your Windows machine as depicted here below.  To switch between machines, you will need to use `eval(docker-machine env MACHINE_NAME)` . Once you are using the right machine, you can then execute the docker run command to bring up the container.

![docker setup](https://github.com/SharePointOscar/docker-windows-box/raw/master/images/docker-windows-box.png)

**Comment by dax-westerman** [comment]
Sure, I’ve tried a few, but as an example the most recent attempt was

[cid:image001.png@01D2AFAB.AE2DA0E0]

My apologies, this is my first foray into using Docker and Kitematic, so I must ask a quick question.  My goal is to run IIS within Docker on a Windows machine.  As such I need to run

eval(docker-machine env MACHINE_NAME)

where MACHINE_NAME is my local machine?

Thank you,
Dax

**Comment by SharePointOscar** [comment]
Understood, and no worries :)  

For everyone's sake here, I think this is not a Kinematic issue, so perhaps not using this channel to address your issue would be appropriate.  I do recommend you take a look at https://github.com/SharePointOscar/docker-windows-box which shows you how to setup your Windows box to work with Docker, it contains scripts that @StefanScherer has generously provided and should get you going fast!

**Comment by FrenchBen** [comment]
As @SharePointOscar mentioned these are Windows Container images only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
