### ISSUE TITLE
not able to downlaod the neo4j-cluster image via kitematic

### ISSUE THREAD

**Issue by jaags** [docker/kitematic#2560]
### Actual behavior

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: lame referral"}
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
