### ISSUE TITLE
SETUP ERROR: Could not determine IP from docker-machine. 

### ISSUE THREAD

**Issue by jrvilda** [docker/kitematic#2561]
MINGW64 ~
$ docker-machine inspect
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.99.100",
        "MachineName": "default",
        "SSHUser": "docker",
        "SSHPort": 6274,
        "SSHKeyPath": "C:\\Users\\******\\.docker\\machine\\machines\\default\
\id_rsa",
        "StorePath": "C:\\Users\\******\\.docker\\machine",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "VBoxManager": {},
        "HostInterfaces": {},
        "CPU": 1,
        "Memory": 1024,
        "DiskSize": 20000,
        "NatNicType": "82540EM",
        "Boot2DockerURL": "",
        "Boot2DockerImportVM": "",
        "HostDNSResolver": false,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HostOnlyNicType": "82540EM",
        "HostOnlyPromiscMode": "deny",
        "UIType": "headless",
        "HostOnlyNoDHCP": false,
        "NoShare": false,
        "DNSProxy": true,
        "NoVTXCheck": false,
        "ShareFolder": ""
    },
    "DriverName": "virtualbox",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [],
            "Ipv6": false,
            "InsecureRegistry": [],
            "Labels": [],
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": true,
            "RegistryMirror": [],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Agent": false,
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Image": "swarm:latest",
            "Strategy": "spread",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": [],
            "ArbitraryJoinFlags": [],
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "C:\\Users\\******\\.docker\\machine\\certs",
            "CaCertPath": "C:\\Users\\******\\.docker\\machine\\certs\\ca.pem",
            "CaPrivateKeyPath": "C:\\Users\\******\\.docker\\machine\\certs\\ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "C:\\Users\\******\\.docker\\machine\\machines\\default\\server.pem",
            "ServerKeyPath": "C:\\Users\\******\\.docker\\machine\\machines\\default\\server-key.pem",
            "ClientKeyPath": "C:\\Users\\******\\.docker\\machine\\certs\\key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "C:\\Users\\******\\.docker\\machine\\certs\\cert.pem",
            "ServerCertSANs": [],
            "StorePath": "C:\\Users\\******\\.docker\\machine\\machines\\default"
        }
    },
    "Name": "default"
}

**Comment by jrvilda** [comment]
$ docker -D ip default
docker: 'ip' is not a docker command.
See 'docker --help'

**Comment by jrvilda** [comment]
00:00:25.634963 NAT: Link up
00:00:43.158799 VMMDev: Guest Log: VBoxService 5.1.18 r114002 (verbosity: 0) linux.amd64 (Mar 15 2017 16:30:21) release log
00:00:43.158828 VMMDev: Guest Log: 00:00:00.000087 main     Log opened 2017-04-11T10:30:32.023897000Z
00:00:43.160504 VMMDev: Guest Log: 00:00:00.001815 main     OS Product: Linux
00:00:43.161166 VMMDev: Guest Log: 00:00:00.002479 main     OS Release: 4.4.59-boot2docker
00:00:43.161202 VMMDev: Guest Log: 00:00:00.002515 main     OS Version: #1 SMP Fri Mar 31 17:24:41 UTC 2017
00:00:43.161235 VMMDev: Guest Log: 00:00:00.002548 main     Executable: /sbin/VBoxService
00:00:43.161243 VMMDev: Guest Log: 00:00:00.002549 main     Process ID: 2374
00:00:43.161248 VMMDev: Guest Log: 00:00:00.002549 main     Package type: LINUX_64BITS_GENERIC
00:00:43.165380 VMMDev: Guest Log: 00:00:00.006691 main     5.1.18 r114002 started. Verbose level = 0
00:00:43.168895 VMMDev: Guest Log: 00:00:00.010192 vminfo   rtldrNativeLoad: dlopen('libdbus-1.so.3', RTLD_NOW | RTLD_LOCAL) failed: libdbus-1.so.3: cannot open shared object file: No such file or directory
00:00:43.168954 VMMDev: Guest Log: 00:00:00.010265 vminfo   Error: Unable to connect to system D-Bus (1/3): D-Bus not installed
00:00:43.176510 VMMDev: Guest Additions capability report: (0x0 -> 0x0) seamless: no, hostWindowMapping: no, graphics: no
00:00:43.324308 NAT: IPv6 not supported
00:00:45.092721 NAT: DHCP offered IP address 10.0.2.15
00:00:45.093007 NAT: DHCP offered IP address 10.0.2.15
00:00:48.168343 VMMDev: Guest Log: 00:00:05.011613 vminfo   Error: Unable to connect to system D-Bus (2/3): D-Bus not installed
00:00:53.167770 VMMDev: Guest Log: 00:00:10.013533 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed
00:02:00.008464 NAT: DNS#0: 10.200.202.227
00:02:00.008498 NAT: DNS#1: 10.200.202.243
00:02:00.008505 NAT: DNS#2: 192.168.227.1
00:02:00.008510 NAT: DNS#3: 192.168.193.2
00:15:00.649197 NAT: DNS#0: 10.200.202.227
00:15:00.649234 NAT: DNS#1: 10.200.202.243

**Comment by jrvilda** [comment]
$ docker run hello-world
time="2017-04-11T13:15:25+02:00" level=info msg="Unable to use system certificat
e pool: crypto/x509: system root pool is not available on Windows"
Unable to find image 'hello-world:latest' locally
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Get http
s://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:
53: server misbehaving.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by FrenchBen** [comment]
Please provide the output of:
Mac:
```
$ env | grep -i "docker"
```
Windows:
```
Get-Childitem -Path Env:* | Sort-Object Name
```

**Comment by jrvilda** [comment]
Does not display anything containing the word docker:
PS C:\Users\jrodvild> Get-Childitem -Path Env:* | Sort-Object Name | findstr -I -N docker
PS C:\Users\jrodvild>

**Comment by jrvilda** [comment]
Finally, docker run well, one problem with local proxy.
I have managed to install a web application, with several containers (openproject & openproject-postgres) but Kitematic still gives the same error.
I now have the environment variables set well, http_proxy, htts_proxy and no_proxy.
