### ISSUE TITLE
Prestashop image doesn't download

### ISSUE THREAD

**Issue by mannygt** [docker/kitematic#2564]
### Expected behavior
Download prestashop image 
### Actual behavior
It crash when almost finish downloading
### Steps to reproduce the behavior

  1. Look for bitnami image of prestashop
  2. download

![image](https://cloud.githubusercontent.com/assets/24414759/24963814/e8610f38-1f5c-11e7-8f43-d7bc8b928d80.png)

**Comment by FrenchBen** [comment]
<img width="886" alt="prestashop" src="https://cloud.githubusercontent.com/assets/3965324/24988577/af87ce40-1fbb-11e7-9559-8685a6e30e62.png">
I'm unable to replicate this issue - You may need to reset your installation of Docker.
