### ISSUE TITLE
I can't download tcgabiolinksgui

### ISSUE THREAD

**Issue by woodhaha** [docker/kitematic#2566]
I'm interesting in TCGAbiolinksGUI, but the installing procedures for me is complicated and confusing. I have tried many times to download "tcgabiolinksgui" with Kitematic, but the downloading process never complete, I don't know why. Please give me a guidance, thanks for your kindly help!

**Comment by FrenchBen** [comment]
Please open an issue with the image owner:
https://hub.docker.com/r/tiagochst/tcgabiolinksgui/

The image is 3GB, which is probably why it's taking so long to download
