### ISSUE TITLE
Can any please resolve this error 

### ISSUE THREAD

**Issue by Rajitha15** [docker/kitematic#2567]
### Expected behavior
ailed to register layer: error creating overlay mount to /var/lib/docker/overlay2/51a8bbc4dfd0302dc737f076e1bfbb67de6796cd389b87014d286dd90dd90a44/merged: no such file or directory
### Actual behavior

getting erro

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
I would try to do a reset on the app
