### ISSUE TITLE
下载docker镜像时，出现了500错误

### ISSUE THREAD

**Issue by xiaopangalf** [docker/kitematic#2569]
镜像下载不下来啊，出现下面错误，什么情况啊
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: server misbehaving"}

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
