### ISSUE TITLE
Manifest not found 

### ISSUE THREAD

**Issue by flamusdiu** [docker/kitematic#2576]
### Expected behavior
`docker pull  flamusdiu/archlinux-devel:latest` should pull the inital file and start building image
### Actual behavior
`HTTP code is 404 which indicates error: undefined - {"message":"manifest for flamusdiu/archlinux-devel:latest not found"}` is the continual error that I am getting. It doesn't work from either Kitematic (where this error comes from) or docker cli.

### Information about the Issue
I am getting the error when attempting a pull. I looked around the docker site but did not notice any new changing to docker. I am using the latest CE.

### Steps to reproduce the behavior

`docker pull  flamusdiu/archlinux-devel:latest`

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/flamusdiu/archlinux-devel/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by flamusdiu** [comment]
Well, I am the owner ... haha. I think I figured it out from what you said. I swore it was working when I put it up ... /sigh
