### ISSUE TITLE
Ability to edit host VM's amount of memory & CPU

### ISSUE THREAD

**Issue by jamshid** [docker/kitematic#258]
How do you set the amount of memory and cpu used by the vm you create? Is there a `profile` file like docker? Or do you just have to edit `dev` in the Virtual Box gui?

**Comment by jeffdm** [comment]
Thanks for the issue!

Editing the VM directly in VBox is probably your best bet for now.

**Comment by marcosscriven** [comment]
Is the plan here that eventually Docker will simply support OS X, obviating the boot2docker VM? If so, do you know the timeline for that? If this is the case, then I'd agree it's not worth spending any time building out a GUI for the VM settings.

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
