### ISSUE TITLE
Kitematic hangs with "UPDATING" bluebox and removes container after setting volume local folder on Windows 10 if the drive is not shared in Docker

### ISSUE THREAD

**Issue by budzek** [docker/kitematic#2580]
### Expected behavior
To get a popup information about a need to enable drive sharing in Docker settings.
### Actual behavior
The blue box "UPDATING" stays, nothing else happens in GUI. The container is removed from docker !!!
### Information about the Issue

Kitematic hangs with "UPDATING" bluebox and removes container after setting volume local folder on Windows 10 if the drive is not shared in Docker.

### Steps to reproduce the behavior

  1. Don't have the drive shared in docker settings
  2. In the volume that was already mounted (without any local folder) try to set local folder.
  3. The bluebox "UPDATING" will be shown and will remain.
  4. The docker container on which the operation was performed is removed from docker - it will be missing after Kitematic restart, as well as in result of 'docker ps -a'.

Docker: 
Version 17.03.1-ce-win5 (10743)
Channel: stable
b18e2a5

**Comment by FrenchBen** [comment]
Without the drive share, it's impossible to mount it in the container, which then fails and there isn't much that kitematic can do atm. 
Kitematic is not coupled to a specific setup and thus cannot detect the folders that are shared or not. 

If you have suggestions on how a `docker run ...` can detect that the folder isn't shared, I'm happy to discuss this as a proposal. Closing this issue in favor of a proposal on how it could be handled.
