### ISSUE TITLE
creating oprudkyi/laravel-bootstrap-adminlte-starter-kit

### ISSUE THREAD

**Issue by brazitech** [docker/kitematic#2582]
getting the following error     
(HTTP code 404) unexpected - {"message":"manifest for oprudkyi/laravel-bootstrap-adminlte-starter-kit:latest not found"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/oprudkyi/laravel-bootstrap-adminlte-starter-kit/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
