### ISSUE TITLE
impossible to login with long email

### ISSUE THREAD

**Issue by remisharrock** [docker/kitematic#2591]
### Expected behavior
you can enter the email entirely during login
### Actual behavior
you cannot enter the email entirely during login (maximum number of characters is reached)
### Information about the Issue
when you try to login with a long email, the maximum number of characters can be reached

### Steps to reproduce the behavior

  1. ... try to enter a long email at login
  2. ...

**Comment by FrenchBen** [comment]
This has been fixed in a recent PR, which has yet to be released. 
https://github.com/docker/kitematic/pull/2574

Thanks for the issue!
