### ISSUE TITLE
Manifest not found

### ISSUE THREAD

**Issue by wesaidso** [docker/kitematic#2592]
### Expected behavior
Download docker image

### Actual behavior
Failing with 404 error code

### Information about the Issue
HTTP code is 404 which indicates error: undefined - {"message":"manifest for psmith/synology-docker-homebridge:latest not found"}

### Steps to reproduce the behavior

1. In Kitematic select image Synology-docker-homebridge

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/psmith/synology-docker-homebridge/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
