### ISSUE TITLE
Kitematic v0.17.0 can't be opened on Mac

### ISSUE THREAD

**Issue by JamesChevalier** [docker/kitematic#2593]
### Expected behavior

Open Kitematic from the Applications folder without issue.

### Actual behavior

Open Kitematic from the Applications folder, and receive a popup with the message:

> “Kitematic (Beta)” can’t be opened because the identity of the developer cannot be confirmed.
> Your security preferences allow installation of only apps from the Mac App Store and identified developers.

### Information about the Issue

This issue does not occur for v0.13.1 & I would prefer not to have to change my security preferences in order to continue using Kitematic.

### Steps to reproduce the behavior

  1. Download [v0.17.0 for mac](https://github.com/docker/kitematic/releases/download/v0.17.0/Kitematic-0.17.0-Mac.zip)
  2. Unzip the file
  3. Drag the unzipped file into the Applications folder (replacing the existing version, if prompted)
  4. Run Kitematic
  5. Receive error

**Comment by FrenchBen** [comment]
6. Right-Click App, click 'open' 🎉

**Comment by JamesChevalier** [comment]
Thanks - that's an interesting workaround to the process globally changing this by going through System Preferences > Security & Privacy > General > Allow applications downloaded from > Anywhere

It does still seem like something fundamentally changed between 0.13.1 and 0.17.0, though. I'd argue that we shouldn't have to circumvent security settings in order to run Kitematic.

Do you have a long term fix planned?

**Comment by FrenchBen** [comment]
@JamesChevalier I rebuilt the mac App and uploaded it to the github release - It passed all of the signing checks. 
If you want to give that a try, I'd be happy to get your feedback on it.

**Comment by JamesChevalier** [comment]
Thanks @FrenchBen - that worked perfectly!
I appreciate all your help.

**Comment by JamesChevalier** [comment]
Version [0.17.1](https://github.com/docker/kitematic/releases/tag/v0.17.1) has brought this issue back.

**Comment by FrenchBen** [comment]
@JamesChevalier I just updated the zip - something happened on upload where it gets corrupted and becomes 3x the size.
Can you try it again?

**Comment by JamesChevalier** [comment]
That fixed it up! Thanks @FrenchBen
