### ISSUE TITLE
Add a refresh button

### ISSUE THREAD

**Issue by albfan** [docker/kitematic#2594]
### Expected behavior

When running docker from command line be able to reflect new containers on kitematic

### Actual behavior

You need to start or stop another container to simulate a refresh and see the rest of running containers

### Information about the Issue

docker ce on windows

### Steps to reproduce the behavior

Run a container outside kitematic

**Comment by FrenchBen** [comment]
Refresh is already in place; you can do so by clicking the word `Containers` or by going to the `View` menu and clicking on `Refresh Container List` - The shortcut key is `CMD+R`

**Comment by albfan** [comment]
Cool, thanks

**Comment by hoegge** [comment]
There is no `view` menu in Kitematic (on Windows). How should people know and know about the refresh shortcut key?
