### ISSUE TITLE
Unable to create hello-world-nginx container

### ISSUE THREAD

**Issue by sguergachi** [docker/kitematic#2595]
### Expected behavior
I expect there to be no errors when I create the hello-world-nginx container
### Actual behavior
I get this error:
`failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\e3aa1900af2570a1cd0f895be0fd2e2aca16087041191013ba779d9dc3de84d1: The system cannot find the path specified.`
### Information about the Issue
Using Windows containers on the latest version of Docker for Windows and latest version of Kitematic.

### Steps to reproduce the behavior

  1. Click Create button on hello-world-nginx
  2. See error after a while of it trying to download and create the container.

**Comment by FrenchBen** [comment]
What do you get if you do:
`docker run --rm -it -P kitematic/hello-world-nginx` from PowerShell?

**Comment by sguergachi** [comment]
I get `C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\18c6bcaada584352cbbf4d74e020444f63afef2ffc64314bf587c00eb6a04695: The system cannot find the path specified..`

**Comment by sguergachi** [comment]
When I switch to Linux Containers it works. I guess this is a Docker for Windows specific issue?

**Comment by joejordan** [comment]
@sguergachi I also stumbled on this when first getting started with Docker on Windows. That particular container is Linux-based.

**Comment by sguergachi** [comment]
Perhaps a solution would be for the UI to reflect which container is windows/Linux based. Or even better: filter out containers that aren't compatible from view.

**Comment by FrenchBen** [comment]
@sguergachi There is some thoughts in the works as to how we can reliably do this. 
Feel free to open a new issue as a proposal to how Kitematic should handle it.
