### ISSUE TITLE
[macOS] identity of developer cannot be confirmed

### ISSUE THREAD

**Issue by aduermael** [docker/kitematic#2596]
I'm getting that message when opening Kitematic on a Mac. I guess that's because the app is not signed correctly.

![screen shot 2017-04-26 at 1 08 11 pm](https://cloud.githubusercontent.com/assets/6775074/25454576/cd5beef8-2a81-11e7-8843-793cac5fe3cf.png)

Installing Kitematic from Docker for Mac is hard:

- select "Kitematic" in the menu
- a popup invites you to download it and place it in `/Applications` directory
- if you retry you see that error message, without the "open" button
- you need to right click on Kitematic in  `/Applications` to see it
- after doing this, it will finally  work from Docker for Mac menu

I don't think we had that issue when we released Docker for Mac... Has anything been changed in Kitematic's release process since then?

**Comment by FrenchBen** [comment]
I think that shows up no matter what, if the app isn't downloaded from the app store. If you know of a better way to do this, I'm all ears.

**Comment by WilsonGiese** [comment]
@FrenchBen, I don't think that is true. As long as you've got a Developer ID cert you should be able to sign the app and distribute as is without seeing this warning. Whether or not there is currently a Developer ID to use is another story. 

See  [Apple Developer ID](https://developer.apple.com/developer-id/) and  [Distribution guide](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html)

**Comment by FrenchBen** [comment]
@WilsonGiese I was thinking of the different pop-up - The application was repackaged to prevent the above screenshot from happening.

**Comment by MarusaThem** [comment]
this is permission when you install app not have authentic. you could use teminal with comand line as below for fix

sudo spctl --master-disable

**Comment by KadirMYilmaz** [comment]
That works, MarusaThem. Thank you!

> this is permission when you install app not have authentic. you could use teminal with comand line as below for fix
> 
> sudo spctl --master-disable

Works perfectly! Thank you!
