### ISSUE TITLE
Preferences for Exec Button : 

### ISSUE THREAD

**Issue by ddavisgraphics** [docker/kitematic#2598]
This is a future enhancement, I like the convenience of the exec button, but I hardly use it because I prefer to use bash for autocompletion. So what I'll describe are my complete opinions on a way that I would use it more and maybe others.  

### Expected behavior

Preferences Menu: 
Exec Preference 
- bash || sh ((boolean options or radio buttons)) 

**if shell is chosen** 
`bash -c "clear && docker exec -it hydratest sh"` 
**if bash is chosen**  
`bash -c "clear && docker exec -it hydratest bash"` 

### Actual behavior

Clicking the exec button  runs `bash -c "clear && docker exec -it hydratest sh"`

**Comment by FrenchBen** [comment]
This has already been implemented in this PR: https://github.com/docker/kitematic/pull/2493
Our next release of Kitematic will have it.
