### ISSUE TITLE
Unable to pull docker image for SQL Server On Linux

### ISSUE THREAD

**Issue by kdssg** [docker/kitematic#2599]
### Expected behavior
I was trying to download SQL Server On Linux from Docker GitHub location.
### Actual behavior
I was trying to download SQL Server On Linux from Docker GitHub location.
### Information about the Issue
I was trying to download SQL Server On Linux from Docker GitHub location. Unable to download it and we are getting an error.
"(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}"

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
Additionally Microsoft SQL server is a windows image and thus will not work on a linux machine
