### ISSUE TITLE
Ubuntu Software Center reports Kitematic_0.17.0_amd64.deb 

### ISSUE THREAD

**Issue by megha-n-bodke** [docker/kitematic#2601]
### Expected behavior
Ubuntu Software Center should install Kitematic_0.17.0_amd64.deb without any issues.

### Actual behavior
It warns package is of bad quality. I need to click on "Ignore and Install" to install it.
![kitematiclinuxbadqualitypopup](https://cloud.githubusercontent.com/assets/13938070/25553073/a7e9ee3e-2cc7-11e7-8fd3-d06bb25eb537.png)

**Comment by FrenchBen** [comment]
@megha-n-bodke Can you provide the 'details' under that pop-up. A couple of things are checked with packages that may be causing this pop-up; anything that can help us fix the issue would be great.

**Comment by tito-culver** [comment]
@FrenchBen
not sure if it's the same thing with @megha-n-bodke's case but when I tried on ubuntu 14.04, bunch of "wrong-file-owner-uid-or-gid" comes out. (sry capture might be hard to see in Jap UI but it says Bad quality package) 

![ubuntu1404](https://user-images.githubusercontent.com/29378814/27040962-8052fd74-4fcd-11e7-93e2-58a1f7a66864.png)

**Comment by FrenchBen** [comment]
@tito-culver thanks for the screenshot - It looks like the electron packaging doesn't seem to include the boilerplate `%: dh ...` debhelper rule that's commonly seen in packaging guides, debhelper will call `dh_fixperms` to set the proper permissions on the application once installed. 

If you care to look into it and help us fix this, it would be appreciated!

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
