### ISSUE TITLE
HTTP code is 404 which indicates error

### ISSUE THREAD

**Issue by lochaitis** [docker/kitematic#2603]
### Expected behavior

Should be able to download the image from my repo on Dockerhub

### Actual behavior

Locates the image but when I try download I get the below error

HTTP code is 404 which indicates error: undefined - {"message":"manifest for costalochaitis/cfckubectl:latest not found"}

### Steps to reproduce the behavior

  1. ... try download image again gets same error
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/costalochaitis/cfckubectl/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
