### ISSUE TITLE
Expose Container Environment variables from a container onto the host

### ISSUE THREAD

**Issue by mikedevita** [docker/kitematic#2604]
I realize this may already be possible but I think I'm just missing the settings somewhere?

### Expected behavior
expected environment variables to be set when a container is set with the appropriate environment variables... for example with the mysql container.

This helps to allow my node.js app which is running on my actual host to interpret the username, password, port, host automatically based on `process.env.<CONTAINERNAME>_$VARIABLE`

e.g.
```
<CONTAINERNAME>_HOST = 127.0.0.1
<CONTAINERNAME>_PORT = 32768
<CONTAINERNAME>_USER = SOMEUSER
<CONTAINERNAME>_PASSWORD = SOMEPASSWORD
```

### Actual behavior
nothing is set, causing me to have to update my configs each time the port or host changes.
### Steps to reproduce the behavior
1. build a new mysql container
2. define the appropriate required environment variables
3. start the container
4. run `env` to check to see if the environment variables are set

**Comment by FrenchBen** [comment]
This is somewhat going against the container logic - If you were to start your node.js app within a container, it would be able to connect to your mysql db via the internal network.
Most would actually use a compose file to get these connected.
