### ISSUE TITLE
Create / Pull requests fail with a 404 for bfolkens/docker-opencv

### ISSUE THREAD

**Issue by shirishr** [docker/kitematic#2606]
### Expected behavior
Expected docker image to be cloned
### Actual behavior
Error: (HTTP code 404) unexpected - {"message":"manifest for bfolkens/docker-opencv:latest not found"}
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/bfolkens/docker-opencv/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
