### ISSUE TITLE
Localhost no longer serves website properly

### ISSUE THREAD

**Issue by AppreciateIT** [docker/kitematic#2607]
![screen shot 2017-05-02 at 6 43 13 pm](https://cloud.githubusercontent.com/assets/24654665/25642456/f6579aec-2f67-11e7-945e-7bbb40f61ac6.png)
I have a container set up hosting Drupal through nginx, and php7.0-fpm.  It was working perfectly until, I believe, I installed Kubernetes and pushed the container to dockerhub, and later to Google Cloud.  Now the container still shows up in Kitematic, it is up and running and I can access it through the CLI ("Exec" option).  The ports are set up as localhost:8082 -> Docker port: 80 as usual.  Everything seems fine but I'm no longer able to access the container via the browser.  When I hit http://localhost:8082 now I get: 
"You have chosen to open:

which is: DMS file (549 bytes)
from http://localhost:8082"...

See attached screenshot.

### Expected behavior
 Access website on Docker Container.

### Actual behavior
Get handed a DMS file.

### Information about the Issue
This is on Mac OSX 

### Steps to reproduce the behavior
Not sure any more what I've done to cause this.  Hoping you can provide a clue.

Any help as to how to get this working again or where I went astray would be much appreciated.

Cheers,

Matt

**Comment by FrenchBen** [comment]
can you provide a curl of:
```
curl -i http://localhost:8082/
```
Is this container something we can look at? Technically we're serving the data properly on localhost, as you're getting a response. The issue is the content that your service is sending back.

**Comment by AppreciateIT** [comment]
Hmm, that gave me this:

> HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Thu, 04 May 2017 00:27:25 GMT
Content-Type: application/octet-stream
Content-Length: 549
Last-Modified: Wed, 05 Apr 2017 22:53:48 GMT
Connection: keep-alive
ETag: "58e5757c-225"
Accept-Ranges: bytes

<?php

/**
 * @file
 * The PHP page that serves all page requests on a Drupal installation.
 *
 * All Drupal code is released under the GNU General Public License.
 * See COPYRIGHT.txt and LICENSE.txt files in the "core" directory.
 */

use Drupal\Core\DrupalKernel;
use Symfony\Component\HttpFoundation\Request;

$autoloader = require_once 'autoload.php';

$kernel = new DrupalKernel('prod', $autoloader);

$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();

$kernel->terminate($request, $response);

**Comment by AppreciateIT** [comment]
So it looks like this is an Nginx configuration problem, I think.  Am I right?  I have to add another clause to the .conf to handle this file?  I don't understand why it called it a DMS file.  Anyway, I think I get it.  Thanks for the clue.  I'll let you know how it goes.

Cheers,

Matt
