### ISSUE TITLE
set http_proxy not possible

### ISSUE THREAD

**Issue by chrigifrei** [docker/kitematic#2612]
### Expected behavior
Connect to DockerHub

### Actual behavior
Connection Refused

### Information about the Issue
Using kitematic behind HTTP/S proxy.

### Steps to reproduce the behavior

- Connect to Docker Hub
- Enter Credentials

**Comment by FrenchBen** [comment]
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
