### ISSUE TITLE
Copy Image data to host volume upon initialization

### ISSUE THREAD

**Issue by AppreciateIT** [docker/kitematic#2613]
### Expected behavior
An image created from a Dockerfile has volumes,  if these image directories contain data and the host directories (volumes) don't, then copy the data into the host.  If "docker create" or "docker run" specifies the host directory with the -v flag, the data from the image should be copied into the host directory.  Ideally there should be a different flag to mount the volumes from the host onto the container.  

### Actual behavior
Host directories are empty upon initialization.  Where's the data?

### Information about the Issue
In Docker's documentation: [https://docs.docker.com/engine/tutorials/dockervolumes/#data-volumes](https://docs.docker.com/engine/tutorials/dockervolumes/#data-volumes) it says
"Volumes are initialized when a container is created. If the container’s base image contains data at the specified mount point, that existing data is copied into the new volume upon volume initialization. (Note that this does not apply when mounting a host directory.)"

It is a little ambiguous as to whether this even happens when running a container from the command line.  The Docker documentation seems to indicate that the same flag (-v) is used for the "Volume initialization" and when "mounting a host directory".  The only distinction mentioned in the examples is that in the former, no host directory is specified.  In the latter the host directory is specified.  This makes no sense because you are not telling Docker where to copy the data in the former, and in the latter the data from the host is used.  

### Steps to reproduce the behavior

  1. Create or Run container with volumes configured in the Dockerfile with or without -v flag
  2. Configure the directories onto the host in Kitematic (it doesn't seem to pick them up from the container even if it was specified in the command line)
3. Navigate to the directories specified on the host.
4. The data is not there.

I realize this may be a Docker issue, not necessarily a Kitematic one.  Is there a solution I've overlooked?  

Cheers,

Matt

**Comment by AppreciateIT** [comment]
The only solution I've found is copying the data in after the volumes are mounted. PITA

**Comment by FrenchBen** [comment]
@AppreciateIT Hi Matt, volumes are initialized on container run, but are somewhat hidden and 1-shot. You can see them all by doing `docker volume ls`.
When you bind mount a volume, the `init` process that generates the data still needs to happen. 
If it happens after the fact, then your volume will overwrite what data had been created in the container.

**Comment by AppreciateIT** [comment]
Thanks, I'll monkey with it.  Still learning.  Much appreciated.
