### ISSUE TITLE
Kitematic Windows:  (HTTP code 404) unexpected - {"message":"manifest for USERNAME/myrepository:latest not found"}

### ISSUE THREAD

**Issue by ky3zdhou3ttf** [docker/kitematic#2615]
### Expected behavior

open repository in Windows Kitematic (alpha) and edit it; after successfully creating it on Docker Hub website

### Actual behavior

error message in Windows Kitematic (alpha)
(HTTP code 404) unexpected - {"message":"manifest for USERNAME/myrepository:latest not found"}

### Steps to reproduce the behavior

create new Docker Hub account
create new empty repository (private) on Docker Hub
open Kitematic (alpha) on Windows 10
sign in
select the repository
click on "create"
<img width="815" alt="2017_05_05_15_49_28_kitematic" src="https://cloud.githubusercontent.com/assets/28444444/25748235/b95c8d4c-31aa-11e7-9880-e1767a5c1150.png">

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/USERNAME/myrepository/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
