### ISSUE TITLE
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/jboss/wildfly/manifests/latest: unauthorized: incorrect username or password"}

### ISSUE THREAD

**Issue by sensha4u** [docker/kitematic#2619]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified
