### ISSUE TITLE
Download and install error - Docker Hello Work Image

### ISSUE THREAD

**Issue by wsalmi** [docker/kitematic#2620]
### Expected behavior
Download and Install imagem

### Actual behavior
Download - OK
Install - Fail

### Information about the Issue
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\a4bd1588531737e832266833cfd93f5c183f105ed6482939d435ae82610c60be: O sistema não pode encontrar o caminho especificado.

### Steps to reproduce the behavior

  1. Download Docker Hello Work Image
  2. Await...

**Comment by FrenchBen** [comment]
What's your Docker version? Are you running Docker for Windows?

**Comment by wsalmi** [comment]
I'am using 17.03.1-ce-win12 (12058).

**Comment by FrenchBen** [comment]
What's the output of:
```
docker info
```

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
