### ISSUE TITLE
[macOS] Kitematic destroys existing vm named "default" managed by docker-machine when using other driver than virtualbox.

### ISSUE THREAD

**Issue by fabsb** [docker/kitematic#2621]
### Expected behavior

Kitematic use existing vm (created via docker-machine) named "default".

### Actual behavior

Kitematic **removes/destroys** the existing vm named _default_ when using other driver than _virtualbox_.

### Information about the Issue

This only happens when using other docker-machine drivers like [xhyve driver](https://github.com/zchee/docker-machine-driver-xhyve).

docker version:
```
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8.1
 Git commit:   89658be
 Built:
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker-machine version:
```
$ docker-machine version
docker-machine version 0.11.0, build 5b27455
```

docker-machine-driver-xhyve version:
```
$ brew info docker-machine-driver-xhyve
docker-machine-driver-xhyve: stable 0.3.2 (bottled), HEAD
```

kitematic version: `0.17.0`

Kitematic checks whether a virtualbox vm exists named "default and since I'm using the xhyve driver, the default vm managed by docker-machine gets destroyed. Kitematic should not use virtualbox directly when probing existing vms but rather ask docker-machine.

The logic for destroying/creating vms when starting happens [here](https://github.com/docker/kitematic/blob/master/src/utils/SetupUtil.js#L137).

### Steps to reproduce the behavior

  1. Install docker, docker-machine via brew
```
$ brew install docker docker-machine
```
 
  2. Install xhyve driver for docker-machine by following [instructions](https://github.com/zchee/docker-machine-driver-xhyve#install)
```
$ brew install docker-machine-driver-xhyve

# docker-machine-driver-xhyve need root owner and uid
$ sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
$ sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
```

  3. Create default machine
```
$ docker-machine create --driver xhyve default
```

  4. docker-machine reports a vm named _default_ using driver _xhyve_
```
$ docker-machine ls
NAME      ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER        ERRORS
default   -        xhyve    Running   tcp://192.168.64.4:2376           v17.05.0-ce
```

  5. Install kitematic via brew cask
```
$ brew cask install kitematic
```
  6. Start kitematic
  7. docker-machine reports a vm named _default_ using driver _virtualbox_
```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           v17.05.0-ce
```

**Comment by FrenchBen** [comment]
It's been documented that Kitematic will use/create a VM called `default` - I would suggest naming your other vm something else than default. 
For example:
`docker-machine create --driver xhyve xdefault` will solve all of your issues
