### ISSUE TITLE
http 401 - unexpected

### ISSUE THREAD

**Issue by bnmnetp** [docker/kitematic#2622]
### Expected behavior
Click on jenkins to install new container

### Actual behavior
Get error message:
```
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: unauthorized: incorrect username or password"}
```
However jenkins appears to download and continue working towards installation in the background

### Information about the Issue

Both Docker and Redis think I am logged in.

OK, after letting things go for a while, I could tell that it wasn't really downloading and installing jenkins, or even the hello_world app.  Restarting Kitematic cleared up the problem somewhat... I attempted to install redis as well and got an error message similar to the one above.   Quitting and restarting then kick starts the redis installation...

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified


You could also remove your `.docker` credentials from your home directory and clear the credentials.
