### ISSUE TITLE
unable to stop container

### ISSUE THREAD

**Issue by archmisha** [docker/kitematic#2623]
### Expected behavior
clicking stop on kitematix should stop container

### Actual behavior
(HTTP code 502) unexpected - Bad response from Docker engine

### Information about the Issue
latest docker and kitematix on windows

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
What containers are you running? What happens if you do a `docker stop ....` via PowerShell?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
