### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by Protoje** [docker/kitematic#2626]
### Expected behavior
Setting up Kitematic with Virutalbox and Docker

### Actual behavior
connect ETIMEDOUT 52.73.51.236:443

### Information about the Issue
After fixing several issues with Kitematic setting up the Linux VM in Virtualbox I finally came to the point where I thought everything was working fine. But if I start Kitematic now it automatically starts the Default VM in Virtualbox and after a couple of seconds showing "No images" an Error appears saying "connect ETIMEDOUT 52.73.51.236:443".
I looked up a couple Solutions like the thread #1029, tried many fixes but nothing works for me. 

I do have a Windows 7 client, enterprise proxy behind (which shouldn't be the problem, since I put the URL into the "start.sh" as said in some threads I found yesterday to fix the "setting up a linux VM issue" i had)  and attached is a Screenshot showing the Kitematic Error.

![kitematicerror](https://cloud.githubusercontent.com/assets/11775627/25841288/ccce2460-349f-11e7-9e32-9e07d434580e.jpg)

I hope you can help me fixing it and if you need any additional information feel free to ask.

Thanks and greetings from Germany,
Josh

### Steps to reproduce the behavior

  1. Download "Docker Toolbox"
  2. Install everything needed
  3. Start Kitematic and let it do what it wants to do (creating VM etc.) 
  4. Hopefully see the issue

EDIT:
I also looked up the following Thread and tried what it says.. didn't work.
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

And of course I did the "A simple restart of Kitematic and the VM should do it:
docker-machine restart default" solution-try as well (and not only once) and it didn't work, too.

To give you as much information as (hopefully/maybe) needed, here's a Screenshot of some Outputs I saw you wanted to see in other Threads.

![docker-error](https://cloud.githubusercontent.com/assets/11775627/25842292/df764918-34a3-11e7-8865-cd3c00996017.jpg)

Now I tried following fix again:

Open network center
Change adapter settings
Right click your Virtualbox host-only adapter and select Properties
Enable "Virtualbox NDIS6 Bridget Networking Driver" (if it's disabled - if it's not, see next)
If the checkbox in step 4 was disabled, VB should work just fine now (no reboot needed). Otherwise repeat steps 3-4 for every network adapter you have (Ethernet, WiFi...) and always uncheck the NDIS6 checkbox -> apply -> check it again -> apply.

After that I shut down the VM, closed virtualbox and Kitematic, started Kitematic, it turned up to 100% and then this appeared: 

![newerror](https://cloud.githubusercontent.com/assets/11775627/25843027/4830f5d2-34a6-11e7-920f-95ccbfbf8150.jpg)

The Default Linux VM on Virtualbox is still successfully turned on and works just fine.

I kinda don't know what happened or what I did, but after that last Error appeared I restarted everything again and the very first Error seems slipped away and changed to the last one :laughing: Can't reproduce the first, but maybe if I get to fix the Error I recieved now the very first ETIMEDOUT Error will come back.

**Comment by Protoje** [comment]
I also looked up the following Thread and tried what it says.. didn't work.
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by Protoje** [comment]
Ok... I don't know if I'm making things worse while trying to fix those Issues by myself, but now I created a completely new Error again.
I clicked on "Delete VM & Retry Setup" while hoping to fix the second "ETIMEDOUT" error. Now this appears:

![worse](https://cloud.githubusercontent.com/assets/11775627/25844286/362099ac-34aa-11e7-9d7e-eae76106c49c.jpg)

**Comment by Protoje** [comment]
Cleared out the "Host-only Networks" in Virtualbox, clicked on "Delete VM & Retry Setup" and came back to the very first ETIMEDOUT error. Back to the roots I guess.
What am I doing wrong here? :rofl:

**Comment by FrenchBen** [comment]
Do you have any anti-virus running? A lot of them end up blocking local calls/connection

**Comment by Protoje** [comment]
Yeah, I have Kaspersky installed on that Notebook, but as far as I know it shouldn't be a problem, since I never had any with it. But I will look it up when I'm back tomorrow to get sure.

**Comment by Protoje** [comment]
As expected, Kaspersky doesn't block anything.

**Comment by Protoje** [comment]
Seems like I got it working now.
What I did was using this script out of your Wiki:

> set proxy=YOUR_PROXY
> SET HTTP_PROXY=%proxy%
> SET HTTPS_PROXY=%proxy%
> for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
> SET NO_PROXY=%DOCKER_HOST%
> set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
> cd Kitematic
> Kitematic.exe
> 

Yes, I tried it yesterday as well, but today I saw that of no reason I put some _""_ before and after `YOUR_PROXY` which seems like made that whole script unfunctional.

But I do have another Problem now. I can't download Ansible. I'm able to download and install other Containers, but Ansible won't work as shown on the Screenshot.

![ansible](https://cloud.githubusercontent.com/assets/11775627/25885463/cbceff80-3558-11e7-9e99-7b457ba0c3e0.jpg)

**Comment by FrenchBen** [comment]
@Protoje thank you for the follow up - Happy to hear you got it working 🎉 
The Ansible project failed, simply because https://hub.docker.com/r/ansible/ansible/tags/ doesn't have any `latest` tag - In kitematic, you can select one of their existing tags and see this working again.

**Comment by Protoje** [comment]
Unfortunately I passed through this problem myself again and can confirm that this is incorrect. :sweat_smile: 
What you can see on the screenshot was the try to download one of their existing tags with kitematic. And I guess it is what you said, that Kitematic tried (because it's a standard variable i guess) to download the "latest" image from Ansbile, but since there is no "latest" tag in their Git, Kitematic wasn't able to download it. 
I opened up a Thread to Ansible at that time. You can see what I did, here:
https://github.com/ansible/ansible/issues/24433

But I got it all working now. Had some enterprise issues coming with some typical standard docker issues which made it kinda impossible for me to get along with all this stuff at first (since I'm a total Docker newb), but I got it all fixed now. (Hopefully.. took me like a week to get it all working :sweat_smile: )

Thanks for your support @FrenchBen and keep up the work!

Greetings from Germany,
Josh
