### ISSUE TITLE
[Feature] Rename button 'Save'

### ISSUE THREAD

**Issue by anton-arsentyev** [docker/kitematic#2627]
Propose to rename button 'Save' to 'Save and restart container'
or something similar, because i dont see way to save new ENV variable without restarting container
+ its not clear that after saving variables container would be restarted

![screen shot 2017-05-09 at 12 40 22](https://cloud.githubusercontent.com/assets/22887126/25847086/e8c01268-34b4-11e7-91c0-6f39e8a02815.png)

**Comment by FrenchBen** [comment]
@anton-arsentyev If you look at the status of the container, it's clearly indicated that the container is being restarted.
Additionally the `save` button is greyed out preventing additional changes from being made.

**Comment by anton-arsentyev** [comment]
@FrenchBen now I see it, but this question one still open ;)

> its not clear that after saving variables container would be restarted

Also I can save variables and go to restart even if I didnt make any changes...
Container can took to load fully looong time...

Some hint would be nice)

**Comment by FrenchBen** [comment]
What behavior requires the hint? What happened that made you wish you knew the container would restart?
