### ISSUE TITLE
Connect to Docker Hub Login Screen Email validation fails

### ISSUE THREAD

**Issue by werty1st** [docker/kitematic#2628]
### Expected behavior
I should be able to press the Login Button.

### Actual behavior
It tells me that my email address is invalid. (if its because of the plus sign this is also an error, because its allowed to use a plus after a username to create an alias addresses on gmail.)
![image](https://cloud.githubusercontent.com/assets/4736160/25853238/68f9fb3a-34cc-11e7-9fb8-44033a7dc574.png)

### Information about the Issue
Ubuntu 16.04 (german language settings)
Kitematic_0.17.0_amd64.deb

### Steps to reproduce the behavior

  1. Open Kitematic
  2. Enter or paste email address
  3. see the error

**Comment by FrenchBen** [comment]
This has been fixed in this PR: https://github.com/docker/kitematic/pull/2574
It will be part of the next Kitematic release.
Thanks!
