### ISSUE TITLE
Problem installing the Official Discourse image from Kitematic

### ISSUE THREAD

**Issue by mikrocell** [docker/kitematic#2630]
### Expected behavior
Install the official Discourse distribution 
### Actual behavior
Throws a 404: (HTTP code 404) unexpected - {"message":"manifest for discourse/discourse:latest not found"}
### Information about the Issue
Just installed Docker on my OS/X 10.12.4 and am able to install and uninstall other containers successfully.  Docker run hello-world  works fine.

### Steps to reproduce the behavior

  1. Open Kitematic
  2. Try to install the official Discourse container

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/discourse/discourse/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
