### ISSUE TITLE
What should I do to return to the Container list?

### ISSUE THREAD

**Issue by Hzzone** [docker/kitematic#2632]
![](http://omoitwcai.bkt.clouddn.com/2017-05-10-%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-05-10%20%E4%B8%8B%E5%8D%884.39.17.png)

I found that I can't do anything even though I reinstalled kitematic....

**Comment by FrenchBen** [comment]
What did you click on to create this situation?
There's a need to add a `reset` button as well on that page, for tricky settings that stick around.
