### ISSUE TITLE
Installing "portainer" on Windows 10

### ISSUE THREAD

**Issue by ppumkin** [docker/kitematic#2633]
### Expected behavior

Container installs and runs.

### Actual behavior

Failed to install

### Information about the Issue

```
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\Docker\windowsfilter\ba67cbfae1e42e33934c654f4d15950069576ef3bdf7cb3b9cb57b8491387577\UtilityVM\Files\Windows\servicing\Packages\Microsoft-OneCore-Containers-Package~31bf3856ad364e35~amd64~~10.0.14393.0.cat: The process cannot access the file because it is being used by another process.
```

Docker is set to Windows container mode - other than that pretty much standard install.

### Steps to reproduce the behavior

Click install on portainer

**Comment by FrenchBen** [comment]
Could you run the same `docker run ` command from powershell so that we can see the full output?

**Comment by ppumkin** [comment]
It works when I switch to "Linux Containers"
I suppose this whole new Native Windows thing is a bit of a spanner in the works as how do we know if the hypervisor is a Windows or  Linux image? :(
