### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for dashdb/local:latest not found"}

### ISSUE THREAD

**Issue by mcpurcel01** [docker/kitematic#2634]
![screen shot 2017-05-10 at 11 41 04 am](https://cloud.githubusercontent.com/assets/7832335/25907541/b752986a-3575-11e7-8105-824a3d0abad5.png)

### Expected behavior
Pull dock a IBM dashDB local docker image.

### Actual behavior

(HTTP code 404) unexpected - {"message":"manifest for dashdb/local:latest not found"}
### Steps to reproduce the behavior
https://hub.docker.com/r/ibmdashdb/local/

 Deploying on Windows or Macintosh (SMP only)
Video: Perform a single-node installation on Windows using Kitematic

Deploying IBM dashDB Local on Windows or Macintosh requires a Linux VM, in which you run Docker. By downloading the Docker Toolbox, which includes a GUI and a VM, you can accomplish this easily.

Before you begin

Meet all of the prerequisites in dashDB Local prerequisites.

Clear your browser's cache.

Procedure

1) Start Kitematic and log in.

2) Click Docker CLI button, and delete the default VM.

docker-machine rm default

3) Create a new VM with sufficient memory and storage for the dashDB image. The following command creates a machine with a 40 GB virtual disk, 4 GB of RAM, and 1 virtual CPU, but you can increase the values if your system supports them:

docker-machine create -d virtualbox --virtualbox-disk-size "40000" --virtualbox-memory "4096" --virtualbox-cpu-count "1"  default

4) Restart Kitematic.

5) In the Kitematic GUI, click "My Repos" in the FILTER BY field.

6) Find the dashDB Local tile and click CREATE. You can use either the image that is tagged as "latest" or the image that is tagged as "<latest_version>-kitematic"; they are identical.

7) On the head node host, log in to the web console by using the web console URL that was provided after the successful completion messages. The URL is https://<head_node_IPaddress>:8443.

What to do next

Consider changing the default password for the bluadmin user, as described in Changing the dashDB Local bluadmin password.

**Comment by ngryman** [comment]
Same here for a lot of images, selecting a specific tags works however.

**Comment by mcpurcel01** [comment]
Thanks.
