### ISSUE TITLE
unknown blob error for microsoft iis 

### ISSUE THREAD

**Issue by vinaysuthar** [docker/kitematic#2640]
### Expected behavior
microsoft iis container must be downloaded

### Actual behavior
unknown blob error reported

### Information about the Issue
issue on mac

### Steps to reproduce the behavior

  1. Search IIS
  2. select microsoft iis container from result
  3. click create

**Comment by vinaysuthar** [comment]
same issue with nano server/iis on mac

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by vinaysuthar** [comment]
ty, that was helpful
