### ISSUE TITLE
Error when trying to setup an Umbraco container

### ISSUE THREAD

**Issue by spairous** [docker/kitematic#2642]
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\Docker\windowsfilter\33844c83bb8bd0cffea3e630a73cb12d323c87373b2feff8699a50823b02aed8\UtilityVM\Files\Windows\servicing\Packages\Microsoft-NanoServer-Win32Compat-Package~31bf3856ad364e35~amd64~en-US~10.0.14393.0.cat: The process cannot access the file because it is being used by another process.

**Comment by FrenchBen** [comment]
No information provided or steps to replicate - Closing
