### ISSUE TITLE
Map Windows10 Path on Docker Container without comandline

### ISSUE THREAD

**Issue by rodrigofujioka** [docker/kitematic#2644]

**Comment by FrenchBen** [comment]
https://docs.docker.com/docker-for-windows/#shared-drives

**Comment by rodrigofujioka** [comment]
I know, I wanted to know if you have a graphical option, without having to enter commands in console.

**Comment by FrenchBen** [comment]
For exposed volumes, there'a `Volumes` tab in kitematic that can be clicked on within the container detail.
