### ISSUE TITLE
HTTP code is 404 which indicates error: undefined - {"message":"manifest for apache/nifi:latest not found"}

### ISSUE THREAD

**Issue by domenicocampagnolo** [docker/kitematic#2651]
### Expected behavior
Create new Docker container for apache/nifi 

### Actual behavior
Error 

### Information about the Issue
HTTP code is 404 which indicates error: undefined - {"message":"manifest for apache/nifi:latest not found"}

### Steps to reproduce the behavior

  1. open Kitematic
  2. Search for Docker images from Docker Hub
  3. input apache/nifi
  4. select the image pointing to https://hub.docker.com/r/apache/nifi/ (docker pull apache/nifi)

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/apache/nifi/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
