### ISSUE TITLE
Unable to download Underworld2

### ISSUE THREAD

**Issue by cameriaux** [docker/kitematic#2652]
### Expected behavior
I wish to download underworld2:dev. 
### Actual behavior
When I try to do it, it downloads 99.95% but then crashes and reports this error below

### Information about the Issue
read tcp 10.0.2.15:39560->54.230.245.136:443: read: connection reset by peer

### Steps to reproduce the behavior

  1. ...select the container underworld2:dev 
  2. ...create

Thanks for your insight.
Regards Catherine.

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
