### ISSUE TITLE
Can't create the container

### ISSUE THREAD

**Issue by dondiegodelavega** [docker/kitematic#2653]
### Expected behavior
To let container being created
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for delavega/au-commerce:latest not found"}
### Information about the Issue
Just cant create it using Kitematic , but with command line is possible.

### Steps to reproduce the behavior

  1. just find in 'au-commerce' and create

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/delavega/au-commerce/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
