### ISSUE TITLE
kitematic create new mysql

### ISSUE THREAD

**Issue by mablerf** [docker/kitematic#2655]
### Expected behavior
download and start a mysql container 

### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Information about the Issue
OSX 10.11.6 
Docker CE 17.03.1-ce-mac12 (17661) 

Restarting Docker seems to temporarily fix the issue. 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
