### ISSUE TITLE
Jenkins Container - failes to map volumes

### ISSUE THREAD

**Issue by thomasgpeters** [docker/kitematic#2658]
### Expected behavior
Opening Jenkins Volume should not crash the container

### Actual behavior
Container crashes when enabling Volumes

### Information about the Issue
It is consistant.

### Steps to reproduce the behavior

  1. ... Download Jenkins container.
  2. ... Start Jenkins
  3. ... Click the volume in the Kitematic interface
  4. ... Enable Volumes
  5. ... Container crashes

**Comment by FrenchBen** [comment]
unable to replicate on my part - What image are you using? Where do you map the volume? what version of Docker? What operating system?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
