### ISSUE TITLE
ansible:latest - 404 Error

### ISSUE THREAD

**Issue by MonaGopal** [docker/kitematic#2661]
### Expected behavior
Expected to successfully download the ansible:latest image
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for ansible/ansible:latest not found"}
### Information about the Issue
Unable to download the ansible image

### Steps to reproduce the behavior

  1. ... Download the image from Docker Hub via Kitematic

**Comment by FrenchBen** [comment]
Please see: https://github.com/docker/kitematic/issues/2626#issuecomment-302021541
