### ISSUE TITLE
Uknown blob

### ISSUE THREAD

**Issue by eduardopin** [docker/kitematic#2664]
### Expected behavior
Dowload ASP.NET Image

### Actual behavior
Error dowloading ASP.NET

### Information about the Issue
Just pop up an error "Error dowloading ASP.NET"

### Steps to reproduce the behavior

  1. ...
Open Kitematic
  2. ...
Search for ASP.NET
3... 
Click and wait for the download.

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
