### ISSUE TITLE
Unable to download images with Kitematic

### ISSUE THREAD

**Issue by lfallo1** [docker/kitematic#2665]
UPDATE: Issue is resolved if logging in with username instead of email.  Still a bug, I suppose, but easy enough to get around it.

### What I am doing
Logged in & attempting to download hello-world-nginx via kitematic.  I have a verified email address confirmed via my account page on the docker hub site.

Note that it downloads without issue when I logout.

### What occurred
Receive 401 error message

### Details
Exact error message: (HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce
 1. Try to download any image as a logged in user

**Comment by FrenchBen** [comment]
@lfallo1 Thanks for the update - there is a fix for it coming in the next release of kitematic, thanks to this PR:
https://github.com/docker/kitematic/pull/2574
