### ISSUE TITLE
Can't login with kitematic

### ISSUE THREAD

**Issue by johnbocook** [docker/kitematic#2666]
### Expected behavior
Login, pull docker image
### Actual behavior
Get error when pulling docker image - invalid user/password
### Information about the Issue
I'm using the correct login, I can login to hub.docker.com just fine. 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
can you provide a screenshot of the error?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
