### ISSUE TITLE
unauthorized: authentication required For pulling Tensor Flow Docker instance

### ISSUE THREAD

**Issue by podilaaditya** [docker/kitematic#2668]
### Steps to reproduce the behavior

  1. Start The kinematic and then select the TensorFlow instance  
  2. Click the download, we get the error "unauthorized: authentication required"

**Comment by FrenchBen** [comment]
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified

**Comment by SamyAgarkar** [comment]
Tensorflow works only on python 3.5.x . You must have installed latest 3.6.x version.....Uninstall it and install 3.5.x.
