### ISSUE TITLE
Improve VirtualBox detection and invocation

### ISSUE THREAD

**Issue by daaain** [docker/kitematic#267]
Right now VirtualBox is [hardcoded to `/usr/bin/VBoxManage`](https://github.com/kitematic/kitematic/blob/master/src/VirtualBox.js#L7) which is a big limitation.

I have VB installed with [Homebrew Cask](https://github.com/caskroom/homebrew-cask), which is at `/usr/local/bin/vboxmanage`, but other package managers might put it elsewhere too.

Maybe a better solution would be simply asking the system for the path (eg. `which vboxmanage`) and using the [existing version check](https://github.com/kitematic/kitematic/blob/master/src/VirtualBox.js#L12) to infer if VB is already installed / working correctly?

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
