### ISSUE TITLE
No repo

### ISSUE THREAD

**Issue by ibondy** [docker/kitematic#2670]
### Expected behavior 
Access to my repo

### Actual behavior
HTTP code is 404 which indicates error: undefined - {"message":"manifest for ibondy/myrepo:latest not found"}
### Steps to reproduce the behavior

  1. trying to access my repo
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/ibondy/myrepo/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
