### ISSUE TITLE
The font used for container log should be configurable

### ISSUE THREAD

**Issue by Riduidel** [docker/kitematic#2672]
### Expected behavior

I would like to have a legible font used on my monitor.

Or a way to easily zoom in (Ctrl-Mousescroll to the rescue !)

### Actual behavior
![6waipqb](https://cloud.githubusercontent.com/assets/171018/26346618/18d313f4-3fa7-11e7-9499-0cf214e7682f.png)

### Information about the Issue

I've a Dell XPS 15 with Full HD display.

### Steps to reproduce the behavior

  1. use a monitor with a high DPI value
  2. show container log

Notice I'm really not crazy about that, it's just that I've got to look closer, and I'm quite sure I'm not the only one ageing developper.
Beside, Kitematic is such a good thing for reluctant Docker users like me that I can't help trying to improve it.

**Comment by FrenchBen** [comment]
Feel free to pick this PR back up :)
https://github.com/docker/kitematic/pull/1479

**Comment by agatlin** [comment]
The container font size is ridiculously small. This should be a top priority to fix unless your target audience is only fighter pilots and others with vision significantly better than  20/20.

**Comment by a4bits** [comment]
agree on that! :-)
