### ISSUE TITLE
Unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by avdvyver** [docker/kitematic#2673]
### Expected behavior
Getting the following error message when trying to download container

(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: unauthorized: incorrect username or password"}

### Actual behavior
Expecting to download the container

### Steps to reproduce the behavior

  1. Reset password
  2. Login 
  3. Download official Jenkins Container. 
  4. Getting error message

**Comment by avdvyver** [comment]
The issue already resolved in next version. 
Workaround: login with username, not email

**Comment by caokhang91** [comment]
Login with username worked

**Comment by ryanhell** [comment]
Worked for me also. Thank you

**Comment by elinalin** [comment]
it works !
