### ISSUE TITLE
Kitematic cannot find powershell

### ISSUE THREAD

**Issue by jenzmarkallen** [docker/kitematic#2674]
When clicking on the DOCKER CLI button I get the following message

![ps](https://cloud.githubusercontent.com/assets/25798204/26358079/66b70eca-3f9f-11e7-8227-126ae96762a2.GIF)

### Information about the Issue
Using Docker Tools on a WIN 7 machine

**Comment by FrenchBen** [comment]
Couple of changes were made in the recent code that should help solve this. Once Docker 17.06 is out, can you try it again?

**Comment by 40rn05lyv** [comment]
Hi, I have the same issue. Windows 7 x64, the latest Docker Toolbox. Any workarounds?

**Comment by jokersss** [comment]
have u guys solved?, i have the same question ,too

**Comment by wyllmachado** [comment]
close the topic without solution that ridiculous
