### ISSUE TITLE
error in download of 

### ISSUE THREAD

**Issue by silviocrivellini** [docker/kitematic#2675]
### Steps to reproduce the behavior

  1. downloading the docker oracledatabase_12cr1:latest
  2. I have 173G available on disk ... but I meet following error error  "write /var/lib/docker/tmp/GetImageBlob149266684: no space left on device"

**Comment by FrenchBen** [comment]
Please see https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
