### ISSUE TITLE
OSX seems to stop default vm when battery is low, kitematic gets out of sync.

### ISSUE THREAD

**Issue by bigblind** [docker/kitematic#2677]
When my battery gets low on OSX (even if it doesn't completely go to 0%), it seems that the default VM gets killed, and kitematic gets out of sync

### Expected behavior

I try to stop, restart, modify settings on a container ==> I get an error message saying the vm is no longer running

### Actual behavior

The UI just doesn't seem to respond.

### Information about the Issue

OS: macOS 10.12.5
docker-machine version 0.8.2, build e18a919
Docker version 1.12.6, build 78d1802
kitematic version: 0.12.0 (will update to 0.17.0 and see if the same issue occurs)

### Steps to reproduce the behavior

  1. Add a container
  2. Let your laptop battery go down to below 5% and wait a bit longer
  3. Try to alter a container

**Comment by bigblind** [comment]
Looks like this is what's going on with virtualbox: https://www.virtualbox.org/ticket/9925

**Comment by FrenchBen** [comment]
It's pretty difficult for us to detect when vbox is deconnected until we actually try to do something -If you have something in mind to detect it, I'm all ears (and would enjoy a PR :)
