### ISSUE TITLE
Error in creating new image

### ISSUE THREAD

**Issue by theklr** [docker/kitematic#2684]
### Expected behavior
Docker creates a new container from the image chosen.
### Actual behavior
Receive error response: 
```
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: unauthorized: incorrect username or password"}
```
### Information about the Issue
Docker Kitematic 0.17.0
macOS Sierra  v10.12.5
 Container does seem to download in background. 

### Steps to reproduce the behavior

  1. Select image From hub clicking create 
  2. populates in container field
  3.  Receives code

**Comment by FrenchBen** [comment]
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified
