### ISSUE TITLE
image operating system "windows" cannot be used on this platform

### ISSUE THREAD

**Issue by wangliguokaka** [docker/kitematic#2687]
when I use command: docker pull microsoft/aspnet
The exception occur:image operating system "windows" cannot be used on this platform

when I use the command : docker pull microsoft/dotnet is ok.
I want to know how to install aspnet image, thank you.

**Comment by wangliguokaka** [comment]
PS:the docker run in the windows Server 2012

**Comment by wangliguokaka** [comment]
I use Kitematic (Alpha) to create virtual machine, I find the message  is that "is staring the linux virtual machine ...." I think the problem  is the OS type, now how to change the type of os,? I need the widows OS.
thank you.

**Comment by wangliguokaka** [comment]
I use the os image is boot2docker, it is a linux  image. I think the season of problem is the selection of image type. I want to know that how to download the windows image.

**Comment by FrenchBen** [comment]
Make sure that you can do both from Powershell first:
`docker pull microsoft/aspnet` and `docker pull microsoft/dotnet` if not, provide the output of `docker info` here.

Kitematic isn't magic, if the CLI can't do it, Kitematic won't fix that

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
