### ISSUE TITLE
Logging in breaks functionality

### ISSUE THREAD

**Issue by du5tball** [docker/kitematic#2693]
### Expected behavior
After logging in with my docker hub account, it should show me images and download them

### Actual behavior
After logging in, I get "(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/mariadb/manifests/latest: unauthorized: incorrect username or password"}". The container doesn't matter.

### Information about the Issue
When I'm not logged into the docker hub via kitematic, I can download all containers. When I log in, I can't. This goes for every container.

### Steps to reproduce the behavior

  1. Log into Kitematic

**Comment by FrenchBen** [comment]
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified

**Comment by du5tball** [comment]
Why did this get closed? The Account is active and verified, I can log in perfectly fine into cloud.docker.comcloud.

**Comment by FrenchBen** [comment]
the 401/403 is usually because you're logged in and haven't confirmed your account - I'm unable to replicate this locally.
What do you get when you run: `docker run -it mariadb` ?

**Comment by iamgaurav** [comment]
@du5tball try using your username to login rather than your email.
