### ISSUE TITLE
image operating system "windows" cannot be used on this platform

### ISSUE THREAD

**Issue by davenso** [docker/kitematic#2696]
I am trying to run download and run Microsoft IIS, but got the error message: 
"image operating system "windows" cannot be used on this platform"

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by git-chinmay** [comment]
I am trying to do auto build an image in docker hub and getting this error.Is auto build only supported for non windows images ?

**Comment by sraddhananda** [comment]
if you enable experimental in docker settings, it will let you run windows images.

**Comment by westandy-dcp** [comment]
"Windows Container image only" seems to defeat the purpose of using Docker at all.
