### ISSUE TITLE
Integrate x11

### ISSUE THREAD

**Issue by robtec** [docker/kitematic#270]
Just a simple setting to allow display settings be added during a container run statement, for x11 forwarding :smile:

**Comment by jeffdm** [comment]
Thanks for the issue! Is this possible on Mac OS X? IIRC the latest versions don't ship with X11.

**Comment by robtec** [comment]
Hey, see the following workaround, a bit messy :cry: 
https://github.com/docker/docker/issues/8710
Requires `socat` to listen for forwarded traffic and then route it through the XQuartz app.

Yeah IDK if x11 is still out of the box, my mac is early 2011 but `brew` allows a simple install of XQuartz.
I have a few dev containers like a nodejs one that forwards Sublime Text over x11, a buddy of mine setup a Intellij dev container, pretty sweet :+1: 

I guess integration may be overkill, could just simply add a DISPLAY variable to the container though the settings pane.

Up to you guys :smile:

**Comment by koddsson** [comment]
I'm gonna work on this a bit and see if I can get something decent up.

**Comment by robtec** [comment]
Cool, would be interested to see what you come up with :smile: :+1:

**Comment by koddsson** [comment]
@robtec I made a PR in #326. Check it out and let me know what you think! :wink:
