### ISSUE TITLE
starting container with non-empty request body was deprecated since v1.10 and removed in v1.12

### ISSUE THREAD

**Issue by basvanbeek** [docker/kitematic#2706]
### Expected behavior
start container

### Actual behavior
very briefly a 400 error is shown with the following message:
starting container with non-empty request body was deprecated since v1.10 and removed in v1.12
immediately followed by showing an empty black log page

### Information about the Issue
this problem started after an upgrade of Docker for Mac 17.06.0-rc1 

### Steps to reproduce the behavior

  1. fresh install of Docker for Mac and Kitematic and it will happen

**Comment by szyhf** [comment]
I got the same problem！！Kitematic works well before I have my lunch
I forgot if if it's occur after I update my docker.

masOS

**Comment by DmitriyBaklikov** [comment]
Same to me. Able to start via CLI, but unable to via Kitematic interface.

**Comment by szyhf** [comment]
@DmitriyBaklikov @basvanbeek  
Hey guys~
I reinstall the stable version of docker-for-mac, and the problem sloved.
Seems like something goes wrong with the rc version of docker.

**Comment by FrenchBen** [comment]
Thanks for the report everyone, I'll check out the RC and will see what's going on.

**Comment by FrenchBen** [comment]
Opened a bug on the moby/moby project:
https://github.com/moby/moby/issues/33501

**Comment by godbout** [comment]
Same here. Updated to  17.06.0-rc1-ce-mac13 (18169) and right away Kitematic cannot start any container. Cli works. Let me know if you need info.

**Comment by FrenchBen** [comment]
Looks like it's a bug on the proxy that is pushed with Docker for Desktop - we'll await a fix on their part. 
Thanks everyone for the QA and bug report!
