### ISSUE TITLE
"unauthorized: authentication required" while pulling magento/magento2devbox-web 

### ISSUE THREAD

**Issue by sherifzanaty** [docker/kitematic#2708]
### Expected behavior

image should be downloaded

### Actual behavior

During the pulling process  I am getting "unauthorized: authentication required"

### Information about the Issue

ERROR: unauthorized: authentication required
ERROR: No container found for web_1
Install Magento
ERROR: No container found for web_1
Press any key to continue . . .

### Steps to reproduce the behavior

  1. ... docker pull magento/magento2devbox-web

**Comment by FrenchBen** [comment]
Are you logged in to docker hub? Did you verify your account?
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified
