### ISSUE TITLE
HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### ISSUE THREAD

**Issue by abhincho** [docker/kitematic#2715]
### Expected behavior
pulling "ghost" container from docker-hub
### Actual behavior
HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
### Steps to reproduce the behavior

  1. open kitematic
  2. choose container
  3. click on create

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.

**Comment by JiSikKim** [comment]
I have same problem
![image](https://user-images.githubusercontent.com/35905694/37802492-057eba90-2e6e-11e8-8e85-446363f21102.png)

**Comment by rampaps-star** [comment]
I am facing the same problem. I have a good internet.
(HTTP code 500) server error - Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
