### ISSUE TITLE
Request: Terminal within application

### ISSUE THREAD

**Issue by J7mbo** [docker/kitematic#2716]
Would it be possible to have the terminal window running within the Kitematic application, like the logs, instead of firing up another window? My immediate thought when using the application for the first time would be that I could click into the window and start typing a few commands. 

Not a technical concern, would just keep the whole UI + experience cleaner.

**Comment by FrenchBen** [comment]
@J7mbo I like the idea and it was brought up before. Some of the challenges were to create a proper and pleasant terminal emulation while retaining some of the user's shell preferences.
