### ISSUE TITLE
401 Errors

### ISSUE THREAD

**Issue by gressd** [docker/kitematic#2722]
### Expected behavior
No 401
### Actual behavior
401
### Information about the Issue
just reset password etc
![screen shot 2017-06-08 at 11 48 47 am](https://user-images.githubusercontent.com/21316842/26937846-92df6e7c-4c40-11e7-9bd7-8c8ecb645140.png)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Did you login? If so did you make sure that your docker credentials are valid?
What happens if you do `docker pull drupal` in your terminal?

**Comment by gressd** [comment]
Yes logout & in, still 401

Works via cli / term

Dave


On Jun 9, 2017, at 4:05 PM, French Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you login? If so did you make sure that your docker credentials are valid?
What happens if you do docker pull drupal in your terminal?

**Comment by FrenchBen** [comment]
Can you try the same action while not logged in? I'm unable to replicate on my end:
![drupal](https://user-images.githubusercontent.com/3965324/27102577-90b5e470-503a-11e7-92f4-29e27cc79e59.png)

Are you behind a firewall or proxy?

**Comment by gressd** [comment]
Strange,

Reboot mac now it's working

Close & thanks

Dave


On Jun 13, 2017, at 2:17 PM, French Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you try the same action while not logged in? I'm unable to replicate on my end:
[drupal]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_3965324_27102577-2D90b5e470-2D503a-2D11e7-2D92f4-2D29e27cc79e59.png&d=DwMFaQ&c=uilaK90D4TOVoH58JNXRgQ&r=NGmsEF2wOvExP7Gwupnh6pKFWL_uaqgO7-CyG6wweh8&m=1ymC4einHyjSRQv8qmgWcZeiz0XYhgj7-E3mLLT3if0&s=lI345dSeKZJsg41TJb2labVMgHYg_mQPlsjFbHlbidY&e=>

Are you behind a firewall or proxy?
