### ISSUE TITLE
Unable to download docker image django in MacOS Sierra

### ISSUE THREAD

**Issue by kantanand** [docker/kitematic#2727]
### Steps to reproduce the behavior

  1. open kitematic 
  2. login to your account 
  3. select django and try to install

**Comment by FrenchBen** [comment]
Can you provide the following info:
`docker version`
`docker info`
`docker run django`

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
