### ISSUE TITLE
Bad response from docker engine while installing Jenkins

### ISSUE THREAD

**Issue by kunal-saxena** [docker/kitematic#2731]
### Expected behavior
In MacBook Air, Jenkins container should be installed 

### Actual behavior
error while creating container of  jenkins in kitematic 
Following error received: "(HTTP code 502) unexpected - Bad response from Docker engine" 

### Information about the Issue
searched and selected jenkins container , when clicked on create it gave error. 

### Steps to reproduce the behavior

  1. Login in kitemeatic
  2. search Jenkins container and click "create" 
  3. After 5 min it gave error ....

Second time when i tried creating jenkins container it worked seemlessly ..

**Comment by FrenchBen** [comment]
can you do the same thing via the CLI and provide the full output?
Also can you provide the output of: `docker version` and `docker info`

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
