### ISSUE TITLE
Feature request:  Pass exec commands to container on start

### ISSUE THREAD

**Issue by hellonearthis** [docker/kitematic#2736]
I would like to add exec commands to a docker container on startup.
So I can do an apt update as well as install stuff like the nano editor.

Or can these be added as container parameters like Shell /bin/bash
but with exec the/commands

**Comment by FrenchBen** [comment]
Why not create your own image base on the above needs?

**Comment by hellonearthis** [comment]
That might be a bit much for my coding skills.  Will look into it and try and work out where I can hook into the system to achieve that.  Any tips on where to start, anyone?

**Comment by FrenchBen** [comment]
You can look at the get started guide:
https://docs.docker.com/get-started/part2/
