### ISSUE TITLE
Unable to change volume

### ISSUE THREAD

**Issue by djsowa** [docker/kitematic#2738]
### Expected behavior
Allow to change volumes for docker image
### Actual behavior
When trying to change the volume for mongo image I'm receiving an error:
_Invalid directory - Please make sure directory exists and you can read/write to it_
### Information about the Issue
Kitematic(windows 8.1) 

### Steps to reproduce the behavior

  1. ...Run mongo image
  2. ...In image settings try to change the volume for /data/configdb

**Comment by FrenchBen** [comment]
Using toolbox, only your home user folder is shared with the VM. If a different location is selected, you will not be able to use that folder with a folder.

**Comment by VokaMut** [comment]
Mount another volume at VirtualBox like this:
Name: c/Users/another_folder/
Path: D:\path\to\another\folder
Access: Full

![image](https://user-images.githubusercontent.com/4266448/35723177-6af23fb2-080a-11e8-9c58-69ae225dc70e.png)

**Comment by Mokolos** [comment]
thanks a lot (y)

**Comment by Nishnha** [comment]
In case anyone stumbles upon this answer, there is a [workaround](https://forums.docker.com/t/mounting-folders-outside-the-users-folder-on-windows/65662/4) for Docker Toolbox on Windows. Normally, Docker Toolbox only provides volumes access to the user's home folder (e.g., C:/Users) and subdirectories.

The workaround is to add a shared folder to the Docker Virtualbox VM with the folder path as the folder you want to share and the mount point as where you want to access it in your Docker Compose file (see the image as reference). 

![A folder in my external hard drive's project folder with the mount point set to /aifi](https://user-images.githubusercontent.com/12107187/76384642-e2efbc00-6335-11ea-9f3e-b5c812cd512c.png)

You can then access this shared folder by referencing the mount point. For example, my Compose file has:
```
volumes:
      - "/aifi/data/downloads:/app/data/downloads"
```
and I can access the files correctly. 

Unfortunately, Kitematic does not correctly show the volume and it cannot be set in the program. It gives the same error as OP, _Invalid directory - Please make sure directory exists and you can read/write to it_.
