### ISSUE TITLE
aliyun mirror error HTTP code 500 server error

### ISSUE THREAD

**Issue by pooy** [docker/kitematic#2740]
(HTTP code 500) server error - {"message":"parse https://docker-machine create --engine-registry-mirror=https://b3zydnfm.mirror.aliyuncs.com -d virtualbox default\ndocker-machine create --engine-registry-mirror=https://b3zydnfm.mirror.aliyuncs.com -d virtualbox default\ndocker-machine create --engine-registry-mirror=https://b3zydnfm.mirror.aliyuncs.com -d virtualbox default\n: invalid character \" \" in host name"}

![docker_mirror_500_error.png](http://pooy.qiniudn.com/docker_mirror_500_error.png)

**Comment by FrenchBen** [comment]
Proper docs are here:
https://www.docker-cn.com/registry-mirror
