### ISSUE TITLE
docker image error

### ISSUE THREAD

**Issue by nandhiniraman** [docker/kitematic#2741]
while connecting to DOCKER hub I get the below error
(HTTP code 404) unexpected - {"message":"manifest for j2connector/j2test:latest not found"}

can someone help me on this issue.

thanks

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/j2connector/j2test/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
