### ISSUE TITLE
unable to save items in local folder specified in volume

### ISSUE THREAD

**Issue by maxxu05** [docker/kitematic#2746]
### Expected behavior
I am assuming that the items that I have saved within the container should also save in the local folder on my computer.

### Actual behavior
I am saving items in a container (specifically the TCGABiolinksGUI container) but it does not show up in the local folder that I selected for configuring volumes. I have been consistently losing my data in the container when I deleted the container or when I press save on the "General" tab which resets the container some reason

### Information about the Issue
I am using kitematic within the docker toolbox. For reference: I have attached photos.

![image](https://user-images.githubusercontent.com/29440154/27237524-64fd913e-5297-11e7-8e6d-0801dad0a254.png)
![image](https://user-images.githubusercontent.com/29440154/27237546-7757c4f8-5297-11e7-9c6e-3c64f86d0c2b.png)
![image](https://user-images.githubusercontent.com/29440154/27237558-88d82470-5297-11e7-8bb5-4b4e2c76f313.png)

### Steps to reproduce the behavior

  1. Try saving anything within the container
  2. Look at the local folder and no new files have appeared.

**Comment by woshiliuweijing123** [comment]
Hi, I wonder if you have already solved this problem. I have the same issue and it drived me crazy :(
