### ISSUE TITLE
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/2.46.3: unauthorized: incorrect username or password"}

### ISSUE THREAD

**Issue by quki** [docker/kitematic#2748]
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/2.46.3: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jmwong** [comment]
Hi @quki , can you try logging into Kitematic with your username instead of email?

**Comment by umassthrower** [comment]
that worked for me
