### ISSUE TITLE
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/tensorflow/tensorflow/manifests/latest: unauthorized: incorrect username or password"}

### ISSUE THREAD

**Issue by akkefa** [docker/kitematic#2752]
I am already logged in. But its showing this error continuously,

**Comment by jmwong** [comment]
@akkefa can you verify if you can successfully log into cloud.docker.com with the same credentials?

**Comment by RuBiCK** [comment]
Same issue. I'm getting 401 with every image I try to pull when I'm logged in and I can successfully log into cloud.docker.com

Doing pull without being logged in works fine. 

Is there any reason for doing pulls from a public registry authenticated ?

**Comment by FrenchBen** [comment]
@RuBiCK Can you provide us with the output of:
`docker version`
`docker info`
and 
`cat ~/.docker/config.json | jq ".credsStore"`

Please make sure that the output of the last command doesn't divulge any sensitive information.
Entries like your email and/or `auth` may allow someone to login on your behalf if shared here without caution.

**Comment by FrenchBen** [comment]
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified

**Comment by jmwong** [comment]
Hi @akkefa , @RuBiCK  , can you try logging into Kitematic with your username instead of email address?

**Comment by RuBiCK** [comment]
@jmwong  it works fine with username instead of email.


```
bash-3.2$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

```


```
bash-3.2$ docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: MHJI:E43P:LC57:K4GF:GU4F:63MH:GOZV:VKLI:ZOUR:V6JN:CKAD:I3OE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 68
 Goroutines: 76
 System Time: 2017-06-19T20:53:38.261038727Z
 EventsListeners: 3
No Proxy: *.local, 169.254/16, 192.168.* , 180.46.*.*
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
bash-3.2$ 

```

I couldn't find config.json on macOS
```
bash-3.2$ find $HOME -name config.json -type f 2>/dev/null
bash-3.2$
```

**Comment by FrenchBen** [comment]
@RuBiCK we've identified the issue and have created a ticket internally - For the time being logging in with your username (Docker ID) instead of email address will fix this.

**Comment by kumarakn** [comment]
This resolution worked for me.
