### ISSUE TITLE
q

### ISSUE THREAD

**Issue by xuancuongspk** [docker/kitematic#2754]
### Steps to reproduce the behavior

  1. (HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/datarhei/restreamer/manifests/latest: unauthorized: incorrect username or password"}

  2. (HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/datarhei/restreamer/manifests/latest: unauthorized: incorrect username or password"}

**Comment by philipyoo** [comment]
Login with the same credentials you would use at [cloud.docker.com](https://cloud.docker.com), and instead of using email to login to kitematic, use your username instead.

**Comment by FrenchBen** [comment]
As @philipyoo mentioned, pulling images via email address isn't working as expected. 

Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
