### ISSUE TITLE
Trying to download bdu spark2

### ISSUE THREAD

**Issue by jgperrin** [docker/kitematic#2758]
### Expected behavior
download & run?

### Actual behavior
message saying: error unauthorized: authentication required

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Unable to reproduce this - Please provide exact steps to reproduce and docker versions

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Comment by jgperrin** [comment]
Was not able to reproduce issue lately. Merci
