### ISSUE TITLE
[Bug] Broken fonts on Linux

### ISSUE THREAD

**Issue by Deus-Rex** [docker/kitematic#2760]
### Expected behavior
Press the Exec icon to bring up the terminal.
and
Try to change the directory that a volume leads to.

### Actual behavior
Dialog box with broken font that can't be read. [Screenshot](http://i.imgur.com/NCs5sr4.png)
and
File selection window also has the broken font. [Screenshot](http://i.imgur.com/x4gzGAy.png)

### Information about the Issue
I'm using Manjaro Linux 64bit with Gnome v3.24
This is the only application it happens in.
I have other software that uses Electron, and none of those have any issues.

Seems to only happen to dialog boxes and file selection dialogs that use the Gnome toolkit.

**Comment by FrenchBen** [comment]
I'm not familiar with Manjaro linux and currently only Ubuntu has been vetted. 
With all of the different flavors of linux out there, it's difficult for me to support them all. 

Feel free to clone the repo and do some debugging in order for us to help support your distro. 
Thanks!

**Comment by qywx** [comment]
It should be enough to install some font or several fonts. Could you say what fonts are used or where to find what fonts are used?

**Comment by DavidFeller** [comment]
I'm facing the same problem on a "fresh" and "clean" ubuntu 17.10 box. I haven't try to install any additional fonts. 

![kitematic_ubuntu_artful](https://user-images.githubusercontent.com/2094727/32226065-d1b22620-be47-11e7-8b09-ca18f5930edf.png)

**Comment by agentcobra** [comment]
same problem for me under
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

**Comment by agentcobra** [comment]
same issue like #2829, #3064

**Comment by seanlinmt** [comment]
If I run "grunt", kitematic launches without the broken fonts. But if I run "dist/Kitematic-linux-x64/Kitematic", the broken fonts show up. Sounds more like a problem with the electron packager. 

I'm using Rolling Arch Linux.

**Comment by agentcobra** [comment]
@seanlinmt installed with aur repository ?

**Comment by seanlinmt** [comment]
@agentcobra Yes. From the AUR repository. I changed electron-version to 1.7.9 in package.json and then built, repackaged and then installed the package directly using pacman.
