### ISSUE TITLE
Login email format cannot be recognized

### ISSUE THREAD

**Issue by eliu** [docker/kitematic#2761]
### Expected behavior
Kitematic should be recognized valid email address of NetEase
e.g: example@163.com

### Actual behavior
Kitematic could not recognize email format from NetEase and report error message as follows:
`Must be 4-30 lower case letters or numbers , or a valid email`

### Information about the Issue
Version: 0.17.0
Platform: macOS

### Steps to reproduce the behavior

  1. Click Docker for Mac daemon icon
  2. Select `Kitematic`
  3. Enter login email like  `example@163.com` and press Tab;

**Comment by FrenchBen** [comment]
Already fixed in a previous PR and part of the new release coming out soon. Thanks for the issue
