### ISSUE TITLE
Unable to create image in Docker Container

### ISSUE THREAD

**Issue by Ram2911** [docker/kitematic#2764]
### Expected behavior
Create image either through Shell Script or through Kinematic UI.
### Actual behavior
Unable to create an image in-spite of enabling virtual box.
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please provide the code for the image you're trying to create/build so that we can try to replicate

**Comment by Ram2911** [comment]
I could resolve it by running the shell script from Windows PowerShell tool that I downloaded. Initially I was trying from command prompt and it didnt work as it was throwing "Docker daemon engine is not running in your environment" error.
