### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by dai-shun** [docker/kitematic#2771]
1. when I want to get a image,there is an error
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/redis/manifests/latest: Get https://auth.docker.io/token?account=daishun&scope=repository%3Alibrary%2Fredis%3Apull&service=registry.docker.io: net/http: TLS handshake timeout"}

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
