### ISSUE TITLE
Set the 'ServerName' directive globally to suppress this message on a Wordpress container

### ISSUE THREAD

**Issue by ventouris** [docker/kitematic#2772]
### Expected behavior
Installation page of a new wordpress container
### Actual behavior
Blank page
### Information about the Issue
I installed a mySQL container and set the password with a variable MYSQL_ROOT_PASSWORD. Then I created a new wordpress container. Added the following variables:

WORDPRESS_DB_HOST: the ip with the port of the mysql
WORDPRESS_DB_PASSWORD: the password I set on mysql
ServerName: localhost

I also changed the privileges on the volume of wordpress to read and write everyone.

However on the wordpress logs I have this:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Fri Jun 23 12:49:33.297932 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.30 configured -- resuming normal operations
[Fri Jun 23 12:49:33.298026 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

And the preview is empty

Kitematic 0.17.0
MacOs: 10.12.5 

### Steps to reproduce the behavior

  1. Download mysql
  2. Set a new root password
  3. Download wordpress
  4. Add WORDPRESS_DB_HOST
  5. Add WORDPRESS_DB_PASSWORD
  6. Add ServerName

**Comment by FrenchBen** [comment]
Localhost is really going to be the container's localhost and not what you want - I would advise to leave the `ServerName` var as it is by default and only configure the WORDPRESS_DB* vars

**Comment by ventouris** [comment]
There isn't any `ServerName` var on a clean Wordpress container. And even if I remove it, I have exactly the same behaviour.

**Comment by FrenchBen** [comment]
The `ServerName` config isn't part of the MySQL or Wordpress docs:
https://store.docker.com/images/mysql
https://store.docker.com/images/wordpress

Provide me with actual steps to replicate this and it'll be easier for us to debug what's going on

**Comment by ventouris** [comment]
As I said on the first post:

  1. Create a new Wordpress container (the first one on the list)
  2. Add the WORDPRESS_DB_HOST from your mySQL
  3. Add the WORDPRESS_DB_PASSWORD
 
Then Wordpress container doesn't work. It is just a blank page when you try to open the url and the only error on the Wordpress console is:

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Tue Jun 27 12:24:02.924359 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.30 configured -- resuming normal operations
[Tue Jun 27 12:24:02.924520 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

As you see, I didn't add anything about `ServerName`...

**Comment by FrenchBen** [comment]
I created and setup mysql:
![mysql](https://user-images.githubusercontent.com/3965324/27590767-f711ac7a-5b4f-11e7-9847-a29fd4be2483.png)

I created and setup wordpress:
![wordpress](https://user-images.githubusercontent.com/3965324/27590782-0396c4e4-5b50-11e7-86b5-7ae733c19f1c.png)

Wordpress cannot talk to mysql unless you "link" them together:
```
$ docker network create mywordpress
1749cf24464caf24f7a87f18638bcd36b57e0a53375cea8b0387404b2844662e
$ docker network connect mywordpress mysql
$ docker network connect mywordpress wordpress
```

Click the web-preview button:
![wp-setup](https://user-images.githubusercontent.com/3965324/27590832-340fddb8-5b50-11e7-8f3d-3a6eeeee4c21.png)


I cannot reliably reproduce this - Please provide exact steps and screenshots as I did.

**Comment by ventouris** [comment]
Sorry about that. I should have done it before. This is a screencast with the process. As you can see, I use the mysql I already have and create a new Wordpress container. I add the mysql IP on DB_HOST and the password, but I still don't have a preview.

[https://www.dropbox.com/s/9epnte972fa5de0/My%20Movie%204.mp4?dl=0](url)

**Comment by FrenchBen** [comment]
The video is of pretty poor quality which isn't helping - One thing you didn't mention is that you were using VirtualBox. 
Although it's a small detail, everything I did was done using Docker for Mac. (I'd highly recommend you upgrade to it)

What is the output of the Wordpress logs as you see them in the window (complete)?
Can you curl the wordpress installer from within the Virtualbox?

**Comment by ventouris** [comment]
I am new on Docker and I just downloaded kitematic... Now I removed VM and installed Docker for Mac as you suggested. I had an error on Wordpress 
```
MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known
```
Then I created a new Network with docker command
```
$ docker network create mywordpress
```
Changed both mysql and wordpress to that network and it worked. However, I thought from Google that if both are on bridge and not on a new network, it should work. Do I need to create a new network for every Wordpress container?

**Comment by FrenchBen** [comment]
You can keep all of your containers on the same network if you'd like - For security purposes, containers on the regular bridge network cannot use service discovery, although you could use the regular container IP; but that IP may change. 

See: http://mfranc.com/blog/docker-containers-communication/

Previously you used the IP of the VM to communicate to the container. 
Your mysql request would be something like:
WP -> VM -> MySQL -> VM -> WP
With proper container network:
WP -> MySQL -> WP

FYI: you don't even need the mysql port to be open (exposed), since the containers use a Docker-specific network to talk to each other. It's simply convenient for you to be able to login to mysql from the outside.
