### ISSUE TITLE
user-defined network reference weirdness

### ISSUE THREAD

**Issue by ThaBrad** [docker/kitematic#2773]
### Expected behavior
restart container (via Kitematic or of course bash)

### Actual behavior
shortly flashes (UI), too fast to read error (screenshot said connection problem with user-defined network)

### Information about the Issue
should show error properly and not a 0,1s flash
resolve issue automatically (at least while reloading UI or on access [run, exec, ….] of container)

### Steps to reproduce the behavior

  1. user-defined network
  2. udn deleted
  3. created other udn
  4. restart of old [unchanged] container (with still old network reference)

**Comment by FrenchBen** [comment]
you mean create a udn, attach a container to it, then delete it and restart the container that had the old network reference?

**Comment by ThaBrad** [comment]
@FrenchBen
Sry, sure: 
Create udn, attach (1st container), run, stop, delete old udn, create new udn, attach (2nd container), run (1st)... or simpler, same as you described, same result

I think the CLI (at least) should automatically feedback on that and ask for a fix. 
And Kitematic should cover that case as well or at least show the error properly

**Comment by FrenchBen** [comment]
There's definitely a lot of user induced errors that could be made and unfortunately Kitematic doesn't have a lot of capacity to handle all of the test cases (gracefully).

The 'flashed' error is all that we get from the daemon, which then gets pushed to a full kitematic error, although not very descriptive. Feel free to provide a PR in order to get this fixed.

**Comment by ThaBrad** [comment]
Yeah Kitematic but the CLI as well doesn't give a really useful error message or path of correction, not even speaking of self correction (with a yes/no), which would be simple. PR, I'd like, but time's not on my side :-/.

**Comment by FrenchBen** [comment]
Feel free to open one up if the time opens up :)
