### ISSUE TITLE
failing to download mariadb although I am logged in

### ISSUE THREAD

**Issue by qordobafranzi** [docker/kitematic#2781]
### Actual behavior

(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/mariadb/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. downloading mariadb image
  2.

**Comment by FrenchBen** [comment]
Can you try this again but login with your Docker ID (username). Closing for now, but feel free to re-open if this doesn't fix it.
