### ISSUE TITLE
UX: Make input fields more clearer that they can be edited

### ISSUE THREAD

**Issue by ESWAT** [docker/kitematic#2782]
### Expected behavior
Should able to clearly identify editable input fields in the UI by looking at them.

### Actual behavior
Input fields, like port inputs, do not clearly convey they are input fields and instead look like static text.

I’m a Docker newb and I didn’t realize until after using Kitematic for a bit that the following fields were editable:

![screen shot 2017-06-26 at 14 09 06](https://user-images.githubusercontent.com/65468/27553641-b8b4bf7a-5a79-11e7-85da-8b74f4d867a0.png)

I should be able to identify text that is editable, without having to reference the context of the form or hover my pointer over text…

**Comment by FrenchBen** [comment]
editable text is of a different color than the static text - How do you suggest we highlight this edit property?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
