### ISSUE TITLE
Unable to download and create images through Kitematic

### ISSUE THREAD

**Issue by neildcruz19** [docker/kitematic#2789]
I am able to login to kitematic but, get a 401  response when creating a new container.

### Actual behavior

(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/rabbitmq/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. Login to Kitematic - Mac OSX
  2. Search for RabbitMQ
  3. Create the RabbitMQ container

**Comment by FrenchBen** [comment]
There's a good chance that you logged in using your email address. Try to login using your username instead and that should fix the issue.
