### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for dustinmoris/docker-demo-nancy:latest not found"}

### ISSUE THREAD

**Issue by RobertoCamara** [docker/kitematic#2795]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
If the image you're creating a container from doesn't have a `:latest` tag (which is the default), you need to manually select the tag to use from the UI;


Click the three "dots" to open the details pane for the image

<img width="489" alt="screen shot 2017-07-02 at 17 59 56" src="https://user-images.githubusercontent.com/1804568/27774924-820dc99a-5f50-11e7-832e-a6aec6657937.png">

Click on the "selected tag" 

<img width="424" alt="screen shot 2017-07-02 at 18 00 07" src="https://user-images.githubusercontent.com/1804568/27774927-975cf5d2-5f50-11e7-9393-f3e276ce9b3c.png">

Select the image tag you want to use:

<img width="283" alt="screen shot 2017-07-02 at 18 00 28" src="https://user-images.githubusercontent.com/1804568/27774932-bb40d1da-5f50-11e7-83c0-0e1255153353.png">

Click the close button ("X"):

<img width="276" alt="screen shot 2017-07-02 at 18 00 43" src="https://user-images.githubusercontent.com/1804568/27774933-ca9d7e9e-5f50-11e7-8b5d-66cc352a7bde.png">

Then click "create" to create a container using the image (and tag) you selected
