### ISSUE TITLE
I am not able to connect to the registry

### ISSUE THREAD

**Issue by scottturley** [docker/kitematic#2796]
### Expected behavior
I should be able to connect

### Actual behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/selenium/standalone-firefox-debug/manifests/2.53.0: unauthorized: incorrect username or password"}

### Information about the Issue
I am logged in but unable to connect.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
There's a good chance you logged in using your email address - Try and login with your Docker ID to see if this resolves the issue
