### ISSUE TITLE
Unable to see images and containers on Kitematic

### ISSUE THREAD

**Issue by WeiKitzglue** [docker/kitematic#2797]
### Expected behavior
Ability to view Containers and Images on Kitematic
### Actual behavior
Cannot detect them even though I have created new containers
### Information about the Issue
I am unable to see my containers/images displaying on Kitematic even though I just created them.

**Comment by FrenchBen** [comment]
Did you perhaps start with a Virtualbox setup and now use Docker for Mac?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
