### ISSUE TITLE
dl-docker can not find image

### ISSUE THREAD

**Issue by threelaws** [docker/kitematic#2806]
HTTP code is 404 which indicates error: undefined - {"message":"manifest for floydhub/dl-docker:latest not found"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/floydhub/dl-docker/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
