### ISSUE TITLE
open /mnt/sda1/var/lib/docker/tmp/GetImageBlob152807945: read-only file system

### ISSUE THREAD

**Issue by jessecotto** [docker/kitematic#2810]
### Expected behavior
Install Shinobi CCTV Docker Kinematic as explained in Install Doc.
### Actual behavior

open /mnt/sda1/var/lib/docker/tmp/GetImageBlob152807945: read-only file system

**Comment by FrenchBen** [comment]
Can you provide the system that this is running under and the associated steps to reproduce the error? (what exact image)

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
