### ISSUE TITLE
maybe unselected running container's icon should be green

### ISSUE THREAD

**Issue by binderclip** [docker/kitematic#2811]
### Expected behavior

When a running container is selected, it's icon should be green, just like when it's not selected.

![two](https://user-images.githubusercontent.com/8187479/27848625-1e513128-6179-11e7-9c58-08a41921f0bc.png)

### Actual behavior

![one](https://user-images.githubusercontent.com/8187479/27848629-241cabaa-6179-11e7-9203-400e95a05b15.png)

### Information about the Issue

Without the green color, there maybe a confusion.

### Steps to reproduce the behavior

  1. Start a container
  2. Select another container

**Comment by FrenchBen** [comment]
When you select the container, the right hand side panel will indicate that it is running and thus having an icon on the left side distract from it. 
<img width="215" alt="running" src="https://user-images.githubusercontent.com/3965324/27854842-938c90ce-6168-11e7-894f-fa5fb891cf37.png">

Other non-selected containers do need to show this change of status, to visual confirm that they are indeed running.

**Comment by binderclip** [comment]
So why not just hide the icon?

I think keeping the `~` `-` shape but discard the green and gray color will make people confused.

**Comment by FrenchBen** [comment]
The icon is part of the design and keeps it consistent with the running containers below it. 
Visually having the green there makes it look off. 
You can try it by using the chrome console and you will see that the design will not match well.
