### ISSUE TITLE
How to deal with it

### ISSUE THREAD

**Issue by zhipengyang** [docker/kitematic#2813]
![problem](https://user-images.githubusercontent.com/13879453/27900969-d8bcaf08-6262-11e7-97d2-ea978350dbe5.png)
When I installed the kitematic, it can't connect to the www......  Can anyone tell me how to deal with it? Many many thanks

**Comment by FrenchBen** [comment]
Can you provide details of your setup?
What operating system and version?
What version of kitematic?
What version of docker?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
