### ISSUE TITLE
v0.17.1 release zip files missing locales and resources files

### ISSUE THREAD

**Issue by sandscap-sc** [docker/kitematic#2814]
### Expected behavior
The downloadable release zip files of 0.71.1 should contain the `resources` and `locales` files similar to what is in release 0.71.0.
### Actual behavior
Folders  `resources` and `locales` in the 1.17.1 release zip file are empty
### Information about the Issue
Kitematic.exe does not start when those folders are empty. I had to copy the folders from the 0.17.0 release in order to get 1.17.1 running on Windows 10.

### Steps to reproduce the behavior

  1. [Download release v1.17.1](https://github.com/docker/kitematic/releases/download/v0.17.1/Kitematic-0.17.1-Windows.zip)
  2. Unzip and try to run kitematic.exe and it will fail to start on Windows.

**Comment by sandscap-sc** [comment]
Yes, the folders are present, but empty. Are they supposed to be empty? Mine 0.17.1 would not run until I copied the contents of those two folders from 0.17.0 into 0.17.1.

Just to double check - I just downloaded https://github.com/docker/kitematic/releases/download/v0.17.1/Kitematic-0.17.1-Windows.zip on two different windows machines, with two totally different network and internet access points and both contain 0 bytes in the locales and resources folder.

**Comment by FrenchBen** [comment]
Went ahead and updated the release Zip file to what I had:
https://github.com/docker/kitematic/releases/tag/v0.17.1

Let me know if the issue persists. Thanks for reporting this, feel free to re-open the issue if that doesn't fix the problem for you.
