### ISSUE TITLE
Could not login with an email address 

### ISSUE THREAD

**Issue by fengyc** [docker/kitematic#2818]
### Expected behavior

Login with an email address that contains a dot, e.g.  example.example@example.com

### Actual behavior

Failed and got an error message "Must be 4-30 lower case letters or number, or a valid email"

### Information about the Issue

I could use this email address to login hub.docker.com, but kitematic could not recognize the email address that contain a dot.

### Steps to reproduce the behavior

  1.  Install kitematic (windows 10)
  2.  Open kitematic, and try to login with an email like example.example@example.com
  3.  Get the error message

**Comment by FrenchBen** [comment]
The latest release of kitematic will allow login via an email address - the issue is that it will then prevent you from pulling images, due to an internal change needed. 
A ticket has been created to make sure that users can use their email as well as their docker ID to do this.
