### ISSUE TITLE
kitematic showing manifest error:

### ISSUE THREAD

**Issue by Nithya25Mari** [docker/kitematic#2819]
### Steps to reproduce the behavior

  1. login to the dockerhub
  2. creating a sample node application
![capture](https://user-images.githubusercontent.com/26431700/28003787-d2c2c71a-655d-11e7-98df-92e0364f8f09.PNG)

**Comment by FrenchBen** [comment]
Go to:
https://hub.docker.com/r/nitikishu/
Realize that the image you're trying to use doesn't exist.
