### ISSUE TITLE
When trying to pull from dockerhub i get login error.

### ISSUE THREAD

**Issue by Kezryk** [docker/kitematic#2820]
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/smartive/nutch-elasticsearch-mongodb/manifests/latest: unauthorized: incorrect username or password"}
 
I can log-in thru the website but not this way

**Comment by FrenchBen** [comment]
There's a good chance you logged in using your email address - There's currently a lack of support for email when pulling an image. Please try to login via your Docker ID (hub username) and that should fix it.
