### ISSUE TITLE
image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by UdoW** [docker/kitematic#2828]
### Expected behavior
I installed Docker for Windows and switched to containers.

### Actual behavior
When I try to install Debian as container then I get this error message:

image operating system "linux" cannot be used on this platform

In former versions of Docker Machine for Windows I had not problems with this.

I installed this version:

Version 17.06.0-ce-win18 (12627)
Channel: stable
d9b6651

I have Hyper-V activated.

**Comment by thaJeztah** [comment]
Docker for windows allows switching between Linux containers and native Windows containers; if you want to use Linux containers (such as Debian), make sure you enabled that mode

See this section in the documentation https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by breddi** [comment]
To switch to windows containers

In powershell (open as an admin): 

**& $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon .**

**Comment by LaLamborghini331** [comment]
Still having this issue,

**Comment by eschrader** [comment]
Solution: switch docker to linux in systray https://stackoverflow.com/questions/43346580/docker-image-operating-system-windows-cannot-be-used-on-this-platform Then run a docker ps in PowerShell as admin to wake things up, wait 10 seconds and then you can build your linux container on Windows 10 just fine!
