### ISSUE TITLE
Unable to download the containers from the hub.

### ISSUE THREAD

**Issue by jselvaprabu** [docker/kitematic#2831]
### Expected behavior
Should be able to download the container from the hub.
### Actual behavior
Throws following error when we click on CREATE:

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
### Steps to reproduce the behavior

  1. Open Kitematic
  2. Search for Ubuntu or Hello World or anyother container.
 3.Click on Create.

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
