### ISSUE TITLE
prof.

### ISSUE THREAD

**Issue by 376473984** [docker/kitematic#2833]
### Expected behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
