### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by rnogal** [docker/kitematic#2834]
### Expected behavior
Install weblogic 12 for IDEA edployments

### Actual behavior
Error 404
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
I'm unable to replicate this issue - Please provide more information. 
Can you replicate the issue with a simple `docker run ...` ?
Closing until more information has been provided

**Comment by rnogal** [comment]
I´m using kinematic. I search for weblogic docker image. The image formweblogic and Intellij IDEA is broken

(HTTP code 404) unexpected - {"message":"manifest for opavlova/weblogic:latest not found"}
