### ISSUE TITLE
unauthorized Error while Downloading Odoo 9.0

### ISSUE THREAD

**Issue by nasseryo** [docker/kitematic#2839]
### Expected behavior
Download Odoo 9.0
### Actual behavior
Showing unauthorized Error 
### Information about the Issue
I'm getting this error: 

(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/odoo/manifests/9.0: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
