### ISSUE TITLE
pull error

### ISSUE THREAD

**Issue by fatCoderCat** [docker/kitematic#2840]
### Expected behavior
pull the image
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:49953->10.0.2.3:53: i/o timeout"}
### Steps to reproduce the behavior
docker pull hello-world

**Comment by ZarubinArtem** [comment]
The same problem with Kitematic app, but `docker pull <any_container>` in Terminal works well.

**Comment by FrenchBen** [comment]
If docker pull doesn't work, kitematic will not work as well.
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
