### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by vaibhavscorpiog** [docker/kitematic#2845]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ZarubinArtem** [comment]
@vaibhavscorpiog I bet you need to provide some details following the Ticket template.

**Comment by vaibhavscorpiog** [comment]
Helo,

I am  not able to download Cassandra image.

Regards
Vaibhav

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
