### ISSUE TITLE
image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by motorcyclediary** [docker/kitematic#2847]
### Expected behavior
Download image
### Actual behavior
Getting error: image operating system "linux" cannot be used on this platform
### Steps to reproduce the behavior

  1. Open kinematic
  2. Select image to download (datascience-notebook)

**Comment by FrenchBen** [comment]
If you're on a Windows machine with Windows container selected, then you will not be able to run linux containers

**Comment by motorcyclediary** [comment]
is there any any way of running a linux container on windows using a VMware
or Hyper-V?

**Comment by FrenchBen** [comment]
@motorcyclediary Please see the link to the docs above, or provide more information on your setup.

**Comment by motorcyclediary** [comment]
Hi,

I'm running Windows 2016 Server and would like to implement a setup that
allows me to run Linux docker containers on windows. If necessary using a
VM client. Please advise if that's possible.

Br - Imran

**Comment by FrenchBen** [comment]
Hi @motorcyclediary thanks for the details - There's currently a Windows 2k16 server Edge installer, that can be found here:
https://store.docker.com/editions/community/docker-ce-desktop-windows

Marking this issue as resolved, but feel free to re-open it if this doesn't fit your needs.

**Comment by batjko** [comment]
I'm not sure that link applies to my case:
`ERROR: cannot download image with operating system "linux" when requesting "windows"`

I don't have a "Switch to so-and-so containers" menu item:
![image](https://user-images.githubusercontent.com/7287076/32996930-43c48dc8-cd81-11e7-878e-5b5e61ebaedf.png)

![image](https://user-images.githubusercontent.com/7287076/32996945-6df33d6a-cd81-11e7-9359-1167c0fa2e1e.png)

**Comment by eugene-s** [comment]
@batjko Same problem

**Comment by rtaylor30** [comment]
I had the same issue with:

Version 17.11.0-ce-win40 (14328)
Channel: edge
6b31b18

I noticed that when I unchecked the box, it started working
