### ISSUE TITLE
HTTP error code 500

### ISSUE THREAD

**Issue by artkernelzyc** [docker/kitematic#2850]
```(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}```

**Comment by PegWu** [comment]
I have a similar issue:

when i run: 
docker pull klokantech/tileserver-gl

this error message was returned to me:

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:58395->10.0.2.3:53: i/o timeout"}

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
Additionally if you are behind a proxy or firewall, see our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
