### ISSUE TITLE
starting in VM fails. No way to revert back to native

### ISSUE THREAD

**Issue by EdZilla** [docker/kitematic#2852]
### Expected behavior
When I selected restart kitematic in a VM, but that fails, I expect to be able to revert back to native. 

### Actual behavior
Starting Docker VM in a linux VM...eventually fails with a long crash dump and this: 
Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout,You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.

After that, there is no way to revert back to running kitematic in native (osx) 

### Information about the Issue
OSX 10.10.5 (Yosemite)
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0

### Steps to reproduce the behavior

  1. select restart in a VM
  2. Retry, or remove vm and retry. failure
  3. kill kitematic after failure
  4. restart docker
  5. open kitematic again but it's still trying to run in a vm.

**Comment by FrenchBen** [comment]
If you update to the latest Kitematic, there is a `reset` button that was added to sort you out of this situation.
https://github.com/docker/kitematic/releases/tag/v0.17.1
