### ISSUE TITLE
In mac, should be install docker first to have better terminal command support?

### ISSUE THREAD

**Issue by THPubs** [docker/kitematic#2854]
Hi, I installed kitematic only in my machine and now I can't access the docker commands through my normal terminal. So, is it ok if I install docker seperately first and then install kitematic? Will it use the system installed docker or install it's own version?

**Comment by FrenchBen** [comment]
Hello @THPubs We recommend you install Docker for Mac:
https://www.docker.com/community-edition#/mac

Kitematic is a UI that doesn't install Docker but leverages the installed version.
