### ISSUE TITLE
Unable to install dash using docker/kitematic

### ISSUE THREAD

**Issue by mpruna** [docker/kitematic#2860]
### Expected behavior
Able to install dash using docket/kitematic
[https://plot.ly/products/dash](url)

### Actual behavior
While attempting to create a docker container I get:
(HTTP code 404) unexpected - {"message":"manifest for dashproject/dash:latest not found"}
Also please see attached:
![error](https://user-images.githubusercontent.com/7471140/28481051-3caff246-6e5b-11e7-847c-201ba2b7b9be.PNG)

### Information about the Issue
OS Windows 7 Professional
PS C:\Program Files\Docker Toolbox> docker info
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.74-boot2docker
Operating System: Boot2Docker 17.06.0-ce (TCL 7.2); HEAD : 0672754 - Thu Jun 29
00:06:31 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: default
ID: EBNR:NUBE:JJWK:JY4N:VNTK:GJLJ:2ZJC:SQ4Y:DN3V:TS4H:SVKQ:OVZV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 207
 Goroutines: 217
 System Time: 2017-07-21T20:29:08.296997856Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Steps to reproduce the behavior

  1. ... Attempt to install dash

Please advise

Cheers,

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/dashproject/dash/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
