### ISSUE TITLE
Bug: Tagged image pulled from shell results in 404 when creating new container from Kitematic

### ISSUE THREAD

**Issue by whatch** [docker/kitematic#2870]
### Expected behavior

OSX 10.12.5
Kitematic 0.17.1
Docker version 17.06.0-ce, build 02c1d87

after pulling ruby:2.3, from the shell, I see the image listed when I issue the command `docker images` from the shell, as well as My Images in Kitematic. When I click "Create" within Kitematic My Images view, I expect a container to be launched.

### Actual behavior

I immediately get an error: 

> (HTTP code 404) no such image - no such image: local-library/ruby:2.3: No such image: local-library/ruby:2.3

### Information about the Issue

I have other images I pulled using the shell, and I'm able to launch them from Kitematic, but this is the only one that specified a tag when I pulled the image, so possibly relevant. I am also able to run the local image from the shell with `docker run -it ruby:2.3` and get expected behavior.

### Steps to reproduce the behavior

  1. from bash shell, execute: `docker pull ruby:2.3`
  2. In Kitematic, click + New to add a new container. In the following view, select "My Images" tab, then for Ruby 2.3 image, select "Create"

**Comment by FrenchBen** [comment]
Thanks for the report - I'll see about getting a patch in for the next release.

**Comment by leabet** [comment]
I got the same issue on windows 10 as well. Kitematic cannot find locally built images any more on 0.17.1 version. This issue doesn't exist on 0.17.0 version.

**Comment by maksbotan** [comment]
I've done `git bisect` and found that this error starts with commit 4eff85d0256b7ccc983dff4e74386a6fd898ac02 by @FrenchBen 
Diff is really small, so can you please look into it and fix?

By the way, there seems to be a typo `image` -> `imageq` in `src/components/ImageCard.react.js` file.

**Comment by FrenchBen** [comment]
@maksbotan thanks for digging up the change. 
`imageq` should be correct, as we are passing the prop as `image`, see here:
https://github.com/docker/kitematic/blob/4eff85d0256b7ccc983dff4e74386a6fd898ac02/src/components/NewContainerSearch.react.js#L251

The issue is in the imageSplit logic, I wanted an easy way to "tag" local builds, but turns out it introduced the bug above. 
I haven't had much time to look at it, but feel free to suggest a fix.

**Comment by mhelmetag** [comment]
Picked up this issue. Hope that's okay! PR got linked to this ticket.

**Comment by dgenezini** [comment]
Is this fix released already? I'm having this problem on the latest version.

**Comment by mhelmetag** [comment]
@dgenezini , it should be... what version are you on? This issue was fixed in `v0.17.2`.

**Comment by dgenezini** [comment]
I'm was on v0.17.1
I was just downloading from https://download.docker.com/kitematic/Kitematic-Windows.zip, it's not updated there, sorry and thanks. Works great now. 👍

**Comment by leosco** [comment]
This is still broken on Mac...
