### ISSUE TITLE
Container was removed when change port mapping in Kitematic

### ISSUE THREAD

**Issue by XtheWiz** [docker/kitematic#2875]
### Expected behavior
Container should remain with new port mapping.

### Actual behavior
Old container gone and replace with clean new container....

### Steps to reproduce the behavior

  1. Create new container, for example, ubuntu. Go into it shell and create only 1 new empty file.
  2. Back to Kitematic. Go to Settings -> Hostname/Ports, and change port mapping. Click "save"
  3. Kitematic running this container, Go into it by clicking exec. Previously created file is gone.

**Comment by FrenchBen** [comment]
It's currently not possible to dynamically update a container's port. 
When you update the ports in Kitematic, we delete the container and re-create it with the proper configuration.
Containers are stateless, which means that you should not be writing to them. You can keep some of the data if you mount a volume where you expect the data to be kept.
