### ISSUE TITLE
image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by santoshmb** [docker/kitematic#2879]
### Expected behavior
Start Docker
### Actual behavior
image operating system "linux" cannot be used on this platform

### Information about the Issue

Windows 10 LTSB on VMWARE ESXi

C:\Users\>**docker info**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.0.amd64fre.rs1_release.160715-1616)
Operating System: Windows 10 Enterprise 2016 LTSB Evaluation
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 5.999GiB
Name: US-NJ1v20221W05
ID: JCXT:UITZ:PPY2:VDAP:MGZU:JY7X:NL5X:6KKO:7U6F:AWUP:4ERL:HETB
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 31
 System Time: 2017-07-26T10:55:47.9092339-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

C:\Users\santoshadm>**docker version**
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: true

C:\Users\santoshadm>

### Steps to reproduce the behavior

  1. ...Fresh Windows 10 VM
  2. ...New Docker CE Edition
Start Docker - fails

**Comment by FrenchBen** [comment]
If you're running Docker for Windows, you can switch to using linux or windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
