### ISSUE TITLE
Kitematic Issue

### ISSUE THREAD

**Issue by ashu-22** [docker/kitematic#2881]
### Steps to reproduce the behavior

  1. ... When I login and create my account every thing working fine I am done with that thing.
  2. ... Then When I used to run the shell of the program. It is working absolutely fine, After while I imagined some problem due to in my login and password. I tried it so many times, But It did not working out properly. May be I can imagine something wrong. But, When I used to start login again then I had some issue regarding the same. Hopefully, Issue will be resolved very well.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by ashu-22** [comment]
Issue is fixed thanks a lot.
