### ISSUE TITLE
error in loading docker image

### ISSUE THREAD

**Issue by nikhiltiwari1** [docker/kitematic#2885]
### Actual behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/gentux/kubectl/manifests/latest: unauthorized: incorrect username or password"}
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
