### ISSUE TITLE
hyperledger/fabric-peer/manifests/latest 500 ERROR

### ISSUE THREAD

**Issue by spyhole** [docker/kitematic#2889]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/hyperledger/fabric-peer/manifests/latest: net/http: TLS handshake timeout"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/hyperledger/fabric-peer/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
