### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:33405->[::1]:53: read: connection refused"}

### ISSUE THREAD

**Issue by j1mbosharp** [docker/kitematic#2891]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by j1mbosharp** [comment]
Trying t images.o load LAMP from tutum using Kitematic. Same error for other

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by alankent** [comment]
I just got a new laptop, setting it all up. I got this problem when trying Kitematic out too. I don't have a proxy. The problem turned out to be Docker Engine failing to download images (not Kitematic). Running docker commands to download images from the command line was also failing (it just hung). Being on Windows I did a reboot ... and that cleared the problem - everything worked fine after that. So I suspect this error message is an indication of a docker engine problem downloading images, not a Kitematic problem.

The message I got was:

```
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:35914->[::1]:53: read: connection refused"}
```

Not a very friendly Kitematic error message!

**Comment by FrenchBen** [comment]
Kitematic doesn't try to assume anything and thus sends the same error that the engine would (API response)
@alankent what would've been a better message?

**Comment by zephraph** [comment]
Just to throw this out there, I ran across the same error. From the message it seems like there's a network issue. 

```
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:50169->[::1]:53: read: connection refused"}
```

I suspect that's not actually what's happening. I'm not behind a proxy, firewall isn't blocking. I'll dig around a bit.

**Comment by FrenchBen** [comment]
@zephraph Are you using toolbox or Docker for Mac?
What happens when you do `docker run hello-world` what happens when you do the same within the VM (if on Toolbox)

**Comment by zephraph** [comment]
I apologize for not putting in the specifics. I encountered that on my windows machine. When I tried to do a docker run it just hung there for a while. I had to manually kill it. 

I’ll report back tonight on more detailed specifics like docker version, system specs, etc. Seems to be a windows specific issue.

**Comment by fredhohenstein** [comment]
==
I apologize for not putting in the specifics. I encountered that on my windows machine. When I tried to do a docker run it just hung there for a while. I had to manually kill it.
==

I have the same issue. Have to restart de docker components (from the windows tray icon) and then sometimes it works. I'll restart the docker components (from the windows tray icon) until it works...

**Comment by aliamani** [comment]
resolve with chage dns nameserver in:
vim /etc/resolv.conf 

nameserver 8.8.8.8

**Comment by salmagomaa** [comment]
sudo vi /etc/resolv.conf


nameserver 8.8.8.8
nameserver 8.8.4.4
