### ISSUE TITLE
Error when connection to docker registry

### ISSUE THREAD

**Issue by abennani31** [docker/kitematic#2892]
### Expected behavior
Download image
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
