### ISSUE TITLE
Docker run not working with  microsoft/dotnet:1.1-sdk

### ISSUE THREAD

**Issue by ganeshan** [docker/kitematic#2893]
### Expected behavior
Expected the image to be downloaded and run.
### Actual behavior
Sending build context to Docker daemon  9.216kB
Step 1/10 : FROM microsoft/dotnet:1.1-sdk AS build-env
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:58531->[::1]:53: read: connection refused
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
