### ISSUE TITLE
(HTTP code 500) server error while downloading image

### ISSUE THREAD

**Issue by dreammaster38** [docker/kitematic#2894]
### Expected behavior
Downloading requested docker image.

### Actual behavior
Error message : (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 10.0.75.1:3129: getsockopt: connection refused"}

Calling the URL 'https://registry-1.docker.io/v2/' in browser gives this result:

`{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}`

### Information about the Issue
I'm behind a company proxy. But it is configured for docker.

### Steps to reproduce the behavior

  1. Open Kitematic from docker pop up menu
  2. Search for image you want to download
  3. Click create --> error occurs

### Versions used

I installed Docker for windows not the Toolbox

## Docker

- Docker for Windows CE V17.06.0-ce-win18 (12627)
- stable channel

## Kitematic

- Version 0.17.1

## Proxy configuration in docker

![2017-08-01 08_25_06-settings](https://user-images.githubusercontent.com/834612/28812314-7532b086-7694-11e7-82fb-2c5053be23b3.png)

## Proxy configuration in kitematic

I use this batch file to start kitematic:
`set proxy=http://localhost:3129
SET HTTP_PROXY=%proxy%
SET HTTPS_PROXY=%proxy%
for /f %%i in ('docker-machine.exe ip default') do set DOCKER_HOST=%%i
SET NO_PROXY=%DOCKER_HOST%
set DOCKER_HOST=tcp://%DOCKER_HOST%:2376
Kitematic.exe`

**Comment by krital** [comment]
I just installed latest version on a new Mac and got. exactly the same

**Comment by FrenchBen** [comment]
@dreammaster38 and @krital please provide details of your configuration:
* Docker Version
* Docker product installed (Toolbox or Docker for Mac)
* Versions of above software
* Version of Kitematic
* How was the VPN/proxy configured

**Comment by dreammaster38** [comment]
Hi @FrenchBen,

i updated my post above with additional info. Hope it helps.

Thanx,

Thomas

**Comment by FrenchBen** [comment]
@dreammaster38 I would not use `localhost` as the name for the proxy, as it will change depending on the application making the call. 
This is why you're getting the request on `10.0.75.1:3129` as localhost for that particular vm is `10.0.1.75`

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
