### ISSUE TITLE
(HTTP code 404) no such image - no such image: local-library/fedora:25: No such image: local-library/fedora:25

### ISSUE THREAD

**Issue by cqlilon** [docker/kitematic#2901]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
There's a small bug in Kitematic that's already been reported when dealing with library images that get flagged incorrectly - Closing this in favor of the previous issue

**Comment by psyrendust** [comment]
@FrenchBen can you add a link to the previous issue that you mentioned?

**Comment by FrenchBen** [comment]
@psyrendust https://github.com/docker/kitematic/issues/2870
