### ISSUE TITLE
image operating system "windows" cannot be used on this platform

### ISSUE THREAD

**Issue by wjkang55** [docker/kitematic#2903]
### Expected behavior
I want to Winodws APP download

### Actual behavior
image operating system "windows" cannot be used on this platform
### Information about the Issue
I am test docker
OS: windows 10
I installed docker and Kitematic
In kitematic download Active directory,
But image operating system "windows" cannot be used on this platform
Do not Windows APP support in the docker?

thanks

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
