### ISSUE TITLE
it show Starting docker vm forever

### ISSUE THREAD

**Issue by linyintao2010** [docker/kitematic#2904]
1,  when i open the Kitematic software, it show starting docker vm interface forever, can not move next, and nothing remind

**Comment by FrenchBen** [comment]
In the latest version there is a 'reset' button to allow you to set things back to the way they were - If you're using Virtualbox there's a chance that the setup has failed and thus could take a long time to validate.
Either way I'm unable to replicate or help any further without proper steps to replicate the issue and also details about your actual setup
