### ISSUE TITLE
Get https://registry-1.docker.io/v2/library/mysql/manifests/latest: unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by albertoivo** [docker/kitematic#2907]
I'm successfully connected in Docker Hub and kitematic

I'm trying to pull mysql container

### Expected behavior
install normally

### Actual behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/mysql/manifests/latest: unauthorized: incorrect username or password"}

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
