### ISSUE TITLE
I have enough space in the device but still i get error saying that no space on the device. please advice

### ISSUE THREAD

**Issue by ddgowda76** [docker/kitematic#2911]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ddgowda76** [comment]
I have enough space on the device but still get error saying no space. please advice

**Comment by FrenchBen** [comment]
By default we create a VM that is only 20gb in size. You can change this by creating a larger VM from the get-go:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
