### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:55982->[::1]:53: read: connection refused"}

### ISSUE THREAD

**Issue by balienig** [docker/kitematic#2916]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.

No information provided or steps to replicate - Closing 😞
