### ISSUE TITLE
Expose port and mapping IP/interface

### ISSUE THREAD

**Issue by lifehome** [docker/kitematic#292]
Since Kitematic done a great job, but it seems it could only be accessed internally. Unless you got your box assigned as 192.168.99.100, otherwise you'll get stucked when it comes to whether exposing port or mapping your docker to an interface.

So I hereby suggest kitematic should be able to add a feature, <b>allowing users to expose port to certain interface, like mapping port to IPs.</b>

For instance, docker "A" using port 1234, normally it would be assigned to 192.168.99.100:49158(random port). But when it comes to the "advance tab", we could map port 1234 to interface en3, with IP 10.x.x.x:1234.

This could be useful while your mac has more than one network interface.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by ianneub** [comment]
Would love this feature as well. The use case for us is that often times a developer wants to show the boss or manager the work in progress to quickly get feedback. Would be great to be able to send the boss a URL that he can click on that points to the developer's local docker dev environment.

**Comment by davehun** [comment]
you can do this pretty easily using netcat:
`ncat  -kl -p $MachineExternalPort --sh-exec "ncat $MacIP $MacPort"`


where `$MachineExternalPort` is the port you want to expose
`$MacIP` is the ipaddress from kitematic gui ports setting
`$MacPort` is the port from kitematic gui ports setting

e.g.:
`ncat  -4 -kl -p 8080 --sh-exec "ncat 192.168.99.100 32772"`
exposed the nginx example

**Comment by bunam** [comment]
how i correct this :
- stop Kitematic
- open VirtualBox
-> stop the vm
-> remove the vm (plus files)
- go to preferences / Network / hosts
-> remove all 
- stop VirtualBox
- go to preferences / Network / hosts
-> add a new network
- start Kitematic

now it's working (and i can ping 192.168.99.100)

(i have complicated network setup...)

**Comment by timbrandin** [comment]
This would be amazing to have. How can we get started working on this?

**Comment by jeffdm** [comment]
As a temporary work around, adding a bridge network adapter to the VM could work.

**Comment by BenPoulson** [comment]
@jeffdm Have you personally tried this work around?

Each time I've tried it, the docker VM would fail to start up when initialised through Kitematic. The VM fully boots, but the app doesn't seem to be able to connect to it.

**Comment by basiclaser** [comment]
Are there any solutions to this yet? I can't get mongoDB or elasticsearch connecting with external applications . running kitematic 0.10.0 on OSX 10.10.5

**Comment by davehun** [comment]
there are 2 workarounds above @bunam's and myself

**Comment by sliontc** [comment]
How to run a 3 nodes cluster on the docker?

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.

**Comment by olivier-squid** [comment]
Hi folks, so what's the outcome? What do we have to do in Kitematic/Docker to allow external access to the VM?

**Comment by pkris001** [comment]
I was able to allow external access by changing the promiscous mode to "Allow All" from "Deny" inside the Network settings for the linux VM running inside virtual box. I have attached a screenshot.

![kitematic-external-access](https://cloud.githubusercontent.com/assets/3609040/25557061/bfbabef6-2cce-11e7-8a7c-c0f23c155fcc.jpg)

**Comment by FrenchBen** [comment]
@pkris001 thanks for sharing - Please keep in mind that it means that you're now exposing all of your services to the 'world'
