### ISSUE TITLE
Downloading of image from kitematic 

### ISSUE THREAD

**Issue by sushil-sundaram** [docker/kitematic#2922]
### Expected behavior
The image should download.
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
### Information about the Issue
Docker pull used to give the same issue but worked yesterday suddenly.

### Steps to reproduce the behavior

  1. ...open kitematic
  2. ...download ros image
![screen shot 2017-08-04 at 3 23 05 pm](https://user-images.githubusercontent.com/12962901/28964051-da469a14-7928-11e7-9c65-c3feb5ffab5b.png)

**Comment by FrenchBen** [comment]
If Docker pull all of a sudden works, then kitematic will work as well - Kitematic cannot solve docker pull issues (there is no magic) as it uses docker in the background. 

If you can provide proper steps for me to reproduce this error, then I'll be happy to debug it - Closing for now, until more information has been provided.
