### ISSUE TITLE
Problem downloading ansible:ansible from repo

### ISSUE THREAD

**Issue by flexifoil21** [docker/kitematic#2924]
### Expected behavior
Using Kitematic or command-line I try to download ansible:ansible image

### Actual behavior
Download fails with the following message:
HTTP code is 404 which indicates error: undefined - {"message":"manifest for ansible/ansible:latest not found"}

### Information about the Issue
I have duplicated the issue on two different MacBooks using the latest Docker for Mac version

### Steps to reproduce the behavior

  1. Use Kitematic or command line to download ansible:ansible image

**Comment by FrenchBen** [comment]
Please see: https://github.com/docker/kitematic/issues/2626#issuecomment-302021541
