### ISSUE TITLE
Kinematic

### ISSUE THREAD

**Issue by MrLee36** [docker/kitematic#2928]
### Steps to reproduce the behavior

  1. ...
  2. ...
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/microsoft/mssql-server-linux/manifests/latest: unauthorized: incorrect username or password"}

**Comment by MrLee36** [comment]
Ho do i correct the usename and password issues for 
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/microsoft/mssql-server-linux/manifests/latest: unauthorized: incorrect username or password"}

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
