### ISSUE TITLE
HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/cassandra/manifests/latest: unauthorized: incorrect username or password"}

### ISSUE THREAD

**Issue by techmio** [docker/kitematic#2929]
### Expected behavior
create docker successfully
### Actual behavior
error 
HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/cassandra/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

1.search cassandra docker.
2.click create.
3. while connecting to github, remove this job.
4.search cassandra again.
5.select the same and click create
6.error appear.

**Comment by blogw** [comment]
I got this error too when I download hello-world-nginx

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
