### ISSUE TITLE
With Customized MACHINE_STORAGE_PATH Kitematic failed.

### ISSUE THREAD

**Issue by nsidhaye** [docker/kitematic#2933]
### Expected behavior
With `MACHINE_STORAGE_PATH=C:\VM\.docker\machine` Kitematic should run flow-lessly on WINDOWS 10 Home Edition with Docker Toolbox 17.06.0a-ce

### Actual behavior
1. Kitematic could not detect if docker-machine is running or not. It will simply remove default vm and re-create it.
1. Kitematic Screen shows error `Certificate directory does not exist`
1. If I removed system environment variable `MACHINE_STORAGE_PATH` and recreate new image with `docker-machine create --driver "virtualbox" default` then Kitematic will able to recognize it.

### Information about the Issue
I used both virtual boxes default comes with docker toolbox as well as new Virtual Box 5.1.26. Both shows same behavior.

### Steps to reproduce the behavior

  1. Delete your .docker folder & .virtualbox folder for clean slate.
  2. Declare `MACHINE_STORAGE_PATH` system variable other than default one. like C:\VM\.docker\machine
  3. Run Kitematic.

This OPTIONAL step makes it interesting. It able to detect certificate but could not detect if docker-machine is running or not. It simply recreates default VM. Very BAD !!!
  4. [Optional STEP] Run docker-machine create command to create default VM. Set appropriate env variables (set env variables after docker-machine env default) and then run Kitematic. 

Kitematic could not able to detect default vm is running. It will recreate VM and this time Kitematic able to start only you will lost all old images. Also, if you close kitematic and run again then also it exhibit same behavior. 

> With this Optional Step Kitematic able to run but it will blows default VM image every time and re-built from cache (I guess). It blows all docker pulled docker images !!!

**Comment by FrenchBen** [comment]
@nsidhaye Can you try with the latest build found in the repo? Toolbox may have not pulled in our most recent fix.
https://github.com/docker/kitematic/releases/tag/v0.17.1

**Comment by rsingh25** [comment]
I tried with v0.17.1 on windows 10 pro. I setup MACHINE_STORAGE_PATH variable to D drive. It still fails with "Certificate directory does not exist".

**Comment by FrenchBen** [comment]
@rsingh25 This is the code that looks up the existing machine:
https://github.com/docker/kitematic/blob/master/src/utils/SetupUtil.js#L137

One thing to keep in mind, is that the setting is an ENV var, which means that you'll need to start Kitematic from the CLI terminal that had the ENV var set.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Comment by oulaly** [comment]
Try to add env var like this `DOCKER_CERT_PATH='C:\VM\.docker\certs'`, make sure there are `.pem` files in `certs` directory.
