### ISSUE TITLE
Pull failing when downloading on Windows 10 Home using Kitematic and command line.  

### ISSUE THREAD

**Issue by mukhasir** [docker/kitematic#2936]
### Information about the Issue
Pull failing when downloading on Windows 10 Home using Kitematic and command line.  
I have Windows 10 Home and I had used Docker tool kit for Docker, but when I run "docker pull Microsoft/aspnet" I am getting this error - "image operating system "windows" cannot be used on this platform". When I pull an image with Linux as base it is downloading and running also, example "docker pull microsoft/dotnet"(which run .NET Core for Linux and Windows)

I need to run asp.net web application on windows container. Can you please help me on this. I have a deadline on making this workout. 

Please help me out.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
