### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by rasmus** [docker/kitematic#2937]
### Expected behavior

Be able to download Docker images from the hub through Kitemagic

### Actual behavior

Fails with a 500 server error

![image](https://user-images.githubusercontent.com/18956/29120497-bb45c596-7d0a-11e7-8aca-a6d160a600ef.png)

### Information about the Issue

- Fresh Windows 10 install (build 15063)
- Fresh Docker install (17.06.0-ce-win19 (12801))
- Behind a proxy

### Steps to reproduce the behavior

  1. Open Kitemagic
  2. Click "Create" on any image

**Comment by FrenchBen** [comment]
Are you using Docker for Windows or Toolbox?
I would make sure that your proxy settings are correct and follow these instructions if you're on Toolbox:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
