### ISSUE TITLE
There are no shared folders for ubuntu image

### ISSUE THREAD

**Issue by inuwas** [docker/kitematic#2941]
![image](https://user-images.githubusercontent.com/12743152/29171990-62c15094-7dd6-11e7-8086-a2d9398feee7.png)

I am having an issue sharing files with my ubuntu installation on Kitematic. Please see the attached image.

![image](https://user-images.githubusercontent.com/12743152/29171998-6c5a54a2-7dd6-11e7-807d-dbc04bc44020.png)
There is nowhere that indicates the folders that are being shared between my mac and the ubuntu installation. Please help. Cheers

**Comment by FrenchBen** [comment]
This works as expected. Ubuntu doesn't share any volumes in their Dockerfile, causing you to not see the option in Kitematic. 
You can however mount folders using the CLI:
https://docs.docker.com/engine/admin/volumes/volumes/
