### ISSUE TITLE
(HTTP code 401) unexpected 

### ISSUE THREAD

**Issue by Highflyer** [docker/kitematic#2943]
### Expected behavior
To create MySQL images.
### Information about the Issue

(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/mysql/manifests/latest: unauthorized: incorrect username or password"}
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
