### ISSUE TITLE
network issue between docker and virtualbox on mac osx

### ISSUE THREAD

**Issue by mmourani** [docker/kitematic#2945]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mmourani** [comment]
![monosnap 2017-08-11 15-17-11](https://user-images.githubusercontent.com/29897003/29211115-2d637526-7ea8-11e7-9187-77eeeec18eb9.png)

**Comment by mmourani** [comment]
i removed all, cleaned all files and reinstalled and I still get the same error.

**Comment by FrenchBen** [comment]
I would recommend you use Docker for Mac instead of Toolbox:
https://docs.docker.com/docker-for-mac/install/

**Comment by mmourani** [comment]
hi again, 

I did as instructed to download the docker for Mac from this link: 
https://docs.docker.com/docker-for-mac/install/

and then I created one container 'dev' successfully and then I tried another container 'default' and i get an error. Please see the snapshots attached 
![terminal -zsh 2017-08-12 16-04-11](https://user-images.githubusercontent.com/29897003/29240524-595c3368-7f78-11e7-9499-a31a60ae3462.png)
![terminal -zsh 2017-08-12 16-04-51](https://user-images.githubusercontent.com/29897003/29240525-5eebab74-7f78-11e7-9c6f-799169551bc4.png)
