### ISSUE TITLE
404 when pulling searchblox in docker

### ISSUE THREAD

**Issue by deelite** [docker/kitematic#2946]
### Expected behavior

Pulling the image

### Actual behavior

Not downloading.

### Information about the Issue

(HTTP code 404) unexpected - {"message":"manifest for searchblox/searchblox:latest not found"}

### Steps to reproduce the behavior

  1. search searchblox in docker repo in Kitematic
  2. click "create"
3. Message: (HTTP code 404) unexpected - {"message":"manifest for searchblox/searchblox:latest not found"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/searchblox/searchblox/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by deelite** [comment]
Thanks for the help. I will give it a try.

Best, Jan.

Am 11.08.2017 23:29 schrieb "French Ben" <notifications@github.com>:
