### ISSUE TITLE
repo missing??

### ISSUE THREAD

**Issue by rgoyankaitrs** [docker/kitematic#2947]
### Expected behavior
my repo that i created yesterday rgoyanka/centos is missing...?
### Information about the Issue
No idea why would that happen

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/rgoyanka/centos/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
