### ISSUE TITLE
Where is the Links field in Kitematic 

### ISSUE THREAD

**Issue by scanlonjts** [docker/kitematic#2952]
### Expected behavior
watched a video and saw someone configuring "Links' on network tab from a Wordpress install to a mariadb - 

### Actual behavior
I don't have the Link

### Information about the Issue
Watch video on : https://www.youtube.com/watch?v=DqqVRIXZwzc&feature=youtu.be

I am using: 
Kitematic on Mac - v. 0.17.0

### Steps to reproduce the behavior

  1. ...  start mariadb container
  2. ... start wordpress container
 3. .. wordpress container / settings/network - no link section

**Comment by FrenchBen** [comment]
That's correct - only 0.17.1 has the new link feature:
https://github.com/docker/kitematic/releases/tag/v0.17.1
