### ISSUE TITLE
Error asked

### ISSUE THREAD

**Issue by devhotmail** [docker/kitematic#2963]
### Steps to reproduce the behavior

  1. I got error when I try to create jekins
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: unauthorized: incorrect username or password"}
 
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
