### ISSUE TITLE
Error when creating kibana container

### ISSUE THREAD

**Issue by flatbunny** [docker/kitematic#2971]
**Expected**

That a kibana container is created

**Actual**

Get error message: 
(HTTP code 404) no such image - no such image: docker.elastic.co/kibana:5.5.1: No such image: docker.elastic.co/kibana:5.5.1

The image is: 

docker.elastic.co/kibana/kibana:5.5.1

Kitematic is trying to use:

docker.elastic.co/kibana:5.5.1

**Replicate**

1. Use docker cli to pull image: docker pull docker.elastic.co/kibana/kibana:5.5.1
2. Use kibana to create container

**Comment by FrenchBen** [comment]
As of right now some of the external repository functionality is broken in Kitematic when using local images.
See: https://github.com/docker/kitematic/issues/2870 for a similar issue.
