### ISSUE TITLE
failed creating a container with kitematic

### ISSUE THREAD

**Issue by kibou227mirai** [docker/kitematic#2972]
I failed creating (downloading) a container with kitematic.
[error messege]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:41514->[::1]:53: read: connection refused"}

**Comment by LightVolk** [comment]
I have the save issue!

**Comment by FrenchBen** [comment]
Can you both provide the details of your setup:
* Windows version
* Docker Version
* Docker for Windows version
* Kitematic version

**Comment by marttinen** [comment]
Same issue here - both for kitematic as well as `docker pull rabbitmq` (or any other package) via console.

Windows 10 `version 1703 (build 15063.502)`
Docker:
```
Version:      17.06.0-ce
API version:  1.30 (minimum version 1.12)
Go version:   go1.8.3
Git commit:   02c1d87
Built:        Fri Jun 23 21:51:55 2017
```
Kitematic: 0.12.0 (taken from kitematic.exe details)

**Comment by kibou227mirai** [comment]
@marttinen 
Thanks! Docker Container running now !
But, when rebooting My PC, I need to format docker all for docker running. 
I will make this as another issue.


# For your reference

My Setup is 
- Windows version：
    Microsoft Windows [Version 10.0.15063]          (Win10Pro)
- Docker For Windows Version：
    Docker version 17.06.0-ce, build 02c1d87
 : 17.06
- Ketematic Version：0.17.1    ※not know kitematic.exe property

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
