### ISSUE TITLE
HTTP code 500

### ISSUE THREAD

**Issue by xutl** [docker/kitematic#2976]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:40967->[::1]:53: read: connection refused"}

**Comment by xutl** [comment]
PS C:\Windows\system32> docker pull php
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:56953->[::1]:53: read: connection refused

**Comment by FrenchBen** [comment]
Kitematic cannot do any magic - If `docker pull php` doesn't work, Kitematic won't be able to solve this.
Make sure that `docker pull php` works from your CLI first.

Do you have a proxy/vpn enabled?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
