### ISSUE TITLE
Kinematic should refresh its list of running containers

### ISSUE THREAD

**Issue by 0xbaadf00d** [docker/kitematic#2977]
### Expected behavior
The Kinematic app should refresh itself the containers that show up as running.

### Actual behavior
The list of running containers only refresh when new containers are created from Kitematic

### Information about the Issue
0.17

### Steps to reproduce the behavior

  1. Run Kitematic
  2. Create and run a new containers with the `docker` CLI

### Comment

Maybe Kitematic should connect to docker daemon (via unix socket or std socket) and listen container creation / deletion event

**Comment by FrenchBen** [comment]
It does.. I can create containers from the CLI and see them come up in Kitematic - 
What containers and configs are you using that aren't getting a refresh.

![alpine](https://user-images.githubusercontent.com/3965324/29541962-94c0e104-868c-11e7-9e73-07501c2d2fa2.gif)


Additionally going to View > Refresh Container List (shorcut CMD/CTRL+R) will refresh it.

**Comment by 0xbaadf00d** [comment]
Hi,

just reinstalled Docker on macOS and Kitematic works as expected.
