### ISSUE TITLE
Refresh of Docker container in Kitematic

### ISSUE THREAD

**Issue by DsrMedia** [docker/kitematic#2979]
I'm changing the docker configuration file and I have to remove and rebuild the containers very often. I create and start the containers from the command line with a build script. 
The new container does not appear in the containers list in kitematic. I have to close kitematic and reopen it again. 

It would be very nice if there is refresh button, which refreshes the local container list.
thx
Max

**Comment by FrenchBen** [comment]
There is one actually - You can click the 'Containers' title or go to View > Refresh Container List (CMD/CTRL+R shortcut)
