### ISSUE TITLE
unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by LiorLindvor** [docker/kitematic#2982]
### Expected behavior
Create New Container
### Actual behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}

### Information about the Issue
I Just Logged in with the actual username and password,

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by andrs1294** [comment]
+1

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by SerdukovAA** [comment]
+1
