### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by fabiocabrini** [docker/kitematic#2983]
### Expected behavior
login and download container
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Information about the Issue
I can not install a container on kitematic.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
