### ISSUE TITLE
Kitematic (Alpha) - Rel. April 2017 + cygwin64 + windows10

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/kitematic#2984]
@HoloSound commented on [Thu May 04 2017](https://github.com/docker/docker.github.io/issues/3164)

### Problem description

Windows 10 German
Cygwin64 
Kitematic (Alpha) - Rel. April 2017

### Problem location

```
user@host /cygdrive/c/Program Files/Docker Toolbox
$ ./start.sh
./start.sh: Zeile 41: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe: Kommando nicht gefunden.
rm: das Entfernen von '/cygdrive/c/Users/a8900scr/.docker/machine/machines/default/default/Logs/VBox.log' ist nicht möglich: Device or resource busy
rm: das Entfernen von '/cygdrive/c/Users/a8900scr/.docker/machine/machines/default/default/Logs/VBoxHardening.log' ist nicht möglich: Device or resource busy
Looks like something went wrong in step ´Checking if machine default exists´... Press any key to continue...

user@host /cygdrive/c/Program Files/Docker Toolbox
$ ls -l start.sh
-rwxrwx---+ 1 Administratoren Domänen-Benutzer 2863  6. Apr 18:10 start.sh

user@host /cygdrive/c/Program Files/Docker Toolbox
$
```

### Project version(s) affected

Kitematic (Alpha) - Rel. April 2017

### Suggestions for a fix

In my installation of virtual Box - the Installation Path is
```
user@host /cygdrive/c/Program Files/Docker Toolbox
$ echo $VBOX_MSI_INSTALL_PATH
C:\Program Files\Oracle\VirtualBox\

user@host /cygdrive/c/Program Files/Docker Toolbox
$
```

These Back-Slashes produce errors in cygwin!

Therefore I coded the exchange of Back-Slashes.

```
user@host /cygdrive/c/Program Files/Docker Toolbox
$ diff start.sh start_new_20170406.sh
40a41,43
> # 20170502 - RS - cygwin differences
> VBOXMANAGE=` echo "${VBOXMANAGE}" | /usr/bin/sed -e 'sx\\\\x/xg' `
>

user@host /cygdrive/c/Program Files/Docker Toolbox
$
```

Rem.: Fault already reported in: Closed #187 !!!

---

@joaofnfernandes commented on [Tue Aug 22 2017](https://github.com/docker/docker.github.io/issues/3164#issuecomment-324151003)

Since this is a product feature, I'm moving this issue to the Kitematic repo.

**Comment by FrenchBen** [comment]
Kitematic doesn't install anything; as shown in the Project version affected, this is a toolbox issue.
Please open an issue in the appropriate repo:
https://github.com/docker/toolbox
