### ISSUE TITLE
Kitematic Installation (Windows 10)

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/kitematic#2985]
@HoloSound commented on [Thu May 04 2017](https://github.com/docker/docker.github.io/issues/3163)

### Problem description

Windows 10 (German)
Installed Oracle VM Virtual Box (latest Version)
after Installation of Kitematic (Alpha)
the Virtual Box gets to an OLD Version !

### Problem location

Installation of Kitematic (Alpha)
installes (its virtualBox version) over an existing newer version of installed Virtual Box!

### Project version(s) affected

Docker Toolbox.exe from 6. April 2017

### Suggestions for a fix

Installation procedure should check if virtual Box already exists on the system.
(Only newer versions should be installed!)

Rem.: Fault was already reported in: Closed #187.

---

@joaofnfernandes commented on [Tue Aug 22 2017](https://github.com/docker/docker.github.io/issues/3163#issuecomment-324152074)

Since this feedback about the product, I'm moving this to the Kitematic repository.

**Comment by FrenchBen** [comment]
Kitematic doesn't install anything; as shown in the `Project version affected`, this is a toolbox issue.
Please open an issue in the appropriate repo:
https://github.com/docker/toolbox
