### ISSUE TITLE
Cannot log into Oracle 11g Express

### ISSUE THREAD

**Issue by robertconti** [docker/kitematic#2989]
### Expected behavior

Installed a new Oracle 11G docker container from Kitematic: wnameless/oracle-xe-11g:latest

Attempting to connect to the Oracle instance from web preview link within Kitematic by supplying 
username = 'system' and password = 'oracle'

Receive invalid credential error

### Actual behavior

I should be able to connect to the DB with these credentials

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This isn't the right location for support with images. 
Feel free to open the issue in their own repo:
https://github.com/wnameless/docker-oracle-xe-11g
