### ISSUE TITLE
Login user can't install recommended docker image

### ISSUE THREAD

**Issue by chinese007** [docker/kitematic#2990]
### Expected behavior
The recommended "hello-world-nginx" image would be installed successfully.
### Actual behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}
### Information about the Issue
This happens on windows 10.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
