### ISSUE TITLE
unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by shubo83** [docker/kitematic#2991]
###environment
kitematic for mac

###behavior
1. search mysql

2. create mysql official

###error info

(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/mysql/manifests/latest: unauthorized: incorrect username or password"}

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
