### ISSUE TITLE
unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by jcpc91** [docker/kitematic#2996]
### Expected behavior
download o install de expected 
### Actual behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/ghost/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ...download o install Kinematic (beta)
  2. ...trya install any image

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by jcpc91** [comment]
@FrenchBen thanks it work!!
