### ISSUE TITLE
When click create button Jenkins

### ISSUE THREAD

**Issue by Kalmaasaly** [docker/kitematic#3000]
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/80/808f0889a6d3770f66860640f668d9e540948f0bd8457da25dd5b1054030153e/data?Expires=1503663836&Signature=Qmi-3cxpyp0eHz1fSVvSkyhXcfoTgCgDx9FdiQ0CKYrEkFQ1eSpj1Ry5yVMy98wRQJGr2zNbsRe~FhA7WdVu3iNAch8x~K1-ltAwAbU4fe-igWNgSLgtb0vWtSw~nOJAMfTI61zT-J46SnGBAgiY4CcadeEU6Pu8HTBuVWByJOk_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: EOF

**Comment by FrenchBen** [comment]
![jenkins](https://user-images.githubusercontent.com/3965324/29731990-850d4858-899b-11e7-9abc-07aa3c764bd8.png)

Mine downloaded and is running without issue - I would retry on a solid connection.
