### ISSUE TITLE
HTTP code 401: unauthorized

### ISSUE THREAD

**Issue by amatosg** [docker/kitematic#3001]
### Expected behavior
Container created
### Actual behavior
Container cannot be installed
### Information about the Issue
When I try to create a container, I get this error:
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. Open Kitematic
  2. Select any container

Using Kitematic 0.17.1 on macOS 10.12.3
![screenshot_26_08_17_01_32](https://user-images.githubusercontent.com/4570069/29739234-6540d69e-89fe-11e7-92c8-fad18ddd9367.png)

**Comment by sunliwen** [comment]
Same issue occurred with the same version until I setup a registry-mirror.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
