### ISSUE TITLE
Not displaying all images

### ISSUE THREAD

**Issue by HaidarZ** [docker/kitematic#3003]
### Expected behavior
Display all local images
### Actual behavior
Local built images are missing.
### Steps to reproduce the behavior
1- Examine the available images using the following command :
$docker image ls
it outputs two images , one for the image I've built, and another one that's my image is using (i.e java).
2- Go to "My Images" tab inside kitematic , it only displays the java image :/

**Comment by FrenchBen** [comment]
Can you show the output of your `docker image ls`? By default Kitematic will not show dangling images.
Additionally the CLI shows all tags line by line, Kitematic keeps the tags confined to the image the belong in. 
i.e. if you have:
`myimage:1.0` and `myimage:2.0` in the CLI, they will show as 2 lines. In Kitematic you will get 1 image labelled `myimage` and when you click the `tag` you can then view `1.0` and `2.0`
