### ISSUE TITLE
"message":"manifest for qiime2/core:latest not found"

### ISSUE THREAD

**Issue by ashwaniiitd123** [docker/kitematic#3009]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/qiime2/core/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
