### ISSUE TITLE
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/ubuntu/manifests/latest: unauthorized: incorrect username or password"}

### ISSUE THREAD

**Issue by catroo** [docker/kitematic#3010]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jcpc91** [comment]
#2996 this issue works for me

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
