### ISSUE TITLE
Can't be pull images named hyperledger/fabric-* 

### ISSUE THREAD

**Issue by caoxie** [docker/kitematic#3012]
### Steps to reproduce the behavior
docker pull hyperledger/fabric-baseimage
Using default tag: latest

Please login prior to pull:
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (849127910@qq.com): caoxie
Password:
Error response from daemon: manifest for hyperledger/fabric-baseimage:latest not found

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/hyperledger/fabric-baseimage/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
