### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by ashwaniiitd123** [docker/kitematic#3016]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ashwaniiitd123** [comment]
I am trying to download qiime 2 from docker but its giving me error. And showing me message to file ticket on Github Repo

**Comment by FrenchBen** [comment]
Please see previous issue that were opened with the same error.
https://github.com/docker/kitematic/issues/3009#issuecomment-325825445
