### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by netfron** [docker/kitematic#3018]
### Information about the Issue

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

  1. find and install new image

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
