### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for buildchimp/koji-dojo-builder:latest not found"}

### ISSUE THREAD

**Issue by k2patel** [docker/kitematic#3020]
### Expected behavior
Downloading
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for buildchimp/koji-dojo-builder:latest not found"}
### Information about the Issue
not able to download images

### Steps to reproduce the behavior

  1. open kitematic
  2. search koji
  3. create 'koji-dojo-builder'
  4 error appear instantaneously

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/buildchimp/koji-dojo-builder/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
