### ISSUE TITLE
Error on create a new container

### ISSUE THREAD

**Issue by yelken** [docker/kitematic#3029]
### Steps to reproduce the behavior

  1. ... Create a new Container
  2. ... (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:40511->[::1]:53: read: connection refused"}

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
