### ISSUE TITLE
kitematic windows server image download issue

### ISSUE THREAD

**Issue by mamudragon** [docker/kitematic#3031]
### Information about the Issue
kitematic cannot download windows images.

### Steps to reproduce the behavior

  1. switch docker to windows containers.
  2. download a MS server 2016 image.
  3. downloading is very slow , when compared to linux containers.
  4. had not downloaded single windows image yet. a/c name : mamudragon
  5. windows image downloading goes up to 74% and then suddenly, shows 53%. Why? How?

**Comment by FrenchBen** [comment]
Check the size of the windows server docker image - It's usually about 6-8GB, instead of the common 100MB Linux docker images.
