### ISSUE TITLE
HTTP code 401

### ISSUE THREAD

**Issue by hotpixelgroup** [docker/kitematic#3034]
### Expected behavior
I can create a new container by clicking "New" then clicking "Create" on a Docker image after I have successfully authenticated

### Actual behavior
I get an error and cannot create a container (using "Redis" as an example)

### Information about the Issue
`(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/redis/manifests/latest: unauthorized: incorrect username or password"}`

### Steps to reproduce the behavior

  1. Login successfully via Docker Hub credentials
  2. See following error: Could not fetch repository information from Docker Hub
  3. Can successfully create Mongo image despite initial error 
`(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/redis/manifests/latest: unauthorized: incorrect username or password"}`
  4. Cannot create any other images at all and get 
`(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/redis/manifests/latest: unauthorized: incorrect username or password"}`

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by hoegge** [comment]
Why is this closed? It is a bug. I had the same issue and signed in with Docker ID and it worked. But Kitematic says "e-mail or docker ID" in the text box, which should then be corrected, right?
