### ISSUE TITLE
manifest for oprudkyi/laravel-bootstrap-adminlte-starter-kit:latest not found

### ISSUE THREAD

**Issue by edunicastro** [docker/kitematic#3036]
### Expected behavior

Download and create the docker image when clicked.

### Actual behavior

Error message is displayed, it looks like it's downloading the image though.

### Information about the Issue

Error Message:
(HTTP code 404) unexpected - {"message":"manifest for oprudkyi/laravel-bootstrap-adminlte-starter-kit:latest not found"}

### Steps to reproduce the behavior

  1. ... lookup 'laravel' in kitematic
  2. ... click on create for the image

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/oprudkyi/laravel-bootstrap-adminlte-starter-kit/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by gamalgogo** [comment]
Use: docker pull -a oprudkyi/laravel-bootstrap-adminlte-starter-kit
