### ISSUE TITLE
Cannot use docker toolbox to pull windows containers.

### ISSUE THREAD

**Issue by JonahAcquah** [docker/kitematic#3040]
### Expected behavior
Pull and run the windows octopus docker image successfully
### Actual behavior
Cannot run a "window" container on my windows 10 set up
### Steps to reproduce the behavior

  1. Try docker pull octopusdeploy/octopusdeploy:3.4.8

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
