### ISSUE TITLE
Solc small but not loading or downloading

### ISSUE THREAD

**Issue by cyberience** [docker/kitematic#3049]
### Steps to reproduce the behavior

  1. New
  2. Solc
  3. select solc First item by ethereum, 13K

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/ethereum/solc/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
