### ISSUE TITLE
Not able to start Spark container

### ISSUE THREAD

**Issue by maksimu** [docker/kitematic#3053]
### Expected behavior
Not able to start/create Spark container

### Actual behavior
Should be able to install Spark

### Information about the Issue
![image](https://user-images.githubusercontent.com/187306/30290277-9ccb61a0-96e3-11e7-8f5e-9b2f9f584464.png)

![image](https://user-images.githubusercontent.com/187306/30290218-72ff23e8-96e3-11e7-9cbf-30d2c1fc02ff.png)

### Steps to reproduce the behavior

  1. Open Kitematics
  2. Search for `spark`
  3. Create new container from the first `spark` result

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/mesosphere/spark/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
