### ISSUE TITLE
Not able to download the images using kitematic

### ISSUE THREAD

**Issue by tiwari251** [docker/kitematic#3056]
### Information about the Issue
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
