### ISSUE TITLE
Error creating hello-world-ngix

### ISSUE THREAD

**Issue by adnangul** [docker/kitematic#3059]
### Expected behavior
Should be able to create 

### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority"}

### Steps to reproduce the behavior

  1. Run Kitematic
  2. Login
  3. New Container -> Select hello-world-ngix 
  4. Select/Click Create button
  5. Error appear
![snaphot](https://user-images.githubusercontent.com/9469824/30350618-22d2a7c8-97dd-11e7-848a-f9c7091a1a2f.png)

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
