### ISSUE TITLE
401 error when already logged in when creating a container

### ISSUE THREAD

**Issue by frandevel** [docker/kitematic#3061]
### Expected behavior
If my user is written in the user info area, I assume I'm logged in properly. Container should start downloading with no issues or error messages.

### Actual behavior
I get: (HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/elasticsearch/manifests/latest: unauthorized: incorrect username or password"}
It stays in a "Downloading" state, but nothing happens any more even if I log back in
### Information about the Issue
This happened when trying to create a "Official" ElasticSearch container

### Steps to reproduce the behavior

  1. Open Kitematic with a logged in session, from the day before.
  2. Search for "Elasticsearch" container.
  3. Click on "create".

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
