### ISSUE TITLE
Question/alert window with squares instead of text on Linux/Fedora 26

### ISSUE THREAD

**Issue by samupl** [docker/kitematic#3064]
### Expected behavior

The confirm window should contain text

### Actual behavior

The confirm window contains squares

### Information about the Issue

Running on X.org instead of wayland, basically on default settings when it comes to fonts.

```
$ cat /etc/fedora-release
Fedora release 26 (Twenty Six)

$ uname -r
4.12.11-300.fc26.x86_64

$ gnome-shell --version
GNOME Shell 3.24.3

```

### Steps to reproduce the behavior

  1. Build and run Kitematic on Fedora 26 (make && npm start, or build RPM using grunt)
  2. Find an old stopped container and click on the "X" button to remove it
  3. Observe the confirmation window

### Attachments

![Screenshot with bug](https://cdn.pbrd.co/images/GKi2BrZ.png)

**Comment by samupl** [comment]
Upon clicking on a modal nothing appears in the console:

```npm start                                                                                                                                                                              master

> Kitematic@0.17.1 start /home/js/git/kitematic
> grunt

Running "newer:babel" (newer) task

Running "newer:babel:dist" (newer) task
No newer files to process.

Running "less:dist" (less) task
>> 1 stylesheet created.

Running "newer:copy:dev" (newer) task

Running "copy:dev" (copy) task
Copied 156 files

Running "newer-postrun:copy:dev:1:/home/js/git/kitematic/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "shell:electron" (shell) task

Running "watchChokidar" task
Waiting...
Utworzono nowe okno w istniejącej sesji przeglądarki.
```

(The last line was me opening a link through kitematic, which causec my chrome to report this)

**Comment by samupl** [comment]
Apparently, this can be fixed by following steps outlined in another issue: https://github.com/docker/kitematic/issues/2357 - simply using newer version of electron seems to fix the problem. Any possibility to have this merged into the future release?

**Comment by FrenchBen** [comment]
@samupl Unfortunately I don't have the necessary cycles to make this happen - Is this something you could help with?

**Comment by samupl** [comment]
I could try in my free time. Aparrently, newer version of electron causes other bugs to appear. I'll find some free time and read through the development guide and see what I can do :)

**Comment by FrenchBen** [comment]
Fixed by https://github.com/docker/kitematic/pull/3313
