### ISSUE TITLE
Kitematic stops and delete all the changes

### ISSUE THREAD

**Issue by mrmmins** [docker/kitematic#3066]
### Information about the Issue
I'm not sure how to define this issue.
But basically I'm doing this:
I installed Docker Kitematic 0.17.0 and I installed (a lot of times) Django (Official) using the GUI.
and I start a new Django Project.
All is good at this point.
When the image is running, I'm trying to add a new port (8000 to be specific) and the image is restarted and all my changes are deleted (but, not only my project changes, also the apt-get changes) and the image is restarted as the original.

It's very weird, and the only change that I'm doing is adding the port using the GUI

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Containers are note stateful (immutable) and thus aren't suppose to be modified - If you need to make modifications that persist:
* Mount a directory where the data will be saved
* Mount a volume where the data will be saved

When kitematic makes a  port change it re-creates the container in the background, as there is no way to dynamically change a container's config post-creation.
