### ISSUE TITLE
rmeertens/tensorflowgym is not working

### ISSUE THREAD

**Issue by seantab** [docker/kitematic#3071]
### Steps to reproduce the behavior

  1. ... Can not download this docker, I already tried several times both from kite and docker prompt... once finishes around 99% it throws an error as follow
  2. ...failed to register layer: Error processing tar file(exit status 1): write /notebooks/OpenCV/build/modules/stitching/test_precomp.hpp.gch/opencv_test_stitching_Release.gch: no space left on device

**Comment by FrenchBen** [comment]
No space left means that you'll need to either clean up existing images, or create a larger drive in Virtualbox.

`docker image prune` to cleanup unused images
Creating a new VM with 100GB space:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space
