### ISSUE TITLE
dial tcp: lookup auth.docker.io on 10.0.2.3:53: read udp 10.0.2.15:34574->10.0.2.3:53: i/o timeout

### ISSUE THREAD

**Issue by Seifeddine111** [docker/kitematic#3072]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
