### ISSUE TITLE
HTTP code 500

### ISSUE THREAD

**Issue by haozi000005** [docker/kitematic#3073]
### Information about the Issue
server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:37538->[::1]:53: read: connection refused"}

### Steps to reproduce the behavior

  1. download a image

**Comment by FrenchBen** [comment]
Please try to use the Docker registry from China instead:
https://www.docker-cn.com/registry-mirror
