### ISSUE TITLE
Not able to get Docker file for Carto DB

### ISSUE THREAD

**Issue by prakashavenue** [docker/kitematic#3075]
### Expected behavior
Should be able to download docker 
### Actual behavior
Failing
### Information about the Issue

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

  1. From Docker Kitematic search for CartoDB then click on create on the first result.
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
If not feel free to re-open this issue!
