### ISSUE TITLE
Kitematic Mac App email login field

### ISSUE THREAD

**Issue by dzienisz** [docker/kitematic#3077]
### Expected behavior
Email longer than 30 signs should be valid

### Actual behavior
You can't put emails longer than 30 signs

**Comment by FrenchBen** [comment]
Thanks for the issue - Hub is having some difficulty with pulling images via emails atm - It's encouraged to use the Docker ID rather than the email. 
I'll keep this open for tracking purposes.

**Comment by mhelmetag** [comment]
@FrenchBen , so would you want to remove the ability to use email (just use username)? Or just extend the limit?

**Comment by dzienisz** [comment]
Docker account provide login by email so I would like to extend that field.

In my case I'm missing just one letter. Make this field like 40 characters?

**Comment by FrenchBen** [comment]
I think that for now it may be best to disable email login, due to the hub issues.

**Comment by mhelmetag** [comment]
Sounds good 👌 I could see that the other option would be to mimic the character limit on the email field to be the same as the one in DockerHub (possibly 255 or something).

**Comment by mhelmetag** [comment]
I think this can be closed now that kitematic only uses usernames.

**Comment by FrenchBen** [comment]
Fixed in #3229 - Closing
