### ISSUE TITLE
Add ability to specifiy repository URL to pull from

### ISSUE THREAD

**Issue by jbaruch** [docker/kitematic#308]
That's a bit related to #232, but not exactly. #232 is about adding authentication while I am talking about replacing the DockerHub with another URL completely (with or without authentication).

**Comment by jeffdm** [comment]
Great! Thanks for the issue!

**Comment by ccit-spence** [comment]
In our case we use Artifactory to store our docker images.  This would apply for us since we can't specify the URL.

**Comment by FrenchBen** [comment]
Closing as dup of #210
