### ISSUE TITLE
Docker Toolbox Error: Kitematic Error: Windows 7

### ISSUE THREAD

**Issue by Zuhayer** [docker/kitematic#3081]
### Expected behavior
Kitematic to run for the first time.
### Actual behavior
Error while loading Virtual Box/
### Information about the Issue
Just installed the toolbox, trying to use docker.

### Steps to reproduce the behavior

  1. Windows 7
  2. Install docker toolbox

I am getting same error on Windows 7. It is my company laptop and I cannot install Win10 on it. 

Is there a solution to this, which does not require Win10 or latest setup?

![untitled](https://user-images.githubusercontent.com/5408155/30587208-c84e3654-9d4b-11e7-9a48-bdb8df441434.png)

**Comment by FrenchBen** [comment]
Can you try to run the machine create via PowerShell first?
`docker-machine -D create default`

**Comment by Zuhayer** [comment]
The output of command `docker-machine -D create default` is too long to fit here. I have saved it in a file. It keeps repeating the last lines of the error.
[command response.txt](https://github.com/docker/kitematic/files/1336886/command.response.txt)

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Comment by Zuhayer** [comment]
ok @FrenchBen.

**Comment by juanaquino77** [comment]
Hello, I have the same error, how can I solve it?
