### ISSUE TITLE
Unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by noahgift** [docker/kitematic#3084]
### Expected behavior
Downloading a docker container in Kitematic
### Actual behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: unauthorized: incorrect username or password"}### Information about the Issue

### Steps to reproduce the behavior

  1. ...Create New 
![screen shot 2017-09-20 at 11 35 46 am](https://user-images.githubusercontent.com/58792/30661127-db825fc8-9df7-11e7-8f70-066df4b7ac2e.png)

  2. ...

**Comment by andrewjamesford** [comment]
I commented out the "credsStore" line in my docker config.json to be able to retrieve public images.

`{
  // "credsStore" : "osxkeychain",
  "auths": {
    "https://index.docker.io/v1/": {}
  }
}`

~/.docker/config.json

**Comment by noahgift** [comment]
Ah, good to know, that is a help to use the UI.  Seems like a bug here they should fix.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
