### ISSUE TITLE
Installation error on Opendronemap

### ISSUE THREAD

**Issue by danieldupre** [docker/kitematic#3088]
Installing https://hub.docker.com/r/nro2dai/odm/ 
into may Windows 10 docker I received this error 

failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\39218900c699cca3b108d743c3724017ffe216a5b8873b88846d53ced67b5b41: The system cannot find the path specified.

**Comment by FrenchBen** [comment]
Looks like an error on Download - Could you try again via the CLI and post any output here?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
