### ISSUE TITLE
ide50-offline error

### ISSUE THREAD

**Issue by Siya360** [docker/kitematic#3102]
### Expected behavior
trying to create / downloading ide50-offline via Kitematic (beta)

### Actual behavior
I am logged in to Docker so the credentials are correct not too sure why is says incorrect
### Information about the Issue
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/cs50/ide50-offline/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ...start kitematic
  2. ...search for 'cs50ide-offline' and click create

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by Siya360** [comment]
Thank you, it worked but image i was downloading produced an error while in progress, ticket:#3136  already opened for it
