### ISSUE TITLE
can't authenticate kitematic from mac to my account

### ISSUE THREAD

**Issue by prutasiscale** [docker/kitematic#3104]
### Actual behavior
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
