### ISSUE TITLE
Error 500 after clicking on Create for "official Postgres" image on Ubuntu

### ISSUE THREAD

**Issue by SpartaHub** [docker/kitematic#3107]
### Expected behavior
Downloading starts successfully

### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/postgres/manifests/latest: unauthorized: incorrect username or password"}

### Preconditions
kinematic is installed on Ubuntu 17.04

### Steps to reproduce the behavior

  1. Open kinematic
  2. Click on +NEW
  3. Type "Postgres" to Search field
  4. Click on Create for official Postgres image

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
