### ISSUE TITLE
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}

### ISSUE THREAD

**Issue by josejayesh** [docker/kitematic#3109]
### Steps to reproduce the behavior

  1. ...Login to kitematic using docker id 
2. Successfully logded in 
  3 . try to add container 

<img width="1031" alt="screen shot 2017-09-29 at 4 37 41 pm" src="https://user-images.githubusercontent.com/204433/31039685-8a474972-a534-11e7-96a1-d82980314591.png">

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
