### ISSUE TITLE
Windows Container error when pulling image

### ISSUE THREAD

**Issue by dawson1990** [docker/kitematic#3115]
### Expected behavior
To pull an image of Couchbase 
### Actual behavior
gives an error: no matching manifest for windows/amd64 in the manifest list entries
### Information about the Issue
Happens when trying to pull some images also, but others work fine.

### Steps to reproduce the behavior

  1. Switch to Windows Containers
  2. run command:
 docker run -d --name db1 -p 8091-8094:8091-8094 -p 11210:11210 couchbase:enterprise-4.6.3

**Comment by FrenchBen** [comment]
Not all images have windows equivalent - I would confirm with the image owner that a windows version, with that tag exists.
