### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for drupalci/php-5.3.29-apache:latest not found"}

### ISSUE THREAD

**Issue by vasilvestre** [docker/kitematic#3116]
### Expected behavior
Working php 5.3 apache container
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for drupalci/php-5.3.29-apache:latest not found"}
### Information about the Issue
It happen only when I use kitematic GUI

  1. Install Kitematic on windows
  2. Download drupalci php5.3.29-apache image

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/drupalci/php-5.3.29-apach/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
