### ISSUE TITLE
Docs button leads to a 404 page

### ISSUE THREAD

**Issue by sivanbecker** [docker/kitematic#3117]
### Expected behavior
i would expect the gui to say something like:  " sorry but there are no available docs" and not opening my browser.

### Actual behavior
i got a 404 page on my browser.

### Information about the Issue
The project i'm working on (at work) uses images which i dont load to docker hub, we use an internal registry. 

### Steps to reproduce the behavior

  1. simply push the docs button when no docs exist for a container/project.
  
please  let me    know  if i can assist with more details or help solve it.

Thanks
Sivan

**Comment by FrenchBen** [comment]
If you click the docs icon for a container that was built locally, you will not get "docs" - Docs are really a shortcut to the landing page on Docker Hub for that container image.
