### ISSUE TITLE
Not logged in 500 error when creating a new container

### ISSUE THREAD

**Issue by laran** [docker/kitematic#3120]
### Expected behavior
Not an error

### Actual behavior
- Created a new redis container by clicking "Create".
- Got this error:
```(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/redis/manifests/latest: unauthorized: incorrect username or password"}```

### Information about the Issue
- I am logged in (so I know my username and password are correct)

### Steps to reproduce the behavior

  1. Log into Kitematic
  2. Click "+ NEW" button
  3. Click "CREATE" next to any image

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
