### ISSUE TITLE
EXEC-spawned shell closes if pressing two keyboard keys at the same time

### ISSUE THREAD

**Issue by dkoding** [docker/kitematic#3121]
### Expected behavior
Shell window does not close when I press several letters on keyboard simultaneously.

### Actual behavior
Shell window closes when I press several letters on keyboard simultaneously.
For example - if I press 'v' and 'b' at the same time (could happen!) the shell simply closes.

### Steps to reproduce the behavior

  1. Press 'Exec' button to open new shell
  2. Press 'v' and 'b' or any other two adjacent letter keys at the same time

**Comment by dkoding** [comment]
Forgot to mention: Platform Windows 10 Home.

**Comment by dkoding** [comment]
Docker image: kafka-zookeper-single

Environment: SHELL: /bin/bash

Windows 10

[image: Innebygd bilde 1]

2017-10-04 22:10 GMT+02:00 French Ben <notifications@github.com>:

**Comment by FrenchBen** [comment]
Looks like the image is missing - Can you update?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.

**Comment by dkoding** [comment]
kafka-zookeper-single is the docker image I was using., but I've been using several others with the same result.
