### ISSUE TITLE
Kitematic stuck at 100% loading VM upon first start

### ISSUE THREAD

**Issue by sindhus** [docker/kitematic#3122]
### Expected behavior

I would expect Kitematic to start up 

### Actual behavior

Kitematic stuck at 100% loading VM

### Information about the Issue

From other bug reports, I understood that Kitematic is trying to create a 'default' machine. The binary that creates this is `docker-machine`, so I manually ran `docker-machine create --driver virtualbox default`, this in turn downloads 'boot2docker.iso' (40mb).

There is no indication in the UI that all this is happening in the background. Because I have a slow flaky connection, this process seems to take forever. Would be nice if I told what was going on behind the screens.

### Steps to reproduce the behavior

  1. Fresh install of Kitematic Docker Toolbox on OS X
  2. Start Kitematic for the first time

**Comment by FrenchBen** [comment]
when you run it by hand, do you get the proper VM to start?
If you're on OSX, I highly recommend you move to [Docker for Mac](https://www.docker.com/community-edition#/mac)

**Comment by yutanakano** [comment]
I am using `docker for mac`
When you run `Kitematic`, the following message appears

```
VirtualBox is not installed. Please install it via the Docker Toolbox.
```

**Comment by FrenchBen** [comment]
@yutanakano if you previously used Toolbox, there's a chance you had some Kitematic settings that matched. 
There should be a `reset` button that will allow you to set everything back to normal

**Comment by yutanakano** [comment]
Thank you for your early reply
I have never used `Toolbox`
I can not click `reset` of the attached image
Will it be another problem?
![2017-10-11 1 04 00](https://user-images.githubusercontent.com/8127089/31397151-2e1fcce2-ae20-11e7-9396-212b52210beb.png)

**Comment by FrenchBen** [comment]
@yutanakano You mean that the `reset` button is not clickable for you? Can you show the console log output?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
