### ISSUE TITLE
Refresh is not done correctly in Kitematic

### ISSUE THREAD

**Issue by adiallo-talend** [docker/kitematic#3125]
I have a private repository where i am pulling images from using the powershell cli you provide. The issue i am facing is that Kitematic UI is not getting refresh (Not sure if it is really the expected behavior for the alpha version), but i am expecting to see in the list of images then when i start in the containers, this is not always the case. Had to restart the GUI sometime before seeing the images/containers

**Comment by FrenchBen** [comment]
You can "force" a refresh either through CTRL+R or going to View ->  Refresh Container list.
