### ISSUE TITLE
Download MSSQL-SERVER-LINUX not possible

### ISSUE THREAD

**Issue by bertush** [docker/kitematic#3126]
### Expected behavior
Download mussel-server-linux container

### Actual behavior
Error message "HTTP code is 404 which indicates error: undefined - {"message":"manifest for microsoft/mssql-server-linux:latest not found"}" appears. Container is nog downloaded.

### Information about the Issue
MacOs High Sierra
Docker 17.09.0-ce-mac33
Kitematic 0.12.0

### Steps to reproduce the behavior

  1. Start Docker
  2. Start Kitematic
  3. In Kitematic click New. Enter MSSQL in the Search field.
  4. Select microsoft mysql-server-linux Create button

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/microsoft/mssql-server-linux/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
