### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by Zerof007** [docker/kitematic#3127]
i want to add new containers, and have chosen one but it can not be download

thank you for helping me

**Comment by FrenchBen** [comment]
Can you provide the command that you're running in the terminal?

**Comment by superg28** [comment]
I'm having the same problem, running the commands in the doc example

    docker push superg28/get-started:part2

get the following

![image](https://user-images.githubusercontent.com/3284154/31664905-74021f04-b347-11e7-8fa7-46eb164085cb.png)

then with the next attempt

![image](https://user-images.githubusercontent.com/3284154/31664934-9592fac6-b347-11e7-8b3d-ac6f2da86e73.png)

**Comment by FrenchBen** [comment]
Seems that image is private, which means that I cannot replicate the issue. 
TLS timeout is usually due to a bad connection - Can you try using the Google Public DNS?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
