### ISSUE TITLE
We are fetting this error

### ISSUE THREAD

**Issue by pmummhc** [docker/kitematic#3128]
no matching manifest for windows/amd64 in the manifest list entries

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
