### ISSUE TITLE
Missing manifest for microsoft/mssql-server-linux image

### ISSUE THREAD

**Issue by ndongo** [docker/kitematic#3131]
### Expected behavior
The image is downloaded from the hub.

### Actual behavior
An HTTP code 404 is received with the following error 
(HTTP code 404) unexpected - {"message":"manifest for microsoft/mssql-server-linux:latest not found"}

### Information about the Issue
As described above.
Versions info: 
Docket Version 17.09.0-ce-mac33 (19543) on MacOs Sierra
Docker Kitematic 0.13.1

### Steps to reproduce the behavior

  1. Open Kitematic 
  2. Add new 
  3. Search for mssql-server-linux image
  4. Select for the Microsoft's version 
  5. It loads and fails.
<img width="1088" alt="dockererrormicrosoft" src="https://user-images.githubusercontent.com/962671/31297524-90bca9b6-aae6-11e7-8786-defd179f90f0.png">

**Comment by zxxz** [comment]
@ndongo the `latest` tag is not currently available. You can choose `2017-GA` or `2017-latest` see [hub](https://hub.docker.com/r/microsoft/mssql-server-linux/tags/). 
See also https://github.com/docker/kitematic/issues/3126.

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/microsoft/mssql-server-linux/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by ndongo** [comment]
Thanks, guys.
