### ISSUE TITLE
### (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### ISSUE THREAD

**Issue by tamvcspk** [docker/kitematic#3135]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by tamvohaphan** [comment]
You absolutely right. We cannot login by email. We have to login by id
