### ISSUE TITLE
Read-Only file system error whistle downloading image

### ISSUE THREAD

**Issue by Siya360** [docker/kitematic#3136]
### Expected behavior
to download ide50-offline image
### Actual behavior
donwloads, and spews an error at 43% download progress
### Information about the Issue
write /mnt/sda1/var/lib/docker/tmp/GetImageBlob193812294: read-only file system

### Steps to reproduce the behavior

  1. ...donwload ide50-offline image
  2. ...monitor download progress

**Comment by FrenchBen** [comment]
Can you provide a link to the actual hub image? I would recommend having a solid connection if the image is large.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
