### ISSUE TITLE
Unable to login to Dockerhub as email contains "+"

### ISSUE THREAD

**Issue by misschak** [docker/kitematic#3137]
### Expected behavior
On dockerhub login screen, allow email to contain "+"
### Actual behavior
Validator Error "Must be 4-30 lower case letters or numbers, or a valid email"
### Steps to reproduce the behavior

  1. Login from Kitematic App
  2. Use email address with "+"

**Comment by FrenchBen** [comment]
Logging to Docker Hub with an email is currently not working as expected. Please use your Docker ID to login instead.

**Comment by misschak** [comment]
Oops, I see.. thanks much FrenchBen!
