### ISSUE TITLE
Node.js container doesn't work on OSX

### ISSUE THREAD

**Issue by ccarnino** [docker/kitematic#314]
Hi!
I am trying to add a new container for the stack MEAN.js (MongoDb, Express, Angular, Node.js) on my OSX Yosemite.

I tried the one of maccam912/meanjs (and different other meanjs and nodejs containers). All download correctly, but as soon as I try to Start them, the label goes back to STOPPED. I have no logs and no indication of what's wrong.

It could be a problem of port forwarding between the node.js server and the container, or something similar.

I tried to run the nginx hello world container and it works correctly.

How can I help to fix the problem?
Thanks a lot!

**Comment by jeffdm** [comment]
Hi there. Thank for the issue!

What would be your ideal behavior of Kitematic for this image? That will help us work together on a fix :smiley: 

Note: Kitematic defaults the to running the command in the `CMD` directive specified in the image's `Dockerfile` when it starts the container. [In this case](https://registry.hub.docker.com/u/maccam912/meanjs/dockerfile/) there doesn't seem to be a CMD directive. It looks like on the CLI you specify the `bash` command which keeps the container alive. Kitematic's bad at running these containers in general, since it runs 'bash' but in the background, and the container dies.

One idea is to:
- Make Kitematic run some long-runnig process by default so the container stays alive.
- Small fix on the meanjs image: run the MongoDB process by default.

**Comment by ccarnino** [comment]
Thanks for the response, but I think it's a problem with the ports.
I tried to add the `CMD mongod`, but nothing changes.

Now I tried to use the official meanjs repo, running from terminal with `fig`, and I get the same problem.
I think it's a problem of docker, not of Kitematic.

This are all the steps:
`git clone https://github.com/meanjs/mean.git .
boot2docker up
fig build
fig up`

And this is the log I get:
`Galeon:meanjs claudio$ fig up
Recreating meanjs_db_1...
Recreating meanjs_web_1...
Attaching to meanjs_db_1, meanjs_web_1
db_1  | 2015-03-21T13:43:51.077+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=b53d05ecb1de
db_1  | 2015-03-21T13:43:51.077+0000 I CONTROL  [initandlisten] 
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] 
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] 
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] db version v3.0.0
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] git version: a841fd6394365954886924a35076691b4d149168
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] build info: Linux ip-10-171-101-151 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 BOOST_LIB_VERSION=1_49
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1  | 2015-03-21T13:43:51.078+0000 I CONTROL  [initandlisten] options: {}
db_1  | 2015-03-21T13:43:51.085+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
db_1  | 2015-03-21T13:43:51.086+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
db_1  | 2015-03-21T13:43:51.168+0000 I JOURNAL  [durability] Durability thread started
db_1  | 2015-03-21T13:43:51.168+0000 I JOURNAL  [journal writer] Journal writer thread started
db_1  | 2015-03-21T13:43:51.173+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
web_1 | Running "jshint:all" (jshint) task
web_1 | >> 56 files lint free.
web_1 | 
web_1 | Running "csslint:all" (csslint) task
web_1 | >> 2 files lint free.
web_1 | 
web_1 | Running "concurrent:default" (concurrent) task
web_1 | Running "nodemon:dev" (nodemon) task
web_1 | Running "watch" task
web_1 | Waiting...
web_1 | [nodemon] v1.2.1
web_1 | [nodemon] to restart at any time, enter `rs`
web_1 | [nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js
web_1 | [nodemon] starting `node --debug server.js`
web_1 | Debugger listening on port 5858
web_1 | --
web_1 | MEAN.JS - Development Environment application started
web_1 | Environment:			development
web_1 | Port:				3000
web_1 | Database:			mongodb://localhost/mean-dev
web_1 | --
web_1 | Could not connect to MongoDB!
web_1 | Error: failed to connect to [localhost:27017]`

This is the first time I play with docker/Kitematic, so I cannot really understand what is happening.

Thanks for the help

**Comment by jeffdm** [comment]
Sorry for the delay

Interesting, does the `DB_1_PORT_27017_TCP_ADDR` environment variable get set properly in the web container?

**Comment by andrewsuzuki** [comment]
Same problem here.

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
