### ISSUE TITLE
unable to download websphere liberty from mac

### ISSUE THREAD

**Issue by navindian** [docker/kitematic#3140]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by navindian** [comment]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

**Comment by FrenchBen** [comment]
Is this using Docker for Mac or Toolbox?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
