### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: unauthorized: incorrect username or password"}

### ISSUE THREAD

**Issue by jackfruh** [docker/kitematic#3150]
Used Kitematic to try to download hello-world.
I am signed into kitematic

**Comment by falihakz** [comment]
try using your username instead of email. It works for me.

**Comment by lightningspirit** [comment]
I confirm that changing the login form email to username worked for me. I wasn't able to connect to Docker Hub using Kitematic. After signing out and login again using username instead of email, I was able to download containers.

**Comment by diverjoe** [comment]
Solved my problem as well.

**Comment by amir2260** [comment]
work!!! for me, thanks.

**Comment by Alucardxy** [comment]
OK! It's Worked, thanks!
