### ISSUE TITLE
IBM dashdb problem after download

### ISSUE THREAD

**Issue by nigelfreddy** [docker/kitematic#3158]
### Expected behavior
Download would complete successfully
### Actual behavior
After download completed received the error below. I have registered with Docker and with Ibm and received confirmation from ibm
### Information about the Issue
(HTTP code 404) unexpected - {"message":"pull access denied for ibmdashdb/local, repository does not exist or may require 'docker login'"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/USER/IMAGE/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
