### ISSUE TITLE
I cannot download redis system from docker.

### ISSUE THREAD

**Issue by allwell997** [docker/kitematic#3160]
### Steps to reproduce the behavior

  1. doeck pull redis
  2. the system return the message "no matching manifest for windows/amd64 in the manifest list entries"

**Comment by FrenchBen** [comment]
Redis is a linux docker image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
