### ISSUE TITLE
Error after install?

### ISSUE THREAD

**Issue by Atomzwieback** [docker/kitematic#3161]
### Expected behavior
after install on mac i hope it will be work
### Actual behavior
after install i logged into my docker acc
### Information about the Issue
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/kitematic/minecraft/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

IDK

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
