### ISSUE TITLE
canvas-lms download fails

### ISSUE THREAD

**Issue by brandondrew** [docker/kitematic#3162]
### Expected behavior

canvas-lms:latest image would download and a container would be created.

### Actual behavior

    (HTTP code 404) unexpected - {"message":"manifest for instructure/canvas-lms:latest not found"}

### Steps to reproduce the behavior

  1. click <kbd>+ New</kbd>  in Kitematic
  2. search for canvas-lms
  3. choose the (likely) first option—instructure/canvas-lms:latest
  4. watch it fail

**Comment by brandondrew** [comment]
@FrenchBen thanks for the reply.  Just so I understand the situation, and can make the appropriate request to the appropriate people, is the `latest` tag something that Kitematic expects everything to have for everything, or did someone from Instructure create an entry somewhere that specified the `latest` tag (which Kitematic read from), but also turned around and failed to provide anything with that tag in their git repo?

**Comment by aholland** [comment]
@brandondrew thank, I have reported this to Instructure. It's their problem. It happens on the command line too, not just with Kitematic (honestly I don't even know what Kitematic is). https://github.com/instructure/canvas-lms/issues/1330
