### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for ansible/ansible:latest not found"}

### ISSUE THREAD

**Issue by endriv** [docker/kitematic#3164]
### Expected behavior
create a container

### Actual behavior

(HTTP code 404) unexpected - {"message":"manifest for ansible/ansible:latest not found"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
This is expected - Please see https://github.com/docker/kitematic/issues/2626#issuecomment-302021541
