### ISSUE TITLE
twill/jenkins-dind-ansible, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by preinking** [docker/kitematic#3167]
### Expected behavior

download of docker image

### Actual behavior

reply repository does not exist or may require 'docker login'

### Information about the Issue

Response that you cannot download an image that has just been uploaded does not make sens

### Steps to reproduce the behavior

  1. create image, push image
  2. pull the same image

Although the image is create its impossible to download the same

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
It's difficult for me to troubleshoot your issue as the image seems to be private and thus cannot be accessed publicly.
