### ISSUE TITLE
docker: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\d2dab1878cf591d869d33aa2c4cd410cd92614a44c776041c506fc765c1a98f1: The system cannot find the path specified.

### ISSUE THREAD

**Issue by satishdhanaraj** [docker/kitematic#3170]
Am trying to pull an image from docker hub.

> docker pull zuehlke/shiny

And am facing below error:
`docker: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\d2dab1878cf591d869d33aa2c4cd410cd92614a44c776041c506fc765c1a98f1: The system cannot find the path specified.`

**Am having Docker for Windows:**
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true

Thanks in Advance

**Comment by kh77** [comment]
same issue i m facing

**Comment by FrenchBen** [comment]
@satishdhanaraj if the `docker pull` failed, then it seems to be more of a setup issue, then a Kitematic issue.
Please open an issue in either https://github.com/docker/for-win/issues or https://github.com/docker/toolbox/issues
