### ISSUE TITLE
lren/xnat:latest not found

### ISSUE THREAD

**Issue by spmmachine** [docker/kitematic#3171]
### Expected behavior
starting up a xnat server

### Actual behavior
Error code:
(HTTP code 404) unexpected - {"message":"manifest for lren/xnat:latest not found"}

### Steps to reproduce the behavior
  1. Start Kinematic
  2. Search for "xnat"
3. install lren/xnat image

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/lren/xnat/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
