### ISSUE TITLE
Error adding/creating docker container with Kitematic for windows

### ISSUE THREAD

**Issue by Ben1980** [docker/kitematic#3173]
### Expected behavior
Add a new container when clicking on create

### Actual behavior
Shows error screen:
![17-10-2017 11-51-17](https://user-images.githubusercontent.com/919260/31658517-8716a896-b331-11e7-8be6-79fc7b4046f4.png)

### Steps to reproduce the behavior
  1. Start Kitematic for Windows
  2. Login with xour credentials
  3. Click on create of an existing container, such as postgres.
  4. Download sign appears, but error screen is shown when selecting container

**Comment by Aareon** [comment]
Experiencing this on Ubuntu 16.04.3 as well. Same steps to reproduce.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by Ben1980** [comment]
Ok yes it does solve the problem.
But i still would say this is a bug, simply because its posible to login into docker hub with the email.

**Comment by Aareon** [comment]
I agree with @Big Ben. If email logins were at least disallowed, it would clear up a lot of ambiguity with this error.
