### ISSUE TITLE
Can't start container from custom docker registry mirror

### ISSUE THREAD

**Issue by dstockton** [docker/kitematic#3175]
### Pre-requisites...
From the command line, pull a docker image from your private registry...
```
$ docker images
REPOSITORY                                                        TAG                 IMAGE ID            CREATED             SIZE
registry1-eu1.protect-the-innocent.com:5000/jenkins-slave   latest              d9fd3aa4af2e        13 days ago         570MB
```
Image shows on list.

### Expected behavior
Click ```Create``` button and expect a container to start.
### Actual behavior
Click ```Create``` button and see an error:
```(HTTP code 400) unexpected - no such image: registry1-eu1.protect-the-innocent.com:5000/jenkins-slave:5000/jenkins-slave: invalid reference format```
### Information about the Issue
- macOS Sierra 10.12.6
- Kitematic 0.17.1
- Docker for Mac
-- Version 17.09.0-ce-mac35 (19611)
-- Channel: stable
-- a98b7c1b7c
### Steps to reproduce the behavior

  1. docker pull from private registry
  2. click 'create' on image in Kitematic UI

**Comment by FrenchBen** [comment]
This is a slightly different issue, where there is a bug in the parsing of private registry images that appear within your local images. 
Closing in favor of previous issue: https://github.com/docker/kitematic/issues/2870
