### ISSUE TITLE
Kitematic failure to login

### ISSUE THREAD

**Issue by webmaster-trackandrecover** [docker/kitematic#3178]
### Expected behavior
Login and be able to retrieve Docker Images and run them
### Actual behavior
We're sorry. There seems to be an error:
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/mysql/manifests/latest: unauthorized: incorrect username or password"}

If this error is invalid...
### Information about the Issue
I'm able to login to Github repo, to docker.io..etc Even Kitematic logs in using my credentials yet I'm unable to pull Dockers.

### Steps to reproduce the behavior

  1. Login normally
  2. Attempt to pull and Docker image

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
