### ISSUE TITLE
Why does this problem happen? (HTTP code 500) server error -

### ISSUE THREAD

**Issue by shogosanz** [docker/kitematic#3185]
### Expected behavior
work
### Actual behavior
did not work
### Information about the Issue
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/wonderfall/cowrie/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. select +NEW
  2. select any docker image
  3. click create
  4. error

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
