### ISSUE TITLE
I can't install on mac

### ISSUE THREAD

**Issue by blyzer** [docker/kitematic#3190]
### Expected behavior
install!
### Actual behavior
cannot used on this platform.
### Information about the Issue
running docker on Mac

### Steps to reproduce the behavior

  1. search image
  2. selected
  3. click install.

**Comment by FrenchBen** [comment]
What did you install?
What image did you select?
Can you run it via the CLI?

**Comment by blyzer** [comment]
Was a image of windows core on docker running on Mac.

Enver Francisco

**Comment by pgensler** [comment]
Related, I tried to re-install Docker Tools for OS X on my machine, when I try to click "Use Kitematic" in the installer, I get the following error:
![image](https://user-images.githubusercontent.com/7308115/32018166-a97accec-b98e-11e7-9aac-a05cde71becd.png)
I am able to run docker via the Docker Quickstart Terminal
I'm on OS X Sierra 10.12.6.  Let me know if you need more info, or any logs. Should the
