### ISSUE TITLE
docker php-msf failed

### ISSUE THREAD

**Issue by zxq911** [docker/kitematic#3196]
### Expected behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:54553->10.0.2.3:53: i/o timeout"}

### Information about the Issue

how to deal this question!

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
