### ISSUE TITLE
Can't pull image, error 500 even after logging in via Kitematic

### ISSUE THREAD

**Issue by Aareon** [docker/kitematic#3197]
### Expected behavior
Pull image

### Actual behavior
```
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}
```
### Information about the Issue
I only just downloaded Docker CE and have successfully logged in.
- Ubuntu 16.04
- Kitematic (alpha)

This goes for any and all images that I try to pull.

### Steps to reproduce the behavior
  1. Download Docker
  2. Login via Kitematic (alpha) with Docker Hub credentials
  3. Pull image ("hello-world (official)" for example)
  4. Error

### Additional notes
Say I were to attempt to pull the official "hello-world" image via Kitematic. I would receive this code 500 error. However, if I were to execute `docker run hello-world`, I can pull and execute the image without error.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
