### ISSUE TITLE
Adding same TCP and UDP ports

### ISSUE THREAD

**Issue by ssi-praveen-marothu** [docker/kitematic#3200]
### Expected behavior
Add TCP and UDP ports with the same port number.

### Actual behavior
It allows either TCP or UDP port when we use the same port number.

### Steps to reproduce the behavior

  1. Go to the Hostname/Ports view in kitematic
  2. Add TCP port with a port number
  3. Add UDP port with the same port number
  4. the 2nd entry replaces the first.

**Comment by FrenchBen** [comment]
This issue already exists in moby/moby, and should be tracked there instead:
https://github.com/moby/moby/issues/4635
