### ISSUE TITLE
Not allowing to log in !!! 

### ISSUE THREAD

**Issue by algorithmor** [docker/kitematic#3201]
### Expected behavior
Should log me in

### Actual behavior
Gives error : unauthorised : incorrect username password

### Information about the Issue
Does not allow to login

### Steps to reproduce the behavior

  1. ... Try logging in with your credentials
  2. ... Verify that the credentials are indeed correct by directly logging to docker Hub

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
