### ISSUE TITLE
Download impossible

### ISSUE THREAD

**Issue by Kruemelmonsta** [docker/kitematic#3205]
1. choose and try to load a image
  2. getting error: (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:47734->[::1]:53: read: connection refused"};

**Comment by FrenchBen** [comment]
Can you do the same pull via the cli? `docker pull hello-world`?
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
