### ISSUE TITLE
kitematic cannot handle https://hub.docker.com/r/asmagin/jenkins-on-windowsservercore/

### ISSUE THREAD

**Issue by jeanpoelie** [docker/kitematic#3206]
### Expected behavior
To start installing the docker

### Actual behavior
Error:
image operating system "windows" cannot be used on this platform

### Information about the Issue
Seems that I cannot install image "jenkins-on-windowsservercore" with kitematic.

### Steps to reproduce the behavior

  1. download kitematic
  2. install https://hub.docker.com/r/asmagin/jenkins-on-windowsservercore/

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
