### ISSUE TITLE
Getting "latest not found error" when pulling

### ISSUE THREAD

**Issue by beveridj** [docker/kitematic#3212]
### Steps to reproduce the behavior

  1. execute the following command: docker run -d --shm-size 1GB --name oracle_database -p 1521:1521 -v /data bofm/docker-oracle12c

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/bofm/oracle12c/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
