### ISSUE TITLE
Cant download official MySQL image from docker hub (server error) 

### ISSUE THREAD

**Issue by wissamalwakeel** [docker/kitematic#3220]
### Expected behavior
Download and start the image
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:48682->[::1]:53: read: connection refused"}
### Information about the Issue
Using docker Kitematic to download and start the mysql image
### Steps to reproduce the behavior

  1. search for the mysql on kitematic-->All 
  2. Chose the official image from docker hub
  3. get the above error message

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.

**Comment by brennenhuang** [comment]
Do you solve that problem?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity from OP - Feel free to re-open if appropriate.
