### ISSUE TITLE
Cannot add any container to docker 

### ISSUE THREAD

**Issue by piomark** [docker/kitematic#3222]
### Expected behavior
The container should be initialized

### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/evolveum/midpoint/manifests/latest: unauthorized: incorrect username or password"}

### Information about the Issue
This issue happens on Win10, I'm not able to initialize any container. 
While using Kitematic if I add the container then kill and restart docker the container will be initialized.

### Steps to reproduce the behavior

  1. Execute pull cmd in shell / try to initialize container using Kitematic
  2. Error is shown

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
