### ISSUE TITLE
Can't connect to repos

### ISSUE THREAD

**Issue by katmel98** [docker/kitematic#3228]
### Expected behavior
After login, connect and download docker images

### Actual behavior
Always rejected because errors: (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/redis/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ... Login
  2. ...

**Comment by mhelmetag** [comment]
This seems like something that could happen if you reset your password after already being logged in... maybe try logging out and back in? Because if I log in and check My Repos, it works fine.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
