### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for netflixoss/eureka:latest not found"}

### ISSUE THREAD

**Issue by jefyian** [docker/kitematic#3241]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/netflixoss/eureka/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by mhelmetag** [comment]
@FrenchBen, maybe this is another case for error handling UX? Like whenever we get this response from Docker, we instead tell the user that there's no image for the specific tag and to try downloading a different tag or open an issue with the maintainer of the image?

**Comment by FrenchBen** [comment]
@mhelmetag Yes, it would be really good - Although there are times when the image has no tags at all, in which case no other tag can be selected. 
Happy to see some UX improvements on that front if you're up to it :)

**Comment by mhelmetag** [comment]
Possibly 😄 we'll see what I'm feeling some weekends.
