### ISSUE TITLE
Issue when try to create Sonarqube container

### ISSUE THREAD

**Issue by tiendoan246** [docker/kitematic#3242]
### Steps to reproduce the behavior

  1. Search sonarqube image on Tikematic
  2. Select sonarqube and click "create" to see the issue below:
"(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:54608->[::1]:53: read: connection refused"}
"

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
