### ISSUE TITLE
cannot download cassandra 

### ISSUE THREAD

**Issue by elinalin** [docker/kitematic#3244]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mhelmetag** [comment]
@elinalin , if the workaround in #2673 worked for you, can this issue be closed?

@FrenchBen , maybe an idea here is to catch and handle 401s from docker and basically just give the workaround provided in #2673 (to logout and log back in; also the removal of email logins should help here...)?

**Comment by FrenchBen** [comment]
@mhelmetag Most will have switched to the Hub login by now, no need to add the force logout IMHO. 
I'll cut a new release of Kitematic with your changes this week.

**Comment by mhelmetag** [comment]
@FrenchBen , awesome 👌
