### ISSUE TITLE
cannot download cassandra

### ISSUE THREAD

**Issue by elinalin** [docker/kitematic#3245]
cannot download cassandra 
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/library/cassandra/manifests/latest: unauthorized: incorrect username or password"}

**Comment by mhelmetag** [comment]
@elinalin , I think this is a duplicate of #3244 . Can you close this and add the extra info to the first issue (#3244)?

**Comment by FrenchBen** [comment]
Duplicate of #3244
