### ISSUE TITLE
I could not download any docker images.

### ISSUE THREAD

**Issue by enom2g** [docker/kitematic#3249]
### Expected behavior
download any docker images.

### Actual behavior
I faced to below message.
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/centos/mysql-57-centos7/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. I logined github.
  2. Kitematic application running.
  3. I found something docker images.
  4. Click downlaod.
  5. but I faced below message.
      (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/centos/mysql-57-centos7/manifests/latest: unauthorized: incorrect username or password"}

**Comment by mhelmetag** [comment]
Can you make sure you're on the newest version of Kitematic and try logging out and back in?

**Comment by Tolsi** [comment]
I got the same:

```
> docker pull anapsix/alpine-java
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/anapsix/alpine-java/manifests/latest: unauthorized: incorrect username or password
```

**Comment by enom2g** [comment]
Dear mhelmetag~

Thanks a lot~
It's working~

Jay.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
