### ISSUE TITLE
getting 500 error when pulling an image

### ISSUE THREAD

**Issue by mhamri** [docker/kitematic#3251]
### Expected behavior
be able to pull an image peacfully
### Actual behavior
giving 500 error 
### Information about the Issue
getting this error 
`(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:45965->[::1]:53: read: connection refused"}`

### Steps to reproduce the behavior
1- run this on PowerShell with admin privilege (or without) : `docker pull continuumio/anaconda3`

**Comment by FrenchBen** [comment]
Unable to replicate, can you provide details of your setup?

**Comment by mhamri** [comment]
look like it was a temporary issue from docker.io, i couldn't reproduce it again
