### ISSUE TITLE
HTTP CODE 500 SERVOR ERROR - JUPYTER NOTEBOOK

### ISSUE THREAD

**Issue by trafic3** [docker/kitematic#3252]
### Expected behavior

Running a machine learning algorithm on my localhost.

### Actual behavior

I get an HTTP code 500 servor error when trying to run this command : docker-compose.up

### Information about the Issue

https://github.com/searchVIU/Labs/blob/master/readme.md

### Steps to reproduce the behavior

After downloading : https://github.com/searchVIU/Labs/blob/master/readme.md :

bash-3.2$ cd Labs
bash-3.2$ docker-compose up
Building jupyter
Step 1/3 : FROM jupyter/tensorflow-notebook
ERROR: Service 'jupyter' failed to build: Get https://registry-1.docker.io/v2/jupyter/tensorflow-notebook/manifests/latest: unauthorized: incorrect username or password
bash-3.2$ 

I do not understand why it is not working.

Thank you 
Alice

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
