### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries for images "drupal"

### ISSUE THREAD

**Issue by chris-using** [docker/kitematic#3253]
I tried to pull drupal image but shows me that error message.

**Comment by FrenchBen** [comment]
Looking at the architecture list, it should be there:
https://hub.docker.com/_/drupal/

Can you provide the full output of `docker -D pull drupal`

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
