### ISSUE TITLE
incorrect username or password

### ISSUE THREAD

**Issue by carlose18** [docker/kitematic#3260]
this is what I do in the terminal:
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Pass12345!' -p 34203:1433 microsoft/mssql-server-linux:rc1

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/microsoft/mssql-server-windows-express/manifests/latest: unauthorized: incorrect username or password"}

what am I doing wrong?

**Comment by mhelmetag** [comment]
I don't think that's talking about the password for the container. I think that's a dockerhub saying your credentials are incorrect.

I would logout and log back in. Make sure to use your username and not your email. That sometimes makes things better.

**Comment by carlose18** [comment]
wtff man, this is, login with user no email. thx

**Comment by mhelmetag** [comment]
I tried this and got something different:
```
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Pass12345!' -p 34203:1433 microsoft/mssql-server-linux:rc1      [21:26:14]
Unable to find image 'microsoft/mssql-server-linux:rc1' locally
docker: Error response from daemon: manifest for microsoft/mssql-server-linux:rc1 not found.
See 'docker run --help'.
```

But I got it to work trying to pull `latest`:
```
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Pass12345!' -p 34203:1433 microsoft/mssql-server-linux:latest   [21:26:17]
Unable to find image 'microsoft/mssql-server-linux:latest' locally
latest: Pulling from microsoft/mssql-server-linux
```

Are you sure you tried logging out and back in?

Also maybe the `rc1` tag just isn't available?

**Comment by 1and1get2** [comment]
I'm getting the same error using kitematic

`(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/ubuntu-upstart/manifests/latest: unauthorized: incorrect username or password"}`

**Comment by Tu-Szu-Chi** [comment]
When I using **Kitematic** have the same problem
But I **Sign out** account on Kitematic, it's ok
I can download image non-error

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by mhelmetag** [comment]
I think that's more of a docker issue than a kitematic one...

The latest version of kitematic doesn't allow logins via email for this reason AFAIK.

**Comment by FrenchBen** [comment]
@drcjones @mhelmetag that's correct - the current Docker ID support can't support emails as it currently works and thus causing errors when an email-authenticated user tries to pull an image.

**Comment by dwilhel1** [comment]
@mhelmetag logging out and back in again has solved the issue for me.

**Comment by a1g0rithm** [comment]
I can confirm that using your username instead of email to log in fixes this.

**Comment by martinsnelson** [comment]
I reset the docker hub password, and entered with username.
It worked
