### ISSUE TITLE
Not able to login from terminal

### ISSUE THREAD

**Issue by abhaic** [docker/kitematic#3261]
### Expected behavior
docker login is showing login failed

### Actual behavior
docker login should allow me to login when correct credentials are used

### Information about the Issue
I am able to login on docker hub and kitematic but docker CLI is failing the login when same credentials are used

### Steps to reproduce the behavior
=> docker login
=> Entered username
=> Entered password
Error response from daemon: Get https://registry-1.docker.io/v2/library/centos/manifests/latest: unauthorized: incorrect username or password

**Comment by mhelmetag** [comment]
One tip is using your username and not your email to login.

Another would be to try resetting your password and logging out and back in.

Hopefully that'll fix it. That error just looks like you're using the wrong credentials.

**Comment by DeeprajPandey** [comment]
Same issue here. Can not login from CLI. Any updates/workarounds, anyone?

**Comment by DeeprajPandey** [comment]
I ran into the same issue. Using the username instead of the registered email works.

I think the issue can be closed now. :D

**Comment by ulrich** [comment]
Issue fixed, Kitematic can login to the hub now.

Thank you for your feedback.
