### ISSUE TITLE
Error a crear image kali-linux

### ISSUE THREAD

**Issue by brocoLee** [docker/kitematic#3263]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mhelmetag** [comment]
I was able to create the kali-linux container just fine.

Can you share what container you are pulling (for instance, I'm pulling from `kalilinux/kali-linux-docker:latest`)?

Also, can you share the error that you're getting when creating the container?

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
