### ISSUE TITLE
Is there a specific node/npm version we should be using while contributing?

### ISSUE THREAD

**Issue by mhelmetag** [docker/kitematic#3266]
Should we have an `.nvmrc` (or some other node version manager file) that makes development a bit more standard?

I tried using node 8 and kitematic got very sad.

This is all kind of part a larger conversation to update kitematic to a higher version of electron (and, in turn, node).

Thoughts?

**Comment by FrenchBen** [comment]
Travis has it pinned at `4.1.1`
https://github.com/docker/kitematic/blob/master/.travis.yml

**Comment by mhelmetag** [comment]
Sounds good 👌  should've realized that from the `travis.yml` and `package.json`.

Yeah... a fair bit. I've been researching electron-forge and surf (for a build pipeline). Lots of possibilities...
