### ISSUE TITLE
install paddle error

### ISSUE THREAD

**Issue by yhongm** [docker/kitematic#3270]
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/paddlepaddle/paddle/manifests/latest: Get https://auth.docker.io/token?account=yhongm&scope=repository%3Apaddlepaddle%2Fpaddle%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
