### ISSUE TITLE
Cant download image for offline use.

### ISSUE THREAD

**Issue by bakkone** [docker/kitematic#3272]
### Expected behavior

Download image

### Actual behavior
Error message:
image operating system "windows" cannot be used on this platform

### Information about the Issue

Trying to download an image for offline transfer to a windows server 2016 machine. But since the image wouldn't work on my Win7 docker toolkit machine, it refuses to download.

### Steps to reproduce the behavior

  1. Install docker toolkit
  2. try: docker pull microsoft/windowsservercore:latest

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
