### ISSUE TITLE
build ubuntu16.04 on windows 10 failed

### ISSUE THREAD

**Issue by sammi** [docker/kitematic#3277]
### Expected behavior
Get ubuntu:16.04 images

### Actual behavior
It complains:
"no matching manifest for windows/amd64 in the manifest list entries"

### Information about the Issue

Build image in windows 10

### Steps to reproduce the behavior

  1.  Dockerfile:
FROM ubuntu:16.04
  2. Build image and gets errr:
docker build -t myImage .

**Comment by FrenchBen** [comment]
ubuntu isn't a windows image, but a linux image.

If you're running Docker for Windows, you can switch to using windows/linux containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
