### ISSUE TITLE
Behind proxy connection issue

### ISSUE THREAD

**Issue by vmasule** [docker/kitematic#3279]
### Expected behavior
Should successfully download image
### Actual behavior
Connection error
### Information about the Issue
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

  1. ... Setup proxy for Kitematics
  2. ... try to download image

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
