### ISSUE TITLE
Latest release URL version inconsistency

### ISSUE THREAD

**Issue by detvdl** [docker/kitematic#3284]
### Expected behavior
Use consistent versioning in release urls.
### Actual behavior
Latest release no longers prefixes version with `v` in download url.
### Information about the Issue
The current Caskfile for kitematic depends on the url format
`https://github.com/docker/kitematic/releases/download/v#{version}/Kitematic-#{version}-Mac.zip`

The latest 0.17.2 release currently resides at the url https://github.com/docker/kitematic/releases/download/0.17.2/Kitematic-0.17.2-Mac.zip

### Steps to reproduce the behavior
Try to run `brew cask install kitematic` or updating your currently installed version. A 404 error should result from this.

**Comment by FrenchBen** [comment]
The cask file you mention isn't maintained by us. 
I've updated the tag on the release to "fix" it, but it's considered a 3rd party tool. 

Thanks for the issue.
