### ISSUE TITLE
(HTTP code 404) unexpected - manifest for quantconnect/lean:latest not found

### ISSUE THREAD

**Issue by genefyx** [docker/kitematic#3291]
### Expected behavior
Installs software
### Actual behavior
(HTTP code 404) unexpected - manifest for quantconnect/lean:latest not found
### Information about the Issue
Software appears correctly on source. Should work correctly

### Steps to reproduce the behavior

  1. ... type in quantconnect
  2. ... click create

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/quantconnect/lean/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
