### ISSUE TITLE
500 Error When trying to download a container.

### ISSUE THREAD

**Issue by jamiepeloquin** [docker/kitematic#3297]
### Expected behavior
Container begins to download.

### Actual behavior
500 Error, bad username/password:
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/amazonlinux/manifests/latest: unauthorized: incorrect username or password"}

### Information about the Issue
Successfully logged into Docker with credentials.

### Steps to reproduce the behavior

  1. Sign into Docker
  2. Launch Kitematic
  3. Search for "amazon linux" (my example, but also failed on Ubuntu official)
  4. Download the "official" container

**Comment by jamiepeloquin** [comment]
Okay - so, it appears that this is related to signing in with an email address rather than a Docker Hub username (even though the field states it supports either). Signing in with the username seems to work as expected.

**Comment by FrenchBen** [comment]
The fix: Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

That's correct - we issued a fix for this in the latest Kitematic release
