### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp 34.200.28.105:443: getsockopt:

### ISSUE THREAD

**Issue by himanshuroak** [docker/kitematic#3298]
Displaying the Error when starting the Kitematic (Alpha)
Means after Launch Kitematic.

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
