### ISSUE TITLE
Deployment workflow from Desktop to Server running Docker

### ISSUE THREAD

**Issue by chovy** [docker/kitematic#330]
Is it possible to deploy a docker from you mac app? That would be pretty cool as I have no idea how to do this manually.

**Comment by jeffdm** [comment]
Hi there! Thanks for the issue.

There isn't a way to deploy containers to servers via Kitematic (yet!, there's an issue tracked here: #231).

This seems to be similar to that issue, but with a spin on having a workflow from Laptop => Server so I'll keep this open :smiley:

**Comment by 08ski11s** [comment]
it would be great if kitematic GUI have the ability to install/create/deploy container to cloud servers, that would be awesome feature, everything would be automated from the GUI panel... 

is it possible to install kitematic into the cloud server? for installing/creating/deploying containers

**Comment by FrenchBen** [comment]
closing in favor of your other issue
