### ISSUE TITLE
Downloading official node (node:latest) fails

### ISSUE THREAD

**Issue by italianrich** [docker/kitematic#3308]
### Expected behavior
Clicking "Create" in Kitematic on the Node Official (node:latest) image, should download the image

### Actual behavior

This error:

no matching manifest for windows/amd64 in the manifest list entries

### Steps to reproduce the behavior

  1. ... Open kitematic
  2. ... search for node
3. on node:latest, official, click create
4. read error message

**Comment by FrenchBen** [comment]
`node:latest` is a linux container and thus will not work within windows containers. 

To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
