### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for instructure/canvas-lms:latest not found"}

### ISSUE THREAD

**Issue by hiepkhachbk** [docker/kitematic#3315]
When I try to create a container from the docker image.
The error is showing

<img width="1071" alt="screen shot 2017-11-16 at 6 43 05 pm" src="https://user-images.githubusercontent.com/1708428/32889590-0f6e6e8e-cafe-11e7-9c66-8f4d11625f1f.png">

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
