### ISSUE TITLE
http500 first run selenium/standalone-firefox 

### ISSUE THREAD

**Issue by andidii** [docker/kitematic#3317]
### Expected behavior
image selenium/standalone-firefox downloads
### Actual behavior
We're sorry, there seems to be an error
### Information about the Issue

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:53693->[::1]:53: read: connection refused"}

### Steps to reproduce the behavior
type in console docker run --rm -p 10044:4444 --name selenium-firefox  selenium/standalone-firefox

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
