### ISSUE TITLE
docker pull heroku/heroku attempting to fetch non-existent image

### ISSUE THREAD

**Issue by jcbennett3** [docker/kitematic#3318]
### Expected behavior
heroku:latest
### Actual behavior
latest not found
### Information about the Issue
This happens when I click the link to create from the provided folder.

### Steps to reproduce the behavior

  1. Search heroku-16 from Kitematic's explore mechanism
  2. Click first heroku link

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/heroku/heroku/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
