### ISSUE TITLE
Error Pulling Image Configuration: <link> i/o timeout

### ISSUE THREAD

**Issue by rollnlearn** [docker/kitematic#3321]
### Expected behavior
This was supposed to download scrapinghun/splash

### Actual behavior
It gave the following error instead:

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/81/819b6bfdaa2852cea581bb73cbb4676731957a457d64543b1c9bf997fc55d983/data?Expires=1511043383&Signature=WAd~q1lBHRmDsIrtPZbaMWLsxYGq-3TYFBV0PnNHFOxf63SbPKM8wAkgpHmyymnpuh08pkj6y56F9WH~91rR4NLVrQKQX8231vs9ePYmhlIKMWLBPebiTsBJCnKPbkLa0Ifh4LA1GLt77vrYPXVLHEBAO-LQ7kbE1XS2mxJRfp4_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 218.248.255.164:443: i/o timeout

I tried doing this by going to the command-line and by executing the following command: docker pull scrapinghub/splash and also by using the Kitematic. Both the methods gave the error shown above.

### Steps to reproduce the behavior

  1. Download and install Docker Toolbar from the official website which includes installation for Oracle VM as well. The version of Oracle VM that came long with it was 5.2.0
  2. I launched it using Docker Quickstart Terminal. After a few minutes the terminal was started.
  3. I tried the following commands: docker-machine ls , docker ps -a Everything was working fine.
  4. Then I tried to pull hello-world using the command: docker pull hello-world. It did not work. Neither for splash.

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by rollnlearn** [comment]
No, I am not behind any firewall or proxy
