### ISSUE TITLE
Not able to download Selenium- Hub

### ISSUE THREAD

**Issue by Sandytrp** [docker/kitematic#3324]
### Expected behavior
Selenium hub Image should be downloaded

### Actual behavior
Showing Error: "(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:46226->[::1]:53: read: connection refused"}"

### Information about the Issue
OS: Win10
Dockor Version 17.09.0-ce-win33 (13620)

Note: Even not able to pull images from PowerShell

### Steps to reproduce the behavior

  1. ... Open Kitematic
  2. ... Search "Selenium- hub"
  3. ... Download "Selenium- hub"

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
