### ISSUE TITLE
Not Able to Create Container through Docker Cli as well as Kinematic

### ISSUE THREAD

**Issue by makwanaparth94** [docker/kitematic#3325]
### Information about the Issue:
To Implement a Grid functionality, Download Docker with CLI and Kinematic.
Through CLI i add the command so it shows that " Unable to find Image"
and Using Kinematic UI click on create of Selenium hub but it generate :"We are sorry .There seems to be an error.
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}"

Help me out to resolve these Issues so I can create Selenium hub,node debug and node firefox container to Implement Grid Functionality.

Attaching the Screenshot for the same:
![docker_error](https://user-images.githubusercontent.com/28529639/33009506-1ef53ce6-cdfd-11e7-8d8a-af4b6b995fb1.jpg)
![kinematic_error](https://user-images.githubusercontent.com/28529639/33009543-43c8d4c4-cdfd-11e7-9b78-7fc69e712f33.jpg)

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
