### ISSUE TITLE
Another PC can not access the server of any Container server for 192.168.99.100:xxxx

### ISSUE THREAD

**Issue by fishasen** [docker/kitematic#3327]
### Expected behavior
Container can  served-out for  LAN
### Actual behavior
no connection with container for other device
### Information about the Issue
I just try change the Network to Host network for resolve this problem，but the container  has an error，
and i can not access the Jenkins for 192.168.10.193:8080（host ip） in host Machine

![image](https://user-images.githubusercontent.com/17735370/33053513-e4ab9a96-ceae-11e7-876b-737a053ef090.png)

**Comment by FrenchBen** [comment]
`192.168.99.100` isn't exposed to the network - You would need to forward requests coming to your machine to the VM running inside of it.
