### ISSUE TITLE
HTTP 500 Server Error

### ISSUE THREAD

**Issue by saigop** [docker/kitematic#3329]
### Expected behavior
Supposed to install jenkins docker image

### Actual behavior
Got error in Kitematic "(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: unauthorized: incorrect username or password"}"

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
