### ISSUE TITLE
Container does not create - Error shown

### ISSUE THREAD

**Issue by MrD2** [docker/kitematic#3332]
### Expected behavior
Docker image starts execution

### Actual behavior
Error is shown nothing happens. On cmd it blocks indefinetly

### Information about the Issue
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:43651->[::1]:53: read: connection refused"}

### Steps to reproduce the behavior

1. download image
2. run
docker run centos:7 bash

Same happens using Kitematic on windows if i try to create new container with other image, ubuntu 4ex

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
