### ISSUE TITLE
The container's status always keep (health: starting) and the CPU greater than 100% instantly, the container restart every 10 seconds

### ISSUE THREAD

**Issue by xuejun123** [docker/kitematic#3344]
### Information about the Issue
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

 below is the log

![wechatimg1](https://user-images.githubusercontent.com/33950358/33199326-caacb318-d12a-11e7-93e6-2c40af50eb27.jpeg)
Error executing action `create` on resource 'directory[/etc/gitlab]'
![wechatimg2](https://user-images.githubusercontent.com/33950358/33199331-d112a2f8-d12a-11e7-802d-d8e6f400eba5.jpeg)
Recipe Compile Error in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/default.rb

### Steps to reproduce the behavior

  1. sudo docker run --detach \
    --hostname gitlab.tkground.internal \
    --publish 5443:5443 --publish 5080:80 --publish 522:22 \
    --name gitlab \
    --restart always \
    --volume /srv/gitlab/config:/etc/gitlab \
    --volume /srv/gitlab/logs:/var/log/gitlab \
    --volume /srv/gitlab/data:/var/opt/gitlab \
    gitlab/gitlab-ce:latest

  CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
fa21fd85e95e        100.36%             52.31MiB / 1.952GiB   2.62%               624B / 96B          0B / 45.1kB         10

**Comment by FrenchBen** [comment]
Unfortunately this forum is dedicated to Kitematic issues only and not setup/container issues. 
Since this seems independent of Kitematic, feel free to open an issue in: https://github.com/moby/moby
