### ISSUE TITLE
Kitematic's download feature seems broken (Mac High Sierra)

### ISSUE THREAD

**Issue by majamee** [docker/kitematic#3346]
### Expected behavior
Kitematic should download the docker image from Docker Hub (in this example https://hub.docker.com/r/base/archlinux/)

### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:37442->10.0.2.3:53: i/o timeout"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Can you do this via the CLI?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (108/100 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:56426)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eMLFi-0014wC-H9
	for greg@biomassiv.es; Tue, 05 Dec 2017 15:59:46 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=nbWwjTynR9ge9j1fYvFXJnhV37Y=; b=dxDhZz7Z+pMFWWgy
	voinAiMwZAHGQehN2gb5i87wDaTwIowkRDAD/EouLs4lCU8rmypnfrVeiRngTWZI
	R8A24HSdyrVYiajBgPeTgHJJvqm4hYF29OCg59hP/jRE79f42t6ulbw5z5qz6VRo
	V2zdV3F3Wox3c+rzJ0KxNE5mC4M=
Received: by filter0190p1las1.sendgrid.net with SMTP id filter0190p1las1-14206-5A2716AA-34
        2017-12-05 21:59:06.663336574 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id DD9PZAsYScizDUDp8kmpyA
	for <greg@biomassiv.es>; Tue, 05 Dec 2017 21:59:06.387 +0000 (UTC)
Date: Tue, 05 Dec 2017 21:59:06 +0000 (UTC)

**Comment by jcwright77** [comment]
same issue under windows 10 docker toolbox both in kinematic and in cli under docker quickstart
docker tries to access https://registry-1.docker.io/v2/ which generates an unathorized message in a json response. curiously , the registry listed by docker info is  https://index.docker.io/v1/ which differs in api version and hostname. Perhaps somewhere the /v2/ endpoint has been introduced?

**Comment by FrenchBen** [comment]
@jcwright77 did you login using your Docker ID? If you've used email, then it'll not work. 
Additionally the above errors was due to an incorrect config around vpn. Please open a new issue if you have problems with it, after looking at the wiki tips.

**Comment by jcwright77** [comment]
@FrenchBen I logged in with my Docker ID not my email. This issue in my case seems to stem from an incorrect initial configuration in docker toolbox.  Redoing the configuration from docker-machine as I reported in #3653 . This is still a bug in that in does not happen with docker for the mac and probably should be fixed.

**Comment by FrenchBen** [comment]
It looks like this is a machine/virtualbox issue, as this is where the provisioning happens; not at the Kitematic level.
