### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password"}

### ISSUE THREAD

**Issue by nasrullo** [docker/kitematic#3347]
### Steps to reproduce the behavior

  1. docker pull busybox
  (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password"}

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:40887 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1eMLDW-0013bi-5D
	for greg@biomassiv.es; Tue, 05 Dec 2017 15:57:30 -0600
Date: Tue, 05 Dec 2017 13:56:50 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1512511010;
	bh=TBd4yccvK+JrP0ceLVzdBzTSr/t1RBv9+xo4AZ+oeOE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Tz9oBwurcdgel61ICdUibWSgh/mTf1Gtyawj+9UeP+TLH+7zSb8LwjAXiW4FpgEQl
	 p+sFyybFKXK1FD4scRLMmvttDzB/+rEo+BnQsdnsa+dreAuxHZMksLDaCNZ4fUbe1q
	 fNblae16Nd+AiZdVTaIDb2dPE2O70sQSkiIs8xyM=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:48921)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eMLDX-0013ck-6f
	for greg@biomassiv.es; Tue, 05 Dec 2017 15:57:31 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=jQUdiG3iWa1pLNKEXiH3hKcnI8o=; b=UukFFVZk3Th5IFA8
	N2fDsu/RAHbKpL4t50P9dcxGwHaz4MGNDrJeEMnh5d3/Ho8uMOKFzA7I8oIKx+RK
	J+aUQDpOXdKOfqbNaAQRnlB0eVzuLmKeo9mp6E6ftitqO7iQDQBhPVEasbq03Tj0
	4uDi19jtZluHnato5mX54cZZomc=
Received: by filter0627p1mdw1.sendgrid.net with SMTP id filter0627p1mdw1-5620-5A271623-1E
        2017-12-05 21:56:51.651755654 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0023p1iad2.sendgrid.net (SG) with ESMTP id 3tn1wBJ2Sdi7MPkesB0X8A
	for <greg@biomassiv.es>; Tue, 05 Dec 2017 21:56:51.638 +0000 (UTC)
Date: Tue, 05 Dec 2017 21:56:51 +0000 (UTC)
