### ISSUE TITLE
I get Invalid password using a valid hub.docker password 

### ISSUE THREAD

**Issue by mauriciovander** [docker/kitematic#3354]
### Expected behavior
I should be able to pull images from docker hub. 

### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/nginx/manifests/latest: unauthorized: incorrect username or password"}

### Information about the Issue
My usual docker hub account stopped working.

### Steps to reproduce the behavior
  1. Successfully login to Kitematic
  2. try to pull Nginx Image

Also: 
docker login fails with correct password
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

**Comment by mhelmetag** [comment]
I would try logging out, grabbing the latest version of kitematic, and then logging back in. That should help!

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
