### ISSUE TITLE
Error - Create container

### ISSUE THREAD

**Issue by arielmesquitaa** [docker/kitematic#3355]
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Information about the Issue
![image](https://user-images.githubusercontent.com/23404392/33242285-816e2eee-d2b9-11e7-8b31-7c4beb0e2ba6.png)

### Steps to reproduce the behavior

  1. open kitematic
  2. select container
  3. create

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:60789)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eMLDA-0013PP-8y
	for greg@biomassiv.es; Tue, 05 Dec 2017 15:57:08 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=U8+CpuBihf+Q7b5zsnWmTXc70gQ=; b=DY7asa492DZ9EnnB
	++eLPD+vjw8h9pPUfGDNTNv8/h77J3uoQsWxvaYWE5C8j/L0WXuHLoqLu/FhATDq
	CAUZtWQLTFygaDpXg8Pe5smhtQxN+B4DeKuo0Isw/FO2LAmKWE4rbr6S23ICACrY
	EgW2WKuHtacF3v3Xgdg+CGv6KdQ=
Received: by filter0014p1las1.sendgrid.net with SMTP id filter0014p1las1-30450-5A27160C-13
        2017-12-05 21:56:28.640547756 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id TldBoKjWTYitcpjTUPsJ_w
	for <greg@biomassiv.es>; Tue, 05 Dec 2017 21:56:28.396 +0000 (UTC)
Date: Tue, 05 Dec 2017 21:56:28 +0000 (UTC)
