### ISSUE TITLE
Wrong message when company policy limits file size to download

### ISSUE THREAD

**Issue by hpham04** [docker/kitematic#3360]
### Expected behavior
Display appropriate error message
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/cuongdd1/citus-iot-device-simulator/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
