### ISSUE TITLE
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\ccd944f93ded6e0e4e0c07d997cf052cf2657ac0506375d8607c0c09e15a5c8f\UtilityVM: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by dkrusia** [docker/kitematic#3366]
### Expected behavior
It should have pulled window/nanoserver
### Actual behavior
came up with the above error
### Information about the Issue
 Using a computer with windows 10 Enterprise installed, switch to Windows Container mode and try to pull the above image.  I tried it with Symantec Endpoint  disabled and stopping all the related processes.  I tried with Kitematic and directly from power shell and command prompts.  In all cases, the end result was the above error.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Can you try to pull it without Kitematic?

**Comment by dkrusia** [comment]
No. First I tried without Kitematic and tried all sorts of thing.  Finally, I thought Kitematic might help.  However, it was giving the same error messages.

**Comment by dkrusia** [comment]
Interesting enough, when I go to aws  ec2 with container for windows server 2016, they use much older version of docker for windows. It is 1.xxx.

**Comment by FrenchBen** [comment]
Kitematic will unfortunately magically resolve any issues. It's simply a GUI for common CLI commands.
You can open an issue here: https://github.com/docker/for-win

**Comment by dkrusia** [comment]
Why did you close this?  Did  you find a fix?

**Comment by dkrusia** [comment]
I got it.
