### ISSUE TITLE
Docker for Netscaler CPX not working

### ISSUE THREAD

**Issue by omahrez** [docker/kitematic#3371]
### Actual behavior
404 not found
### Information about the Issue
the link to the image does not work
HTTP code is 404 which indicates error: undefined - {"message":"manifest for mmx170067/cpx:latest not found"}

### Steps to reproduce the behavior

pull image

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/mmx170067/cpx/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
