### ISSUE TITLE
(HTTP code 404) no such image - no such image: local-library/wordpress:latest: No such image: local-library/wordpress:latest

### ISSUE THREAD

**Issue by shafkatalam** [docker/kitematic#3372]
### Steps to reproduce the behavior

  1. ...
(HTTP code 404) no such image - no such image: local-library/wordpress:latest: No such image: local-library/wordpress:latest

  2. ...

**Comment by mhelmetag** [comment]
@shafkatalam , are you on the latest version of kitematic? This issue should be fixed in the latest version.

**Comment by FrenchBen** [comment]
Please upgrade to the latest release as proposed by @mhelmetag
