### ISSUE TITLE
500 error creating new containers

### ISSUE THREAD

**Issue by cparadigm** [docker/kitematic#3373]
### Expected behavior
Getting the container
### Actual behavior
Error message
### Information about the Issue
Every time I create a new container I'm getting an error message

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/node/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. Find a container to create
  2. Create it.

**Comment by mhelmetag** [comment]
Try downloading the latest version and logging out and back in. That should solve things.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
