### ISSUE TITLE
Manifest not found on pull

### ISSUE THREAD

**Issue by code4tips** [docker/kitematic#3376]
## Expected behavior
Pushed a new repo. Then tried to pull it with docker pull dockerxo/nano-iis-php-mysql
expected the image to be pulled. 

### Actual behavior
Error message: Error response from daemon: manifest for dockerxo/nano-iis-php-mysql:latest not found

### Information about the Issue
I also tried it with Kitematic. Same result.

### Steps to reproduce the behavior
  1. C:\dockerz\nano-mysql>docker push dockerxo/nano-iis-php-mysql
The push refers to a repository [docker.io/dockerxo/nano-iis-php-mysql]
e07e2d4d8599: Pushed
65cc52d2ad1b: Pushed
7ace42a90c35: Mounted from nanoserver/iis-php
3c7479060f31: Mounted from nanoserver/iis-php
67f92755d5a5: Skipped foreign layer
6c357baed9f5: Skipped foreign layer
v1: digest: sha256:a98c496535f5b6e605219131e4f47843e7a882c62b64a4e1ff8b5f33b77c75e5 size: 1791

  2. pull dockerxo/nano-iis-php-mysql

![image](https://user-images.githubusercontent.com/34147729/33465190-59680e84-d614-11e7-9b15-1f5910fea98f.png)

**Comment by mhelmetag** [comment]
I think you have to tag the pushed image as latest. Kitematic pulls the image tagged `latest`. If it doesn't, you'll get this error.

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/dockerxo/nano-iis-php-mysql/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
