### ISSUE TITLE
I/O Timeout

### ISSUE THREAD

**Issue by armelraja** [docker/kitematic#3378]
### Information about the Issue

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/a6/a61a91cc0d1bafe6f88612278c24c68ffec215379066bd9efe8199fc350666e0/data?Expires=1512223653&Signature=dWuklbZMEvCoHwfw-ql6CU4VjVw3iW7aUeML-j85umLgiEWrdVhAcGGZgbBsay~sgG5y-pPUHOpgAnWMy1EKS3ljs-l1sV9Lv2y~DrSKxpmg09jt8oyP6tqCRD-jl6nU-Po8Bhv8PkCyg~~Hc-EZHGexXA46rTY5TaO9OS5wP3w_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 218.248.255.164:443: i/o timeout
### Steps to reproduce the behavior

  1. ...tensorflow
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
