### ISSUE TITLE
Got--HTTP code 500

### ISSUE THREAD

**Issue by kevinedison** [docker/kitematic#3380]
### Expected behavior
  open the docker from Kitematic.
### Actual behavior
   Got the "HTTP code 500" and can't create the docker.

### Information about the Issue
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: Bad Request"}

### Steps to reproduce the behavior

  1.  open Kitematic client;
  2. search docker img with type mysql at top bar.
  3. click the Create link for any recommended docker.

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by kevinedison** [comment]
Thanks,
It works while change to [Using system proxy] while [Manual proxy configuration] is empty.
