### ISSUE TITLE
there is no option to delete image

### ISSUE THREAD

**Issue by malikasinger1** [docker/kitematic#3381]
why there is no option to delete images? I'm using the latest version just installed

**Comment by malikasinger1** [comment]
Just installed doesn't mean that I'm new, I'm using it from more then one month

**Comment by si458** [comment]
1. Click NEW (left hand side near top)
2. Click My Images (right hand side near top)
3. Click the 3 dots next to the image you want to remove
4. Click 'Delete Tag' (wont be able to click this unless all containers using that image have been removed)
👍

**Comment by FrenchBen** [comment]
Closing as @si458 provided the steps to do so.
