### ISSUE TITLE
(HTTP code 500) server error 

### ISSUE THREAD

**Issue by mramosArg** [docker/kitematic#3384]
I get the error below at Download using Kitematic

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/postgres/manifests/latest: unauthorized: incorrect username or password"}

**Comment by proteck** [comment]
Same error !

**Comment by proteck** [comment]
For me it was a timeout exceeded exception, with the same HTTP code.

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
