### ISSUE TITLE
Unable to run Hello-world-nginx on Kitematic

### ISSUE THREAD

**Issue by eosai01** [docker/kitematic#3387]
### Expected behavior
Successful run Hello-world-nginx
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. ..Happens when i try to run the container

  2. ...

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
