### ISSUE TITLE
fix discourse

### ISSUE THREAD

**Issue by Sceko** [docker/kitematic#3389]
(HTTP code 404) unexpected - {"message":"manifest for discourse/base:latest not found"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/discourse/base/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
