### ISSUE TITLE
error in Kitematic

### ISSUE THREAD

**Issue by waleezhammad** [docker/kitematic#3390]
### Actual behavior
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\docker\windowsfilter\097a736b319880d8222309d560e86b010d203dc376164b9be7be8402b80d31c4: The system cannot find the path specified.
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please repeat the process via the CLI - if that fails, then open an issue in the appropriate GIthub repo: https://github.com/docker/for-win
