### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for hyperledger/fabric-peer:latest not found"}

### ISSUE THREAD

**Issue by okuye** [docker/kitematic#3391]
### Expected behavior

Create the fabric-peer

### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for hyperledger/fabric-peer:latest not found"}

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/hyperledger/fabric-peer/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
