### ISSUE TITLE
Missing version info in Kitematic for Debian

### ISSUE THREAD

**Issue by gitowiec** [docker/kitematic#3392]
### Expected behavior
Easly check Kitematic version.

### Actual behavior
There is no menu or `--version` or `-v` option to check what Kitematic version user have installed on his machine.

### Information about the Issue
I tried to run Kitematic by command line interface via `kitematic --version` and I couldn't get version printed out. I tried to find any menu in Kitematic app and besides the configuration screen I can't find anything

### Steps to reproduce the behavior

  1. Install Kitematic on Debian 9
  2. Try to get its version

**Comment by FrenchBen** [comment]
What am I missing here? 
```
~$ docker run --rm -it debian:latest bash
# apt-get update && apt-get install curl zip
# curl -sSLO https://github.com/docker/kitematic/releases/download/v0.17.3/Kitematic-0.17.3-Ubuntu.zip
# unzip Kitematic-0.17.3-Ubuntu.zip && cd dist
# dpkg --info Kitematic_0.17.3_amd64.deb
 new debian package, version 2.0.
 size 45139498 bytes: control archive=533 bytes.
     598 bytes,    13 lines      control
 Package: kitematic
 Version: 0.17.3-1
 Section: devel
 Priority: optional
 Architecture: amd64
 Depends: git, gconf2, gconf-service, gvfs-bin, libc6, libcap2, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libnotify4, libnss3, libxtst6, python, xdg-utils
 Recommends: lsb-release
 Suggests: gir1.2-gnomekeyring-1.0, libgnome-keyring0
 Installed-Size: 171855
 Maintainer: Ben French <frenchben@docker.com>
 Homepage: https://kitematic.com/
 Description: Simple Docker Container management for Mac OS X, Windows and Ubuntu.
  Run containers through a simple, yet powerful graphical user interface.
```
Version is clearly shown as `0.17.3-1`
Using a container to proof this - as of this writing, `debian:latest` is Debian 9.2

**Comment by gitowiec** [comment]
You are not checking the version of installed application, you are printing info about installation package, and I wasn't asking for that.

**Comment by FrenchBen** [comment]
```
# dpkg -i Kitematic_0.17.3_amd64.deb
# dpkg-query -l | grep kitematic
iU  kitematic                 0.17.3-1                       amd64        Simple Docker Container management for Mac OS X, Windows and Ubuntu.
```

**Comment by gitowiec** [comment]
That's nice, thanks.
