### ISSUE TITLE
Windows: Don't Display Option to Use VirtualBox

### ISSUE THREAD

**Issue by mrgrew** [docker/kitematic#3405]
### Expected behavior

On WIndows I shouldn't see a "Use VirtualBox instead of Native on next restart" checkbox if VirtualBox isn't supported.

### Actual behavior

I clicked that checkbox, restarted, and Kitematic wouldn't start.

### Information about the Issue

I used information at https://github.com/docker/kitematic/issues/2499 to resolve the issue.

### Steps to reproduce the behavior

  1. Install Docker on Windows
  2. Install Kitematic
  3. Open Kitematic settings
  4. Click the "Use VirtualBox instead of Native on next restart" checkbox
  5. Restart
  6. Attempts to open Kitematic won't succeed and neither reset nor retry setup allows for recovery

**Comment by FrenchBen** [comment]
Virtualbox was the first supported tool and thus shall remain part of the options. Clicking it assumes you have Virtualbox installed. 
If you obtained Kitematic through a different release than bundled with Virtualbox, then this option shouldn't appear, unless the native setup is broken.
