### ISSUE TITLE
image operating system "windows" cannot be used on this platform (on a Mac)

### ISSUE THREAD

**Issue by ovidiu8** [docker/kitematic#3410]
Hello,
I just tried to install the win10build container and the error is this from the title
Any ideas?
I have Kitematic on a Mac

**Comment by collin5** [comment]
@ovidiu8 I don't think this is a kitematic specific issue. Try checking out [this](https://forums.docker.com/t/how-do-i-start-a-windows-docker-container-on-my-mac-os-x/12953) thread.
