### ISSUE TITLE
pull is causes error 

### ISSUE THREAD

**Issue by wissamalwakeel** [docker/kitematic#3411]
### Expected behavior
hello-world-nginx container starts properly 

### Actual behavior
error during the pull operation of the container 

### Information about the Issue
failed to register layer: failed to start service utility VM (applydiff 954f1a36977b5a715c85cfd830bc51be095e39075f2cc5f5416af6b28d567a08): container 954f1a36977b5a715c85cfd830bc51be095e39075f2cc5f5416af6b28d567a08_svm encountered an error during CreateContainer: failure in a Windows system call: winapi error #3228369022 (0xc06d007e) extra info: {"SystemType":"container","Name":"954f1a36977b5a715c85cfd830bc51be095e39075f2cc5f5416af6b28d567a08_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}

### Steps to reproduce the behavior
on a windows 10 Enterprise x64 machine
Windows version 1709
OS build 16299.98  
  1. start Windows PowerShell as Administrator
  2. execute the following command "docker pull kitematic/hello-world-nginx"

**Comment by FrenchBen** [comment]
If this is an issue with Docker for Windows, I would encourage you to open an issue in https://github.com/docker/for-win
