### ISSUE TITLE
Long log lines lead to inaccessible kitematic interface

### ISSUE THREAD

**Issue by sgrossberndt** [docker/kitematic#3412]
### Expected behavior
When the log lines in the container are very long on Kitematic 0.17.3 on Ubuntu the tabs "Home" and "Settings" are accessible.

### Actual behavior
Long log lines lead to the "Home" and "Settings" tab being pushed so far to the right that they are no longer accessible by the user.

![bildschirmfoto vom 2017-12-14 18-03-34](https://user-images.githubusercontent.com/3786510/34005004-da3dd83c-e0f9-11e7-9efc-299da9487c00.png)

**Comment by FrenchBen** [comment]
Can you provide some container image that would replicate this? I can't seem to make it happen on OSX

**Comment by jmgfr** [comment]
Hi,
I have this issue with many container, 
I need two screen and maximize window for acces home and setiings Tab on the second screen

Containers : 
-openkm/openkm
-obviouscap/openkm
-eclipse/che-server
etc ...

Thanks

**Comment by FrenchBen** [comment]
thanks @jmgfr for the images - Do you have anything like this that is smaller than 100mb? Some of the above are 1gb

**Comment by jmgfr** [comment]
Hi, 
Thanks for your reply.
I've tested some af smaller container images but none of them replicate this !
Is thre a way to run kitematic in verbose or debug mode and send you a log or a trace ?

Thanks
![kitematic](https://user-images.githubusercontent.com/13685004/39066855-dc1b37da-44d6-11e8-876b-44d4f8ef04cc.gif)

**Comment by FrenchBen** [comment]
What version are you running? I'm unable to reproduce this in 0.17.2
_added a max-width thinking that was needed_
![fix](https://user-images.githubusercontent.com/3965324/39071624-c0a673dc-44b5-11e8-9cad-700ddd93b965.png)
_without any fix at all it looks the same_
![no-fix](https://user-images.githubusercontent.com/3965324/39071617-bb482f98-44b5-11e8-9370-0144b52687a9.png)

**Comment by jmgfr** [comment]
I'm using 0.17.3 downloaded from this github and installed via dkpg without any error.
My ubuntu is 14.04.5 LTS
Thanks

**Comment by sgrossberndt** [comment]
I have this issue with https://hub.docker.com/r/elmarhinz/typo3.docker-development/ (as I wrote using Kitematic 0.17.3 on Ubuntu 17.10)

**Comment by FrenchBen** [comment]
Didn't realize this was an ubuntu specific issue... can someone look at setting a max-width on content, if it helps?

**Comment by sgrossberndt** [comment]
How to do that?

**Comment by sgrossberndt** [comment]
Sorry, I don't get it. How do Chrome Developer Tools come into play with a binary installed from a *.deb file? I did find `/usr/share/kitematic/resources/app/main.css` and adding

```
.details-panel.home .content {
  max-width: 900px;
}
```

makes at least the settings tab available for me even if there are long log lines.

![content_wrapped_at_900px](https://user-images.githubusercontent.com/3786510/39243889-38e5aebc-488f-11e8-80a4-c053012f7dc9.png)

By adding

```
.details-panel.home .content .mini-logs .widget .logs {
  max-width: 600px;
}
```

I can additionally wrap the actual log lines so the web preview box is visible: 

![logs_wrapped_to_600px](https://user-images.githubusercontent.com/3786510/39243890-390bebea-488f-11e8-821f-0e116d5d0453.png)

**Comment by FrenchBen** [comment]
The same shortcut use on Chrome, can be used in Kitematic (we use electron).
Can you try `max-width: 100%` ?

**Comment by sgrossberndt** [comment]
In Chromium I use `Ctrl+Shift+I` but when using that in kitematic nothing happens. Tested some combinations now `Ctrl+Alt+I` is it.. :-)

Using `max-width: 100% ` on these both elements has no effect :-(

**Comment by FrenchBen** [comment]
ctrl+shift+i works for me - if you can figure out the max-width that works well, it would be helpful, since I don't have the proper env

**Comment by sgrossberndt** [comment]
It works for me with two additional definitions
```
.details {
    width: 75%;
}
.details-panel.home .content .left {
    width: 60%;
}
```
which is not perfect for small window sizes but much better as all ui elements are accessible

**Comment by FrenchBen** [comment]
Thanks for the help debugging this @sgrossberndt, and getting a PR submitted 👍
