### ISSUE TITLE
How to run Kitematic on Mac with proxy?

### ISSUE THREAD

**Issue by odg0318** [docker/kitematic#3416]
I am running docker under corporate firewall.
As a result, tls certification failed when I tried to login dockerhub.
It seems that below package is internally used to make a http request.
https://www.npmjs.com/package/request#tlsssl-protocol

I think there are two way to workaround; proxy or tls config.
The former has an advantage not to change code.
But I don't know how to set proxy settings to kitematic.

Please let me know how to do that.

Best regards.

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by odg0318** [comment]
@FrenchBen  I asked how to use proxy on mac.
When I did following the document you mentioned, it doesn't work well.
Can you let me know how to use proxy on mac?

Thanks in advance.

**Comment by FrenchBen** [comment]
proxy on mac is a feature that is often requested as part of the docker toolbox and why I forwarded you there. 
It's impossible for me to know your setup, unless you share it.
For the desktop product called Docker for Mac, please see the information here: https://docs.docker.com/docker-for-mac/networking/

**Comment by odg0318** [comment]
@FrenchBen 
My company firewall uses its own certificate to monitor network traffic.
It needs to install self-signed certificate on my mac.
But it seems like that kitematic doesn't use the certificate installed on mac to execute https request  such as login to docker hub.

On my mac, I set HTTP(S)_PROXY and checked whether docker hub login is available or not using chrome. And it is available. In the same environment, I run kitematic and tried to login but it showed x509 certificate problem.

I checked a source, https://github.com/docker/kitematic/blob/master/src/utils/HubUtil.js#L150,  about login to dockerhub; 
I tested `curl -XPOST https://hub.docker.com/v2/users/login/` on my terminal with(out) web proxy and cerificate verification is passed, which means a http settings(firewall) is right.

As I said, `npm request` package is used to make a http request.
There is no code about certificate settings in kitematic.
Look at the following link. https://www.npmjs.com/package/request#tlsssl-protocol

Could you tell me how to properly run kitematic with http proxy or skip to check certificate?
