### ISSUE TITLE
53/tcp & 53/udp ports

### ISSUE THREAD

**Issue by Homas** [docker/kitematic#3420]
### Expected behavior
Kitematic should allow adding the same ports but different protocols.
Kitematic should allow adding port 53/tcp.
### Actual behavior
1. Kitematic does not allow adding the same port for tcp and udp. Second port with a different protocol is automatically removed.
2. Kinematic does not allow to add 53/tcp at all. It changes it to udp.
### Information about the Issue
Kinematic 0.17.0 on Mac OS with native support.
[Here](https://github.com/docker/kitematic/issues/344#issuecomment-338381610) is reported the same issue.
### Steps to reproduce the behavior
  1. Add a container
  2. Specify port mapping 53/tcp and save
  3. Go to Home and return back to port config. 53/tcp - changed to udp
  4. Add a second port 53/tcp. Try to save - it disappears. You can try any other ports. But you should specify the same number but different protocols.

**Comment by FrenchBen** [comment]
This is actually a limitation of Docker not Kitematic:
https://github.com/moby/moby/issues/4635
