### ISSUE TITLE
Error after downloading a container

### ISSUE THREAD

**Issue by lorenzoperone** [docker/kitematic#3421]
### Expected behavior
Install and run a container

### Actual behavior
Error after downloading

### Information about the Issue
The error shown is "failed to register a layer: error procession tar file (exit status: 1) write /usr/bin/node: no space left on device

### Steps to reproduce the behavior

  1. Try do run this container: https://hub.docker.com/r/jeroenjanssens/data-science-at-the-command-line/
  2. After downloading the error is shown

My Mac is MacBook Pro (13 inch, Mid 2009) my OS 10.11.6, in past I was able to use Kinematic without problem.

**Comment by lorenzoperone** [comment]
[Here](https://www.dropbox.com/s/iadsk0oipgafbil/Schermata%202017-12-17%20alle%2017.59.20.png?dl=0) is a screenshot

**Comment by FrenchBen** [comment]
Is this on Docker for Mac or using Toolbox?
Both have limitations in size - Toolbox creates a default VM of 20gb, which is pretty quick to fill up. 
You can always create a new VM with more room, by following the wiki instructions:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space

Docker for Mac faq is here: https://docs.docker.com/docker-for-mac/faqs/
