### ISSUE TITLE
Windows Installers

### ISSUE THREAD

**Issue by deinok** [docker/kitematic#3429]
Releases of windows could be in the form of *.msi and *.appx packages.

I think that https://github.com/electron-userland/electron-builder can do this for you ;)

**Comment by deinok** [comment]
Yeah, sure. The only condition for *.appx is that we are going to need to enable appveyor. Appx packages can only be built in W10.

Also i think that this way to releasing packages can also benefit linux and mac. (We can also make other package types).

Could you give me more information about how is Kitematic build and other relevant information?

**Comment by FrenchBen** [comment]
Enabling AppVeyor wouldn't be too bad. Let me know what it takes and we'll see how to make it happen!

**Comment by deinok** [comment]
Perfect, can you say me the system dependencies in order to build the electron app?
I supose that in order to build everything i should run `npm install` and `npm run release`

- **Linux:** Node, NPM
- **Mac:** Node, NPM
- **Windows:** Node, NPM

**Comment by FrenchBen** [comment]
There's also a `Makefile` that allows you to do a simple:
`make run`  or `make release`

**Comment by deinok** [comment]
@FrenchBen Hey, im testing some things and seems like i found one strange thing.
Using this SC https://github.com/deinok/kitematic/tree/electron-build
- `npm install`
- `npm release`
Try to execute `./dist/Kitematic-win32-x64/Kitematic.exe` -> Dont start properly. Is this normal?

It could be related something called app.asar?

**Comment by FrenchBen** [comment]
Not too familiar with Electron builder. Can you try to build from master first and confirm that works, then add the builder steps?

**Comment by deinok** [comment]
I tried it in other computer (master-windows) and do the same. Only a white screen is show.

**Comment by FrenchBen** [comment]
Any errors shown in the console?

**Comment by deinok** [comment]
In windows: npm release -> no stderr -> dist exe not working
In windows + electron-builder -> stderr related to .asar
In linux : npm release -> works well
In linux + electron-builder -> stderr related to .asar

You can check it in my fork:electron-build

**Comment by deinok** [comment]
@FrenchBen Well, seems finished (Tested on Windows)(Linux and Mac are left, but should be okey or only a bit of conf at electron-build.json).
Im facing some issues but master seems to have that same issues.

`npm install && npm run release:windows` will generate packages at `./dist/` (*.msi and *.appx)

**Comment by FrenchBen** [comment]
I should have a windows machine to test this after the holidays - I'll merge then.
Thanks again for the help!

**Comment by deinok** [comment]
Perfect
