### ISSUE TITLE
pull   hyperledger/fabric-membersrvc:latest   

### ISSUE THREAD

**Issue by Yangdaidai** [docker/kitematic#3434]
error pulling image configuration: Get https://acs-cn-hangzhou-mirror.oss-cn-hangzhou.aliyuncs.com/docker/registry/v2/blobs/sha256/b3/b3654d32e4f9be01f42f08a2677ad953ed34d6d714133463e386d3156a6ff6f9/data?Expires=1513831652&OSSAccessKeyId=R40Xc1Wa1rpLvQBA&Signature=d9G7f9q%2B6M9pcE3FNf4IWgo7gro%3D: dial tcp 116.62.99.45:443: getsockopt: connection refused

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/hyperledger/fabric-membersrvc/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by Yangdaidai** [comment]
Thank you, my network was not good at that time and I did not pull it down. After a while, it has now been successfully pulled down.

**Comment by Yangdaidai** [comment]
Thank you, my network was not very good, did not pull it down, then I have successfully pulled down.
