### ISSUE TITLE
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer 

### ISSUE THREAD

**Issue by ColinMillsSTG** [docker/kitematic#3437]
### Expected behavior
Image is downloaded and made available locally.
### Actual behavior
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\71d50a35847e0013e9d57ffdf00789e418ea58734496ebc7677bce0426978d35: The system cannot find the path specified.
### Information about the Issue
Error was found in Kitematic interface.

### Steps to reproduce the behavior

  1. In containers browser, click "Create" button
  2. Wait to connect to Docker
  3. Download reaches roughly 50%
  4. Error appears

**Comment by FrenchBen** [comment]
can you run the same command using `docker pull ... ` this will isolate the issue to kitematic or your Docker setup.

**Comment by raaraya** [comment]
I am having the same problem:

"failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\a0fb1b614dcee6a8c7a532ca62b8b081e911127854d25eedbe9ce99b540c0b39: The parameter is incorrect."

The same happens when using docker pull, I was trying to pull microsoft/nanoserver:latest.

**Comment by FrenchBen** [comment]
This is a Windows Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using linux/windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by fktt** [comment]
You have selecteYou have selected Windows Containers at the time of setup rather than Linux Containers so only Windows-based images will run. To resolve this, right-click the tray icon and select 'Switch to Linux Containers' and it will start working.
https://stackoverflow.com/a/49657088/4258588

**Comment by wave31** [comment]
You have selected Windows Containers at the time of setup rather than Linux Containers so only Windows-based images will run. To resolve this, right-click the tray icon and select 'Switch to Linux Containers' and it will start working.

https://stackoverflow.com/a/49657088/4258588

**Comment by wave31** [comment]
You have selected Windows Containers at the time of setup rather than Linux Containers so only Windows-based images will run. To resolve this, right-click the tray icon and select 'Switch to Linux Containers' and it will start working.
https://stackoverflow.com/a/49657088/4258588

**Comment by spanwair** [comment]
propably you overwrite your hyper-v like me.
for windows container in windows this solved my issue:

1. go to "Turn Windows features on or off"
2. turn of your Hyper-v
3. restart computer
4. go back to "Turn Windows features on or off"
5. turn on Hyper-v
6. restart computer
7. start docker (in this case docker for windows)
8. try to pull "docker pull hello-world"
9. than try to start it "docker start hello-world"
10. if all goes well you see possitive msg from docker

This solve it for me. Happy coding

**Comment by cahitbeyaz** [comment]
I installed docker with windows containsers. For me switching to Linux Containers and switching back to windows containers solved issue.
