### ISSUE TITLE
No files in mounted directory

### ISSUE THREAD

**Issue by pacmandv** [docker/kitematic#3438]
### Expected behavior
to see files in a mounted directory
### Actual behavior
no files
### Information about the Issue
mapped the volume via the Kinematic

![Imapped the volume via the Kinematic](https://i.imgur.com/USmFcm9.png)

and add the same directory to the Vbox

![IVbox](https://i.imgur.com/NA13bHK.png)

### Steps to reproduce the behavior

  1. run hello-world-nginx
  2. map /website_files to the windows directory
  3. Restart container and docker machine
  4. check directory

**Comment by FrenchBen** [comment]
The files in vbox need to be mounted which isn't necessarily done. Check by doing a docker-machine ssh default to check if the folder exists
