### ISSUE TITLE
Cannot create with Kitematic due to unauthorized access (incorrect User/Pass)

### ISSUE THREAD

**Issue by stuartweir** [docker/kitematic#3444]
### Expected behavior
Be able to create the docker container and pull it on local with Kitematic

### Actual behavior
```(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/library/ruby/manifests/latest: unauthorized: incorrect username or password"}```

### Information about the Issue
I logged out of Kitematic, updated my password on Docker Hub, and then relogged in (successfully) into kitematic. I get the same issue.

### Steps to reproduce the behavior

  1. Attempt to create container
  2. If it fails, log out of kitematic, and update password on Docker Hub
  3. After updating password, log in to Kitematic again, attempt to create docker container
  4. Profit (or rather, fail again).

**Comment by FrenchBen** [comment]
Make sure to use your docker id and not your docker email.
