### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by service2client** [docker/kitematic#3448]
### Expected behavior
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
### Actual behavior
typing this command in Win PowerShell or MINGW64 gives errors. How to you get Bitmark Node out of debug mode?
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
### Steps to reproduce the behavior

  1. ...docker run -d --name bitmarkNode -p 9980:9980 \
-p 2136:2136 -p 2135:2135 -p 2130:2130 \
-e PUBLIC_IP=yourip \
bitmark/bitmark-node
  2. ...

**Comment by FrenchBen** [comment]
You need to pass the env Var to the docker run command. 
With `-e GIN_MODE=release` support for the image would be better within the bitmark repo
