### ISSUE TITLE
http error 500

### ISSUE THREAD

**Issue by tomomcmanus** [docker/kitematic#3451]
### Expected behavior
Elasticsearch, Logstash, Kibana (ELK) Docker image
### Actual behavior
(HTTP code 500) server error - Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:42909->10.0.2.3:53: i/o timeout.

### Steps to reproduce the behavior

  1. ...ran in 2 different wifi environments
  2. ...ran from cli and kitematic

**Comment by FrenchBen** [comment]
Make sure that you can do a `docker pull ` of the image and we can go from there.

**Comment by thaJeztah** [comment]
closing because this issue went stale
