### ISSUE TITLE
Kitematic don't use the ios proxy (on Ubuntu)

### ISSUE THREAD

**Issue by vilas27** [docker/kitematic#3467]
I can't connect/logging to dockerhub using the kitematic, because its not using the ubuntu proxy.
If i export the proxy on command line and after run the kitematic in the same session, it work well.
So how i can set this, exist some kitematic configuration file or i need to export the proxy all the time?
Thanks in advance

**Comment by lroellin** [comment]
This is also not working on macOS.

**Comment by FrenchBen** [comment]
@vilas27 For Kitematic to pickup the proxy, you will need to start it from the CLI, so that it can read the env vars. 

@lroellin 
If you use Docker for Mac then it'll work as expected.

**Comment by lroellin** [comment]
Yes, but I can't log into Docker Hub from Kitematic :)

**Comment by FrenchBen** [comment]
@lroellin I don't understand, Docker for Mac has nothing to do with logging in to Hub. You can also do so from Kitematic.

**Comment by lroellin** [comment]
@FrenchBen Yes, that's correct. But in Kitematic, it doesn't work (ECONNREFUSED), whereas in the Docker for Mac GUI I have the option to set the proxy, and then it works alright.

**Comment by vilas27** [comment]
Now it's working fine, via CLI or through the ubuntu application menu. Before I just had the proxy configured in the network options and now I configured the proxy in other places (ex: ```/etc/environment```, ```/etc/apt/apt.conf``` and etc). Maybe that was the problem, is missing the proxy in the right place, but now it is ok.
Thank you ;)

**Comment by FrenchBen** [comment]
This is resolved, I'm closing the issue.
