### ISSUE TITLE
Kitematic failed to login to Docker Hub.

### ISSUE THREAD

**Issue by kenitosan** [docker/kitematic#3506]
### Expected behavior
Login to docker hub successfully.

### Actual behavior
Login to docker hub from kitematic failed.

### Information about the Issue
(HTTP code 401) unexpected - {"message":"Get https://registry-1.docker.io/v2/kitematic/hello-world-nginx/manifests/latest: unauthorized: incorrect username or password"}

### Steps to reproduce the behavior

  1. fire up Kitematic from a MacOS El Capitan environment.
      MacOS version: 10.11.6 (El Capitan)
      Kitematic version: 0.17.0
      Electron version: 0.35.4

  2. click on hello-world-nginx image

**Comment by Viktorminator** [comment]
I removed my newly created image and deleted, after that all works fine

**Comment by Trackhe** [comment]
[issue/5308](https://github.com/docker/kitematic/issues/5308)

**Comment by ulrich** [comment]
Issue fixed, Kitematic can login to the hub now.

Thank you for your feedback.
