### ISSUE TITLE
Unable to download Nexus3 

### ISSUE THREAD

**Issue by waacot** [docker/kitematic#3530]
### Expected behavior
Unable to download Nexus 3 docker image.

### Information about the Issue
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 172.20.10.1:53: read udp 10.0.2.15:52076->172.20.10.1:53: i/o timeout"}

### Steps to reproduce the behavior
Get the docker file from Docker registry.

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by waacot** [comment]
Thx FrenchBen, looks there were a network issue on DNS resolution with a guest WiFi.
Have a nice day.
