### ISSUE TITLE
Multi-layer image names (more than 1 split with /)

### ISSUE THREAD

**Issue by jameswinegar** [docker/kitematic#3533]
### Expected behavior
UI allows to launch images with names similar to
base/project/container

### Actual behavior
HTTP 404 
![image](https://user-images.githubusercontent.com/8434889/35261439-b27ddea0-ffd5-11e7-92ae-7411fba5bfb4.png)

### Information about the Issue
Nothing terribly interesting to say.

### Steps to reproduce the behavior

  1. Pull an image from GCR (google cloud registry) or tag a local image with multiple /

**Comment by FrenchBen** [comment]
I believe this was fixed in the latest release - Could you confirm?

**Comment by jameswinegar** [comment]
Confirmed with user fixed.
