### ISSUE TITLE
(HTTP code 404) unexpected - manifest for machaval/dw-playground:latest not found

### ISSUE THREAD

**Issue by ethanport** [docker/kitematic#3537]
Can't find dw-playground:latest or run `docker pull machaval/dw-playground`

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/machaval/dw-playground/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
