### ISSUE TITLE
error docker in windows 

### ISSUE THREAD

**Issue by gbdadx** [docker/kitematic#3542]
### open kitematic .... trying using ide offline
  1. ...when  i try to use docker and cs50ide offline, it says i cannot use it in windows
  2. ...
![image](https://user-images.githubusercontent.com/26774948/35481193-b49f3f18-03fd-11e8-827f-ccb4c2e78798.png)

**Comment by FrenchBen** [comment]
This is a Linux Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using linux/windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
