### ISSUE TITLE
i cannot use cs50ide offline - error message in windows

### ISSUE THREAD

**Issue by gbdadx** [docker/kitematic#3543]
### Steps to reproduce the behavior

  1. ...
  2. ...
![image](https://user-images.githubusercontent.com/26774948/35481275-4cc2a356-03ff-11e8-9934-6452fa26ebb9.png)

**Comment by FrenchBen** [comment]
As the message states, `--privileged` isn't currently supported on Windows:
https://github.com/moby/moby/issues/31059

**Comment by gbdadx** [comment]
too much problems to run docker and cs50 ide offline. i had asked in facebook 10 days ago, when docker ate my memory and disk use. i can run docker and kitematic now, but i cannot run the cs50 ide with them. thank you for your comments . im going to uninstall docker and all related , and continue with cs50.io

**Comment by FrenchBen** [comment]
@gbdadx You may have better luck opening a ticket with the owner, here:
https://github.com/cs50/ide50

Additionally there are a few people that did shared their startup scripts, such as:
https://github.com/glennlopez/CS50.HarvardX/blob/master/cs50-ide.sh
