### ISSUE TITLE
Error pulling images

### ISSUE THREAD

**Issue by jplourde71** [docker/kitematic#3546]
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/81/81409e9021d330edbe6411201cd161fa862201742be0fe0b3e13a980f11fada2/data?Expires=1517290293&Signature=E9U~R--bMFFYOGPED7DeNpd5S5eTzJPBHzC5Gb6t1zZCdwqJL~ZcH0ObxTjfWoqZZYTSJr7b3EOV0OVT4IBxsLOnFo8IezuVvb4wIuOtY1iFgoY2n9G9WVcBJSk0iRv0RpJMJCtA2wZYSMq3JYBOb5VnBmU6Z3MkEQaQUitdpi8_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
