### ISSUE TITLE
Cannot connect to Docker Hub

### ISSUE THREAD

**Issue by ottacat** [docker/kitematic#3550]
### Expected behavior
Connect to Docker Hub
### Actual behavior
Server 500 error
### Information about the Issue
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

  1. Use Kitematic to download MongoDB container
  2. Error occurs.

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
