### ISSUE TITLE
Cant set volumes to a folder on another drive

### ISSUE THREAD

**Issue by osher** [docker/kitematic#3554]
### Expected behavior
Changing the volume should be work and everything should be dandy.

### Actual behavior
an error message is observed, and the selected folder is not accepted.
![image](https://user-images.githubusercontent.com/803101/35630671-b007c308-06aa-11e8-8c0e-b34c5cfa8b19.png)

Mind that it does work when I'm selecting a folder in the same volume:
![image](https://user-images.githubusercontent.com/803101/35630725-d2211c82-06aa-11e8-8337-1d8f5c35c1d7.png)

### Information about the Issue
Consider windows-10 home, 
with a small SSD disk for system at C:, and a large disk for data  accessible at D:.
docker-toolbox installer which I have downloaded *today*, and virtual-box isntaller which I have also instaled today prior to docker-toolbox.

### Steps to reproduce the behavior
1. Create a container of any kind that requires a volume.
2. Create a folder on drive D. Make sure you can create files in it.
3. Try to change the mounted volume to the data folder you created on drive D

I tried with and without stopping the container, for no avail.

**Comment by FrenchBen** [comment]
Known limitation of Docker Toolbox - Install Docker for Windows for a better experience
