### ISSUE TITLE
wsarecv: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by 306240** [docker/kitematic#3555]
### Expected behavior
I Expect the newly created VM on docker tool box to function like default VM
### Actual behavior
Unable to execute any docker commands on newly created VM
### Information about the Issue
I am able to pull images and create containers on default VM. However, when I am trying the same on newly created VM I see the below error

error during connect: Get https://192.168.99.103:2376/v1.31/images/json?filters=%7B%22reference%22%3A%7B%22ls%22%3Atrue%7D%7D: read tcp xx.xx.xxx.xxx:52970->xx.xx.xxx.xx:8080: wsarecv: An existing connection was forcibly closed by the remote host.

$ docker version
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:05 2017
 OS/Arch:      windows/amd64

Server:
 Version:      18.01.0-ce
 API version:  1.35 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   03596f5
 Built:        Wed Jan 10 20:13:12 2018
 OS/Arch:      linux/amd64
 Experimental: false

$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
BPM       -        virtualbox   Running   tcp://192.168.99.103:2376           v18.01.0-ce
default   *        virtualbox   Running   tcp://192.168.99.101:2376           v18.01.0-ce

BPM is causing the issue.

I tried restart, regenerating the certs etc..
### Steps to reproduce the behavior

  1. Install docker quick start terminal and try to create a new VM apart from default.
  2. Try to execute any command on the new VM.

**Comment by FrenchBen** [comment]
sounds like the VM wasn't setup properly - I would remove the default VM and re-create it
