### ISSUE TITLE
Solr Image issue

### ISSUE THREAD

**Issue by Wellcom-London** [docker/kitematic#3558]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Wellcom-London** [comment]
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/0e/0ee0d104030e718851b52de79213b26e24be0113c1e8ef45e950371129908a04/data?Expires=1517570416&Signature=Gg3P7EJjNbSsRfjKLYHxe~rz94AjzithQRuuMyhCW8UgtRCmmo9vfLdO9Fe4NM8cVI~~oDclkjTM93L55C0h27qdLFJnNOCjs6KO63VVgdO~skSfHJ2nNOy4PjzoLSoe9H~t1oMjpl2i-cAUhT~887Hgs6NkJpBiL6Nsw51Y3NM_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 52.85.90.49:443: i/o timeout

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
