### ISSUE TITLE
Cannot add tuleap-aio from the kitematic interface

### ISSUE THREAD

**Issue by stevebelt** [docker/kitematic#3560]
### Expected behavior
Should be able to install tuleap-aio (from enalean) using the kitematic UI

### Actual behavior
Container downloads and starts-up, but is unable to launch the postfix process within the container. As you watch the Console output, you will see postfix continually starts and crashes.

### Information about the Issue
I believe (based upon similar symptoms reported by non-kitematic users) that this is because the initial install of the container (as described by https://www.tuleap.org/get-started/deploy-tuleap-docker-container) expects the VIRTUAL_HOST environment be set.

### Steps to reproduce the behavior

  1. In the Containers window, select NEW+
  2. Find tuleap-aio
  3. select CREATE
  4. watch the console window. It will end-up in a continuous loop saying:
```
2018-02-02 17:19:21,224 INFO spawned: 'postfix' with pid 403
2018-02-02 17:19:22,227 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-02-02 17:19:22,232 INFO exited: postfix (exit status 1; not expected)
2018-02-02 17:19:22,233 INFO received SIGCLD indicating a child quit
```

**Comment by FrenchBen** [comment]
Reading the documentation for the container, mentions the need to pass the env var of `-e VIRTUAL_HOST=localhost`:
https://hub.docker.com/r/enalean/tuleap-aio/

After initial creation, go to the container created, edit the env var and add what's needed. The container will then work as expected. 

IMHO this is more of an issue on the container image itself - The image should have defaults that work as expected and the ability to override those defaults via the mentioned flag.
