### ISSUE TITLE
Adding container through docker

### ISSUE THREAD

**Issue by reesebl** [docker/kitematic#3562]
### Expected behavior
Show manifest, download container
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for trephine/salome-8.3.0:latest not found"}
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/trephine/salome-8.3.0/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
