### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by Artimunor** [docker/kitematic#3563]
### Steps to reproduce the behavior

  1. search on mysql
  2. download it
  3, error
 (HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
