### ISSUE TITLE
problem with official bvlc caffe image

### ISSUE THREAD

**Issue by aksenofff** [docker/kitematic#3564]
### Information about the Issue
When you try to create container of official caffe framework, an error message is shown.
It says: "(HTTP code 404) manifest for bvlc/caffe:latest not found"

### Steps to reproduce the behavior

  1. I have installed Docker Toolbox (Windows 7 Ultimate). 
  2. I ran Kitematic in VirtualBox mode.
  3. I searched for "caffe".
  4. Then, I hit "CREATE" button on the first search result.
  That's it.
![kitematic](https://user-images.githubusercontent.com/36139250/35782827-5e2a72ac-0a0f-11e8-881a-3cc40716f63b.png)

**Comment by aksenofff** [comment]
Thanks for the quick answer!But how can I specify another tag in Kitematic?6:48, 5 февраля 2018 г., Sebastiaan van Stijn <notifications@github.com>:That image doesn’t have a :latest tag, so you’ll have to specify a specific tag to run (see the available tags on docker hub; https://hub.docker.com/r/bvlc/caffe/tags/)

**Comment by aksenofff** [comment]
Nevermind, I've found it already.Thanks again!10:23, 5 февраля 2018 г., "Аксенов Андрей" <axe61reg@yandex.ru>:Thanks for the quick answer!But how can I specify another tag in Kitematic?6:48, 5 февраля 2018 г., Sebastiaan van Stijn <notifications@github.com>:That image doesn’t have a :latest tag, so you’ll have to specify a specific tag to run (see the available tags on docker hub; https://hub.docker.com/r/bvlc/caffe/tags/)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by FrenchBen** [comment]
Closing as resolved
