### ISSUE TITLE
impossible to access https://registry-1.docker.io/v2/

### ISSUE THREAD

**Issue by cleblain** [docker/kitematic#3573]
### Expected behavior
get an image 
### Actual behavior
an error occured : access refused
### Information about the Issue
UNAUTHORIZED access

### Steps to reproduce the behavior

  1. ...install Docker Toolbox
  2. ...try the first steps : docker run hello-world or the same with kinematic

**Comment by cleblain** [comment]
i check this address : https://registry-1.docker.io/v2/
i got this message {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
so when i want to load an image i got connection refused ?

**Comment by FrenchBen** [comment]
What happens when you do `docker pull nginx`?

**Comment by cleblain** [comment]
i get a connection refused

**Comment by cleblain** [comment]
(HTTP code 500) server error - Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: getsockopt: connection refused

**Comment by cleblain** [comment]
i did the same in applying proxy
(HTTP code 500) server error - Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 192.168.1.16:3128: getsockopt: connection refused

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by cleblain** [comment]
Hi, thank you for the link. 
endly, yesterday i found a solution based on some of your advice ( proxy setting within VM) and also rules on proxy. i should take time to read all your advices.
thank you again for your time

**Comment by FrenchBen** [comment]
If you're working from a Mac, I highly suggest using [Docker for Mac](https://docs.docker.com/docker-for-mac/install/)
