### ISSUE TITLE
Error Trying to install postgres

### ISSUE THREAD

**Issue by fhgomes** [docker/kitematic#3576]
### Expected behavior
Create postgres container

### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

 1. Open kitematic
 2. New
 3. Postgres
 4. create

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
