### ISSUE TITLE
Kitematic unexpected error

### ISSUE THREAD

**Issue by grishgrigoryan** [docker/kitematic#3578]
![screen shot 2018-02-09 at 1 54 09 pm](https://user-images.githubusercontent.com/9796964/36021934-c183ed58-0da0-11e8-84ee-741b46cfe14d.png)

> Command failed: /usr/local/bin/docker-machine -D start default,Docker Machine Version: 0.13.0, build 9ba6da9,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:49973,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,command=start machine=default,(default) Calling .GetState,(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | name="default",(default) DBG | groups="/",(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)",(default) DBG | UUID="6f6cc384-92e4-4ca6-8bf3-6d02c591187f",(default) DBG | CfgFile="/Users/Grigor/.docker/machine/machines/default/default/default.vbox",(default) DBG | SnapFldr="/Users/Grigor/.docker/machine/machines/default/default/Snapshots",(default) DBG | LogFldr="/Users/Grigor/.docker/machine/machines/default/default/Logs",(default) DBG | hardwareuuid="6f6cc384-92e4-4ca6-8bf3-6d02c591187f",(default) DBG | memory=2048,(default) DBG | pagefusion="off",(default) DBG | vram=8,(default) DBG | cpuexecutioncap=100,(default) DBG | hpet="on",(default) DBG | chipset="piix3",(default) DBG | firmware="BIOS",(default) DBG | cpus=1,(default) DBG | pae="on",(default) DBG | longmode="on",(default) DBG | triplefaultreset="off",(default) DBG | apic="on",(default) DBG | x2apic="off",(default) DBG | cpuid-portability-level=0,(default) DBG | bootmenu="disabled",(default) DBG | boot1="dvd",(default) DBG | boot2="dvd",(default) DBG | boot3="disk",(default) DBG | boot4="none",(default) DBG | acpi="on",(default) DBG | ioapic="on",(default) DBG | biosapic="apic",(default) DBG | biossystemtimeoffset=0,(default) DBG | rtcuseutc="on",(default) DBG | hwvirtex="on",(default) DBG | nestedpaging="on",(default) DBG | largepages="on",(default) DBG | vtxvpid="on",(default) DBG | vtxux="on",(default) DBG | paravirtprovider="default",(default) DBG | effparavirtprovider="kvm",(default) DBG | VMState="poweroff",(default) DBG | VMStateChangeTime="2018-02-06T18:32:04.000000000",(default) DBG | monitorcount=1,(default) DBG | accelerate3d="off",(default) DBG | accelerate2dvideo="off",(default) DBG | teleporterenabled="off",(default) DBG | teleporterport=0,(default) DBG | teleporteraddress="",(default) DBG | teleporterpassword="",(default) DBG | tracing-enabled="off",(default) DBG | tracing-allow-vm-access="off",(default) DBG | tracing-config="",(default) DBG | autostart-enabled="off",(default) DBG | autostart-delay=0,(default) DBG | defaultfrontend="",(default) DBG | storagecontrollername0="SATA",(default) DBG | storagecontrollertype0="IntelAhci",(default) DBG | storagecontrollerinstance0="0",(default) DBG | storagecontrollermaxportcount0="30",(default) DBG | storagecontrollerportcount0="30",(default) DBG | storagecontrollerbootable0="on",(default) Calling .Start,(default) DBG | "SATA-0-0"="/Users/Grigor/.docker/machine/machines/default/boot2docker.iso",(default) DBG | "SATA-ImageUUID-0-0"="9242dbb7-3728-42e9-b829-c9c8c3cb2985",(default) DBG | "SATA-tempeject"="off",(default) DBG | "SATA-IsEjected"="off",(default) DBG | "SATA-1-0"="/Users/Grigor/.docker/machine/machines/default/disk.vmdk",(default) DBG | "SATA-ImageUUID-1-0"="5aa39f2d-8004-4ef0-afe6-1b529a4510dd",(default) DBG | "SATA-2-0"="none",(default) DBG | "SATA-3-0"="none",(default) DBG | "SATA-4-0"="none",(default) DBG | "SATA-5-0"="none",(default) DBG | "SATA-6-0"="none",(default) DBG | "SATA-7-0"="none",(default) DBG | "SATA-8-0"="none",(default) DBG | "SATA-9-0"="none",(default) DBG | "SATA-10-0"="none",(default) DBG | "SATA-11-0"="none",(default) DBG | "SATA-12-0"="none",(default) DBG | "SATA-13-0"="none",(default) DBG | "SATA-14-0"="none",(default) DBG | "SATA-15-0"="none",(default) DBG | "SATA-16-0"="none",(default) DBG | "SATA-17-0"="none",(default) DBG | "SATA-18-0"="none",(default) DBG | "SATA-19-0"="none",(default) DBG | "SATA-20-0"="none",(default) DBG | "SATA-21-0"="none",(default) DBG | "SATA-22-0"="none",(default) DBG | "SATA-23-0"="none",(default) DBG | "SATA-24-0"="none",(default) DBG | "SATA-25-0"="none",(default) DBG | "SATA-26-0"="none",(default) DBG | "SATA-27-0"="none",(default) DBG | "SATA-28-0"="none",(default) DBG | "SATA-29-0"="none",(default) DBG | natnet1="nat",(default) DBG | macaddress1="08002718FC5D",(default) DBG | cableconnected1="on",(default) DBG | nic1="nat",(default) DBG | nictype1="82540EM",(default) DBG | nicspeed1="0",(default) DBG | mtu="0",(default) DBG | sockSnd="64",(default) DBG | sockRcv="64",(default) DBG | tcpWndSnd="64",(default) DBG | tcpWndRcv="64",(default) DBG | nic2="none",(default) DBG | nic3="none",(default) DBG | nic4="none",(default) DBG | nic5="none",(default) DBG | nic6="none",(default) DBG | nic7="none",(default) DBG | nic8="none",(default) DBG | hidpointing="ps2mouse",(default) DBG | hidkeyboard="ps2kbd",(default) DBG | uart1="off",(default) DBG | uart2="off",(default) DBG | uart3="off",(default) DBG | uart4="off",(default) DBG | lpt1="off",(default) DBG | lpt2="off",(default) DBG | audio="coreaudio",(default) DBG | clipboard="disabled",(default) DBG | draganddrop="disabled",(default) DBG | vrde="off",(default) DBG | usb="off",(default) DBG | ehci="off",(default) DBG | xhci="off",(default) DBG | SharedFolderNameMachineMapping1="Users",(default) DBG | SharedFolderPathMachineMapping1="/Users",(default) DBG | vcpenabled="off",(default) DBG | vcpscreens=0,(default) DBG | vcpfile="/Users/Grigor/.docker/machine/machines/default/default/default.webm",(default) DBG | vcpwidth=1024,(default) DBG | vcpheight=768,(default) DBG | vcprate=512,(default) DBG | vcpfps=25,(default) DBG | GuestMemoryBalloon=0,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | name="default",(default) DBG | groups="/",(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)",(default) DBG | UUID="6f6cc384-92e4-4ca6-8bf3-6d02c591187f",(default) DBG | CfgFile="/Users/Grigor/.docker/machine/machines/default/default/default.vbox",(default) DBG | SnapFldr="/Users/Grigor/.docker/machine/machines/default/default/Snapshots",(default) DBG | LogFldr="/Users/Grigor/.docker/machine/machines/default/default/Logs",(default) DBG | hardwareuuid="6f6cc384-92e4-4ca6-8bf3-6d02c591187f",(default) DBG | memory=2048,(default) DBG | pagefusion="off",(default) DBG | vram=8,(default) DBG | cpuexecutioncap=100,(default) DBG | hpet="on",(default) DBG | chipset="piix3",(default) DBG | firmware="BIOS",(default) DBG | cpus=1,(default) DBG | pae="on",(default) DBG | longmode="on",(default) DBG | triplefaultreset="off",(default) DBG | apic="on",(default) DBG | x2apic="off",(default) DBG | cpuid-portability-level=0,(default) DBG | bootmenu="disabled",(default) DBG | boot1="dvd",(default) DBG | boot2="dvd",(default) DBG | boot3="disk",(default) DBG | boot4="none",(default) DBG | acpi="on",(default) DBG | ioapic="on",(default) DBG | biosapic="apic",(default) DBG | biossystemtimeoffset=0,(default) DBG | rtcuseutc="on",(default) DBG | hwvirtex="on",(default) DBG | nestedpaging="on",(default) DBG | largepages="on",(default) DBG | vtxvpid="on",(default) DBG | vtxux="on",(default) DBG | paravirtprovider="default",(default) DBG | effparavirtprovider="kvm",(default) DBG | VMState="poweroff",(default) DBG | VMStateChangeTime="2018-02-06T18:32:04.000000000",(default) DBG | monitorcount=1,(default) DBG | accelerate3d="off",(default) DBG | accelerate2dvideo="off",(default) DBG | teleporterenabled="off",(default) DBG | teleporterport=0,(default) DBG | teleporteraddress="",(default) DBG | teleporterpassword="",(default) DBG | tracing-enabled="off",(default) DBG | tracing-allow-vm-access="off",(default) DBG | tracing-config="",(default) DBG | autostart-enabled="off",(default) DBG | autostart-delay=0,(default) DBG | defaultfrontend="",(default) DBG | storagecontrollername0="SATA",(default) DBG | storagecontrollertype0="IntelAhci",(default) DBG | storagecontrollerinstance0="0",(default) DBG | storagecontrollermaxportcount0="30",(default) DBG | storagecontrollerportcount0="30",(default) DBG | storagecontrollerbootable0="on",(default) DBG | "SATA-0-0"="/Users/Grigor/.docker/machine/machines/default/boot2docker.iso",(default) DBG | "SATA-ImageUUID-0-0"="9242dbb7-3728-42e9-b829-c9c8c3cb2985",(default) DBG | "SATA-tempeject"="off",(default) DBG | "SATA-IsEjected"="off",(default) DBG | "SATA-1-0"="/Users/Grigor/.docker/machine/machines/default/disk.vmdk",(default) DBG | "SATA-ImageUUID-1-0"="5aa39f2d-8004-4ef0-afe6-1b529a4510dd",(default) DBG | "SATA-2-0"="none",(default) DBG | "SATA-3-0"="none",(default) DBG | "SATA-4-0"="none",(default) DBG | "SATA-5-0"="none",(default) DBG | "SATA-6-0"="none",(default) DBG | "SATA-7-0"="none",(default) DBG | "SATA-8-0"="none",(default) DBG | "SATA-9-0"="none",(default) DBG | "SATA-10-0"="none",(default) DBG | "SATA-11-0"="none",(default) DBG | "SATA-12-0"="none",(default) DBG | "SATA-13-0"="none",(default) DBG | "SATA-14-0"="none",(default) DBG | "SATA-15-0"="none",(default) DBG | "SATA-16-0"="none",(default) DBG | "SATA-17-0"="none",(default) DBG | "SATA-18-0"="none",(default) DBG | "SATA-19-0"="none",(default) DBG | "SATA-20-0"="none",(default) DBG | "SATA-21-0"="none",(default) DBG | "SATA-22-0"="none",(default) DBG | "SATA-23-0"="none",(default) DBG | "SATA-24-0"="none",(default) DBG | "SATA-25-0"="none",(default) DBG | "SATA-26-0"="none",(default) DBG | "SATA-27-0"="none",(default) DBG | "SATA-28-0"="none",(default) DBG | "SATA-29-0"="none",(default) DBG | natnet1="nat",(default) DBG | macaddress1="08002718FC5D",(default) DBG | cableconnected1="on",(default) DBG | nic1="nat",(default) DBG | nictype1="82540EM",(default) DBG | nicspeed1="0",(default) DBG | mtu="0",(default) DBG | sockSnd="64",(default) DBG | sockRcv="64",(default) DBG | tcpWndSnd="64",(default) DBG | tcpWndRcv="64",(default) DBG | nic2="none",(default) DBG | nic3="none",(default) DBG | nic4="none",(default) DBG | nic5="none",(default) DBG | nic6="none",(default) DBG | nic7="none",(default) DBG | nic8="none",(default) DBG | hidpointing="ps2mouse",(default) DBG | hidkeyboard="ps2kbd",(default) DBG | uart1="off",(default) DBG | uart2="off",(default) DBG | uart3="off",(default) DBG | uart4="off",(default) DBG | lpt1="off",(default) DBG | lpt2="off",(default) DBG | audio="coreaudio",(default) DBG | clipboard="disabled",(default) DBG | draganddrop="disabled",(default) DBG | vrde="off",(default) DBG | usb="off",(default) DBG | ehci="off",(default) DBG | xhci="off",(default) DBG | SharedFolderNameMachineMapping1="Users",(default) DBG | SharedFolderPathMachineMapping1="/Users",(default) DBG | vcpenabled="off",(default) DBG | vcpscreens=0,(default) DBG | vcpfile="/Users/Grigor/.docker/machine/machines/default/default/default.webm",(default) DBG | vcpwidth=1024,(default) DBG | vcpheight=768,(default) DBG | vcprate=512,(default) DBG | vcpfps=25,(default) DBG | GuestMemoryBalloon=0,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00,(default) DBG | Not found,(default) DBG | COMMAND: /usr/local/bin/VBoxManage hostonlyif create,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | 0%...,(default) DBG | Progress state: NS_ERROR_FAILURE,(default) DBG | VBoxManage: error: Failed to create the host-only adapter,(default) DBG | VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory,(default) DBG | VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface,(default) DBG | VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue,

**Comment by FrenchBen** [comment]
I would recommend you use Docker for Mac, instead of Docker Toolbox
