### ISSUE TITLE
Error installing scratch image

### ISSUE THREAD

**Issue by tamsanh** [docker/kitematic#3580]
### Expected behavior

Download scratch and install

### Actual behavior

Error because scratch is a reserved name

### Information about the Issue

I was just trying to install a scratch image to install things

### Steps to reproduce the behavior

  1. Click +New
  2. Search `scratch`
  3. Click `create` under the official scratch
  4. Encounter the error

**Comment by FrenchBen** [comment]
Scratch doesn't actually run anything. It's a correct image but doesn't actually build/run anything.
