### ISSUE TITLE
Error grabbing container image repository?

### ISSUE THREAD

**Issue by reidel** [docker/kitematic#3581]
### Expected behavior
download and clone of containter image
### Actual behavior
error 404: (HTTP code 404) unexpected - manifest for hzhuskycision/pix4dautorepo:latest not found
### Information about the Issue
Action initiateed in Kitematic from search of repo, clicking the create button

### Steps to reproduce the behavior

  1. click the create button for the  hzhuskycision/pix4dautorepo container image
  2. wait for the results

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/hzhuskycision/pix4dautorepo/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
