### ISSUE TITLE
Canvas-lms returning error using kitematic for docker

### ISSUE THREAD

**Issue by armageddon6** [docker/kitematic#3586]
### Expected behavior
Docker container for Canvas-lms (Instructure) would be created

### Actual behavior
message returned: (HTTP code 404) unexpected - {"message":"manifest for instructure/canvas-lms:latest not found"}

### Information about the Issue
Trying to create a container using Kitematic

### Steps to reproduce the behavior

  1. ... search for camvas lms in kitematic
  2. ...click the create button

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/instructure/canvas-lms/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
