### ISSUE TITLE
 (HTTP code 500) server error - Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by tomgron** [docker/kitematic#3590]
### Expected behavior
Download any image from hub.docker.com with Kitematic

### Actual behavior
Kitematic starts to download but fails mith message : (HTTP code 500) server error - Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Env Win10x64 (latest), latest Kitematic

![image](https://user-images.githubusercontent.com/1743381/36339069-fc2eba98-13c5-11e8-91dc-86e9a6e76830.png)

![image](https://user-images.githubusercontent.com/1743381/36339087-69faaa96-13c6-11e8-9ec2-055f7decb876.png)

### Information about the Issue
Just tried to download with Kitematic after logging in as "tomgron" - just not working, doesn't even start to download.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

Kitematic doesn't have any magical way to configure this - If you can't pull from within the Boot2Docker VM, then Kitematic wont either.
