### ISSUE TITLE
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### ISSUE THREAD

**Issue by ahoehma** [docker/kitematic#3594]
### Expected behavior
postgres container download

### Actual behavior
error

### Information about the Issue
I installes docker for windows ... Hyper-V ... Installation was successful.

**Comment by FrenchBen** [comment]
Can you replicate the issue via the CLI?

**Comment by geosava** [comment]
Hi I have the same issue right now trying to download jeci/jbake-docker public image.

I have the problem in kinematic wherer I get error 500 like this one and form docker CLI running "docker pull jeci/jbake-docker" getting

`Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

I am on windows 10 with latest docker CE Version 17.12.0-ce-win47 (15139).

**Comment by geosava** [comment]
Playing with the issue I have found that when I run
docker run --rm -it --net=host jeci/jbake-docker

The CLI returns that there is no latest tag.

So viewing it from kitematic I show that the latest tag is 2.5.0 and by running
docker run --rm -it --net=host jeci/jbake-docker:2.5.0 the image was finally downloaded.

**Comment by FrenchBen** [comment]
@geosava Marking this as resolved.

**Comment by geosava** [comment]
The initial poster had a problem with the "postgres container".

I have just found that the specific container I wanted to use at the time did not had a tag labeled "latest" in its repository that caused the issue.

If I use a specific tag in command line CLI or Kitematic it works. 
But kitematic container browser has as default tag the tag "latest" even if it does not exists in the container repo.

I hope this will help people with similar issues.
