### ISSUE TITLE
Hello-world-nginx fails on Docker-for-Windows (command line)

### ISSUE THREAD

**Issue by aplatypus** [docker/kitematic#3599]
### Expected behavior

* I expected the docker file to load and run
  * image: [hello-world-nginx](https://hub.docker.com/r/kitematic/hello-world-nginx/)
* It does Not.

For reference
* The plain old hello-world docker image runs on command line, but not from Kitematic

Relates to:
* [Hello-world-nginx fails on Kitematic #3598](https://github.com/docker/kitematic/issues/3598)

### Actual behavior

**[hello-world-nginx](https://hub.docker.com/r/kitematic/hello-world-nginx/)** 

```
D:> docker run   kitematic/hello-world-nginx
Unable to find image 'kitematic/hello-world-nginx:latest' locally
latest: Pulling from kitematic/hello-world-nginx
77c6c00e8b61: Extracting [==================================================>]   2.17MB/2.17MB
9b55a9cb10b3: Download complete
e6cdd97ba74d: Download complete
7fecf1e9de6b: Download complete
6b75f22d7bea: Download complete
e8e00fb8479f: Download complete
69fad424364c: Download complete
b3ba6e76b671: Download complete
a956773dd508: Download complete
26d2b0603932: Download complete
3cdbb221209e: Download complete
a3ed95caeb02: Download complete
docker: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\8dc53fe00ab6fb97707dc915fd367ded66bd77bbf937d596ae7f965916be4135: The system cannot find the path specified.
See 'docker run --help'.
```

### Information about the Issue

* Please see output from docker command line
*  Windows 10 64-bit
*  Docker version 17.12.0-ce-win47 (151139)
*  Engine:  17.12.0-ce
* Machine:  0.13.0
* Compose:  1.18.0
* Notary: 0.4.3
* Credential helpers: 0.6.0

### Steps to reproduce the behavior

  1. .On Windows with Docker for Windows installed
  2. Enter: `docker run   kitematic/hello-world-nginx`

**Comment by FrenchBen** [comment]
DUP of https://github.com/docker/kitematic/issues/3598

**Comment by aplatypus** [comment]
This is a different use-case.

This model works from the command line on Linux.  So the Hello-world-nginx  image itself is fine.

**Comment by FrenchBen** [comment]
With the error being exactly the same, the underlying problem may be the same `The system cannot find the path specified`
