### ISSUE TITLE
Unable to create Docker image 

### ISSUE THREAD

**Issue by nilavalagansugumaran** [docker/kitematic#3601]
### Expected behavior
I should be able to download the docker image
### Actual behavior
Error message - 
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

  1. Login to Kitematic
  2. add new container 
  3. search for "mongodb"
  4. click "create" on any image to see the error

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
Additionally if you're behind a firewall, then please check our Wiki for more information.
