### ISSUE TITLE
Hello-World-Nginx Failed to Pull Image

### ISSUE THREAD

**Issue by ondrovic** [docker/kitematic#3605]
### Expected behavior
Download and access image
### Actual behavior
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\8471a9a9e19ae66589faa66976d80f5a544732d431c78b41611cc52739a49ea7: The system cannot find the path specified.
### Information about the Issue
Windows 10 build 

### Steps to reproduce the behavior

  1. docker pull kitematic/hello-world-nginx

**Comment by FrenchBen** [comment]
Seems to be a Docker for Windows issue, since the CLI does the same thing - Can you open up an issue here: https://github.com/docker/for-win
