### ISSUE TITLE
Etherium Solc Docker Image cannot be installed via Kitematic

### ISSUE THREAD

**Issue by catapultio** [docker/kitematic#3607]
### Expected behavior
As a user, I should be able to download the official etherium/solc docker image located on Docker Hub. via Kitematic [Etherium Solc Docker](https://hub.docker.com/r/ethereum/solc/)

### Actual behavior
When trying to create a new etherium/solc image from Kitematic, I am receiving a 404 error.

### Information about the Issue
<img width="642" alt="screen shot 2018-02-23 at 6 55 56 pm" src="https://user-images.githubusercontent.com/35767764/36622459-33e662a6-18cb-11e8-993b-8c0202c74b39.png">

### Steps to reproduce the behavior

  1. Start up the Docker app for OSX
  2. Once Docker is up and running, start Kitematic
  3. Click the "+ Create" button
  4. Enter "solc" in the Search bar
  5. Hit the "Create" button for the etherium/solc result.
  6. Observe error

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/ethereum/solc/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by catapultio** [comment]
I should have realized that there was not a "latest" tagged image... Sorry about that and many thanks for your help!!
