### ISSUE TITLE
Can't pull Linux containers when using LCOW

### ISSUE THREAD

**Issue by hoegge** [docker/kitematic#3609]
### Expected behavior
With the new ability to run in "Linux Containers on Windows" one can finally get rid of using Hyper-V and enable VMWare and Virtual Box on the same system running Docker for Windows. But there seems to be no way to let Kitematic know, that I want to run / get Linux containers / images - like the command line parameter:
`docker pull --platform linux`
### Actual behavior
`We're sorry. There seems to 
be an error:
cannot download image with operating system "linux" when requesting "windows"

### Information about the Issue
There should really be an option switch choosing between Windows and Linux containers/images in Kitematic.

### Steps to reproduce the behavior

  1. Switch to Windows containers (in Docker for Windows)
  2. Open Kitematic
  3. Try to download e.g. Ubuntu:latest

**Comment by FrenchBen** [comment]
Can you please open up an issue in https://github.com/docker/for-win ?

**Comment by hoegge** [comment]
@FrenchBen  yes - but why? Isn't pulling with this flag something Kitematic should do when calling docker        ?
