### ISSUE TITLE
what is this problem? how to solve it?

### ISSUE THREAD

**Issue by KeymonWong** [docker/kitematic#3611]
###
Error while pulling image: Get https://index.docker.io/v1/repositories/gitlab/gitlab-ce/images: http: error connecting to proxy http://127.0.0.1:53847: dial tcp 127.0.0.1:53847: getsockopt: connection refused

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by KeymonWong** [comment]
thx
