### ISSUE TITLE
Getting error on Kitematic when creating container

### ISSUE THREAD

**Issue by ryadav46** [docker/kitematic#3614]
![kitematic](https://user-images.githubusercontent.com/36722854/36671224-e86bcb06-1b20-11e8-97f4-1d21324161d9.PNG)

**Comment by FrenchBen** [comment]
What happens when you try to run the same container via the CLI?

**Comment by ryadav46** [comment]
![k](https://user-images.githubusercontent.com/36722854/36709222-bd7a8690-1b9c-11e8-8996-98460edc45f0.PNG)

**Comment by FrenchBen** [comment]
Since the error is also present at the CLI level, it seems related to a Docker for Windows issue, not Kitematic. See:
https://github.com/docker/for-win/issues/351
