### ISSUE TITLE
manifest for asteroidice/arch-csnobol4:latest not found

### ISSUE THREAD

**Issue by charleswardell** [docker/kitematic#3615]
### Expected behavior
From Kitematic I tried to create a new container using asteroidice/arch-csnobol4

### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for asteroidice/arch-csnobol4:latest not found"}

### Steps to reproduce the behavior

  1. Search for snobol4
  2. Click create on the image that is found

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/asteroidice/arch-csnobol4/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
