### ISSUE TITLE
Start on docker startup

### ISSUE THREAD

**Issue by N-Andronopoulos** [docker/kitematic#3625]
### Feature request

I think it's very essential to have a "start on docker startup" tick box, like doing to docker cli: `docker update --restart=always <CONTAINER ID>`

**Comment by FrenchBen** [comment]
You mean having this option be part of the interface/ui?

**Comment by N-Andronopoulos** [comment]
Yes of course, I think I would be best in the advanced settings of the container view (with the privileged, TTY stuff).

**Comment by FrenchBen** [comment]
Feel free to play with it and provide us with a PR :)

**Comment by FrenchBen** [comment]
@N-Andronopoulos Closing now, since the PR was merged
