### ISSUE TITLE
(HTTP code 404) unexpected - manifest for kubernetesdashboarddev/kubernetes-dashboard-amd64:latest not found

### ISSUE THREAD

**Issue by sukonkan** [docker/kitematic#3629]
(HTTP code 404) unexpected - manifest for kubernetesdashboarddev/kubernetes-dashboard-amd64:latest not found

**Comment by avlad** [comment]
same issue

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/kubernetesdashboarddev/kubernetes-dashboard-amd64/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
