### ISSUE TITLE
HTTP code 500 when I download Mongo using Docker

### ISSUE THREAD

**Issue by joaopcm** [docker/kitematic#3631]
### Expected behavior
It should download the MongoDB

### Actual behavior
When I click in "create", Mongo shows this message: (HTTP code 500) server error - readlink /var/lib/docker/overlay2/l: invalid argument

### Information about the Issue
I do not know if the issue is because of my Firewall

### Steps to reproduce the behavior

  1. Installing Docker
  2. Creating an image
  3. Creating MongoDB using Docker

**Comment by FrenchBen** [comment]
Can you re-create this using the CLI?

**Comment by joaopcm** [comment]
Thanks for reply me, French!

  I've used the same version of Docker in the last mounth, and that worked. But recently I've needed to format my pc, and right now I am having this issue.

**Comment by FrenchBen** [comment]
@joaopcm can you confirm that doing `docker run ...` your image, shows you the same error?
