### ISSUE TITLE
erlang

### ISSUE THREAD

**Issue by yzmjava** [docker/kitematic#3633]
### Steps to reproduce the behavior

  1. ...
  2. ...(HTTP code 500) server error - Get https://registry-1.docker.io/v2/library/erlang/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Ferlang%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
