### ISSUE TITLE
Virtual Box Setup gives "We're Sorry!"

### ISSUE THREAD

**Issue by sl5net** [docker/kitematic#3638]
### Expected behavior
stops with errors after seconds

### Actual behavior
Says needet to use VirtualBox - Setup. Then it runs to 99% says ""We're Sorry!" and stops with the erros bolow

### Information about the Issue
Command failed: C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.13.0, build 9ba6da9,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:52453,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:52457,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.2.6r120293,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: wmic computersystem get hypervisorpresent,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | HypervisorPresent ,(default) DBG | TRUE ,(default) DBG | ,(default) DBG | },Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)",open C:\Users\Administrator\.docker\machine\machines\default\default\Logs\VBox.log: Das System kann den angegebenen Pfad nicht finden.,notifying bugsnag: [Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"],

**Comment by rillig** [comment]
I had a similar error. This error page should be improved:

* The error messages are logically organized in lines; still, they are displayed as an unreadable blob.
  To make them display nicer, replace `,(?! )` with `,\n`.

* Since this is an "unexpected error", there should be a "report this error" button.

**Comment by FrenchBen** [comment]
The last line tells you exactly what the error is:
```
This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
```
