### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for fecshop/fecshop:latest not found"}

### ISSUE THREAD

**Issue by caihaibin1991** [docker/kitematic#3639]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by caihaibin1991** [comment]
i can search this image ,but i can not install it.

**Comment by caihaibin1991** [comment]
the keyword is "fecshop"

**Comment by Memerto** [comment]
I tried to download the image "cakephp" but got the same problem.
Why is listed if you get an error 404?

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/fecshop/fecshop/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
