### ISSUE TITLE
hyperledger fabric

### ISSUE THREAD

**Issue by DIBI-KOUADJO** [docker/kitematic#3640]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
No information provided or steps to replicate - Closing 😞

**Comment by DIBI-KOUADJO** [comment]
________________________________________
De : French Ben <notifications@github.com>
Envoyé : mardi 13 mars 2018 00:59:56
À : docker/kitematic
Cc : DIBI KOUADJO JEAN MARTIAL; Author
Objet : Re: [docker/kitematic] hyperledger fabric (#3640)

Closed #3640<https://github.com/docker/kitematic/issues/3640>.
