### ISSUE TITLE
(HTTP code 500) server error

### ISSUE THREAD

**Issue by CptPlastic** [docker/kitematic#3649]
### Expected behavior
Download images

### Actual behavior
(HTTP code 500) server error - Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Information about the Issue
I can run images fine in docker 

### Steps to reproduce the behavior

  1. Install Kitematic connect to docker hub
  2. attempt to download from docker hub

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
