### ISSUE TITLE
Files gone after restart

### ISSUE THREAD

**Issue by Holzberg** [docker/kitematic#3651]
### Expected behavior
I installed Docker Toolbox on Windows 10 Pro and am using VirtualBox.  I installed the official Redmine Docker and using the CLI I ran:

`docker run -it -v //c/Users/tholzer/docker://data:rw redmine bash`

I then copied files from /data to /usr/src/redmine/public/themes
Then, after restart the files are gone.
Not sure why it keeps resetting the instance.

### Actual behavior

Files are deleted instead of retained,

### Steps to reproduce the behavior

  1. see above

**Comment by FrenchBen** [comment]
How do you restart? Are you sure that redmine doesn't have a process that touches that particular location?
Also this looks like a CLI command, not something done via Kitematic. Please open it in the appropriate repo docker/for-win
