### ISSUE TITLE
docker pull Failure lhwong/kie-workbench-showcase

### ISSUE THREAD

**Issue by piropiron-n** [docker/kitematic#3657]
### Expected behavior
I got the docker image 

### Actual behavior
Client.Timeout exceeded while awaiting headers

### Information about the Issue
Operating results environment with other docker image.

### Steps to reproduce the behavior

  1. docker pull lhwong/kie-workbench-showcase
     Using default tag: latest

  2. Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
Additionally verify that you can pull the image via the cli: `docker pull lhwong/kie-workbench-showcase`

**Comment by piropiron-n** [comment]
Thank you for your reply.

My problem was caused by not logging in to the docker HUB.
It was not a problem of DNS and HTTP PROXY.
