### ISSUE TITLE
Not able to pull images

### ISSUE THREAD

**Issue by prakashpillay** [docker/kitematic#3662]
Get https://registry-1.docker.io/v2/library/rabbitmq/manifests/sha256:07f9953d80065064e6d09b96fef562ae9e122b19478f2c541c94537d7feb7d43: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:60027->192.168.65.1:53: i/o timeout

I get this error both through powershell command line and kitematic

**Comment by FrenchBen** [comment]
If you get it on both, then it's not a kitematic issue. 
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
Additionally, if you're behind a firewall or vpn, see our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
