### ISSUE TITLE
Cant set docker client config

### ISSUE THREAD

**Issue by sunfuze** [docker/kitematic#367]
I use docker in China, connecting to docker hub without a mirror is very slowly. I want to set `registry-mirror`. In ubuntu, I can set it in `/etc/default/docker`.But using kitematic, i cant find anything docs about the config of docker client setting.

**Comment by jeffdm** [comment]
Thanks for the issue!

For now, you can ssh into the VM via `docker-machine ssh` and then change `/etc/default/docker` in the VM. Hope this helps

**Comment by sunfuze** [comment]
Thank. I have found the solution, the local docker-machine using boot2docker image, the config is in `/var/lib/boot2docker/profile`

**Comment by sunfuze** [comment]
I was not working well, `docker search` through the registry mirror, but `pull` never succeeded

**Comment by imWildCat** [comment]
Hi, @sunfuze , did you solve the problem?

In my case, it worked fine.

Just following: https://dashboard.daocloud.io/mirror

> 配置Docker加速器
> 请确认你的 Kitematic 已经启动，并执行
```bash
docker-machine ssh dev
sudo sed -i "s|EXTRA_ARGS='|EXTRA_ARGS='--registry-mirror=http://b89f3c51.m.daocloud.io |g" /var/lib/boot2docker/profile
exit
docker-machine restart dev
```
