### ISSUE TITLE
install CRISPRAnalyzeR got server 500.

### ISSUE THREAD

**Issue by urmyfaith** [docker/kitematic#3670]
### Expected behavior

pull image CRISPRAnalyzeR 

### Actual behavior
Got  a server error 500.

### Information about the Issue

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

  1. in the search box, enter CRISPRAnalyzeR 
  2. choose CRISPRAnalyzeR ,click create.
  3. got server error 500.

**Comment by FrenchBen** [comment]
The image is 3GB! 
Better be on a solid connection the whole time. 
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.
