### ISSUE TITLE
Kitematic Issue While Logged in With Username instead of email

### ISSUE THREAD

**Issue by DreamIntoTheDeep** [docker/kitematic#3671]
### Expected behavior
To open up a helloworld project in docker/kitematic
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
### Information about the Issue
I logged in with my username, not my e-mail. That didn't work

### Steps to reproduce the behavior

  1. ...I clicked on helloworld 
  2. ...clicked create and voila.

**Comment by FrenchBen** [comment]
Timeout is usually linked to 2 things:
* Your DNS isn't great: try something more solid, such as Google DNS
* You are behind a firewall/proxy: look in our wiki for solutions around this. 

If you can run/pull the image via the CLI, then it's a kitematic issue. If you get the same error, then it's more than likely a setup issue. 

Without much more information it's difficult for this to be replicated. Closing until further details are provided.
