### ISSUE TITLE
Cannot download/pull from hub

### ISSUE THREAD

**Issue by jayeuperio** [docker/kitematic#3674]
### Expected behavior
pull images from hub
### Actual behavior
(HTTP code 500) server error - Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by FrenchBen** [comment]
Can you replicate this behavior via `docker pull ...`

**Comment by jayeuperio** [comment]
yup. I tried other images and still got some errors.
Its working fine now after I restart the PC. It seems a network failure on my side.
Thank you for the response. And sorry if I panicked quickly. :)
