### ISSUE TITLE
Not using Corporate Proxy

### ISSUE THREAD

**Issue by ryanpconnors** [docker/kitematic#3682]
### Expected behavior
Opening the Kitematic application directly behind a corporate proxy, all available images should be populated.

![image](https://user-images.githubusercontent.com/916687/37839528-0a95b34e-2e91-11e8-8bb5-eef8a5c37138.png)

### Actual behavior
When opening the Kitematic application directly behind a corporate proxy the images are never properly loaded.

![image](https://user-images.githubusercontent.com/916687/37839557-1ef3439c-2e91-11e8-994f-d99a2cedf364.png)

### Information about the Issue
I can get the images to load behind the proxy by running:
```
http_proxy=$HTTP_PROXY open /Applications/Docker/Kitematic\ \(Beta\).app
```
However, when opening the application directly the images never get through the proxy.

### Steps to reproduce the behavior

  1. From behind a proxy, open the kitematic application directly or by running `open /Applications/Docker/Kitematic\ \(Beta\).app`.
Note that the images will not load.
  2. Open the application by directly referencing the HTTP Proxy environment variable `http_proxy=$HTTP_PROXY open /Applications/Docker/Kitematic\ \(Beta\).app`
note that the images will load.

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
