### ISSUE TITLE
datarobot-prime-server

### ISSUE THREAD

**Issue by njss** [docker/kitematic#3683]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
No information provided or steps to replicate - Closing 😞

**Comment by njss** [comment]
Sorry for not providing the necessary steps to replicate the problem. I just used the Kitematic automatic form, and I did not noticed that the form was not filled automatically after all. Basically, what happened was some kind of critical error when trying to start the docker image: datarobot-prime-server available online on Docker Hub.

Best,

Nelson
