### ISSUE TITLE
Don't show page bar

### ISSUE THREAD

**Issue by qwinmen** [docker/kitematic#3684]
### Expected behavior
A numeraible bar need be hide.
### Actual behavior
![image](https://user-images.githubusercontent.com/22964689/37841726-64101b0e-2ed1-11e8-9416-c28dedf03ce8.png)
see image.
### Information about the Issue
Numeraible bar error. Non-critical state.

### Steps to reproduce

  1. Open 'All' tab
  2. Then open 'My Images' and you see numerable bar - bag

**Comment by FrenchBen** [comment]
@qwinmen there's a good chance something else is at work here - Could you share the output of 
`docker image ls` from your CLI?

**Comment by qwinmen** [comment]
hello. My 'docker image ls' 
![default](https://user-images.githubusercontent.com/22964689/37878330-133ebbb8-3070-11e8-99ee-035f03ed829a.png)
but it is  a not be intrested. Look, if you open 'All' tab, input into search field something (for example 'po'), scroll down and see a numeric bar, ok? Good, then you need click to 'My Images' tab, and see this bug :)
![default](https://user-images.githubusercontent.com/22964689/37878417-c59c1a2a-3071-11e8-9b2a-f3d4f6473ec7.png)
I'm sorry about my english)))

**Comment by FrenchBen** [comment]
@qwinmen no problem - Thanks for the report. I could use help patching this, are you interested?

**Comment by qwinmen** [comment]
yes, good idea, interested to me. How can i help?

**Comment by FrenchBen** [comment]
@qwinmen Checkout a copy of the repo, and see if you can figure out why this is happening 👍
