### ISSUE TITLE
Fail to install openchain/server from Kitematic on macOS High-Sierra

### ISSUE THREAD

**Issue by cunnois** [docker/kitematic#3685]
### Expected behavior
openchain/server installs successfully
### Actual behavior
Fail with error '(HTTP code 404) unexpected - manifest for openchain/server:latest not found'
### Steps to reproduce the behavior

  1. Search Openchain from Kitematic
  2. Install
  3. Fail

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/openchain/server/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
