### ISSUE TITLE
 TLS handshake timeout

### ISSUE THREAD

**Issue by EllusionLee** [docker/kitematic#3690]
### Steps to reproduce the behavior

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/47/4760dc956b2ddc9ac1c508936e39b63a22c6f0640ef58c1b10ff73f04e253ffe/data?Expires=1522092354&Signature=U2osNB7KY4uKlmySBiPtMbnRd1pz-M9jcpNk1z0bv11Ey5-4hVXkF39fZKWyXVfTEoYf6~4ElfpOMIuUDKoFygn-oo2gp-uEtEQxCqFAgJvXzI7vA4p-qbivHE2GP71wrx9Ff4KjCN2hDopHqA8kstnHzktnSdW2I4gxJltCAFk_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

I would recommend you upgrade to Docker for Mac/Windows, which natively prevents any of the above tricks.
