### ISSUE TITLE
Failed to download

### ISSUE THREAD

**Issue by Devyang** [docker/kitematic#3702]
### Actual behavior
docker pull dtagdevsec/suricata
Using default tag: latest
Error response from daemon: manifest for dtagdevsec/suricata:latest not found

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/dtagdevsec/suricata/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
