### ISSUE TITLE
Focus downloaded file in explorer after saving logs for container

### ISSUE THREAD

**Issue by collin5** [docker/kitematic#3704]
### Expected behavior
For better UX, it would be better if the file is focused in File Explorer once save is successful.
Or a button for _**"Show in Folder"**_ can be added to the save successful dialog

### Actual behavior
Currently, a dialog shows up with logs have been successfully saved

<img width="486" alt="screen shot 2018-03-29 at 18 35 59" src="https://user-images.githubusercontent.com/11579108/38098223-1c3bf3f8-3380-11e8-8fe9-f7182b05a189.png">

### Steps to reproduce the behavior

  1. Go to the container.
  2. And click the button to save logs.

**Comment by FrenchBen** [comment]
@collin5 Do you think this would be something you could pick up?

**Comment by collin5** [comment]
@FrenchBen  💯 Yeah. I can pick this up

**Comment by FrenchBen** [comment]
Closed in #3708 Thanks @collin5 for the help! 👍

**Comment by collin5** [comment]
@FrenchBen Ur welcome. Thanks
