### ISSUE TITLE
Docker Disk Space Error

### ISSUE THREAD

**Issue by alisajjad** [docker/kitematic#3709]
OS: Mac OS X High Sierra 10.13.4
Docker Version Version 18.03.0-ce-mac60 (23751)
While adding Jenkins 
https://hub.docker.com/r/cloudbees/jenkins-enterprise/
Came across this error

write /var/lib/docker/tmp/GetImageBlob245505453: no space left on device

**Comment by FrenchBen** [comment]
By default we create a small disk, to make sure that it will fit on most developer laptop. However, you can actually create your own disk by following these instructions:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space

You can also cleanup existing disk space, via `docker system prune`

**Comment by alisajjad** [comment]
Hi Ben
           Appreciate your help and guidance, I am using native hypervisor rather than VB and could not find hoe to raise the disk size, did from Kitematic front end and it raised Docker.raw size at "" /Users/sajjadali/Library/Containers/com.docker.docker/Data/vms/0 "" copying Diagnostic ID
**D1B1A7FC-1A86-4BED-AAFD-348C11B8B710**
Thanks in advance for your help
Best Regards

**Comment by HarrisHan** [comment]
Hello @FrenchBen when I call `docker-machine -D create -d virtualbox --virtualbox-disk-size "100000" default`

I got the blow & still receive the 
`echo: write error: No space left on device`

Docker Machine Version:  0.12.2, build 9371605
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:61676
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:61680
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
Host already exists: "default"
