### ISSUE TITLE
manifest for daqyzete/datastage-9-1-2:latest not found

### ISSUE THREAD

**Issue by PraveenKS30** [docker/kitematic#3711]
I am trying to pull datastage 9.1 version but getting below issue:

$ docker pull daqyzete/datastage-9-1-2
Using default tag: latest
Error response from daemon: manifest for daqyzete/datastage-9-1-2:latest not found

Please suggest how to resolve it.

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/daqyzete/datastage-9-1-2/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
