### ISSUE TITLE
I want creat galaxy-rnacommender

### ISSUE THREAD

**Issue by peishimei** [docker/kitematic#3714]
### Information about the Issue
I want to download galaxy-rnacommender from Docker (Kinematic),but there exists an error 

### Steps to reproduce the behavior

  1. I have registered in Docker in website with my mailbox
  2. I search the galaxy-rnacommender and click the "creat "key, But with an error
 error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/dd/dd1f25445b045556e41d311e76cfef562c197b092711af6cdb6cff5d18598aab/data?Expires=1522684207&Signature=FUDoAswuhbjblWHVnpeTfTcSkt8Rb8uAOVegrlswFlOBy79V7wQ4H-hU-NdsdRxSw4NoAwH8ooGI8lbvssbmpmUI4-P4t9RKWgPB6xQAek1w7GHda4v2z7vOtfsyTxIt26x6CwLXWZkwMRDVrm641BlPebo4J9J70DCdB5QOVnw_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

what can I do now?

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as Google DNS.

Timeout usually means that communication was interrupted, which is often linked to Docker images that are quite large.
