### ISSUE TITLE
HTTP code 404

### ISSUE THREAD

**Issue by jgunvaldson** [docker/kitematic#3716]
### Expected behavior
(HTTP code 404) unexpected - {"message":"manifest for jgunvaldson/core-audit-service:latest not found"}
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for jgunvaldson/core-audit-service:latest not found"}
### Information about the Issue
(HTTP code 404) unexpected - {"message":"manifest for jgunvaldson/core-audit-service:latest not found"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/jgunvaldson/core-audit-service/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
