### ISSUE TITLE
Unable to download the centos image to windows 10

### ISSUE THREAD

**Issue by bsmurali** [docker/kitematic#3721]
### Steps to reproduce the behavior

  1. ...open kinematic

  2. ...select centos container
3. click download
4. no matching manifest for windows/amd64 in the manifest list entries

**Comment by FrenchBen** [comment]
This is a Linux Container image only - Please see the documentation for this image and the requirements. 
To learn more about Windows Containers, please see this post: 
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Additionally, if you're running Docker for Windows, you can switch to using linux/windows containers:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
