### ISSUE TITLE
(HTTP code 404) no such image - no such image: homme/openstreetmap-tiles:latest: No such image: homme/openstreetmap-tiles:latest

### ISSUE THREAD

**Issue by karanjarich** [docker/kitematic#3722]
Am trying to download openstream map tiles unfornately after sometimes i receive an error as follows
  
   (HTTP code 404) no such image - no such image: homme/openstreetmap-tiles:latest: No such image: homme/openstreetmap-tiles:latest

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/homme/openstreetmap-tiles/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by karanjarich** [comment]
thanks i managed to overcome the issue
