### ISSUE TITLE
ERROR when dowload tensor-android of jandavis

### ISSUE THREAD

**Issue by damminhtien** [docker/kitematic#3724]
I try to download this image but get:
(HTTP code 404) unexpected - manifest for danjarvis/tensorflow-android:latest not found

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/danjarvis/tensorflow-android/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
