### ISSUE TITLE
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Conflict. The container name "/composer-playground" is already in use by container "79aae4ff070ef1208e4857cd50c9468461269df07faf7694099edbe3aa7351a7". You have to remove (or rename) that container to be able to reuse that name. 

### ISSUE THREAD

**Issue by kkumarv** [docker/kitematic#3737]
### Steps to reproduce the behavior

  1. ... Hi , Not able to run the composer playground using docker CLI
  2. ... getting the error as 
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Conflict. The container name "/composer-playground" is already in use by container "79aae4ff070ef1208e4857cd50c9468461269df07faf7694099edbe3aa7351a7". You have to remove (or rename) that container to be able to reuse that name.
Se

**Comment by FrenchBen** [comment]
`The container name "/composer-playground" is already in use by container `
Sounds like you already have it running - Remove any old containers that have the same name, and run it again.
