### ISSUE TITLE
Add option to select zsh in 'exec command shell'

### ISSUE THREAD

**Issue by ssx** [docker/kitematic#3739]
### Expected behavior
Ability to select Zsh from select box.

### Actual behavior
Zsh isn't present.

### Information about the Issue
N/A

### Steps to reproduce the behavior

  1. Click select box for shells.
  2. Feel disappointment.

**Comment by FrenchBen** [comment]
@ssx Could you provide me with a couple container image examples that have zsh?

**Comment by ssx** [comment]
Hi @FrenchBen!

That's a very good question. 

It would have been most useful when using 'Docker CLI' feature, I'll have a look and see if there any containers, I can build one if not.

**Comment by FrenchBen** [comment]
@ssx the point of this question is that providing you with a `zsh` option to use within a container, when no image have `zsh` baked in is a bit pointless.

**Comment by ssx** [comment]
That's quite a valid point!
