### ISSUE TITLE
Can "docker exec" button in Kitematic use another shell client rather than powershell under windows?

### ISSUE THREAD

**Issue by CC-Hsu** [docker/kitematic#3745]
Hi,

Currently Kitematic opens powershell as terminal for a container in Windows.

But the user experience varies from Win7 to Win10, depending on the version of powershell.

Maybe Kitematic can bind a unified terminal emulator such as [Mintty](https://mintty.github.io/) for Windows.

Or is it possible to add a new option for user to locate their terminal emulator in App Settings, so that users can choose their favorite one (Even under Ubuntu Desktop)?

Finally thanks for such a cute GUI for docker personal users.

**Comment by FrenchBen** [comment]
Powershell is the default in all Windows containers. It seems that you're referring to the actual terminal that is being opened?
If this, this request should be in the github.com/docker/toolbox repository.

**Comment by CC-Hsu** [comment]
Hi, 

Thanks for reply.

What I meant is the shell opened by "DOCKER CLI" in Kitematic:
![image](https://user-images.githubusercontent.com/8018872/38763183-b5d8fcfa-3fc8-11e8-98e8-ef8a647b66ad.png)

And the "EXEC" button for a running container:
![image](https://user-images.githubusercontent.com/8018872/38763220-4ea02ed6-3fc9-11e8-8b5c-a3874f295dd8.png)

Rather than "Docker Quickstart Terminal" as you mentioned.

Is it possible to enhance Kitematic to open these two shell prompts using other terminal emulators rather than default powershell?

**Comment by FrenchBen** [comment]
The Docker CLI is the quickstart and the only one that would use the native shell env. When you exec into a container you are limited to the shell that the container has.

**Comment by CC-Hsu** [comment]
Thanks for your clarification.

However, Is it possible for user to choose terminal emulator window (Not the shell environment) for these shell cli?

I mean, currently when opening a terminal (Docker CLI or exec) the following window is opened,
![image](https://user-images.githubusercontent.com/8018872/38763674-fa9b408c-3fd2-11e8-9f65-cc2d8803eef9.png)

And I hope to choose other window, for instance, mintty used in Cygwin,
![image](https://user-images.githubusercontent.com/8018872/38763688-6ed6304c-3fd3-11e8-8a36-b3c309ce7e30.png)

I think it would be good if Kitematic can open [other command prompt window applications in Windows](https://www.technig.com/command-prompt-alternatives-windows/).

**Comment by shijunti19** [comment]
![image](https://user-images.githubusercontent.com/5392211/46987511-10c3d780-d127-11e8-9e88-f6e709f0f4ed.png)

![image](https://user-images.githubusercontent.com/5392211/46987502-07d30600-d127-11e8-8c20-1e0320862f74.png)

**Comment by alex-pravdin-springernature** [comment]
No changes yet? In our company, PowerShell is disabled on workstations by domain policies. Can't run a docker shell at all in Kitematic. Thanks to the built-in docker UI which now contains a similar button and runs CMD shell without any issues. Time to delete Kitematic?

**Comment by SergioSuarezGil** [comment]
+1 i want to use cmder or cygwin
