### ISSUE TITLE
kitematic parse the wrong docker images

### ISSUE THREAD

**Issue by xsank** [docker/kitematic#3752]
registry.cn-hangzhou.aliyuncs.com/xsank/tianchi_server_mesh:0.0.0
### Expected behavior
the docker image should be tianchi_server_mesh

### Actual behavior
![image](https://user-images.githubusercontent.com/1661334/38776639-ce7c1968-40cc-11e8-8ce7-1a0cac500fce.png)

### Information about the Issue
the point is that i cannot modity the wrong image name, so alway create failed...
### Steps to reproduce the behavior

  1. build local images with name url/path1/path2:tag
  2. docker push
  3. then use kitematic to find

**Comment by FrenchBen** [comment]
There's an existing issue around using registries other than hub; this causes the images to have a much longer name that can be tricky to parse. 
If you're incline to do so, feel free to submit a PR that will get this fixed :) 
Closing in favor of older issue

**Comment by pli2014** [comment]
got it. trickly issue of longer name..
