### ISSUE TITLE
Not able to download kali linux docker image from kitematic

### ISSUE THREAD

**Issue by hearsid** [docker/kitematic#3753]
### Expected behavior
Should download the image from kitematic

### Actual behavior
It is giving this error,
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/kalilinux/kali-linux-docker/manifests/latest: Get https://auth.docker.io/token?account=hearsid&scope=repository%3Akalilinux%2Fkali-linux-docker%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 10.0.2.3:53: read udp 10.0.2.15:59854->10.0.2.3:53: i/o timeout"}

### Steps to reproduce the behavior
Go to kitematic on a macbook and try to download kali linux docker

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as CloudFlare DNS `1.1.1.1`
https://blog.cloudflare.com/announcing-1111/
