### ISSUE TITLE
code 500

### ISSUE THREAD

**Issue by ndjurovic** [docker/kitematic#3754]
### Actual behavior

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as CloudFlare DNS `1.1.1.1`
https://blog.cloudflare.com/announcing-1111/
