### ISSUE TITLE
failed to register layer: re-exec error: exit status 1

### ISSUE THREAD

**Issue by KhalilAbdo** [docker/kitematic#3758]
### Steps to reproduce the behavior

  1. ... select OOCE via kitematic
  2. ... error generated at end of process

**Comment by FrenchBen** [comment]
Can you reproduce this with `docker pull ....`  and provide us with the details here?

**Comment by KhalilAbdo** [comment]
Hello Ben,
I just ran a Docker pull on hpoo/ooce and received the following error during the installation - failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\f077330e1f81a27da063041699badc2273f840891d73cb6d5be6fe38ea3029d4: The system cannot find the path specified.

Thanks,

**Comment by FrenchBen** [comment]
Looks like your Docker for Windows installation is broken - Could you open up an issue with the team here:
https://github.com/docker/for-win/issues
