### ISSUE TITLE
Allow mounting custom volume directories

### ISSUE THREAD

**Issue by jeffdm** [docker/kitematic#376]
Right now only volumes defined in `Dockerfiles` can be host-mounted via Kitematic. Users should have a way to host-mount into arbitrary folders in the container.

**Comment by kematzy** [comment]
+100

Also, some kind of documentation on how to convert a great docker container into a fully supported Kitematic container with custom volume addition, logs and previews would be great too.

**Comment by jeffdm** [comment]
@kematzy great! Thanks for the note!

**Comment by gregorydickson** [comment]
+1

**Comment by bauschan** [comment]
+1

**Comment by Blux** [comment]
+1

**Comment by jb510** [comment]
+1000 on @kematzy's  "documentation on how to convert a great docker container into a fully supported Kitematic container with custom volume addition, logs and previews would be great too"

I've been banging my head into a lot of glass doors today trying to figure that out on my own.  

The only container that seems to work with mounted volumes is kitematic/hello-world-nginx and I can't even find the source and how how it does it.  

Every other container with volumes breaks as soon as I enable them.

**Comment by jeffdm** [comment]
@jb510 really sorry to hear that! It's mostly from the Dockerfile. The summary:

Volumes: Make sure there's a `VOLUME` directive in the Dockerfile
Ports: Make sure there's an `EXPOSE` directive in the Dockerfile
Environment variables:  Use `ENV` directives in the Dockerfile

 and we'll post a doc article on the website (kitematic.com/docs) soon

**Comment by jb510** [comment]
@jeffdm Oh goodness don't be sorry! Kitematic is freaking amazing...  All sorts of possibilities are swirling through my head.  

One question.  Where do I find the Dockerfile for kitematic/hello-world-nginx ? I'd like to read/understand it and I can't find it.

**Comment by jeffdm** [comment]
@jb510 here https://github.com/kitematic/html although we had to squash the image for faster download.

@mchiang0610 it may be a good idea to make this an automated build instead for the Dockerfile reference

**Comment by jb510** [comment]
TY!  Exactly what I was looking for!

**Comment by ajermakovics** [comment]
+1

**Comment by nym** [comment]
+1

**Comment by mchiang0610** [comment]
This is definitely something that should be on the roadmap for Kitematic. Is anyone willing to help us work on this as we prioritize on the Windows version of Kitematic in the meantime? @kematzy @ajermakovics @jb510 @nym 

Would love to hear thoughts on how it should be implemented.

**Comment by alexj** [comment]
Not to pile on, but I'll add a +1. I've been excited to try Docker via Kitematic, but not being able to define a volume is a hard blocker for me. I've banged my head a few times now trying to set up various Wordpress containers, but couldn't find where the files could be edited. Luckily, I found this thread. I'm excited about Kitematic, as I think I could use it to ease how I work on side projects (PHP, Python, and eventually Node). 

Sadly, I don't think there's much I can contribute to move this forward, outside of explaining my expectations as a user:

* When I load a new container, it would ideally have a volume set up with access to that container's filesystem.
* For specific containers, like one devoted to WordPress, I'd love it if Kitematic provided an easy way to go straight to that software's directory root 
* I want to be able to change the Volume's mapping of the Docker Folder - > Mac Folder, as I can with  hello-world-nginx. I should be able to do this whether or not the creator of the Creator specifically enabled it.

I'm new to Docker, so I may be asking for too much, but I thought it worth documenting.

Thanks, and keep up the great work!

**Comment by zedtux** [comment]
+1111 !

**Comment by zedtux** [comment]
I have a first version of this feature working (adding new volume, setting the folder, see the volume in the container and read/write files from container and from host).

There are still some updates to do especially when removing volumes.

It doesn't really make sense I'm publishing my code for now as I'm branching from my Linux fork. As soon as done, in the case the Linux portage is not merged I will do another branch originating from master and test on OSX.

**Comment by zedtux** [comment]
I have solved the refresh issue with the LOCAL FOLDER when using 'CHANGE' and 'REMOVE' buttons.

**Comment by affogato** [comment]
Why is this not possible with some containers e.g. Tomcat ?

**Comment by pik0** [comment]
How do I add a volume in the Configure Volumes panel? I've downloaded the nginx:latest (not hello world) and the panel shows the mount, but no plus (+). Maybe the docker file is read only or is there some other setting I need to do to to make changes?

Also, where are the docker files stored that I might be able to start making my own. 

Sorry for the RTFM questions, but I can't seem to find anything more than basic documentation online...

**Comment by zedtux** [comment]
@affogato sorry .. what ?

@pik0 have you cloned my repository and then checked out the branch `linux/features/add-volumes` (BTW are you running Kitematic on Linux as the Linux portage is not yet in master and I need to use it in order to contribute to the project so my branch is Linux only for now ...)

**Comment by zedtux** [comment]
I have opened a pull request with the final implementation. All the details are in the pull request and the pull request has been done without the Linux support so that you can test it @jeffdm, @kematzy, @gregorydickson, @bauschan, @Blux, @jb510, @ajermakovics, @nym, @mchiang0610, @alexj, @affogato and @pik0.

Feel free to send me your feedbacks ! :)

**Comment by affogato** [comment]
@zedtux To elaborate, for most of the containers that I want to use in Kitematic (e.g. official Rails, official Tomcat), it is not possible to set the Volumes or Ports parameters in the Settings tabs. 
It is easy to set them on the command line with boot2docker, but I'd much rather use Kitematic.

**Comment by zedtux** [comment]
Sorry @affogato, what do you mean ?

Using my fork allows you to add/remove Volumes (not ports but it the next thing I'll do). Now regarding the easy way of doing it, just tell me your idea if you have one and I can change the code ;)

**Comment by jeffdm** [comment]
Fantastic! Sorry for the radio silence. Will take a look at the PR after Linux support.

**Comment by pik0** [comment]
I'm using Kitematic on Mac OS Yosemite. Will the container auto update? Or do I need to add it anew to get the latest Dockerfile?

**Comment by zedtux** [comment]
@pik0 you don't need to update anything. Until this code is merge in the Git official repository, you have to clone my repository using `git` and then `checkout` the branch `features/volumes-management`. Here running `make` and `npm start` should make Kitematic popping up with the editable Volumes.

**Comment by pik0** [comment]
Okay, i’ll give that a shot. Fortunately, we’re still in the evaluation phase for Docker so it’s not (yet) mission critical… :)

Pik0

**Comment by ericelliott** [comment]
+1

**Comment by Manfred73** [comment]
I have a mongodb container created with kitematic. It sets the ports and access url which I can use to access it, but the volume is not set. When I change the volume to a location under my user directory, the port and access url disappear.

**Comment by marcelorodrigo** [comment]
+1, please

**Comment by jonjack** [comment]
I can successfully mount a volume when running a container:-

```
docker run -d -p 80:80 -v /Users/me/Documents/Kitematic/nginx/html:/app/nginx/html jonjack/alpinginx
```

Whatever is in `/Users/me/Documents/Kitematic/nginx/html` is successfully served by Nginx in my container.

The mount point has to be under /Users/[user]/Documents/Kitematic/ for this to work though.

If I attempt to modify the path in Kitematic then the continer not only gets stopped but also removed.

Also, I cannot have modifications in the host path show up in the continer without first trashing the documents and replacing them with the updated ones.

---
Im on:-

OSX Yosemite
Kitematic 0.8.5
Docker Engine 1.8.2
Docker Machine 0.4.1

**Comment by zedtux** [comment]
@marcelorodrigo as soon as my [Pull Request for the Linux support](https://github.com/kitematic/kitematic/pull/696) is merged, I will refresh this PR and update it.

**Comment by marcelorodrigo** [comment]
@zedtux great work ;)

**Comment by RVN-BR** [comment]
Any idea why th PRs from Jun still havent made there way in?  Adding custom mountpoints should be a natural thing IMO.... just like it isnt limited when running docker CLI, I dont see why it should me limited in Kitematic?

**Comment by zedtux** [comment]
@RVN-BR basically I'm finishing first my PR on the linux support then I'll finish this PR. It shouldn't be too much to do to finish it so it should be merged very soon

**Comment by FrenchBen** [comment]
@zedtux There's a similar PR in place, which seems to also remove some of the Virtualbox quirkiness available here: https://github.com/docker/kitematic/pull/1202

Just a thought.

**Comment by tiptronic** [comment]
Any news on this?

**Comment by zedtux** [comment]
I tried to merge master but the code changed too much, especially the usage of props instread of state break completely my code.
I tried anyway to make it working quickly but it will take some time ... It's always the same story when waiting before to merge PR :-)
Code is moving too fast.

Anyway, I'll do my best to get back on track with this feature.

**Comment by tiptronic** [comment]
That would be great!  This would make Kitematic 100x more useful than it is already!

**Comment by FrenchBen** [comment]
As mentioned before, there's a different PR now open for this, see: https://github.com/docker/kitematic/issues/376#issuecomment-159430473

@zedtux's PR was closed in favor of 1202

**Comment by tiptronic** [comment]
Hm... if I'm not mistaken, I'm on #376  ;)

**Comment by FrenchBen** [comment]
Yup just mentioning that the proper PR for this feature was provided in the comment as linked :)

**Comment by tiptronic** [comment]
Ah - ok... didn't get it, since there was no link to 1202 (and I just clicked the link) ;)

**Comment by syardumi** [comment]
I built @alexandrev's PR for issue 1202 on his branch pr-1192, but I didn't see the functionality mentioned in this issue. Will he be including the custom dirs (add/remove/etc.) in this PR?

**Comment by alexandrev** [comment]
The code of this PR is here: https://github.com/docker/kitematic/pull/1202 and you can see that other people could build and test the code. If you have any troubles trying to get it built, please, let me know

**Comment by syardumi** [comment]
Thanks Alex. I did find the code and built it with no problems. But, I don't see the add/remove custom volumes feature in it. Am I missing something?

**Comment by alexandrev** [comment]
No, you cannot add a new volume, you can map a volume to a custom folder.

**Comment by syardumi** [comment]
@zedtux Is it OK if I take over on this issue? I should be able to adapt your code fairly easily.

All - this issue request is very different than issue #1202

**Comment by zedtux** [comment]
@syardumi I haven't finished my PR as @FrenchBen [selected another one](https://github.com/docker/kitematic/pull/722#issuecomment-172627621) which was apparently covering the need, otherwise I would have completed it.

Now if, as you previously said, it's not really the same, you can take over of course, but it's then too bad for me :)

**Comment by syardumi** [comment]
Yea, and that PR has been closed in favor of 1202 also, but the functionality talked about in both this one and 722 are not included. @zedtux don't let me stop you from completing this request. My intention was not to take away a project you enjoy. I simply downloaded Kitematic, saw the feature missing - that would put Kitematic on par with Tutum for this feature - and decided to investigate. That lead me to here and to 1202 and now to 722 before noticing that it all got lost in the shuffle. Thanks for all your hard work you've done to get it started too!

**Comment by zedtux** [comment]
Thank you @syardumi. I'm quite busy on other stuff so you can take my work and make it working with the current master if you'd like to.

**Comment by alexandrev** [comment]
Could you explain or even drafted the feature that you are missing? How
should it work? A way to add or remove more volumes than the ones specified
on the dockerfile? Previous the first time you create the container or in
the container settings for new configurations?

We can add it to the PR 1202 so you don't miss anything but I need to know
exactly the requirements to deliver it.

Thanks in advance.

**Comment by syardumi** [comment]
Alex, the idea would be to customize any and all mount points after the container is added to Docker. That said, I worked out a possible solution already via this branch: https://github.com/syardumi/kitematic/tree/PR-376

It's not exactly like @zedtux 's solution, but it's pretty close.

**Comment by alexandrev** [comment]
Ok, if you like I could take a look and try it to merge it with the current
version of pull request 1202

**Comment by syardumi** [comment]
Yea, please do. However, I've only tested on Mac OS X and not extensively, so know that it may need some cleaning up.

**Comment by neeoon** [comment]
+1

**Comment by chenasraf** [comment]
+1. Any news on this?

**Comment by syardumi** [comment]
@alexandrev did you ever merge my branch into PR 1202?

**Comment by ShashankaNataraj** [comment]
OK, I just went to the volumes tab under settings and dont see a plus / add button. Not sure why this is in the downloadable version if it isnt functional yet...

**Comment by FrenchBen** [comment]
@ShashankaNataraj because the developers that helped work on this issue have yet to rebase their code. 
Feel free to help them out.

**Comment by karneaud** [comment]
+1000

**Comment by campbx** [comment]
@syardumi Excellent solution!

@alexandrev Alex, please merge his solution in #1202  - this is a very important feature that lot of people are craving for.

**Comment by jbownzino** [comment]
+1

**Comment by karneaud** [comment]
you guys should take a look at docker-sync

**Comment by FrenchBen** [comment]
@karneaud this has been done in Docker for Mac/Windows.

**Comment by midlettuce** [comment]
can't add volumes, still.

starting up with -v will create a volume which is half editable in current UI.

docker run -v [local_folder]:[remote_folder] -p 8888:8888 [image]

**Comment by FrenchBen** [comment]
@midlettuce feel free to open up an issue with the image owner for not exposing the proper volumes.

**Comment by raphaklaus** [comment]
In 0.12.0 this issue seems to be not implemented under Windows.

**Comment by jamesmanning** [comment]
@FrenchBen WRT "this has been done in Docker for Mac/Windows." does "this" mean Kitematic should allow adding volumes to containers even for volumes not defined in the Dockerfile?  I installed Docker for Windows 2.0.7135 on October 12 (Kitematic/version says v0.35.4) but don't see any UI under Settings -> Volumes for adding a volume.  Am I looking in the wrong place?

Thanks!

**Comment by bartclaeys** [comment]
Still not solved in 2018?

**Comment by M1kep** [comment]
I'm unsure how this is a closed issue? This still does not appear to be supported on linux at least
