### ISSUE TITLE
Docker Image not available 

### ISSUE THREAD

**Issue by suliman317** [docker/kitematic#3763]
### Expected behavior
Hello, I think the docker image is not available 

### Error when trying to do a  'docker pull netdisco/netdisco'

(HTTP code 404) unexpected - {"message":"manifest for netdisco/netdisco:latest not found"}

### Steps to reproduce the behavior

  1. ... 
  2. ...

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/netdisco/netdisco/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged
