### ISSUE TITLE
Missing container for homeassistant's raspberrypi3

### ISSUE THREAD

**Issue by pschatz** [docker/kitematic#3766]
### Information about the Issue
(HTTP code 404) unexpected - {"message":"manifest for homeassistant/raspberrypi3-homeassistant:latest not found"}

### Steps to reproduce the behavior

  1. query for the container in kitematic and select create
  2. or, run the pull command specified by the author "docker pull homeassistant/raspberrypi3-homeassistant"

**Comment by FrenchBen** [comment]
1. Go to https://hub.docker.com/r/homeassistant/raspberrypi3-homeassistant/tags/
2. Observe no latest tags were created for that image
3. Select a different tag in Kitematic (if one exists)
4. 🎉  enjoy container running.

Ideally you open an issue with the repo owner to let them know how frustrating it is that they don't have a latest image tagged

**Comment by pschatz** [comment]
Thanks for the quick reply.
