### ISSUE TITLE
Suggestion: Call VM 'kitematic' instead of 'dev'

### ISSUE THREAD

**Issue by nathanleclaire** [docker/kitematic#377]
https://github.com/kitematic/kitematic/blob/615206af1a2044cfe7d057c9e22dc8fec8523e66/src/DockerMachine.js#L8

cc @jeffdm @Elesant 

`dev` is a pretty common name for `docker-machine` VMs and is not very descriptive in terms of what is it or where it came from.  I highly recommend changing the name to something like "kitematic" so users don't get confused, accidentally remove it, etc.

**Comment by ankushagarwal** [comment]
+100
Bonus points for naming it `kitematic-<version>`

**Comment by mchiang0610** [comment]
@nathanleclaire @ankushagarwal We need to be careful about existing users using the ```dev``` VM name. 

For Windows we will launch with a "kitematic" name - still open to suggestions.

**Comment by gschrader** [comment]
From using Kitematic on macosx, I was surprised when I installed the Windows version that it created a new 'kitematic' vm instead of using my pre-existing "dev" vm.  I assume that can't be changed until https://github.com/kitematic/kitematic/issues/777 is addressed.

**Comment by FrenchBen** [comment]
Vm was migrated to the final name of 'default' - Closing.
