### ISSUE TITLE
Issues downloading containers via Kitematic

### ISSUE THREAD

**Issue by zeff013** [docker/kitematic#3796]
### Expected behavior

Press create button on a new container. It starts to download container to local repository.

### Actual behavior

(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: EOF"}

### Steps to reproduce the behavior

  1. open Kitematic
  2. try creating several new containers, not present in local repository

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as CloudFlare DNS `1.1.1.1`
https://blog.cloudflare.com/announcing-1111/
