### ISSUE TITLE
change upload.ini file of wordpress image using kitematic 

### ISSUE THREAD

**Issue by Hbehboodi** [docker/kitematic#3797]
### Expected behavior
I am using a wordpress image on kitematic and I had done some configuration for my website on that. Now I faced a problem. I need to increase the max upload image size of the wordpress image. I searched and find some result that advice to use a dockerfile to change the upload.ini file. So I need some UI or command options to be able to change the upload.ini file.

### Actual behavior
It seems that I am unable to do this with kitematic images and it seems that even I am not able to change the configurations using command line for my current image in kitematic!! It seems that I should start with a new image and I lost my configurations.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Containers are immutable - If you're trying to change something from the default image, then you'll need to build your own.
