### ISSUE TITLE
No permite configurar los volúmenes de las imagenes de microsoft/mssql-server-linux 

### ISSUE THREAD

**Issue by McPetro** [docker/kitematic#3803]
### Expected behavior
Al configurar la imagen microsoft/mssql-server-linux permita modificar las direcciones de los volumenes de datos

### Actual behavior
No da la opción de configurar los volumenes de datos ni detecta la dirección interna del contenedor

### Information about the Issue
Sucede con todos los tags de las imágenes. Utilizando docker para mac y kitematic (beta)

### Steps to reproduce the behavior

  1.  containers /new 
  2. Select microsoft/mssql-server-linux
  3. settings volumes remains empty .

**Comment by candido1212** [comment]
você deverá criar seu próprio container docker, o container padrão da microsoft, não disponibilizou essa opção

**Comment by McPetro** [comment]
Gracias!!
