### ISSUE TITLE
Cannot download images on windows 10 

### ISSUE THREAD

**Issue by traptisinghal** [docker/kitematic#3804]
### Expected behavior
Should be able to download images from docker hum
### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:57254->192.168.65.1:53: i/o timeout"}
### Steps to reproduce the behaviour
1. Install docker on windows 10 and try downloading an image
.

**Comment by FrenchBen** [comment]
Please make sure that you're on a stable connection and use a solid DNS such as CloudFlare DNS `1.1.1.1`
https://blog.cloudflare.com/announcing-1111/
