### ISSUE TITLE
Unable to login/signup - Desktop app.

### ISSUE THREAD

**Issue by omnsium** [docker/kitematic#3835]
### Expected behavior
Should allow signup or login, else throw error.
### Actual behavior
Input form appears unresponsive(no error or ui feedback) while trying to login/signup.
### Steps to reproduce the behavior

  1. Click on user login option.
  2. Fill in all the input form fields - signup or sign in.
  3. Submit or Login. (stays in the same state - no error or ui feedback)

**Comment by jkears** [comment]
I have the same issue, busy icon spins forever after Log In button pressed

**Comment by ulrich** [comment]
Issue fixed, Kitematic can login to the hub now.

Thank you for your feedback.
