### ISSUE TITLE
(HTTP code 404) unexpected - {"message":"manifest for mobz/elasticsearch-head:latest not found"}

### ISSUE THREAD

**Issue by alexrezen** [docker/kitematic#3967]
### Expected behavior
not 404
### Actual behavior
404
### Steps to reproduce the behavior

  1. ... select docker image
  2. ...run
  3. ...observe fail

**Comment by turtlepod** [comment]
I have the same issue.

**Comment by thaJeztah** [comment]
Looks like that repository does not have a `:latest` tag, so you will have to specify a specific tag to use; here's the steps to do so (steps below are for the offciel `elasticsearch` image, but the steps are similar for the image you're using):

<img width="288" alt="screenshot 2019-02-28 at 11 13 10" src="https://user-images.githubusercontent.com/1804568/53559259-0dffd700-3b4a-11e9-84dc-aca7eadb8266.png">

Click on the `...` button to view the image's details

<img width="289" alt="screenshot 2019-02-28 at 11 13 25" src="https://user-images.githubusercontent.com/1804568/53559322-27088800-3b4a-11e9-91ec-88ca26854d28.png">

Click on the `Selected tag: latest` to open the "tag selection" window

<img width="293" alt="screenshot 2019-02-28 at 11 13 48" src="https://user-images.githubusercontent.com/1804568/53559363-3be51b80-3b4a-11e9-8bd0-c5da16e891cd.png">

Click the tag / version of the image you want to run

<img width="296" alt="screenshot 2019-02-28 at 11 13 57" src="https://user-images.githubusercontent.com/1804568/53559412-51f2dc00-3b4a-11e9-924a-2929fafdcdbb.png">

Click the `(X)` to close the tag selector window

<img width="295" alt="screenshot 2019-02-28 at 11 14 16" src="https://user-images.githubusercontent.com/1804568/53559443-62a35200-3b4a-11e9-8691-57e375a90a7b.png">

Click on the `Create` button to pull the image and start the container
