### ISSUE TITLE
Docker containers not showing in Kitematic

### ISSUE THREAD

**Issue by Tiboonn** [docker/kitematic#4010]
MAC version 10.13.5
Kitematic version 0.17.2

### Expected behavior
My Docker containers should appear in Kitematic.

### Actual behavior
My Docker containers are not appearing in Kitematic.

### Information about the Issue
If I type 'docker ps' in the terminal I see my docker containers running.

I reinstalled Kitematic
Tried restarting the virtual machine manually.
Restarted Docker

I can launch new docker containers from Kitematic with an image.

**Comment by mlh758** [comment]
I've noticed that the container list does not automatically refresh.

Have you tried manually refreshing the container list?

![image](https://user-images.githubusercontent.com/4331955/43325567-9f1aa88c-917c-11e8-9cb9-9c0b076e585d.png)

**Comment by Tiboonn** [comment]
@mlh758 I have tried that also, no luck :(

**Comment by DrGirlfriend** [comment]
I also have the same issue. Mine started once I moved my docker image to a new location, Kitematic could not find it so I moved the Docker image back thinking the path might be hard codes. No luck refreshing/restarting either.

**Comment by mlh758** [comment]
So I just fired up my work laptop this morning and Kitematic was giving me an error. I didn't think to copy and paste it at the time, unfortunately.

Now I'm having this same issue. Kitematic isn't seeing any containers on my system even though I have several running.

**Comment by Tiboonn** [comment]
@mlh758 Hum, strange. Maybe it is because of an update...?
I will try to go back to an older version.

**Comment by Tiboonn** [comment]
I have fixed the problem:

1. Remove kitematic
2. Remove the files from `~/Library/Application\ Support/Kitematic`
3. Remove the VM in VirtualBox BE CAREFULL(NOT sure if this will remove all your docker containers and data)
4. Reinstall Kitemetic
5. Docker containers should appear again

**Comment by smcllc** [comment]
Had the same problem on a Mac today. I still had the Kitematic Beta installed. I had uninstalled by just deleting the .app, and unzipping the current one into Applications. When I pulled an image via CLI, I could not get it to show up. Had to completely uninstall Kitematic and used App Cleaner to get any of the additional files and then reinstalled. Image list shows up correctly.

**Comment by linsongyang** [comment]
The problem caused by Host Network, if any of the containers about to be linked has already been connected to host network, then it's not visible to the other container to be selected to link
