### ISSUE TITLE
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer

### ISSUE THREAD

**Issue by MatterhornProject** [docker/kitematic#4065]
### Expected behavior
launch app
### Information about the Issue
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\62edc4ef59b5671f4f4f12262bb7b5c6349cb8c34aaceaf994c08b2e3ac600c5: system can not find the specified path..

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by MatterhornProject** [comment]
resolved

**Comment by ducttapecoder-vt** [comment]
@MatterhornProject Can you please not do this? Explain how it was resolved. I have a similar error message and would benefit from whatever you discovered.
