### ISSUE TITLE
docker rename CLI command is not reflected in Kitematic

### ISSUE THREAD

**Issue by jeffdm** [docker/kitematic#409]
1. run `docker rename <container> <newname>`
2. Kitematic isn't updated

**Comment by SvenDowideit** [comment]
+1 - just hit it :)

is there a `force refresh', or are you hooking into the `docekr events`?

**Comment by mikaoelitiana** [comment]
Images pulled from cli won't be displayed in kitematic neither

**Comment by FrenchBen** [comment]
Unfortunately there are no events triggered when a rename happens. 
Closing as rename should be done in kitematic
