### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by NormanColoma** [docker/kitematic#4094]
### Expected behavior

After login, loggged in successfully

### Actual behavior

Login page remains hanging after login

### Information about the Issue

Once you click login button, login page remains hanging with the spinning.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pablomirallessoler** [comment]
I have the same problem on mac os

**Comment by ajustlike** [comment]
win7 the same problem

**Comment by mpash** [comment]
I'm getting it as well. I'm able to login via the CLI, and the system tray app, but Kitematic hangs after attemping a login.

**Comment by wesgtr** [comment]
I'm with the same problem, in Windows 10. I have installed right now, and trying to login get this error, but the login data, and still loading forever.
![screen shot 2018-09-11 at 13 48 19](https://user-images.githubusercontent.com/41586568/45374776-7e7d6080-b5c9-11e8-8eb4-3e86631070dc.png)

**Comment by israelpereira** [comment]
Same here, Windows 10 Pro

**Comment by nbortolotti** [comment]
same here, ubuntu 18.04.01 LTS, kitematic 0.17.03

**Comment by jaypozo** [comment]
Same issue, Ubuntu 16.04

**Comment by owen800q** [comment]
I have the same issue on ubuntu 16.04 .....

**Comment by BorisBerlin** [comment]
Same in Win10

**Comment by bhargodevarya** [comment]
Same here as well, windows 7 enterprise

**Comment by Ubaid-Gul** [comment]
No solution is provided anywhere except duplicate duplicate.

**Comment by alexwasner** [comment]
A year old issue with something as important as logging in and there is no solution or update anywhere. Fantastic.

**Comment by timmay54** [comment]
@alexwasner I feel ya. same issue

**Comment by AnthonyFuscoSE** [comment]
Same issue

**Comment by quickware** [comment]
same issue with Kitematic-0.17.8-Windows.zip on windows 10

**Comment by anthony0030** [comment]
Same issue with Kitematic 0.17.6 on OSX

**Comment by manowark** [comment]
Same issue 
- Kitematic 0.17.6
- macOS 10.14.6

**Comment by grimwinoleader** [comment]
Same issue for me too:
- Docker Desktop 2.1.0.3
- Kitematic 0.17.8
- macOS 10

14.6

**Comment by tobarsegais** [comment]
Same issue for me:
Was annoying because Docker insisted I upgrade to the latest version of Kitematic.

- Docker Desktop 2.1.0.3
- Kitematic 0.17.8
- macOS 10.14.6

**Comment by rizkiherda** [comment]
Same here, Windows 10 Pro

**Comment by gwc4github** [comment]
This is still an issue but there is a fix you can get here: https://github.com/docker/kitematic/issues/5308

**Comment by UnMatty** [comment]
same problem on MacOs 10.14.6

**Comment by MySource14** [comment]
Same issue too on win 10 pro.

**Comment by Raizelian** [comment]
Same issue with:
- macOS 10.14.6
- Kitematic 0.17.8
- Docker 2.1.0.3

But I can confirm that this fix works perfectly:
> (https://github.com/docker/kitematic/issues/4094#issuecomment-535612310) This is still an issue but there is a fix you can get here: #5308

**Comment by stephen-turner** [comment]
Thanks for the report. There was a change in the Hub login API code a few days ago, and we accidentally lost a backward compatibility fix. (In fact the one that we put in place when this ticket was first opened in September 2018). If possible, we're looking to re-fix it in Hub, rather than get everyone to download a new Kitematic.

**Comment by 153957** [comment]
@stephen-turner Can you provide a time estimate for when this might be fixed on Docker Hub?

**Comment by ulrich** [comment]
Issue fixed, Kitematic can login to the hub now.

Thank you for your feedback.

**Comment by anthony0030** [comment]
I can confirm it is working for me now and it logged in fast.
