### ISSUE TITLE
Issue with login to docker hub through Kitematic

### ISSUE THREAD

**Issue by tellanad** [docker/kitematic#4098]
### Expected behavior
Has to login to Dokcerhub and Kitematic page has to open
### Actual behavior
Stuck on login screen for couple of hours no result
### Steps to reproduce the behavior

  1. ...
<img width="909" alt="screen shot 2018-09-11 at 1 52 49 pm" src="https://user-images.githubusercontent.com/14303298/45387136-095e5b00-b5ca-11e8-9af5-00e3f2e28c6c.png">

  2. ...

**Comment by ulrich** [comment]
Issue fixed, Kitematic can login to the hub now.

Thank you for your feedback.
