### ISSUE TITLE
Cannot connect to Docker Hub

### ISSUE THREAD

**Issue by stefjoosten** [docker/kitematic#4099]
### Expected behavior
I launched Kitematic (Beta) on my MacBook Pro (High Sierra). I expected I could login into Docker Hub, because I'm on the internet.

### Actual behavior
The login process stalls. I get no message and it lasts for minutes. The only way I could stop the waiting is to quit Kitematic from the MacOS dock.
![afbeelding](https://user-images.githubusercontent.com/275768/45407580-1cc10300-b66a-11e8-8d56-ea105af6447a.png)

### Information about the Issue
Could this be caused by a non-http(s) protocol that is blocked by the company's firewall? I have no clue...

### Steps to reproduce the behavior

  1. ... start Kitematic (beta)
  2. ... push the login button on the top of the Kitematic window.

**Comment by stefjoosten** [comment]
duplicate issue from #4094 (sorry...)

**Comment by Ubaid-Gul** [comment]
@stefjoosten The link you provided there is no solution. people keep saying same problem on windows 7, 10 and mac but no solution is given.
