### ISSUE TITLE
unable to install elastic search image 

### ISSUE THREAD

**Issue by vikramsisodia27** [docker/kitematic#4177]
### Expected behavior
It should create elastic search image
### Actual behavior
(HTTP code 404) unexpected - {"message":"manifest for centerforopenscience/elasticsearch:latest not found"}

### Information about the Issue
(HTTP code 404) unexpected - {"message":"manifest for centerforopenscience/elasticsearch:latest not found"}

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Dupe of #4171.
