### ISSUE TITLE
Kitematic hangs upon doing search - "Loading Images"

### ISSUE THREAD

**Issue by aeftekhari2** [docker/kitematic#4196]
### Expected behavior
I expect it to work or timeout or something...!

### Actual behavior
I tried searching for "dynamodb-local" and the spinner keeps going and it says "Loading Images"

### Information about the Issue
I've seen this problem reported before and it was quickly closed!  Apparently this is a recurring problem with docker and Kitematic.

### Steps to reproduce the behavior

  1. Install and run Kitematic
  2. Search for "dynamodb-local"

**Comment by duncdrum** [comment]
same here bnoth on macOS 10.13.6 and 10.14, this behaviour only started kitematic 0.17.5, 0.17.3 works fine

**Comment by Trexology** [comment]
I guess I'm not alone. The error occurred when trying to search for any Images. Open develop console and found this error

> [Bugsnag] Invalid API key 'undefined'

System:
Kitematic 0.17.5
Mac Mojave 10.14

**Comment by florianorben** [comment]
These seem to be two different issues.
- The loading indicator: My guess is docker's api introduced some kind of rate limiting, making (some of) the multiple concurrent requests fail - leaving the app in a buggy state.
- `[Bugsnag] Invalid API key 'undefined'` -> Bluebird's lib api has changed a bit
The PR should fix those problems

**Comment by techfluent7** [comment]
Same behavior on _**macOS High Sierra Version 10.13.6**_.
Any search on Kitematic window hangs up by saying "Loading Images" 
I searched for 'alpine'
Docker is installed on mac and running.
What is the work around for this ?

<img width="1082" alt="untitled1" src="https://user-images.githubusercontent.com/44531153/47607554-8bc2a300-d9ef-11e8-8e1d-649487975d00.png">

**Comment by costa974** [comment]
+1

**Comment by Sebahemm** [comment]
Same here. Every search gets stuck on "Loading Images".
Windows 10 
Kitematic 0.17.5.0

**Comment by BeepBeepImAJeep** [comment]
now im on a mac. but installing the docker toolbox fixed the issue for me.. it gave me kitematic beta, and it works with search now.

**Comment by edtorba** [comment]
+1

**Comment by AlaxLee** [comment]
+1 with v0.17.5. Downgraded to v0.17.3, seemed to work just fine too ...

**Comment by SergioSuarezDev** [comment]
+1 same on 17.5 with macos Mojave

**Comment by wbecotte** [comment]
Upgraded to Docker **2.0.0.0.-win78 (28905)** which added something to detect outdated kitematic versions, so that causes a problem because for me the 0.17.3 downgrade worked, but now it won't let me run that version and the 0.17.5 version has the same problem anyone encounter this?

**Comment by jmartens** [comment]
@seanli or @jmorganca can you have a look at this? It severly limits functionality and seems to have a patch available through PR #4201.

**Comment by Avonstar** [comment]
> ### Expected behavior
> I expect it to work or timeout or something...!
> 
> ### Actual behavior
> I tried searching for "dynamodb-local" and the spinner keeps going and it says "Loading Images"
> 
> ### Information about the Issue
> I've seen this problem reported before and it was quickly closed! Apparently this is a recurring problem with docker and Kitematic.
> 
> ### Steps to reproduce the behavior
> 1. Install and run Kitematic
> 2. Search for "dynamodb-local"

**Comment by Avonstar** [comment]
Still an issue. Still hangs when searching for images on a Mac. Anybody working on this? I guess I will have to download Docker Toolbox and get the beta version as this appears to work.

**Comment by pepesan** [comment]
Same problem here. 
MacOSX 10.14.1 
Docker for desktop: Version 2.0.0.0-mac81 (29211)
Engine: 18.09.0
Kitematic 0.17.5 not working
Kitematic 0.17.3 working perfectly

**Comment by nilsdebruin** [comment]
Same problem here:
Mac OSX 10.14.1
Docker for desktop: Version 2.0.0.0-mac81 (29211)
Engine: 18.09.0
Kitematic: 0.17.5

Kitematic loading image screen keeps on spinning and returning no results

**Comment by hoegge** [comment]
Also hangs on Windows when searching

**Comment by diegorv** [comment]
0.17.3 downgrade worked

**Comment by knks** [comment]
The latest version 0.17.5 also worked well.

**Comment by leeprincefoxmail** [comment]
+1

**Comment by chrisyouritdept** [comment]
The version 0.17.6 for Windows fixed the issue for me.  By the way it would be nice to have the "version" file in the install root directory updated to the right version as it has 1.8.8.  The version I was running was 10/19/2018 and it would hang during a search.  Thank you for fixing this!

**Comment by losectrl** [comment]
+1
