### ISSUE TITLE
Windows 10 "context canceled" error

### ISSUE THREAD

**Issue by johneboldt** [docker/kitematic#4216]
### Expected behavior
Create a container

### Actual behavior
Receive the following message: We're sorry. There seems to be an error: context canceled

### Steps to reproduce the behavior

  1. Click + NEW
  2. Select hello-world-ngnix
  3. Click CREATE
  4. Receive the error message

**Comment by aarontaycheehsien** [comment]
I have the same problem. Whether selecting ghost, elastic search and hello-world ngnix.

**Comment by johneboldt** [comment]
Just started working - must have been something in my environment. It would be nice to see a more detailed message as to the cause!
