### ISSUE TITLE
Stop / Start VirtualBox VM button

### ISSUE THREAD

**Issue by rberger** [docker/kitematic#426]
It would be nice to have a button or menu item to stop / start the VirtualBox VM. 

I know you can set it so that it stops on Kitematic app closing, but it would be helpful to have a manual way in addition

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by th3m4ri0** [comment]
:+1:

**Comment by razmo** [comment]
+1

**Comment by FrenchBen** [comment]
This is more of a machine management issue, which has been discussed in the wiki. 
To keep the issues clean, I'll refer to the wiki for future improvements. 
https://github.com/docker/kitematic/wiki/Machine-Management
