### ISSUE TITLE
Error :(HTTP code 404) unexpected - manifest for elasticsearch:latest not found

### ISSUE THREAD

**Issue by test2301** [docker/kitematic#4267]
### Expected behavior

While trying to create a new container from kitematic UI for elasticsearch got this 404 error.
Ideally it should create a new container.

### Actual behavior

Got an error 

(HTTP code 404) unexpected - manifest for elasticsearch:latest not found

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Dupe of #4171.
