### ISSUE TITLE
MacOS 0.17.5 not search images

### ISSUE THREAD

**Issue by SergioSuarezDev** [docker/kitematic#4278]
Kitematic MacOS 0.17.5

### Information about the Issue
Can't search images with Kitematic

### Steps to reproduce the behavior
Searching an image, Kitematic stuck

### Screenshot
![captura de pantalla 2018-11-12 a las 12 53 42](https://user-images.githubusercontent.com/3636232/48346038-18b95d80-e67a-11e8-82d9-fd4879c19be2.png)

**Comment by SergioSuarezDev** [comment]
Downgrading to Kitematic to v0.17.3 fixed the problem.
But please fix this issue on v017.5 :=)

**Comment by connermo** [comment]
+1

**Comment by davidbdeath** [comment]
I'm having the same problem, works fine on my QNAP NAS

**Comment by foezor** [comment]
I downgraded my version and now it works fine. Seems like a problem with the last version of kitematic

**Comment by SergioSuarezDev** [comment]
Now is working with  0.17.7

**Comment by SergioSuarezDev** [comment]
issue closed

**Comment by hllinc** [comment]
Now this problem has appeared again in version 0.17.6.

**Comment by SergioSuarezDev** [comment]
> Now this problem has appeared again in version 0.17.6.

what is your so?

**Comment by hllinc** [comment]
> > Now this problem has appeared again in version 0.17.6.
> 
> what is your so?
see this issue:
https://github.com/docker/kitematic/issues/4483
