### ISSUE TITLE
Install elastic search say (HTTP code 404) unexpected - manifest for elasticsearch:latest not found

### ISSUE THREAD

**Issue by marcopgordillo** [docker/kitematic#4302]
### Expected behavior
Have an image of elasticsearch in kitematic for windows
### Actual behavior
I can't download the image of elasticsearch
### Information about the Issue
(HTTP code 404) unexpected - manifest for elasticsearch:latest not found

### Steps to reproduce the behavior

  1. ...Install kitematic for windows 10 with docker
  2. ...install elastic search

**Comment by stephen-turner** [comment]
Dupe of #4171.
