### ISSUE TITLE
Not work with dockerhub images finding, showing, anything.

### ISSUE THREAD

**Issue by edp1096** [docker/kitematic#4306]
Version : Windows 10

* Before 0.17.3 - Work.
* 0.17.5
  - Docker hub search : Not work. Infinite loading image
  - `My Images` completely not Work.

**Comment by hshyk** [comment]
Same here on macOS Mojave (10.14.1). The 0.17.5 version only shows recommended images. You cannot create any of them. It will not search Docker Hub or your local images. The spinner keeps spinning with no results. Using 0.17.3 works fine.

**Comment by hanssens** [comment]
Same here, also on macOS. After upgrading to 0.17.5 search doesn't work at all.

The console debugger shows the following:

![image](https://user-images.githubusercontent.com/493382/48772147-bee11500-ecc3-11e8-8ccb-814fad1a1586.png)

**Comment by alexmanie** [comment]
Same here :(

**Comment by briva** [comment]
same

**Comment by hanssens** [comment]
Lots of discussion about this in issue #4234; I would like to suggest for everyone to follow it up in there (and upvote it there as well).

**Comment by edp1096** [comment]
As https://github.com/docker/kitematic/issues/4234#issuecomment-445447041 , found that the issue was fixed.

Closing.

**Comment by stufim** [comment]
My experience on MS Windows 10 Professional, use Kitematic 0.17.3 and "My Images" works fine.
