### ISSUE TITLE
Kitematic cannot use Docker for Mac as backend

### ISSUE THREAD

**Issue by Chenyao2333** [docker/kitematic#4327]
### Expected behavior

Kitematic use Docker for Mac as backend.

### Actual behavior

It automatically creates a new virtualbox vm.

### Information about the Issue

I have no idea why kitematic can't detect Docker for Mac. Could you provide me some instructions to seek what happends in kitematic?

### Steps to reproduce the behavior

  1. Keep Docker for Mac on running.
  2. Open Kitematic

**Comment by Chenyao2333** [comment]
I solved that just after trying:

~~~
rm -rf ~/Library/Application\ Support/Kitematic
~~~

Maybe some legacy configurations cause kitematic use virtualbox.

**Comment by undancer** [comment]
<img width="1192" alt="kitematic-error" src="https://user-images.githubusercontent.com/431735/49025709-312b8b00-f1d7-11e8-89db-7bc60b667bd3.png">
