### ISSUE TITLE
Mac Mojave fails at the creation of new machines

### ISSUE THREAD

**Issue by iSanchezDev** [docker/kitematic#4375]
I run docker desktop and kitematic from its selector bar. The app starts well.

The installation is clean I got no any virtual machines already created from docker and he virtualBox is working fine. 

After a few seconds Kitematic reports this error:
Command failed: /usr/local/bin/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.16.0, build 702c267f,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:51301,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:51307,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,Reading certificate data from /Users/isanchez/.docker/machine/certs/ca.pem,Decoding PEM data...,Parsing certificate...,Reading certificate data from /Users/isanchez/.docker/machine/certs/cert.pem,Decoding PEM data...,Parsing certificate...,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: /usr/local/bin/VBoxManage --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.2.20r125813,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) Calling .GetConfigRaw,(default) Calling .Create,(default) DBG | Creating disk image...,(default) DBG | Creating 20000 MB hard disk image...,(default) DBG | Writing magic tar header,(default) DBG | Writing SSH key tar header,(default) DBG | Calling inner createDiskImage,(default) DBG | &{/usr/local/bin/VBoxManage [/usr/local/bin/VBoxManage convertfromraw stdin /Users/isanchez/.docker/machine/machines/default/disk.vmdk 20971520000 --format VMDK] [] <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>},(default) DBG | Starting command,(default) DBG | Copying to stdin,(default) DBG | Filling zeroes,(default) DBG | Converting from raw image file="stdin" to file="/Users/isanchez/.docker/machine/machines/default/disk.vmdk"...,(default) DBG | Creating dynamic image with size 20971520000 bytes (20000MB)...,(default) DBG | Closing STDIN,(default) DBG | Waiting on cmd,(default) DBG | COMMAND: /usr/local/bin/VBoxManage createvm --basefolder /Users/isanchez/.docker/machine/machines/default --name default --register,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | Virtual machine 'default' is created and registered.,(default) DBG | UUID: 17430346-ea29-4907-a05f-b9c72a165eae,(default) DBG | Settings file: '/Users/isanchez/.docker/machine/machines/default/default/default.vbox',(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | VM CPUS: 1,(default) DBG | VM Memory: 2048,(default) DBG | COMMAND: /usr/local/bin/VBoxManage modifyvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 2048 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 on --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage modifyvm default --nic1 nat --nictype1 82540EM --cableconnected1 on,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage storagectl default --name SATA --add sata --hostiocache on,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage storageattach default --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/isanchez/.docker/machine/machines/default/boot2docker.iso,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage storageattach default --storagectl SATA --port 1 --device 0 --type hdd --medium /Users/isanchez/.docker/machine/machines/default/disk.vmdk,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage guestproperty set default /VirtualBox/GuestAdd/SharedFolders/MountPrefix /,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage guestproperty set default /VirtualBox/GuestAdd/SharedFolders/MountDir /,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | setting up shareDir '/Users' -> 'Users',(default) DBG | COMMAND: /usr/local/bin/VBoxManage sharedfolder add default --name Users --hostpath /Users --automount,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage setextradata default VBoxInternal2/SharedFoldersEnableSymlinksCreate/Users 1,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | name="default",(default) DBG | groups="/",(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)",(default) DBG | UUID="17430346-ea29-4907-a05f-b9c72a165eae",(default) DBG | CfgFile="/Users/isanchez/.docker/machine/machines/default/default/default.vbox",(default) DBG | SnapFldr="/Users/isanchez/.docker/machine/machines/default/default/Snapshots",(default) DBG | LogFldr="/Users/isanchez/.docker/machine/machines/default/default/Logs",(default) DBG | hardwareuuid="17430346-ea29-4907-a05f-b9c72a165eae",(default) DBG | memory=2048,(default) DBG | pagefusion="off",(default) DBG | vram=8,(default) DBG | cpuexecutioncap=100,(default) DBG | hpet="on",(default) DBG | chipset="piix3",(default) DBG | firmware="BIOS",(default) DBG | cpus=1,(default) DBG | pae="on",(default) DBG | longmode="on",(default) DBG | triplefaultreset="off",(default) DBG | apic="on",(default) DBG | x2apic="off",(default) DBG | cpuid-portability-level=0,(default) DBG | bootmenu="disabled",(default) DBG | boot1="dvd",(default) DBG | boot2="dvd",(default) DBG | boot3="disk",(default) DBG | boot4="none",(default) DBG | acpi="on",(default) DBG | ioapic="on",(default) DBG | biosapic="apic",(default) DBG | biossystemtimeoffset=0,(default) DBG | rtcuseutc="on",(default) DBG | hwvirtex="on",(default) DBG | nestedpaging="on",(default) DBG | largepages="on",(default) DBG | vtxvpid="on",(default) DBG | vtxux="on",(default) DBG | paravirtprovider="default",(default) DBG | effparavirtprovider="kvm",(default) DBG | VMState="poweroff",(default) DBG | VMStateChangeTime="2018-12-11T10:46:45.745000000",(default) DBG | monitorcount=1,(default) DBG | accelerate3d="off",(default) DBG | accelerate2dvideo="off",(default) DBG | teleporterenabled="off",(default) DBG | teleporterport=0,(default) DBG | teleporteraddress="",(default) DBG | teleporterpassword="",(default) DBG | tracing-enabled="off",(default) DBG | tracing-allow-vm-access="off",(default) DBG | tracing-config="",(default) DBG | autostart-enabled="off",(default) DBG | autostart-delay=0,(default) DBG | defaultfrontend="",(default) DBG | storagecontrollername0="SATA",(default) DBG | storagecontrollertype0="IntelAhci",(default) DBG | storagecontrollerinstance0="0",(default) DBG | storagecontrollermaxportcount0="30",(default) DBG | storagecontrollerportcount0="30",(default) DBG | storagecontrollerbootable0="on",(default) DBG | "SATA-0-0"="/Users/isanchez/.docker/machine/machines/default/boot2docker.iso",(default) DBG | "SATA-ImageUUID-0-0"="fdf05eb7-da93-467a-971d-5cb8fc359090",(default) DBG | "SATA-tempeject"="off",(default) DBG | "SATA-IsEjected"="off",(default) DBG | "SATA-1-0"="/Users/isanchez/.docker/machine/machines/default/disk.vmdk",(default) DBG | "SATA-ImageUUID-1-0"="7decd3e3-f610-4d09-9725-22c8bbb34cd5",(default) DBG | "SATA-2-0"="none",(default) DBG | "SATA-3-0"="none",(default) DBG | "SATA-4-0"="none",(default) DBG | "SATA-5-0"="none",(default) DBG | "SATA-6-0"="none",(default) DBG | "SATA-7-0"="none",(default) DBG | "SATA-8-0"="none",(default) DBG | "SATA-9-0"="none",(default) DBG | "SATA-10-0"="none",(default) DBG | "SATA-11-0"="none",(default) DBG | "SATA-12-0"="none",(default) DBG | "SATA-13-0"="none",(default) DBG | "SATA-14-0"="none",(default) DBG | "SATA-15-0"="none",(default) DBG | "SATA-16-0"="none",(default) DBG | "SATA-17-0"="none",(default) DBG | "SATA-18-0"="none",(default) DBG | "SATA-19-0"="none",(default) DBG | "SATA-20-0"="none",(default) DBG | "SATA-21-0"="none",(default) DBG | "SATA-22-0"="none",(default) DBG | "SATA-23-0"="none",(default) DBG | "SATA-24-0"="none",(default) DBG | "SATA-25-0"="none",(default) DBG | "SATA-26-0"="none",(default) DBG | "SATA-27-0"="none",(default) DBG | "SATA-28-0"="none",(default) DBG | "SATA-29-0"="none",(default) DBG | natnet1="nat",(default) DBG | macaddress1="080027B6C483",(default) DBG | cableconnected1="on",(default) DBG | nic1="nat",(default) DBG | nictype1="82540EM",(default) DBG | nicspeed1="0",(default) DBG | mtu="0",(default) DBG | sockSnd="64",(default) DBG | sockRcv="64",(default) DBG | tcpWndSnd="64",(default) DBG | tcpWndRcv="64",(default) DBG | nic2="none",(default) DBG | nic3="none",(default) DBG | nic4="none",(default) DBG | nic5="none",(default) DBG | nic6="none",(default) DBG | nic7="none",(default) DBG | nic8="none",(default) DBG | hidpointing="ps2mouse",(default) DBG | hidkeyboard="ps2kbd",(default) DBG | uart1="off",(default) DBG | uart2="off",(default) DBG | uart3="off",(default) DBG | uart4="off",(default) DBG | lpt1="off",(default) DBG | lpt2="off",(default) DBG | audio="coreaudio",(default) DBG | audio_in="false",(default) DBG | audio_out="false",(default) DBG | clipboard="disabled",(default) DBG | draganddrop="disabled",(default) DBG | vrde="off",(default) DBG | usb="off",(default) DBG | ehci="off",(default) DBG | xhci="off",(default) DBG | SharedFolderNameMachineMapping1="Users",(default) DBG | SharedFolderPathMachineMapping1="/Users",(default) DBG | videocap="off",(default) DBG | videocap_audio="off",(default) DBG | videocapscreens=0,(default) DBG | videocapfile="/Users/isanchez/.docker/machine/machines/default/default/default.webm",(default) DBG | videocapres=1024x768,(default) DBG | videocaprate=512,(default) DBG | videocapfps=25,(default) DBG | videocapopts=,(default) DBG | GuestMemoryBalloon=0,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00,(default) DBG | Not found,(default) DBG | COMMAND: /usr/local/bin/VBoxManage hostonlyif create,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | 0%...,(default) DBG | Progress state: NS_ERROR_FAILURE,(default) DBG | VBoxManage: error: Failed to create the host-only adapter,(default) DBG | VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory,(default) DBG | VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface,(default) DBG | VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue,Opting out of crash reporting.,

When I see the chromium developer tools:

/Applications/Kitematic.app/Contents/Resources/app.asar/utils/DockerMachineUtil.js:256 Error: ENOENT: no such file or directory, open '/Users/isanchez/.docker/machine/machines/default/default/Logs/VBox.log'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
    at Object.virtualBoxLogs (/Applications/Kitematic.app/Contents/Resources/app.asar/utils/DockerMachineUtil.js:254:30)
    at Object._callee4$ (/Applications/Kitematic.app/Contents/Resources/app.asar/utils/SetupUtil.js:464:60)
    at tryCatch (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as throw] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at <anonymous>

**Comment by iSanchezDev** [comment]
I reinstalled everything with VirtualBox 5.2.22 version and I solved this issue

**Comment by iSanchezDev** [comment]
I reinstalled everything with VirtualBox 5.2.22 version and I solved this issue

**Comment by nvfl600d** [comment]
I have the same issue and even reinstalling did not help. Is there any solution?
