### ISSUE TITLE
Specify that the exposed Docker Port is a UDP port.

### ISSUE THREAD

**Issue by vladikoff** [docker/kitematic#438]
The port view in Kitematic does not show if the exposed port is a udp port. (udp port 
example: https://github.com/DataDog/docker-dd-agent/blob/master/Dockerfile#L37)
### Current
![image](https://cloud.githubusercontent.com/assets/128755/7350473/6dc3aaa6-eccd-11e4-9997-29082b297b46.png)
### Expected 
The "Docker Port" column should say something like:
8125(udp)

**Comment by jeffdm** [comment]
@vladikoff Thanks for the issue!

**Comment by vladikoff** [comment]
@jeffdm welcome!

**Comment by giodegas** [comment]
+1

**Comment by FrenchBen** [comment]
Closing as UDP is now fully supported

**Comment by vladikoff** [comment]
Thank You!
