### ISSUE TITLE
Hates Windows

### ISSUE THREAD

**Issue by mpash** [docker/kitematic#4499]
### Expected behavior
For it to work on Windows.

### Actual behavior
Nothing works.

### Information about the Issue
Search is broken in all previous releases to latest.
'context canceled' error when downloading anything.
Said they have fixed this many times before, but either grossly misunderstand what needs to be fixed, or doesn't care.

### Steps to reproduce the behavior

  1. Get off the couch
  2. Download Kitematic for Windows
  3. Bang your head against a wall for hours wondering why the developer doesn't care about Windows users.

**Comment by emulvihill** [comment]
Agreed, this is some serious amateur hour $#@! - context cancelled indeed. People have been telling them this is a problem since October.

**Comment by chenwei791129** [comment]
This problem has been solved by [kitematic v0.17.7](https://github.com/docker/kitematic/releases/tag/v0.17.7)

**Comment by mpash** [comment]
@chenwei791129 wonderful!
