### ISSUE TITLE
Logs don't live stream

### ISSUE THREAD

**Issue by johncokos** [docker/kitematic#452]
The logs seem to be on a polling or delay.  Perhaps this is something native to our application, but we whizz a whole lot of stuff through the log and need to see that pretty much in real time.

Is there a way to hook that log view up to a (near) real time feed or at the least, let the polling interval be configurable?

**Comment by jeffdm** [comment]
@johncokos thanks for the issue!

It _should_ be realtime (we hook directly into the docker log stream).  Does it only update if you switch panes?

**Comment by johncokos** [comment]
Yes, I have to go "Home" or "Settings" and then back to "Logs" to see it update.

What I've been doing is having a shell script in my terminal that runs in a loop to spit out the log from the container instead.  Yucky.

**Comment by jeffdm** [comment]
Indeed. Sorry about that. Trying to reproduce now

**Comment by jeffdm** [comment]
@johncokos this fix is now available in Kitematic 0.5.23

**Comment by jeffdm** [comment]
Reopening, issue still occurs if you stop and start a container

**Comment by FrenchBen** [comment]
logs are now properly streaming in latest release. Closing
