### ISSUE TITLE
Cannot download jenkins:latest container

### ISSUE THREAD

**Issue by oktbabs** [docker/kitematic#4572]
### Information about the Issue
Cannot download jenkins:latest container

### Steps to reproduce the behavior

  1. ...Connection through kitematic
  2. ...

**Comment by oktbabs** [comment]
I logged in through kitematic and it provided me containers to download but I got 
![image](https://user-images.githubusercontent.com/35835776/52325297-6e34aa80-29dc-11e9-8f1a-60e1d83e3876.png)

**Comment by oktbabs** [comment]
![image](https://user-images.githubusercontent.com/35835776/52325332-89071f00-29dc-11e9-86d0-cc9fdfb455d1.png)

**Comment by chm9948** [comment]
but console is possible.

ex) docker pull wordpress
