### ISSUE TITLE
context canceled

### ISSUE THREAD

**Issue by chenwei791129** [docker/kitematic#4586]
### Information about the Issue
**OS:** 
  Windows 10 Pro 1809 (64bit) Build 17763.292

**Docker Desktop:** 
  Version 2.0.0.2 (30215)
  Channel: stable
  Build: 0b030e1
  Container: Linux

**Kitematic:** 
  Version 0.17.6.0

### Steps to reproduce the behavior
  1. When i create any containers using Kitematic always fail, but i used "docker pull" command was successful

**Comment by djaffer** [comment]
It is maybe because of Windows Defender. Turn off the threat and virus protection to see if it helps. If it does then add the Kitematic folder as the exclusion in the Defender settings.

**Comment by chenwei791129** [comment]
> It is maybe because of Windows Defender. Turn off the threat and virus protection to see if it helps. If it does then add the Kitematic folder as the exclusion in the Defender settings.

No, I closed Windows Defender, but the issue is same.

**Comment by chenwei791129** [comment]
This problem has been solved by  [kitematic v0.17.7](https://github.com/docker/kitematic/releases/tag/v0.17.7)
