### ISSUE TITLE
context canceled (code-server)

### ISSUE THREAD

**Issue by milosites** [docker/kitematic#4728]
### Expected behavior
Create a (codercom/code-server) container

### Actual behavior
Error: "context canceled"

### Information about the Issue
Error occurs during "downloading" stage
Windows 10 Pro x64.... up-to-date
Kitematic v0.17.7

Docker:
-Version 2.0.0.3 (31259)
-Channel: stable
-Build: 8858db3
-Engine: 18.09.2
-Notary 0.6.1
-Compose: 1.23.2
-Credential Helpers: 0.6.0
-Machine: 0.16.1
-Kubernetes: v1.10.1

### Steps to reproduce the behavior

  1. Open Kitematic
  2. Search for "codercom/code-server"
  3. Click "Create" button
  4. Fails

**Comment by jbaranski** [comment]
Same problem, same platform and docker version as OP. Trying to spin up redis:latest

![image](https://user-images.githubusercontent.com/10889950/55260885-ee8ac580-523f-11e9-98a7-ab2607d5ceea.png)

**Comment by wishwzp** [comment]
@jbaranski 
Making Kitematic project under the Release of download the latest Release Kitematic fix the Bug
1. Delete just download Kitematic
2. In the Release of the project in Github Kitematic Kitematic download the latest Release
3. Put the new Kitematic in Docker tip location: C: \ Program Files \ Docker \ Kitematic
4. Complete
