### ISSUE TITLE
(HTTP code 500) server error - manifest unknown: manifest unknown ???

### ISSUE THREAD

**Issue by tong12580** [docker/kitematic#4793]
please hlep me!

![image](https://user-images.githubusercontent.com/13707643/56452622-6fcc0880-6365-11e9-97f0-8f56485e4a43.png)

**Comment by thaJeztah** [comment]
Looks like that image doesn't exist on Docker Hub; https://hub.docker.com/_/jokers

The error message indicates that Kitematic tried to pull an image from docker hub, but it wasn't found.

I'm closing this issue, because it doesn't look like a bug, but feel free to continue the conversation
