### ISSUE TITLE
Can't create new containers with Kitematic

### ISSUE THREAD

**Issue by awesomekowski** [docker/kitematic#4804]
### Expected behavior
download a new container 

### Actual behavior
Error message "context canceled"

### Information about the Issue
newest version of Kitematic

### Steps to reproduce the behavior

1. Open Kitematic
2. Containers [+ NEW]
3. select Container and click CREATE
4, Connecting to docker hub
5. Error

**Comment by 1shkelzeni** [comment]
hey, did you solve this, cause I have the same problem

**Comment by awesomekowski** [comment]
> hey, did you solve this, cause I have the same problem

Hey, 

yeah I did solve it!
You have to download an older version of kitematic and open it in the explorer and not via docker.

**Comment by 1shkelzeni** [comment]
What ya mean in the explore, should I open kinematic or what , can you provide more details, please

**Comment by 1shkelzeni** [comment]
I have two Containers working in this, and can not delete the cinematic

**Comment by 1shkelzeni** [comment]
> > hey, did you solve this, cause I have the same problem
> 
> Hey,
> 
> yeah I did solve it!
> You have to download an older version of kitematic and open it in the explorer and not via docker.

Can ya ?
