### ISSUE TITLE
Context canceled when trying to pull an image

### ISSUE THREAD

**Issue by joost00719** [docker/kitematic#4810]
### Expected behavior
Download a docker image

### Actual behavior
Context canceled error

### Information about the Issue
When I try to download a Docker image with Kitematic, it starts a loading screen, and shortly after I get this message
"We're sorry. There seems to be an error:
Context Canceled
If this error is incalid, please file a ticket on our Github repo."

### Steps to reproduce the behavior

1. Install Docker
2. Install Kitematic
3. Try to download a Docker Image. (I tried https://hub.docker.com/r/itzg/minecraft-server for this example)

![image](https://user-images.githubusercontent.com/21021559/56766794-8978b000-67aa-11e9-9da0-71d4d46f197c.png)

**Comment by nuinattapon** [comment]
Yes, I also faced the same issue.

**Comment by nuinattapon** [comment]
I think that someone has a short term fix on this. Pls check https://github.com/docker/kitematic/issues/4509

This problem has been solved by kitematic v0.17.7

I downloaded this version and it works!

**Comment by tihomirjauk** [comment]
Had same issue on windows.
https://github.com/docker/kitematic/releases/tag/v0.17.7
Download, unzip and replace installation folder.
