### ISSUE TITLE
Provide warning when creating container from a base image

### ISSUE THREAD

**Issue by gunjan5** [docker/kitematic#485]
Downloaded official ubuntu docker image, but when I power it on by clicking on power on button it shows powered on (RUNNING) for half a second and then goes back to STOPPED by itself. Same thing with the official CentOS image. Nothing in the logs. No errors.

![image](https://cloud.githubusercontent.com/assets/5966968/7553557/61ebe3c0-f6b3-11e4-93d1-ba438efb1c4d.png)

nginx and django images seem to work fine. Have not done anything special with these images. Fresh install. Tried rebooting the VM. Works fine with boot2docker CLI.

Kitematic version 0.5.25, OS X 10.9.5, also tried it on a friend's OS X 10.10 Yosemite (same issue with those images)

**Comment by mchiang0610** [comment]
@gunjan5 Hi Gunjan, Kitematic can't run base images. Are you looking to run Ubuntu? (If so, try the Ubuntu-upstart image from Docker Hub).

We should have better prompt in Kitematic to explain this though.

**Comment by gunjan5** [comment]
Thanks Michael! An error prompt should help. I was also trying CentOS which didn't work. Official and centos-jre.

**Comment by zedtux** [comment]
Hum ... sorry I'm not sure to understand the issue ... Ubuntu image is running fine with Kitematic

![screenshot from 2015-06-26 12 01 31](https://cloud.githubusercontent.com/assets/478564/8375102/bff75690-1bfa-11e5-86ea-c99ea7735b92.png)

**Comment by FrenchBen** [comment]
This is a more of an issue with the use of the container rather than with Kitematic. Closing
