### ISSUE TITLE
Changing name on cli not replicating to Kitematic

### ISSUE THREAD

**Issue by casalot** [docker/kitematic#498]
When using cli "docker rename" to change the name of a container, it does not reflect on the Kitematic UI. Any subsequent UI setting changes for the container will 404.

**Comment by mchiang0610** [comment]
@casalot Thanks for this bug report. We will look into it.

**Comment by FrenchBen** [comment]
There is currently no event triggered when a container is renamed. Until the core daemon does this, we will not be able to make this work.
Closing.
