### ISSUE TITLE
Settings | Volumes enables the volume mapping without warning

### ISSUE THREAD

**Issue by SvenDowideit** [docker/kitematic#502]
ifyou start a new container, and then browse to "settings" "volumes", then click change on a volume

you don't get the "Warning: enabling volumes may kill everything" warning.

its also not clear if this will enable only the one mapping, or a mapping for all volumes.

**Comment by TeckniX** [comment]
@SvenDowideit I can add some text below the Volume mapping to indicate that this will force a reboot of the container. 
What I'm not following is the part: 'not clear if this will enable only the one mapping, or a mapping for all volumes' - volume mapping is a 1:1 relationship, if you change the volume on your 'Mac Folder', isn't it implied that you're changing the mapping for the 'Docker Folder' associated with it?

**Comment by FrenchBen** [comment]
All warnings should be in place now. Closing
