### ISSUE TITLE
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/31/314918ddaedfedc0345d3191546d800bd7f28bae180541c9b8b45776d322c8c2/data?verify=1563548232-oUEyUSMj54EflEweOaBbUBOb%2Bbo%3D: Service Unavailable

### ISSUE THREAD

**Issue by elhamkhosty** [docker/kitematic#5091]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Vvk177** [comment]
on running following command
`docker build -t vivek177/sample-docker-example .`

getting this error 

error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/
