### ISSUE TITLE
Error while creating elastic search container

### ISSUE THREAD

**Issue by Ashish0410verma** [docker/kitematic#5149]
### Expected behavior
- Elastic search container should be created.

### Actual behavior
- I am getting Http 500 server error manifest unknown: manifest unknown

### Steps to reproduce the behavior

  1. ...Go to kitematic and create elastic search container
  2. ... Getting http 500 error
![Screenshot (9)](https://user-images.githubusercontent.com/53661411/62415851-148d0000-b64e-11e9-8995-2c60aea2d022.png)

**Comment by scipe** [comment]
I have different error: 404.
(HTTP code 404) unexpected - manifest for elasticsearch:latest not found: manifest unknown: manifest unknown

**Comment by Ashish0410verma** [comment]
@scipe If u want to setup elastic search with kibana using docker then follow this link https://stackoverflow.com/questions/52542487/unable-to-connect-to-kibana-elasticsearch-using-docker-compose. I used the same docker-compose file and was able to run both kibana and elstic search successfully.

**Comment by scipe** [comment]
@Ashish0410verma yeah, sure. In case when you trying to download not "latest" it's working. I just trying setup same thing, but not inside docker. In k8 - and in first time have same error with creating pod, but after I change version from latest to anything - it start working.
