### ISSUE TITLE
Unable to download container

### ISSUE THREAD

**Issue by ajandemorenawer** [docker/kitematic#5195]
### Expected behavior
supposedly download docker container
### Actual behavior
Fails

### Information about the Issue
ETIMEDOUT
ETIMEDOUT
connect
192.168.99.101
2376

### Steps to reproduce the behavior
1 Select container for download and CREATE

**Comment by AOsipian** [comment]
Any updates on this?

One reason could maybe be your network's restrictions. Like when a corporate network is tightly secured and makes it difficult for various processes to correctly execute the intended actions.

**Comment by ajandemorenawer** [comment]
I have tried it at home too but doesn't work either. Thanks anyway.
