### ISSUE TITLE
Error:: Download ElasticSearch Image

### ISSUE THREAD

**Issue by itsismail** [docker/kitematic#5239]
### Expected behavior
Download ElasticSearch Image
### Actual behavior
Error:manifest for elasticsearch:latest not found: manifest unknown: manifest unknown
### Information about the Issue

manifest for elasticsearch:latest not found: manifest unknown: manifest unknown
### Steps to reproduce the behavior

  1. Open Kitematic
  2. Search for elasticsearch & click on create 

![image](https://user-images.githubusercontent.com/14868433/64102383-439bac00-cd89-11e9-9f01-02c909adf81c.png)

**Comment by aptonline** [comment]
I'm also seeing the above error.

**Comment by MTS22** [comment]
![image](https://user-images.githubusercontent.com/39028268/76129801-bae81c00-6008-11ea-8b59-a13c42bdff0f.png)
had the same problem on windows when building the container.
solved it by going to the file docker-compose.yml: 
and change the image of the service to:

`image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1`
check if the image you want to pull exists

**Comment by thaJeztah** [comment]
Looks like that repository does not have a `:latest` tag, so you will have to specify a specific tag to use; here's the steps to do so:

<img width="288" alt="screenshot 2019-02-28 at 11 13 10" src="https://user-images.githubusercontent.com/1804568/53559259-0dffd700-3b4a-11e9-84dc-aca7eadb8266.png">

Click on the `...` button to view the image's details

<img width="289" alt="screenshot 2019-02-28 at 11 13 25" src="https://user-images.githubusercontent.com/1804568/53559322-27088800-3b4a-11e9-91ec-88ca26854d28.png">

Click on the `Selected tag: latest` to open the "tag selection" window

<img width="293" alt="screenshot 2019-02-28 at 11 13 48" src="https://user-images.githubusercontent.com/1804568/53559363-3be51b80-3b4a-11e9-8bd0-c5da16e891cd.png">

Click the tag / version of the image you want to run

<img width="296" alt="screenshot 2019-02-28 at 11 13 57" src="https://user-images.githubusercontent.com/1804568/53559412-51f2dc00-3b4a-11e9-924a-2929fafdcdbb.png">

Click the `(X)` to close the tag selector window

<img width="295" alt="screenshot 2019-02-28 at 11 14 16" src="https://user-images.githubusercontent.com/1804568/53559443-62a35200-3b4a-11e9-8691-57e375a90a7b.png">

Click on the `Create` button to pull the image and start the container
