### ISSUE TITLE
Unable to download the docker image from kinematic.

### ISSUE THREAD

**Issue by syedzubair-dev** [docker/kitematic#5298]
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

![image](https://user-images.githubusercontent.com/44016150/65085890-62c34c00-d9cd-11e9-8222-b4626fbca784.png)

**Comment by thaJeztah** [comment]
The mysql container image is only available for Linux (see https://hub.docker.com/_/mysql?tab=tags), so pulling that image when running native windows containers will produce this error. You can switch Docker to use Linux containers if you're planning to (only) run Linux images.
