### ISSUE TITLE
You Cant Login to Docker HUB? Download now here.

### ISSUE THREAD

**Issue by Trackhe** [docker/kitematic#5308]
I made a "Update Version". with Login Fix and adding Features.

You can Download it [here](https://github.com/Trackhe/kitematic/releases/latest).

I use:
https://github.com/docker/kitematic/pull/3462 .. https://github.com/docker/kitematic/pull/3692 .. https://github.com/docker/kitematic/pull/4401 .. https://github.com/docker/kitematic/pull/5306 .. https://github.com/docker/kitematic/pull/2542

Have Fun :P  

PS: I accept no liability for bugs, loss of data or other things related to this post and the packages.
 
you can write bugs to this package below.

**Comment by snickom** [comment]
And the description key is?

**Comment by Trackhe** [comment]
@snickom Fix sign up, and then it can be closed.

**Comment by mariovp** [comment]
I had this issue with the latest version, your version works great, thanks!

**Comment by danielfreitas1** [comment]
Working fine. Thanks.

**Comment by AdamCaviness** [comment]
Thanks for taking the time to do this. For me I had two snags:
1) The docker Kitmatic update dialog sent me to a version that wasn't the latest so docker desktop kept re-prompting. I promptly found the latest release on github and worked around that.
2) I couldn't sign in with 0.17.8 of Kitematic and found your build.

Thanks again.

**Comment by bvogel** [comment]
Sorry, but I wouldn't trust some random person linking files from mega.nz to solve an issue which really should be fixed by the kitematic team in the first place. I consider this "solution" as harmful und this no-issue should be closed and buried as soon as possible. Spamming all related bugs isn't helpful either!

**Comment by Trackhe** [comment]
> Sorry, but I wouldn't trust some random person linking files from mega.nz to solve an issue which really should be fixed by the kitematic team in the first place. I consider this "solution" as harmful und this no-issue should be closed and buried as soon as possible. Spamming all related bugs isn't helpful either!

okey @bvogel 

1. "linking files from mega.nz"
Mega is a fast cloud provider with no restrictions. That's why my choice fell on this one.

2. "to solve an issue which really should be fixed by the kitematic team in the first place."
I'm also waiting for an update with a fix. but there is no update for almost 20 days!
Complain to the kitematic team.

3. "I consider this "solution" as harmful und this no-issue should be closed and buried as soon as possible."
You do not have to use this fix. and I try to help other people. 
if you have a problem keep it for yourself!

4. "Spamming all related bugs isn't helpful either!"
Yes that's true. nevertheless, the same applies here certainly. Anyone who shares this link just wants to help!
everything else is a spiteful submission.


I wish you a wonderful day. gez. Trackhe(M.N)

**Comment by Trackhe** [comment]
Wow jea update.
https://github.com/docker/kitematic/releases v0.17.9 but no fix. and no fuck is given. if they continue like that, I open a fork. @mat007 please fix. and close the issue. you only need to merge https://github.com/docker/kitematic/pull/5306

**Comment by Trackhe** [comment]
[Fork Kitematic Download Release](https://github.com/Trackhe/kitematic/releases/latest).
