### ISSUE TITLE
Allow static IP Addresses for containers

### ISSUE THREAD

**Issue by johncokos** [docker/kitematic#531]
This is probably just something with our implementation, but the fact that "dev" changes from 192.169.99.100 is causing us problems.  We're trying to script some of the setup steps and document some troubleshooting advice for folks ... and that changing IP keeps biting me.

"Hey ... do all off this stuff AND make sure and find the IP address and then change it in these commands that you have to copy and paste" makes for a bad experience for the inexperienced users that is our intended audience.

Possible to lock that down somehow?

**Comment by TeckniX** [comment]
I think this is more of a docker-machine issue, as using the virtualbox driver, you cannot dynamically provide a different machine IP than the 192.168.99.100 they have provided in their dhcpserver settings. 

I believe you could create a new host-only interface and associate your `dev` vbox with it to get the IP you want. 

Why do you need to change the IP address in the first place?

**Comment by johncokos** [comment]
We don't want it to change. Ever

What happens is that if you have an issue and have to delete or stop the Dev machine... When it comes back up it'll now have a new IP like .101

That makes my bash scripts sad

**Comment by ssteinerx** [comment]
I am having this issue where I get mismatches of SSH keys and have to rebuild the virtual machine.  Each time I do, the IP address goes up by one and I can't find where to get it back to 192...100 where other tools expect it to be.

**Comment by FrenchBen** [comment]
@ssteinerx Take a l

**Comment by ssteinerx** [comment]
@FrenchBen Hopefully they'll 'be in contact soon.'  Fortunately, shutting down VirtualBox and waiting until the DHCP lease expires (long enough to get tea) is a work around.

**Comment by sachinerosnow** [comment]
i'am running jenkins container ,so i need to access my jenkins by other laptop
please help me ..
