### ISSUE TITLE
Cannot log in to docker hub 

### ISSUE THREAD

**Issue by inastrangeland** [docker/kitematic#5313]
Log in to docker hub and get access to repository

Login hangs and never completes

Mac OS Mojave 10.14.6, Docker for Mac, Kitematic

### Steps to reproduce the behavior

  1. Open Kitematic
  2. .Enter log in credentials
`3. Wait for completion of login

**Comment by inastrangeland** [comment]
This solved my login issue.

https://github.com/docker/kitematic/issues/4214

**Comment by Trackhe** [comment]
Have you try to usehttps://github.com/docker/kitematic/issues/5308?

**Comment by inastrangeland** [comment]
No, 4214 fixed it.

**Comment by Trackhe** [comment]
then close the issue

**Comment by inastrangeland** [comment]
closed
