### ISSUE TITLE
Dockerhub not login

### ISSUE THREAD

**Issue by erselbey** [docker/kitematic#5326]
https://pasteboard.co/IzMLe1v.png

macOS >> Kitematic-0.17.9-Mac.zip

**Comment by Trackhe** [comment]
Use https://github.com/Trackhe/kitematic/releases/tag/v0.17.10

**Comment by jeserkin** [comment]
Wait so what was exactly the issue? Missing header?

**Comment by erselbey** [comment]
Kitematic does not input. It remains constantly loading.

**Comment by jeserkin** [comment]
Ou. Okay.

**Comment by ulrich** [comment]
Issue fixed, Kitematic can login to hub now.

Thank you for your feedback.

**Comment by erselbey** [comment]
Thank you for solved. Running 👌

**Comment by jeserkin** [comment]
@erselbey , so link provided by @Trackhe is the one, that should be used or what is the solution?
