### ISSUE TITLE
Kitematic login issue.

### ISSUE THREAD

**Issue by niveditha03** [docker/kitematic#5328]
### Expected behavior
When i put the username and password given for my docker hub in kitematic it must login . 
### Actual behavior
Not able to login to kitematic.
### Information about the Issue
When i give my username and password it does not login ,it just keeps buffering.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Trackhe** [comment]
Use https://github.com/Trackhe/kitematic/releases/latest

**Comment by ulrich** [comment]
Issue fixed, Kitematic can login to hub now.

Thank you for your feedback.
