### ISSUE TITLE
Kitematic is terrible.

### ISSUE THREAD

**Issue by BillyCoda** [docker/kitematic#5330]
### Expected behavior
Postgres container created

### Actual behavior
Error message with a link to here

### Information about the Issue
Kitematic seems to be not worth using, ever.

### Steps to reproduce the behavior

  1. Click the "+ NEW" button to go to the new container page
  2. Click the "CREATE" button on the Postgres tile
  3. ???
  4. Prof- ... error

**Comment by Trackhe** [comment]
I dont know what are you mean. 
<img width="1433" alt="Bildschirmfoto 2019-10-01 um 17 52 02" src="https://user-images.githubusercontent.com/1494328/65978555-318a5780-e474-11e9-94bb-9bf3144d3b25.png">

**Comment by BillyCoda** [comment]
![kitematic-error](https://user-images.githubusercontent.com/38147848/66670557-4eaeeb00-ec17-11e9-9a10-22066be53176.PNG)
Not seeing the version number anywhere.

**Comment by BillyCoda** [comment]
Updated and fixed. I rescind my comments about Kitematic being terrible, for now.
