### ISSUE TITLE
Container logs inside freeze after stopping and restarting the container 

### ISSUE THREAD

**Issue by mchiang0610** [docker/kitematic#535]

**Comment by TeckniX** [comment]
Is this on a particular container? The logs are being displayed properly on my `ghost` container:

```logs
> ghost@0.6.2 start /usr/src/ghost
> node index

Migrations: Up to date at version 003
Ghost is running in development... 
Listening on 0.0.0.0:2368 
Url configured as: http://localhost:2368 
Ctrl+C to shut down

> ghost@0.6.2 start /usr/src/ghost
> node index

Migrations: Up to date at version 003
Ghost is running in development... 
Listening on 0.0.0.0:2368 
Url configured as: http://localhost:2368 
Ctrl+C to shut down
```

**Comment by ianbytchek** [comment]
Not sure if I get the exact same thing. After restarting containers logs are not updating properly, I have to switch between home and logs tabs to get the refresh.

**Comment by mchiang0610** [comment]
@TeckniX Sorry for the delay. This seems to be a sporadic problem. I cannot reproduce most of the time. Opened an issue so we are aware. 

@ianbytchek Yes, same error.

**Comment by ianbytchek** [comment]
It happens all the time. Start the container that prints something into stdout, restart it, logs stop automatically refreshing, only by switching from home and logs tabs or vice versa.

**Comment by TeckniX** [comment]
@ianbytchek thanks for the good step-by-step, I now see it too. I'll start working on a fix

**Comment by FrenchBen** [comment]
Closing as this has been fixed in recent versions
