### ISSUE TITLE
issue for Macos catalina

### ISSUE THREAD

**Issue by Yof3ng** [docker/kitematic#5379]
## problem
after clicking `My images` , you will find that each button are useless, then the app crashed.

**Comment by Trackhe** [comment]
what is your kitematic version?

**Comment by Yof3ng** [comment]
latest version.

**Comment by Trackhe** [comment]
try this version https://github.com/Trackhe/kitematic/releases

**Comment by Yof3ng** [comment]
great, problem solved! thx for your help!

**Comment by Yof3ng** [comment]
okay，there is a new problem in `v0.17.11` .
after clicking `exec`, it throw a warning, i can't open the termial in docker.
```warning
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggabil…:868 Unhandled rejection Error: Command failed: /Applications/Kitematic.app/Contents/Resources/resources/terminal docker exec -it 0x14_ubuntuenv_v0.2 bash
92:124: execution error: “System Events” has error：“osascript” don't permit send it。 (1002)

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
```
I don't know if it's about permissions.

**Comment by Trackhe** [comment]
You can give me some instrucktions to reproduce the error? I try to fix it.

**Comment by Trackhe** [comment]
try to add this
![Bildschirmfoto 2019-11-03 um 12 22 19](https://user-images.githubusercontent.com/1494328/68084357-cf3ac300-fe34-11e9-8cc1-41514a067fe2.png)

**Comment by Yof3ng** [comment]
Nice! thx very much...It works...I guess it cause new version app don't get the permission, old version's configuration was still save in system even though the app has been uninstalled.👍
