### ISSUE TITLE
Stucking at "Connecting to Docker Hub" when create a container from images in kitematic UI

### ISSUE THREAD

**Issue by h3d-haivq** [docker/kitematic#5383]
### Setup
OS: macOS 10.15
Tool: Docker Toolbox, VirtualBox 6.0.14, Kitematic 

### Expected behavior
A container created after selecting an image

### Actual behavior
Kitematic keeps showing `Connecting to Docker Hub`, no new container created. 

### Information about the Issue
Everything is fine with Docker CLI. Containers can be created and managed using Docker CLI.
![image](https://user-images.githubusercontent.com/40750611/67695751-33dec380-f9d8-11e9-943d-d24484711419.png)

### Steps to reproduce the behavior

  1. Select an image from the image list in the UI, a new screen appear with `Connecting to Docker Hub`
  2. Nothing happend next, no image is downloaded, no new container created

**Comment by micopiira** [comment]
Same here on Windows 10

**Comment by Trackhe** [comment]
try this pls https://github.com/Trackhe/kitematic/releases

**Comment by Miirek** [comment]
@Trackhe - this build is not signed

**Comment by Trackhe** [comment]
@Miirek okey srry but i cant sign it becouse i dont give 100$ for a developer acc every jear.

**Comment by 1UC1F3R616** [comment]
@h3d-haivq found a solution?

**Comment by h3d-haivq** [comment]
> @h3d-haivq found a solution?

I've stopped using docker toolbox and kitematic since the new Docker for Mac is quite good.
