### ISSUE TITLE
hello-world-nginx fails to be created

### ISSUE THREAD

**Issue by NandanBharadwaj** [docker/kitematic#5438]
### Expected behavior
hello-world-nginx container has be downloaded and running.

### Actual behavior
Container fails to run with below error,
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\265d419a6d6aed18270e25cf5d893f965429a22b4c891ef58d4b4e7a67f88992: The system cannot find the path specified.

### Information about the Issue
Information on the environment is as below,
![image](https://user-images.githubusercontent.com/23073204/69415099-f22f0780-0d4e-11ea-875e-60d882bec603.png)

### Steps to reproduce the behavior

  1. With Windows Docker Engine configured to run Windows containers, try to run hello-world-nginx container from Kitematic.

**Comment by thaJeztah** [comment]
Yes, the kitematic/hello-world-nginx image is only available for Linux, so won't be able to run on Windows
