### ISSUE TITLE
(HTTP code 404) no such image - no such image: microsoft/mssql-server-linux:latest: No such image: microsoft/mssql-server-linux:latest

### ISSUE THREAD

**Issue by akinetopsia** [docker/kitematic#5448]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
looks like those images moved; https://hub.docker.com/r/microsoft/mssql-server-linux (also see https://hub.docker.com/_/microsoft-mssql-server?tab=description for new locations)
