### ISSUE TITLE
Scary High CPU Usage ... possible Fix

### ISSUE THREAD

**Issue by johncokos** [docker/kitematic#549]
One of my co-workers ran into an issue where his system CPU would skyrocket to the point of his computer becoming hot enough to cook eggs whenever he would fire up kitematic and mount some folders.

After some troubleshooting, he, working with @mchiang0610 discovered that the "Dev" has an auto-mount on the /Users folder for some reason...

![image](https://cloud.githubusercontent.com/assets/1766332/7842997/aedf7010-045b-11e5-9709-7925080d383c.png)

Disabling this mount fixed the problem.  Any reason why that folder is mounted automatically?  If this is not required can KM or docker-machine be changed not to mount that folder as a matter of course?

**Comment by mchiang0610** [comment]
@johncokos, the backlash from doing so is stopping the support of volumes. 

The reason for this is most likely due to nodemon doing polling on the shared folder - causing high CPU. (This is a problem within Docker that we will have to solve)

**Comment by johncokos** [comment]
This particular developer had nodemon set to monitor a folder under /Users, not on the /Users folder itself, the out of control polling with that mount enabled is still a mystery, but this change solved it.

Are you saying that if we remove /Users from the dev auto-mount, that we'll lose the ability to mount anything else?  Or just anything under that folder?

**Comment by mchiang0610** [comment]
@johncokos you'll lose the ability to mount anything, unfortunately. :(

**Comment by johncokos** [comment]
That is unfortunate.  Back to the drawing board

**Comment by TeckniX** [comment]
@johncokos For reference this was documented as part of the Docker volume management:
https://docs.docker.com/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume

The high-level visual is such - Docker runs within a VM, which has your `/Users` volume shared. Thus docker can access/mount anything within that `/Users` directory. 

Could it be just a high-level of files within the `/Users` directory? Would you mind creating an empty dir for the Dev to auto-mount and see if the same CPU levels are reached. 

For example, create a directory called `kitematic` under `/Users` - Load VirtualBox and mount that directory `/Users/kitematic`. 

ref: not the same setup/app, but similar issue with nodemon:
https://github.com/ChrisWren/grunt-nodemon/issues/46

**Comment by johncokos** [comment]
In actual practice, we have the users put their stuff in a folder such as:

/Users/project/workspaces/<dir>...

In KM, we have them selectively mount any number of those <dir> files as they want.  Some choose 1 some choose 5, whatever they need to do so that they can have the node system use their files 

Whatever they mount up, nodemon monitors.

Anyway ... 

For some of our users there are no problems.  For others, we get this crazy out of control thing only when a certain one of those folders is mounted.  That folder isn't special, has no symlinks, nothing out of the ordinary ... but the CPU usage goes through the roof.

The really odd thing about it is that inside the container, the CPU usage is paltry, like 4% or so.  Outside, on the actual computer, vboxheadless spins out of control going over 300% CPU.

Only when not mounting that one folder does it go away.

Tough to troubleshoot what is making vboxheadless go nuts, so I'm having a hard time asking for help here as I can only report that it's going crazy under a very specific circumstance.

**Comment by TeckniX** [comment]
@johncokos hence my recommendation of mounting the folder only in Virtualbox (not kitematic)

Using your example, I would change the mounted volume in Virtualbox to be `/Users/project/workspaces/` instead of the more general `/Users` it mounts by default.

What you do afterwards in Kitematic will still work as it did before, but your limiting the nodemon to all files within `/Users/project/workspaces/` instead of `/Users` regardless of what volumes are used in kitematic (docker)

**Comment by johncokos** [comment]
We will try that.

I feel like we tell nodemon to just tactially monitor a few folders, so I'll check that and try your suggestion

**Comment by jpapejr** [comment]
My experience has been that ant grunt watch or nodemon watch of the filesystem shared by VBox causes horrible CPU burn in the vm process.. Something on the order of a constant 114%-200%. If you stop the process doing the filesystem watching, the burn goes away. Unfortunately, you're still left with the Kinematic helper processes chewing up CPU, but that's another issue. :)

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
