### ISSUE TITLE
Error Datastax Server Enterprise Docker Container Latest Not Found

### ISSUE THREAD

**Issue by mfiguer** [docker/kitematic#5624]
### Expected behavior
With command docker _**pull datastax/dse-server**_ the Datastax Server Enterprise Docker Container Latest should be installed

### Actual behavior
_**docker pull datastax/dse-server**_ Using default tag: latest Error response from daemon: manifest for datastax/dse-server:latest not found: manifest unknown: manifest unknown

### Information about the Issue
https://hub.docker.com/r/datastax/dse-server

### Steps to reproduce the behavior

1. Open Kitematic on Windows 
2. Open Docker CLI
3. According with documentation the docker pull command is **docker pull datastax/dse-server**
4. PS C:\Program Files\Docker Toolbox> _**docker pull datastax/dse-server**_ Using default tag: latest Error response from daemon: manifest for datastax/dse-server:latest not found: manifest unknown: manifest unknown

**Comment by AntoinePetit24** [comment]
Same issue

**Comment by thaJeztah** [comment]
Looks like that repository does not have a `:latest` tag, so you will have to specify a specific tag to use; here's the steps to do so (steps below are for the `elasticsearch` image, but the steps are similar for the image you're using):

<img width="288" alt="screenshot 2019-02-28 at 11 13 10" src="https://user-images.githubusercontent.com/1804568/53559259-0dffd700-3b4a-11e9-84dc-aca7eadb8266.png">

Click on the `...` button to view the image's details

<img width="289" alt="screenshot 2019-02-28 at 11 13 25" src="https://user-images.githubusercontent.com/1804568/53559322-27088800-3b4a-11e9-91ec-88ca26854d28.png">

Click on the `Selected tag: latest` to open the "tag selection" window

<img width="293" alt="screenshot 2019-02-28 at 11 13 48" src="https://user-images.githubusercontent.com/1804568/53559363-3be51b80-3b4a-11e9-8bd0-c5da16e891cd.png">

Click the tag / version of the image you want to run

<img width="296" alt="screenshot 2019-02-28 at 11 13 57" src="https://user-images.githubusercontent.com/1804568/53559412-51f2dc00-3b4a-11e9-924a-2929fafdcdbb.png">

Click the `(X)` to close the tag selector window

<img width="295" alt="screenshot 2019-02-28 at 11 14 16" src="https://user-images.githubusercontent.com/1804568/53559443-62a35200-3b4a-11e9-8691-57e375a90a7b.png">

Click on the `Create` button to pull the image and start the container

**Comment by maxiplux** [comment]
I'm having the same issue

**Comment by maxiplux** [comment]
Here my solution to this problem
version: "3"

services:
  dse-server:
    image: datastax/dse-server:6.8.2
    container_name: dse-server
    environment:
      DS_LICENSE: accept
    ports:
      - "9042:9042"
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 1g

  dse-studio:
    image: datastax/dse-studio:latest
    container_name: dse-studio
    environment:
      DS_LICENSE: accept
    ports:
      - "9091:9091"
    links:
      - dse-server
    depends_on:
      - dse-server

volumes:
  db-data:

networks:
  front-tier:
  back-tier:

**Comment by thaJeztah** [comment]
Yes, see my comment above; the maintainers of the `datastax/dse-server` image decided not to have a `:latest` tag, in which case you have to specify the tag/version of the image to use
