### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by gracianow** [docker/kitematic#5670]
### Expected behavior
open repository
### Actual behavior
(HTTP code 404) unexpected - manifest for gracianow/wag_kdck:latest not found: manifest unknown: manifest unknown
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
Looks like that repository either doesn't exist on Hub, or requires authentication; https://hub.docker.com/r/gracianow/wag_kdck
