### ISSUE TITLE
Create hello-world-nginx does not work

### ISSUE THREAD

**Issue by maruthihr** [docker/kitematic#5723]
### Expected behavior
Create hello-world-nginx should download an nginx image and launch a container from it 

### Actual behavior
On clicking Create, Following error is reported 
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\650fdf35c75717da07795bdc6fe2cfc598f54e9264eb021b684c38fc14d00bce: The system cannot find the path specified.

### Information about the Issue
On windows 10. Docker daemon set to windows container mode. Connects to docker hub

### Steps to reproduce the behavior

  1. Start Kitematic
  2. Click on Create 'hello-world-nginx'

**Comment by thaJeztah** [comment]
I think that image is only available as a Linux image; if you are running Docker Desktop, and want to run Linux containers, you need to switch docker to Linux containers; https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

I don't think there's a bug at hand here, so I'm closing this issue, but feel free to continue the conversation
