### ISSUE TITLE
configure volumes - set mac folder not work on latest yosemite 

### ISSUE THREAD

**Issue by simiula** [docker/kitematic#599]
I try with many image.
I clicked CHANGE button, then locate my mac folder (try on boot disk and an external disk), then click OK: appear the No Folder text and it is impossible to set my local folder. (I also used the hello world ngix image without success).

**Comment by jeffdm** [comment]
Thanks for the issue.

Kitematic will only mount directories under `/Users`. Were the directories you tried under that path?

We should really do a check-in app.

**Comment by simiula** [comment]
> Il giorno 05/giu/2015, alle ore 20:00, Jeffrey Morgan <notifications@github.com> ha scritto:
> 
> Thanks for the issue.
> 
> Kitematic will only mount directories under /Users. Were the directories you tried under that path?
> 
> 
Inside Users is working. On any other position is not.
I have a dedicated harddisk to my projects…it is a non sense to use the Users only, 
specially because ‘modern’ macs with SSD has not very large hardisk…
It is cheaper to have more disks connected. (I have Mac retina with SD cards and some USB 3 SSD..).

Bye

> We should really do a check-in app.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/kitematic/kitematic/issues/599#issuecomment-109381403>.
> 

Gerardo Iula

State of the art iOS Apps

Via Campo Sportivo 2B
24040 Pontirolo Nuovo (BG) - Italy

Site: http://www.simiula.com
Mail: info@simiula.com
Twitter: @simiula

For online sites and iOS Apps catalogue: 
http://www.simiula.com/

**Comment by TeckniX** [comment]
@simiula you can actually use VBox to mount a different folder than the /Users - It's just the default mounted folder.

**Comment by ribozz** [comment]
I also vote to remove this artificial restriction and allow to mount any folders into docker containers (Configure volumes tab).
Now I am forced to create containers using DOCKER CLI.

My use case is simple:
I need /Users folder to be consistent in all three places VirtualBox, Host Machine and my working environment inside container (mcloud-osx). This allow not to thing about path differences in all three places.

How I create my container now, if doing this manually:
$ docker run -d -v /Users --name mcloud mcloud/mcloud-osx

Before I was able to start same thing through Kitematic UI and mount folder, now I get "Invalid directory. Volume directories must be under your Users directory".

Another thing is that if I use docker cli to start the container, Kitematic UI don't show where volume is being mounted, showing "No Folder" instead.

**Comment by groovemaps** [comment]
+1

**Comment by digitaldavenyc** [comment]
+1

**Comment by FrenchBen** [comment]
There's a pending PR to have this baked in #1202  - Be on the lookout.
