### ISSUE TITLE
How do I change which path gets exposed locally?

### ISSUE THREAD

**Issue by ovizii** [docker/kitematic#619]
I downloaded the official nginx container and it exposes /var/cache/nginx which I think is useless trying to follow your tutorial => https://kitematic.com/docs/nginx-web-server/ since the websie actually resides inside /usr/share/nginx/html 

Using kitematic I can only change the local part of this Volume mapping not the container part !? what to do...

**Comment by mchiang0610** [comment]
Hi @ovizii thanks for bringing this up. 

In order to change the paths that you mount, you will have to change it on the Docker image. 

Try the Nginx one that Kitematic recommends 

![image](https://cloud.githubusercontent.com/assets/3325447/8121954/efec36ca-1067-11e5-83a3-3b0233f319b3.png)

**Comment by ovizii** [comment]
Thanks, I had thought, maybe, just maybe, there was an option to change that with Kitematic :-) 
I guess I'll have some more reading up to do :-)

**Comment by TeckniX** [comment]
@ovizii you could always re-create the nginx container and map whatever volume you'd like, but using the Kitematic 'hello-world-nginx' as @mchiang0610 advised would be the easier choice.

**Comment by ovizii** [comment]
that's beside the point, I'm trying to learn more about docker and thought I'd start with a GUI hence kitematic, still busy reading documentation and tutorials about docker and the likes :-)
