### ISSUE TITLE
Change virtualbox ip address

### ISSUE THREAD

**Issue by bbhenry** [docker/kitematic#638]
Is it possible to change the Virtualbox Docker Machine's IP address? I tried it and it lost association with Kitematic.

**Comment by TeckniX** [comment]
By default on a VM, the Docker-Machine created will have the IP address of `192.168.99.100` - I don't believe there are any commands to change it, unless you re-write the driver for it.

**Comment by bbhenry** [comment]
Can this be added as enhancement then?

**Comment by TeckniX** [comment]
If you're so incline, you could just pull the source code from github and just set it to whatever you wanted:
https://github.com/docker/machine/blob/c10962320729a8d436eb09ce9aaae1f4bdd7d0ad/drivers/virtualbox/virtualbox.go

**Comment by mchiang0610** [comment]
I'll add it as a feature request for people to vote on. 

@TeckniX's suggestion is sound if you're inclined to do so.

**Comment by TechJournalist** [comment]
where is the location for the feature request vote on this issue? Would be a huge bonus for me/my testing to be able to assign/adjust IP addresses. Thanks!

**Comment by mchiang0610** [comment]
@TechJournalist Sorry, I meant this as a place where people can comment and help submit a PR.

**Comment by TechJournalist** [comment]
ok - and how can i help submit a PR or get this changed?

**Comment by TechJournalist** [comment]
k i'm getting stuck trying to figure out how to make this work / but happy to try and contribute. Does the -defaultHostOnlyCIDR  - variable just need to be set to FOO or?

**Comment by TechJournalist** [comment]
Would love to see this in the GUI so normal users can get this done easily.

**Comment by mchiang0610** [comment]
Hi @TechJournalist , to do a pull request on Kitematic please feel free to fork Kitematic's code, make the necessary changes on your repository, and then make a pull request to us. That is when we will review the code with the team. 

I believe this might be a feature for Docker machine - adding @nathanleclaire from Machine team for technical help. Also cc'd @jeffdm 

Thanks for helping!

**Comment by jeffdm** [comment]
@TechJournalist a current workaround, assuming you've got the Toolbox installed:

- Close Kitematic
- Delete the current `default` VM: `docker-machine rm -f default`
- Create a new default machine `docker-machine create -d virtualbox --virtualbox-hostonly-cidr "192.168.99.1/24"`
- Open Kitematic and it should be using this VM.

As for making this doable via the GUI, I think eventually we'll want KM to be configurable to point to any host but this is work in progress. Check out https://github.com/kitematic/kitematic/pull/876 for a cool example of a team at the DockerCon 2015 hackathon (see #3, Lightning Kite) https://blog.docker.com/2015/07/highlights-dockercon-2015-hackathon/

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
