### ISSUE TITLE
Add ability to specify and save custom parameters to a container

### ISSUE THREAD

**Issue by kireevco** [docker/kitematic#678]
Things like `--device` or any other custom parameters.

**Comment by kireevco** [comment]
Any workaround from UI for this at least? It's a little bit too hard to ask users to open cli. Can we use some exported env variable from a dockerfile?

**Comment by zedtux** [comment]
@kireevco no there's no workaround as far as I know. It needs to be implemented specifically as each flags you wan to specify match with a specific Docker server API attribute.

If you need the `--device` flag, then request the possibility to mount devises, but if you need another one, you should open another issue.

**Comment by FrenchBen** [comment]
Closing this issue due to the lack of activity and in favor of #764
