### ISSUE TITLE
Cannot start container if No CMD specified in image

### ISSUE THREAD

**Issue by scornelissen85** [docker/kitematic#692]
When starting an Alpine container it stopped with error 500 (No command specified). I think it stopped because alphine has no command. I would like to set a command in Kitematic, but there is no option to do so.

**Comment by TeckniX** [comment]
If you pull the latest 0.7.2 release you should have Advance features that will allow you to set it to a semi-tty which should fix the issue. 

![node](https://cloud.githubusercontent.com/assets/33699/8258918/c79f69ec-1686-11e5-8e34-b78caa78faee.png)
