### ISSUE TITLE
Cmd + 0 should re-open Window

### ISSUE THREAD

**Issue by doxxx** [docker/kitematic#702]
If I close the Kitematic window using Cmd-W, there's no way to re-open the window without quitting Kitematic and restarting it. Combined with the option to shutdown the Linux VM on closing Kitematic, this is problematic.

**Comment by jeffdm** [comment]
@doxxx thanks for the issue. What's the usual procedure on Mac? If you click the dock icon the window should return.

**Comment by jeffdm** [comment]
Going to close this for now, but feel free to re-open. Like other Mac apps, clicking the icon on the dock will re-open the Kitematic window.

**Comment by doxxx** [comment]
Sorry for not replying, for some reason I wasn't notified of your comment.

Usually, if it's intended that there is only ever one main window in the app, there is an item in the Window menu, with the main window's name and usually bound to Cmd-0 or Cmd-1, that re-opens the window.

**Comment by jeffdm** [comment]
Got it! That makes sense, I'll re-open this.

**Comment by mikaoelitiana** [comment]
I created a PR for this https://github.com/kitematic/kitematic/pull/1229
