### ISSUE TITLE
User should be able to configure on-premise private registries in Kitematic configuration.

### ISSUE THREAD

**Issue by gmsr** [docker/kitematic#769]
User should be able to configure on-premise private registries in Kitematic configuration. At present, user is not able to configure on-premise private registries. Not sure whether you are allowing docker registry enterprise configuration to pull images from private registries.

**Comment by rcarmo** [comment]
+1 for this. Rather... +9000!

**Comment by BSick7** [comment]
:+1:

**Comment by steve-jansen** [comment]
:+1:

**Comment by rberger** [comment]
+1000

**Comment by fritzrichter** [comment]
:+1:

**Comment by FrenchBen** [comment]
Although it's not very well document, as support isn't 100% yet, Kitematic does check for local environment endpoints before using it's hard-coded path.

One could set its registry as such and Kitematic would read from it:
`export REGHUB2_ENDPOINT="http://my.repo.docker"`

**Comment by michaelwilde** [comment]
We're going to need this big time @FrenchBen. Especially if we get Docker Trusted Registry.  It would help to be able to "add a registry" as a config setting.. or "change default registry"...   Please consider that as i'd like to deploy docker images for all Splunk demos for employees, partners.. and maybe even the public.

**Comment by FrenchBen** [comment]
@michaelwilde I actually made this possible in this PR https://github.com/kitematic/kitematic/pull/1076

Just need someone to help QA ;)

**Comment by michaelwilde** [comment]
@FrenchBen ... you know I'll help.  What do i do?

**Comment by FrenchBen** [comment]
@michaelwilde 
Clone the repository:
`git clone https://github.com/FrenchBen/kitematic/`
Use the `private-repo` branch (https://github.com/FrenchBen/kitematic/tree/private-repo)
`npm install`
`npm start`

You should be able to navigate to the preference panel where you can update the link to the docker hub of choice.
![private-repo](https://cloud.githubusercontent.com/assets/3965324/10461504/9f042ec4-71a7-11e5-95c0-95a2c3bd8f94.png)

**Comment by balakumarpg** [comment]
Hi FrenchBen,
I am very new to docker, but I think I managed to test this, but I get error message "Registry does not exists or is down". But I can access my registry using browser ssl enabled and currently I am not using any authentication on registry. Hope this helps you or help me to proceed further.

/Bala.

**Comment by steve-jansen** [comment]
@FrenchBen 
I also get `Registry does not exist or is down` running the private-repo branch on https://github.com/FrenchBen/kitematic/ against my Docker Trusted Registry instance.

The problem appears to be [src/utils/RegHubUtil.js  lines 30-37](https://github.com/FrenchBen/kitematic/blob/6ab013e243d00d714d1c5c2223b835a8ce07e72e/src/utils/RegHubUtil.js#L30-L37) which assumes the private registry will have a repository named `debian`.  My private registry does not have a registry named debian, so this check fails.

According to [the Docker Registry HTTP API v2](https://docs.docker.com/registry/spec/api/#api-version-check), we might `GET /v2/` and verify a 200 response code.

**Comment by FrenchBen** [comment]
@steve-jansen good point - I thought the check would work as debian is a pretty common image. What I didn't realize is that a lot of the registry API calls will be different and thus the branch isn't going to work as expected. There's a lot more work to be done to get this working properly.

**Comment by michaelwilde** [comment]
I can also see a use case for "multiple registries"... say we have a private one for internal stuff at Splunk, using Kite.. i might want to be able to see the one's I am allowed to use, AND the one at hub.docker.com/v2

Y'all definitely want to get it working with DTS for for sure. Liking the direction.

**Comment by FrenchBen** [comment]
@michaelwilde Absolutely! I see it as something like yum repos, where multiple channels can be added allowing for a greater range of images to be selected.

**Comment by michaelwilde** [comment]
@FrenchBen any chance you can raise this to a higher priority.  Close to becoming a customer.  Will require Kitematic + DTR.

**Comment by michaelwilde** [comment]
Hows the progress?  Any movement on DTR in Kitematic?

**Comment by cschritt** [comment]
+1

**Comment by michaelwilde** [comment]
bump.

**Comment by FrenchBen** [comment]
Closing in favor of #210
