### ISSUE TITLE
Mapping Docker folder to custom local folder on separate partition

### ISSUE THREAD

**Issue by kotowick** [docker/kitematic#809]
For boot2docker on OSX, I overrode the boot2docker command to mount the volume in the Dockerfile (/data) to a custom partition that is case sensitive. 

Would it be possible to add this as a feature in Kitematic?

**Comment by xkidro** [comment]
+1

**Comment by kotowick** [comment]
Anyone know if this is getting anywhere?

**Comment by alexandrev** [comment]
That should be covered with the PR https://github.com/kitematic/kitematic/pull/1202. Please, take a look to make sure that's the same behavior that you want to.

**Comment by FrenchBen** [comment]
This is now available using Docker for Mac/Windows
