### ISSUE TITLE
Using --dns and --dns-search with kitematic

### ISSUE THREAD

**Issue by boosis** [docker/kitematic#817]
Before Kitematic, I was running my containers with --dns and --dns_search parameters which were changing the /etc/resolv.conf in the container.

Now I am playing around with Kitematic and I want to know if it's possible to set these per container?

**Comment by FrenchBen** [comment]
@boosis Sorry but this feature is currently not available. Feel free to implement it and create a pull request for it :D

**Comment by boosis** [comment]
@FrenchBen unfortunately I am not js developer, so I won't be able to help you there :)

At the moment (I am learning Docker as of now) I only use --dns and --dns_search on one of the containers as the container has to use our own dns server. Apart from that Kitematic does the job for me.

**Comment by FrenchBen** [comment]
Can you provide the full `docker run` command you use? It shouldn't be too hard to add support for it.

**Comment by boosis** [comment]
I use docker-compose to run my containers and I have these in the yml file
`dns: 192.168.35.254`
`dns_search: company.localhost`

which correlates to
`docker run --dns=192.168.35.254 --dns-search=company.localhost`

**Comment by FrenchBen** [comment]
@boosis if you want to give it a try:
https://github.com/TeckniX/kitematic/tree/advance-dns

**Comment by boosis** [comment]
I would love to try this but I have no idea how to build the source code :)

**Comment by boosis** [comment]
Advanced settings tab is disappeared

https://www.dropbox.com/s/crrmzo0w04x90pr/Screenshot%202015-07-17%2017.26.28.png?dl=0

**Comment by FrenchBen** [comment]
@boosis make sure that you are compiling the 'advance-dns' branch - the master isn't kept updated so that it's easier for me determine what is compiled (aka no advance tab) ;)

**Comment by boosis** [comment]
@FrenchBen I just tested this and seems to be working. But it doesn't accept domain.localhost as it's not valid domain but we still use it for our development servers.
Ref: https://en.wikipedia.org/wiki/.localhost

Is it possible to enable tlds like .localhost, .dev etc?

**Comment by boosis** [comment]
@FrenchBen I think (!) I managed to send a pull request to https://github.com/TeckniX/kitematic/tree/advance-dns

Which adds .localhost and .dev to the domain regex. This is my first pull request so excuse me if I did something wrong but I was able to build and run it without any problem and it's now accepting .dev and .localhost

**Comment by FrenchBen** [comment]
Some of the spacing was a little off, but I did add the .localhost and .dev to my code. Thanks for the PR.

I'd like to see a bit more QA on it, I may send a PR to the kitematic team :)

**Comment by klousiaj** [comment]
:+1: 
Is this something that is still being considered for a PR and inclusion?

**Comment by FrenchBen** [comment]
@klousiaj there isn't much demand for it and thus wasn't integrated - A PR had been created but there wasn't much interest/feedback on it. 
Closing for now - if you feel there is a need for it, please create a Feature proposal.
