### ISSUE TITLE
Overwrite ENTRYPOINT/CMD

### ISSUE THREAD

**Issue by boosis** [docker/kitematic#819]
I am running the Redis image (https://registry.hub.docker.com/_/redis/) and according to the documentation I need to run the container with
`redis-server --appendonly yes`
but the image runs
`redis-server`

Is it possible to change the CMD?

**Comment by marcelaraujo** [comment]
+1

**Comment by FrenchBen** [comment]
Closing this issue due to the lack of activity and in favor of pending feature #1260
