### ISSUE TITLE
When Ports or Volumes are blank then provide instructions on how to open a port or volume

### ISSUE THREAD

**Issue by cclauss** [docker/kitematic#831]
Some official container images (e.g. Django) have no ports and no volumes open.  This is confusing for inexperienced users.  When these Kitematic tabs are blank, it would be helpful to fill that whitespace with instructions on how to open a port or create a volume.

**Comment by FrenchBen** [comment]
Thanks for the feature request.
There are two PR currently under review that bring the Port edit and Volume edit when none are provided to Kitematic.

**Comment by FrenchBen** [comment]
Closing this issue due to the lack of activity and in favor or pending PR
