### ISSUE TITLE
Kitematic will display / imply access to volumes which aren't accessible on the host.

### ISSUE THREAD

**Issue by nathanleclaire** [docker/kitematic#849]
![image](https://cloud.githubusercontent.com/assets/1476820/8839600/f2221d08-308b-11e5-8cd0-54b2e88ce002.png)

I created this container on CLI using a command like:

```console
$ docker run --name docker-service-journal -d -v /run:/run debian:jessie journalctl -f -u docker.service
```

(this is on the "Next Generation" b2d, so the exact command may not work out of the box)

`/run` is totally accessible within my VM, but not so much on the OSX host (We only mount `/Users` into the VM, so there's not really "perfect" sharing).

IMO this should probably just not be displayed, since it's kind of an "invalid" volume for editing from the host.  Longer-term maybe Kitematic could hack around it with something like SSHFS/MacFUSE, 9p, rsync etc. etc. etc.

**Comment by FrenchBen** [comment]
@nathanleclaire when you say 'on CLI' you mean logged in to the actual VM? Otherwise I don't think the volume mapping would work from a regular OSX terminal?

**Comment by nathanleclaire** [comment]
> when you say 'on CLI' you mean logged in to the actual VM? Otherwise I don't think the volume mapping would work from a regular OSX terminal?

Well, ultimately it doesn't really matter as the request sent to the Docker API always comes in as "use `/run` for the host volume, and `/run` for the container mount" due to the usage of absolute paths.

**Comment by nathanleclaire** [comment]
A hacky solution to this would be to check if the volumes start with `/Users`, `/home` (for Linux), or `/c/` (Windows), but ultimately I'd like something better.

**Comment by FrenchBen** [comment]
I agree that this needs some work/refactoring. 

Kitematic already does the host path check hacky solution, when you go through the UI to mount the Volume. 
We're already seeing this also with custom User paths/mounts which fail, due to them not being under `/Users/`

**Comment by FrenchBen** [comment]
Closing this issue due to the lack of activity and in favor of volume management PR
