### ISSUE TITLE
Bugs reported by Kitematic not useful to Docker machine team

### ISSUE THREAD

**Issue by mchiang0610** [docker/kitematic#856]
* Improve bug reporting on Kitematic
- [ ] Always have docker-machine debug logs

- [ ] Output of VBoxManage list hostonlyifs

- [ ] Output of VBoxManage list dhcpsevers

- [ ] Docker Daemon logs    (command is: this is for boot2docker ISO debian edition `docker-machine ssh docker-vm-name -- journalctl --no-pager -u docker.service` ) 

- [ ] boot2docker network daemon log  

- [ ] Machine vbox.log 

- [ ] Machine foo.vbox (XML) -> property of created VMs 

Nice to have: 
- [ ] SSH exit 0 verbose output

**Comment by timfallmk** [comment]
@mchiang0610 `docker logs <container>` might also be useful to get the container log output.

**Comment by Fahrradflucht** [comment]
Is this still valid? I mean now that there is Docker for Mac and Docker for Windows?

**Comment by FrenchBen** [comment]
closing with @Fahrradflucht's input validating this.
