### ISSUE TITLE
var/run/sshd must be owned by root and not group or world-writable.

### ISSUE THREAD

**Issue by phuongtailtranminh** [docker/kitematic#893]
Hi

I'm running OS X 10.10.4, Kitematic 0.7.6 and installed docker-oracle-xe-11g

But this is log when i was trying start it.

```
Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

/var/run/sshd must be owned by root and not group or world-writable.
```

How can i fix that?

There is no sshd in /var/run
<img width="912" alt="kitematic" src="https://cloud.githubusercontent.com/assets/12473996/9095598/5243cb9e-3be2-11e5-90de-85b8e87b5e68.png">

**Comment by FrenchBen** [comment]
There are quite a few images for docker-oracle-xe-11g - Can you post a link to the one you used?

**Comment by phuongtailtranminh** [comment]
@FrenchBen , It's alexeiled / docker-oracle-xe-11g

**Comment by VilhoRaatikka** [comment]
Hi, any updates on this issue? I'm facing the same.

**Comment by FrenchBen** [comment]
@VilhoRaatikka Looking at the error, it seems to be related to the image itself - Not much we can do on our end. 
Feel free to fork the repo and make the appropriate changes to get it up and working:
https://github.com/alexei-led/docker-oracle-xe-11g
