### ISSUE TITLE
Message boxes show up always on first Monitor

### ISSUE THREAD

**Issue by thomasvogel** [docker/kitematic#924]
If more than one monitor is attached to a Windows PC and kinematic is actually not running on the first one, the message boxes still show up on the first screen.

**Comment by FrenchBen** [comment]
I don't believe this is a kitematic issue but more of a mirror setting within the control panel. Did you try to tweak some of the settings?

**Comment by thomasvogel** [comment]
No, I didn't tweak anything.
Do message boxes in kitematic use "center screen" or "center app" when messagebox.show is called?
As windows developer, I often had to do with similar issues :-)

**Comment by FrenchBen** [comment]
@thomasvogel we actually use the [electron app](http://electron.atom.io/) type messages - Do you get a similar message with the Atom editor?

**Comment by FrenchBen** [comment]
Closing this issue due to the lack of activity in more than 15 days
