### ISSUE TITLE
Port publishing is lost when restarting container started with -P

### ISSUE THREAD

**Issue by djsly** [docker/kitematic#977]
How to reproduce
```
docker run -d --name cassandra01 -P cassandra:2.1.8
```
you will see in kinematic that all 5 ports are published.

```
docker restart cassandra01
```
kinematic still shows the published port same as docker ps

Now in kitematic, press stop followed by start, we are still happy, ports published. (the same is valid with the docker stop / start commands)

Finally, in kinematic, press the restart button...

:( both kinematic and docker ps shows that the list of published ports is inexistent at this point..

**Comment by FrenchBen** [comment]
#confirmed to be an issue - Thanks for filing the issue, PR should follow

**Comment by FrenchBen** [comment]
Closing as this was fixed in recent releases
