### ISSUE TITLE
Resize VM through GUI (Memory etc) 

### ISSUE THREAD

**Issue by roncanepa** [docker/kitematic#979]
Just set up kitematic on a new machine.  It really needs to ask the user how much memory it should give to the VM it will create or else set more sensible defaults.  This is a 4GB laptop for testing and throwing 2GB at the docker-vm is overkill.

**Comment by FrenchBen** [comment]
You can always resize it within the VirtualBox app  to fit your needs.  
The 2GB VM seems to be a pretty compromise for most setups and allows for smooth running containers on most machines.

With that said, there's a section in the wiki that discusses [Machine/VM Management](https://github.com/kitematic/kitematic/wiki/Machine-Management) - One of the settings would allow you to pick and choose your VM size.

**Comment by roncanepa** [comment]
Yes, I'm aware that I can resize it in virtual box and that's what I've been doing. However, that requires 1) knowing that it's possible, which given the UI nature isn't necessarily an absolute, and 2) that the entire VM start up, then get shut down manually, then edited manually.

**Comment by FrenchBen** [comment]
IMHO
1) You would know it's possible if you realized to begin with that the VM was created with 2GB. Isn't that where you looked?
2) By default the VM is shutdown when you close Kitematic, so it's really a matter of closing Kitematic, Tweak the memory in VBox then re-open Kitematic.

**Comment by roncanepa** [comment]
Considering that the point of Kitematic is to provide a GUI for people who may or may not have used docker before, and may or may not have used Virtualbox before, my main point stands.  Especially since Kitematic starts a headless virtualbox.  In addition, the option to shutdown the VM upon quitting Kitematic was NOT checked in my version that I installed today.

**Comment by FrenchBen** [comment]
@roncanepa I'm not arguing that GUI point at all and it's also why there's a complete solution spec'd out - I was merely pointing out that for most users the default amount of ram isn't a huge problem right out of the box.

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.

**Comment by jrajav** [comment]
@FrenchBen Can you please explain how, exactly? Currently here from a search and I still don't see how to change memory from Kitematic.

**Comment by FrenchBen** [comment]
@jrajav it's not in Kitematic but in the pref panel of Docker for Mac/Windows
